# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=연결 특성이 누락되었습니다.
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=디렉토리 아래에서 텍스트 파일 데이터베이스를 열 수 없음\: 

query_COMMAND_IS_EMPTY=조회 명령이 비어 있습니다.
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=교차 테이블 조회는 지원되지 않습니다.
query_COMMAND_NOT_VALID=조회 명령이 올바르지 않습니다.
query_ARGUMENT_ERROR=인수는 'NAME' 또는 'TYPE'이어야 합니다.
query_IO_EXCEPTION=파일을 읽을 때 I/O 예외가 발생했습니다.
query_SOURCE_DATA_ERROR=소스 데이터에서 중복된 열 이름을 발견했습니다.
query_COLUMN_NAME_ERROR=열 이름 오류
query_INVALID_FLAT_FILE=플랫 파일 데이터 원본이 잘못되었습니다.
query_text_error=쿼리 텍스트 서식 오류

resultSet_COLUMN_NOT_FOUND=열을 찾을 수 없음\:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=커서가 아직 초기화되지 않았습니다.

resultSetMetaData_INVALID_COLUMN_INDEX=올바르지 않은 열 색인\:

savedSelectedColumnsInfoString_INVALID=잘못 저장된 열 정보

dataTypes_TYPE_NAME_INVALID=올바르지 않은 유형 이름\:

dataSetMetaData_PRODUCT_NAME=DTP ODA 텍스트 파일 데이터 소스 제공자

common_ARGUMENT_CANNOT_BE_NULL=인수는 널(null)이 아니어야 합니다.
common_CONNECTION_HAS_NOT_OPEN=연결이 열려 있지 않습니다.
common_CANNOT_FIND_COLUMN=열을 찾을 수 없습니다.
common_NULL_QUERY_TEXT = 쿼리 텍스트가 Null입니다.

data_read_error=데이터를 정확하게 읽을 수 없습니다. 원본 데이터가 변경된 것 같습니다.

Invalid_column_name = 잘못된 열 이름

query_streamClosed=스트림의 처리가 완료되었습니다.
query_invalidTableName=올바르지 않은 테이블 이름\:

dateUtil.ConvertFails=날짜로 변환 실패 원본:
