# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=Verbindungseigenschaften fehlen.
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=Die Flachdateidatenbank unterhalb des folgenden Verzeichnisses kann nicht geöffnet werden\: 

query_COMMAND_IS_EMPTY=Der Abfragebefehl ist leer.
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=Tabellenübergreifende Abfragen werden nicht unterstützt.
query_COMMAND_NOT_VALID=Der Abfragebefehl ist ungültig.
query_ARGUMENT_ERROR=Das Argument muss 'NAME' oder 'TYPE' sein.
query_IO_EXCEPTION=Beim Lesen der Datei ist eine E/A-Ausnahmebedingung aufgetreten.
query_SOURCE_DATA_ERROR=Doppelte Spaltennamen in Quellendaten gefunden.
query_COLUMN_NAME_ERROR=Fehler bei Spaltennamen

resultSet_COLUMN_NOT_FOUND=Spalte nicht gefunden\:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=Der Cursor wurde noch nicht initialisiert.

resultSetMetaData_INVALID_COLUMN_INDEX=Ungültiger Spaltenindex\:

dataTypes_TYPE_NAME_INVALID=Ungültiger Typname\:

dataSetMetaData_PRODUCT_NAME=Datenquellenprovider für DTP-ODA-Flachdatei

common_ARGUMENT_CANNOT_BE_NULL=Argumente dürfen nicht Null sein.
common_CONNECTION_HAS_NOT_OPEN=Die Verbindung ist nicht geöffnet.
common_CANNOT_FIND_COLUMN=Keine Spalten gefunden.
query_streamClosed=Datenstrom geschlossen
query_invalidTableName=Ungültiger Tabellenname\:
