# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=接続プロパティーが欠落しています。
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=ディレクトリー下のフラット・ファイル・データベースを開くことができません。 

query_COMMAND_IS_EMPTY=QUERY コマンドが空です。
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=クロス・テーブル・クエリーはサポートされていません。
query_COMMAND_NOT_VALID=QUERY コマンドが無効です。
query_ARGUMENT_ERROR=引数は「NAME」または「TYPE」にする必要があります。
query_IO_EXCEPTION=ファイルの読み取り中に入出力例外が発生しました。
query_SOURCE_DATA_ERROR=ソース・データに重複する列名が見つかりました。
query_COLUMN_NAME_ERROR=列名のエラー
query_INVALID_FLAT_FILE=フラットファイルのデータソースは無効です。 列番号の検証を無効にするには、末尾 NULL 列を使用してください。
query_text_error=クエリテキストの書式エラー
resultSet_COLUMN_NOT_FOUND=列が見つかりません\:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=カーソルがまだ初期化されていません。

resultSetMetaData_INVALID_COLUMN_INDEX=無効な列インデックス\:

savedSelectedColumnsInfoString_INVALID=保存された列情報が無効です。

dataTypes_TYPE_NAME_INVALID=無効な型名\:

dataSetMetaData_PRODUCT_NAME=DTP ODA Flat File Data Source Provider

common_ARGUMENT_CANNOT_BE_NULL=引数は NULL にできません。
common_CONNECTION_HAS_NOT_OPEN=接続が開かれていません。
common_CANNOT_FIND_COLUMN=列が見つかりません。
common_NULL_QUERY_TEXT = クエリテキストが NULL です。

data_read_error=データを正しく読み取れません。データソースの設定が変更された可能性があります。

Invalid_column_name = 列名が無効です。

invalid_flatfile_format = フラットファイルの形式が無効です。

query_streamClosed=ストリームがクローズされました。
query_invalidTableName=無効なテーブル名\:

dateUtil.ConvertFails=日付に変換できません。 ソース :
dateFormatISO_cannotConvert={0} の値を変換できません。
