# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=缺少连接属性。
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=打不开以下目录下的平面文件数据库：

query_COMMAND_IS_EMPTY=查询命令是空的。
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=不支持交叉表查询。
query_COMMAND_NOT_VALID=查询命令无效。
query_ARGUMENT_ERROR=参数应为“NAME”或“TYPE”。
query_IO_EXCEPTION=读取文件时发生了 I/O 异常。
query_SOURCE_DATA_ERROR=在源数据中找到重复的列名。
query_COLUMN_NAME_ERROR=列名错误
query_INVALID_FLAT_FILE=平面文件数据源无效。
query_text_error=查询文本格式错误

resultSet_COLUMN_NOT_FOUND=找不到列：
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=尚未初始化游标。

resultSetMetaData_INVALID_COLUMN_INDEX=无效列索引：

savedSelectedColumnsInfoString_INVALID=无法的保存列信息

dataTypes_TYPE_NAME_INVALID=无效类型名称：

dataSetMetaData_PRODUCT_NAME=DTP ODA 平面文件数据源提供程序

common_ARGUMENT_CANNOT_BE_NULL=参数不能为空。
common_CONNECTION_HAS_NOT_OPEN=连接未打开。
common_CANNOT_FIND_COLUMN=找不到任何列。
common_NULL_QUERY_TEXT = 查询文本为空

data_read_error=无法正确读取数据，数据源设置可能已更改

Invalid_column_name = 无效的列名称

invalid_flatfile_format = 无效的平面文件格式

query_streamClosed=流已关闭
query_invalidTableName=表名无效：

dateUtil.ConvertFails=转换为日期失败。 源:
dateFormatISO_cannotConvert=无法转换 {0} 的值。
