# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=Les propriétés de connexion sont manquantes.
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=Impossible d'ouvrir la base de données du fichier à plat sous le répertoire \: 

query_COMMAND_IS_EMPTY=La commande de requête est vide.
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=La requête multi-table n'est pas prise en charge.
query_COMMAND_NOT_VALID=La commande de requête est incorrecte.
query_ARGUMENT_ERROR=L'argument doit être 'NAME' ou 'TYPE'.
query_IO_EXCEPTION=Une exception E-S s'est produite lors de la lecture du fichier.
query_SOURCE_DATA_ERROR=Des noms de colonnes en double ont été trouvées dans les données source.
query_COLUMN_NAME_ERROR=Erreur de nom de colonne

resultSet_COLUMN_NOT_FOUND=Colonne introuvable \:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=Le curseur n'a pas encore été initialisé.

resultSetMetaData_INVALID_COLUMN_INDEX=Index de colonne incorrecte \:

dataTypes_TYPE_NAME_INVALID=Nom de type incorrect \:

dataSetMetaData_PRODUCT_NAME=Fournisseur de source de données de fichier à plat DTP ODA

common_ARGUMENT_CANNOT_BE_NULL=Les arguments ne peuvent pas avoir la valeur null.
common_CONNECTION_HAS_NOT_OPEN=La connexion n'est pas établie.
common_CANNOT_FIND_COLUMN=Colonnes introuvables.
query_streamClosed=Flux fermé
query_invalidTableName=Nom de table incorrect \:
