# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=Les propriétés de connexion sont manquantes.
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=Impossible d'ouvrir la base de données du fichier à plat sous le répertoire \: 
connection_CANNOT_OPEN_FLAT_FILE_URI=Cannot open flat file from URI <{0}>, because: <{1}>.
connection_MISSING_FILELOCATION=Missing required connection properties: home folder for local flat file and URI for remote flat file. 
connection_MISSING_HOMEFOLDER=Missing required connection properties: Home folder for local flat files 
connection_MISSING_FILEURI=Missing required connection properties: File URI for remote flat file. 

query_COMMAND_IS_EMPTY=La commande de requête est vide.
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=La requête multi-table n'est pas prise en charge.
query_COMMAND_NOT_VALID=La commande de requête est incorrecte.
query_ARGUMENT_ERROR=L'argument doit être 'NAME' ou 'TYPE'.
query_IO_EXCEPTION=Une exception E-S s'est produite lors de la lecture du fichier.
query_SOURCE_DATA_ERROR=Des noms de colonnes en double ont été trouvées dans les données source.
query_COLUMN_NAME_ERROR=Erreur de nom de colonne
query_INVALID_FLAT_FILE=La source de données Flatfile est incorrecte. Utilisez les colonnes avec valeurs nulles à la fin pour désactiver la validation du nombre de colonnes.
query_text_error=Erreur de format du texte de la requête
resultSet_COLUMN_NOT_FOUND=Colonne introuvable \:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=Le curseur n'a pas encore été initialisé.

resultSetMetaData_INVALID_COLUMN_INDEX=Index de colonne incorrecte \:

savedSelectedColumnsInfoString_INVALID=Informations de colonnes enregistrées incorrectes

dataTypes_TYPE_NAME_INVALID=Nom de type incorrect \:

dataSetMetaData_PRODUCT_NAME=Fournisseur de source de données de fichier à plat DTP ODA

common_ARGUMENT_CANNOT_BE_NULL=Les arguments ne peuvent pas avoir la valeur null.
common_CONNECTION_HAS_NOT_OPEN=La connexion n'est pas établie.
common_CANNOT_FIND_COLUMN=Colonnes introuvables.
common_NULL_QUERY_TEXT = La valeur du texte de la requête est nulle

data_read_error=Impossible de lire les données correctement, les paramètres de la source de données ont probablement été modifiés

Invalid_column_name = Nom de colonne incorrect

invalid_flatfile_format = Format de fichier plat incorrect

query_streamClosed=Flux fermé
query_invalidTableName=Nom de table incorrect \:

dateUtil.ConvertFails=Echec de la conversion en date. Source :
dateFormatISO_cannotConvert=Impossible de convertir la valeur de {0}.
