# Exception messages for the Oda Flat File Driver

connection_CONNECTION_PROPERTIES_MISSING=Faltan las propiedades de conexión.
connection_CANNOT_OPEN_FLAT_FILE_DB_DIR=No se puede abrir la base de datos del archivo plano bajo el directorio\: 

query_COMMAND_IS_EMPTY=El mandato de consulta está vacío.
query_DO_NOT_SUPPORT_CROSS_TABLE_QUERY=La consulta de tabla cruzada no está soportada.
query_COMMAND_NOT_VALID=El mandato de consulta no es válido.
query_ARGUMENT_ERROR=El argumento debe ser 'NAME' o 'TYPE'.
query_IO_EXCEPTION=Se ha producido una excepción de E/S al leer el archivo.
query_SOURCE_DATA_ERROR=Se han encontrado nombres de columna duplicados en los datos fuente.
query_COLUMN_NAME_ERROR=Error de nombre de columna
query_INVALID_FLAT_FILE=La fuente de datos de archivo sin formato no es válida.

resultSet_COLUMN_NOT_FOUND=No se ha encontrado la columna\:
resultSet_CURSOR_HAS_NOT_BEEN_INITIALIZED=El cursor todavía no se ha inicializado.

resultSetMetaData_INVALID_COLUMN_INDEX=Índice de columna no válido\:

dataTypes_TYPE_NAME_INVALID=Nombre de tipo no válido\:

dataSetMetaData_PRODUCT_NAME=Proveedor de origen de datos de archivo plano de ODA de DTP

common_ARGUMENT_CANNOT_BE_NULL=Los argumentos no pueden ser nulos.
common_CONNECTION_HAS_NOT_OPEN=La conexión no está abierta.
common_CANNOT_FIND_COLUMN=No se puede encontrar columnas.
query_streamClosed=Corriente cerrada
query_invalidTableName=Nombre de tabla no válido\:

dateUtil.ConvertFails=Error al convertir la fecha. Fuente:
