Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse 数据工具平台 HSQLDB 启用插件

navigator.content.name = HSQLDB 配置文件内容扩展

connection.factory = HSQLDB 连接工厂
connection.profile = HSQLDB 连接配置文件

driver.category.name = HSQLDB
driver.category.description = HSQ  JDBC 驱动程序
driver.version.category.name = 1.8
driver.version.category.description = 用于 V1.8 的 HSQLDB JDBC 驱动程序
driver.name = HSQLDB JDBC 驱动程序
driver.description = 用于 HSQLDB 的 JDBC 驱动程序

DRIVER_CLASS_PROPERTY_NAME=驱动程序类
VENDOR_PROPERTY_NAME=供应商
VERSION_PROPERTY_NAME=版本
DATABASE_NAME_PROPERTY_NAME=数据库名称
CONNECTION_URL_PROPERTY_NAME=连接 URL
USER_ID_PROPERTY_NAME=用户 ID

