Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB 사용 플러그인

navigator.content.name = HSQLDB 프로필 콘텐츠 확장명

connection.factory = HSQLDB 연결 팩토리
connection.profile = HSQLDB 연결 프로필

driver.category.name = HSQLDB
driver.category.description = HSQLDB JDBC 드라이버
driver.version.category.name = 1.8
driver.version.category.description = 버전 1.8용 HSQLDB JDBC 드라이버
driver.name = HSQLDB JDBC 드라이버
driver.description = HSQLDB용 JDBC 드라이버

DRIVER_CLASS_PROPERTY_NAME=드라이버 클래스
VENDOR_PROPERTY_NAME=공급업체
VERSION_PROPERTY_NAME=버전
DATABASE_NAME_PROPERTY_NAME=데이터베이스 이름
CONNECTION_URL_PROPERTY_NAME=연결 URL
USER_ID_PROPERTY_NAME=사용자 ID

