Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse-Datentools-Plattform HSQLDB Enablement Plug-In

navigator.content.name = HSQLDB Profil-Content-Extension

connection.factory = HSQLDB Verbindungs-Factory
connection.profile = HSQLDB Verbindungsprofil

driver.category.name = HSQLDB
driver.category.description = HSQLDB JDBC-Treiber
driver.version.category.name = 1.8
driver.version.category.description = HSQLDB JDBC-Treiber für Version 1.8
driver.name = HSQLDB JDBC-Treiber
driver.description = JDBC-Treiber für HSQLDB

DRIVER_CLASS_PROPERTY_NAME=Treiberklasse
VENDOR_PROPERTY_NAME=Anbieter
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Datenbankname
CONNECTION_URL_PROPERTY_NAME=Verbindungs-URL
USER_ID_PROPERTY_NAME=Benutzer-ID

