Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB Enablement Plug-in

navigator.content.name = HSQLDB プロファイルコンテンツの拡張

connection.factory = HSQLDB 接続ファクトリ
connection.profile = HSQLDB 接続プロファイル

driver.category.name = HSQLDB
driver.category.description = HSQLDB JDBC ドライバ
driver.version.category.name = 1.8
driver.version.category.description = HSQLDB JDBC Drivers for Version 1.8
driver.name = HSQLDB JDBC ドライバ
driver.description = HSQLDB 用の JDBC ドライバ

DRIVER_CLASS_PROPERTY_NAME=ドライバクラス
VENDOR_PROPERTY_NAME=ベンダ
VERSION_PROPERTY_NAME=バージョン
DATABASE_NAME_PROPERTY_NAME=データベース名
CONNECTION_URL_PROPERTY_NAME=接続 URL
USER_ID_PROPERTY_NAME=ユーザ ID

