Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Plug-in d'habilitation HSQLDB pour plate-forme d'outils de données Eclipse

navigator.content.name = Extension de contenu de profil HSQLDB

connection.factory = Génération de connexion HSQLDB
connection.profile = Profil de connexion HSQLDB

driver.category.name = HSQLDB
driver.category.description = Pilotes JDBC HSQLDB
driver.version.category.name = 1.8
driver.version.category.description = Pilotes JDBC HSQLDB pour Version 1.8
driver.name = Pilote JDBC HSQLDB
driver.description = Pilote JDBC pour HSQLDB

DRIVER_CLASS_PROPERTY_NAME=Classe de pilote
VENDOR_PROPERTY_NAME=Vendeur
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Nom de la base de données
CONNECTION_URL_PROPERTY_NAME=URL de connexion
USER_ID_PROPERTY_NAME=ID utilisateur

