Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Complemento de activación de HSQLDB para Eclipse Data Tools Platform

navigator.content.name = Extensión de contenido del perfil de HSQLDB

connection.factory = Fábrica de conexión HSQLDB
connection.profile = Perfil de conexión HSQLDB

driver.category.name = HSQLDB
driver.category.description = Controladores JDBC de HSQLDB
driver.version.category.name = 1.8
driver.version.category.description = Controladores JDBC de HSQLDB para versión 1.8
driver.name = Controlador JDBC de HSQLDB
driver.description = Controlador JDBC para HSQLDB

DRIVER_CLASS_PROPERTY_NAME=Clase de controlador
VENDOR_PROPERTY_NAME=Proveedor
VERSION_PROPERTY_NAME=Versión
DATABASE_NAME_PROPERTY_NAME=Nombre de base de datos
CONNECTION_URL_PROPERTY_NAME=URL de conexión
USER_ID_PROPERTY_NAME=Identificador de usuario

