# Copyright (c) 2005, 2012 Actuate Corporation.
constants_componentName=DTP 열린 데이터 액세스
profileFileExtension_APPLIED_DEFAULT_FILE_EXT={2}의 {1} 확장명에 의해 제공된 기본 파일 확장명({0}) 적용
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND={0} 확장점의 여러 개의 확장명을 찾았습니다.  이 중 하나의 확장명만 적용됩니다.
propertyProvider_CANNOT_FIND_PROFILE=프로필 저장소 경로({1})에서 명명된 프로필({0})을 찾을 수 없거나 이에 액세스할 수 없습니다.
propertyProvider_NO_RESOURCE_IDENTIFIERS=연결 프로필 저장소 파일의 상대 경로({0})를 확인할 수 있는 AppContext에서 제공되는 ResourceIdentifiers가 없습니다.
propertyProvider_UNABLE_TO_RESOLVE_PATH=AppContext에서 제공되는 ResourceIdentifiers({0})는 연결 프로필 저장소 파일의 상대 경로({1})를 확인할 수 없습니다.\n파일이 응용 프로그램 리소스 폴더 {2}에 위치하는지 확인하십시오.
