# Copyright (c) 2005, 2012 Actuate Corporation.
constants_componentName=Accès aux données ouvertes DTP
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Extension de fichier ({0}) appliquée par défaut, contribution apportée par l'extension {1} dans {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Plusieurs extensions du point d'extension {0} ont été détectées.  Une seule extension sera appliquée.
propertyProvider_CANNOT_FIND_PROFILE=Impossible de trouver le profil spécifié ({0}) ou d'y accéder à l'emplacement de stockage des profils ({1}).
propertyProvider_NO_RESOURCE_IDENTIFIERS=Aucun ResourceIdentifiers disponible dans l'appContext pour résoudre le chemin d'accès relatif du fichier de stockage des profils de connexion ({0}).
propertyProvider_UNABLE_TO_RESOLVE_PATH=Le ResourceIdentifiers ({0}) fourni dans l'appContext n'a pas pu résoudre le chemin relatif du fichier de stockage des profils de connexion ({1}). \nVérifiez que le fichier se trouve dans le dossier des ressources de l'application : {2}
