# Copyright (c) 2005, 2012 Actuate Corporation.
constants_componentName=DTP オープンデータアクセス
profileFileExtension_APPLIED_DEFAULT_FILE_EXT={2} 内の {1} 拡張によって提供されたデフォルトのファイル拡張子 ({0}) が適用されました。
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND={0} 拡張ポイントの複数の拡張子が見つかりました。  いずれか 1 つのみが適用されます。
propertyProvider_CANNOT_FIND_PROFILE=プロファイルストアのパス ({1}) で名前付きプロファイル ({0}) を検索またはアクセスできません。
propertyProvider_NO_RESOURCE_IDENTIFIERS=接続プロファイルストアファイルの相対パス ({0}) を解決するための使用可能な ResourceIdentifiers が AppContext 内にありません。
propertyProvider_UNABLE_TO_RESOLVE_PATH=AppContext で指定されている ResourceIdentifiers ({0}) は、接続プロファイルストアファイルの相対パス ({1}) を解決できませんでした。\nファイルがアプリケーションのリソースフォルダの下にあることを確認してください: {2}
