# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP 열린 데이터 액세스
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=프로필 저장소 경로({1})에서 명명된 프로필({0})을 찾을 수 없거나 이에 액세스할 수 없습니다.
propertyProvider_UNABLE_TO_RESOLVE_PATH=AppContext에서 제공되는 ResourceIdentifiers({0})는 연결 프로필 저장소 파일의 상대 경로를 확인할 수 없습니다((1}).
