# Copyright (c) 2005, 2012 Actuate Corporation.
constants_componentName=DTP 开放式数据访问
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=已应用 {2} 中的 {1} 扩展提供的默认文件扩展名({0})。
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=找到 {0} 扩展点的多个扩展。  将仅应用其中一个。
propertyProvider_CANNOT_FIND_PROFILE=在配置文件存储路径({1})中无法找到或访问指定配置文件({0})。
propertyProvider_NO_RESOURCE_IDENTIFIERS=appContext 中无法找到任何 ResourceIdentifiers 来解析连接配置文件存储文件的相对路径 ({0})。
propertyProvider_UNABLE_TO_RESOLVE_PATH=appContext 中提供的 ResourceIdentifiers ({0}) 无法解析连接配置文件存储文件的相对路径 ({1})。\n请检查该文件位于应用程序资源文件夹下: {2}
