# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP Open-Datenzugriff
propertyProvider_CANNOT_FIND_PROFILE=Benanntes Profil ({0}) wird im Profilspeicherpfad ({1}) nicht gefunden, oder es kann nicht darauf zugegriffen werden.
propertyProvider_UNABLE_TO_RESOLVE_PATH=The ResourceIdentifiers ({0}) provided in the appContext was unable to resolve the connection profile store file's relative path ((1}).
