# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP 开放式数据访问
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=在配置文件存储路径({1})中无法找到或访问指定配置文件({0})。
propertyProvider_UNABLE_TO_RESOLVE_PATH=在 appContext 中提供的 ResourceIdentifiers ({0})无法解析连接配置文件存储文件的相对路径((1})。
