# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=Accès aux données ouvertes DTP
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=Impossible de trouver le profil spécifié ({0}) ou d'y accéder à l'emplacement de stockage des profils ({1}).
propertyProvider_UNABLE_TO_RESOLVE_PATH=The ResourceIdentifiers ({0}) provided in the appContext was unable to resolve the connection profile store file's relative path ((1}).
