# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP Open-Datenzugriff
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=Benanntes Profil ({0}) wird im Profilspeicherpfad ({1}) nicht gefunden, oder es kann nicht darauf zugegriffen werden.
propertyProvider_UNABLE_TO_RESOLVE_PATH=Die in AppContext angegebene ResourceIdentifiers ({0}) konnte den relativen Pfad der Verbindungsprofilspeicherdatei ((1}) nicht auflösen.
