# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=Acceso de datos abierto de DTP
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=No es posible encontrar ni acceder al perfil con nombre ({0}) en la ruta de almacenamiento de perfil ({1}).
propertyProvider_UNABLE_TO_RESOLVE_PATH=El ResourceIdentifiers ({0}) proporcionado en appContext no ha podido resolver la ruta relativa del archivo de almacenamiento del perfil de conexión ((1}).
