# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP オープンデータアクセス
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Applied the default file extension ({0}) contributed by the {1} extension in {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Multiple extensions of the {0} extension point are found.  Only one of them will be applied.
propertyProvider_CANNOT_FIND_PROFILE=プロファイルストアのパス ({1}) で名前付きプロファイル ({0}) を検索またはアクセスできません。
propertyProvider_UNABLE_TO_RESOLVE_PATH=AppContext で指定されている ResourceIdentifiers ({0}) は、接続プロファイルストアファイルの相対パス ({1}) を解決できませんでした。
