# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=Acceso de datos abierto de DTP
propertyProvider_CANNOT_FIND_PROFILE=No es posible encontrar ni acceder al perfil con nombre ({0}) en la ruta de almacenamiento de perfil ({1}).
propertyProvider_UNABLE_TO_RESOLVE_PATH=The ResourceIdentifiers ({0}) provided in the appContext was unable to resolve the connection profile store file's relative path ((1}).
