# Copyright (c) 2005, 2011 Actuate Corporation.
constants_componentName=DTP Open-Datenzugriff
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Die von der {1} Erweiterung in {2} beigetragene Standard-Dateierweiterung ({0}) wurde angewendet.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Es wurden mehrere Erweiterungen des {0} Erweiterungspunkts gefunden.  Nur eine von ihnen wird angewendet.
propertyProvider_CANNOT_FIND_PROFILE=Benanntes Profil ({0}) wird im Profilspeicherpfad ({1}) nicht gefunden, oder es kann nicht darauf zugegriffen werden.
propertyProvider_UNABLE_TO_RESOLVE_PATH=Die in AppContext angegebene ResourceIdentifiers ({0}) konnte den relativen Pfad der Verbindungsprofilspeicherdatei ((1}) nicht auflösen.
