# Copyright (c) 2005, 2012 Actuate Corporation.
constants_componentName=Acceso de datos abierto de DTP
profileFileExtension_APPLIED_DEFAULT_FILE_EXT=Se ha aplicado la extensión de archivo predeterminada ({0}) proporcionada por la extensión {1} en {2}.
profileFileExtension_MULTIPLE_EXTENSIONS_FOUND=Se han encontrado varias extensiones del punto de extensión {0}.  Sólo se aplicará una de ellas.
propertyProvider_CANNOT_FIND_PROFILE=No es posible encontrar ni acceder al perfil con nombre ({0}) en la ruta de almacenamiento de perfil ({1}).
propertyProvider_NO_RESOURCE_IDENTIFIERS=No hay ningún ResourceIdentifiers disponible en appContext para resolver la ruta relativa del archivo de almacenamiento del perfil de conexión ({0}).
propertyProvider_UNABLE_TO_RESOLVE_PATH=El ResourceIdentifiers ({0}) proporcionado en appContext no ha podido resolver la ruta relativa del archivo de almacenamiento del perfil de conexión ((1}).\nCompruebe que el archivo se encuentra en la carpeta de recursos de la aplicación: {2}
