###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB iSeries Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
driverUID = Identificador de usuario
driverPWD = Contraseña

DB2_UDB_ISERIES_CATEGORY_NAME = DB2 para i5/OS

org.eclipse.datatools.enablement.ibm.db2.iseries.driverTemplate = Controlador de servidor de datos de IBM para JDBC y SQLJ
org.eclipse.datatools.enablement.ibm.db2.iseries.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.ibm.db2.iseries.toolbox.driverTemplate = AS/400 Toolbox para Java

jdbc.connection.name = Conexión JDBC
profile.db2.iseries.title = DB2 para i5/OS
