###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Oracle UI Plug-in
providerName=Eclipse Data Tools Platform

profile.oracle.wizard.title = Oracle
profile.oracle.wizard.description = Oracle の接続プロファイルを作成します。
profile.oracle.properties = ドライバのプロパティ
