###############################################################################
# Copyright (c) 2006 - 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Oracle Plug-in
providerName=Eclipse.org

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
catalogType = 카탈로그
driverUID = 사용자 ID
driverPWD = 암호

ORACLE_CATEGORY_NAME = Oracle
11_VERSION_CATEGORY_NAME = 11
10_VERSION_CATEGORY_NAME = 10
9_VERSION_CATEGORY_NAME = 9
8_VERSION_CATEGORY_NAME = 8

org.eclipse.datatools.enablement.oracle.11.driverTemplate = Oracle Thin 드라이버
org.eclipse.datatools.enablement.oracle.10.driverTemplate = Oracle Thin 드라이버
org.eclipse.datatools.enablement.oracle.9.driverTemplate = Oracle Thin 드라이버
org.eclipse.datatools.enablement.oracle.8.driverTemplate = Oracle Thin 드라이버
org.eclipse.datatools.enablement.oracle.11.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.oracle.10.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.oracle.9.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.oracle.8.other.driverTemplate = 기타 드라이버

jdbc.connection.name = JDBC 연결
profile.oracle.title = Oracle
