###############################################################################
# Copyright (c) 2006 - 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Oracle Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
catalogType = Catálogo
driverUID = Identificador de usuario
driverPWD = Contraseña

ORACLE_CATEGORY_NAME = Oracle
11_VERSION_CATEGORY_NAME = 11
10_VERSION_CATEGORY_NAME = 10
9_VERSION_CATEGORY_NAME = 9
8_VERSION_CATEGORY_NAME = 8

org.eclipse.datatools.enablement.oracle.11.driverTemplate = Controlador de Oracle Thin
org.eclipse.datatools.enablement.oracle.10.driverTemplate = Controlador de Oracle Thin
org.eclipse.datatools.enablement.oracle.9.driverTemplate = Controlador de Oracle Thin
org.eclipse.datatools.enablement.oracle.8.driverTemplate = Controlador de Oracle Thin
org.eclipse.datatools.enablement.oracle.11.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.oracle.10.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.oracle.9.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.oracle.8.other.driverTemplate = Otro controlador

jdbc.connection.name = Conexión JDBC
profile.oracle.title = Oracle
