###############################################################################
# Copyright (c) 2006 - 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Oracle Plug-in
providerName=Eclipse Data Tools Platform

driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
catalogType = カタログ
driverUID = ユーザ ID
driverPWD = パスワード

ORACLE_CATEGORY_NAME = Oracle
11_VERSION_CATEGORY_NAME = 11
10_VERSION_CATEGORY_NAME = 10
9_VERSION_CATEGORY_NAME = 9
8_VERSION_CATEGORY_NAME = 8

org.eclipse.datatools.enablement.oracle.11.driverTemplate = Oracle Thin Driver
org.eclipse.datatools.enablement.oracle.10.driverTemplate = Oracle Thin Driver
org.eclipse.datatools.enablement.oracle.9.driverTemplate = Oracle Thin Driver
org.eclipse.datatools.enablement.oracle.8.driverTemplate = Oracle Thin Driver
org.eclipse.datatools.enablement.oracle.11.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.oracle.10.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.oracle.9.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.oracle.8.other.driverTemplate = その他のドライバ

jdbc.connection.name = JDBC 接続
profile.oracle.title = Oracle
