################################################################################
## Copyright (c) 2005, 2008 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
##	  IBM Corporation = bug fix #203829
################################################################################ 
plugin.internal_error=Erreur interne - org.eclipse.datatools.connectivity
ImportProfilesDialog.btnOverwrite.text=&Remplacer les profils de connexion existants s'ils portent le même nom
ExportProfilesDialog.button.text2=&Parcourir...
ExportProfilesDialog.group.text=Sélectionnez les profils de connexion à exporter \:
ExportProfilesDialog.button.text1=&Désélectionner tout
ExportProfilesDialog.button.text=&Sélectionner tout
ImportProfilesDialog.button.text=&Parcourir...
ExportProfilesDialog.label.text=Indiquez un nom de &fichier \:
ImportProfilesDialog.label.text=Indiquez un nom de &fichier \:
ImportProfilesDialog.text.text=Remarque \: le profil de connexion à importer doit être du type de ceux que vous pouvez\n créer à l'aide de l'assistant Nouveau profil de connexion. Les types de profil de connexion non pris en charge \n seront refusés.
ExportProfilesDialog.null.title=Exportation des profils de connexion
ImportProfilesDialog.null.title=Importation des profils de connexion
ExportProfilesDialog.btnEncryption.text=Chiffrer le contenu du fichier
actions.export.noselection=Sélectionnez au moins un profil de connexion \!
actions.export.nofile=Indiquez un nom de fichier \!
actions.export.norepository = Spécifiez un référentiel cible.
actions.export.notvalidfile = Spécifiez un chemin et un nom de fichier corrects.
dialog.exception.title=Exception
dialog.exception.message=Exception \: {0}
NewCPWizard.title=Nouveau profil de connexion
IntroductionWizardPage.title=Page d'introduction
IntroductionWizardPage.intro=Cet assistant vous guide à travers les étapes requises pour créer un profil de connexion.
CPWizardSelectionPage.title = Profil de connexion
CPWizardSelectionPage.desc = Sélectionnez un type de profil de connexion.
CPWizardSelectionPage.group = Types de profils de &connexion :
CPWizardSelectionPage.defaultName =Nouveau {0}
CPWizardSelectionPage.defaultNameExtended =New {0}({1})
actions.connect.job=Tâche de connexion au serveur
actions.connect.uijob=Régénération de la vue
actions.ping.job=Tâche de ping du serveur
actions.ping.uijob=Tâche Afficher la boîte de dialogue
actions.connect.title=Connexion au serveur...
actions.ping.title=Test de ping du serveur...
actions.ping.success=Ping réussi \!
actions.ping.failure=Echec du ping \!
actions.delete.title=Confirmation de la suppression
actions.delete.confirm=Voulez-vous vraiment supprimer le profil de connexion "{0}" ?
properties.dialog=Boîte de dialogue des propriétés
properties.category.general=Généralités
properties.connectionprofile.name=Nom du profil
properties.connectionprofile.desc=Description
properties.connectionprofile.autoconnect=Connexion automatique
properties.category.name=Nom de la catégorie
properties.category.id=ID de catégorie
ServersView.action.showproperties=&Propriétés
ServersView.action.refresh=&Régénérer
ServersView.action.newCP=&Nouveau...
ServersView.action.exportCPs=&Exporter...
ServersView.action.importCPs=&Importer...
NewConnectionProfileWizard.title=Nouveau profil de connexion
NewConnectionProfileWizard.create.failure=Echec de la création du profil de connexion
NewConnectionProfileWizardPage.Status.DuplicateName=Le nom du profil de connexion existe déjà \!
NewConnectionProfileWizardPage.Status.NoName=Indiquez un nom de profil de connexion \!
NewConnectionProfileWizardPage.Status.NoRepository = Spécifiez un référentiel.
NewConnectionProfileWizardPage.title = Créer un profil de connexion
NewConnectionProfileWizardPage.desc = Saisissez les informations de profil.
NewConnectionProfileWizardPage.cp_name = No&m :
NewConnectionProfileWizardPage.cp_desc = &Description (facultatif) :
NewConnectionProfileWizardPage.choices=Veuillez sélectionner \:
NewConnectionProfileWizardPage.summary_cp_name=Nom
NewConnectionProfileWizardPage.summary_cp_desc=Description
NewConnectionProfileWizardPage.Button.AutoConnect = Connexion &automatique au démarrage
NewConnectionProfileWizardPage.Button.AutoConnect1 = Connexion automatique au démarrage.
NewConnectionProfileWizardPage.summary_autoconnect = Connexion automatique au démarrage
NewConnectionProfileWizardPage.summary_autoconnect_on_finish = Connexion automatique à la fin
NewConnectionProfileWizardPage.localRepository = Créer dans le référentiel d'espace de travail (local)
NewConnectionProfileWizardPage.chooseRepository = Choisissez un référentiel :
ConnectionProfileDetailsPage.Button.TestConnection=&Tester la connexion
ConnectionProfileDetailsPage.AskConfirmation=Boîte de dialogue de confirmation
ConnectionProfileDetailsPage.AskReconnect=Les informations de connexion de ce profil de connexion ont été modifiées. Voulez-vous vous reconnecter au serveur ?
SummaryWizardPage.title=Récapitulatif
SummaryWizardPage.description=Informations émanant des pages précédentes.
SummaryWizardPage.property=Propriété
SummaryWizardPage.value=Valeur
dialog.title.error=Erreur
dialog.title.success=Réussite
rename.dialog.title=Boîte de dialogue Attribution d'un nouveau nom
rename.dialog.message=Indiquez un nouveau nom de profil de connexion \:
rename.dialog.errmsg.existing=Le nom existe déjà. Indiquez un autre nom \!
rename.dialog.errmsg.invalid=Nom incorrect. Indiquez un nom correct \!
error.connect={1}.  Pour plus de détails, consultez le fichier de consignation.
error.contentExtension=Erreur de connexion à l''extension "{0}" sur le profil "{1}" (Erreur \: {2})
CPVersionPropertyPage.desc=Informations relatives à la version de {0}.\nCes informations ont été obtenues lors de la dernière tentative de connexion.  Si la dernière tentative de connexion a échoué, aucune information relative à la version ne seront disponibles.
CPVersionPropertyPage.button.updateVersion=Se connecter et mettre à jour les informations sur la version
CPVersionPropertyPage.label.versionUnavailable=Les informations relatives à la version ne sont pas disponibles pour ce profil.
CPVersionPropertyPage.label.techVersions=Ce serveur comporte les technologies suivantes \:
ConnectionProfileSummaryPage.button.testConnection=&Tester la connexion
CommonLabelProviderBase.label.version=v.
CommonLabelProviderBase.label.version.versionless={0} ({1}) 
CommonLabelProviderBase.label.localRepository=Référentiel d'espace de travail (local)

properties.connectionprofile.type = Type de profil
DSE.Refresh.label = &Actualiser

CPDeleteChange.name = Supprimer le profil de connexion {0}
CPDeleteChange.error.ProfileDoesNotExist = Le profil de connexion que vous essayez de supprimer n'existe pas.
CPDeleteChange.delete.failure = Echec de la suppression du profil de connexion.
CPDeleteProcessor.name = Processeur de suppression de connectivité DTP
CPDuplicateProcessor.name = Processeur de duplication de profil de connexion DTP
CPCopyChange.name = Dupliquer le profil de connexion {0}
CPCopyChange.error.ProfileDoesNotExist = Le profil de connexion que vous essayez de dupliquer n'existe pas.
CPCopyChange.title.error = Echec de la duplication du profil de connexion.
CPCopyChange.error.InvalidTarget = La cible spécifiée n'est pas un référentiel de profils de connexion valide.
CPCopyChange.error.RepositoryNotConnected = Non connecté au référentiel de profils de connexion cible {0}.
CPMoveProcessor.name = Processeur de déplacement de profil de connexion DTP
CPMoveChange.name = Déplacer le profil de connexion {0}
CPMoveChange.error.ProfileDoesNotExist = Le profil de connexion que vous essayez de déplacer n'existe pas.
CPMoveChange.title.error = Echec du déplacement du profil de connexion.
CPCreateChange.name = Créer le profil de connexion {0}
CPCreateChange.error.NewProfileDoesNotHaveName = Un nom est requis pour la création du nouveau profil de connexion.
CPCreateChange.error.NewProfileAlreadyExists = Un profil de connexion portant le nouveau nom existe déjà.
CPCreateChange.error.NewProfileDoesNotHaveProviderID = Un ID de fournisseur de profils de connexion est requis pour la création du nouveau profil de connexion.
CPCreateChange.error.NewProfileDoesNotHaveNonNullPropertiesObject = Un objet de propriétés non nul est requis pour la création du nouveau profil de connexion.
CPCreateChange.create.failure = Echec de la création du profil de connexion.
CPCreateProcessor.name = Processeur de création de connectivité DTP
CPRenameChange.name = Renommer le profil de connexion {0}
CPRenameProcessor.name = Processeur de réattribution de nom de connectivité DTP
CPRenameChange.title.error = Echec de la réattribution d'un nom au profil de connexion.

PropertyDescriptor.error.title = Erreur lors du traitement du descripteur de propriété pour la définition de pilote
PropertyDescriptor.error.msg = Erreur lors du traitement des propriétés de définition du pilote.
PasswordTextPropertyDescriptor.property.label = Mot de passe
DriverClassBrowsePropertyDescriptor.property.label = Classe de pilote
DriverClassBrowsePropertyDescriptor.jardialog.title = Classes disponibles à partir de la liste Jar
DriverClassBrowsePropertyDescriptor.jardialog.msg = Indiquez le nom de la classe de pilote ou sélectionnez une classe parmi les JAR disponibles.
DriverClassBrowsePropertyDescriptor.noclasses.title = Aucune classe de pilote disponible
DriverClassBrowsePropertyDescriptor.noclasses.msg = Aucune classe de pilote disponible pour la liste jar en cours.

StatusBar.Connected = Connecté
StatusBar.Disconnected = Déconnecté
StatusBar.ConnectedMessage = {0} ({1})

StatusBar.WorkingOffline = Travail hors ligne

DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE = &Travailler hors ligne
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE = &Enregistrer hors ligne

DriverPropertyEditorDescriptor.InvalidID = ID valide manquant pour le descripteur de l'éditeur de propriété du pilote
DriverPropertyEditorDescriptor.InvalidTargetTemplateID = ID de modèle cible valide manquant pour le descripteur de l'éditeur de propriété du pilote
DriverPropertyEditorDescriptor.InvalidTargetPropertyId = ID de propriété cible valide manquant pour le descripteur de l'éditeur de propriété du pilote
DriverPropertyEditorDescriptor.InvalidCustomPropertyEditorClass = Editeur de propriété personnalisé valide manquant pour le descripteur de l'éditeur de propriété du pilote

ExtensibleProfileDetailsWizardPage.title = Spécifiez un lecteur et les informations de connexion
ExtensibleProfileDetailsWizardPage.description = Dans le menu déroulant, sélectionnez un lecteur et fournissez les informations de connexion.
ExtensibleProfileDetailsWizardPage.driverCombo.label = &Lecteurs :
ExtensibleNewConnectionProfileWizard.title = Nouveau profil de connexion

DriverUIContributorComposite.group = &Propriétés

OtherDriverUIContributor.generaltab = Général
OtherDriverUIContributor.optionaltab = Facultatif
OtherDriverUIContributor.databaseName.label = B&ase de données :
OtherDriverUIContributor.url.label = &URL :
OtherDriverUIContributor.userName.label = Nom d'utili&sateur :
OtherDriverUIContributor.password.label = &Mot de passe :
OtherDriverUIContributor.savePassword.label = Enregistre&r mot de passe
OtherDriverUIContributor.optionalProps.label = Propriétés supplémentaires :
OtherDriverUIContributor.summaryData.database = Base de données
OtherDriverUIContributor.summaryData.username = Nom d'utilisateur
OtherDriverUIContributor.summaryData.savePassword = Enregistrer mot de passe
OtherDriverUIContributor.summaryData.true = vrai
OtherDriverUIContributor.summaryData.false = faux
OtherDriverUIContributor.summaryData.url = URL

OtherDriverUIContributor.errormessage.requiresdatabase = Entrez un nom pour la base de données.
OtherDriverUIContributor.errormessage.requiresurl = Entrez une URL.
OtherDriverUIContributor.errormessage.requiresusername = Entrez un nom d'utilisateur.

ConnectAction.title = Propriétés de {0}

