## Copyright (c) 2005, 2009 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
##	  IBM Corporation = bug fix #203829
##	  Actuate Corporation - bug fix #261452
################################################################################ 
plugin.internal_error=Interner Fehler - org.eclipse.datatools.connectivity
ImportProfilesDialog.btnOverwrite.text=&Vorhandene Verbindungsprofile gleichen Namens überschreiben
ExportProfilesDialog.button.text2=Dur&chsuchen...
ExportProfilesDialog.group.text=Zu exportierendes Verbindungsprofil auswählen\:
ExportProfilesDialog.button.text1=Alles a&bwählen
ExportProfilesDialog.button.text=Alles a&uswählen
ImportProfilesDialog.button.text=Dur&chsuchen...
ExportProfilesDialog.label.text=&Dateinamen angeben\:
ImportProfilesDialog.label.text=&Dateinamen angeben\:
ImportProfilesDialog.text.text=Hinweis\: Das Verbindungsprofil für den Import muss von einem Typ sein,\nder mithilfe des neuen Verbindungsprofilassistenten erstellt werden kann.\nNicht unterstützte Verbindungsprofiltypen werden verworfen.
ExportProfilesDialog.null.title=Verbindungsprofile exportieren
ImportProfilesDialog.null.title=Verbindungsprofile importieren
ExportProfilesDialog.btnEncryption.text=Dateiinhalt &verschlüsseln
actions.export.noselection=Bitte wählen Sie mindestens ein Verbindungsprofil aus\!
actions.export.nofile=Bitte geben Sie den Dateinamen an\!
actions.export.norepository = Geben Sie ein Ziel-Repository an.
actions.export.notvalidfile = Geben Sie einen gültigen Dateinamen und Pfad an.
dialog.exception.title=Ausnahmebedingung
dialog.exception.message=Abgefangene Ausnahmebedingung\: {0}
NewCPWizard.title=Neues Verbindungsprofil
IntroductionWizardPage.title=Einführungsseite
IntroductionWizardPage.intro=Dieser Assistent führt Sie durch die Erstellung eines Verbindungsprofils.
CPWizardSelectionPage.title = Verbindungsprofil
CPWizardSelectionPage.desc = Wählen Sie einen Verbindungsprofiltyp.
CPWizardSelectionPage.group = &Verbindungsprofiltypen:
CPWizardSelectionPage.defaultName =Neu: {0}
CPWizardSelectionPage.defaultNameExtended =Neu: {0}({1})
actions.connect.job=Serverjob verbinden
actions.connect.uijob=Sicht aktualisieren
actions.ping.job=Serverjob mit Ping überprüfen
actions.ping.uijob=Dialogjob anzeigen
actions.connect.title=Verbindung zum Server wird hergestellt...
actions.ping.title=Server wird mit Ping überprüft...
actions.ping.success=Überprüfung mit Ping erfolgreich\!
actions.ping.failure=Überprüfung mit Ping fehlgeschlagen\!
actions.delete.title=Löschen bestätigen
actions.delete.confirm=Soll das Verbindungsprofil "{0}" wirklich gelöscht werden?
properties.dialog=Eigenschaftendialog
properties.category.general=Allgemein
properties.connectionprofile.name=Profilname
properties.connectionprofile.desc=Beschreibung
properties.connectionprofile.autoconnect=Automatisch verbinden
properties.category.name=Kategoriename
properties.category.id=Kategorie-ID
ServersView.action.showproperties=&Eigenschaften
ServersView.action.refresh=&Aktualisieren
ServersView.action.newCP=&Neu...
ServersView.action.exportCPs=&Exportieren...
ServersView.action.importCPs=&Importieren...
NewConnectionProfileWizard.title=Neues Verbindungsprofil
NewConnectionProfileWizard.create.failure=Fehler bei Verbindungsprofilerstellung
NewConnectionProfileWizardPage.Status.DuplicateName=Der Name des Verbindungsprofils ist bereits vorhanden\!
NewConnectionProfileWizardPage.Status.NoName=Bitte geben Sie den Namen des Verbindungsprofils an\!
NewConnectionProfileWizardPage.Status.NoRepository = Geben Sie ein Repository an.
NewConnectionProfileWizardPage.Status.NoSpacesInName = Verbindungsprofilname darf nicht mit Leerzeichen beginnen oder enden.
NewConnectionProfileWizardPage.title = Verbindungsprofil erstellen
NewConnectionProfileWizardPage.desc = Geben Sie die Profilinformationen ein.
NewConnectionProfileWizardPage.cp_name = Na&me:
NewConnectionProfileWizardPage.cp_desc = &Beschreibung (optional):
NewConnectionProfileWizardPage.choices=Bitte auswählen\:
NewConnectionProfileWizardPage.summary_cp_name=Name
NewConnectionProfileWizardPage.summary_cp_desc=Beschreibung
NewConnectionProfileWizardPage.Button.AutoConnect = Beim Starten &automatisch verbinden
NewConnectionProfileWizardPage.Button.AutoConnect1 = Beim Starten automatisch verbinden
NewConnectionProfileWizardPage.summary_autoconnect = Beim Starten automatisch verbinden
NewConnectionProfileWizardPage.summary_autoconnect_on_finish = Beim Beenden automatisch verbinden
NewConnectionProfileWizardPage.localRepository = In Arbeitsplatz-Repository erstellen (lokal)
NewConnectionProfileWizardPage.chooseRepository = Repository wählen:
ConnectionProfileDetailsPage.Button.TestConnection=Verbindung &testen
ConnectionProfileDetailsPage.AskConfirmation=Bestätigungsdialog
ConnectionProfileDetailsPage.AskReconnect=Die Informationen dieses Verbindungsprofils wurden geändert. Möchten Sie die Verbindung zum Server wiederherstellen?
SummaryWizardPage.title=Zusammenfassung
SummaryWizardPage.description=Diese Informationen wurden auf den vorherigen Seiten zusammengestellt.
SummaryWizardPage.property=Eigenschaft
SummaryWizardPage.value=Wert
dialog.title.error=Fehler
dialog.title.success=Erfolgreich
rename.dialog.title=Umbenennungsdialog
rename.dialog.message=Neuen Verbindungsprofilnamen eingeben\:
rename.dialog.errmsg.existing=Der Name ist vorhanden, bitte geben Sie einen anderen Namen ein\!
rename.dialog.errmsg.invalid=Der Name ist ungültig, bitte geben Sie einen gültigen Namen ein\!
rename.dialog.errmsg.NoSpacesInName = Verbindungsprofilname darf nicht mit Leerzeichen beginnen oder enden.
error.connect={1}.  Details finden Sie in der Protokolldatei.
error.contentExtension=Beim Herstellen der Verbindung zur Erweiterung "{0}" für das Profil "{1}" trat ein Fehler auf (Fehler\: {2}).
CPVersionPropertyPage.desc=Versionsinformationen für {0}.\nDiese Informationen wurden beim letzten Verbindungsversuch erhalten.  Falls der letzte Verbindungsversuch nicht erfolgreich war, sind keine Informationen verfügbar.
CPVersionPropertyPage.button.updateVersion=Versionshinweise verbinden und aktualisieren
CPVersionPropertyPage.label.versionUnavailable=Die Versionsinformationen sind für dieses Profil nicht verfügbar.
CPVersionPropertyPage.label.techVersions=Folgende Technologien sind auf diesem Server verfügbar\:
ConnectionProfileSummaryPage.button.testConnection=Verbindung &testen
CommonLabelProviderBase.label.version={0} ({1} v. {2}) 
CommonLabelProviderBase.label.version.versionless={0} ({1}) 
CommonLabelProviderBase.label.localRepository=Arbeitsplatz-Repository (lokal)

properties.connectionprofile.type = Profiltyp
DSE.Refresh.label = &Aktualisieren
DSE.View.Tooltip = Datenquellen-Explorer

CPDeleteChange.name = Verbindungsprofil {0} löschen
CPDeleteChange.error.ProfileDoesNotExist = Das Verbindungsprofil, das Sie löschen möchten, ist nicht vorhanden.
CPDeleteChange.delete.failure = Das Löschen des Verbindungsprofils ist fehlgeschlagen.
CPDeleteProcessor.name = Prozessor zum Löschen der DTP-Verbindung
CPDuplicateProcessor.name = Prozessor zum Vervielfältigen des DTP-Verbindungsprofils
CPCopyChange.name = Verbindungsprofil {0} vervielfältigen
CPCopyChange.error.ProfileDoesNotExist = Das Verbindungsprofil, das Sie vervielfältigen möchten, ist nicht vorhanden.
CPCopyChange.title.error = Das Vervielfältigen des Verbindungsprofils ist fehlgeschlagen.
CPCopyChange.error.InvalidTarget = Das angegebene Ziel ist kein gültiges Verbindungsprofil-Repository.
CPCopyChange.error.RepositoryNotConnected = Keine Verbindung zum Ziel-Verbindungsprofil-Repository {0}.
CPMoveProcessor.name = Prozessor zum Verschieben des DTP-Verbindungsprofils
CPMoveChange.name = Verbindungsprofil {0} verschieben
CPMoveChange.error.ProfileDoesNotExist = Das Verbindungsprofil, das Sie verschieben möchten, ist nicht vorhanden.
CPMoveChange.title.error = Das Verschieben des Verbindungsprofils ist fehlgeschlagen.
CPCreateChange.name = Verbindungsprofil {0} erstellen
CPCreateChange.error.NewProfileDoesNotHaveName = Für das Erstellen eines neuen Verbindungsprofils ist ein Name erforderlich.
CPCreateChange.error.NewProfileAlreadyExists = Ein Verbindungsprofil mit dem neuen Namen ist bereits vorhanden.
CPCreateChange.error.NewProfileDoesNotHaveProviderID = Die Anbieter-ID des Verbindungsprofils ist für eine Erstellung des neuen Verbindungsprofils erforderlich.
CPCreateChange.error.NewProfileDoesNotHaveNonNullPropertiesObject = Ein Eigenschaftsobjekt mit einem Wert ungleich Null ist für die Erstellung eines neuen Verbindungsprofils erforderlich.
CPCreateChange.create.failure = Das Erstellen des Verbindungsprofils ist fehlgeschlagen.
CPCreateProcessor.name = Prozessor zum Erstellen der DTP-Verbindung
CPRenameChange.name = Verbindungsprofil {0} umbenennen
CPRenameProcessor.name = Prozessor zum Umbenennen der DTP-Verbindung
CPRenameChange.title.error = Das Umbenennen des Verbindungsprofils ist fehlgeschlagen.

PropertyDescriptor.error.title = Fehler beim Verarbeiten des Eigenschaften-Deskriptors für die Treiberdefinition
PropertyDescriptor.error.msg = Fehler beim Verarbeiten von Eigenschaften für die Treiberdefinition aufgetreten.
PasswordTextPropertyDescriptor.property.label = Kennwort
DriverClassBrowsePropertyDescriptor.property.label = Treiberklasse
DriverClassBrowsePropertyDescriptor.jardialog.title = In der JAR-Liste verfügbare Klassen
DriverClassBrowsePropertyDescriptor.jardialog.msg = Geben Sie den Namen der Treiberklasse an, oder wählen Sie eine Klasse aus den verfügbaren JARs.
DriverClassBrowsePropertyDescriptor.noclasses.title = Keine Treiberklassen verfügbar
DriverClassBrowsePropertyDescriptor.noclasses.msg = Für die aktuelle JAR-Liste sind keine Treiberklassen verfügbar.

StatusBar.Connected = Verbunden
StatusBar.Disconnected = Verbindung getrennt
StatusBar.ConnectedMessage = {0} ({1})

StatusBar.WorkingOffline = Offline arbeiten

DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE = Offline &arbeiten
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE = Offline &speichern

DriverPropertyEditorDescriptor.InvalidID = Eigenschaftseditor-Deskriptor verfügt über keine gültige ID
DriverPropertyEditorDescriptor.InvalidTargetTemplateID = Eigenschaftseditor-Deskriptor verfügt über keine gültige Zielvorlagen-ID
DriverPropertyEditorDescriptor.InvalidTargetPropertyId = Eigenschaftseditor-Deskriptor verfügt über keine gültige Zieleigenschafts-ID
DriverPropertyEditorDescriptor.InvalidCustomPropertyEditorClass = Eigenschaftseditor-Deskriptor verfügt über keinen gültigen benutzerdefinierten Eigenschaftseditor

ExtensibleProfileDetailsWizardPage.title = Treiber- und Verbindungsdetails angeben
ExtensibleProfileDetailsWizardPage.description = Wählen Sie einen Treiber aus der Dropdown-Liste, und geben Sie Anmeldedetails für die Verbindung an.
ExtensibleProfileDetailsWizardPage.driverCombo.label = &Treiber:
ExtensibleNewConnectionProfileWizard.title = Neues Verbindungsprofil

DriverUIContributorComposite.group = &Eigenschaften

CommonDriverUIContributor.optionaltab = &Optional
CommonDriverUIContributor.optionalProps.label = Zusätzliche Eigenschaften:
CommonDriverUIContributor.generaltab = &Allgemein

OtherDriverUIContributor.databaseName.label = &Datenbank:
OtherDriverUIContributor.url.label = &URL:
OtherDriverUIContributor.userName.label = &Benutzername:
OtherDriverUIContributor.password.label = Kenn&wort:
OtherDriverUIContributor.savePassword.label = &Kennwort speichern
OtherDriverUIContributor.summaryData.database = Datenbank
OtherDriverUIContributor.summaryData.username = Benutzername
OtherDriverUIContributor.summaryData.savePassword = Kennwort speichern
OtherDriverUIContributor.summaryData.true = Wahr
OtherDriverUIContributor.summaryData.false = Falsch
OtherDriverUIContributor.summaryData.url = URL

OtherDriverUIContributor.errormessage.requiresdatabase = Enter a database name.
OtherDriverUIContributor.errormessage.requiresurl = Enter a URL.
OtherDriverUIContributor.errormessage.requiresusername = Enter a user name.

ConnectAction.title = Eigenschaften für {0}

Boolean.true = Wahr
Boolean.false = Falsch

NewRepositoryWizard.title = Neues Repository-Assistent-Fenster

NewConnectionProfileWizardPage.Status.ContainsColon= Verbindungsprofilname darf keinen Doppelpunkt (:) enthalten!

