category.datatools.name=データベースツール
category.datatools.description=データベース開発ツール

DatabaseManagement.command.explain=実行プランの取得
DatabaseManagement.command.execute=すべて実行
DatabaseManagement.command.execute.select=選択したテキストを実行
DatabaseManagement.command.dmldialog.select=SQL クエリビルダで編集...
DatabaseManagement.ToggleComment=コメントの切り替え
DatabaseManagement.command.run=実行
DatabaseManagement.command.debug=デバッグ
DatabaseManagement.command.savetodb=データベースに保存
DatabaseManagement.command.refresh=データベースから更新
DatabaseManagement.command.saveAsTemplate=テンプレートとして保存

sqlEditorName=SQL エディタ

sqlProblemName=SQL 構文の検証エラー
sqlPortabilityName=SQL 移植タスク

database.development.perspective=データベース開発

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= SQL の編集
context.editingSQL.description= SQL コンテキストの編集

ActionDefinition.showSQLInfo.name= SQL の情報を表示
ActionDefinition.showSQLInfo.description= カーソル位置にある要素の SQL 情報を表示します。

#preference page names
DatabaseManagement.General=全般
DatabaseManagement.EditorTemplates=テンプレート
DatabaseManagement.CodeAssist=コードアシスト
DatabaseManagement.SQLEditor=SQL エディタ
DatabaseManagement.ConnectionOptions=接続レベルのオプション
DatabaseManagement.SyntaxColoring=Syntax Coloring

