###############################################################################
# Copyright (c) 2008 Sybase, Inc. and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Sybase, Inc. - initial API and implementation
###############################################################################
pluginName   = Eclipse Data Tools Platform SQL Editor
providerName = Eclipse Data Tools Platform

category.datatools.name=Datenbanktools
category.datatools.description=Datenbankentwicklungstools

DatabaseManagement.command.explain=Ausführungsplan abrufen
DatabaseManagement.command.execute=Alle ausführen
DatabaseManagement.command.execute.select=Ausgewählten Text ausführen
DatabaseManagement.command.execute.current=Aktuellen Text ausführen
DatabaseManagement.command.execute.as.one.statement=Ausgewählten Text als eine Anweisung ausführen
DatabaseManagement.command.dmldialog.select=In SQL Query Builder bearbeiten...
DatabaseManagement.ToggleComment=Kommentar ein/aus
DatabaseManagement.command.run=Ausf
DatabaseManagement.command.debug=Debug
DatabaseManagement.command.savetodb=In Datenbank speichern
DatabaseManagement.command.refresh=Von Datenbank aktualisieren
DatabaseManagement.command.saveAsTemplate=Als Vorlage speichern
DatabaseManagement.command.gotomatchingtoken=Zu übereinstimmendem Token

sqlEditorName=SQL-Editor

sqlProblemName=Problem bei Validierung der SQL-Syntax
sqlPortabilityName=SQL-Portabilitätsaufgabe

database.development.perspective=Datenbankentwicklung

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= Bearbeiten von SQL
context.editingSQL.description= Bearbeiten von SQL-Kontext

ActionDefinition.showSQLInfo.name= SQL-Informationen anzeigen
ActionDefinition.showSQLInfo.description= Zeigt die SQL-Informationen zu dem Element an der Cursorposition an.

#preference page names
DatabaseManagement.General=Allgemein
DatabaseManagement.EditorTemplates=Vorlagen
DatabaseManagement.CodeAssist=Hilfe zum Code
DatabaseManagement.SQLEditor=SQL-Editor
DatabaseManagement.ConnectionOptions=Optionen für Verbindungsebene
DatabaseManagement.SyntaxColoring=Syntaxfarbe

