category.datatools.name=Outils de base de données
category.datatools.description=Outils de développement de base de données

DatabaseManagement.command.explain=Obtenir le plan d'exécution
DatabaseManagement.command.execute=Exécuter Tout
DatabaseManagement.command.execute.select=Exécuter le texte sélectionné
DatabaseManagement.command.dmldialog.select=Modifier dans le générateur de requête SQL...
DatabaseManagement.ToggleComment=Basculer le commentaire
DatabaseManagement.command.run=Exécuter
DatabaseManagement.command.debug=Déboguer
DatabaseManagement.command.savetodb=Enregistrer dans la base de données
DatabaseManagement.command.refresh=Actualiser à partir de la base de données
DatabaseManagement.command.saveAsTemplate=Enregistrer comme modèle
DatabaseManagement.command.gotomatchingtoken=Goto Matching Token

sqlEditorName=Editeur SQL

sqlProblemName=Problème de validation de syntaxe SQL
sqlPortabilityName=Tâche de portabilité SQL

database.development.perspective=Développement de base de données

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= Modification de SQL
context.editingSQL.description= Modification du contexte SQL

ActionDefinition.showSQLInfo.name= Afficher les informations SQL
ActionDefinition.showSQLInfo.description= Afficher les informations SQL pour l'élément à la position du curseur

#preference page names
DatabaseManagement.General=Général
DatabaseManagement.EditorTemplates=Modèles
DatabaseManagement.CodeAssist=Code Assist
DatabaseManagement.SQLEditor=Editeur SQL
DatabaseManagement.ConnectionOptions=Options de niveau de connexion
DatabaseManagement.SyntaxColoring=Coloration syntaxique

