category.datatools.name=데이터베이스 도구
category.datatools.description=데이터베이스 개발 도구

DatabaseManagement.command.explain=실행 계획 가져오기
DatabaseManagement.command.execute=모두 실행
DatabaseManagement.command.execute.select=선택한 텍스트 실행
DatabaseManagement.command.dmldialog.select=SQL 쿼리 빌더로 편집...
DatabaseManagement.ToggleComment=설명 전환
DatabaseManagement.command.run=실행
DatabaseManagement.command.debug=디버그
DatabaseManagement.command.savetodb=데이터베이스에 저장
DatabaseManagement.command.refresh=데이터베이스에서 새로 고침
DatabaseManagement.command.saveAsTemplate=템플릿으로 저장

sqlEditorName=SQL 편집기

sqlProblemName=SQL 구문 유효성 문제
sqlPortabilityName=SQL 이식성 작업

database.development.perspective=데이터베이스 개발

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= 편집 SQL
context.editingSQL.description= 편집 SQL 컨텍스트

ActionDefinition.showSQLInfo.name= SQL 정보 보기
ActionDefinition.showSQLInfo.description= 커서 위치에 있는 요소의 SQL 정보 보기

#preference page names
DatabaseManagement.General=일반
DatabaseManagement.EditorTemplates=템플릿
DatabaseManagement.CodeAssist=코드 지원
DatabaseManagement.SQLEditor=SQL 편집기
DatabaseManagement.ConnectionOptions=연결 수준 옵션
DatabaseManagement.SyntaxColoring=Syntax Coloring