category.datatools.name=数据库工具
category.datatools.description=数据库开发工具

DatabaseManagement.command.explain=获取执行方案
DatabaseManagement.command.execute=全部执行
DatabaseManagement.command.execute.select=执行所选文本
DatabaseManagement.command.dmldialog.select=在 SQL 查询生成器中编辑...
DatabaseManagement.ToggleComment=切换注释
DatabaseManagement.command.run=运行
DatabaseManagement.command.debug=调试
DatabaseManagement.command.savetodb=保存至数据库
DatabaseManagement.command.refresh=从数据库刷新
DatabaseManagement.command.saveAsTemplate=另存为模板

sqlEditorName=SQL 编辑器

sqlProblemName=SQL 语法验证问题
sqlPortabilityName=SQL 可移植性任务

database.development.perspective=数据库开发

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= 编辑 SQL
context.editingSQL.description= 编辑 SQL 上下文

ActionDefinition.showSQLInfo.name= 显示 SQL 信息
ActionDefinition.showSQLInfo.description= 显示游标位置处的元素的 SQL 信息

#preference page names
DatabaseManagement.General=常规
DatabaseManagement.EditorTemplates=模板
DatabaseManagement.CodeAssist=代码助手
DatabaseManagement.SQLEditor=SQL 编辑器
DatabaseManagement.ConnectionOptions=连接级别选项
DatabaseManagement.SyntaxColoring=Syntax Coloring

