category.datatools.name=Herramientas de base de datos
category.datatools.description=Herramientas de desarrollo de base de datos

DatabaseManagement.command.explain=Obtener plan de ejecución
DatabaseManagement.command.execute=Ejecutar todo
DatabaseManagement.command.execute.select=Ejecutar texto seleccionado
DatabaseManagement.command.dmldialog.select=Editar en el compilador de consultas SQL...
DatabaseManagement.ToggleComment=Alternar comentario
DatabaseManagement.command.run=Ejecutar
DatabaseManagement.command.debug=Depurar
DatabaseManagement.command.savetodb=Guardar en base de datos
DatabaseManagement.command.refresh=Actualizar desde base de datos
DatabaseManagement.command.saveAsTemplate=Guardar como plantilla
DatabaseManagement.command.gotomatchingtoken=Ir a token coincidente

sqlEditorName=Editor SQL

sqlProblemName=Problema de validación de sintaxis SQL
sqlPortabilityName=Tarea de portabilidad de SQL

database.development.perspective=Desarrollo de base de datos

templates.sql.generic.contextType.name=SQL
templates.sql.asa.contextType.name=SQL-ASA
templates.sql.ase.contextType.name=SQL-ASE
templates.sql.ase15.contextType.name=SQL-ASE15
templates.sql.asiq.contextType.name=SQL-ASIQ

context.editingSQL.name= Edición de SQL
context.editingSQL.description= Edición de contexto de SQL

ActionDefinition.showSQLInfo.name= Mostrar información de SQL
ActionDefinition.showSQLInfo.description= Muestra la información de SQL para el elemento en la posición del cursor

#preference page names
DatabaseManagement.General=General
DatabaseManagement.EditorTemplates=Plantillas
DatabaseManagement.CodeAssist=Ayuda de código
DatabaseManagement.SQLEditor=Editor SQL
DatabaseManagement.ConnectionOptions=Opciones de nivel de conexión
DatabaseManagement.SyntaxColoring=Colores de sintaxis

