IdentifierValidator_doublequotation_invalid=对此标识符错误地使用了引号
IdentifierValidator_doublequotation_notpermit=在带引号标识符禁用方式下不允许使用引号
IdentifierValidator_table_invalidstart=表名只能以字母、_ 或 # 开头
IdentifierValidator_localvariable_invalidstart=局部变量只能以字母、_ 或 @ 开头
IdentifierValidator_parameter_invalidstart=局部变量只能以字母、_ 或 @ 开头
IdentifierValidator_other_invalidstart=标识符只能以字母和 {0} 开头
IdentifierValidator_invalid_part=后续字母可以包含字母、数字、#、@、_ 或货币符号
IdentifierValidator_invalid_reservedword=标识符不能为保留字

