IdentifierValidator_doublequotation_invalid=この識別子は引用符で正しく囲まれていません。
IdentifierValidator_doublequotation_notpermit=識別子を引用符で囲まないモードでは、引用符を使用できません。
IdentifierValidator_table_invalidstart=テーブル名の開始文字として使用できるのは、_ と # だけです。
IdentifierValidator_localvariable_invalidstart=ローカル変数の開始文字として使用できるのは、_ と @ だけです。
IdentifierValidator_parameter_invalidstart=ローカル変数の開始文字として使用できるのは、_ と @ だけです。
IdentifierValidator_other_invalidstart=識別子の開始文字として使用できるのは {0} だけです。
IdentifierValidator_invalid_part=先頭以外の文字には、数字、#、@、_、通貨記号を使用できます。
IdentifierValidator_invalid_reservedword=識別子には予約語を使用できません。

