IdentifierValidator_doublequotation_invalid=Diese Kennung wurde nicht korrekt angegeben.
IdentifierValidator_doublequotation_notpermit=Anführungszeichen ist in angegebener Kennung nicht zulässig; Off-Modus
IdentifierValidator_table_invalidstart=Tabellenname kann nur mit einem Buchstaben, _ oder # beginnen.
IdentifierValidator_localvariable_invalidstart=Lokale Variable kann nur mit einem Buchstaben, _ oder @ beginnen.
IdentifierValidator_parameter_invalidstart=Lokale Variable kann nur mit einem Buchstaben, _ oder @ beginnen.
IdentifierValidator_other_invalidstart=Kennung kann nur mit dem Buchstaben {0} beginnen.
IdentifierValidator_invalid_part=Nachfolgende Zeichen können Buchstaben, Zahlen, #, @, _ oder Währungssymbole enthalten.
IdentifierValidator_invalid_reservedword=Die Kennung darf kein reserviertes Wort sein.

