IdentifierValidator_doublequotation_invalid=L'identificateur n'est pas correctement entre guillemets
IdentifierValidator_doublequotation_notpermit=Les guillemets ne sont pas autorisés en dehors du mode d'identificateur entre guillemets
IdentifierValidator_table_invalidstart=Le nom d'une table ne peut commencer que par une lettre, _ ou #
IdentifierValidator_localvariable_invalidstart=Une variable locale ne peut commencer que par une lettre, _ ou @
IdentifierValidator_parameter_invalidstart=Une variable locale ne peut commencer que par une lettre, _ ou @
IdentifierValidator_other_invalidstart=Un identificateur ne peut commencer que par une lettre, {0}
IdentifierValidator_invalid_part=Les caractères suivants peuvent inclure des lettres, des chiffres, #, @, _ ou des symboles monétaires
IdentifierValidator_invalid_reservedword=L'identificateur ne peut pas être un mot réservé

