IdentifierValidator_doublequotation_invalid=Este identificador no está situado entre comillas correctamente
IdentifierValidator_doublequotation_notpermit=No se permiten las comillas en el modo desactivado de identificador entre comillas
IdentifierValidator_table_invalidstart=El nombre de tabla sólo puede empezar con una letra, _ o #
IdentifierValidator_localvariable_invalidstart=La variable local sólo puede empezar con una letra, _ o @
IdentifierValidator_parameter_invalidstart=La variable local sólo puede empezar con una letra, _ o @
IdentifierValidator_other_invalidstart=El identificador sólo puede empezar con una letra, {0}
IdentifierValidator_invalid_part=Los caracteres posteriores pueden incluir letras, números, #, @, _ o símbolos de moneda
IdentifierValidator_invalid_reservedword=El identificador no puede ser una palabra reservada

