IdentifierValidator_doublequotation_invalid=이 식별자의 따옴표가 올바르게 붙여지지 않았습니다.
IdentifierValidator_doublequotation_notpermit=따옴표는 따옴표 붙은 식별자 해제 모드에서 허용되지 않습니다.
IdentifierValidator_table_invalidstart=테이블 이름은 문자, _ 또는 @로 시작해야 합니다.
IdentifierValidator_localvariable_invalidstart=로컬 변수는 문자, _ 또는 @로 시작해야 합니다.
IdentifierValidator_parameter_invalidstart=로컬 변수는 문자, _ 또는 @로 시작해야 합니다.
IdentifierValidator_other_invalidstart=식별자는 문자 {0}로 시작해야 합니다.
IdentifierValidator_invalid_part=첫 글자는 문자, 숫자, #, @, _, 또는 통화 기호를 포함할 수 있습니다.
IdentifierValidator_invalid_reservedword=식별자는 예약어일 수 없습니다.

