
CodeAssist_description=Code-Unterstützungseinstellungen für SQL-Editor
CodeAssist_general_title=&Allgemein
CodeAssist_showSystemGroup=Datenbankobjekte anzeigen
CodeAssist_showSystemTables=System&tabellen anzeigen
CodeAssist_showSystemProcedures=System&prozeduren und -funktionen anzeigen
CodeAssist_showOwnerOfTable=&Eigentümer der Tabelle oder Ansicht anzeigen
CodeAssist_asa_tips=Die folgenden Voreinstellungen sind nur für die SQL Anywhere-Datenbank verfügbar:
CodeAssist_showSystemViews=Systeman&sichten anzeigen
CodeAssist_asa_titile=&ASA
CodeAssist_insertSingleProposals=E&inzelne Vorschläge automatisch einfügen
CodeAssist_autoActivationGroup=Autom. Aktivierung
CodeAssist_enableAuto=Autom. Aktivierung a&ktivieren
CodeAssist_autoActivationDelay=Verzögerung der a&utom. Aktivierung:
CodeAssist_autoActivationTriggers=Autom. Aktivierung wird für SQL ausgelöst:




SQLEditor_general_title=&Allgemein
SQLEditor_syntaxValidationGroup=&Syntaxvalidierung
SQLEditor_syntaxValidation=Syntaxvalidierung akti&vieren
SQLEditor_syntaxValidation_tooltip=Syntaxvalidierung durchführen und SQL-Anweisungsstrukturen in der Gliederungsansicht aktualisieren
SQLEditor_maxLineButton=&Max. Anzahl von Zeilen:
SQLEditor_maxLineButton_tooltip=Syntaxvalidierung deaktivieren, wenn der Inhalt die max. Anzahl von Zeilen erreicht
SQLEditor_showPromptDialog=Zur Deaktivierung der Syntaxvalidierung auffordern, wenn der Inhalt die max. Anzahl von Zeilen erreicht

SQLEditor_showSyntaxErorrDetail=Detaillierte Anmerkungsinformationen an&zeigen
SQLEditor_showSyntaxErorrDetail_tooltip=Detaillierte Anmerkungsinformation wie beispielsweise Syntaxvorschläge anzeigen

SQLEditor_executeCurrentSQLGroup=Aktuellen Text ausführen
SQLEditor_executeSQLBetweenDelimiter=SQLs zwischen Trennzeichen ausführen
SQLEditor_executeSQLBetweenDelimiter_tip=SQLs zwischen Trennzeichen vor und nach aktueller Cursorposition ausführen
SQLEditor_executeCurrentLine=Aktuelle Zeile ausführen
SQLEditor_executeCurrentLine_tip=Text in Zeile mit Cursorposition ausführen
SQLEditor_executeSQLBetweenBlankLine=SQLs zwischen Leerzeilen ausführen
SQLEditor_executeSQLBetweenBlankLine_tip=SQLs zwischen Leerzeilen vor und nach aktueller Cursorposition ausführen

SQLEditor_typing_title=&Eingabe
SQLEditor_typingAidsGroup_title=Diese Eingabehilfen im Smart Insert-Modus aktivieren:
SQLEditor_typingAidsTable_columnName1=Name
SQLEditor_typingAidsTable_columnName2=Kontext
SQLEditor_typingAidsTable_columnName3=Beschreibung

SQLEditor_closeSingleQuotes=Einzelne Anführungszeichen schließen
SQLEditor_closeSingleQuotes_description=Falls aktiviert, einzelne Anführungszeichen schließen.
SQLEditor_closeSingleQuotes_preview='${cursor}'

SQLEditor_closeDoubleQuotes=Doppelte Anführungszeichen schließen
SQLEditor_closeDoubleQuotes_description=Falls aktiviert, doppelte Anführungszeichen schließen.
SQLEditor_closeDoubleQuotes_preview="${cursor}"

SQLEditor_closeBrackets=Klammern schließen
SQLEditor_closeBrackets_description=Falls aktiviert, Klammern schließen.
SQLEditor_closeBrackets_preview=(${cursor})

SQLEditor_closeComments=Kommentare schließen
SQLEditor_closeComments_description=Falls aktiviert, mehrzeilige SQL-Kommentare schließen.
SQLEditor_closeComments_preview=/*\n *${cursor}\n */


SQLEditor_beginEndStatement=Beginn-Ende
SQLEditor_beginEndStatement_description=Fügen Sie das 'Ende' mit korrektem Einzug hinzu, und bewegen Sie den Cursor zu einer neuen Zeile zwischen Beginn/Ende mit dem korrekten Einzug.
SQLEditor_beginEndStatement_preview=BEGIN\n\t${cursor}\nEND

SQLEditor_typingAidsTable_context_all=Alles

SQLEditor_typingAids_preview=Vorschau:

General_max_row_num=Max. Zeilenzahl muss größer als Null sein.
General_invalid_int=\ ist keine gültige Ganzzahl.

GeneralPreferencePage_portable_target=Ohne
GeneralPreferencePage_execute_error_mode=Soll beim Auftreten von Fehlern während der SQl-Ausführung fortgefahren werden?
GeneralPreferencePage_execute_always=&Immer
GeneralPreferencePage_execute_never=&Nie
GeneralPreferencePage_execute_prompt=Auff&ordern
GeneralPreferencePage_savebeforerenaming_prompt=Auf&fordern
GeneralPreferencePage_savebeforerenaming_always=I&mmer
GeneralPreferencePage_title=Allgemeine Einstellungen
GeneralPreferencePage_description=Allgemeine Einstellungen für die Datenbankentwicklungstools.
GeneralPreferencePage_hover_affordance=Affordance im &Hover-Zustand zeigen, um darzulegen, wie diese 'sticky' gemacht werden können
GeneralPreferencePage_portable_check=&Portabilitäts-Prüfungsziel:

SyntaxColoringPage_description=Farb- und Stileinstellungen für die Syntax.
SyntaxColoringPage_color=F&arbe:
SyntaxColoringPage_bold=&Fett
SyntaxColoringPage_italic=&Kursiv
SyntaxColoringPage_strikethrough=&Durchgestrichen
SyntaxColoringPage_underline=&Unterstrichen
SyntaxColoringPage_preview=Vor&schau:
SyntaxColoringPage_syntax_items=S&yntaxelemente:
SyntaxColoringPage_default_foreground_color=Standard-&Vordergrundfarbe
