
CodeAssist_description=Ajustes de ayuda de código para SQL Editor
CodeAssist_general_title=&General
CodeAssist_showSystemGroup=Mostrar objetos de base de datos
CodeAssist_showSystemTables=Mostrar &tablas del sistema
CodeAssist_showSystemProcedures=Mostrar &procedimientos y funciones del sistema
CodeAssist_showOwnerOfTable=Mostrar p&ropietario de la tabla o vista
CodeAssist_asa_tips=Las preferencias siguientes están disponibles sólo para la base de datos SQL Anywhere:
CodeAssist_showSystemViews=Mostrar &vistas del sistema
CodeAssist_asa_titile=&ASA
CodeAssist_insertSingleProposals=&Insertar propuestas simples automáticamente
CodeAssist_autoActivationGroup=Activación automática
CodeAssist_enableAuto=&Activar activación automática
CodeAssist_autoActivationDelay=Retardo de activación a&utomática:
CodeAssist_autoActivationTriggers=Activadores de activación automática para SQL:




SQLEditor_general_title=&General
SQLEditor_syntaxValidationGroup=Validación de &sintaxis
SQLEditor_syntaxValidation=A&ctivar validación de sintaxis
SQLEditor_syntaxValidation_tooltip=Realizar validación de sintaxis y actualizar estructuras de sentencias SQL en la vista de contorno
SQLEditor_maxLineButton=&Número máximo de líneas:
SQLEditor_maxLineButton_tooltip=Desactivar la validación de sintaxis cuando el contenido supera el número máximo de líneas
SQLEditor_showPromptDialog=Solicitar la validación de sintaxis cuando el contenido supera el número máximo de líneas

SQLEditor_showSyntaxErorrDetail=&Mostrar información detallada de anotación
SQLEditor_showSyntaxErorrDetail_tooltip=Mostrar información detallada de anotación, por ejemplo algunas propuestas de sintaxis

SQLEditor_typing_title=&Escribir
SQLEditor_typingAidsGroup_title=Activar estas ayudas a la escritura en el modo Inserción inteligente:
SQLEditor_typingAidsTable_columnName1=Nombre
SQLEditor_typingAidsTable_columnName2=Contexto
SQLEditor_typingAidsTable_columnName3=Descripción

SQLEditor_closeSingleQuotes=Cerrar comillas simples
SQLEditor_closeSingleQuotes_description=Si están activadas, cerrar comillas simples.
SQLEditor_closeSingleQuotes_preview='${cursor}'

SQLEditor_closeDoubleQuotes=Cerrar comillas dobles
SQLEditor_closeDoubleQuotes_description=Si están activadas, cerrar comillas dobles.
SQLEditor_closeDoubleQuotes_preview="${cursor}"

SQLEditor_closeBrackets=Cerrar paréntesis
SQLEditor_closeBrackets_description=Si están activados, cerrar paréntesis.
SQLEditor_closeBrackets_preview=(${cursor})

SQLEditor_closeComments=Cerrar comentarios
SQLEditor_closeComments_description=Si están activados, cierre los comentarios de varias líneas de SQL.
SQLEditor_closeComments_preview=/*\n *${cursor}\n */


SQLEditor_beginEndStatement=Begin-End
SQLEditor_beginEndStatement_description=Añada 'end' con un sangrado adecuado y, a continuación, mueva el cursor a una nueva línea entre Begin/End con un sangrado correcto.
SQLEditor_beginEndStatement_preview=BEGIN\n\t${cursor}\nEND

SQLEditor_typingAidsTable_context_all=Todos

SQLEditor_typingAids_preview=Vista previa:

General_max_row_num=El número de línea máximo debe ser mayor de cero.
General_invalid_int=\ no es un entero válido

GeneralPreferencePage_portable_target=Ninguno
GeneralPreferencePage_execute_error_mode=Si continuar o no cuando se produce un error durante la ejecución de SQL
GeneralPreferencePage_execute_always=&Siempre
GeneralPreferencePage_execute_never=&Nunca
GeneralPreferencePage_execute_prompt=S&olicitud
GeneralPreferencePage_savebeforerenaming_prompt=So&licitud
GeneralPreferencePage_savebeforerenaming_always=Sie&mpre
GeneralPreferencePage_title=Ajustes generales
GeneralPreferencePage_description=Ajustes generales para las herramientas de desarrollo de bases de datos.
GeneralPreferencePage_hover_affordance=Mostrar permiso en &movimiento sobre cómo hacerlo ajustado
GeneralPreferencePage_portable_check=&Destino de comprobación de portabilidad:

SyntaxColoringPage_description=Ajustes de estilo y color para la sintaxis.
SyntaxColoringPage_color=&Color:
SyntaxColoringPage_bold=&Negrita
SyntaxColoringPage_italic=Curs&iva
SyntaxColoringPage_strikethrough=&Tachado
SyntaxColoringPage_underline=S&ubrayado
SyntaxColoringPage_preview=&Vista previa:
SyntaxColoringPage_syntax_items=Elementos de sinta&xis
