
CodeAssist_description=SQL 编辑器的代码帮助设置
CodeAssist_general_title=常规(&G)
CodeAssist_showSystemGroup=显示数据库对象
CodeAssist_showSystemTables=显示系统表(&T)
CodeAssist_showSystemProcedures=显示系统过程和函数(&P)
CodeAssist_showOwnerOfTable=显示表或视图的所有者(&O)
CodeAssist_asa_tips=下列首选项仅对 SQL Anywhere 数据库可用:
CodeAssist_showSystemViews=显示系统视图(&V)
CodeAssist_asa_titile=ASA(&A)
CodeAssist_insertSingleProposals=自动插入单个建议(&I)
CodeAssist_autoActivationGroup=自动激活
CodeAssist_enableAuto=启用自动激活(&E)
CodeAssist_autoActivationDelay=自动激活延迟(&U):
CodeAssist_autoActivationTriggers=SQL 的自动激活触发器:




SQLEditor_general_title=常规(&G)
SQLEditor_syntaxValidationGroup=语法验证(&S)
SQLEditor_syntaxValidation=启用语法验证(&N)
SQLEditor_syntaxValidation_tooltip=在“轮廓”视图中执行语法验证并更新 SQL 语句结构
SQLEditor_maxLineButton=最大行数(&M):
SQLEditor_maxLineButton_tooltip=内容超过最大行数时禁用语法验证
SQLEditor_showPromptDialog=提示内容超过最大行数时禁用语法验证

SQLEditor_showSyntaxErorrDetail=显示详细注释信息(&H)
SQLEditor_showSyntaxErorrDetail_tooltip=显示详细注释信息，如某些语法建议

SQLEditor_executeCurrentSQLGroup=执行当前文本
SQLEditor_executeSQLBetweenDelimiter=执行分隔符之间的 SQL
SQLEditor_executeSQLBetweenDelimiter_tip=执行当前光标位置前后的分隔符之间的 SQL
SQLEditor_executeCurrentLine=执行当前行
SQLEditor_executeCurrentLine_tip=执行光标位置的行文本
SQLEditor_executeSQLBetweenBlankLine=执行空白行之间的 SQL
SQLEditor_executeSQLBetweenBlankLine_tip=执行当前光标位置前后的空间行之间的 SQL

SQLEditor_typing_title=输入(&T)
SQLEditor_typingAidsGroup_title=在智能插入方式下启用输入帮助:
SQLEditor_typingAidsTable_columnName1=名称
SQLEditor_typingAidsTable_columnName2=上下文
SQLEditor_typingAidsTable_columnName3=说明

SQLEditor_closeSingleQuotes=单引号
SQLEditor_closeSingleQuotes_description=如果启用，则关闭单引号。
SQLEditor_closeSingleQuotes_preview='${cursor}'

SQLEditor_closeDoubleQuotes=关闭双引号
SQLEditor_closeDoubleQuotes_description=如果启用，则关闭双引号。
SQLEditor_closeDoubleQuotes_preview="${cursor}"

SQLEditor_closeBrackets=关闭圆括号
SQLEditor_closeBrackets_description=如果启用，则关闭圆括号。
SQLEditor_closeBrackets_preview="${cursor}"

SQLEditor_closeComments=关闭注释
SQLEditor_closeComments_description=如果启用，则关闭 SQL 多行注释。
SQLEditor_closeComments_preview=/*\n *${cursor}\n */


SQLEditor_beginEndStatement=Begin-End
SQLEditor_beginEndStatement_description=添加带有适当标识的“end”，然后将游标移至带有正确标识的 Begin/End 之间的新行。
SQLEditor_beginEndStatement_preview=BEGIN\n\t${cursor}\nEND

SQLEditor_typingAidsTable_context_all=全部

SQLEditor_typingAids_preview=预览:

General_max_row_num=最大行号必须大于零。
General_invalid_int=\ 不是有效的整数

GeneralPreferencePage_portable_target=无
GeneralPreferencePage_execute_error_mode=执行 SQL 期间发生错误时是否继续
GeneralPreferencePage_execute_always=始终(&L)
GeneralPreferencePage_execute_never=从不(&N)
GeneralPreferencePage_execute_prompt=提示(&R)
GeneralPreferencePage_savebeforerenaming_prompt=提示(&O)
GeneralPreferencePage_savebeforerenaming_always=始终(&W)
GeneralPreferencePage_title=常规设置
GeneralPreferencePage_description=数据库开发工具的常规设置。
GeneralPreferencePage_hover_affordance=在悬浮窗口中显示有关粘附方式的接受度(&H)
GeneralPreferencePage_portable_check=可移植性检查目标(&P):

SyntaxColoringPage_description=语法颜色和样式设置。
SyntaxColoringPage_color=颜色(&C):
SyntaxColoringPage_bold=粗体(&B)
SyntaxColoringPage_italic=斜体(&I)
SyntaxColoringPage_strikethrough=删除线(&S)
SyntaxColoringPage_underline=下划线(&U)
SyntaxColoringPage_preview=预览(&W):
SyntaxColoringPage_syntax_items=语法项目(&Y):
SyntaxColoringPage_default_foreground_color=默认前景色(&F)
