
CodeAssist_description=Paramètres Code Assist pour l'éditeur SQL
CodeAssist_general_title=&Général
CodeAssist_showSystemGroup=Afficher les objets de la base de données
CodeAssist_showSystemTables=Afficher les &tables du système
CodeAssist_showSystemProcedures=Afficher les &procédures et fonctions du système
CodeAssist_showOwnerOfTable=Afficher le pr&opriétaire de la table ou de la vue
CodeAssist_asa_tips=Les préférences suivantes sont disponibles uniquement pour la base de données SQL Anywhere :
CodeAssist_showSystemViews=Afficher les &vues du système
CodeAssist_asa_titile=&ASA
CodeAssist_insertSingleProposals=&Insérer automatiquement des propositions uniques
CodeAssist_autoActivationGroup=Activation automatique
CodeAssist_enableAuto=Activ&er l'activation automatique
CodeAssist_autoActivationDelay=Retard d'activation a&utomatique :
CodeAssist_autoActivationTriggers=L'activation automatique se déclenche pour SQL :




SQLEditor_general_title=&Général
SQLEditor_syntaxValidationGroup=Validation de &syntaxe
SQLEditor_syntaxValidation=&Activer la validation de syntaxe
SQLEditor_syntaxValidation_tooltip=Effectuer une validation de syntaxe et mettre à jour les structures d'instructions SQL dans la vue de contour
SQLEditor_maxLineButton=Nombre &maximum de lignes :
SQLEditor_maxLineButton_tooltip=Désactiver la validation de syntaxe lorsque le contenu dépasse le nombre maximum de lignes
SQLEditor_showPromptDialog=Invite de désactivation de la validation de syntaxe lorsque le contenu dépasse le nombre maximum de lignes

SQLEditor_showSyntaxErorrDetail=Affic&her les informations d'annotations détaillées
SQLEditor_showSyntaxErorrDetail_tooltip=Afficher les informations d'annotations détaillées telles que certaines suggestions de syntaxe

SQLEditor_typing_title=&Saisie
SQLEditor_typingAidsGroup_title=Activer ces aides à la saisie dans le mode d'insertion intelligent :
SQLEditor_typingAidsTable_columnName1=Nom
SQLEditor_typingAidsTable_columnName2=Contexte
SQLEditor_typingAidsTable_columnName3=Description

SQLEditor_closeSingleQuotes=Fermer les guillemets simples
SQLEditor_closeSingleQuotes_description=Si activés, fermer les guillemets simples.
SQLEditor_closeSingleQuotes_preview='${cursor}'

SQLEditor_closeDoubleQuotes=Fermer les guillemets doubles
SQLEditor_closeDoubleQuotes_description=Si activés, fermer les guillemets doubles.
SQLEditor_closeDoubleQuotes_preview="${cursor}"

SQLEditor_closeBrackets=Fermer les parenthèses
SQLEditor_closeBrackets_description=Si activées, fermer les parenthèses.
SQLEditor_closeBrackets_preview=(${cursor})

SQLEditor_closeComments=Fermer les commentaires
SQLEditor_closeComments_description=Si activés, fermer les commentaires multilignes SQL.
SQLEditor_closeComments_preview=/*\n *${cursor}\n */


SQLEditor_beginEndStatement=Début-Fin
SQLEditor_beginEndStatement_description=Ajouter la 'fin' en respectant le retrait de texte, puis déplacer le curseur sur une nouvelle ligne entre le début et la fin en respectant le retrait de texte.
SQLEditor_beginEndStatement_preview=BEGIN\n\t${cursor}\nEND

SQLEditor_typingAidsTable_context_all=Tous

SQLEditor_typingAids_preview=Aperçu :

General_max_row_num=Le nombre maximum de lignes doit être supérieur à zéro.
General_invalid_int=\ n'est pas un entier valide

GeneralPreferencePage_portable_target=Aucun
GeneralPreferencePage_execute_error_mode=Continuer lorsqu'une erreur se produit lors de l'exécution de SQL ?
GeneralPreferencePage_execute_always=&Toujours
GeneralPreferencePage_execute_never=&Jamais
GeneralPreferencePage_execute_prompt=&Invite
GeneralPreferencePage_savebeforerenaming_prompt=&Invite
GeneralPreferencePage_savebeforerenaming_always=&Toujours
GeneralPreferencePage_title=Paramètres généraux
GeneralPreferencePage_description=Paramètres généraux pour les outils de développement de base de données.
GeneralPreferencePage_hover_affordance=Indiquer comment rendre l'élément copiable lors du pointage
GeneralPreferencePage_portable_check=&Cible de vérification de portabilité :

SyntaxColoringPage_description=Paramètres de couleurs et de style pour la syntaxe.
SyntaxColoringPage_color=&Couleur :
SyntaxColoringPage_bold=&Gras
SyntaxColoringPage_italic=&Italique
SyntaxColoringPage_strikethrough=&Barré
SyntaxColoringPage_underline=&Texte souligné
SyntaxColoringPage_preview=Pré&visualisation :
SyntaxColoringPage_syntax_items=Eléments de s&yntaxe :
SyntaxColoringPage_default_foreground_color=Default &foreground color
