
CodeAssist_description=SQL エディタのコードアシストの設定
CodeAssist_general_title=全般(&G)
CodeAssist_showSystemGroup=データベースオブジェクトの表示
CodeAssist_showSystemTables=システムのテーブルを表示する(&T)
CodeAssist_showSystemProcedures=システムのプロシージャと関数を表示する(&P)
CodeAssist_showOwnerOfTable=テーブルやビューの所有者を表示する(&O)
CodeAssist_asa_tips=次の環境設定は SQL Anywhere データベースでのみ使用できます :
CodeAssist_showSystemViews=システムのビューを表示する(&V)
CodeAssist_asa_titile=ASA(&A)
CodeAssist_insertSingleProposals=1 つの提案を自動的に挿入する(&I)
CodeAssist_autoActivationGroup=自動アクティブ化
CodeAssist_enableAuto=自動アクティブ化を有効にする(&E)
CodeAssist_autoActivationDelay=自動アクティブ化の遅延(&U) :
CodeAssist_autoActivationTriggers=SQL の自動アクティブ化のトリガ :




SQLEditor_general_title=全般(&G)
SQLEditor_syntaxValidationGroup=構文の検証(&S)
SQLEditor_syntaxValidation=構文の検証を有効にする(&N)
SQLEditor_syntaxValidation_tooltip=アウトラインビューで構文を検証し、SQL 文の構造を更新します。
SQLEditor_maxLineButton=最大行数(&M) :
SQLEditor_maxLineButton_tooltip=コンテキストが最大行数を超えた場合は構文の検証を無効する
SQLEditor_showPromptDialog=コンテキストが最大行数を超えた場合は構文の検証を無効にするメッセージを表示します。

SQLEditor_showSyntaxErorrDetail=詳細な注釈情報を表示する(&H)
SQLEditor_showSyntaxErorrDetail_tooltip=構文の提案などの詳細な注釈情報を表示する

SQLEditor_typing_title=入力(&T)
SQLEditor_typingAidsGroup_title=スマート挿入モードで次の入力補助機能を有効にする :
SQLEditor_typingAidsTable_columnName1=名前
SQLEditor_typingAidsTable_columnName2=コンテキスト
SQLEditor_typingAidsTable_columnName3=説明

SQLEditor_closeSingleQuotes=一重引用符を閉じる
SQLEditor_closeSingleQuotes_description=有効な場合は、一重引用符を閉じます。
SQLEditor_closeSingleQuotes_preview='${cursor}'

SQLEditor_closeDoubleQuotes=二重引用符を閉じる
SQLEditor_closeDoubleQuotes_description=有効な場合は、二重引用符を閉じます。
SQLEditor_closeDoubleQuotes_preview="${cursor}"

SQLEditor_closeBrackets=かっこを閉じる
SQLEditor_closeBrackets_description=有効な場合は、かっこを閉じます。
SQLEditor_closeBrackets_preview=(${cursor})

SQLEditor_closeComments=コメントを閉じる
SQLEditor_closeComments_description=有効な場合は、SQL の複数行のコメントを閉じます。
SQLEditor_closeComments_preview=/*\n *${cursor}\n */


SQLEditor_beginEndStatement=Begin-End
SQLEditor_beginEndStatement_description=適切なインデントで 'end' を追加し、Begin と End の間を改行して適切なインデントを指定します。
SQLEditor_beginEndStatement_preview=BEGIN\n\t${cursor}\nEND

SQLEditor_typingAidsTable_context_all=すべて

SQLEditor_typingAids_preview=プレビュー :

General_max_row_num=最大行数はゼロより大きくしてください。
General_invalid_int=\ は無効な整数です。

GeneralPreferencePage_portable_target=なし
GeneralPreferencePage_execute_error_mode=SQL の実行中にエラーが発生した場合に、続行するかどうかを指定します。
GeneralPreferencePage_execute_always=常に続行する(&L)
GeneralPreferencePage_execute_never=続行しない(&N)
GeneralPreferencePage_execute_prompt=確認メッセージを表示する(&R)
GeneralPreferencePage_savebeforerenaming_prompt=確認メッセージを表示する(&O)
GeneralPreferencePage_savebeforerenaming_always=常に続行する(&W)
GeneralPreferencePage_title=一般設定
GeneralPreferencePage_description=データベース開発ツールの一般的な設定。
GeneralPreferencePage_hover_affordance=ツールチップを表示したままの状態にする方法についてアフォーダンスをツールチップに表示する(&H)
GeneralPreferencePage_portable_check=移植性チェックのターゲット(&P) :

SyntaxColoringPage_description=構文の色とスタイルの設定
SyntaxColoringPage_color=カラー(&C) :
SyntaxColoringPage_bold=太字(&B)
SyntaxColoringPage_italic=斜体(&I)
SyntaxColoringPage_strikethrough=取り消し線(&S)
SyntaxColoringPage_underline=下線(&U)
SyntaxColoringPage_preview=プレビュー(&W) :
SyntaxColoringPage_syntax_items=構文項目(&Y) :

