
CodeAssist_description=SQL 편집자용 코드 지원 설정
CodeAssist_general_title=일반(&G)
CodeAssist_showSystemGroup=데이터베이스 개체 보기
CodeAssist_showSystemTables=시스템 테이블 보기(&T)
CodeAssist_showSystemProcedures=시스템 프로시저와 함수 보기
CodeAssist_showOwnerOfTable=테이블 또는 뷰 소유자 보기
CodeAssist_asa_tips=다음 기본 설정은 SQL Anywhere 데이터베이스에만 사용할 수 있습니다:
CodeAssist_showSystemViews=시스템 뷰 보기(&V)
CodeAssist_asa_titile=&ASA(&A)
CodeAssist_insertSingleProposals=단일 제안 자동 삽입(&I)
CodeAssist_autoActivationGroup=자동 활성화
CodeAssist_enableAuto=자동 실행 사용(&E)
CodeAssist_autoActivationDelay=자동 실행 지연(&U)
CodeAssist_autoActivationTriggers=SQL용 자동 실행 트리거:




SQLEditor_general_title=일반(&G)
SQLEditor_syntaxValidationGroup=구문 유효성 검사(&S)
SQLEditor_syntaxValidation=구문 유효성 검사 사용(&N)
SQLEditor_syntaxValidation_tooltip=구문 유효성 검사를 실행하고 윤곽선 보기의 SQL 문 구조를 업데이트 하십시오.
SQLEditor_maxLineButton=최대 줄 수(&M):
SQLEditor_maxLineButton_tooltip=내용이 최대 줄 수를 초과하면 구문 유효성 검사를 사용할 수 없습니다.
SQLEditor_showPromptDialog=내용이 최대 줄 수를 초과하면 구문 유효성 검사를 즉시 사용할 수 없습니다.

SQLEditor_showSyntaxErorrDetail=상세 주석 정보표시(&H)
SQLEditor_showSyntaxErorrDetail_tooltip=몇 가지 구문 제안과 같은 상세 주석 정보 보기

SQLEditor_typing_title=입력(&T)
SQLEditor_typingAidsGroup_title=스마트 삽입 모드의 입력 보조 기능 사용:
SQLEditor_typingAidsTable_columnName1=이름
SQLEditor_typingAidsTable_columnName2=컨텍스트
SQLEditor_typingAidsTable_columnName3=설명

SQLEditor_closeSingleQuotes=작은 따옴표 닫기
SQLEditor_closeSingleQuotes_description=사용 가능한 경우, 작은 따옴표를 닫으십시오.
SQLEditor_closeSingleQuotes_preview='${커서}'

SQLEditor_closeDoubleQuotes=큰 따옴표 닫기
SQLEditor_closeDoubleQuotes_description=사용 가능한 경우, 큰 따옴표를 닫으십시오.
SQLEditor_closeDoubleQuotes_preview="${커서}"

SQLEditor_closeBrackets=괄호 닫기
SQLEditor_closeBrackets_description=사용 가능한 경우, 괄호를 닫으십시오.
SQLEditor_closeBrackets_preview=(${커서})

SQLEditor_closeComments=설명 닫기
SQLEditor_closeComments_description=사용 가능한 경우, 다중 선 설명을 닫으십시오.
SQLEditor_closeComments_preview=/*\n *${커서}\n */


SQLEditor_beginEndStatement=BEGIN-END
SQLEditor_beginEndStatement_description=알맞게 들여쓰기하여 '끝'을 추가한 다음, 커서를 알맞게 들여쓰기하여 시작/끝 사이의 새 줄로 이동하십시오.
SQLEditor_beginEndStatement_preview=BEGIN\n\t${커서}\nEND

SQLEditor_typingAidsTable_context_all=모두

SQLEditor_typingAids_preview=미리 보기:

General_max_row_num=최대 줄 번호는 0보다 커야 합니다.
General_invalid_int=\ 올바른 정수 아님

GeneralPreferencePage_portable_target=없음
GeneralPreferencePage_execute_error_mode=SQL 실행 중 오류가 발생했을 때 계속 여부
GeneralPreferencePage_execute_always=항상(&L)
GeneralPreferencePage_execute_never=안 함(&N)
GeneralPreferencePage_execute_prompt=묻기(&R)
GeneralPreferencePage_savebeforerenaming_prompt=묻기(&O)
GeneralPreferencePage_savebeforerenaming_always=항상(&W)
GeneralPreferencePage_title=일반 설정
GeneralPreferencePage_description=데이터베이스 개발 도구의 일반 설정.
GeneralPreferencePage_hover_affordance=가리킴의 행동 유동성 보기(&H)
GeneralPreferencePage_portable_check=이식성 확인 대상(&P):

SyntaxColoringPage_description=해당 구문의 색상 및 스타일 설정
SyntaxColoringPage_color=색상(&C):
SyntaxColoringPage_bold=굵게(&B)
SyntaxColoringPage_italic=기울임꼴(&I)
SyntaxColoringPage_strikethrough=취소선(&S)
SyntaxColoringPage_underline=밑줄(&U)
SyntaxColoringPage_preview=미리 보기(&W):
SyntaxColoringPage_syntax_items=구문 항목(&Y):
SyntaxColoringPage_default_foreground_color=Default &foreground color
