ParseException_expecting=Attendait :
ParseException_encountered=Rencontrée "
ParseException_atline=" à la ligne
ParseException_atcolumn=, colonne
ParseException_period=.
ParseException_expection_oneof=Attendait un :

JavaCharStream_invalid_escape=Caractère d'échappement invalide à la ligne {0} colonne {0}.

SimpleNode_1=Erreur lors de la tentative de récupération de l'emplacement du nœud :
SimpleNode_2=Erreur lors de la récupération du texte SQL :
SimpleNode_3=Erreur lors de la tentative de suppression du nœud :

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = La valeur de précision doit être supérieure à zéro
SQLParser_datatype_judgeLengthAndScale = Vous devez spécifier une échelle inférieure ou égale à la taille
SQLParser_datatype_exceed_maxlength = La longueur maximum autorisée de la chaîne en octets est 32767.

TokenMgrError_lexical_error=Erreur lexicale à la ligne {0}, colonne {1}.  Rencontrée : {2}, après : "{3}"
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})

