ParseException_expecting=Erwartet wurde:
ParseException_encountered=Vorgefunden "
ParseException_atline=" auf Zeile
ParseException_atcolumn=, in Spalte
ParseException_period=.
ParseException_expection_oneof=Erwartet wurde einer der folgenden:

JavaCharStream_invalid_escape=Ungültiges Escape-Zeichen auf Zeile {0} in Spalte {0}.

SimpleNode_1=Fehler beim Versuch, die Position des Knotens zu ermitteln:
SimpleNode_2=Fehler beim Abrufen von SQL-Text:
SimpleNode_3=Fehler beim Versuch, den Knoten zu löschen:

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = Präzision muss größer als Null sein.
SQLParser_datatype_judgeLengthAndScale = Sie müssen eine Skalierung angeben, die gleich der Größe oder kleiner als diese ist
SQLParser_datatype_exceed_maxlength = Die maximal zulässige Länge der Zeichenfolge in Byte ist 32767.

TokenMgrError_lexical_error=Lexikalischer Fehler auf Zeile {0}, in Spalte {1}. Vorgefunden: {2}, nach : "{3}"
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})
