ParseException_expecting=필요:
ParseException_encountered=발생 "
ParseException_atline="이(가) 열
ParseException_atcolumn=줄에 발생했습니다.
ParseException_period=.
ParseException_expection_oneof=다음 중 하나 필요:

JavaCharStream_invalid_escape=열 {0} 줄 {0}에 잘못된 확장 문자가 있습니다.

SimpleNode_1=노드의 위치를 가져오는 중 오류가 발생했습니다.
SimpleNode_2=SQL 텍스트를 가져오는 중 오류가 발생했습니다.
SimpleNode_3=노드 삭제 중 오류 발생:

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 정밀도는 0보다 커야 합니다.
SQLParser_datatype_judgeLengthAndScale = 0보다 작거나 같은 배율을 지정해야 합니다.
SQLParser_datatype_exceed_maxlength = 문자열의 최대 허용 길이(바이트)는 32767입니다.

TokenMgrError_lexical_error=줄 {0}, 열 {1}에서 어휘 오류가 발생했습니다. 다음 이후 발생: {2}, 먼저 발생한 오류 : "{3}"
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})

