ParseException_expecting=预期:
ParseException_encountered=遇到 "
ParseException_atline="，行
ParseException_atcolumn=，列
ParseException_period=。
ParseException_expection_oneof=预期下列之一:

JavaCharStream_invalid_escape=第 {0} 行第 {0} 列出现无效转义字符。

SimpleNode_1=尝试获取节点位置时出错:
SimpleNode_2=执行 getSQLText 时出错:
SimpleNode_3=尝试删除节点时出错:

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 精度必须大于零
SQLParser_datatype_judgeLengthAndScale = 必须指定小于或等于该大小的数值
SQLParser_datatype_exceed_maxlength = 允许的最大字符串字节长度为 32767。

TokenMgrError_lexical_error=第 {0} 行第 {1} 列出现词法错误。在“{3}”之后遇到了 {2}。
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})

