ParseException_expecting=結果の予測値 :
ParseException_encountered=実際の結果 : "
ParseException_atline=" 行 :
ParseException_atcolumn=、列 :
ParseException_period=
ParseException_expection_oneof=結果の予想値 (次のうちの 1 つ) :

JavaCharStream_invalid_escape=行 {0}、列 {0} にあるエスケープ文字が無効です。

SimpleNode_1=ノードの位置を取得中にエラーが発生しました :
SimpleNode_2=getSQLText でエラーが発生しました :
SimpleNode_3=ノードの削除中にエラーが発生しました :

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 精度はゼロよりも大きな値にしてください。
SQLParser_datatype_judgeLengthAndScale = スケールはサイズ以下の値にしてください。
SQLParser_datatype_exceed_maxlength = 文字列の長さは最大 32767 バイトです。

TokenMgrError_lexical_error=行 {0}、列 {1} で語彙エラーが発生しました  : {2} ("{3}" の後)
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})

