ParseException_expecting=Se esperaba:
ParseException_encountered=Se ha encontrado "
ParseException_atline=" en la línea
ParseException_atcolumn=, columna
ParseException_period=.
ParseException_expection_oneof=Se esperaba uno de:

JavaCharStream_invalid_escape=Carácter de escape no válido en la línea {0} columna {0}.

SimpleNode_1=Error al intentar obtener la posición del nodo:
SimpleNode_2=Error en getSQLText:
SimpleNode_3=Error al intentar eliminar nodo:

####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = Precisión debe ser mayor que cero
SQLParser_datatype_judgeLengthAndScale = Debe especificar una escala que sea menor o igual que el tamaño
SQLParser_datatype_exceed_maxlength = La longitud máxima en bytes del string permitida es de 32767.

TokenMgrError_lexical_error=Error léxico en la línea {0}, columna {1}.  Se ha encontrado: {2}, después: "{3}"
TokenMgrError_eof=<EOF>
TokenMgrError_currentchar="{0}" ({1})

