####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =Projekt &erstellen...
ResourceAndContainerGroup_error_linked_project=Ungültiger übergeordneter Ordner. Wählen Sie ein nicht verknüpftes Projekt aus.

showAdvanced = &Erweitert >>
hideAdvanced = << &Erweitert

ResourceGroup_resource = Ressource
ResourceGroup_nameExists = Dieser Name ist bereits vorhanden.
ResourceGroup_folderEmpty = Wählen Sie einen Projektordner aus.
ResourceGroup_noProject = Das angegebene Projekt existiert nicht.
ResourceGroup_emptyName = Der Name ''{0}" ist leer.
ResourceGroup_invalidFilename = ''{0}'' ist kein gültiger Dateiname.

# --- New File ---
WizardNewFileCreationPage_progress = Wird erstellt
WizardNewFileCreationPage_errorTitle = Probleme bei der Erstellung
WizardNewFileCreationPage_fileLabel = Dateina&me:
WizardNewFileCreationPage_file = Datei
WizardNewFileCreationPage_internalErrorTitle = Probleme bei der Erstellung
WizardNewFileCreationPage_internalErrorMessage = Interner Fehler: {0}
WizardNewFileCreationPage_error_create_file="Ausnahme in {0}.getNewFile(): {1}"

# --- TextEditor Save As ---
Editor_error_save_message=Speichervorgang konnte nicht abgeschlossen werden. {0}
Editor_error_save_title=Probleme beim Speichern-unter-Vorgang...
Editor_warning_save_delete=Die Originaldatei ''{0}'' wurde gelöscht.

CreateFolderAction_text = &Ordner erstellen...
CreateFolderAction_toolTip = Neuen Ordner erstellen
CreateFolderAction_title = Neu

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = Wählen Sie den übergeordneten Ordner aus, oder &geben Sie einen Namen ein:
ContainerGroup_selectFolder = Wählen Sie den Ordner aus:
