####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =프로젝트 생성(&C)...
ResourceAndContainerGroup_error_linked_project=잘못된 부모 폴더입니다. 연결되지 않은 프로젝트를 선택하십시오.

showAdvanced = 고급(&A)>>
hideAdvanced = << 고급(&A)

ResourceGroup_resource = 리소스
ResourceGroup_nameExists = 동일한 이름이 이미 있습니다.
ResourceGroup_folderEmpty = 프로젝트 폴더를 선택하십시오.
ResourceGroup_noProject = 지정된 프로젝트가 없습니다.
ResourceGroup_emptyName = ''{0}'' 이름이 비어 있습니다.
ResourceGroup_invalidFilename = ''{0}''은(는) 잘못된 파일 이름입니다.

# --- New File ---
WizardNewFileCreationPage_progress = 만드는 중
WizardNewFileCreationPage_errorTitle = 생성 문제
WizardNewFileCreationPage_fileLabel = 파일 이름(&M):
WizardNewFileCreationPage_file = 파일
WizardNewFileCreationPage_internalErrorTitle = 생성 문제
WizardNewFileCreationPage_internalErrorMessage = 내부 오류: {0}
WizardNewFileCreationPage_error_create_file="{0}에 예외가 발생했습니다. getNewFile(): {1}"

# --- TextEditor Save As ---
Editor_error_save_message=저장을 완료할 수 없습니다. {0}
Editor_error_save_title=다른 이름으로 저장 중 문제 발생...
Editor_warning_save_delete=원본 파일 ''{0}''이(가) 삭제되었습니다.

CreateFolderAction_text = 폴더 생성(&L)...
CreateFolderAction_toolTip = 새 폴더 생성
CreateFolderAction_title = 새로 만들기

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = 부모 폴더 입력 또는 선택(&E):
ContainerGroup_selectFolder = 폴더 선택:
