####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =创建项目(&C)...
ResourceAndContainerGroup_error_linked_project=无效父文件夹。选择未链接的项目。

showAdvanced = 高级(&A) >>
hideAdvanced = << 高级(&A)

ResourceGroup_resource = 资源
ResourceGroup_nameExists = 相同名称已存在。
ResourceGroup_folderEmpty = 选择项目文件夹
ResourceGroup_noProject = 指定的项目不存在。
ResourceGroup_emptyName = “{0}”名称为空。
ResourceGroup_invalidFilename = “{0}”不是有效文件名。

# --- New File ---
WizardNewFileCreationPage_progress = 创建
WizardNewFileCreationPage_errorTitle = 创建问题
WizardNewFileCreationPage_fileLabel = 文件名(&M):
WizardNewFileCreationPage_file = 文件
WizardNewFileCreationPage_internalErrorTitle = 创建问题
WizardNewFileCreationPage_internalErrorMessage = 内部错误:{0}
WizardNewFileCreationPage_error_create_file=“{0}.getNewFile() 中出现异常: {1}”

# --- TextEditor Save As ---
Editor_error_save_message=无法完成保存操作。{0}
Editor_error_save_title=执行“另存为...”操作期间发生问题。
Editor_warning_save_delete=已删除原始文件“{0}”。

CreateFolderAction_text = 创建文件夹(&O)...
CreateFolderAction_toolTip = 创建新文件夹
CreateFolderAction_title = 新建

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = 输入或选择父文件夹(&E):
ContainerGroup_selectFolder = 选择文件夹:
