####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =プロジェクトの作成(&C)...
ResourceAndContainerGroup_error_linked_project=親フォルダが無効です。リンクされていないプロジェクトを選択してください。

showAdvanced = 詳細設定(&A) >>
hideAdvanced = << 詳細設定(&A)

ResourceGroup_resource = リソース
ResourceGroup_nameExists = 同じ名前はすでに使用されています。
ResourceGroup_folderEmpty = プロジェクトフォルダを選択してください。
ResourceGroup_noProject = 指定したプロジェクトは存在しません。
ResourceGroup_emptyName = ''{0}'' の名前が空です。
ResourceGroup_invalidFilename = ''{0}'' は有効なファイル名ではありません。

# --- New File ---
WizardNewFileCreationPage_progress = 作成中
WizardNewFileCreationPage_errorTitle = 作成エラー
WizardNewFileCreationPage_fileLabel = ファイル名(&M) :
WizardNewFileCreationPage_file = file
WizardNewFileCreationPage_internalErrorTitle = 作成エラー
WizardNewFileCreationPage_internalErrorMessage = 内部エラー : {0}
WizardNewFileCreationPage_error_create_file="{0}.getNewFile(): {1} で例外が発生しました。"

# --- TextEditor Save As ---
Editor_error_save_message=保存できません。
Editor_error_save_title=名前を付けて保存中にエラーが発生しました...
Editor_warning_save_delete=元のファイル ''{0}'' は削除されています。

CreateFolderAction_text = フォルダの作成(&O)...
CreateFolderAction_toolTip = フォルダの新規作成
CreateFolderAction_title = 新規

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = 親フォルダの入力・選択(&E) :
ContainerGroup_selectFolder = フォルダの選択 :
