####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =&Crear proyecto...
ResourceAndContainerGroup_error_linked_project=Carpeta principal no válida. Seleccione un proyecto no vinculado.

showAdvanced = &Avanzado>>
hideAdvanced = << &Avanzado

ResourceGroup_resource = recurso
ResourceGroup_nameExists = Este nombre ya existe.
ResourceGroup_folderEmpty = Seleccione una carpeta de proyecto.
ResourceGroup_noProject = El proyecto especificado no existe.
ResourceGroup_emptyName = El nombre ''{0}'' está vacío.
ResourceGroup_invalidFilename = ''{0}'' no es un nombre de archivo válido.

# --- New File ---
WizardNewFileCreationPage_progress = Creando
WizardNewFileCreationPage_errorTitle = Problemas en la creación
WizardNewFileCreationPage_fileLabel = No&mbre de archivo:
WizardNewFileCreationPage_file = archivo
WizardNewFileCreationPage_internalErrorTitle = Problemas en la creación
WizardNewFileCreationPage_internalErrorMessage = Error interno: {0}
WizardNewFileCreationPage_error_create_file="Excepción en {0}.getNewFile(): {1}"

# --- TextEditor Save As ---
Editor_error_save_message=No se ha podido guardar. {0}
Editor_error_save_title=Problemas al guardar como...
Editor_warning_save_delete=Se ha eliminado el archivo original ''{0}''.

CreateFolderAction_text = Crear &carpeta...
CreateFolderAction_toolTip = Crear nueva carpeta
CreateFolderAction_title = Nuevo

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = &Introduzca o seleccione la carpeta principal:
ContainerGroup_selectFolder = Seleccione la carpeta:
