####################################################
#  ContainerSelectionGroup resource Message
####################################################
ContainerSelectionGroup_createProjectAction_label =&Créer un projet...
ResourceAndContainerGroup_error_linked_project=Dossier parent invalide. Sélectionner un projet non associé.

showAdvanced = &Avancé >>
hideAdvanced = << &Avancé

ResourceGroup_resource = ressource
ResourceGroup_nameExists = Ce nom existe déjà.
ResourceGroup_folderEmpty = Sélectionner un dossier projet.
ResourceGroup_noProject = Le projet spécifié n'existe pas.
ResourceGroup_emptyName = Le nom ''{0}'' est vide.
ResourceGroup_invalidFilename = ''{0}'' n'est pas un nom de fichier valide.

# --- New File ---
WizardNewFileCreationPage_progress = Création en cours
WizardNewFileCreationPage_errorTitle = Problèmes de création
WizardNewFileCreationPage_fileLabel = No&m de fichier :
WizardNewFileCreationPage_file = fichier
WizardNewFileCreationPage_internalErrorTitle = Problèmes de création
WizardNewFileCreationPage_internalErrorMessage = Erreur interne : {0}
WizardNewFileCreationPage_error_create_file="Exception dans {0}.getNewFile() : {1}"

# --- TextEditor Save As ---
Editor_error_save_message=La sauvegarde a échoué. {0}
Editor_error_save_title=Problèmes lors de l'enregistrement sous...
Editor_warning_save_delete=Le fichier original ''{0}'' a été supprimé.

CreateFolderAction_text = Créer un d&ossier...
CreateFolderAction_toolTip = Créer un nouveau dossier
CreateFolderAction_title = Nouveau

####################################
# Copied from IDEWorkbenchMessages
####################################
ContainerGroup_message = &Entrer ou sélectionner le dossier parent :
ContainerGroup_selectFolder = Sélectionner le dossier :
