###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Apache Derby Database Definition
providerName=Eclipse Data Tools Platform

100ProductString = Derby
100VersionString = 10.0

101ProductString = Derby
101VersionString = 10.1

102ProductString = Derby
102VersionString = 10.2
