###############################################################################
#
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform Flat File ODA Runtime Driver
datasource.name=텍스트 파일 데이터 소스
dataset.name=텍스트 파일 데이터 세트
oda.data.source.category.name=플랫 파일 데이터 원본
connection.profile.name=ODA 플랫 파일 데이터 원본 연결 프로필

datasource.property.home=홈 폴더(&F)
datasource.property.csvdelimitertype=CSV 형식(&T)
datasource.property.charset=문자 집합(&C)
datasource.property.incltypeline=데이터 형식 표시기로 두 번째 줄 사용(&D)
datasource.property.inclcolumnnameline=열 이름 표시기로 첫 번째 줄 사용(&N)
datasource.property.trailnullcols=널(null) 열 추적 사용
datasource.property.uri=File &URI

dataset.property.savedcolumnsinfo=각 열에 관한 정보

property.value.yes=예
property.value.no=아니오
property.value.comma=쉼표
property.value.semicolon=세미콜론
property.value.pipe=파이프
property.value.tab=탭
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
