plugin.name=DTP ODA 平面文件运行时驱动程序
datasource.name=平面文件数据源
dataset.name=平面文件数据集

datasource.property.home=主文件夹(&F)
datasource.property.csvdelimitertype=CSV 类型(&T)
datasource.property.charset=字符集(&C)
datasource.property.incltypeline=将第二行用作数据类型指示器(&D)
datasource.property.inclcolumnnameline=使用第一行作为列名称指示器(&N)

dataset.property.savedcolumnsinfo=关于每列的信息
property.value.yes=是
property.value.no=否
property.value.comma=逗号
property.value.semicolon=分号
property.value.pipe=竖线
property.value.tab=制表符
