###############################################################################
#
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform Flat File ODA Runtime Driver
datasource.name=Datenquelle für Flachdatei
dataset.name=Datensatz für Flachdatei
oda.data.source.category.name=Unstrukturierte Datenquelle
connection.profile.name=ODA-Verbindungsprofil für unstrukturierte Datenquelle

datasource.property.home=Stamm&ordner
datasource.property.csvdelimitertype=CSV-&Typ
datasource.property.charset=&Zeichensatz
datasource.property.incltypeline=Zweite Zeile als &Datentypindikator verwenden
datasource.property.inclcolumnnameline=Erste Zeile als Spalten&namenindikator verwenden
datasource.property.trailnullcols=Spalten mit Nullen in Endposition verwenden
datasource.property.uri=Datei-&URI

dataset.property.savedcolumnsinfo=Informationen zu den einzelnen Spalten

property.value.yes=Ja
property.value.no=Nein
property.value.comma=KOMMA
property.value.semicolon=SEMIKOLON
property.value.pipe=PIPE
property.value.tab=TAB
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
