plugin.name=Laufzeittreiber für DTP-ODA-Flachdatei
datasource.name=Datenquelle für Flachdatei
dataset.name=Datensatz für Flachdatei

datasource.property.home=Stamm&ordner
datasource.property.csvdelimitertype=CSV-&Typ
datasource.property.charset=&Zeichensatz
datasource.property.incltypeline=Zweite Zeile als &Datentypindikator verwenden
datasource.property.inclcolumnnameline=Erste Zeile als Spalten&namenindikator verwenden

dataset.property.savedcolumnsinfo=Informationen zu den einzelnen Spalten

property.value.yes=Ja
property.value.no=Nein
property.value.comma=KOMMA
property.value.semicolon=SEMIKOLON
property.value.pipe=PIPE
property.value.tab=TAB
