###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Controlador de tiempo de ejecución de archivo plano de ODA de DTP
datasource.name=Origen de datos de archivo plano
dataset.name=Conjunto de datos de archivo plano
oda.data.source.category.name=Archivos sin formato CSV
connection.profile.name=Perfil de conexión de fuente de datos de archivo sin formato ODA

datasource.property.home=Ca&rpeta de inicio
datasource.property.csvdelimitertype=&Tipo de CSV
datasource.property.charset=Conjunto de &caracteres
datasource.property.incltypeline=Utilizar la segunda línea como indicador de tipo de &datos
datasource.property.inclcolumnnameline=Utilizar la primera línea como indicador de &nombre de columna

dataset.property.savedcolumnsinfo=La información sobre cada columna

property.value.yes=Sí
property.value.no=No
property.value.comma=COMA
property.value.semicolon=PUNTO Y COMA
property.value.pipe=CANALIZACIÓN
property.value.tab=TABULACIÓN
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
