plugin.name=Controlador de tiempo de ejecución de archivo plano de ODA de DTP
datasource.name=Origen de datos de archivo plano
dataset.name=Conjunto de datos de archivo plano

datasource.property.home=Ca&rpeta de inicio
datasource.property.csvdelimitertype=&Tipo de CSV
datasource.property.charset=Conjunto de &caracteres
datasource.property.incltypeline=Utilizar la segunda línea como indicador de tipo de &datos
datasource.property.inclcolumnnameline=Utilizar la primera línea como indicador de &nombre de columna

dataset.property.savedcolumnsinfo=La información sobre cada columna

property.value.yes=Sí
property.value.no=No
property.value.comma=COMA
property.value.semicolon=PUNTO Y COMA
property.value.pipe=CANALIZACIÓN
property.value.tab=TABULACIÓN
