plugin.name=Controlador de tiempo de ejecución de archivo plano de ODA de DTP
datasource.name=Origen de datos de archivo plano
dataset.name=Conjunto de datos de archivo plano

datasource.property.home=Ca&rpeta de inicio
datasource.property.charset=Conjunto de &caracteres
datasource.property.incltypeline=Utilizar la segunda línea como indicador de tipo de &datos
property.value.yes=Sí
property.value.no=No
