###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform Flat File ODA Runtime Driver
datasource.name=平面文件数据源
dataset.name=平面文件数据集
oda.data.source.category.name=平面文件数据源
connection.profile.name=ODA 平面文件数据源连接配置文件

datasource.property.home=主文件夹(&F)
datasource.property.csvdelimitertype=CSV 类型(&T)
datasource.property.charset=字符集(&C)
datasource.property.incltypeline=将第二行用作数据类型指示器(&D)
datasource.property.inclcolumnnameline=使用第一行作为列名称指示器(&N)

dataset.property.savedcolumnsinfo=关于每列的信息
property.value.yes=是
property.value.no=否
property.value.comma=逗号
property.value.semicolon=分号
property.value.pipe=竖线
property.value.tab=制表符
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
