plugin.name=DTP ODA Flat File Run-time Driver
datasource.name=フラット・ファイル・データ・ソース
dataset.name=フラット・ファイル・データ・セット

datasource.property.home=ホームフォルダ(&F)
datasource.property.csvdelimitertype=CSV 型(&T)
datasource.property.charset=文字セット(&C)
datasource.property.incltypeline=2 行目をデータ型のインジケータとして使用する(&D)
datasource.property.inclcolumnnameline=1 行目を列名のインジケータとして使用する(&N)

dataset.property.savedcolumnsinfo=各列の情報

property.value.yes=はい
property.value.no=いいえ
property.value.comma=コンマ
property.value.semicolon=セミコロン
property.value.pipe=パイプ
property.value.tab=タブ
