plugin.name=DTP ODA 텍스트 파일 런타임 드라이버
datasource.name=텍스트 파일 데이터 소스
dataset.name=텍스트 파일 데이터 세트

datasource.property.home=홈 폴더(&F)
datasource.property.csvdelimitertype=CSV 형식(&T)
datasource.property.charset=문자 집합(&C)
datasource.property.incltypeline=데이터 형식 표시기로 두 번째 줄 사용(&D)
datasource.property.inclcolumnnameline=열 이름 표시기로 첫 번째 줄 사용(&N)

dataset.property.savedcolumnsinfo=각 열에 관한 정보

property.value.yes=예
property.value.no=아니오
property.value.comma=쉼표
property.value.semicolon=세미콜론
property.value.pipe=파이프
property.value.tab=탭
