###############################################################################
#
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform Flat File ODA Runtime Driver
datasource.name=フラット・ファイル・データ・ソース
dataset.name=フラット・ファイル・データ・セット
oda.data.source.category.name=フラットファイルのデータソース
connection.profile.name=ODA フラットファイルのデータソースの接続プロファイル

datasource.property.home=ホームフォルダ(&F)
datasource.property.csvdelimitertype=CSV 型(&T)
datasource.property.charset=文字セット(&C)
datasource.property.incltypeline=2 行目をデータ型のインジケータとして使用する(&D)
datasource.property.inclcolumnnameline=1 行目を列名のインジケータとして使用する(&N)
datasource.property.trailnullcols=Use trail null columns

dataset.property.savedcolumnsinfo=各列の情報

property.value.yes=はい
property.value.no=いいえ
property.value.comma=コンマ
property.value.semicolon=セミコロン
property.value.pipe=パイプ
property.value.tab=タブ
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリ
