###############################################################################
#
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform Flat File ODA Runtime Driver
datasource.name=Source de données de fichier à plat
dataset.name=Ensemble de fichiers à plat
oda.data.source.category.name=Source de données sous forme de fichier plat
connection.profile.name=Profil de connexion de source de données sous forme de fichier plat ODA

datasource.property.home=Dossier &racine
datasource.property.csvdelimitertype=&Type CSV
datasource.property.charset=Jeu de &caractères
datasource.property.incltypeline=Utilisez la deuxième ligne comme indicateur du type de &données
datasource.property.inclcolumnnameline=Utiliser la première ligne en tant qu'indicateur de &nom de colonne
datasource.property.trailnullcols=Utiliser les colonnes avec valeurs nulles à la fin
datasource.property.uri=&URI de fichier

dataset.property.savedcolumnsinfo=Informations sur chaque colonne

property.value.yes=Oui
property.value.no=Non
property.value.comma=VIRGULE
property.value.semicolon=POINT-VIRGULE
property.value.pipe=BARRE DECIMALE
property.value.tab=TABULATION
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
