###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## LUW Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = Datenba&nk:
CUI_NEWCW_HOST_LBL_UI_ = &Host:
CUI_NEWCW_PORT_LBL_UI_ = &Anschlussnummer:
CUI_NEWCW_CONNECTIONURL_LBL_UI_= Verbindungs-UR&L:
CUI_NEWCW_DEFDBNAME_VAL_UI_ = BEISPIEL
CUI_NEWCW_CLIENTAUTHENTICATION_BTN_UI_ = Cl&ient-Authentifizierung verwenden
CUI_NEWCW_USERNAME_LBL_UI_ = Benutzern&ame:
CUI_NEWCW_PASSWORD_LBL_UI_ = Kenn&wort:
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = &Kennwort speichern
CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = Datenbank
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = Host:
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = Anschlussnummer
CUI_NEWCW_USE_CLIENT_AUTHENICATION_SUMMARY_DATA_TEXT_ = Client-Authentifizierung verwenden
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = Benutzername
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = Kennwort speichern
CUI_NEWCW_DEFAULT_SCHEMA_LBL_UI_ = Standardeinstellungen Schema:
CUI_NEWCW_DEFAULT_SCHEMA_SUMMARY_DATA_TEXT_ = Standardeinstellungen Schema
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = Wahr
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = Falsch

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = Geben Sie einen Datenbanknamen ein, zum Beispiel {0}.
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= Geben Sie einen Hostnamen für den Datenbankserver ein.
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = Geben Sie die Anschlussnummer der Verbindung für den Datenbankserver ein.
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = Geben Sie einen Benutzernamen ein.
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = Geben Sie ein Kennwort ein.



