####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = Präzision muss größer als Null sein.
SQLParser_datatype_judgeLengthAndScale = Sie müssen eine Skalierung angeben, die gleich der Größe oder kleiner als diese ist
SQLParser_datatype_exceed_maxlength = Die maximal zulässige Länge der Zeichenfolge in Byte ist 32767.

plugin_internal_error=Interner Fehler.

#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}\u200E
