####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 精度必须大于零
SQLParser_datatype_judgeLengthAndScale = 必须指定小于或等于该大小的数值
SQLParser_datatype_exceed_maxlength = 允许的最大字符串字节长度为 32767。

plugin_internal_error=内部错误

#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}\u200E
