####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 정밀도는 0보다 커야 합니다.
SQLParser_datatype_judgeLengthAndScale = 0보다 작거나 같은 배율을 지정해야 합니다.
SQLParser_datatype_exceed_maxlength = 문자열의 최대 허용 길이(바이트)는 32767입니다.

plugin_internal_error=내부 오류

#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}\u200E
