####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = La valeur de précision doit être supérieure à zéro
SQLParser_datatype_judgeLengthAndScale = Vous devez spécifier une échelle inférieure ou égale à la taille
SQLParser_datatype_exceed_maxlength = La longueur maximum autorisée de la chaîne en octets est 32767.

plugin_internal_error=Erreur interne.

#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}\u200E
