####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = 精度はゼロよりも大きな値にしてください。
SQLParser_datatype_judgeLengthAndScale = スケールはサイズ以下の値にしてください。
SQLParser_datatype_exceed_maxlength = 文字列の長さは最大 32767 バイトです。

plugin_internal_error=内部エラーが発生しました。

#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}\u200E
