###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = 常规
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = 跟踪

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = 禁用跟踪(&G)
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = 目录(&R):
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = 浏览(&W)...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = 文件名(&M):
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = 跟踪
CUI_NEWCW_APPEND_CHECKBOX_UI_ = 追加
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = 跟踪级别

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = 连接调用
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = 语句调用(&L)
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = 结果集调用
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = 驱动程序配置
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = 连接
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = DRDA 流
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = 结果集元数据
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = 参数元数据
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = 诊断
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = SQL J
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = XA 调用
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = 全选(&A)
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = 取消全选(&D)

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = 输入目录。
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = 输入有效目录。
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = 输入文件名。
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = 请至少选择一个跟踪级别。


