###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = 일반
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = 추적

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = 추적 해제(&G)
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = 디렉터리(&R):
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = 찾아보기(&W)...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = 파일 이름(&M):
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = 추적
CUI_NEWCW_APPEND_CHECKBOX_UI_ = 추가
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = 추적 수준

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = 연결 호출
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = 문 호출(&L)
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = 결과 집합 호출
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = 드라이버 구성
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = 연결
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = DRDA 흐름
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = 결과 집합 메타데이터
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = 매개 변수 메타데이터
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = 진단
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = SQL J
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = XA 호출
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = 모두 선택(&A)
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = 모두 선택 취소(&D)

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = 디렉터리를 입력하십시오.
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = 올바른 디렉터리를 입력하십시오.
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = 파일 이름을 입력하십시오.
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = 적어도 하나 이상의 추적 수준을 선택하십시오.



