###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = Général
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = Traçage

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = Désactiver le traça&ge
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = &Répertoire :
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = Par&courir...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = No&m de fichier :
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = trace
CUI_NEWCW_APPEND_CHECKBOX_UI_ = Ajouter
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = Niveaux de trace

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = Appels de connexions
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = Appe&ls d'instructions
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = Appels d'ensembles de résultats
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = Configuration de pilote
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = Connexion
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = Flux DRDA
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = Métadonnées d'ensembles de résultats
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = Métadonnées de paramètres
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = Diagnostics
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = J SQL
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = Appels XA
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = Sélecti&onner tout
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = &Désélectionner tout

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = Entrer un répertoire.
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = Entrer un répertoire valide.
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = Entrer un nom de fichier.
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = Sélectionner au moins un niveau de trace.

