###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = 全般
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = トレース

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = トレースを無効にする(&G)
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = ディレクトリ(&R) :
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = 参照(&W)...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = ファイル名(&M) :
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = トレース
CUI_NEWCW_APPEND_CHECKBOX_UI_ = 追加
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = トレースレベル

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = 接続の呼び出し
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = 文の呼び出し(&L)
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = 結果セットの呼び出し
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = ドライバの設定
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = 接続
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = DRDA フロー
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = 結果セットのメタデータ
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = パラメタのメタデータ
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = 診断
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = SQL J
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = XA の呼び出し
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = すべて選択(&A)
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = すべて選択解除(&D)

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = ディレクトリを入力してください。
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = 有効なディレクトリを入力してください。
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = ファイル名を入力してください。
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = 少なくとも 1 つのトレースレベルを選択してください。




