###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = General
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = Rastreo

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = Desactivar &rastreo
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = Di&rectorio:
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = E&xaminar...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = No&mbre de archivo:
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = rastreo
CUI_NEWCW_APPEND_CHECKBOX_UI_ = Anexo
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = Niveles de rastreo

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = Llamadas de conexión
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = &Llamadas de sentencias
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = Llamadas de conjunto de resultados
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = Configuración del controlador
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = Se conecta
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = Flujos de DRDA
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = Metadatos de conjunto de resultados
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = Metadatos de parámetros
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = Diagnóstico
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = SQL J
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = Llamadas de XA
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = Selecci&onar todo
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = &Anular la selección de todo

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = Introduzca un directorio.
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = Introduzca un directorio válido.
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = Introduzca un nombre de archivo.
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = Seleccione al menos un nivel de rastreo.



