###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## IBM driver tracing support
#

CUI_NEWCW_DRIVER_OPTIONS_TAB_UI_ = Allgemein
CUI_NEWCW_TRACING_OPTIONS_TAB_UI_ = Ablaufverfolgung

CUI_NEWCW_DISABLE_TRACING_CHECKBOX_UI_ = Ablaufverfolgun&g deaktivieren
CUI_NEWCW_TRACE_DIRECTORY_LABEL_UI_ = Verzei&chnis:
CUI_NEWCW_TRACE_DIRECTORY_BROWSE_BUTTON_UI_ = D&urchsuchen ...
CUI_NEWCW_TRACE_FILE_LABEL_UI_ = Dateina&me:
CUI_NEWCW_DEFAULT_TRACE_FILE_NAME_UI_ = Ablaufverfolgung
CUI_NEWCW_APPEND_CHECKBOX_UI_ = Append
CUI_NEWCW_TRACE_LEVELS_GROUPBOX_UI_ = Ablaufverfolgungsebenen

CUI_NEWCW_CONNECTION_CALLS_CHECKBOX_UI_ = Aufruf: Verbindungen
CUI_NEWCW_STATEMENT_CALLS_CHECKBOX_UI_ = Aufruf: Anweisungen
CUI_NEWCW_RESULT_SET_CALLS_CHECKBOX_UI_ = Ergebnis: Aufrufe
CUI_NEWCW_DRIVER_CONFIGURATION_CHECKBOX_UI_ = Treiberkonfiguration
CUI_NEWCW_CONNECTS_CHECKBOX_UI_ = Verbindet
CUI_NEWCW_DRDA_FLOWS_CHECKBOX_UI_ = DRDA-Durchläufe
CUI_NEWCW_RESULT_SET_METADATA_CHECKBOX_UI_ = Metadata-Ergebnisse
CUI_NEWCW_PARAMETER_METADATA_CHECKBOX_UI_ = Metadata-Parameter
CUI_NEWCW_DIAGNOSTICS_CHECKBOX_UI_ = Diagnose
CUI_NEWCW_SQLJ_CHECKBOX_UI_ = SQL J
CUI_NEWCW_XA_CALLS_CHECKBOX_UI_ = Aufruf: XA
CUI_NEWCW_SELECT_ALL_BUTTON_UI_ = Alles m&arkieren
CUI_NEWCW_DESELECT_ALL_BUTTON_UI_ = A&uswahl aufheben

CUI_NEWCW_ENTER_DIRECTORY_MESSAGE_UI_ = Geben Sie ein Verzeichnis ein.
CUI_NEWCW_ENTER_VALID_DIRECTORY_MESSAGE_UI_ = Geben Sie ein gültiges Verzeichnis ein.
CUI_NEWCW_ENTER_FILE_MESSAGE_UI_ = Geben Sie einen Dateinamen ein.
CUI_NEWCW_SELECT_TRACE_LEVEL_MESSAGE_UI_ = Wählen Sie wenigstens eine Ablaufverfolgungsebene aus.



