###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Informix Plug-in
providerName=Eclipse Data Tools Platform

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호

INFORMIX_CATEGORY_NAME = Informix
10_0_VERSION_CATEGORY_NAME = 10.0
9_4_VERSION_CATEGORY_NAME = 9.4
9_3_VERSION_CATEGORY_NAME = 9.3
9_2_VERSION_CATEGORY_NAME = 9.2

org.eclipse.datatools.enablement.ibm.informix.10_0.driverTemplate = Informix JDBC 드라이버
org.eclipse.datatools.enablement.ibm.informix.10_0.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_4.driverTemplate = Informix JDBC 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_4.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_3.driverTemplate = Informix JDBC 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_3.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_2.driverTemplate = Informix JDBC 드라이버
org.eclipse.datatools.enablement.ibm.informix.9_2.other.driverTemplate = 기타 드라이버

jdbc.connection.name = JDBC 연결
profile.informix.title = Informix
