###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Informix Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Treiberklasse
driverVendor = Anbieter
driverVersion = Version
driverDBName = Datenbankname
driverConnectionURL = Verbindungs-URL
driverUID = Benutzer-ID
driverPWD = Kennwort

INFORMIX_CATEGORY_NAME = Informix
10_0_VERSION_CATEGORY_NAME = 10.0
9_4_VERSION_CATEGORY_NAME = 9.4
9_3_VERSION_CATEGORY_NAME = 9.3
9_2_VERSION_CATEGORY_NAME = 9.2

org.eclipse.datatools.enablement.ibm.informix.10_0.driverTemplate = Informix JDBC-Treiber
org.eclipse.datatools.enablement.ibm.informix.10_0.other.driverTemplate = Anderer Treiber
org.eclipse.datatools.enablement.ibm.informix.9_4.driverTemplate = Informix JDBC-Treiber
org.eclipse.datatools.enablement.ibm.informix.9_4.other.driverTemplate = Anderer Treiber
org.eclipse.datatools.enablement.ibm.informix.9_3.driverTemplate = Informix JDBC-Treiber
org.eclipse.datatools.enablement.ibm.informix.9_3.other.driverTemplate = Anderer Treiber
org.eclipse.datatools.enablement.ibm.informix.9_2.driverTemplate = Informix JDBC-Treiber
org.eclipse.datatools.enablement.ibm.informix.9_2.other.driverTemplate = Anderer Treiber

jdbc.connection.name = JDBC-Verbindung
profile.informix.title = Informix
