###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Informix Plug-in
providerName=Eclipse Data Tools Platform

driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
driverUID = ユーザ ID
driverPWD = パスワード

INFORMIX_CATEGORY_NAME = Informix
10_0_VERSION_CATEGORY_NAME = 10.0
9_4_VERSION_CATEGORY_NAME = 9.4
9_3_VERSION_CATEGORY_NAME = 9.3
9_2_VERSION_CATEGORY_NAME = 9.2

org.eclipse.datatools.enablement.ibm.informix.10_0.driverTemplate = Informix JDBC ドライバ
org.eclipse.datatools.enablement.ibm.informix.10_0.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.ibm.informix.9_4.driverTemplate = Informix JDBC ドライバ
org.eclipse.datatools.enablement.ibm.informix.9_4.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.ibm.informix.9_3.driverTemplate = Informix JDBC ドライバ
org.eclipse.datatools.enablement.ibm.informix.9_3.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.ibm.informix.9_2.driverTemplate = Informix JDBC ドライバ
org.eclipse.datatools.enablement.ibm.informix.9_2.other.driverTemplate = その他のドライバ

jdbc.connection.name = JDBC 接続
profile.informix.title = Informix
