###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Informix UI Plug-in
providerName=Eclipse Data Tools Platform

profile.informix.wizard.title = Informix
profile.informix.wizard.description = Crear un perfil de conexión Informix.
profile.informix.properties = Propiedades de controlador
