# <copyright>
# </copyright>
#
# $Id: plugin.properties,v 1.4 2009/06/02 01:01:24 bfitzpatrick Exp $

# ====================================================================
# To code developer:
#   Do NOT change the properties between this line and the
#   "%%% END OF TRANSLATED PROPERTIES %%%" line.
#   Make a new property name, append to the end of the file and change
#   the code to use the new property.
# ====================================================================

# ====================================================================
# %%% END OF TRANSLATED PROPERTIES %%%
# ====================================================================

pluginName = Eclipse Data Tools Platform Derby Model Plug-in
providerName = Eclipse Data Tools Platform

