DRIVER_CLASS_PROPERTY_NAME=Treiberklasse
VENDOR_PROPERTY_NAME=Anbieter
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Datenbankname
CONNECTION_URL_PROPERTY_NAME=Verbindungs-URL
USER_ID_PROPERTY_NAME=Benutzer-ID
PASSWORD_PROPERTY_NAME=Kennwort

Bundle-Vendor = Eclipse-Datentools-Plattform
Bundle-Name = Eclipse-Datentools-Plattform SQLite UI Enablement Plug-In
profile.page.name = SQLite Profileigenschaften

connection.profile.newwizard = SQLite
connection.profile.newwizard.description = Erstellen Sie ein neues SQLite-Verbindungsprofil.
