DRIVER_CLASS_PROPERTY_NAME=ドライバクラス
VENDOR_PROPERTY_NAME=ベンダ
VERSION_PROPERTY_NAME=バージョン
DATABASE_NAME_PROPERTY_NAME=データベース名
CONNECTION_URL_PROPERTY_NAME=接続 URL
USER_ID_PROPERTY_NAME=ユーザ ID
PASSWORD_PROPERTY_NAME=パスワード

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform SQLite UI Enablement Plug-in
profile.page.name = SQLite のプロファイルのプロパティ

connection.profile.newwizard = SQLite
connection.profile.newwizard.description = SQLite の接続プロファイルを作成します。
