DRIVER_CLASS_PROPERTY_NAME=Clase de controlador
VENDOR_PROPERTY_NAME=Proveedor
VERSION_PROPERTY_NAME=Versión
DATABASE_NAME_PROPERTY_NAME=Nombre de base de datos
CONNECTION_URL_PROPERTY_NAME=URL de conexión
USER_ID_PROPERTY_NAME=Identificador de usuario
PASSWORD_PROPERTY_NAME=Contraseña

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Complemento de activación de IU de SQLite para Eclipse Data Tools Platform
profile.page.name = Propiedades del perfil de SQLite

connection.profile.newwizard = SQLite
connection.profile.newwizard.description = Crear un perfil de conexión SQLite.
