DRIVER_CLASS_PROPERTY_NAME=Classe de pilote
VENDOR_PROPERTY_NAME=Vendeur
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Nom de la base de données
CONNECTION_URL_PROPERTY_NAME=URL de connexion
USER_ID_PROPERTY_NAME=ID utilisateur
PASSWORD_PROPERTY_NAME=Mot de passe

Bundle-Vendor = Plate-forme d'outils de données Eclipse
Bundle-Name = Plug-in d'activation d'interface utilisateur SQLite pour la plate-forme d'outils de données Eclipse
profile.page.name = Propriétés de profil SQLite

connection.profile.newwizard = SQLite
connection.profile.newwizard.description = Créer un profil de connexion SQLite.
