DRIVER_CLASS_PROPERTY_NAME=驱动程序类
VENDOR_PROPERTY_NAME=供应商
VERSION_PROPERTY_NAME=版本
DATABASE_NAME_PROPERTY_NAME=数据库名称
CONNECTION_URL_PROPERTY_NAME=连接 URL
USER_ID_PROPERTY_NAME=用户 ID
PASSWORD_PROPERTY_NAME=密码

Bundle-Vendor = Eclipse 数据工具平台
Bundle-Name = Eclipse 数据工具平台 SQLite UI 启用插件
profile.page.name = SQLite 配置文件属性

connection.profile.newwizard = SQLite
connection.profile.newwizard.description = 创建 SQLite 连接配置文件。
