pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = Vendeur
version = Version 

driver = Pilote JDBC MaxDB
category = MaxDB
connection_url = URL de connexion
instance_name = Nom d'instance
driver_class = Classe de pilote
user_id = ID utilisateur
password = Mot de passe

profile.maxdb.title = Profil MaxDB
jdbc.connection.name = Génération de JDBC MaxDB

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
