pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = 공급업체
version = 버전 

driver = MaxDB JDBC 드라이버
category = MaxDB
connection_url = 연결 URL
instance_name = 인스턴스 이름
driver_class = 드라이버 클래스
user_id = 사용자 ID
password = 암호

profile.maxdb.title = MaxDB 프로필
jdbc.connection.name = MaxDB JDBC 팩토리

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
