pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = Proveedor
version = Versión 

driver = Controlador JDBC de MaxDB
category = MaxDB
connection_url = URL de conexión
instance_name = Nombre de instancia
driver_class = Clase de controlador
user_id = Identificador de usuario
password = Contraseña

profile.maxdb.title = Perfil de MaxDB
jdbc.connection.name = Fábrica JDBC de MaxDB

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
