pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = 供应商
version = 版本 

driver = MaxDB JDBC 驱动程序
category = MaxDB
connection_url = 连接 URL
instance_name = 实例名
driver_class = 驱动程序类
user_id = 用户 ID
password = 密码

profile.maxdb.title = MaxDB 配置文件
jdbc.connection.name = MaxDB JDBC 连接工厂

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
