pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = ベンダ
version = バージョン 

driver = MaxDB JDBC ドライバ
category = MaxDB
connection_url = 接続 URL
instance_name = インスタンス名
driver_class = ドライバクラス
user_id = ユーザ ID
password = パスワード

profile.maxdb.title = MaxDB のプロファイル
jdbc.connection.name = MaxDB JDBC ファクトリ

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
