pluginName=Eclipse Data Tools Platform MaxDB Enablement Plug-in
providerName=Eclipse Data Tools Platform

vendor = Anbieter
version = Version 

driver = MaxDB JDBC-Treiber
category = MaxDB
connection_url = Verbindungs-URL
instance_name = Instanzname
driver_class = Treiberklasse
user_id = Benutzer-ID
password = Kennwort

profile.maxdb.title = MaxDB-Profil
jdbc.connection.name = MaxDB JDBC-Factory

MaxDBName=MaxDB

7_6_category_name = 7.6
7_7_category_name = 7.7
            
