## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =Hilfe zum &Inhalt@Strg+Leerzeichen
ContentAssistProposal.tooltip     =Hilfe zum Inhalt
ContentAssistProposal.image       =
ContentAssistProposal.description =Hilfe zum Inhalt

ContentAssistTip.label       =Tipp zum Inhalt@Strg+Umschalt+Leerzeichen
ContentAssistTip.tooltip     =Tipp zum Inhalt
ContentAssistTip.image       =
ContentAssistTip.description =Tipp zum Inhalt

ContentFormat.label       =SQL f&ormatieren@Strg+Umschalt+F
ContentFormat.tooltip     =SQL formatieren
ContentFormat.image       =
ContentFormat.description =SQL-Quelle formatieren

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =Mit Daten&bank verbinden
SQLEditor.connectAction.tooltip     =Datenbankverbindung auswählen oder erstellen
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =Datenbankverbindung für diesen Editor auswählen oder erstellen

SQLEditor.disconnectAction.label       =Vo&n Datenbank trennen
SQLEditor.disconnectAction.tooltip     =Editor von der Datenbank trennen
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =Editor von der verbundenen Datenbank trennen

SQLEditor.runAction.label       =S&QL ausführen
SQLEditor.runAction.tooltip     =SQL-Anweisungen ausführen
SQLEditor.runAction.image       =
SQLEditor.runAction.description =Die SQL-Anweisungen in dem Editor der verbundenen Datenbank ausführen

SQLEditor.setStatementTerminatorAction.label       =Anweisungsab&bruchzeichen festlegen
SQLEditor.setStatementTerminatorAction.tooltip     =Anweisungsabbruchzeichen festlegen
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =Zeichenfolge festlegen, anhand derer der Editor SQL-Anweisungen voneinander trennt

SQLEditor.action.toggle.commect.label=Kommentar ein/aus
SQLEditor.action.toggle.commect.tooltip=Kommentare für die ausgewählten Zeilen ein/aus
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=Kommentare für die ausgewählten Zeilen ein/aus

AddTemplateAction.label=Als &Vorlage speichern...
AddTemplateAction.tooltip=Ausgewählten Text als Vorlage speichern...
AddTemplateAction.image=
AddTemplateAction.description=Ausgewählten Text als Vorlage speichern...

Editor.ContextPreferencesAction.label=Voreinstellungen...
Editor.ContextPreferencesAction.description=Voreinstellungen anzeigen
Editor.ContextPreferencesAction.tooltip=Voreinstellungen anzeigen
Editor.ContextPreferencesAction.image=
