## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =Ayuda de co&ntenido@Ctrl+ESPACIO
ContentAssistProposal.tooltip     =Ayuda de contenido
ContentAssistProposal.image       =
ContentAssistProposal.description =Ayuda de contenido

ContentAssistTip.label       =Sugerencia de contenido@Ctrl+MAYÚS+ESPACIO
ContentAssistTip.tooltip     =Sugerencia de contenido
ContentAssistTip.image       =
ContentAssistTip.description =Sugerencia de contenido

ContentFormat.label       =F&ormato SQL@Ctrl+MAYÚS+F
ContentFormat.tooltip     =Formato SQL
ContentFormat.image       =
ContentFormat.description =Formato original SQL

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =Conectarse a la &base de datos
SQLEditor.connectAction.tooltip     =Seleccionar o crear una conexión con la base de datos
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =Seleccionar o crear la conexión de la base de datos para este editor

SQLEditor.disconnectAction.label       =Desconectarse de la base de &datos
SQLEditor.disconnectAction.tooltip     =Desconectar el editor de la base de datos
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =Desconectar el editor de la base de datos conectada

SQLEditor.runAction.label       =Ejecutar S&QL
SQLEditor.runAction.tooltip     =Ejecutar las sentencias SQL
SQLEditor.runAction.image       =
SQLEditor.runAction.description =Ejecutar las sentencias SQL en el editor dentro de la base de datos

SQLEditor.setStatementTerminatorAction.label       =Establecer t&erminador de sentencias
SQLEditor.setStatementTerminatorAction.tooltip     =Establecer el terminador de sentencias
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =Establecer el string que debe usar el editor para separar sentencias SQL

SQLEditor.action.toggle.commect.label=A&lternar comentario
SQLEditor.action.toggle.commect.tooltip=Alternar comentarios para las líneas seleccionadas
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=Alternar comentarios para las líneas seleccionadas

AddTemplateAction.label=Grabar como &plantilla...
AddTemplateAction.tooltip=Grabar texto seleccionado como plantilla...
AddTemplateAction.image=
AddTemplateAction.description=Grabar texto seleccionado como plantilla...

Editor.ContextPreferencesAction.label=Preferencias...
Editor.ContextPreferencesAction.description=Mostrar preferencias
Editor.ContextPreferencesAction.tooltip=Mostrar preferencias
Editor.ContextPreferencesAction.image=
