## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =내용 지원(&N)@Ctrl+SPACE
ContentAssistProposal.tooltip     =내용 지원
ContentAssistProposal.image       =
ContentAssistProposal.description =내용 지원

ContentAssistTip.label       =내용 팁@Ctrl+SHIFT+SPACE
ContentAssistTip.tooltip     =내용 팁
ContentAssistTip.image       =
ContentAssistTip.description =내용 팁

ContentFormat.label       =서식 SQL(&O)@Ctrl+SHIFT+F
ContentFormat.tooltip     =서식 SQL
ContentFormat.image       =
ContentFormat.description =서식 SQL 원본

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =데이터베이스에 연결(&B)
SQLEditor.connectAction.tooltip     =데이터베이스 연결 선택 또는 생성
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =이 편집기에 데이터베이스 연결 선택 또는 생성

SQLEditor.disconnectAction.label       =데이터베이스와 연결 해제(&M)
SQLEditor.disconnectAction.tooltip     =데이터베이스와 편집기 연결 해제
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =연결된 데이터베이스와 편집기 연결 해제

SQLEditor.runAction.label       =SQL 실행(&Q)
SQLEditor.runAction.tooltip     =SQL 문 실행
SQLEditor.runAction.image       =
SQLEditor.runAction.description =연결된 데이터베이스 편집기의 SQL 문 실행

SQLEditor.setStatementTerminatorAction.label       =문 종결자 설정(&E)
SQLEditor.setStatementTerminatorAction.tooltip     =문 종결자 설정
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =SQL 문을 구분하는데 편집기를 사용하도록 문자열을 설정하십시오.

SQLEditor.action.toggle.commect.label=설명 전환(&L)
SQLEditor.action.toggle.commect.tooltip=선택한 줄 설명 전환
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=선택한 줄 설명 전환

AddTemplateAction.label=템플릿으로 저장(&T)...
AddTemplateAction.tooltip=선택한 텍스트를 템플릿으로 저장...
AddTemplateAction.image=
AddTemplateAction.description=선택한 텍스트를 템플릿으로 저장...

Editor.ContextPreferencesAction.label=기본 설정...
Editor.ContextPreferencesAction.description=기본 설정 보기
Editor.ContextPreferencesAction.tooltip=기본 설정 보기
Editor.ContextPreferencesAction.image=
