## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =コンテンツのアシスト(&N)@Ctrl+SPACE
ContentAssistProposal.tooltip     =コンテンツのアシスト
ContentAssistProposal.image       =
ContentAssistProposal.description =コンテンツのアシスト

ContentAssistTip.label       =コンテンツのヒント@Ctrl+SHIFT+SPACE
ContentAssistTip.tooltip     =コンテンツのヒント
ContentAssistTip.image       =
ContentAssistTip.description =コンテンツのヒント

ContentFormat.label       =SQL の書式設定(&O)@Ctrl+SHIFT+F
ContentFormat.tooltip     =SQL の書式設定
ContentFormat.image       =
ContentFormat.description =SQL ソースの書式設定

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =データベースに接続(&B)
SQLEditor.connectAction.tooltip     =データベース接続を選択・作成する
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =このエディタのデータベース接続を選択・作成します。

SQLEditor.disconnectAction.label       =データベースから切断(&M)
SQLEditor.disconnectAction.tooltip     =エディタをデータベースから切断する
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =エディタを接続されているデータベースから切断します。

SQLEditor.runAction.label       =SQL の実行(&Q)
SQLEditor.runAction.tooltip     =SQL 文を実行する
SQLEditor.runAction.image       =
SQLEditor.runAction.description =接続されているデータベースに対して、SQL 文をエディタで実行します。

SQLEditor.setStatementTerminatorAction.label       =文の終結子を設定(&E)
SQLEditor.setStatementTerminatorAction.tooltip     =文の終結子を設定する
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =SQL 文を区切るためにエディタで使用する文字列を設定します。

SQLEditor.action.toggle.commect.label=コメントの切り替え(&L)
SQLEditor.action.toggle.commect.tooltip=選択した行のコメントを切り替える
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=選択した行のコメントを切り替えます。

AddTemplateAction.label=テンプレートとして保存(&T)...
AddTemplateAction.tooltip=選択したテキストをテンプレートとして保存する...
AddTemplateAction.image=
AddTemplateAction.description=選択したテキストをテンプレートとして保存する...

Editor.ContextPreferencesAction.label=環境設定...
Editor.ContextPreferencesAction.description=環境設定を表示します。
Editor.ContextPreferencesAction.tooltip=環境設定を表示する
Editor.ContextPreferencesAction.image=
