## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =Co&ntent Assist@Ctrl+SPACE
ContentAssistProposal.tooltip     =Content Assist
ContentAssistProposal.image       =
ContentAssistProposal.description =Content Assist

ContentAssistTip.label       =Content Tip@Ctrl+SHIFT+SPACE
ContentAssistTip.tooltip     =Content Tip
ContentAssistTip.image       =
ContentAssistTip.description =Content Tip

ContentFormat.label       =F&ormater SQL@Ctrl+SHIFT+F
ContentFormat.tooltip     =Formater SQL
ContentFormat.image       =
ContentFormat.description =Formater la source SQL

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =Se connecter à la &base de données
SQLEditor.connectAction.tooltip     =Sélectionner ou créer une connexion à la base de données
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =Sélectionner ou créer la connexion à la base de données pour cet éditeur

SQLEditor.disconnectAction.label       =Se déconnecter &de la base de données
SQLEditor.disconnectAction.tooltip     =Déconnecter l'éditeur de la base de données
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =Déconnecter l'éditeur de la base de données connectée

SQLEditor.runAction.label       =Exécuter S&QL
SQLEditor.runAction.tooltip     =Exécuter les instructions SQL
SQLEditor.runAction.image       =
SQLEditor.runAction.description =Exécuter les instructions SQL dans l'éditeur dans la base de données connectée

SQLEditor.setStatementTerminatorAction.label       =Définir le t&erminateur d'instruction
SQLEditor.setStatementTerminatorAction.tooltip     =Définir le terminateur d'instruction
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =Définir la chaîne que l'éditeur doit utiliser pour séparer les instructions SQL

SQLEditor.action.toggle.commect.label=Bascu&ler un commentaire
SQLEditor.action.toggle.commect.tooltip=Basculer les commentaires des lignes sélectionnées
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=Basculer les commentaires des lignes sélectionnées

AddTemplateAction.label=Enregistrer comme &modèle...
AddTemplateAction.tooltip=Enregistrer le texte sélectionné comme modèle...
AddTemplateAction.image=
AddTemplateAction.description=Enregistrer le texte sélectionné comme modèle...

Editor.ContextPreferencesAction.label=Préférences...
Editor.ContextPreferencesAction.description=Afficher les préférences
Editor.ContextPreferencesAction.tooltip=Afficher les préférences
Editor.ContextPreferencesAction.image=
