## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others.
## All rights reserved. This program and the accompanying materials 
## are made available under the terms of the Eclipse Public License v1.0
## which is available at
## http://www.eclipse.org/legal/epl-v10.html
## 
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

ContentAssistProposal.label       =内容助手@Ctrl+SPACE(&N)
ContentAssistProposal.tooltip     =内容助手
ContentAssistProposal.image       =
ContentAssistProposal.description =内容助手

ContentAssistTip.label       =内容提示@Ctrl+SHIFT+SPACE
ContentAssistTip.tooltip     =内容提示
ContentAssistTip.image       =
ContentAssistTip.description =内容提示

ContentFormat.label       =格式化 SQL@Ctrl+SHIFT+F(&O)
ContentFormat.tooltip     =格式化 SQL
ContentFormat.image       =
ContentFormat.description =格式化 SQL 源代码

## Resources for SQL Editor-specific actions

# Note: the image entry is the relative path from the xxxAction.class file to the yyy.gif file
SQLEditor.connectAction.label       =连接至数据库(&B)
SQLEditor.connectAction.tooltip     =选择或创建数据库连接
SQLEditor.connectAction.image       =
SQLEditor.connectAction.description =对此编辑器选择或创建数据库连接

SQLEditor.disconnectAction.label       =与数据库断开连接(&M)
SQLEditor.disconnectAction.tooltip     =断开编辑器与数据库的连接
SQLEditor.disconnectAction.image       =
SQLEditor.disconnectAction.description =断开编辑器与已连接的数据库的连接

SQLEditor.runAction.label       =运行 SQL(&Q)
SQLEditor.runAction.tooltip     =运行 SQL 语句
SQLEditor.runAction.image       =
SQLEditor.runAction.description =在连接的数据库上的编辑器上运行 SQL 语句

SQLEditor.setStatementTerminatorAction.label       =设置语句终止符(&E)
SQLEditor.setStatementTerminatorAction.tooltip     =设置语句终止符
SQLEditor.setStatementTerminatorAction.image       =
SQLEditor.setStatementTerminatorAction.description =设置编辑器在隔开 SQL 语句时应使用的字符串

SQLEditor.action.toggle.commect.label=切换注释(&L)
SQLEditor.action.toggle.commect.tooltip=对所选行切换注释
SQLEditor.action.toggle.commect.image=
SQLEditor.action.toggle.commect.description=对所选行切换注释

AddTemplateAction.label=另存为模板(&T)...
AddTemplateAction.tooltip=将所选文本另存为模板...
AddTemplateAction.image=
AddTemplateAction.description=将所选文本另存为模板...

Editor.ContextPreferencesAction.label=首选项...
Editor.ContextPreferencesAction.description=显示首选项
Editor.ContextPreferencesAction.tooltip=显示首选项
Editor.ContextPreferencesAction.image=
