## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=오류
SQLUpdater_nonportable={0}(으)로 이동할 수 없음:
SQLUpdater_error_location=표지 위치를 가져오지 못했습니다.
SQLUpdater_error_annotation=주석을 업데이트하는 중 오류가 발생했습니다.
SQLUpdater_error_removemarker=표지를 제거하는 중 오류가 발생했습니다.
SQLUpdate_dialog_title=정보
SQLUpdate_dialog_message=내용에 {0}개 이상의 줄이 포함되어 있습니다. 구문 유효성 검사를 사용하지 않겠습니까?
SQLUpdate_dialog_toggle=선택 저장(&R)
SQLErrorHover_makeStickyHint=초점을 맞추려면 {0}을(를) 누르십시오.

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = 문 종결자 설정
#SQLEditor_setStatementTerminatorDialog_prompt = 문 종결자:

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=위치 {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = 연결 없음
SQLEditor_file_deleted_or_not_accessible=원본 파일 "{0}"이 삭제되었거나 액세스할 수 없습니다.
#SQLEditor_connection_errorDialog_title   = 연결 예외
#SQLeditor_connection_errorDialog_message = 연결에 실패했습니다. 다음 오류가 보고되었습니다:\n"{0}"

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=선택 항목 없음
#SQLEditor_error_save_message=저장을 완료할 수 없습니다._ {0}
#SQLEditor_error_save_title=다른 이름으로 저장 중 문제 발생__.
#SQLEditor_warning_save_delete=원본 파일 ''{0}''이(가) 삭제되었습니다.

plugin_internal_error=SQL 편집기 플러그인 내부 오류

#AbstractSQLHover_makeStickyHint=초점을 맞추려면 {0}를 누르십시오.

SQLEditorConnectionInfo_decode_error={0}에서 SQL 편집기 연결 정보를 디코드하지 못했습니다.

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} 실패
#EditorManager_saveChangesQuestion = ''{0}''이(가) 수정되었습니다._ 변경 내용을 저장하여 강조 표시된 구문을 업데이트하시겠습니까?

Save = 저장

SQLEditor_error_while_trying_to_install_sql_updater=SQL 업데이트 장치를 설치하는 중 오류가 발생했습니다.

SQLEditorStorage_default_name=스크랩북

SQLEditor_status_profile=현재 프로필: {0}, 
SQLEditor_status_database=데이터베이스: {0},
SQLEditor_problem_save_as=다른 이름으로 저장 중 문제 발생...
SQLEditor_could_not_save_as=저장을 완료할 수 없습니다. {0}
SQLEditor_status_dbType=데이터베이스 형식: {0},
SQLEditor_save_message="저장"은 저장된 프로시저를 데이터베이스로 배포합니다.
SQLEditor_status_profile_connected=연결됨
SQLEditor_status_profile_notconnected=연결 안 됨
