## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=Fehler
SQLUpdater_nonportable=Nicht portierbar auf {0}:
SQLUpdater_error_location=Markierungsposition wurde nicht gefunden.
SQLUpdater_error_annotation=Fehler beim Aktualisieren der Anmerkungen
SQLUpdater_error_removemarker=Fehler beim Entfernen von Markierungen
SQLUpdate_dialog_title=Informationen
SQLUpdate_dialog_message=Inhalt enthält mehr als {0} Zeilen. Möchten Sie die Syntaxvalidierung deaktivieren?
SQLUpdate_dialog_toggle=&Antwort merken
SQLErrorHover_makeStickyHint=Für Fokus {0} drücken.

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = Anweisungsabbruchzeichen festlegen
#SQLEditor_setStatementTerminatorDialog_prompt = Anweisungsabbruchzeichen:

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=Position {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = Keine Verbindung
SQLEditor_file_deleted_or_not_accessible=Die Originaldatei "{0}" wurde gelöscht oder ist nicht abrufbar.
#SQLEditor_connection_errorDialog_title   = Verbindungsausnahme
#SQLeditor_connection_errorDialog_message = Die Verbindung ist fehlgeschlagen. Der folgende Fehler wurde gemeldet:\n"{0}"

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=leere Auswahl
#SQLEditor_error_save_message=Speichervorgang konnte nicht abgeschlossen werden_ {0}
#SQLEditor_error_save_title=Probleme beim Speichern-unter-Vorgang__.
#SQLEditor_warning_save_delete=Die Originaldatei ''{0}'' wurde gelöscht.

plugin_internal_error=Interner Fehler im Plug-In für SQL-Editor

#AbstractSQLHover_makeStickyHint=Für Fokus {0} drücken.

SQLEditorConnectionInfo_decode_error=SQLEditorConnectionInfo konnte nicht von {0} decodiert werden

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} fehlgeschlagen
#EditorManager_saveChangesQuestion = ''{0}'' wurde bearbeitet_ Änderungen speichern, um die Kennzeichnung der Syntax zu aktualisieren?

Save = Speichern

SQLEditor_error_while_trying_to_install_sql_updater=Fehler beim Versuch, die SQL-Aktualisierungsanwendung zu installieren

SQLEditorStorage_default_name=Scrapbook

SQLEditor_status_profile=Aktuelles Profil: {0}, 
SQLEditor_status_database=Datenbank: {0},
SQLEditor_problem_save_as=Probleme beim Speichern-unter-Vorgang...
SQLEditor_could_not_save_as=Speichervorgang konnte nicht abgeschlossen werden. {0}
SQLEditor_status_dbType=Datenbanktyp: {0},
SQLEditor_save_message=Mit "Speichern" wird die gespeicherte Prozedur auf der Datenbank bereitgestellt.
SQLEditor_status_profile_connected=verbunden
SQLEditor_status_profile_notconnected=nicht verbunden
