## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=Error
SQLUpdater_nonportable=No portátil a {0}:
SQLUpdater_error_location=Error al obtener ubicación del marcador
SQLUpdater_error_annotation=Se ha producido un error al actualizar anotaciones
SQLUpdater_error_removemarker=Se ha producido un error al eliminar los marcadores
SQLUpdate_dialog_title=Información
SQLUpdate_dialog_message=El contenido incluye más de {0} líneas. ¿Desea desactivar la validación de sintaxis?
SQLUpdate_dialog_toggle=&Recordar mi decisión
SQLErrorHover_makeStickyHint=Pulse {0} para enfoque.

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = Establecer terminador de sentencias
#SQLEditor_setStatementTerminatorDialog_prompt = Terminador de sentencias:

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=posición {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = Sin conexión
SQLEditor_file_deleted_or_not_accessible=El archivo original "{0}" se ha eliminado o no es accesible.
#SQLEditor_connection_errorDialog_title   = Excepción de conexión
#SQLeditor_connection_errorDialog_message = Se ha producido un error en la conexión. Se ha detectado el error siguiente:\n"{0}"

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=selección vacía
#SQLEditor_error_save_message=No se ha podido guardar_ {0}
#SQLEditor_error_save_title=Problemas al guardar como__.
#SQLEditor_warning_save_delete=Se ha eliminado el archivo original ''{0}''.

plugin_internal_error=Error interno del complemento SQL Editor

#AbstractSQLHover_makeStickyHint=Pulse {0} para enfoque.

SQLEditorConnectionInfo_decode_error=Error al descodificar SQLEditorConnectionInfo desde {0}

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} Error
#EditorManager_saveChangesQuestion = ''{0}'' ha sido modificado_ ¿Guardar cambios para actualizar el resaltado de sintaxis?

Save = Guardar

SQLEditor_error_while_trying_to_install_sql_updater=Se ha producido un error al intentar instalar el actualizador de SQL

SQLEditorStorage_default_name=Álbum

SQLEditor_status_profile=Perfil actual: {0}, 
SQLEditor_status_database=Base de datos: {0},
SQLEditor_problem_save_as=Problemas al guardar como...
SQLEditor_could_not_save_as=No se ha podido guardar. {0}
SQLEditor_status_dbType=Tipo de base de datos: {0},
SQLEditor_save_message="Guardar" implementará el procedimiento almacenado en la base de datos
SQLEditor_status_profile_connected=conectado
SQLEditor_status_profile_notconnected=no conectado
