## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=エラー
SQLUpdater_nonportable={0} との汎用性がありません :
SQLUpdater_error_location=マーカ位置の取得エラー
SQLUpdater_error_annotation=注釈の更新中にエラーが発生しました。
SQLUpdater_error_removemarker=マーカの削除中にエラーが発生しました。
SQLUpdate_dialog_title=情報
SQLUpdate_dialog_message=コンテンツが {0} 行を超えています。構文の検証を無効にしますか ?
SQLUpdate_dialog_toggle=次回から同じ設定を使う(&R)
SQLErrorHover_makeStickyHint=強調表示するには、{0} を押してください。

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = 文の終端子の設定
#SQLEditor_setStatementTerminatorDialog_prompt = 文の終端子 :

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=位置 {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = 接続がありません。
SQLEditor_file_deleted_or_not_accessible=元のファイル "{0}" が削除されているか、アクセスできません。
#SQLEditor_connection_errorDialog_title   = 接続の例外
#SQLeditor_connection_errorDialog_message = 次の接続エラーが発生しました :\n"{0}"

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=何も選択されていません
#SQLEditor_error_save_message=完了できません : {0}
#SQLEditor_error_save_title=名前を付けて保存中にエラーが発生しました。
#SQLEditor_warning_save_delete=元のファイル ''{0}'' は削除されています。

plugin_internal_error=SQL Editor Plugin の内部エラー

#AbstractSQLHover_makeStickyHint=強調表示するには、{0} を押してください。

SQLEditorConnectionInfo_decode_error=SQLEditorConnectionInfo を {0} からデコードできません。

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} エラー
#EditorManager_saveChangesQuestion = ''{0}'' が変更されています。変更内容を保存して、強調表示している構文を更新しますか ?

Save = 保存

SQLEditor_error_while_trying_to_install_sql_updater=SQL アップデータのインストール中にエラーが発生しました。

SQLEditorStorage_default_name=スクラップブック

SQLEditor_status_profile=現在のプロファイル : {0}、 
SQLEditor_status_database=データベース : {0}、
SQLEditor_problem_save_as=名前を付けて保存中にエラーが発生しました...
SQLEditor_could_not_save_as=保存できません : {0}
SQLEditor_status_dbType=データベースの型 : {0}、
SQLEditor_save_message=保存すると、ストアドプロシージャがデータベースに配布されます。
SQLEditor_status_profile_connected=接続済み
SQLEditor_status_profile_notconnected=未接続
