## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=错误
SQLUpdater_nonportable=无法移植至 {0}:
SQLUpdater_error_location=未能获取标记位置
SQLUpdater_error_annotation=更新注释时发生了错误。
SQLUpdater_error_removemarker=删除标记时发生了错误。
SQLUpdate_dialog_title=信息
SQLUpdate_dialog_message=内容包含的行数超过 {0}。要禁用语法验证吗?
SQLUpdate_dialog_toggle=记住我的决定(&R)
SQLErrorHover_makeStickyHint=按 {0} 获取焦点。

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = 设置语句终止符
#SQLEditor_setStatementTerminatorDialog_prompt = 语句终止符:

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=位置 {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = 无连接
SQLEditor_file_deleted_or_not_accessible=原始文件“{0}”已被删除或不可访问。
#SQLEditor_connection_errorDialog_title   = 连接异常
#SQLeditor_connection_errorDialog_message = 连接未打开。报告了以下错误:\n“{0}”

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=空选择
#SQLEditor_error_save_message=无法完成保存操作。{0}
#SQLEditor_error_save_title=执行“另存为...”操作期间发生问题。
#SQLEditor_warning_save_delete=已删除原始文件“{0}”。

plugin_internal_error=SQL 编辑器插件内部错误

#AbstractSQLHover_makeStickyHint=按 {0} 获取焦点。

SQLEditorConnectionInfo_decode_error=未能解码来自 {0} 的 SQLEditorConnectionInfo

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} 失败
#EditorManager_saveChangesQuestion = “{0}”已修改。保存更改以更新语法突出显示吗?

Save = 保存

SQLEditor_error_while_trying_to_install_sql_updater=尝试安装 SQL 更新程序时发生了错误。

SQLEditorStorage_default_name=剪贴簿

SQLEditor_status_profile=当前配置文件: {0}, 
SQLEditor_status_database=数据库: {0},
SQLEditor_problem_save_as=执行“另存为...”操作期间发生问题。
SQLEditor_could_not_save_as=无法完成保存操作。{0}
SQLEditor_status_dbType=数据库类型: {0},
SQLEditor_save_message=“保存”会将存储过程部署至数据库
SQLEditor_status_profile_connected=已连接
SQLEditor_status_profile_notconnected=未连接
