## *******************************************************************************
## Copyright (c) 2000, 2005 IBM Corporation and others_
## All rights reserved_ This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1_0
## which is available at
## http://www_eclipse_org/legal/epl-v10_html
##
## Contributors:
##     IBM Corporation - initial API and implementation
## *******************************************************************************/

## Resources for the standard editor actions

common_error=Erreur
SQLUpdater_nonportable=Non portable vers {0} :
SQLUpdater_error_location=Impossible d'obtenir l'emplacement du repère
SQLUpdater_error_annotation=Une erreur s'est produite lors de la mise à jour d'annotations
SQLUpdater_error_removemarker=Une erreur s'est produite lors de la suppression de repères
SQLUpdate_dialog_title=Informations
SQLUpdate_dialog_message=Le contenu compte plus de {0} lignes. Voulez-vous désactiver la validation de syntaxe ?
SQLUpdate_dialog_toggle=Mémo&riser ma décision.
SQLErrorHover_makeStickyHint=Appuyer sur {0} pour effectuer un zoom.

## Resources for the Set Statement Terminator dialog and composite panel

#SQLEditor_setStatementTerminatorDialog_title  = Définir le terminateur d'instruction
#SQLEditor_setStatementTerminatorDialog_prompt = Terminateur d'instruction :

## Resources for the Outline view

SQLEditor_outlinePage_sqlSegment_titlePattern=position {0}

## Resources for the database connection management

SQLEditor_connection_status_noConnection = Pas de connexion
SQLEditor_file_deleted_or_not_accessible=Le fichier original "{0}" a été supprimé ou n'est pas accessible.
#SQLEditor_connection_errorDialog_title   = Exception de connexion
#SQLeditor_connection_errorDialog_message = La connexion a échoué. L'erreur suivante a été détectée :\n"{0}"

## Miscellaneous resources

#SQLEditor_textHover_emptySelection=selection vide
#SQLEditor_error_save_message=La sauvegarde a échoué_ {0}
#SQLEditor_error_save_title=Problèmes lors de l'enregistrement sous__.
#SQLEditor_warning_save_delete=Le fichier original ''{0}'' a été supprimé.

plugin_internal_error=Erreur interne du plug-in de l'éditeur SQL

#AbstractSQLHover_makeStickyHint=Appuyer sur {0} pour effectuer un zoom.

SQLEditorConnectionInfo_decode_error=Impossible de décoder SQLEditorConnectionInfo à partir de {0}

# ============================================================================
# Editor Framework
# ============================================================================
EditorManager_operationFailed = {0} Echec
#EditorManager_saveChangesQuestion = ''{0}'' a été modifié_ Enregistrer les modifications pour mettre à jour le repérage de la syntaxe ?

Save = Enregistrer

SQLEditor_error_while_trying_to_install_sql_updater=Une erreur s'est produite lors de l'installation de l'actualisateur SQL

SQLEditorStorage_default_name=Album

SQLEditor_status_profile=Profil actuel : {0}, 
SQLEditor_status_database=Base de données : {0},
SQLEditor_problem_save_as=Problèmes lors de l'enregistrement sous...
SQLEditor_could_not_save_as=La sauvegarde a échoué. {0}
SQLEditor_status_dbType=Type de base de données : {0},
SQLEditor_save_message="Enregistrer" déploiera la procédure stockée vers la base de données
SQLEditor_status_profile_connected=connecté
SQLEditor_status_profile_notconnected=non connecté
