# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly

###############################################################################
# Copyright (c) 2005 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################


! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse Data Tools Platform
_UI_PLUGIN_NAME                = Compilador de SQL
_NL1_PLUGIN_NAME 			   = Fragmento Nl1 del compilador de SQL
_UI_BUILDER_NAME               = Compilador de consultas SQL

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Nuevo...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Nueva sentencia SQL...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Crear una nueva sentencia de consulta
datatools_sqlbuilder_sqlstatement_actions_openwith = Abrir con
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = Compilador de consultas SQL
datatools_sqlbuilder_sqlstatement_actions_sqleditor = Editor SQL

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = Abrir Editor SQL
datatools_sqlbuilder_sqleditor_title = Editor &SQL

## Resources for the standard editor actions

ContentAssistProposal_label       =Ayuda de co&ntenido@Ctrl+ESPACIO
ContentAssistProposal_tooltip     =Ayuda de contenido
ContentAssistProposal_image       =
ContentAssistProposal_description =Ayuda de contenido

ContentTip_label       =Sugerencia de contenido@Ctrl+MAYÚS+ESPACIO
ContentTip_tooltip     =Sugerencia de contenido
ContentTip_image       =
ContentTip_description =Sugerencia de contenido

# Preference page name
SQLBuilder.PreferencePageName = Compilador de consultas SQL

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = Compilador de consultas SQL
