# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Licensed Materials - Property of IBM
# org.eclipse.datatools.sqltools.sqlbuilder
# (C) Copyright IBM Corporation 2005. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
#   Use, duplication or disclosure restricted
#   by GSA ADP Schedule Contract with IBM Corp.
#
# Properties file for component:  SQLQ - SQL builder 

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse.org
_UI_PLUGIN_NAME                = Compilador de SQL
_NL1_PLUGIN_NAME 			   = Fragmento Nl1 del compilador de SQL
_UI_BUILDER_NAME               = Compilador de consultas SQL

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Nuevo...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Nueva sentencia SQL...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Crear una nueva sentencia de consulta
datatools_sqlbuilder_sqlstatement_actions_openwith = Abrir con
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = Compilador de consultas SQL
datatools_sqlbuilder_sqlstatement_actions_sqleditor = Editor SQL

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = Abrir Editor SQL
datatools_sqlbuilder_sqleditor_title = Editor &SQL

## Resources for the standard editor actions

ContentAssistProposal_label       =Ayuda de co&ntenido@Ctrl+ESPACIO
ContentAssistProposal_tooltip     =Ayuda de contenido
ContentAssistProposal_image       =
ContentAssistProposal_description =Ayuda de contenido

ContentTip_label       =Sugerencia de contenido@Ctrl+MAYÚS+ESPACIO
ContentTip_tooltip     =Sugerencia de contenido
ContentTip_image       =
ContentTip_description =Sugerencia de contenido

# Preference page name
SQLBuilder.PreferencePageName = Compilador de consultas SQL

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = Compilador de consultas SQL
