# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Licensed Materials - Property of IBM
# org.eclipse.datatools.sqltools.sqlbuilder
# (C) Copyright IBM Corporation 2005. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
#   Use, duplication or disclosure restricted
#   by GSA ADP Schedule Contract with IBM Corp.
#
# Properties file for component:  SQLQ - SQL builder 

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse.org
_UI_PLUGIN_NAME                = SQL Builder
_NL1_PLUGIN_NAME 			   = SQL Builder Nl1-Fragment
_UI_BUILDER_NAME               = SQL-Abfrageerstellung

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Neu....
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Neue SQL-Anweisung...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Neue Abfrageanweisung erstellen
datatools_sqlbuilder_sqlstatement_actions_openwith = Öffnen mit
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL-Abfrageerstellung
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL-Editor

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = SQL-Editor öffnen
datatools_sqlbuilder_sqleditor_title = &SQL-Editor

## Resources for the standard editor actions

ContentAssistProposal_label       =Hilfe zum &Inhalt@Strg+Leerzeichen
ContentAssistProposal_tooltip     =Hilfe zum Inhalt
ContentAssistProposal_image       =
ContentAssistProposal_description =Hilfe zum Inhalt

ContentTip_label       =Tipp zum Inhalt@Strg+Umschalt+Leerzeichen
ContentTip_tooltip     =Tipp zum Inhalt
ContentTip_image       =
ContentTip_description =Tipp zum Inhalt

# Preference page name
SQLBuilder.PreferencePageName = SQL-Abfrageerstellung

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = SQL-Abfrageerstellung
