# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly

###############################################################################
# Copyright (c) 2005 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################


! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse Data Tools Platform
_UI_PLUGIN_NAME                = Générateur SQL
_NL1_PLUGIN_NAME 			   = Fragment NI1 du générateur SQL
_UI_BUILDER_NAME               = Générateur de requête SQL

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Nouveau...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Nouvelle instruction SQL...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Créer une nouvelle instruction de requête
datatools_sqlbuilder_sqlstatement_actions_openwith = Ouvrir avec
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = Générateur de requête SQL
datatools_sqlbuilder_sqlstatement_actions_sqleditor = Editeur SQL

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = Ouvrir l'éditeur SQL
datatools_sqlbuilder_sqleditor_title = Editeur &SQL

## Resources for the standard editor actions

ContentAssistProposal_label       =Co&ntent Assist@Ctrl+SPACE
ContentAssistProposal_tooltip     =Content Assist
ContentAssistProposal_image       =
ContentAssistProposal_description =Content Assist

ContentTip_label       =Content Tip@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =Content Tip
ContentTip_image       =
ContentTip_description =Content Tip

# Preference page name
SQLBuilder.PreferencePageName = Générateur de requête SQL

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = Générateur de requête SQL
