# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly

###############################################################################
# Copyright (c) 2005 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################


! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse Data Tools Platform
_UI_PLUGIN_NAME                = SQL ビルダ
_NL1_PLUGIN_NAME 			   = SQL Builder Nl1 Fragment
_UI_BUILDER_NAME               = SQL クエリビルダ

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = 新規作成...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = SQL 文の新規作成...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = クエリ文の新規作成
datatools_sqlbuilder_sqlstatement_actions_openwith = プログラムから開く
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL クエリビルダ
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL エディタ

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = SQL エディタを開く
datatools_sqlbuilder_sqleditor_title = SQL エディタ(&S)

## Resources for the standard editor actions

ContentAssistProposal_label       =コンテンツのアシスト(&N)@Ctrl+SPACE
ContentAssistProposal_tooltip     =コンテンツのアシスト
ContentAssistProposal_image       =
ContentAssistProposal_description =コンテンツのアシスト

ContentTip_label       =コンテンツのヒント@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =コンテンツのヒント
ContentTip_image       =
ContentTip_description =コンテンツのヒント

# Preference page name
SQLBuilder.PreferencePageName = SQL クエリビルダ

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = SQL クエリビルダ
