# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly

###############################################################################
# Copyright (c) 2005 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################


! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse Data Tools Platform
_UI_PLUGIN_NAME                = SQL 生成器
_NL1_PLUGIN_NAME 			   = SQL 生成器 Nl1 片段
_UI_BUILDER_NAME               = SQL 查询生成器

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = 新建...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = 新建 SQL 语句...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = 创建新查询语句
datatools_sqlbuilder_sqlstatement_actions_openwith = 打开方式
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL 查询生成器
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL 编辑器

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = 打开 SQL 编辑器
datatools_sqlbuilder_sqleditor_title = SQL 编辑器(&S)

## Resources for the standard editor actions

ContentAssistProposal_label       =内容助手@Ctrl+SPACE(&N)
ContentAssistProposal_tooltip     =内容助手
ContentAssistProposal_image       =
ContentAssistProposal_description =内容助手

ContentTip_label       =内容提示@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =内容提示
ContentTip_image       =
ContentTip_description =内容提示

# Preference page name
SQLBuilder.PreferencePageName = SQL 查询生成器

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = SQL 查询生成器
