# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly

###############################################################################
# Copyright (c) 2005 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################


! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse.org
_UI_PLUGIN_NAME                = SQL 빌더
_NL1_PLUGIN_NAME 			   = SQL 빌더 Nl1 조각
_UI_BUILDER_NAME               = SQL 쿼리 빌더

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = 새로 만들기...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = 새 SQL 문...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = 새 Query 문 생성
datatools_sqlbuilder_sqlstatement_actions_openwith = 연결 프로그램
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL 쿼리 빌더
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL 편집기

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = SQL 편집기 열기
datatools_sqlbuilder_sqleditor_title = SQL 편집기(&S)

## Resources for the standard editor actions

ContentAssistProposal_label       =내용 지원(&N)@Ctrl+SPACE
ContentAssistProposal_tooltip     =내용 지원
ContentAssistProposal_image       =
ContentAssistProposal_description =내용 지원

ContentTip_label       =내용 팁@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =내용 팁
ContentTip_image       =
ContentTip_description =내용 팁

# Preference page name
SQLBuilder.PreferencePageName = SQL 쿼리 빌더

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = SQL 쿼리 빌더
