# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Licensed Materials - Property of IBM
# org.eclipse.datatools.sqltools.sqlbuilder
# (C) Copyright IBM Corporation 2005. All Rights Reserved.
#
# Note to U.S. Government Users Restricted Rights:
#   Use, duplication or disclosure restricted
#   by GSA ADP Schedule Contract with IBM Corp.
#
# Properties file for component:  SQLQ - SQL builder 

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

! plugin.xml
!
! Menu action labels
!
_UI_PLUGIN_PROVIDER            = Eclipse.org
_UI_PLUGIN_NAME                = SQL ビルダ
_NL1_PLUGIN_NAME 			   = SQL Builder Nl1 Fragment
_UI_BUILDER_NAME               = SQL クエリビルダ

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = 新規作成...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = SQL 文の新規作成...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = クエリ文の新規作成
datatools_sqlbuilder_sqlstatement_actions_openwith = プログラムから開く
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL クエリビルダ
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL エディタ

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = SQL エディタを開く
datatools_sqlbuilder_sqleditor_title = SQL エディタ(&S)

## Resources for the standard editor actions

ContentAssistProposal_label       =コンテンツのアシスト(&N)@Ctrl+SPACE
ContentAssistProposal_tooltip     =コンテンツのアシスト
ContentAssistProposal_image       =
ContentAssistProposal_description =コンテンツのアシスト

ContentTip_label       =コンテンツのヒント@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =コンテンツのヒント
ContentTip_image       =
ContentTip_description =コンテンツのヒント

# Preference page name
SQLBuilder.PreferencePageName = SQL クエリビルダ

# Editor name for the editor which implements sqleditor's SQLBuilder extension point
SQLEditor.SQLBuilderName = SQL クエリビルダ
