wizard.title.selectColumns=Seleccionar columnas
wizard.defaultMessage.selectFolder=Seleccione la carpeta que contiene los archivos planos
wizard.defaultMessage.selectFile=Seleccione el archivo y las columnas para el conjunto de datos
label.selectFolder=&Seleccionar carpeta: 
label.selectFile=Seleccionar &archivo:
label.fileFilter=&Filtro de archivo:
label.includeTypeLine=Utilizar la segunda línea como indicador de tipo de &datos
label.includeColumnNameLine = Utilizar la primera línea como indicador de &nombre de columna
label.selectCharset=Seleccionar &conjunto de caracteres:
label.selectFlatfileStyle=Select flatfile &style:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=Name
editor.title.originalName=Original Name
editor.title.type=Type


datatypes.dateTime=Timestamp
datatypes.decimal=Big Decimal
datatypes.float=Double
datatypes.integer=Integer
datatypes.string=String
datatypes.date=Date
datatypes.time=Time

tooltip.flatfilestyle=Move the mouse to each flat file style for more infomation
tooltip.csv=Comma-{ , } Seperated Values
tooltip.ssv=Semicolon-{ ; } Seperated Values
tooltip.psv=Pipe-{ | } Seperated Values
tooltip.tsv=Tab-{ Tab } Seperated Values
tooltip.columnnameline=Please make sure the existence of column names\n in the first row of the selected file
tooltip.typeline=Please make sure the existence of data type line\n in the second row of the selected file
error.selectFolder=Seleccione una carpeta válida.
error.selectColumns=Seleccione una columna como mínimo para este conjunto de datos.
error.emptyPath=Especifique una vía de acceso.
error.errorExist=Hay un error en la página actual.  ¿Desea guardarla igualmente?
error.noCSVFiles=La carpeta "{0}" no tiene archivos especificados en ella.
error.invalidFilePath=La vía de acceso del archivo no es válida.  ¿Desea continuar?
error.emptyFilePath=La vía de acceso del archivo está vacía.  ¿Desea continuar?
error.duplicatedNameValueOrEmpty=Valor de nombre duplicado o vacío
error.invalidSavedColumnsInfo = Información de columnas guardada no válida
error.invalidColumnName=Nombre de columna no válido
error.invalidQureyText=Texto de consulta no válido

title.warning=Aviso
warning.columnExtensionInvalid=El archivo seleccionado puede no ser un archivo plano válido.  ¿Desea continuar igualmente?
confirm.reselectFileFilterTitle=Confirme para seleccionar un filtro de archivo distinto.
confirm.reselectFileFilterMessage=Al seleccionar un filtro de archivo distinto, las operaciones anteriores no se guardarán.\n\n¿Está seguro?
