wizard.title.selectColumns=Sélection des colonnes
wizard.defaultMessage.selectFolder=Sélectionnez le dossier qui contient les fichiers plats.
wizard.defaultMessage.selectFile=Sélectionnez le fichier et les colonnes pour le jeu de données.

label.selectFolder=Sél&ectionner un dossier : 
label.selectFile=Sélectionnez un f&ichier :
label.fileFilter=Filt&re de fichier :
label.includeTypeLine=Utilisez la deuxième ligne comme indicateur du type de &données.
label.includeColumnNameLine = Utilisez la première ligne en t&ant qu'indicateur de nom de colonne.
label.selectCharset=Sélectionnez un &jeu de caractères :
label.selectFlatfileStyle=Sélectionnez un &style de fichier plat :
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV
label.trailNull=Utilisez les colonnes &nulles de fin.

button.selectFolder.browse=Pa&rcourir...
button.moveUp=Vers le ha&ut
button.moveDown=&Vers le bas
button.delete=&Supprimer

editor.title.name=Nom
editor.title.originalName=Nom d'origine
editor.title.type=Type


datatypes.dateTime=Date Heure
datatypes.decimal=Décimales
datatypes.float=Flottant
datatypes.integer=Entier
datatypes.string=Chaîne
datatypes.date=Date
datatypes.time=Heure
datatypes.boolean=Booléen

tooltip.flatfilestyle=Déplacez la souris sur chaque style de fichier plat pour en savoir plus.
tooltip.csv=Valeurs séparées par une virgule-{ , }
tooltip.ssv=Valeurs séparées par un point virgule-{ ; }
tooltip.psv=Valeurs séparées par une barre décimale-{ | }
tooltip.tsv=Valeurs séparées par une tabulation-{ Tabulation }
tooltip.columnnameline=Vérifiez l'existence des noms de colonnes\n dans la première ligne du fichier sélectionné.
tooltip.typeline=Vérifiez l'existence de la ligne de type de données\n dans la deuxième ligne du fichier sélectionné.
tooltip.button.add=Ajouter toutes les colonnes sélectionnées de la table de gauche au jeu de données sous forme de fichier plat.
tooltip.button.up=Déplacer l'élément sélectionné vers le haut.
tooltip.button.down=Déplacer l'élément sélectionné vers le bas.
tooltip.button.delete=Supprimer l'élément sélectionné.
tooltip.trailNull=Colonnes avec valeurs nulles à la fin lors de la lecture des lignes de données. 
error.selectFolder=Sélectionnez un dossier correct.
error.selectColumns=Sélectionnez au moins une colonne pour ce fichier.
error.emptyPath=Entrez un chemin d'accès.
error.unexpectedError=Une erreur inattendue s'est produite.
error.invalidConnectionFilePath=Le chemin d''accès source au profil de connexion spécifié, "{0}", n''existe pas.
error.invalidFlatFilePath=Chemin de la source de données sous forme de fichier plat invalide. Veuillez corriger le profil de connexion.
error.errorExist=Une erreur s'est produite dans la page en cours.  Voulez-vous quand même l'enregistrer ?
error.noCSVFiles=Le dossier "{0}" ne comporte aucun des fichiers spécifiés.
error.invalidFilePath=Le chemin du fichier est incorrect.  Souhaitez-vous poursuivre ?
error.emptyFilePath=Le chemin du fichier est vide.  Souhaitez-vous poursuivre ?
error.duplicatedNameValueOrEmpty=Valeur de nom dupliquée ou vide
error.invalidSavedColumnsInfo = Informations de colonnes enregistrées incorrectes
error.invalidColumnName=Nom de colonne incorrect
error.invalidQureyText=Texte de la requête incorrect

title.warning=Avertissement
warning.fileExtensionInvalid=Le fichier sélectionné n'est peut-être pas un fichier plat correct.
confirm.reselectFileFilterTitle=Confirmez pour sélectionner un autre filtre de fichier.
confirm.reselectFileFilterMessage=La sélection d'un autre filtre de fichier ne permettra pas l'enregistrement des opérations précédentes.\n\nVoulez-vous continuer ?

confirm.reselectFileNameTitle=Confirmez pour sélectionner un autre fichier plat.
confirm.reselectFileNameMessage=Souhaitez-vous conserver la sélection de colonnes telle que définie actuellement ?
warning.columnNotExist=La colonne sélectionnée "{0}" n'existe pas !

