wizard.title.selectColumns=열 선택
wizard.defaultMessage.selectFolder=텍스트 파일을 포함하는 폴더를 선택하십시오.
wizard.defaultMessage.selectFile=데이터 세트에 대한 열 및 파일을 선택하십시오.
label.selectFolder=폴더 선택(&F): 
label.selectFile=파일 선택(&I):
label.fileFilter=파일 필터(&R):
label.includeTypeLine=데이터 형식 표시기로 두 번째 줄 사용(&D)
label.includeColumnNameLine = 열 이름 표시기로 첫 번째 줄 사용(&N)
label.selectCharset=Charset 선택(&C):
label.selectFlatfileStyle=플랫 파일 스타일 선택(&S):
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=이름
editor.title.originalName=원본 이름
editor.title.type=형식


datatypes.dateTime=Timestamp
datatypes.decimal=큰 십진수
datatypes.float=이중 실선
datatypes.integer=정수
datatypes.string=문자열
datatypes.date=날짜
datatypes.time=시간
datatypes.boolean=부울

tooltip.flatfilestyle=자세한 내용을 보려면 마우스를 각 플랫 파일 스타일로 이동하십시오.
tooltip.csv=쉼표-{ , }로 구분된 값
tooltip.ssv=세미콜론-{ ; }으로 구분된 값
tooltip.psv=파이프-{ | }로 구분된 값
tooltip.tsv=탭-{ Tab }으로 구분된 값
tooltip.columnnameline=선택된 파일의 첫 번째 행에서 \n열 이름이 있는지 확인하십시오.
tooltip.typeline=선택된 파일의 두 번째 행에서 \n데이터 형식 줄이 있는지 확인하십시오.
error.selectFolder=올바른 폴더를 선택하십시오.
error.selectColumns=이 데이터 세트에 대해 최소 하나의 열을 선택하십시오.
error.emptyPath=경로를 입력하십시오.
error.errorExist=현재 페이지에 오류가 있습니다. 저장하시겠습니까?
error.noCSVFiles="{0}" 폴더에 지정된 파일이 없습니다.
error.invalidFilePath=파일 경로가 올바르지 않습니다. 계속하시겠습니까?
error.emptyFilePath=파일 경로가 비어 있습니다. 계속하시겠습니까?
error.duplicatedNameValueOrEmpty=중복된 이름 값 또는 비어 있음
error.invalidSavedColumnsInfo = 잘못 저장된 열 정보
error.invalidColumnName=잘못된 열 이름
error.invalidQureyText=잘못된 쿼리 텍스트

title.warning=경고
warning.fileExtensionInvalid=선택된 파일은 유효한 플랫 파일이 아닐 수 있습니다.
confirm.reselectFileFilterTitle=다른 파일 필터 선택 확인
confirm.reselectFileFilterMessage=다른 파일 필터를 선택하면 저장되지 않은 이전 작업이 손실됩니다.\n\n계속하시겠습니까?
