wizard.title.selectColumns=列の選択
wizard.defaultMessage.selectFolder=フラットファイルが入っているフォルダを選択してください。
wizard.defaultMessage.selectFile=データセットのファイルと列を選択してください。

label.selectFolder=S&elect folder: 
label.selectFile=ファイルの選択(&I) :
label.fileFilter=ファイルフィルタ(&R) :
label.includeTypeLine=2 行目をデータ型のインジケータとして使用する(&D)
label.includeColumnNameLine = 1 行目を列名のインジケータとして使用する(&N)
label.selectCharset=文字セットの選択(&C) :
label.selectFlatfileStyle=フラットファイルのスタイルの選択(&S) :
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

button.selectFolder.browse=B&rowse...

editor.title.name=名前
editor.title.originalName=元の名前
editor.title.type=型


datatypes.dateTime=日時
datatypes.decimal=10進数値
datatypes.float=浮動小数値
datatypes.integer=整数値
datatypes.string=文字列
datatypes.date=日付
datatypes.time=時間
datatypes.boolean=論理

tooltip.flatfilestyle=フラットファイルの各スタイルにマウスのポインタを置くと詳しい説明が表示されます。
tooltip.csv=値をコンマ { , } で区切る
tooltip.ssv=値をセミコロン { ; } で区切る
tooltip.psv=値をパイプ { | } で区切る
tooltip.tsv=値をタブで区切る
tooltip.columnnameline=選択したファイルの 1 行目が列名であることを\n確認してください。
tooltip.typeline=選択したファイルの 2 行目がデータ型であることを\n確認してください。
error.selectFolder=有効なフォルダーを選択してください。
error.selectColumns=このデータ・セットに対して、1 つ以上の列を選択してください。
error.emptyPath=パスを入力してください。
error.unexpectedError=原因不明のエラーが発生しました。
error.invalidConnectionFilePath=接続プロファイルのソースパスとして "{0}" が指定されましたが、このパスは存在しません。
error.invalidFlatFilePath=フラットファイルのデータソースパスが無効です。接続プロファイルを修正してください。
error.errorExist=現行ページにエラーがあります。  保存しますか?
error.noCSVFiles=フォルダー "{0}" には指定されたファイルがありません。
error.invalidFilePath=ファイル・パスが無効です。  続行しますか?
error.emptyFilePath=ファイル・パスが空です。  続行しますか?
error.duplicatedNameValueOrEmpty=名前の値が重複しているか、空白です。
error.invalidSavedColumnsInfo = 保存された列情報が無効です。
error.invalidColumnName=列名が無効です。
error.invalidQureyText=クエリテキストが無効です。

title.warning=警告
warning.fileExtensionInvalid=選択したファイルは、有効なフラットファイルではない可能性があります。
confirm.reselectFileFilterTitle=異なるファイル・フィルターを選択することを確認してください。
confirm.reselectFileFilterMessage=別のファイルフィルタを選択すると、これまでの作業が保存されずに破棄されます。\n\nこのフィルタを選択しますか ?
