wizard.title.selectColumns=Sélection des colonnes
wizard.defaultMessage.selectFolder=Sélectionnez le dossier contenant les fichiers à plat
wizard.defaultMessage.selectFile=Sélectionnez le fichier et les colonnes du fichier
label.selectFolder=&Sélectionnez un dossier : 
label.selectFile=Sélectionnez un f&ichier :
label.fileFilter=Filt&re de fichier :
label.includeTypeLine=Utilisez la deuxième ligne comme indicateur du type de &données
label.includeColumnNameLine = Utiliser la première ligne en tant qu'indicateur de &nom de colonne
label.selectCharset=Sélectionnez un &jeu de caractères :
label.selectFlatfileStyle=Select flatfile &style:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=Name
editor.title.originalName=Original Name
editor.title.type=Type


datatypes.dateTime=Timestamp
datatypes.decimal=Big Decimal
datatypes.float=Double
datatypes.integer=Integer
datatypes.string=String
datatypes.date=Date
datatypes.time=Time

tooltip.flatfilestyle=Move the mouse to each flat file style for more infomation
tooltip.csv=Comma-{ , } Seperated Values
tooltip.ssv=Semicolon-{ ; } Seperated Values
tooltip.psv=Pipe-{ | } Seperated Values
tooltip.tsv=Tab-{ Tab } Seperated Values
tooltip.columnnameline=Please make sure the existence of column names\n in the first row of the selected file
tooltip.typeline=Please make sure the existence of data type line\n in the second row of the selected file
error.selectFolder=Sélectionnez un dossier correct.
error.selectColumns=Sélectionnez au moins une colonne pour ce fichier.
error.emptyPath=Entrez un chemin d'accès.
error.errorExist=Une erreur s'est produite dans la page en cours.  Voulez-vous quand même l'enregistrer ?
error.noCSVFiles=Le dossier "{0}" ne comporte aucun des fichiers spécifiés.
error.invalidFilePath=Le chemin du fichier est incorrect.  Souhaitez-vous poursuivre ?
error.emptyFilePath=Le chemin du fichier est vide.  Souhaitez-vous poursuivre ?
error.duplicatedNameValueOrEmpty=Valeur de nom dupliquée ou vide
error.invalidSavedColumnsInfo = Informations de colonnes enregistrées incorrectes
error.invalidColumnName=Nom de colonne incorrect
error.invalidQureyText=Texte de la requête incorrect

title.warning=Avertissement
warning.columnExtensionInvalid=Le fichier sélectionné n'est peut-être pas un fichier à plat correct.  Souhaitez-vous poursuivre ?
confirm.reselectFileFilterTitle=Confirmez pour sélectionner un autre filtre de fichier.
confirm.reselectFileFilterMessage=Si vous sélectionnez un autre filtre de fichier, les opérations précédentes ne seront pas enregistrées.\n\nVoulez-vous vraiment effectuer cette opération ?
