wizard.title.selectColumns=Spalten auswählen
wizard.defaultMessage.selectFolder=Wählen Sie den Ordner aus, der die Flachdateien enthält.
wizard.defaultMessage.selectFile=Wählen Sie die Datei und die Spalten für den Datensatz aus.
label.selectFolder=Ordner &auswählen: 
label.selectFile=Date&i auswählen:
label.fileFilter=Dateifilte&r:
label.includeTypeLine=Zweite Zeile als &Datentypindikator verwenden
label.includeColumnNameLine = Erste Zeile als Spalten&namenindikator verwenden
label.selectCharset=Zei&chensatz auswählen:
label.selectFlatfileStyle=Flatfile-&Stil auswählen:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=Name
editor.title.originalName=Originalname
editor.title.type=Typ


datatypes.dateTime=Timestamp
datatypes.decimal=Große Dezimalzahl
datatypes.float=Double
datatypes.integer=Ganzzahl
datatypes.string=Zeichenfolge
datatypes.date=Datum
datatypes.time=Zeit
datatypes.boolean=Boolesch

tooltip.flatfilestyle=Für weitere Informationen bewegen Sie die Maus zu jedem Flatfile-Stil.
tooltip.csv=Durch Komma { , } getrennte Werte
tooltip.ssv=Durch Semikolon { ; } getrennte Werte
tooltip.psv=Durch Pipe { | } getrennte Werte
tooltip.tsv=Durch Tab { Tab } getrennte Werte
tooltip.columnnameline=Vergewissern Sie sich, dass in der ersten Zeile der \nausgewählten Datei Spaltennamen vorhanden sind.
tooltip.typeline=Vergewissern Sie sich, dass in der zweiten Zeile der \nausgewählten Datei Datentypzeilen vorhanden sind.

error.selectFolder=Bitte wählen Sie einen gültigen Ordner.
error.selectColumns=Bitte wählen Sie für diesen Datensatz mindestens eine Spalte aus.
error.emptyPath=Geben Sie einen Pfad ein.
error.unexpectedError=Es ist ein unerwarteter Fehler aufgetreten.
error.invalidConnectionFilePath=Der angegebene Quellpfad "{0}" für das Verbindungsprofil ist nicht vorhanden.
error.invalidFlatFilePath=Ungültiger Pfad für unstrukturierte Datenquelle. Aktualisieren Sie das Verbindungsprofil.
error.errorExist=Die Fehlerktuelle Seite enthält Fehler.  Soll sie trotzdem gespeichert werden?
error.noCSVFiles=Der Ordner "{0}" enthält keine der angegebenen Dateien.
error.invalidFilePath=Der Dateipfad ist ungültig.  Wollen Sie fortfahren?
error.emptyFilePath=Der Dateipfad ist leer.  Wollen Sie fortfahren?
error.duplicatedNameValueOrEmpty=Doppelter Namenswert oder leer
error.invalidSavedColumnsInfo = Ungültige gespeicherte Spalteninformationen
error.invalidColumnName=Ungültiger Spaltenname
error.invalidQureyText=Ungültiger Abfragetext

title.warning=Warnung
warning.fileExtensionInvalid=Bei der ausgewählten Datei handelt es sich möglicherweise nicht um eine gültige Flatfile.
confirm.reselectFileFilterTitle=Auswahl eines anderen Filters bestätigen.
confirm.reselectFileFilterMessage=Bei Auswahl eines anderen Dateifilters werden vorherige Vorgänge nicht gespeichert.\n\nTrotzdem fortfahren?
