wizard.title.selectColumns=列の選択
wizard.defaultMessage.selectFolder=フラット・ファイルを含むフォルダーを選択してください。
wizard.defaultMessage.selectFile=そのデータ・セットのファイルおよび列を選択してください。
label.selectFolder=フォルダの選択(&F) : 
label.selectFile=ファイルの選択(&I) :
label.fileFilter=ファイルフィルタ(&R) :
label.includeTypeLine=2 行目をデータ型のインジケータとして使用する(&D)
label.includeColumnNameLine = 1 行目を列名のインジケータとして使用する(&N)
label.selectCharset=文字セットの選択(&C) :
label.selectFlatfileStyle=フラットファイルのスタイルの選択(&S) :
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=名前
editor.title.originalName=元の名前
editor.title.type=型


datatypes.dateTime=Timestamp
datatypes.decimal=BigDecimal
datatypes.float=Double
datatypes.integer=Integer
datatypes.string=String
datatypes.date=Date
datatypes.time=Time

tooltip.flatfilestyle=フラットファイルの各スタイルにマウスのポインタを置くと詳しい説明が表示されます。
tooltip.csv=値をコンマ { , } で区切る
tooltip.ssv=値をセミコロン { ; } で区切る
tooltip.psv=値をパイプ { | } で区切る
tooltip.tsv=値をタブで区切る
tooltip.columnnameline=選択したファイルの 1 行目が列名であることを\n確認してください。
tooltip.typeline=選択したファイルの 2 行目がデータ型であることを\n確認してください。
error.selectFolder=有効なフォルダーを選択してください。
error.selectColumns=このデータ・セットに対して、1 つ以上の列を選択してください。
error.emptyPath=パスを入力してください。
error.errorExist=現行ページにエラーがあります。  保存しますか?
error.noCSVFiles=フォルダー "{0}" には指定されたファイルがありません。
error.invalidFilePath=ファイル・パスが無効です。  続行しますか?
error.emptyFilePath=ファイル・パスが空です。  続行しますか?
error.duplicatedNameValueOrEmpty=名前の値が重複しているか、空白です。
error.invalidSavedColumnsInfo = 保存された列情報が無効です。
error.invalidColumnName=列名が無効です。
error.invalidQureyText=クエリテキストが無効です。

title.warning=警告
warning.fileExtensionInvalid=選択したファイルは、有効なフラットファイルではない可能性があります。
confirm.reselectFileFilterTitle=異なるファイル・フィルターを選択することを確認してください。
confirm.reselectFileFilterMessage=別のファイルフィルタを選択すると、これまでの作業が保存されずに破棄されます。\n\nこのフィルタを選択しますか ?
