wizard.title.selectColumns=Spalten auswählen
wizard.defaultMessage.selectFolder=Ordner mit den unstrukturierten Dateien auswählen.
wizard.defaultMessage.selectFile=Datei und Spalten für den Datensatz auswählen.

label.selectFolder=S&elect folder: 
label.selectFile=Date&i auswählen:
label.fileFilter=Dateifilte&r:
label.includeTypeLine=Zweite Zeile als &Datentypindikator verwenden.
label.includeColumnNameLine = Erste Zeile als Spalten&namenindikator verwenden.
label.selectCharset=Zei&chensatz auswählen:
label.selectFlatfileStyle=Flatfile-&Stil auswählen:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

button.selectFolder.browse=B&rowse...

editor.title.name=Name
editor.title.originalName=Originalname
editor.title.type=Typ


datatypes.dateTime=Datum/Uhrzeit
datatypes.decimal=Dezimal
datatypes.float=Gleitkomma
datatypes.integer=Ganzzahl
datatypes.string=Zeichenfolge
datatypes.date=Datum
datatypes.time=Zeit
datatypes.boolean=Boolesch

tooltip.flatfilestyle=Bewegen Sie die Maus über den Stil einer unstrukturierten Datei, um weitere Informationen zu erhalten.
tooltip.csv=Durch Komma { , } getrennte Werte
tooltip.ssv=Durch Semikolon { ; } getrennte Werte
tooltip.psv=Durch Pipe { | } getrennte Werte
tooltip.tsv=Durch Tab { Tab } getrennte Werte
tooltip.columnnameline=Stellen Sie sicher, dass die erste Zeile\nder gewählten Datei Spaltennamen enthält.
tooltip.typeline=Stellen Sie sicher, dass die zweite Zeile\nder gewählten Datei Datentypen enthält.
error.selectFolder=Bitte wählen Sie einen gültigen Ordner.
error.selectColumns=Bitte wählen Sie für diesen Datensatz mindestens eine Spalte aus.
error.emptyPath=Geben Sie einen Pfad ein.
error.unexpectedError=Es ist ein unerwarteter Fehler aufgetreten.
error.invalidConnectionFilePath=Der angegebene Quellpfad "{0}" für das Verbindungsprofil ist nicht vorhanden.
error.invalidFlatFilePath=Ungültiger Pfad für unstrukturierte Datenquelle. Aktualisieren Sie das Verbindungsprofil.
error.errorExist=Die Fehlerktuelle Seite enthält Fehler.  Soll sie trotzdem gespeichert werden?
error.noCSVFiles=Der Ordner "{0}" enthält keine der angegebenen Dateien.
error.invalidFilePath=Der Dateipfad ist ungültig.  Wollen Sie fortfahren?
error.emptyFilePath=Der Dateipfad ist leer.  Wollen Sie fortfahren?
error.duplicatedNameValueOrEmpty=Doppelter Namenswert oder leer
error.invalidSavedColumnsInfo = Ungültige gespeicherte Spalteninformationen
error.invalidColumnName=Ungültiger Spaltenname
error.invalidQureyText=Ungültiger Abfragetext

title.warning=Warnung
warning.fileExtensionInvalid=Bei der ausgewählten Datei handelt es sich möglicherweise nicht um eine gültige Flatfile.
confirm.reselectFileFilterTitle=Auswahl eines anderen Filters bestätigen.
confirm.reselectFileFilterMessage=Bei Auswahl eines anderen Dateifilters werden vorherige Vorgänge nicht gespeichert.\n\nTrotzdem fortfahren?
