wizard.title.selectColumns=Spalten auswählen
wizard.defaultMessage.selectFile=Datei und Spalten für den Datensatz auswählen.
wizard.WizardTitle.DEFAULT_MESSAGE=Wählen Sie einen Ordner mit unstrukturierten Dateien aus, oder geben Sie einen URI für die unstrukturierte Datei ein.

FolderSelectionPageHelper.SelectFolderDialog.Title=Ordner mit den unstrukturierten Dateien auswählen.

label.selectFolder=Stammordner auswähl&en 
label.fileURI=Datei-&URI eingeben:
lable.fileURI.tooltip=Geben Sie einen URI für die Datei ein, oder wählen Sie eine lokale Datei aus. 
label.selectFile=Date&i auswählen:
label.fileFilter=Dateifilte&r:
label.includeTypeLine=Zweite Zeile als &Datentypindikator verwenden.
label.includeColumnNameLine = Erste Zeile &als Spaltennamenindikator verwenden.
label.selectCharset=Zei&chensatz auswählen:
label.selectFlatfileStyle=Flatfile-&Stil auswählen:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV
label.trailNull=Spalten mit &Nullen in Endposition verwenden.

button.selectFolder.browse=Du&rchsuchen...
button.selectFileURI.browse=&Durchsuchen...
button.selectFileURI.menuItem.relativePath=Relativer Pfad
button.selectFileURI.menuItem.absolutePath=Absoluter Pfad
button.selectFileURI.browse.tooltips=Wählen Sie den URI einer lokalen Datei aus.
button.moveUp=Nach &oben
button.moveDown=Nach &unten
button.delete=Lösch&en

editor.title.name=Name
editor.title.originalName=Originalname
editor.title.type=Typ


datatypes.dateTime=Datum/Uhrzeit
datatypes.decimal=Dezimal
datatypes.float=Gleitkomma
datatypes.integer=Ganzzahl
datatypes.string=Zeichenfolge
datatypes.date=Datum
datatypes.time=Zeit
datatypes.boolean=Boolesch

tooltip.flatfilestyle=Bewegen Sie die Maus über den Stil einer unstrukturierten Datei, um weitere Informationen zu erhalten.
tooltip.csv=Durch Komma { , } getrennte Werte
tooltip.ssv=Durch Semikolon { ; } getrennte Werte
tooltip.psv=Durch Pipe { | } getrennte Werte
tooltip.tsv=Durch Tab { Tab } getrennte Werte
tooltip.columnnameline=Stellen Sie sicher, dass die erste Zeile\nder gewählten Datei Spaltennamen enthält.
tooltip.typeline=Stellen Sie sicher, dass die zweite Zeile\nder gewählten Datei Datentypen enthält.
tooltip.button.add=Alle ausgewählten Spalten aus der Tabelle links zum Datensatz für unstrukturierte Datei hinzufügen
tooltip.button.up=Ausgewähltes Element nach oben verschieben
tooltip.button.down=Ausgewähltes Element nach unten verschieben
tooltip.button.delete=Ausgewähltes Objekt löschen
tooltip.trailNull=Spalten mit Nullen in Endposition beim Lesen von Datenzeilen. 
error.selectFolder=Bitte wählen Sie einen gültigen Ordner.
error.selectColumns=Bitte wählen Sie für diesen Datensatz mindestens eine Spalte aus.
error.emptyPath=Geben Sie einen Pfad ein.
error.unexpectedError=Es ist ein unerwarteter Fehler aufgetreten.
error.invalidConnectionFilePath=Der angegebene Quellpfad "{0}" für das Verbindungsprofil ist nicht vorhanden.
error.invalidFlatFilePath=Ungültiger Pfad für unstrukturierte Datenquelle. Aktualisieren Sie das Verbindungsprofil.
error.errorExist=Die Fehlerktuelle Seite enthält Fehler.  Soll sie trotzdem gespeichert werden?
error.noCSVFiles=Der Ordner "{0}" enthält keine der angegebenen Dateien.
error.invalidFilePath=Der Dateipfad ist ungültig.  Wollen Sie fortfahren?
error.emptyFilePath=Der Dateipfad ist leer.  Wollen Sie fortfahren?
error.duplicatedNameValueOrEmpty=Doppelter Namenswert oder leer
error.invalidSavedColumnsInfo = Ungültige gespeicherte Spalteninformationen
error.invalidColumnName=Ungültiger Spaltenname
error.invalidQureyText=Ungültiger Abfragetext
error.invalidURIPath=Der eingegebene URI ist ungültig.
error.URIConnectionFailure=Verbindung zur URI-Ressource kann nicht geöffnet werden.

title.warning=Warnung
warning.fileExtensionInvalid=Bei der ausgewählten Datei handelt es sich möglicherweise nicht um eine gültige Flatfile.
confirm.reselectFileFilterTitle=Auswahl eines anderen Filters bestätigen.
confirm.reselectFileFilterMessage=Bei Auswahl eines anderen Dateifilters werden vorherige Vorgänge nicht gespeichert.\n\nTrotzdem fortfahren?

confirm.reselectFileNameTitle=Bestätigen Sie zum Auswählen einer anderen unstrukturierten Datei.
confirm.reselectFileNameMessage=Möchten Sie die Spaltenauswahl entsprechend der aktuellen Definition beibehalten?
warning.columnNotExist=Die ausgewählte Spalte '{0}' ist nicht vorhanden.

fileURIChanged.warning.reselectColumnsTitle=URI der Datei in der Datenquelle wurde verändert.
fileURIChanged.warning.reselectColumnsMessage=URI der Datei in der Datenquelle wurde verändert!\nWählen Sie erneut Spalten aus.
Connection.warning.untested=Verbindung wurde nicht getestet. Führen Sie einen Verbindungstest durch, bevor Sie dieses Datenquellenprofil speichern.
Connection.error.invalidPath=Es wurden keine gültigen Speicherorte für unstrukturierte Dateien gefunden.
Connection.error.invalidHomeFolder=Ungültiger Stammordner <{0}> für unstrukturierte Dateien.
Connection.error.invalidFileURI=Ungültiger URI-Pfad <{0}> für unstrukturierte Dateien.

RelativeFileSelectionDialog.Title.SelectFile=Datei auswählen
