wizard.title.selectColumns=열 선택
wizard.defaultMessage.selectFolder=플랫 파일이 들어 있는 폴더 선택합니다.
wizard.defaultMessage.selectFile=데이터 집합에 대한 파일 및 열 선택을 선택합니다.

label.selectFolder=폴더 선택(&E): 
label.selectFile=파일 선택(&I):
label.fileFilter=파일 필터(&R):
label.includeTypeLine=데이터 형식 표시기로 두 번째 줄을 사용(&D)
label.includeColumnNameLine = 열 이름 표시기로 첫 번째 줄 사용(&A)
label.selectCharset=Charset 선택(&C):
label.selectFlatfileStyle=플랫 파일 스타일 선택(&S):
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV
label.trailNull=후행 널 열 사용(&N)

button.selectFolder.browse=찾아보기(&R)...
button.moveUp=위로(&U)
button.moveDown=아래로(&W)
button.delete=삭제(&E)

editor.title.name=이름
editor.title.originalName=원본 이름
editor.title.type=형식


datatypes.dateTime=날짜 시간
datatypes.decimal=십진수
datatypes.float=실수
datatypes.integer=정수
datatypes.string=문자열
datatypes.date=날짜
datatypes.time=시간
datatypes.boolean=부울

tooltip.flatfilestyle=자세한 정보를 보려면 각 플랫 파일 스타일로 마우스를 이동하십시오.
tooltip.csv=쉼표-{ , }로 구분된 값
tooltip.ssv=세미콜론-{ ; }으로 구분된 값
tooltip.psv=파이프-{ | }로 구분된 값
tooltip.tsv=탭-{ Tab }으로 구분된 값
tooltip.columnnameline=선택된 파일의 첫 번째 행에 열 이름이 있는지\n 확인하십시오.
tooltip.typeline=선택한 파일의 두 번째 행에 데이터 형식 줄이 있는지\n 확인하십시오.
tooltip.button.add=왼쪽 테이블에서 선택한 열을 모두 플랫 파일 데이터 집합에 추가합니다.
tooltip.button.up=선택한 항목 위로 이동합니다.
tooltip.button.down=선택한 항목 아래로 이동합니다.
tooltip.button.delete=선택한 항목을 삭제합니다.
tooltip.trailNull=데이터 선을 읽는 동안 널(null) 열을 추적합니다. 
error.selectFolder=올바른 폴더를 선택하십시오.
error.selectColumns=이 데이터 세트에 대해 최소 하나의 열을 선택하십시오.
error.emptyPath=경로를 입력하십시오.
error.unexpectedError=예기치 않은 오류가 발생했습니다.
error.invalidConnectionFilePath=지정된 연결 프로필 원본 경로 "{0}"이(가) 없습니다.
error.invalidFlatFilePath=잘못된 플랫 파일 데이터 원본 경로입니다. 연결 프로필을 수정하십시오.
error.errorExist=현재 페이지에 오류가 있습니다. 저장하시겠습니까?
error.noCSVFiles="{0}" 폴더에 지정된 파일이 없습니다.
error.invalidFilePath=파일 경로가 올바르지 않습니다. 계속하시겠습니까?
error.emptyFilePath=파일 경로가 비어 있습니다. 계속하시겠습니까?
error.duplicatedNameValueOrEmpty=중복된 이름 값 또는 비어 있음
error.invalidSavedColumnsInfo = 잘못 저장된 열 정보
error.invalidColumnName=잘못된 열 이름
error.invalidQureyText=잘못된 쿼리 텍스트

title.warning=경고
warning.fileExtensionInvalid=선택된 파일은 유효한 플랫 파일이 아닐 수 있습니다.
confirm.reselectFileFilterTitle=다른 파일 필터 선택 확인
confirm.reselectFileFilterMessage=다른 파일 필터를 선택하면 저장되지 않은 이전 작업이 손실됩니다.\n\n계속하시겠습니까?

confirm.reselectFileNameTitle=Confirm to select a different flat file.
confirm.reselectFileNameMessage=Do you want to preserve the columns selection the same as the current definition?
warning.columnNotExist=The selected column "{0}" does not exist!
warning.dummy=Test warining Updated
