wizard.title.selectColumns=选择列
wizard.defaultMessage.selectFolder=选择包含平面文件的文件夹
wizard.defaultMessage.selectFile=选择用于该数据集的文件和列
label.selectFolder=选择文件夹(&F): 
label.selectFile=选择文件(&I):
label.fileFilter=文件筛选(&R):
label.includeTypeLine=将第二行用作数据类型指示器(&D)
label.includeColumnNameLine = 使用第一行作为列名称指示器(&N)
label.selectCharset=选择字符集(&C):
label.selectFlatfileStyle=Select flatfile &style:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=Name
editor.title.originalName=Original Name
editor.title.type=Type

datatypes.dateTime=Timestamp
datatypes.decimal=Big Decimal
datatypes.float=Double
datatypes.integer=Integer
datatypes.string=String
datatypes.date=Date
datatypes.time=Time

tooltip.flatfilestyle=Move the mouse to each flat file style for more infomation
tooltip.csv=Comma-{ , } Seperated Values
tooltip.ssv=Semicolon-{ ; } Seperated Values
tooltip.psv=Pipe-{ | } Seperated Values
tooltip.tsv=Tab-{ Tab } Seperated Values
tooltip.columnnameline=Please make sure the existence of column names\n in the first row of the selected file
tooltip.typeline=Please make sure the existence of data type line\n in the second row of the selected file

error.selectFolder=请选择有效文件夹。
error.selectColumns=请至少为此数据集选择一列。
error.emptyPath=请输入路径。
error.errorExist=当前页面存在错误。一定要保存它吗？
error.noCSVFiles=文件夹“{0}”中没有指定任何文件。
error.invalidFilePath=文件路径无效。要继续吗？
error.emptyFilePath=文件路径是空的。要继续吗？
error.duplicatedNameValueOrEmpty=名称值重复或为空
error.invalidSavedColumnsInfo = 无效的保存列信息
error.invalidColumnName=无效列名称
error.invalidQureyText=无效查询文本

title.warning=警告
warning.columnExtensionInvalid=所选文件可能不是有效的平面文件。一定要继续吗？
confirm.reselectFileFilterTitle=确认选择另一文件过滤器。
confirm.reselectFileFilterMessage=选择另一文件过滤器将不会保存先前的操作。\n\n您确定吗？
