wizard.title.selectColumns=Seleccionar columnas
wizard.defaultMessage.selectFolder=Seleccione la carpeta que contiene los archivos sin formato.
wizard.defaultMessage.selectFile=Seleccione el archivo y las columnas del conjunto de datos.

label.selectFolder=S&eleccionar carpeta: 
label.selectFile=Seleccionar &archivo:
label.fileFilter=&Filtro de archivo:
label.includeTypeLine=Utilice la segunda línea como indicador de tipo de &datos.
label.includeColumnNameLine = Utilizar la &primera línea como indicador del nombre de columna.
label.selectCharset=Seleccionar &conjunto de caracteres:
label.selectFlatfileStyle=Seleccionar e&stilo de archivo sin formato:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

button.selectFolder.browse=&Examinar...

editor.title.name=Nombre
editor.title.originalName=Nombre original
editor.title.type=Tipo


datatypes.dateTime=Fecha Hora
datatypes.decimal=Decimal
datatypes.float=Flotante
datatypes.integer=Entero
datatypes.string=String
datatypes.date=Fecha
datatypes.time=Hora
datatypes.boolean=Booleano

tooltip.flatfilestyle=Mueva el puntero del ratón sobre cada estilo de archivo sin formato para obtener más información.
tooltip.csv=Valores separados por comas {,}
tooltip.ssv=Valores separados por puntos y comas {;}
tooltip.psv=Valores separados por barras {|}
tooltip.tsv=Valores separados por tabulaciones {Tab}
tooltip.columnnameline=Asegúrese de que los nombres de columna aparecen\n en la primera fila del archivo seleccionado.
tooltip.typeline=Asegúrese de que la línea de tipo de datos aparece\n en la segunda fila del archivo seleccionado.
tooltip.button.add=Add all the selected columns from the left table to the flat file data set.
tooltip.button.up=Move up the selected item.
tooltip.button.down=Move down the selected item.
tooltip.button.delete=Delete the selected item.
error.selectFolder=Seleccione una carpeta válida.
error.selectColumns=Seleccione una columna como mínimo para este conjunto de datos.
error.emptyPath=Especifique una vía de acceso.
error.unexpectedError=Se ha producido un error inesperado.
error.invalidConnectionFilePath=No existe la ruta especificada "{0}" para la fuente del perfil de conexión.
error.invalidFlatFilePath=Ruta de fuente de datos de archivo sin formato no válida. Corrija el perfil de conexión.
error.errorExist=Hay un error en la página actual.  ¿Desea guardarla igualmente?
error.noCSVFiles=La carpeta "{0}" no tiene archivos especificados en ella.
error.invalidFilePath=La vía de acceso del archivo no es válida.  ¿Desea continuar?
error.emptyFilePath=La vía de acceso del archivo está vacía.  ¿Desea continuar?
error.duplicatedNameValueOrEmpty=Valor de nombre duplicado o vacío
error.invalidSavedColumnsInfo = Información de columnas guardada no válida
error.invalidColumnName=Nombre de columna no válido
error.invalidQureyText=Texto de consulta no válido

title.warning=Aviso
warning.fileExtensionInvalid=El archivo seleccionado podría ser un archivo sin formato no válido.
confirm.reselectFileFilterTitle=Confirme para seleccionar un filtro de archivo distinto.
confirm.reselectFileFilterMessage=Si selecciona un filtro de archivo diferente no se guardarán las operaciones anteriores.\n\n¿Seguro que desea seleccionar un filtro diferente?
