wizard.title.selectColumns=Seleccionar columnas
wizard.defaultMessage.selectFolder=Seleccione una carpeta que contenga los archivos sin formato o introduzca un URI para el archivo sin formato.
wizard.defaultMessage.selectFile=Seleccione el archivo y las columnas del conjunto de datos.

label.selectFolder=S&eleccionar carpeta inicial: 
label.fileURI=Introducir &URI de archivo:
lable.fileURI.tooltip=Introduzca un URI para el archivo o seleccione un archivo local. 
label.selectFile=Seleccionar &archivo:
label.fileFilter=&Filtro de archivo:
label.includeTypeLine=Utilice la segunda línea como indicador de tipo de &datos.
label.includeColumnNameLine = Utilizar la &primera línea como indicador del nombre de columna.
label.selectCharset=Seleccionar &conjunto de caracteres:
label.selectFlatfileStyle=Seleccionar e&stilo de archivo sin formato:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV
label.trailNull=Use columnas &nulas finales.

button.selectFolder.browse=&Examinar...
button.selectFileURI.browse=&Examinar...
button.selectFileURI.menuItem.relativePath=Ruta relativa
button.selectFileURI.menuItem.absolutePath=Ruta relativa
button.selectFileURI.browse.tooltips=Seleccione un URI de archivo local.
button.moveUp=A&rriba
button.moveDown=A&bajo
button.delete=Elimi&nar

editor.title.name=Nombre
editor.title.originalName=Nombre original
editor.title.type=Tipo


datatypes.dateTime=Fecha Hora
datatypes.decimal=Decimal
datatypes.float=Flotante
datatypes.integer=Entero
datatypes.string=String
datatypes.date=Fecha
datatypes.time=Hora
datatypes.boolean=Booleano

tooltip.flatfilestyle=Mueva el puntero del ratón sobre cada estilo de archivo sin formato para obtener más información.
tooltip.csv=Valores separados por comas {,}
tooltip.ssv=Valores separados por puntos y comas {;}
tooltip.psv=Valores separados por barras {|}
tooltip.tsv=Valores separados por tabulaciones {Tab}
tooltip.columnnameline=Asegúrese de que los nombres de columna aparecen\n en la primera fila del archivo seleccionado.
tooltip.typeline=Asegúrese de que la línea de tipo de datos aparece\n en la segunda fila del archivo seleccionado.
tooltip.button.add=Agregue todas las columnas seleccionadas de la tabla izquierda al conjunto de datos de archivo sin formato.
tooltip.button.up=Mueva hacia arriba el elemento seleccionado.
tooltip.button.down=Mueva hacia abajo el elemento seleccionado.
tooltip.button.delete=Elimine el elemento seleccionado.
tooltip.trailNull=Coloque al final las columnas nulas al leer líneas de datos. 
error.selectFolder=Seleccione una carpeta válida.
error.selectColumns=Seleccione una columna como mínimo para este conjunto de datos.
error.emptyPath=Especifique una vía de acceso.
error.unexpectedError=Se ha producido un error inesperado.
error.invalidConnectionFilePath=No existe la ruta especificada "{0}" para la fuente del perfil de conexión.
error.invalidFlatFilePath=Ruta de fuente de datos de archivo sin formato no válida. Corrija el perfil de conexión.
error.errorExist=Hay un error en la página actual.  ¿Desea guardarla igualmente?
error.noCSVFiles=La carpeta "{0}" no tiene archivos especificados en ella.
error.invalidFilePath=La vía de acceso del archivo no es válida.  ¿Desea continuar?
error.emptyFilePath=La vía de acceso del archivo está vacía.  ¿Desea continuar?
error.duplicatedNameValueOrEmpty=Valor de nombre duplicado o vacío
error.invalidSavedColumnsInfo = Información de columnas guardada no válida
error.invalidColumnName=Nombre de columna no válido
error.invalidQureyText=Texto de consulta no válido
error.invalidURIPath=El URI introducido no es válido.
error.URIConnectionFailure=No se puede abrir la conexión con el recurso de URI.

title.warning=Aviso
warning.fileExtensionInvalid=El archivo seleccionado podría ser un archivo sin formato no válido.
confirm.reselectFileFilterTitle=Confirme para seleccionar un filtro de archivo distinto.
confirm.reselectFileFilterMessage=Si selecciona un filtro de archivo diferente no se guardarán las operaciones anteriores.\n\n¿Seguro que desea seleccionar un filtro diferente?

confirm.reselectFileNameTitle=Confirme para seleccionar un archivo sin formato diferente.
confirm.reselectFileNameMessage=¿Desea mantener la selección de columnas igual que la definición actual?
warning.columnNotExist=La columna seleccionada "{0}" no existe.

fileURIChanged.warning.reselectColumnsTitle=El URI de archivo de la fuente de datos ha cambiado.
fileURIChanged.warning.reselectColumnsMessage=El URI de archivo de la fuente de datos ha cambiado.\nSeleccione las columnas de nuevo.
Connection.warning.untested=No se ha probado la conexión. Pruebe la conexión antes de guardar este perfil de fuente de datos.
Connection.error.invalidPath=No se han encontrado ubicaciones de archivo sin formato válidas.
Connection.error.invalidHomeFolder=Carpeta inicial de archivo sin formato no válida <{0}>.
Connection.error.invalidFileURI=Ruta de URI de archivo sin formato no válida <{0}>.
