wizard.title.selectColumns=열 선택
wizard.defaultMessage.selectFolder=텍스트 파일을 포함하는 폴더를 선택하십시오.
wizard.defaultMessage.selectFile=데이터 세트에 대한 열 및 파일을 선택하십시오.
label.selectFolder=폴더 선택(&F): 
label.selectFile=파일 선택(&I):
label.fileFilter=파일 필터(&R):
label.includeTypeLine=데이터 형식 표시기로 두 번째 줄 사용(&D)
label.includeColumnNameLine = 열 이름 표시기로 첫 번째 줄 사용(&N)
label.selectCharset=Charset 선택(&C):
label.selectFlatfileStyle=Select flatfile &style:
label.flatfileComma=CSV
label.flatfileSemicolon=SSV
label.flatfilePipe=PSV
label.flatfileTab=TSV

editor.title.name=Name
editor.title.originalName=Original Name
editor.title.type=Type


datatypes.dateTime=Timestamp
datatypes.decimal=Big Decimal
datatypes.float=Double
datatypes.integer=Integer
datatypes.string=String
datatypes.date=Date
datatypes.time=Time

tooltip.flatfilestyle=Move the mouse to each flat file style for more infomation
tooltip.csv=Comma-{ , } Seperated Values
tooltip.ssv=Semicolon-{ ; } Seperated Values
tooltip.psv=Pipe-{ | } Seperated Values
tooltip.tsv=Tab-{ Tab } Seperated Values
tooltip.columnnameline=Please make sure the existence of column names\n in the first row of the selected file
tooltip.typeline=Please make sure the existence of data type line\n in the second row of the selected file
error.selectFolder=올바른 폴더를 선택하십시오.
error.selectColumns=이 데이터 세트에 대해 최소 하나의 열을 선택하십시오.
error.emptyPath=경로를 입력하십시오.
error.errorExist=현재 페이지에 오류가 있습니다. 저장하시겠습니까?
error.noCSVFiles="{0}" 폴더에 지정된 파일이 없습니다.
error.invalidFilePath=파일 경로가 올바르지 않습니다. 계속하시겠습니까?
error.emptyFilePath=파일 경로가 비어 있습니다. 계속하시겠습니까?
error.duplicatedNameValueOrEmpty=중복된 이름 값 또는 비어 있음
error.invalidSavedColumnsInfo = 잘못 저장된 열 정보
error.invalidColumnName=잘못된 열 이름
error.invalidQureyText=잘못된 쿼리 텍스트

title.warning=경고
warning.columnExtensionInvalid=선택한 파일이 올바른 텍스트 파일이 아닐 수 있습니다. 계속하시겠습니까?
confirm.reselectFileFilterTitle=다른 파일 필터 선택 확인
confirm.reselectFileFilterMessage=다른 파일 필터를 선택하면 이전 조작이 저장되지 않습니다. \n\n계속하시겠습니까?
