###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB LUW Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Classe de pilote
driverVendor = Vendeur
driverVersion = Version
driverDBName = Nom de la base de données
driverConnectionURL = URL de connexion
driverUID = ID utilisateur
driverPWD = Mot de passe

DB2_UDB_CATEGORY_NAME = DB2 pour Linux, UNIX et Windows

org.eclipse.datatools.enablement.ibm.db2.luw.driverTemplate = Pilote de serveur de données IBM pour JDBC et SQLJ
org.eclipse.datatools.enablement.ibm.db2.luw.other.driverTemplate = Autre pilote

jdbc.connection.name = Connexion JDBC
profile.db2.luw.title = DB2 pour Linux, UNIX et Windows
