###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB LUW Plug-in
providerName=Eclipse Data Tools Platform

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호

DB2_UDB_CATEGORY_NAME = Linux, UNIX 및 Windows용 DB2

org.eclipse.datatools.enablement.ibm.db2.luw.driverTemplate = JDBC 및 SQLJ용 IBM 데이터 서버 드라이버
org.eclipse.datatools.enablement.ibm.db2.luw.other.driverTemplate = 기타 드라이버

jdbc.connection.name = JDBC 연결
profile.db2.luw.title = Linux, UNIX 및 Windows용 DB2
