###############################################################################
# Copyright (c) 2005 Versant Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Versant Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform MySQL Database Definition Plug-in
providerName=Eclipse Data Tools Platform
4.0_ProductString = MySQL
4.0_VersionString = 4.0
4.1_ProductString = MySQL
4.1_VersionString = 4.1
5.0_ProductString = MySQL
5.0_VersionString = 5.0
5.1_ProductString = MySQL
5.1_VersionString = 5.1
