################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
# package: org.eclipse.datatools.connectivity.jdt.internal

DriverClasspathContainerPage.name = MyDriverClassPathPage
DriverClasspathContainerPage.title = 연결 드라이버 정의
DriverClasspathContainerPage.msg = 클래스 경로에 Jar를 추가할 드라이버 정의를 선택하십시오.
DriverClasspathContainerPage.combo.title = 사용 가능한 드라이버 정의:
