################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
# package: org.eclipse.datatools.connectivity.jdt.internal

DriverClasspathContainerPage.name = MyDriverClassPathPage
DriverClasspathContainerPage.title = 接続ドライバの定義
DriverClasspathContainerPage.msg = Jar をクラスパスに追加するドライバの定義を選択してください。
DriverClasspathContainerPage.combo.title = 使用可能なドライバの定義:
