###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB zSeries UI Plug-in
providerName=Eclipse.org

profile.db2.zseries.wizard.title = z/OS용 DB2
profile.db2.zseries.wizard.description = z/OS 연결 프로필용 DB2를 생성합니다.
profile.db2.zseries.properties = 드라이버 속성
