###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB zSeries UI Plug-in
providerName=Eclipse Data Tools Platform

profile.db2.zseries.wizard.title = DB2 für z/OS
profile.db2.zseries.wizard.description = Erstellung eines DB2 für z/OS-Verbindungsprofils.
profile.db2.zseries.properties = Treibereigenschaften
