###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server UI Plug-in
providerName=Eclipse.org

profile.sqlserver.wizard.title = SQL Server
profile.sqlserver.wizard.description = 创建 SQL Server 连接配置文件。
profile.sqlserver.properties = 驱动程序属性
