###############################################################################
# Copyright (c) 2009 Sybase, Inc. and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Sybase, Inc. - initial API and implementation
###############################################################################
PlanView.name=실행 계획
PlanView.preferencePage.title=실행 계획 보기 옵션
DataTools.name=데이터 도구

Plugin.Name = Eclipse Data Tools Platform SQL Execution Plan View Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform
