###############################################################################
# Copyright (c) 2009 Sybase, Inc. and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Sybase, Inc. - initial API and implementation
###############################################################################
PlanView.name=执行计划
PlanView.preferencePage.title=执行计划视图选项
DataTools.name=数据工具

Plugin.Name = Eclipse Data Tools Platform SQL Execution Plan View Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform
