################################################################################
## Copyright (c) 2006-2007 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License 2.0
## which accompanies this distribution, and is available at
## https://www.eclipse.org/legal/epl-2.0/
##
## Contributors: 
##  Ingres - Implementation
################################################################################

PLUGIN_NAME = Plug-in de définition de base de données DTP Ingres
PROVIDER_NAME=Plate-forme d'outils de données Eclipse

PRODUCT_DISPLAY_STRING = Ingres
VERSION_DISPLAY_STRING = 2006
