################################################################################
## Copyright (c) 2006-2007 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License 2.0
## which accompanies this distribution, and is available at
## https://www.eclipse.org/legal/epl-2.0/
##
## Contributors: 
##  Ingres - Implementation
################################################################################

PLUGIN_NAME = Complemento de definición de base de datos Ingres DTP
PROVIDER_NAME=Eclipse Data Tools Platform

PRODUCT_DISPLAY_STRING = Ingres
VERSION_DISPLAY_STRING = 2006
