Connection.PropertiesMissing=Certaines propriétés de connexion sont manquantes.
Connection.InvalidAppContext=AppContext incorrect.
Connection.InvalidSource=The xml source file cannot be found or the URL is malformed.
Constants.DriverName=Pilote XML ODA
ResultSet.ResultSetClosed=Jeu de résultats fermé
Query.QueryHasNotBeenPrepared=La requête n'a pas encore été préparée.
Query.ResultSetClosed=Jeu de résultats fermé
Query.InvalidQueryText=Le texte de la requête est incorrect.
RelationInformation.InputStringCannotBeNull=La chaîne d'entrée ne peut être ni nulle ni vierge. 
RelationInformation.InvalidDataTypeName=Le nom du type de données fourni est incorrect.
RelationInformation.InvalidFilterDefinition=La définition de filtre est incorrecte. 
DateUtil.ConvertFails=Echec de la conversion en date. Source :
dataTypes.typeNameInvalid=Le nom de type de données est incorrect :
dateFormatISO8601.inconvertibleValueError=Impossible de convertir la valeur de 
exception.invalidArgument=Type d'argument non valide.
exception.nullDataSourceContent=La source de données est nulle.
ui.invalidXSDFile=Le fichier xsd fourni est incorrect.

