Connection.PropertiesMissing=いくつかの接続プロパティがありません。
Connection.InvalidAppContext=AppContext が無効です。
Connection.InvalidSource=XML ソースファイルが見つからないか、URL が間違っています。
Constants.DriverName=ODA XML ドライバ
ResultSet.ResultSetClosed=結果セットを閉じました。
Query.QueryHasNotBeenPrepared=クエリがまだ記述されていません。
Query.ResultSetClosed=結果セットを閉じました。
Query.InvalidQueryText=クエリテキストが無効です。
RelationInformation.InputStringCannotBeNull=入力文字列は null または空白にできません。 
RelationInformation.InvalidDataTypeName=指定されたデータ型の名前が無効です。
RelationInformation.InvalidFilterDefinition=フィルタの定義が無効です。 
DateUtil.ConvertFails=日付に変換できません。ソース :
dataTypes.typeNameInvalid=無効なデータ型名 :
dateFormatISO8601.inconvertibleValueError=次の値を変換できません。 
exception.invalidArgument=引数の型が無効です。
exception.nullDataSourceContent=データソースのコンテンツが null です。
ui.invalidXSDFile=指定された XSD ファイルが無効です。

