AbstractDBPreferenceFieldPage_nodb=No se puede encontrar nombre de base de datos por id: {0}

SaveAsDialog_filetype_label=&Tipo de archivo:
SaveAsDialog_overwriteQuestion=El archivo ''{0}'' ya existe. ¿Desea reemplazar el archivo existente?
SaveAsDialog_question=Pregunta
SaveAsDialog_filename=&Nombre de archivo:
SaveAsDialog_export_error=Error de exportación
SaveAsDialog_title=Guardar como
SaveAsDialog_message=Guardar como archivo SQL
SaveAsDialog_error=Error
SaveAsDialog_error_msg=Se produce un error al intentar guardar los scripts como un archivo

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = Guardar como
SaveAsDialog_file = archivo
SaveAsDialog_closedProjectMessage = El proyecto seleccionado está cerrado.
# ==============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# ==============================================================================
Question = Pregunta
