AbstractDBPreferenceFieldPage_nodb=Impossible de trouver le nom de la base de données par l'id : {0}

SaveAsDialog_filetype_label=Type de &fichier :
SaveAsDialog_overwrite=Le fichier "{0}" existe déjà. Voulez-vous le remplacer ?
SaveAsDialog_question=Question
SaveAsDialog_filename=Nom de &fichier :
SaveAsDialog_export_error=Erreur d'exportation
SaveAsDialog_title=Enregistrer sous
SaveAsDialog_message=Enregistrer comme un fichier SQL
SaveAsDialog_error=Erreur
SaveAsDialog_error_msg=Une erreur s'est produite lors de la tentative d'enregistrement des scripts comme un fichier

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = Enregistrer sous
SaveAsDialog_file = fichier
SaveAsDialog_closedProjectMessage = Le projet sélectionné est fermé
# =============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# =============================================================================
Question = Question
Always = &Toujours
Never = &Jamais
Prompt = &Invite
