AbstractDBPreferenceFieldPage_nodb=找不到具有以下标识的数据库名称: {0}

SaveAsDialog_filetype_label=文件类型(&F):
SaveAsDialog_overwrite=文件“{0}”已存在。要替换现有文件吗?
SaveAsDialog_question=问题
SaveAsDialog_filename=文件名(&F):
SaveAsDialog_export_error=导出错误
SaveAsDialog_title=另存为
SaveAsDialog_message=另存为 SQL 文件
SaveAsDialog_error=错误
SaveAsDialog_error_msg=尝试将脚本另存为文件时发生了错误

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = 另存为
SaveAsDialog_file = 文件
SaveAsDialog_closedProjectMessage = 选择的项目已关闭。
# =============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# =============================================================================
Question = 问题
Always = 始终(&A)
Never = 从不(&N)
Prompt = 提示(&P)
