AbstractDBPreferenceFieldPage_nodb=ID が {0} のデータベース名が見つかりません。

SaveAsDialog_filetype_label=ファイルの種類(&F) :
SaveAsDialog_overwrite=指定したファイル ''{0}'' はすでに存在します。既存のファイルを上書きしますか ?
SaveAsDialog_question=質問
SaveAsDialog_filename=ファイル名(&F) :
SaveAsDialog_export_error=エクスポートエラー
SaveAsDialog_title=名前を付けて保存
SaveAsDialog_message=SQL ファイルとして保存
SaveAsDialog_error=エラー
SaveAsDialog_error_msg=スクリプトをファイルとして保存中にエラーが発生しました。

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = 名前を付けて保存
SaveAsDialog_file = file
SaveAsDialog_closedProjectMessage = 選択したプロジェクトは閉じています。
# =============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# =============================================================================
Question = 質問
Always = 常に上書きする(&Al)
Never = 続行しない(&N)
Prompt = 確認メッセージを表示する(&P)
