AbstractDBPreferenceFieldPage_nodb=ID로 데이터베이스 이름을 찾을 수 없습니다: {0}

SaveAsDialog_filetype_label=파일 형식(&F):
SaveAsDialog_overwrite=파일 ''{0}''이(가) 이미 있습니다. 기존 파일을 바꾸시겠습니까?
SaveAsDialog_question=질문
SaveAsDialog_filename=파일 이름(&F):
SaveAsDialog_export_error=내보내기 오류
SaveAsDialog_title=다른 이름으로 저장
SaveAsDialog_message=SQL 파일로 저장
SaveAsDialog_error=오류
SaveAsDialog_error_msg=스크립트를 파일로 저장하는 중 오류가 발생했습니다.

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = 다른 이름으로 저장
SaveAsDialog_file = 파일
SaveAsDialog_closedProjectMessage = 선택한 프로젝트가 닫혔습니다.
# =============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# =============================================================================
Question = 질문
Always = 항상(&A)
Never = 안 함(&N)
Prompt = 묻기(&P)
