AbstractDBPreferenceFieldPage_nodb=Datenbankname nach ID nicht gefunden: {0}

SaveAsDialog_filetype_label=&Dateityp:
SaveAsDialog_overwrite=Die Datei "{0}" ist bereits vorhanden. Ersetzen?
SaveAsDialog_question=Frage
SaveAsDialog_filename=&Dateiname:
SaveAsDialog_export_error=Fehler beim Exportieren
SaveAsDialog_title=Speichern unter
SaveAsDialog_message=Als SQL-Datei speichern
SaveAsDialog_error=Fehler
SaveAsDialog_error_msg=Fehler beim Speichern der Skripte als eine Datei

#######################################
#Copied from IDEWorkbenchMessages
#######################################
SaveAsDialog_text = Speichern unter
SaveAsDialog_file = Datei
SaveAsDialog_closedProjectMessage = Das ausgewählte Projekt wird geschlossen.
# =============================================================================
# Dialogs: Copied from IDEWorkbenchMessages
# =============================================================================
Question = Frage
Always = &Immer
Never = &Nie
Prompt = &Auffordern
