###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=Diseñador de archivos planos de ODA de DTP
oda.data.source.name=Archivos planos de CSV
connection.profile.name=Perfil de conexión de origen de datos de archivo plano ODA
newwizard.name=Origen de datos de archivo plano de ODA
newwizard.description=Crear un perfil de conexión de archivo plano de ODA
wizard.window.title=Perfil de origen de datos de archivo plano nuevo
wizard.data.source.page.title=Seleccionar carpeta
profile.propertypage.name=Propiedades de conexión de origen de datos de archivo plano de ODA
wizard.data.set.page.title=Seleccionar columnas
wizard.data.set.title=Seleccionar tabla
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexiones de ODA
