# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=DTP ODA 텍스트 파일 디자이너
newwizard.name=ODA 텍스트 파일 데이터 소스
newwizard.description=ODA 텍스트 파일 연결 프로파일을 작성합니다.
wizard.window.title=새 텍스트 파일 데이터 소스 프로파일
wizard.data.source.page.title=폴더 선택
profile.propertypage.name=ODA 텍스트 파일 데이터 소스 연결 특성
wizard.data.set.page.title=열 선택
wizard.data.set.title=테이블 선택
