###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=Concepteur de fichiers à plat ODA DTP
oda.data.source.name=Fichiers à plat CSV
connection.profile.name=Profil de connexion de la source de données de fichiers à plat ODA
newwizard.name=Source de données de fichiers à plat ODA
newwizard.description=Créer un profil de connexion de fichier à plat ODA
wizard.window.title=Nouveau profil de source de données à plat
wizard.data.source.page.title=Sélection du dossier
profile.propertypage.name=Propriétés de connexion de la source de données de fichiers à plat ODA
wizard.data.set.page.title=Sélection des colonnes
wizard.data.set.title=Sélection du tableau
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fabrique de connexion ODA
