# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=Eclipse Data Tools Platform Flat File ODA Designer
newwizard.name=平面文件数据源
newwizard.description=创建 ODA 平面文件连接概要文件
wizard.window.title=新建平面文件数据源概要文件
wizard.data.source.page.title=定义文件夹或文件 URI
profile.propertypage.name=平面文件数据源连接属性
wizard.data.set.page.title=选择列
wizard.data.set.title=选择表
