###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=DTP ODA Flat File Designer
oda.data.source.name=CSV フラット・ファイル
connection.profile.name=ODA フラット・ファイル・データ・ソース接続プロファイル
newwizard.name=ODA フラット・ファイル・データ・ソース
newwizard.description=ODA フラット・ファイル接続プロファイルの作成
wizard.window.title=新規フラット・ファイル・データ・ソース・プロファイル
wizard.data.source.page.title=フォルダーの選択
profile.propertypage.name=ODA フラット・ファイル・データ・ソース接続プロパティー
wizard.data.set.page.title=列の選択
wizard.data.set.title=表の選択
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリー
