###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=Entwurfsfunktion für DTP-ODA-Flachdatei
oda.data.source.name=CSV-Flachdateien
connection.profile.name=Verbindungsprofil der Datenquelle für eine ODA-Flachdatei
newwizard.name=Datenquelle für ODA-Flachdatei
newwizard.description=Verbindungsprofil für ODA-Flachdatei erstellen
wizard.window.title=Datenquellenprofil für neue Flachdatei
wizard.data.source.page.title=Ordner auswählen
profile.propertypage.name=Verbindungseigenschaften der Datenquelle für eine ODA-Flachdatei
wizard.data.set.page.title=Spalten auswählen
wizard.data.set.title=Tabelle auswählen
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungsfactory
