###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=DTP ODA 텍스트 파일 디자이너
oda.data.source.name=CSV 텍스트 파일
connection.profile.name=ODA 텍스트 파일 데이터 소스 연결 프로파일
newwizard.name=ODA 텍스트 파일 데이터 소스
newwizard.description=ODA 텍스트 파일 연결 프로파일을 작성합니다.
wizard.window.title=새 텍스트 파일 데이터 소스 프로파일
wizard.data.source.page.title=폴더 선택
profile.propertypage.name=ODA 텍스트 파일 데이터 소스 연결 특성
wizard.data.set.page.title=열 선택
wizard.data.set.title=테이블 선택
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
