###############################################################################
# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS messages
#
plugin.name=Eclipse Data Tools Platform Flat File ODA Designer
newwizard.name=Unstrukturierte Datenquelle
newwizard.description=Verbindungsprofil für ODA-Flachdatei erstellen
wizard.window.title=Datenquellenprofil für neue Flachdatei
wizard.data.source.page.title=Ordner oder Datei-URI definieren
profile.propertypage.name=Verbindungseigenschaften für unstrukturierte Datenquelle
wizard.data.set.page.title=Spalten auswählen
wizard.data.set.title=Tabelle auswählen
