###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
#
plugin.name=DTP ODA 平面文件设计器
oda.data.source.name=CSV 平面文件
connection.profile.name=ODA 平面文件数据源连接概要文件
newwizard.name=ODA 平面文件数据源
newwizard.description=创建 ODA 平面文件连接概要文件
wizard.window.title=新建平面文件数据源概要文件
wizard.data.source.page.title=选择文件夹
profile.propertypage.name=ODA 平面文件数据源连接属性
wizard.data.set.page.title=选择列
wizard.data.set.title=选择表
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
