# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=Eclipse Data Tools Platform Flat File ODA Designer
newwizard.name=フラットファイルデータソース
newwizard.description=ODA フラットファイル 接続プロファイルの作成
wizard.window.title=新規フラットファイルデータソース プロファイル
wizard.data.source.page.title=フォルダまたはファイルの URI の定義
profile.propertypage.name=フラットファイルデータソースの接続プロパティ
wizard.data.set.page.title=列の選択
wizard.data.set.title=表の選択
