# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=Concepteur de fichiers à plat ODA DTP
newwizard.name=Source de données de fichiers à plat ODA
newwizard.description=Créer un profil de connexion de fichier à plat ODA
wizard.window.title=Nouveau profil de source de données à plat
wizard.data.source.page.title=Sélection du dossier
profile.propertypage.name=Propriétés de connexion de la source de données de fichiers à plat ODA
wizard.data.set.page.title=Sélection des colonnes
wizard.data.set.title=Sélection du tableau
