# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=Eclipse Data Tools Platform Flat File ODA Designer
newwizard.name=Fuente de datos de archivo sin formato
newwizard.description=Crear un perfil de conexión de archivo plano de ODA
wizard.window.title=Perfil de origen de datos de archivo plano nuevo
wizard.data.source.page.title=Definir carpeta o un URI de archivo
profile.propertypage.name=Propiedades de conexión de fuente de datos de archivo sin formato
wizard.data.set.page.title=Seleccionar columnas
wizard.data.set.title=Seleccionar tabla
