# Copyright (c) 2005, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration
#
oda.data.source.id=org.eclipse.datatools.connectivity.oda.flatfile
#
###############################################################################
# NLS Strings
#
plugin.name=DTP ODA Flat File Designer
newwizard.name=ODA フラット・ファイル・データ・ソース
newwizard.description=ODA フラット・ファイル接続プロファイルの作成
wizard.window.title=新規フラット・ファイル・データ・ソース・プロファイル
wizard.data.source.page.title=フォルダーの選択
profile.propertypage.name=ODA フラット・ファイル・データ・ソース接続プロパティー
wizard.data.set.page.title=列の選択
wizard.data.set.title=表の選択
