###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB iSeries Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V5R2ProductString = DB2 for i5/OS
V5R2VersionString = V5R2

V5R3ProductString = DB2 for i5/OS
V5R3VersionString = V5R3

V5R2Description = IBM DB2 UDB para iSeries versión 5 revisión 2
V5R3Description = IBM DB2 UDB para iSeries versión 5 revisión 3
