INSERT INTO department VALUES (34,'TestTools','T01',null);
INSERT INTO department (DEPTNO, DEPTNAME, ADMRDEPT) VALUES ('T02',default,'T01');
INSERT INTO department (DEPTNO, DEPTNAME, ADMRDEPT) VALUES ('T02',DEFAULT,'T01'),('T02',654,'T01'),('T02',NULL,'T01');
