#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Data Tools Platform - Plug-in für Konnektivitäts-UI
Plugin.ProviderName=Eclipse.org
Database.category=Datenbanken
Extension.PropertyPage.General.Name=Allgemein
Extension.PropertyPage.Version.Name=Version
ProfileFailure = Profilfehler
driverProblem = Treiberprobleme
Extension.NewWizard.Name=Verbindungsprofil
Extension.NewWizard.Description=Verbindungsprofil erstellen
Extension.NewRepositoryWizard.Name = Verbindungsprofil-Repository
Extension.NewRepositoryWizard.Description = Neues Repository für Verbindungsprofile erstellen
datatools.preference.page.name=Konnektivität
drivers.preference.page.name=Treiberdefinitionen
category.name.connectionProfiles=Verbindungsprofile
DSE.content = Erweiterung für Datenquellen-Explorer
