#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=데이터 도구 플랫폼 연결 UI 플러그인
Plugin.ProviderName=Eclipse.org
Database.category=데이터베이스
Extension.PropertyPage.General.Name=공통
Extension.PropertyPage.Version.Name=버전
ProfileFailure = 프로필 실패
Extension.NewWizard.Name=연결 프로파일
Extension.NewWizard.Description=연결 프로파일을 작성합니다.
driverProblem = 드라이버 문제
Extension.NewWizard.Name.Name = 연결 프로필 리포지토리
Extension.NewRepositoryWizard.Description = 연결 프로필에 대한 새 리포지토리 생성
datatools.preference.page.name=연결
drivers.preference.page.name=드라이버 정의
category.name.connectionProfiles=연결 프로파일
datatools.core.ui.preferences.data.node = 데이터 툴링

DSE.content = 데이터 원본 탐색기 확장명

AddProfile.command.label = 새 연결 프로필 명령
AddProfile.command.description = 새 연결 프로필을 생성하는 명령
AddRepositoryProfile.command.label = 새 리포지토리 프로필 명령
AddRepositoryProfile.command.description = 새 리포지토리 프로필을 생성하는 명령
ExportProfile.command.label = 프로필 내보내기 명령
ExportProfile.command.description = 연결 프로필을 내보내는 명령
ImportProfile.command.label = 프로필 가져오기 명령
ImportProfile.command.description = 연결 프로필을 가져오는 명령
