################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name=Plug-in d'interface utilisateur de connectivité de la plateforme d'Outils de données
Plugin.ProviderName=Eclipse.org
Database.category=Bases de données
Extension.PropertyPage.General.Name=Commun
Extension.PropertyPage.Version.Name=Version
ProfileFailure = Echecs des profils
driverProblem = Problèmes de pilote
Extension.NewWizard.Name=Profil de connexion
Extension.NewWizard.Description=Créer un profil de connexion
Extension.NewRepositoryWizard.Name = Référentiel de profils de connexion
Extension.NewRepositoryWizard.Description = Créer un nouveau référentiel pour les profils de connexion
datatools.preference.page.name=Connectivité
drivers.preference.page.name=Définitions de pilote
category.name.connectionProfiles=Profils de connexion
datatools.core.ui.preferences.data.node = Gestion de données

DSE.content = Extension de l'explorateur de source de données
CP.content = Connection Profiles

AddProfile.command.label = Commande nouveau profil de connexion
AddProfile.command.description = Commande pour créer un nouveau profil de connexion
AddRepositoryProfile.command.label = Commande nouveau profil de référentiel
AddRepositoryProfile.command.description = Commande pour créer un nouveau profil de référentiel
ExportProfile.command.label = Commande de profils d'exportation
ExportProfile.command.description = Commande pour exporter des profils de connexion
ImportProfile.command.label = Commande de profils d'importation
ImportProfile.command.description = Commande pour importer des profils de connexion
