#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Plug-in d'interface utilisateur de connectivité de la plateforme d'Outils de données
Plugin.ProviderName=Eclipse.org
Database.category=Bases de données
Extension.PropertyPage.General.Name=Commun
Extension.PropertyPage.Version.Name=Version
ProfileFailure = Echecs des profils
driverProblem = Problèmes de pilote
Extension.NewWizard.Name=Profil de connexion
Extension.NewWizard.Description=Créer un profil de connexion
Extension.NewRepositoryWizard.Name = Référentiel de profils de connexion
Extension.NewRepositoryWizard.Description = Créer un nouveau référentiel pour les profils de connexion
datatools.preference.page.name=Connectivité
drivers.preference.page.name=Définitions de pilote
category.name.connectionProfiles=Profils de connexion
datatools.core.ui.preferences.data.node = Outillage des données

DSE.content = Extension de l'explorateur de source de données

AddProfile.command.label = Commande nouveau profil de connexion
AddProfile.command.description = Commande pour créer un nouveau profil de connexion
AddRepositoryProfile.command.label = Commande nouveau profil de référentiel
AddRepositoryProfile.command.description = Commande pour créer un nouveau profil de référentiel
ExportProfile.command.label = Commande de profils d'exportation
ExportProfile.command.description = Commande pour exporter des profils de connexion
ImportProfile.command.label = Commande de profils d'importation
ImportProfile.command.description = Commande pour importer des profils de connexion
