#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Plug-in UI de Conectividad de la Plataforma de herramientas de datos
Plugin.ProviderName=Eclipse.org
Database.category=Bases de datos
Extension.PropertyPage.General.Name=Común
Extension.PropertyPage.Version.Name=Versión
ProfileFailure=Anomalías del Explorador de orígenes de datos
Extension.NewWizard.Name=Perfil de conexión
Extension.NewWizard.Description=Crear un perfil de conexión
datatools.preference.page.name=Conectividad
drivers.preference.page.name=Definiciones de controlador
category.name.connectionProfiles=Perfiles de conexión
