#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=데이터 도구 플랫폼 연결 UI 플러그인
Plugin.ProviderName=Eclipse.org
Database.category=데이터베이스
Extension.PropertyPage.General.Name=공통
Extension.PropertyPage.Version.Name=버전
ProfileFailure = 프로필 실패
Extension.NewWizard.Name=연결 프로파일
Extension.NewWizard.Description=연결 프로파일을 작성합니다.
driverProblem = 드라이버 문제
Extension.NewWizard.Name.Name = 연결 프로필 리포지토리
Extension.NewRepositoryWizard.Description = 연결 프로필에 대한 새 리포지토리 생성
datatools.preference.page.name=연결
drivers.preference.page.name=드라이버 정의
category.name.connectionProfiles=연결 프로파일
DSE.content = 데이터 원본 탐색기 확장명
