#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Plug-in d'interface utilisateur de connectivité de la plateforme d'Outils de données
Plugin.ProviderName=Eclipse.org
Database.category=Bases de données
Extension.PropertyPage.General.Name=Commun
Extension.PropertyPage.Version.Name=Version
ProfileFailure=Echecs de l'explorateur de source de données
Extension.NewWizard.Name=Profil de connexion
Extension.NewWizard.Description=Créer un profil de connexion
Extension.NewRepositoryWizard.Name = Référentiel de profils de connexion
Extension.NewRepositoryWizard.Description = Créer un nouveau référentiel pour les profils de connexion
datatools.preference.page.name=Connectivité
drivers.preference.page.name=Définitions de pilote
category.name.connectionProfiles=Profils de connexion
