################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name=Plug-in UI de Conectividad de la Plataforma de herramientas de datos
Plugin.ProviderName=Eclipse.org
Database.category=Bases de datos
Extension.PropertyPage.General.Name=Común
Extension.PropertyPage.Version.Name=Versión
ProfileFailure = Errores de perfil
driverProblem = Problemas con el controlador
Extension.NewWizard.Name=Perfil de conexión
Extension.NewWizard.Description=Crear un perfil de conexión
Extension.NewRepositoryWizard.Name = Repositorio de perfiles de conexión
Extension.NewRepositoryWizard.Description = Crear un nuevo repositorio para perfiles de conexión
datatools.preference.page.name=Conectividad
drivers.preference.page.name=Definiciones de controlador
category.name.connectionProfiles=Perfiles de conexión
datatools.core.ui.preferences.data.node = Administración de datos

DSE.content = Extensión de explorador de fuentes de datos
CP.content = Connection Profiles

AddProfile.command.label = Nuevo comando de perfil de conexión
AddProfile.command.description = Comando para crear un nuevo perfil de conexión
AddRepositoryProfile.command.label = Nuevo comando de perfil de repositorio
AddRepositoryProfile.command.description = Comando para crear un nuevo perfil de repositorio
ExportProfile.command.label = Exportar comando de perfiles
ExportProfile.command.description = Comando para exportar perfiles de conexión
ImportProfile.command.label = Importar comando de perfiles
ImportProfile.command.description = Comando para importar perfiles de conexión
