################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name=数据工具平台连接 UI 插件
Plugin.ProviderName=Eclipse.org
Database.category=数据库
Extension.PropertyPage.General.Name=公共
Extension.PropertyPage.Version.Name=版本
ProfileFailure = 配置文件失败
driverProblem = 驱动程序问题
Extension.NewWizard.Name=连接概要文件
Extension.NewWizard.Description=创建连接概要文件
Extension.NewRepositoryWizard.Name = 连接配置文件存储库
Extension.NewRepositoryWizard.Description = 为连接配置文件创建新存储库
datatools.preference.page.name=连接
drivers.preference.page.name=驱动程序定义
category.name.connectionProfiles=连接概要文件
datatools.core.ui.preferences.data.node = 数据管理

DSE.content = 数据源资源管理器扩展
CP.content = Connection Profiles

AddProfile.command.label = 新建连接配置文件命令
AddProfile.command.description = 用于创建新连接配置文件的命令
AddRepositoryProfile.command.label = 新建存储库配置文件命令
AddRepositoryProfile.command.description = 用于创建新存储库配置文件的命令
ExportProfile.command.label = 导出配置文件命令
ExportProfile.command.description = 用于导出连接配置文件的命令
ImportProfile.command.label = 导入配置文件命令
ImportProfile.command.description = 用于导入连接配置文件的命令
