#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=데이터 도구 플랫폼 연결 UI 플러그인
Plugin.ProviderName=Eclipse.org
Database.category=데이터베이스
Extension.PropertyPage.General.Name=공통
Extension.PropertyPage.Version.Name=버전
ProfileFailure=데이터 소스 탐색기 실패
Extension.NewWizard.Name=연결 프로파일
Extension.NewWizard.Description=연결 프로파일을 작성합니다.
datatools.preference.page.name=연결
drivers.preference.page.name=드라이버 정의
category.name.connectionProfiles=연결 프로파일
