#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Data Tools Platform Connectivity UI Plug-in
Plugin.ProviderName=Eclipse.org
Database.category=データベース
Extension.PropertyPage.General.Name=共通
Extension.PropertyPage.Version.Name=バージョン
ProfileFailure=データ・ソース・エクスプローラーの失敗
Extension.NewWizard.Name=接続プロファイル
Extension.NewWizard.Description=接続プロファイルの作成
datatools.preference.page.name=接続
drivers.preference.page.name=ドライバー定義
category.name.connectionProfiles=接続プロファイル
