#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Plug-in UI de Conectividad de la Plataforma de herramientas de datos
Plugin.ProviderName=Eclipse.org
Database.category=Bases de datos
Extension.PropertyPage.General.Name=Común
Extension.PropertyPage.Version.Name=Versión
ProfileFailure = Errores de perfil
driverProblem = Problemas con el controlador
Extension.NewWizard.Name=Perfil de conexión
Extension.NewWizard.Description=Crear un perfil de conexión
Extension.NewRepositoryWizard.Name = Repositorio de perfiles de conexión
Extension.NewRepositoryWizard.Description = Crear un nuevo repositorio para perfiles de conexión
datatools.preference.page.name=Conectividad
drivers.preference.page.name=Definiciones de controlador
category.name.connectionProfiles=Perfiles de conexión
DSE.content = Extensión de explorador de fuentes de datos

AddProfile.command.label = Nuevo comando de perfil de conexión
AddProfile.command.description = Comando para crear un nuevo perfil de conexión
AddRepositoryProfile.command.label = Nuevo comando de perfil de repositorio
AddRepositoryProfile.command.description = Comando para crear un nuevo perfil de repositorio
ExportProfile.command.label = Exportar comando de perfiles
ExportProfile.command.description = Comando para exportar perfiles de conexión
ImportProfile.command.label = Importar comando de perfiles
ImportProfile.command.description = Comando para importar perfiles de conexión
