#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Data Tools Platform - Plug-in für Konnektivitäts-UI
Plugin.ProviderName=Eclipse.org
Database.category=Datenbanken
Extension.PropertyPage.General.Name=Allgemein
Extension.PropertyPage.Version.Name=Version
ProfileFailure=Fehler bei Datenquellen-Explorer
Extension.NewWizard.Name=Verbindungsprofil
Extension.NewWizard.Description=Verbindungsprofil erstellen
datatools.preference.page.name=Konnektivität
drivers.preference.page.name=Treiberdefinitionen
category.name.connectionProfiles=Verbindungsprofile
