#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=数据工具平台连接 UI 插件
Plugin.ProviderName=Eclipse.org
Database.category=数据库
Extension.PropertyPage.General.Name=公共
Extension.PropertyPage.Version.Name=版本
ProfileFailure=数据源资源管理器故障
Extension.NewWizard.Name=连接概要文件
Extension.NewWizard.Description=创建连接概要文件
Extension.NewRepositoryWizard.Name = 连接配置文件存储库
Extension.NewRepositoryWizard.Description = 为连接配置文件创建新存储库
datatools.preference.page.name=连接
drivers.preference.page.name=驱动程序定义
category.name.connectionProfiles=连接概要文件
