#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Data Tools Platform Connectivity UI Plug-in
Plugin.ProviderName=Eclipse.org
Database.category=データベース
Extension.PropertyPage.General.Name=共通
Extension.PropertyPage.Version.Name=バージョン
ProfileFailure = プロファイルエラー
driverProblem = ドライバの問題
Extension.NewWizard.Name=接続プロファイル
Extension.NewWizard.Description=接続プロファイルの作成
Extension.NewRepositoryWizard.Name = 接続プロファイルのリポジトリ
Extension.NewRepositoryWizard.Description = 接続プロファイルへの新しいリポジトリの作成
datatools.preference.page.name=接続
drivers.preference.page.name=ドライバー定義
category.name.connectionProfiles=接続プロファイル
datatools.core.ui.preferences.data.node = データツーリング

DSE.content = データソースエクスプローラの拡張

AddProfile.command.label = 新しい接続プロファイルのコマンド
AddProfile.command.description = このコマンドを実行すると、新しい接続プロファイルが作成されます。
AddRepositoryProfile.command.label = 新しいリポジトリプロファイルのコマンド
AddRepositoryProfile.command.description = このコマンドを実行すると、新しいリポジトリプロファイルが作成されます。
ExportProfile.command.label = プロファイルのエクスポートコマンド
ExportProfile.command.description = このコマンドを実行すると、接続プロファイルがエクスポートされます。
ImportProfile.command.label = プロファイルのインポートコマンド
ImportProfile.command.description = このコマンドを実行すると、接続プロファイルがインポートされます。
