#Thu Jun 22 00:30:53 EDT 2006
Plugin.Name=Data Tools Platform - Plug-in für Konnektivitäts-UI
Plugin.ProviderName=Eclipse.org
Database.category=Datenbanken
Extension.PropertyPage.General.Name=Allgemein
Extension.PropertyPage.Version.Name=Version
ProfileFailure = Profilfehler
driverProblem = Treiberprobleme
Extension.NewWizard.Name=Verbindungsprofil
Extension.NewWizard.Description=Verbindungsprofil erstellen
Extension.NewRepositoryWizard.Name = Verbindungsprofil-Repository
Extension.NewRepositoryWizard.Description = Neues Repository für Verbindungsprofile erstellen
datatools.preference.page.name=Konnektivität
drivers.preference.page.name=Treiberdefinitionen
category.name.connectionProfiles=Verbindungsprofile
datatools.core.ui.preferences.data.node = Datentools

DSE.content = Erweiterung für Datenquellen-Explorer

AddProfile.command.label = Befehl 'Neues Verbindungsprofil'
AddProfile.command.description = Befehl zur Erstellung eines neuen Verbindungsprofils
AddRepositoryProfile.command.label = Befehl 'Neues Repository-Profil'
AddRepositoryProfile.command.description = Befehl zur Erstellung eines neuen Repository-Profils
ExportProfile.command.label = Befehl 'Profile exportieren'
ExportProfile.command.description = Befehl zum Exportieren von Verbindungsprofilen
ImportProfile.command.label = Befehl 'Profile importieren'
ImportProfile.command.description = Befehl zum Importieren von Verbindungsprofilen
