#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue={0} valor de argumento: {1}
editorAppl_exitAppl=La aplicación {0} se ha cerrado.
editorAppl_invalidFileName=Nombre de archivo ({0}) no es válido.
editorAppl_invalidInputFile=El archivo de entrada ({0}) no existe o no se puede leer.
editorAppl_invalidOutputFile=El archivo de salida ({0}) no es válido o no permite escritura.
editorAppl_missingArgValue=Falta un valor para el argumento {0}.
editorAppl_noProfileChanges=No ha habido cambios en el perfil o perfiles de conexión.
editorAppl_overwriteExistingFile=El archivo de salida ({0}) ya existe. ¿Desea sobrescribir su contenido?
editorAppl_promptEditProfileName=Introduzca el nombre de un perfil de conexión para ver o cambiar (opcional)
editorAppl_promptInputFile=Introduzca el nombre de un archivo de perfil de conexión para ver o cambiar (opcional)
editorAppl_promptOutputFile=Introduzca el nombre del archivo de salida para guardar los cambios
editorAppl_startAppl=Iniciar la aplicación {0}...
editorAppl_syntaxArguments=Argumentos de línea de comando opcionales:
editorAppl_syntaxCommand=Utilice "eclipsec" en los comandos de Windows o "eclipse" en otras plataformas.
editorAppl_syntaxHelpInstruction=muestra el siguiente mensaje de ayuda
editorAppl_syntaxInArgInstruction=especifica el archivo de almacenamiento del perfil de conexión para ver o cambiar
editorAppl_syntaxNullArgInstruction=Si no se especifica un valor de argumento, el editor solicitará un valor de entrada.
editorAppl_syntaxOutArgInstruction=especifica el nombre del archivo de salida para guardar los cambios
editorAppl_syntaxProfileNameInstruction1=especifica el nombre de un perfil de conexión para ver o cambiar, en caso de que no se especifique ninguno,
editorAppl_syntaxProfileNameInstruction2=la herramienta pasará por todos los perfiles del archivo de entrada
editorAppl_syntaxUsage=Sintaxis de comandos:
#
ioutil_askReviewStack=¿Desea ver el rastreo de pila?
ioutil_askUpdateValue=¿Desea modificar el valor existente?
ioutil_confirmUserInputChar=y
ioutil_confirmPromptInstruction=para confirmar
ioutil_errorSystemInput=Error al leer de la consola de entrada.
ioutil_exceptionCause=Causa de la excepción: {0}
ioutil_newValuePrompt=Valor nuevo
#
profileFile_askEncryptOutput=¿Desea cifrar el archivo de salida?
profileFile_askUpdateProfile=¿Desea ver o cambiar las propiedades del perfil?
profileFile_errorInstruction=Consulte el registro del área de trabajo para ver posibles excepciones adicionales.
profileFile_errorReadingFile=Ha ocurrido un error al leer el contenido del archivo de entrada de perfil.
profileFile_errorSavingFile=Error al guardar las propiedades modificadas en el archivo de salida.
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=Advertencia: no están disponibles las definiciones de las propiedades. Se ocultarán todos los valores de propiedad existentes.
profileFile_noProfileFound=No se ha encontrado ningún perfil en el archivo de entrada.
profileFile_profileIdentifier=nombre del perfil {0}
profileFile_propertyDriverClass=Clase del controlador JDBC
profileFile_propertyJarList=Rutas Jar del controlador JDBC (utilice ''{0}'' para separar las rutas)
profileFile_propertyPassword=Contraseña
profileFile_propertyUrl=URL de conexión
profileFile_propertyUser=Nombre de usuario
profileFile_specifiedProfileNotFound=No se ha encontrado el perfil especificado ({0}) en el archivo de entrada.
profileFile_statusDone=Finalizado.
profileFile_statusIteratingProfiles=Pasando por cada uno de los perfiles {0} encontrados en el archivo de entrada...
profileFile_statusReadingFile=Leyendo el archivo de entrada ({0})...
profileFile_statusSavingFile=Guardando las propiedades modificadas en el archivo de salida ({0})...
