#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue={0} 参数值: {1}
editorAppl_exitAppl=已退出 {0} 应用程序。
editorAppl_invalidFileName=无效的文件名 ({0})。
editorAppl_invalidInputFile=输入文件 ({0}) 不存在或无法读取。
editorAppl_invalidOutputFile=输出文件 ({0}) 无效或不可写入。
editorAppl_missingArgValue={0} 参数缺少值。
editorAppl_noProfileChanges=未对连接配置文件进行更改。
editorAppl_overwriteExistingFile=输出文件 ({0}) 已存在。是否覆盖其内容?
editorAppl_promptEditProfileName=输入要查看/更改的连接配置文件的名称(可选)
editorAppl_promptInputFile=输入要查看/更改的连接配置文件的名称
editorAppl_promptOutputFile=输入用于保存更改的输出文件的名称
editorAppl_startAppl=启动 {0} 应用程序...
editorAppl_syntaxArguments=可选命令行参数:
editorAppl_syntaxCommand=在 Windows 上的命令中使用 "eclipsec"，或者在其它平台上使用 "eclipse"。
editorAppl_syntaxHelpInstruction=显示此帮助消息
editorAppl_syntaxInArgInstruction=指定要查看/更改的连接配置文件存储文件的名称
editorAppl_syntaxNullArgInstruction=如果没有指定参数值，编辑器将提示输入值。
editorAppl_syntaxOutArgInstruction=指定用于保存更改的输出文件的名称
editorAppl_syntaxProfileNameInstruction1=指定要查看/更改的连接配置文件的名称(如果未指定)，
editorAppl_syntaxProfileNameInstruction2=工具将单步执行在输入文件中找到的所有配置文件
editorAppl_syntaxUsage=命令语法:
#
ioutil_askReviewStack=是否要查看堆栈跟踪?
ioutil_askUpdateValue=是否更改现有值?
ioutil_confirmUserInputChar=y
ioutil_confirmPromptInstruction=确认
ioutil_errorSystemInput=从输入控制台读取时出错。
ioutil_exceptionCause=异常是由 {0} 引起的
ioutil_newValuePrompt=新值
#
profileFile_askEncryptOutput=是否要加密输出文件?
profileFile_askUpdateProfile=查看或更改配置文件属性?
profileFile_errorInstruction=请参阅工作区日志以了解其它可能的异常。
profileFile_errorReadingFile=读取配置文件输入文件的内容时出错。
profileFile_errorSavingFile=将更改的属性保存到输出文件时出错。
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=警告: 属性定义不可用。所有现有的属性值都将被屏蔽。
profileFile_noProfileFound=在输入文件中无法找到配置文件。
profileFile_profileIdentifier={0} 配置文件名称
profileFile_propertyDriverClass=JDBC 驱动程序类
profileFile_propertyJarList=JDBC 驱动程序 Jar 路径(使用“{0}”分隔路径)
profileFile_propertyPassword=密码
profileFile_propertyUrl=连接 URL
profileFile_propertyUser=用户名
profileFile_specifiedProfileNotFound=在输入文件中无法找到指定的配置文件 ({0})。
profileFile_statusDone=完成。
profileFile_statusIteratingProfiles=正在单步执行在输入文件中找到的每个 {0} 配置文件...
profileFile_statusReadingFile=正在读取输入文件 ({0})...
profileFile_statusSavingFile=正在将更改的属性保存到输出文件 ({0})...
