#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue=Valeur de l'argument {0} : {1}
editorAppl_exitAppl=L'application {0} s'est fermée.
editorAppl_invalidFileName=Nom de fichier incorrect ({0}).
editorAppl_invalidInputFile=Le fichier d'entrée ({0}) n'existe pas ou est illisible.
editorAppl_invalidOutputFile=Le nom du fichier de sortie ({0}) est incorrect ou n'est pas accessible en écriture.
editorAppl_missingArgValue=Valeur manquante pour l'argument {0}.
editorAppl_noProfileChanges=Aucune modification n'a été apportée au(x) profil(s) de connexion.
editorAppl_overwriteExistingFile=Le fichier de sortie ({0}) existe déjà. Ecraser son contenu ?
editorAppl_promptEditProfileName=Entrez le nom d'un profil de connexion à afficher/modifier (facultatif)
editorAppl_promptInputFile=Entrez le nom du fichier du profil de connexion à afficher/modifier (facultatif)
editorAppl_promptOutputFile=Entrez le nom du fichier de sortie pour enregistrer vos modifications
editorAppl_startAppl=Lancer l'application {0}...
editorAppl_syntaxArguments=Arguments de ligne de commande facultatifs :
editorAppl_syntaxCommand=Utilisez "eclipsec" dans la commande sur Windows, ou "eclipse" sur les autres plates-formes.
editorAppl_syntaxHelpInstruction=affiche ce message d'aide
editorAppl_syntaxInArgInstruction=spécifie le nom du fichier de stockage du profil de connexion à afficher/modifier
editorAppl_syntaxNullArgInstruction=Si une valeur d'argument n'est pas spécifiée, l'éditeur demandera une valeur d'entrée.
editorAppl_syntaxOutArgInstruction=spécifie le nom du fichier de sortie pour enregistrer vos modifications
editorAppl_syntaxProfileNameInstruction1=spécifie le nom d'un profil de connexion à afficher/modifier ; si aucun nom n'a été spécifié,
editorAppl_syntaxProfileNameInstruction2=l'outil exécutera tous les profils détectés dans le fichier d'entrée
editorAppl_syntaxUsage=Syntaxe de la commande :
#
ioutil_askReviewStack=Voulez-vous afficher la trace de la pile ?
ioutil_askUpdateValue=Modifier la valeur existante ?
ioutil_confirmUserInputChar=y
ioutil_confirmPromptInstruction=pour confirmer
ioutil_errorSystemInput=Erreur lors de la lecture à partir de la console d'entrée.
ioutil_exceptionCause=Cause de l'exception : {0}
ioutil_newValuePrompt=Nouvelle valeur
#
profileFile_askEncryptOutput=Voulez-vous chiffrer le fichier de sortie ?
profileFile_askUpdateProfile=Afficher ou modifier les propriétés du profil ?
profileFile_errorInstruction=Reportez-vous au journal de l'espace de travail pour obtenir les éventuelles exceptions complémentaires.
profileFile_errorReadingFile=Erreur lors de la lecture du contenu du fichier d'entrée du profil.
profileFile_errorSavingFile=Erreur lors de l'enregistrement des propriétés modifiées dans le fichier de sortie.
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=Avertissement : les définitions de propriétés ne sont pas disponibles. Toutes les valeurs de propriétés existantes seront masquées.
profileFile_noProfileFound=Aucun profil n'a été détecté dans le fichier d'entrée.
profileFile_profileIdentifier=Nom de profil {0}
profileFile_propertyDriverClass=Classe de pilote JDBC
profileFile_propertyJarList=Chemins Jar du pilote JDBC (utilisez ''{0}'' pour séparer les chemins)
profileFile_propertyPassword=Mot de passe
profileFile_propertyUrl=URL de connexion
profileFile_propertyUser=Nom d'utilisateur
profileFile_specifiedProfileNotFound=Le profil spécifié ({0}) est introuvable dans le fichier d'entrée.
profileFile_statusDone=Terminé.
profileFile_statusIteratingProfiles=Exécution de chacun des {0} profils détectés dans le fichier...
profileFile_statusReadingFile=Lecture du fichier d'entrée ({0})...
profileFile_statusSavingFile=Enregistrement des propriétés modifiées dans le fichier de sortie ({0}) en cours...
