#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue={0} 引数の値 : {1}
editorAppl_exitAppl={0} アプリケーションを終了しました。
editorAppl_invalidFileName=ファイル名 ({0}) は無効です。
editorAppl_invalidInputFile=入力ファイル ({0}) が存在しないか、読み込めません。
editorAppl_invalidOutputFile=出力ファイル ({0}) が無効か、書き込めません。
editorAppl_missingArgValue={0} 引数に値が指定されていません。
editorAppl_noProfileChanges=接続プロファイルは変更されませんでした。
editorAppl_overwriteExistingFile=出力ファイル ({0}) はすでに存在します。内容を上書きしますか ?
editorAppl_promptEditProfileName=表示・変更する接続プロファイルの名前を入力してください (オプション)。
editorAppl_promptInputFile=表示・変更する接続プロファイルのファイル名を入力してください。
editorAppl_promptOutputFile=変更を保存する出力ファイルの名前を入力してください。
editorAppl_startAppl={0} アプリケーションを起動しています...
editorAppl_syntaxArguments=オプションのコマンドラインの引数 :
editorAppl_syntaxCommand=Windows では eclipsec コマンドを、他のプラットフォームでは eclipse コマンドを使用します。
editorAppl_syntaxHelpInstruction=このヘルプメッセージを表示します。
editorAppl_syntaxInArgInstruction=表示・変更する接続プロファイルの保存用ファイル名を指定します。
editorAppl_syntaxNullArgInstruction=引数の値を指定しない場合は、値を入力するプロンプトが表示されます。
editorAppl_syntaxOutArgInstruction=変更を保存する出力ファイルの名前を指定します。
editorAppl_syntaxProfileNameInstruction1=表示・変更する接続プロファイルの名前を指定します (まだ指定していない場合)。
editorAppl_syntaxProfileNameInstruction2=入力ファイルにあるすべてのプロファイルを検証します。
editorAppl_syntaxUsage=コマンド構文 :
#
ioutil_askReviewStack=スタックトレースを表示しますか ?
ioutil_askUpdateValue=既存の値を変更しますか ?
ioutil_confirmUserInputChar=y
ioutil_confirmPromptInstruction=確定します。
ioutil_errorSystemInput=入力コンソールからの読み取りエラーが発生しました。
ioutil_exceptionCause={0} で例外が発生しました。
ioutil_newValuePrompt=新規の値
#
profileFile_askEncryptOutput=出力ファイルを暗号化しますか ?
profileFile_askUpdateProfile=プロファイルのプロパティを表示・変更しますか ?
profileFile_errorInstruction=その他の例外は、ワークスペースログを参照してください。
profileFile_errorReadingFile=プロファイル入力ファイルの内容を読み取り中にエラーが発生しました。
profileFile_errorSavingFile=変更したプロパティを出力ファイルへ保存中にエラーが発生しました。
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=警告 : プロパティの定義がありません。既存のプロパティ値はすべてマスクされます。
profileFile_noProfileFound=入力ファイルにプロファイルがありません。
profileFile_profileIdentifier={0} プロファイル名
profileFile_propertyDriverClass=JDBC ドライバクラス
profileFile_propertyJarList=JDBC ドライバの Jar パス (パスの区切りには ''{0}'' を使用)
profileFile_propertyPassword=パスワード
profileFile_propertyUrl=接続 URL
profileFile_propertyUser=ユーザ名
profileFile_specifiedProfileNotFound=指定したプロファイル ({0}) は入力ファイルにありません。
profileFile_statusDone=完了しました。
profileFile_statusIteratingProfiles=入力ファイルにある {0} 個のプロファイルをそれぞれ検証しています...
profileFile_statusReadingFile=入力ファイル ({0}) を読み込んでいます...
profileFile_statusSavingFile=出力ファイル ({0}) に変更したプロパティを保存しています...
