#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue={0} 인수 값: {1}
editorAppl_exitAppl={0} 응용 프로그램이 종료되었습니다.
editorAppl_invalidFileName=잘못된 파일 이름({0})입니다.
editorAppl_invalidInputFile=입력 파일({0})이 없거나 읽을 수 없습니다.
editorAppl_invalidOutputFile=출력 파일({0})이 잘못되었거나 쓸 수 없습니다.
editorAppl_missingArgValue={0} 인수의 값이 누락되었습니다.
editorAppl_noProfileChanges=연결 프로필에 변경된 사항이 없습니다.
editorAppl_overwriteExistingFile=출력 파일({0})이 이미 있습니다. 내용을 덮어쓰시겠습니까?
editorAppl_promptEditProfileName=보거나 변경할 연결 프로필의 이름을 입력하십시오(옵션).
editorAppl_promptInputFile=보거나 변경할 연결 프로필 파일의 이름을 입력하십시오(옵션).
editorAppl_promptOutputFile=변경 사항을 저장할 출력 파일의 이름을 입력하십시오.
editorAppl_startAppl={0} 응용 프로그램 시작...
editorAppl_syntaxArguments=명령줄 인수(옵션):
editorAppl_syntaxCommand=Windows에서는 "eclipsec" 명령을 사용하고 다른 플랫폼에서는 "eclipse" 명령을 사용합니다.
editorAppl_syntaxHelpInstruction=이 도움말을 표시합니다.
editorAppl_syntaxInArgInstruction=보거나 변경할 연결 프로필 저장소 파일의 이름을 지정하십시오.
editorAppl_syntaxNullArgInstruction=인수 값을 지정하지 않으면 편집기에 인수 값을 묻는 창이 표시됩니다.
editorAppl_syntaxOutArgInstruction=변경 사항을 저장할 출력 파일의 이름을 지정하십시오.
editorAppl_syntaxProfileNameInstruction1=보거나 변경할 연결 프로필의 이름을 지정하십시오. 아무 것도 지정하지 않으면
editorAppl_syntaxProfileNameInstruction2=도구가 입력 파일에서 찾은 모든 프로필을 차례대로 실행합니다.
editorAppl_syntaxUsage=명령 구문:
#
ioutil_askReviewStack=스택 추적을 보시겠습니까?
ioutil_askUpdateValue=기존 값을 변경하시겠습니까?
ioutil_confirmUserInputChar=y
ioutil_confirmPromptInstruction=를 눌러 확인
ioutil_errorSystemInput=입력 콘솔에서 읽는 도중 오류가 발생했습니다.
ioutil_exceptionCause=예외 발생 원인: {0}
ioutil_newValuePrompt=새 값
#
profileFile_askEncryptOutput=출력 파일을 암호화하시겠습니까?
profileFile_askUpdateProfile=프로필 속성을 보거나 변경하시겠습니까?
profileFile_errorInstruction=가능한 추가 예외는 작업 영역 로그를 확인하십시오.
profileFile_errorReadingFile=프로필 입력 파일의 내용을 읽는 도중 오류가 발생했습니다.
profileFile_errorSavingFile=출력 파일에 변경한 속성을 저장하는 도중 오류가 발생했습니다.
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=경고: 속성 정의를 사용할 수 없습니다. 기존 속성의 모든 값이 마스크됩니다.
profileFile_noProfileFound=입력 파일에 프로필이 없습니다.
profileFile_profileIdentifier={0} 프로필 이름
profileFile_propertyDriverClass=JDBC 드라이버 클래스
profileFile_propertyJarList=JDBC Driver Jar 경로(''{0}''을(를) 사용해 경로 구분)
profileFile_propertyPassword=암호
profileFile_propertyUrl=연결 URL
profileFile_propertyUser=사용자 이름
profileFile_specifiedProfileNotFound=입력 파일에 지정된 프로필({0})이 없습니다.
profileFile_statusDone=완료되었습니다.
profileFile_statusIteratingProfiles=입력 파일에서 찾은 {0}개의 프로필을 차례대로 실행하는 중...
profileFile_statusReadingFile=입력 파일({0})을 읽는 중...
profileFile_statusSavingFile=출력 파일({0})에서 변경한 속성 저장 중...
