#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
editorAppl_argKeyValue={0} Argumentwert: {1}
editorAppl_exitAppl=Die Anwendung {0} wurde beendet.
editorAppl_invalidFileName=Ungültiger Dateiname: ({0}).
editorAppl_invalidInputFile=Die Eingabedatei ({0}) ist nicht vorhanden oder kann nicht gelesen werden.
editorAppl_invalidOutputFile=Die Ausgabedatei ({0}) ist ungültig oder schreibgeschützt.
editorAppl_missingArgValue=Fehlender Wert für Argument {0}.
editorAppl_noProfileChanges=Verbindungsprofil(e) wurden nicht geändert.
editorAppl_overwriteExistingFile=Die Ausgabedatei ({0}) ist bereits vorhanden. Inhalte überschreiben?
editorAppl_promptEditProfileName=Geben Sie den Namen eines anzuzeigenden/zu ändernden Verbindungsprofils ein (optional).
editorAppl_promptInputFile=Geben Sie den Namen der anzuzeigenden/zu ändernden Verbindungsprofildatei ein.
editorAppl_promptOutputFile=Geben Sie den Namen der Ausgabedatei ein, um die Änderungen zu speichern.
editorAppl_startAppl=Anwendung {0} starten...
editorAppl_syntaxArguments=Optionale Befehlszeilenargumente:
editorAppl_syntaxCommand=Verwenden Sie den Befehl "eclipsec" unter Windows bzw. "eclipse" auf anderen Plattformen.
editorAppl_syntaxHelpInstruction=Zeigt diese Hilfemeldung an.
editorAppl_syntaxInArgInstruction=Gibt den Namen der anzuzeigenden/zu ändernden Verbindungsprofildatei an.
editorAppl_syntaxNullArgInstruction=Wenn kein Argumentwert angegeben ist, fragt der Editor einen Eingabewert ab.
editorAppl_syntaxOutArgInstruction=Gibt den Namen der Ausgabedatei an, um die Änderungen zu speichern.
editorAppl_syntaxProfileNameInstruction1=Gibt den Namen eines anzuzeigenden/zu ändernden Verbindungsprofils an. Wenn keines angegeben ist,
editorAppl_syntaxProfileNameInstruction2=durchläuft das Tool alle Profile in der Eingabedatei.
editorAppl_syntaxUsage=Befehlssyntax:
#
ioutil_askReviewStack=Möchten Sie den Ablaufverfolgungsstapel anzeigen?
ioutil_askUpdateValue=Vorhandenen Wert ändern?
ioutil_confirmUserInputChar=j
ioutil_confirmPromptInstruction=zur Bestätigung
ioutil_errorSystemInput=Fehler beim Lesen der Eingabekonsole.
ioutil_exceptionCause=Ausnahme wurde verursacht von: {0}
ioutil_newValuePrompt=Neuer Wert
#
profileFile_askEncryptOutput=Möchten Sie die Ausgabedatei verschlüsseln?
profileFile_askUpdateProfile=Profileigenschaften anzeigen oder ändern?
profileFile_errorInstruction=Mögliche weitere Ausnahmen finden Sie im Arbeitsplatzprotokoll.
profileFile_errorReadingFile=Fehler beim Lesen der Profileingabedatei.
profileFile_errorSavingFile=Fehler beim Speichern der geänderten Eigenschaften in der Ausgabedatei.
profileFile_inputPromptDelimiter=>> 
profileFile_noOdaPropertyDefn=Warnung: Keine Eigenschaftsdefinitionen verfügbar. Alle vorhandenen Eigenschaftswerte werden ausgeblendet.
profileFile_noProfileFound=Keine Profile in der Eingabedatei gefunden.
profileFile_profileIdentifier=Profilname {0}
profileFile_propertyDriverClass=JDBC-Treiberklasse
profileFile_propertyJarList=JAR-Pfade für JDBC-Treiber (''{0}'' als Pfadtrennzeichen verwenden)
profileFile_propertyPassword=Kennwort
profileFile_propertyUrl=Verbindungs-URL
profileFile_propertyUser=Benutzername
profileFile_specifiedProfileNotFound=Das angegebene Profil ({0}) wurde in der Eingabedatei nicht gefunden.
profileFile_statusDone=Fertig.
profileFile_statusIteratingProfiles=Alle {0} in der Eingabedatei gefundenen Profile werden durchlaufen...
profileFile_statusReadingFile=Eingabedatei ({0}) wird gelesen...
profileFile_statusSavingFile=Geänderte Eigenschaften werden in der Ausgabedatei ({0}) gespeichert...
