wizard.asa.multi.action = 创建多个 ASA 配置文件
profile.asa.content = Sybase ASA SQL Model Content Extension

asa9.driver.template = Sybase JDBC Driver for Sybase ASA 9.x
asa10.driver.template = Sybase JDBC Driver for Sybase ASA 10.x
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = Driver Class
driverVendor = Vendor
driverVersion = Version
driverDBName = Database Name
driverConnectionURL = Connection URL
driverUID = User ID
driverPWD = Password

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = Other Driver
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = Other Driver
