wizard.asa.multi.action = 複数の ASA プロファイルの作成
profile.asa.content = Sybase ASA SQL Model Content Extension

asa9.driver.template = Sybase JDBC Driver for Sybase ASA 9.x
asa10.driver.template = Sybase JDBC Driver for Sybase ASA 10.x
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
driverUID = ユーザ ID
driverPWD = パスワード

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = その他のドライバ

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
