wizard.asa.multi.action = 创建多个 ASA 配置文件
profile.asa.content = Sybase ASA SQL 模型内容扩展

asa9.driver.template = Sybase ASA 9.x 的 Sybase JDBC 驱动程序
asa10.driver.template = Sybase ASA 10.x 的 Sybase JDBC 驱动程序
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = 驱动程序类
driverVendor = 供应商
driverVersion = 版本
driverDBName = 数据库名称
driverConnectionURL = 连接 URL
driverUID = 用户 ID
driverPWD = 密码

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = 其他驱动程序
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = 其他驱动程序

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
