wizard.asa.multi.action = 여러 ASA 프로필 생성
profile.asa.content = Sybase ASA SQL 모델 콘텐츠 확장명

asa9.driver.template = Sybase ASA 9.x용 Sybase JDBC 드라이버
asa10.driver.template = Sybase ASA 10.x용 Sybase JDBC 드라이버
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase ASA(Adaptive Server Anywhere)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = 기타 드라이버

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
