wizard.asa.multi.action = Créer des profils ASA multiples
profile.asa.content = Extension de contenu du modèle Sybase ASA SQL

asa9.driver.template = Pilote JDBC Sybase pour Sybase ASA 9.x
asa10.driver.template = Pilote JDBC Sybase pour Sybase ASA 10.x
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = Classe de pilote
driverVendor = Vendeur
driverVersion = Version
driverDBName = Nom de la base de données
driverConnectionURL = URL de connexion
driverUID = ID utilisateur
driverPWD = Mot de passe

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = Autre pilote
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = Autre pilote

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
