wizard.asa.multi.action = Erstellen mehrerer ASA-Profile
profile.asa.content = Sybase ASA SQL-Modell - Content Extension

asa9.driver.template = Sybase JDBC-Treiber für Sybase ASA 9.x
asa10.driver.template = Sybase JDBC-Treiber für Sybase ASA 10.x
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = Treiberklasse
driverVendor = Anbieter
driverVersion = Version
driverDBName = Datenbankname
driverConnectionURL = Verbindungs-URL
driverUID = Benutzer-ID
driverPWD = Kennwort

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = Anderer Treiber
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = Anderer Treiber

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
