wizard.asa.multi.action = Crear varios perfiles ASA
profile.asa.content = Extensión de contenido del modelo SQL de Sybase ASA

asa9.driver.template = Controlador JDBC de Sybase para Sybase ASA 9.x
asa10.driver.template = Controlador JDBC de Sybase para Sybase ASA 10.x
asa.category = ASA

9.xProductString = Sybase Adaptive Server Anywhere (ASA)
10.xProductString = Sybase Adaptive Server Anywhere (ASA)
9.xVersionString = 9.x
10.xVersionString = 10.x

driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
driverUID = Identificador de usuario
driverPWD = Contraseña

org.eclipse.datatools.enablement.sybase.asa.9_x.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.sybase.asa.10_0.other.driverTemplate = Otro controlador

Plugin.name = Sybase ASA Plug-in
Plugin.providerName = Eclipse Data Tools Platform
