###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## Oracle Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = &SID:
CUI_NEWCW_HOST_LBL_UI_ = &Host:
CUI_NEWCW_PORT_LBL_UI_ = &Anschlussnummer:
CUI_NEWCW_USERNAME_LBL_UI_ = Benutzern&ame:
CUI_NEWCW_PASSWORD_LBL_UI_ = Kenn&wort:
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = &Kennwort speichern
CUI_NEWCW_CONNECTIONURL_LBL_UI_= Verbindungs-UR&L:
ALL_CATALOGS_OPTION_UI_ = Alles
DBA_CATALOG_OPTION_UI_ = DBA
USER_CATALOG_OPTION_UI_ = Benutzer
CATALOG_LBL_UI_ = Katalo&g:

CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = SID
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = Host:
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = Anschlussnummer
CUI_NEWCW_CATALOG_SUMMARY_DATA_TEXT_ = Katalog
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = Benutzername
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = Kennwort speichern
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = Wahr
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = Falsch
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = Geben Sie einen SID-Namen ein.
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= Geben Sie einen Hostnamen für den Datenbankserver ein.
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = Geben Sie die Anschlussnummer der Verbindung für den Datenbankserver ein.
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = Geben Sie einen Benutzernamen ein.
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = Geben Sie ein Kennwort ein.
