###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## Oracle Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = SID(&S):
CUI_NEWCW_HOST_LBL_UI_ = 主机(&H):
CUI_NEWCW_PORT_LBL_UI_ = 端口号(&M):
CUI_NEWCW_USERNAME_LBL_UI_ = 用户名(&A):
CUI_NEWCW_PASSWORD_LBL_UI_ = 密码(&W):
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = 保存密码(&V)
CUI_NEWCW_CONNECTIONURL_LBL_UI_= 连接 URL(&L):
ALL_CATALOGS_OPTION_UI_ = 全部
DBA_CATALOG_OPTION_UI_ = DBA
USER_CATALOG_OPTION_UI_ = 用户
CATALOG_LBL_UI_ = 目录(&G):

CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = SID
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = 主机
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = 端口号
CUI_NEWCW_CATALOG_SUMMARY_DATA_TEXT_ = 目录
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = 用户名
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = 保存密码
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = true
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = false
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = 输入 SID 名称。
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= 输入数据库服务器的主机名。
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = 输入数据库服务器的连接端口号。
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = 输入用户名。
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = 输入密码。
