# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2011 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *     Actuate Corporation - added messages
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = La vue {0} n'a aucune instruction SELECT
FE_TRIGGER_ACTION_EMPTY = L'action du déclencheur {0} est vide
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = La table/clé parent référencée par la clé étrangère {0} n'existe pas
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = La contrainte de référence {0} n'a aucune clé
FE_INDEX_HAS_NO_MEMBER = L'index {0} n'a aucun membre
FE_ELEMENT_HAS_NO_TYPE = L'élément saisi {0} n'a aucun type
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES=Valeur manquante pour les attributs requis de l'élément de configuration {0}.
# RDBCorePlugin
RDBCorePlugin_NO_DEFAULT_WORKSPACE=Unable to determine the default workspace location.  Check your OSGi-less platform configuration of the plugin or datatools workspace path.
