# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2009 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *		Actuate Corporation - added DEFN_MISSING_ATTRIBUTE_VALUES message
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = 视图 {0} 没有 SELECT 语句
FE_TRIGGER_ACTION_EMPTY = 触发器 {0} 操作为空
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = 外键 {0} 引用的父表/键不存在
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = 引用约束 ({0}) 没有任何键
FE_INDEX_HAS_NO_MEMBER = 索引 ({0}) 没有任何成员
FE_ELEMENT_HAS_NO_TYPE = 类型化元素 ({0}) 没有任何类型
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES={0} 配置元素的必需属性缺少值。

