# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2011 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *     Actuate Corporation - added messages
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = ビュー {0} に SELECT 文がありません。
FE_TRIGGER_ACTION_EMPTY = トリガ {0} のアクションが空です。
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = フォーリンキー {0} で参照する親テーブル/キーがありません。
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = 参照の制約 {0} にキーがありません。
FE_INDEX_HAS_NO_MEMBER = インデックス {0} にメンバがありません。
FE_ELEMENT_HAS_NO_TYPE = 入力した要素 {0} に型がありません。
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES={0} 設定項目に必要な属性に値が指定されていません。
# RDBCorePlugin
RDBCorePlugin_NO_DEFAULT_WORKSPACE=デフォルトのワークスペースの場所を特定できません。  プラグインまたはデータツールのワークスペースパスの OSGi レスプラットフォームの設定を確認してください。
