# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2011 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *     Actuate Corporation - added messages
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = 뷰 {0}에 SELECT 문이 없습니다.
FE_TRIGGER_ACTION_EMPTY = 트리거 {0} 작업이 비어 있습니다.
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = 외래 키 {0}에서 참조한 부모 테이블/키가 없습니다.
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = 참조 제약 조건 {0}에 키가 없습니다.
FE_INDEX_HAS_NO_MEMBER = 인덱스 {0}에 멤버가 없습니다.
FE_ELEMENT_HAS_NO_TYPE = 입력한 요소 {0}에 형식이 없습니다.
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES=구성 요소 {0}의 필수 특성 값이 없습니다.
# RDBCorePlugin
RDBCorePlugin_NO_DEFAULT_WORKSPACE=Unable to determine the default workspace location.  Check your OSGi-less platform configuration of the plugin or datatools workspace path.
