# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2011 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *     Actuate Corporation - added messages
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = La vista {0} no tiene ninguna sentencia SELECT
FE_TRIGGER_ACTION_EMPTY = A acción del activador {0} está vacía
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = La tabla/clave principal a la que hace referencia la clave externa {0} no existe
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = La restricción de referencia {0} no tiene ninguna clave
FE_INDEX_HAS_NO_MEMBER = El índice {0} no tiene ningún miembro
FE_ELEMENT_HAS_NO_TYPE = El elemento {0} introducido no tiene ningún tipo
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES=Falta el valor en los atributos necesarios del elemento de configuración {0}.
# RDBCorePlugin
RDBCorePlugin_NO_DEFAULT_WORKSPACE=No es posible determinar la ubicación predeterminada del área de trabajo.  Compruebe la configuración de la plataforma sin OSGi de la ruta del área de trabajo de las herramientas de datos o el complemento.
