# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
#/*******************************************************************************
# * Copyright (c) 2007, 2011 IBM Corporation and others.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# * 
# * Contributors:
# *     IBM Corporation - initial API and implementation
# *     Actuate Corporation - added messages
# *******************************************************************************/

#FE
FE_VIEW_HAS_NO_BODY = Die Ansicht {0} hat keine SELECT-Anweisung
FE_TRIGGER_ACTION_EMPTY = Die Triggeranweisung {0} ist leer
FE_PARENT_TABLLE_OR_KEY_DO_NOT_EXIST = Die Parent-Tabelle/der Parent-Key, die/der durch den Foreign-Key {0} referenziert wird, existiert nicht
FE_REFERENCE_CONSTAINT_HAS_NO_KEY = Die Reference-Einschränkung {0} hat keinen Schlüssel
FE_INDEX_HAS_NO_MEMBER = Der Index {0} hat kein Mitglied
FE_ELEMENT_HAS_NO_TYPE = Das eingegebene Element {0} hat keinen Typ
#DEFN
DEFN_MISSING_ATTRIBUTE_VALUES=Wert für erforderliches Attribut von Konfigurationselement {0} fehlt.
# RDBCorePlugin
RDBCorePlugin_NO_DEFAULT_WORKSPACE=Der standardmäßige Speicherort des Arbeitsplatzes kann nicht ermittelt werden.  Prüfen Sie die Konfiguration der Plattform ohne OSGi für den Plug-In- oder den Datentool-Arbeitsplatzpfad.
