###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## LUW Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = データベース(&S):
CUI_NEWCW_HOST_LBL_UI_ = ホスト(&H):
CUI_NEWCW_PORT_LBL_UI_ = ポート番号(&M):
CUI_NEWCW_CONNECTIONURL_LBL_UI_= 接続 URL(&L):
CUI_NEWCW_DEFDBNAME_VAL_UI_ = サンプル
CUI_NEWCW_CLIENTAUTHENTICATION_BTN_UI_ = クライアント認証を使用する(&I)
CUI_NEWCW_USERNAME_LBL_UI_ = ユーザ名:
CUI_NEWCW_PASSWORD_LBL_UI_ = パスワード:
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = パスワードの保存(&V)
CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = データベース
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = ホスト
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = ポート番号
CUI_NEWCW_USE_CLIENT_AUTHENICATION_SUMMARY_DATA_TEXT_ = クライアント認証を使用する
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = ユーザ名
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = パスワードの保存
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = true
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = false

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = データベース名を入力してください (例 : {0})。
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= データベースサーバのホスト名を入力してください。
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = データベースサーバの接続ポート番号を入力してください。
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = ユーザ名を入力してください。
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = パスワードを入力してください。



