<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="sybaseasasqlmodel"
    nsURI="http:///org/eclipse/datatools/connectivity/sqm/sybase/asa/sybaseasasqlmodel.ecore"
    nsPrefix="SybaseASAModel">
  <eClassifiers xsi:type="ecore:EClass" name="SybaseASADatabase" eSuperTypes="sybaseasabasesqlmodel.ecore#//SybaseASABaseDatabase">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ASECompatible" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SybaseASATable" eSuperTypes="sybaseasabasesqlmodel.ecore#//SybaseASABaseTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pctfree" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="-1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="value = -1 means no pctfree has been set"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SybaseASAForeignKey" eSuperTypes="sybaseasabasesqlmodel.ecore#//SybaseASABaseForeignKey">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="checkOnCommit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nullable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SybaseASAIndex" eSuperTypes="sybaseasabasesqlmodel.ecore#//SybaseASABaseIndex">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="virtual" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SybaseASATempTable" eSuperTypes="sybaseasabasesqlmodel.ecore#//SybaseASABaseTempTable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pctfree" eType="ecore:EDataType platform:/plugin/org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="-1"/>
  </eClassifiers>
</ecore:EPackage>
