ExplainSQLActionDelegate.action_title=&Obtenir le plan d'exécution
ExplainSQLActionDelegate.action_tooltip=Expliquer le plan d'exécution SQL
GroupPlanSupportRunnable.continue_explain=Continuer l'explication
GroupPlanSupportRunnable.error_info=Une erreur s'est produite lors de l'explication de la/des dernière(s) instruction(s). Voulez-vous continuer ?
GroupPlanSupportRunnable.sql_execution_plan=Plan d'exécution SQL
GroupPlanSupportRunnable.groups=({0} groupes)
GroupPlanSupportRunnable.group=Groupe {0}
