ExplainSQLActionDelegate.action_title=&Obtener plan de ejecución
ExplainSQLActionDelegate.action_tooltip=Explicar plan de ejecución SQL
GroupPlanSupportRunnable.continue_explain=Continuar explicación
GroupPlanSupportRunnable.error_info=Se ha producido un error al explicar la(s) última(s) sentencia(s). ¿Desea continuar?
GroupPlanSupportRunnable.sql_execution_plan=Plan de ejecución SQL
GroupPlanSupportRunnable.groups=({0} grupos)
GroupPlanSupportRunnable.group=Grupo {0}
