ExplainSQLActionDelegate.action_title=Ausführungs&plan abrufen
ExplainSQLActionDelegate.action_tooltip=SQL-Ausführungsplan erläutern
GroupPlanSupportRunnable.continue_explain=Erläuterung fortsetzen
GroupPlanSupportRunnable.error_info=Fehler beim Erläutern der letzten Anweisung(en). Möchten Sie fortfahren?
GroupPlanSupportRunnable.sql_execution_plan=SQL-Ausführungsplan
GroupPlanSupportRunnable.groups=({0} Gruppen)
GroupPlanSupportRunnable.group=Gruppe {0}
