# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Copyright (c) 2002, 2007. All Rights Reserved IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which is available at
# http://www.eclipse.org/legal/epl-v10.html
#  
# Contributors:
#     IBM Corporation - initial API and implementation
#
# Properties file for component:  SQLQ - SQL builder

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

!
! views/update/RemoveUpdateColumnAction.java
!
_UI_ACTION_REMOVE_UPDATE_COLUMN = &Spalte entfernen

!
! views/update/UpdateTreeElement.java
!
_UI_COLUMN_UPDATE_GROUP = Gruppe aktualisieren

!
! views/update/UpdateTreeViewer.java
!
_UI_COLUMN_UPDATE_COLUMN     = Spalte aktualisieren
_UI_COLUMN_UPDATE_EXPRESSION = Ausdruck

!
!views/update/UpdateViewer.java
!
_UI_WORKBOOK_SET    = Einstellen
_UI_WORKBOOK_WHERE  = Wo


!
! Actions
!
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_ACTION_ADD_TABLE          = Tabelle &hinzufügen...
_UI_ACTION_ADD_TABLE_REPLACE  = Tabelle &ersetzen...
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" in the following line
_UI_ACTION_ADD_FULLSELECT     = &FULLSELECT-Anweisung hinzufügen
_UI_ACTION_REMOVE_TABLE       = Tabelle ent&fernen...

!actions/ChangeStatementTypeAction
_UI_ACTION_CHANGE_STATEMENT_TYPE		= Anweisungstyp än&dern...

!actions/OmitCurrentSchemaAction
_UI_ACTION_OMIT_CURRENT_SCHEMA		= Aktuelles Schema a&uslassen...

!actions/AddValueRowAction
_UI_ACTION_ADD_VALUE_ROW=Werte&zeile hinzufügen

!actions/AddValuesAction.java
_UI_ACTION_ADD_VALUES=Werte &hinzufügen

!actions/AddSubSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following line
_UI_ACTION_ADD_SELECT=&SELECT-Anweisung hinzufügen

!actions/CreateWithTableAction.java
_UI_ACTION_ADD_COMMON_TABLE=&Gemeinsamen Tabellenausdruck (WITH) hinzufügen

!actions/DeleteStatementAction.java
_UI_ACTION_DELETE_STATEMENT=&Löschen...

!expressionbuilder/actions/DeleteExpressionAction.java
_UI_ACTION_DELETE_EXPRESSION=Ausdruck ent&fernen

!expressionbuilder/actions/DeleteCaseClauseAction.java
_UI_ACTION_DELETE_CLAUSE=Klausel ent&fernen

!expressionbuilder/actions/DeleteFunctionParameterAction.java
_UI_ACTION_DELETE_PARAMETER=Parameter ent&fernen

!expressionbuilder/case/CastExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_WIZARD_CAST_EXPRESSION_TITLE=CAST-Ausdruckserstellung

!expressionbuilder/caseexpr/CaseSimplePage.java
_UI_COMBO_ADDFUNCTION=Funktionsausdruck erstellen...

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_COMBO_ADDCASE=CASE-Ausdruck erstellen...
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_COMBO_ADDCAST=CAST-Ausdruck erstellen...
_UI_COMBO_ADDCONSTANT=Konstanten Ausdruck erstellen...
_UI_COMBO_SELECTSUBQUERY=Teilabfrage auswählen...
_UI_COMBO_ADDEXPRBYOPERATOR=Ausdruck mit Operatoren erstellen...
_UI_WIZARD_CASE_SIMPLE_TITLE=Einfacher CASE-Ausdruck
_UI_WIZARD_CASE_SIMPLE_HEADING=Einfachen CASE-Ausdruck erstellen
!! NOTE TO TRANSLATOR: Do not translate "WHEN-THEN" and "ELSE" in the following line
_UI_LABEL_BUILD_WHEN_CLAUSE=WHEN-THEN-Klauseln er&stellen, ELSE-Klausel hinzufügen oder beides.
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_CHECKBOX_ADD_ELSE=&ELSE-Klausel hinzufügen
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_BUTTON_ADD_WHEN=&WHEN-Klausel hinzufügen
_UI_LABEL_EXPRESSION_PREVIEW=Vorschau von CASE-Ausdruck:

!expressionbuilder/function/FunctionBuilderPage.java:

!expressionbuilder/caseexpr/CaseSearchTable.java
_UI_COLUMN_CASE_SEARCH_EXPRESSION=Ausdruck
_UI_COLUMN_CASE_SEARCH_OPERATOR=Operator
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE_SEARCH=WHEN-Klausel ent&fernen
_UI_ACTION_DELETE_SEARCH_CONDITION=Suchbedingung ent&fernen
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION_SEARCH=ELSE-Ausdruck ent&fernen

!expressionbuilder/caseexpr/CaseSearchPage.java
_UI_WIZARD_CASE_SEARCH_HEADING=Gesuchter CASE-Ausdruck
_UI_WIZARD_CASE_SEARCH_EXPR=Gesuchten CASE-Ausdruck erstellen

!expressionbuilder/caseexpr/CaseSimpleTable.java
_UI_COLUMN_CASE_EXPRESSION=Ausdruck
_UI_COLUMN_RESULT_EXPRESSION=Ergebnisausdruck
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE=WHEN-Klausel ent&fernen
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION=ELSE-Ausdruck ent&fernen

!expressionbuilder/...Signatures...
_UI_FCN_ALL=Alles
_UI_FCN_COLUMN=Spalte
_UI_FCN_SPECIAL_REG=Spezielle Register
_UI_FCN_SCALAR=Skalar
_UI_FCN_CONVERSION=Konvertierung
_UI_FCN_SECURITY=Wertpapier
_UI_FCN_DATE_TIME=Datum und Uhrzeit
_UI_FCN_DATE=Datum
_UI_FCN_DB2=DB2
_UI_FCN_LOGICAL=Logisch
_UI_FCN_MATH=Mathematisch
_UI_FCN_BIT=Bit
_UI_FCN_NUMBER=Nummer
_UI_FCN_CHARACTER=Zeichen
_UI_FCN_SUMMARY=Zusammenfassung
_UI_FCN_TEXT=Text
_UI_FCN_SYSTEM=System
_UI_FCN_STRING=Zeichenfolge
_UI_FCN_AGGREGATE=Aggregat
_UI_FCN_MISCELLANEOUS_SINGLE_ROW=Sonstige einzelne Zeile
_UI_FCN_MISCELLANEOUS=Verschiedenes
_UI_FCN_OBJECT_REFERENCE=Objektreferenz
_UI_FCN_CONTROL_FLOW=Steuerfluss
_UI_FCN_TEXT_EXTENDERS=Texterweiterung
_UI_FCN_AIV_EXTENDERS=Audio/Bild/Video-Erweiterungen
_UI_FCN_XMLFUNCTIONS=XML
_UI_FCN_NOT_SUPPORTED=NICHT UNTERSTÜTZT
_UI_FCN_UDF=Benutzerdefinierte Funktionen (UDF)
_UI_FCN_DATALINK=Datalink
_UI_FCN_MQ_EXTENDER=Meldungswarteschlange (MQ)

!expressionbuilder/subquery/SubQueryWizard.java
_UI_WINDOW_TITLE_CHOICES=Optionen für Teilabfrage

!expressionbuilder/function/FunctionBuilderPage.java
_UI_WIZARD_FUNCTION_BUILDER_HEADING=Funktionserstellung
_UI_WIZARD_FUNCTION_BUILDER_EXPL=Erstellen Sie anhand dieser Seite einen Funktionsausdruck.
_UI_WIZARD_FUNCTION_BUILDER_INSTR_CAT=1. Funktions&kategorie auswählen:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_FCN=2. F&unktion auswählen:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_SIG=3. Funktions&signatur auswählen:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_EXPR=4. &Ausdruck für die Argumente auswählen:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_PRE=5. Vorschau des Funktionsausdrucks:

!expressionbuilder/caseexpr/CaseExpressionDialog.java

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following 2 lines
_UI_WIZARD_CASE_OPTION_HEADING=CASE-Optionen
_UI_WIZARD_CASE_OPTION_EXPL=Wählen Sie den Typ des zu erstellenden CASE-Ausdrucks aus.

_UI_GROUP_CASE_TYPE=CASE-Typ
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SEARCHED_WHEN=Ge&suchte WHEN-Klausel

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SEARCHED_WHEN = zum Beispiel CASE WHEN i>j THEN k END

!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SIMPLE_WHEN=E&infache WHEN-Klausel

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SIMPLE_WHEN = zum Beispiel CASE i WHEN 8 THEN j END

!expressionbuilder/caseexpr/CaseExpressionDialog.java
!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_WIZARD_CASE_EXPRESSION_TITLE=CASE-Ausdruckserstellung

!expressionbuilder/constant/ConstantExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_NUMERIC_CONSTANT=0123456789-+E.

!expressionbuilder/case/CaseBuilderPage.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" where it occurs in the following 6 lines
_UI_WIZARD_CAST_BUILDER_TITLE=CAST-Erstellung
_UI_WIZARD_CAST_BUILDER_HEADING=Erstellen Sie anhand dieser Seite einen CAST-Ausdruck.
!! NOTE TO TRANSLATOR: Do not translate "SCOPE" in the following line
_UI_LABEL_PREVIEW_CAST_EXPRESSION=Vorschau des CAST-Ausdrucks:
_UI_LABEL_DATATYPE_LENGTH=Länge des Datentyps:

!expressionbuilder/constant/ConstantExpressionDialog.java
_UI_WIZARD_CONSTANT_TITLE=Erstellung eines konstanten Ausdrucks

!expressionbuilder/constant/NumericConstantBuilderPage.java
_UI_WIZARD_NUMERIC_CONSTANT_TITLE=Erstellung einer numerischen Konstante
_UI_WIZARD_NUMERIC_CONSTANT_HEADER=Erstellung einer numerischen Konstante
_UI_WIZARD_NUMERIC_CONSTANT_EXPL=Erstellen Sie anhand dieser Seite einen numerischen Konstantenausdruck.
_UI_BUTTON_CLEAR=&Entf

!! NOTE TO TRANSLATOR: Do not translate the following 2 lines
_UI_BUTTON_FLOAT_TO_EXP=&F <-> E
_UI_BUTTON_PLUS_MINUS=+&/-

!expressionbuilder/constant/ConstantOptions.java
_UI_WIZARD_CONSTANT_OPTIONS_TITLE=Konstantenoptionen
_UI_WIZARD_CONSTANT_OPTIONS_HEADING=Konstantenoptionen
_UI_WIZARD_CONSTANT_OPTIONS_EXPL=Wählen Sie den Typ des zu erstellenden Konstantenausdrucks aus.
_UI_GROUP_CONSTANT_TYPE=Konstantentyp
_UI_RADIO_NUMERIC=N&umerische Konstante: Ganzzahl, Gleitkommazahl oder Dezimalwert
_UI_RADIO_STRING=&Zeichenkonstante: Zeichen oder grafische Zeichenfolge, Hexadezimalwert oder Hostvariablennamen

!expressionbuilder/constant/StringConstantBuilderPage.java
_UI_WIZARD_STRING_CONSTANT_TITLE=Erstellung einer Zeichenfolgenkonstante
_UI_WIZARD_STRING_CONSTANT_HEADING=Erstellung einer Zeichenfolgenkonstante
_UI_WIZARD_STRING_CONSTANT_EXPL=Erstellen Sie anhand dieser Seite einen Zeichenfolgenkonstantenausdruck. Geben Sie den Ausdruck in das Textfeld ein.
_UI_GROUP_STRING_TYPE=Typ der Zeichenfolgenkonstante
_UI_RADIO_CHARACTER=&Zeichenfolgenkonstante
_UI_RADIO_HEX=&Hexadezimalkonstante
_UI_RADIO_HOST_VARIABLE_NAME=Host&variablenname
_UI_RADIO_GRAPHIC=&Grafische Zeichenfolgenkonstante
_UI_LABEL_PREVIEW_CONSTANT_EXPRESSION=Vorschau des Konstantenausdrucks:

!expressionbuilder/function/FunctionExpressionDialog.java
_UI_WIZARD_FUNCTION_EXPRESSION_TITLE=Erstellung eines Funktionsausdrucks

!ExpressionBuilder/MainExpressionPage.java
_UI_WIZARD_MAIN_EXPRESSION_TITLE=Ausdruckserstellung
_UI_WIZARD_MAIN_EXPRESSION_HEADING=Ausdruckstypen
_UI_WIZARD_MAIN_EXPRESSION_EXPL=Wählen Sie den Typ des zu erstellenden Ausdrucks aus.
_UI_RADIO_FUNCTION=&Funktion

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_RADIO_CASE=&CASE - gesucht oder einfach

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_RADIO_CAST=C&AST

_UI_RADIO_CONSTANT=K&onstante - numerisch, Zeichenfolge oder Hostvariable
_UI_RADIO_SUBQUERY=&Teilabfrage
_UI_RADIO_OPERATORS=A&usdrücke mit Operatoren erstellen
_UI_COLUMN_EXPRESSION=Ausdruck
_UI_COLUMN_OPERATOR=Operator
_UI_COLUMN_PARAMETER=Parameter
_UI_COLUMN_VALUE=Wert

!expressionbuilder/multiexpr/ExpressionsByOperatorsWizard.java
_UI_WIZARD_EXPRESSION_BY_OPERATOR_TITLE=Ausdrücke mit Operatoren erstellen
_UI_WIZARD_EXPRESSION_BY_OPERATOR_HEADING=Ausdrücke mit Operatoren
_UI_WIZARD_EXPRESSION_BY_OPERATOR_EXPL=Erstellen Sie größere Ausdrücke anhand der bereitgestellten Operatoren.
_UI_LABEL_BUILD_LEFT_OP_RIGHT=Ausdrücke auf der linken Seite er&stellen und Operatoren auf der rechten Seite auswählen:
_UI_LABEL_PREVIEW_EXPRESSION=Vorschau des Ausdrucks:

!expressionbuilder/subquery/SubQueryPage.java
_UI_WIZARD_SUBQUERY_HEADING=Teilabfrage
_UI_WIZARD_SUBQUERY_EXPL=Teilabfrage auswählen.
_UI_LABEL_CHOICES=Verfügbare Auswahlen:
_UI_RADIO_EXISTING_STATEMENTS=Teilabfrage auf Grundlage einer &bestehenden Abfrage erstellen
_UI_RADIO_SCRATCH_SELECT=&Original-Teilabfrage erstellen
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following 2 lines
_UI_LABEL_EXISTING_SELECT=SELECT-Anweisung e&rstellen oder bearbeiten:
_UI_LABEL_NEW_SELECT_INFO=Geben Sie eine SELECT&-Anweisung ein. Sie können eine virtuelle Tabelle angeben.

!views/CustomSashForm.java
_UI_TOOLTIP_RESTORE_PANE=Teilfenster wiederherstellen
_UI_TOOLTIP_HIDE_PANE=Teilfenster ausblenden


!preferences/SQLBuilderPreferencePage.java
_UI_PREFERENCES_OMIT_SCHEMA_DESC=Standardwerte für die mit SQL-Anweisungen verknüpften Einstellungen für 'Aktuelles Schema auslassen'
_UI_PREFERENCES_OMIT_SCHEMA_IN_SQL=Aktuelles Schema in generierten SQL-Anweisungen a&uslassen
_UI_PREFERENCES_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Aktuelles Schema
_UI_PREFERENCES_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=&Autorisierungs-ID
_UI_PREFERENCES_OMIT_SCHEMA_SCHEMA_NAME=&Schemaname:

!dialogs/ChangeStatementTypeDialog
_UI_DIALOG_CHANGE_STATEMENT_TYPE_TITLE=SQL-Anweisungstyp ändern
_UI_DIALOG_CHANGE_STATEMENT_TYPE_NOTE=Beim Ändern des SQL-Anweisungstyps wird die aktuelle Anweisung durch eine neue leere Anweisung ersetzt.
_UI_DIALOG_CHANGE_STATEMENT_TYPE_GROUP_TITLE=Anweisungstyp

!dialogs/OmitCurrentSchemaDialog
_UI_DIALOG_OMIT_SCHEMA_TITLE=Aktuelles Schema auslassen
_UI_DIALOG_OMIT_SCHEMA_IN_SQL=Aktuelles Schema in generierten SQL-Anweisungen a&uslassen
_UI_DIALOG_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Aktuelles Schema
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_USER_AS_CURRENT_SCHEMA=&Autorisierungs-ID <{0}>
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=&Autorisierungs-ID
_UI_DIALOG_OMIT_SCHEMA_SCHEMA_NAME=&Schemaname:

!views/execute/ParameterWizards.java
_UI_WIZARD_SPECIFY_VARIABLE_VALUES_TITLE=Variablenwerte angeben

!views/execute/ParameterWizardDialog.java
_UI_WIZARD_PARAMETER_MARKERS_TITLE=Parametermarkierungen

!views/execute/ParameterMarkerPage.java
_UI_WIZARD_PARAMETER_MARKER_TITLE=Variablen ersetzen
_UI_WIZARD_PARAMETER_MARKER_HEADING=Hostvariablenwerte
_UI_WIZARD_PARAMETER_MARKER_EXPL=Die zu verwendenden Variablenwerte angeben

!views/execute/ParameterTableViewer.java
_UI_COLUMN_MARKER_NAME=Name
_UI_COLUMN_TYPE=Typ
_UI_COLUMN_PARAMETER_VALUE=Wert


!views/AddTableDialog.java
_UI_LABEL_TABLE_NAME            = Tabellen&name:
_UI_DIALOG_REPLACE_TABLE_TITLE  = Tabelle ersetzen
_UI_DIALOG_ADD_TABLE_TITLE      = Tabelle hinzufügen
_UI_LABEL_TABLE_ALIAS           = Tabellen&alias:
_UI_DIALOG_TABLE_ALREADY_ADDED  = Tabelle wurde bereits hinzugefügt - Alias angeben
_UI_DIALOG_ADD_VIEW_TO_SELF     = Ansicht kann nicht zu eigener Definition hinzugefügt werden.


!views/GridViewer.java
_UI_COLUMN_DEFAULT_COLUMN=Spalte

!views/insert/InsertGridViewer.java
_UI_COLUMN_INSERT_VALUE=Wert

!views/criteria/CriteriaGridViewer.java
_UI_COLUMN_COLUMN=Spalte
_UI_COLUMN_CRITERIA_OPERATOR=Operator
_UI_COLUMN_CRITERIA_VALUE=Wert

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_COLUMN_CRTIERIA_AND_OR=AND/OR

!views/criteria/CriteriaValueExpression.java
_UI_ACTION_UPDATE_VALUE_EXPRESSON=Wertausdruck akt&ualisieren
_UI_ACTION_REMOVE_CONDITION=Bedingung &entfernen
_UI_MENU_EXECUTE= SQL &ausführen

!views/fullselect/FullSelectViewer.java
!! NOTE TO TRANSLATOR: Do not translate VALUES in the following entry, since it is a SQL keyword
_UI_LABEL_FULL_SELECT_VALUES_HELP=Zum Hinzufügen einer Wertezeile klicken Sie mit der rechten Maustaste in der Gliederungsansicht auf VALUES.

!views/fullselect/ValuesRowViewer.java
_UI_COLUMN_VALUES_ROW_ITEM=Wertezeilenelement
_UI_ACTION_REMOVE_VALUES_ROW=Element entfe&rnen

!views/fullselect/FullSelectGridViewer.java
_UI_COLUMN_STATEMENT=Anweisung
_UI_COLUMN_FULL_SELECT_OPERATOR=Operator

!views/graph/editparts/TableEditPart.java
_UI_ACTION_UPDATE_ALIAS=Alias akt&ualisieren...
_UI_DIALOG_CHANGE_ALIAS_TITLE=Tabellenalias ändern
_UI_DIALOG_CHANGE_ALIAS_TEXT=N&euer Alias:
_UI_ACTION_CREATE_JOIN=&Knotenpunkt erstellen...
_UI_ACTION_REMOVE_TABLE_EDIT=Tabelle ent&fernen


!views/graph/GraphContextMenuProvider.java:
_UI_ACTION_REMOVE_JOIN=&Knotenpunkt entfernen

!views/graph/SourceTargetDialog.java
_UI_DIALOG_SOURCE_AND_TARGET_TITLE=Knotenpunkt erstellen
_UI_DIALOG_SOURCE_AND_TARGET_TEXT=Wählen Sie die Quell- und Zielspalten für den Knotenpunkt aus.
_UI_LABEL_JOIN_SRCCOL_TYPE = Quellspaltentyp:
_UI_LABEL_JOIN_TGTCOL_TYPE = Zielspaltentyp:

_UI_GROUP_SOURCE=Quelle
_UI_LABEL_TABLE=&Tabelle (Alias)
_UI_LABEL_COLUMN=&Spalte
_UI_GROUP_TARGET=Ziel
_UI_LABEL_TARGET_TABLE=T&abelle (Alias)
_UI_LABEL_TARGET_COLUMN=Sp&alte

_UI_GRAPH_PROMPT = Klicken Sie zum Hinzufügen einer Spalte mit der rechten Maustaste in diesem Teilfenster, und verwenden Sie das Kontextmenü.
_UI_GRAPH_PARSE_FAILED = Diese SQL-Syntax ist entweder ungültig oder wird derzeit nicht unterstützt. \
Sie können den SQL-Code manuell eingeben. Einige SQL-Erstellungsfunktionen wurden deaktiviert. \
Zum Aktivieren dieser Funktionen ändern Sie die Syntax.\n\nUm kürzliche Änderungen zu widerrufen, \
wählen Sie 'Zur letzten korrekten Quelle zurückkehren' aus dem SQL-Menü.
_UI_GRAPH_NO_TABLE_FOUND = Tabelle {0} wurde nicht gefunden. Möglicherweise existiert sie nicht, oder sie wurde ausgefiltert. \
Einige SQL-Erstellungsfunktionen wurden deaktiviert. \
Zum Aktivieren dieser Funktionen ändern Sie die Syntax, und speichern Sie die Anweisung.\n\nUm kürzliche Änderungen zu widerrufen, \
wählen Sie 'Zur letzten korrekten Quelle zurückkehren' aus dem SQL-Menü.
_UI_GRAPH_NO_COLUMN_FOUND = Spalte {0} wurde nicht gefunden. Einige SQL-Erstellungsfunktionen wurden deaktiviert. \
Zum Aktivieren dieser Funktionen ändern Sie die Syntax, und speichern Sie die Anweisung.\n\nUm kürzliche Änderungen zu widerrufen, \
wählen Sie 'Zur letzten korrekten Quelle zurückkehren' aus dem SQL-Menü.

!views/inster/InsertTypeViewer.java
_UI_GROUP_INSERT_ROWS=Zeilen einfügen von:
_UI_RADIO_VALUES=Werte
_UI_RADIO_INSERT_FROM_SUBQUERY=Teilabfrage
_UI_ACTION_REMOVE_COLUMN=&Spalte entfernen

!views/insert/InsertSelectViewer.java
_UI_LABEL_QUERY_NAME=Abfragename:

!views/select/GroupByContentViewer.java
_UI_LABEL_GROUPS_TYPE=Typ:
_UI_COMBOBOXITEM_GROUPING_ROOT=Gruppierungsstamm
_UI_ACTION_REMOVE=&Entfernen
_UI_NONE=Ohne
_UI_SIMPLE=Einfach

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_CUBE=CUBE

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_ROLLUP=ROLLUP

_UI_GROUPING=Gruppieren
_UI_GROUPINGSETS=Gruppierungssätze

! views/select/SelectGridViewer.java:
!
_UI_COMBO_SORT_UNSORTED   = Nicht sortiert
_UI_COMBO_SORT_ASCENDING  = Aufsteigend
_UI_COMBO_SORT_DESCENDING = Absteigend
_UI_COMBO_SORT_DEFAULT = Standard

!
!views/select/RemoveSelectColumnsAction.java
!
_UI_ACTION_REMOVE_SELECT_COLUMN = &Spaltenausdruck entfernen

!
!views/select/RemoveOrderByExpressionAction.java
!
_UI_ACTION_REMOVE_ORDER_BY_EXPRESSION = &Reihenfolge nach Ausdruck entfernen

!
! views/select/SelectGridViewer.java
!
_UI_COLUMN_SELECT_ALIAS      = Alias
_UI_COLUMN_SELECT_OUTPUT     = Ausgabe
_UI_COLUMN_SELECT_SORT_TYPE  = Sortiertyp
_UI_COLUMN_SELECT_SORT_ORDER = Sortierreihenfolge

!
! views/select/SelectViewer.java
!
_UI_WORKBOOKPAGE_COLUMNS          = Spalten
_UI_WORKBOOKPAGE_CONDITIONS       = Bedingungen
_UI_WORKBOOKPAGE_GROUPS           = Gruppen
_UI_WORKBOOKPAGE_GROUP_CONDITIONS = Gruppenbedingungen

!
! views/SQLBuilderActionBarContributor.java
!
_UI_TOOLTIP_EXECUTE_SQL = SQL-Anweisung ausführen
_UI_MENU_SQLBUILDER     = &SQL

!
! views/source/SQLSourceViewer.java & SQLSourceParser
!
!! NOTE TO TRANSLATOR: Do not translate the following four lines
_UI_INSERT                   = INSERT
_UI_UPDATE                   = UPDATE
_UI_DELETE                   = DELETE
_UI_SELECT                   = SELECT

_UI_PARSE_ERROR_ENCOUNTERED  = Analysefehler aufgetreten.


!
! views/StatementNameViewer.java
!
_UI_LABEL_STATEMENT = Anweisung:


!
! Join stuff - DefineJoinDialog.java, DefineJoinTypeDialog.java
!
_UI_DEFINE_JOIN_DIALOG_TITLE = Knotenpunkt angeben
_UI_DEFINE_JOIN_DIALOG_INSTR = Knotenpunktart
_UI_RADIO_INNER_JOIN         = &Innerer Knotenpunkt
_UI_RADIO_LEFT_OUTER_JOIN    = &Linker äußerer Knotenpunkt
_UI_RADIO_RIGHT_OUTER_JOIN   = &Rechter äußerer Knotenpunkt
_UI_RADIO_FULL_OUTER_JOIN    = &Voller äußerer Knotenpunkt
_UI_ACTION_SPECIFY_JOIN_TYPE = &Knotenpunkttyp angeben...
_UI_MSG_INVALID_JOIN_TITLE = Inkompatible Typen

!
!views/update/UpdateDesignViewer.java
!
_UI_TOOLTIP_UPDATE_ADD_COL = Einzelne Spalte zur Anweisung hinzufügen
_UI_TOOLTIP_UPDATE_ADD_GRP = Spalten zur Anweisung als Gruppe hinzufügen

!
!views/with/WithTableViewer.java
!
_UI_GROUP_WITH_TABLE     = Tabelle
_UI_GROUP_WITH_COLUMN    = Spalte
_UI_BUTTON_ADD_RIGHT     = Hinzufügen>>
_UI_BUTTON_REMOVE_LEFT   = << Entfernen

!
! views/with/WithStatementViewer
!
_UI_LABEL_WITH_STATEMENT  = Anweisungenname:

! CreateWithTableAction.java

!! NOTE TO TRANSLATOR: Do not translate "WithTable%1" in the following line
_UI_WITH_TABLE_NAME		  = WithTable%1
!
! SQLPreferencePage.java
!
_UI_VALIDATE_PREFERENCE_LABEL = Abfrageanweisungen &validieren, indem sie vor dem Ausführen gespeichert werden
_UI_ERROR_VALUE_GREATER_THAN_0 = Dieser Wert muss eine Ganzzahl über Null sein.

!
!views/SQLBuilder.java
!
_UI_VALIDATE_FAILED_TITLE    = Validierung fehlgeschlagen.
_UI_CONTINUE_WITH_SAVE       = Mit Speichern fortfahren?
_UI_VALIDATING_STATEMENT     = Anweisung wird validiert...
_UI_OBTAINING_CONNECTION     = Verbindung wird aufgerufen...
_UI_VALIDATE_DONE            = Validierung abgeschlossen...
_UI_SAVING_STATEMENT         = Anweisung wird gespeichert...

!model/SQLBuilderConstants.java:
_UI_BUILD_EXPRESSION   = Ausdruckserstellung...
_UI_EDIT_EXPRESSION    = Ausdruck bearbeiten...
_UI_REPLACE_EXPRESSION = Ausdruck ersetzen...
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_ADD_SELECT         = SELECT-Anweisung hinzufügen...
_UI_ADD_FULLSELECT     = FULLSELECT-Anweisung hinzufügen...
_UI_ADD_WITH           = WITH-Anweisung hinzufügen...
_UI_ADD_VALUES         = Werte hinzufügen
_UI_SPECIFY_VALUE	   = Wert angeben...
_UI_SPECIFY_VALUE_TITLE	   = Wert angeben


!========================================================================================
!
! Here is the list of Warning string that have message IDs - make sure they are unique
!
!========================================================================================
_WARN_MESSAGES_ENCOUNTERED      = Warnmeldungen ausgegeben.
_WARN_DATA_WAS_TRUNCATED        = Daten wurden abgeschnitten.
_WARN_SQL_WARNINGS_FOUND        = SQL-Warnungen vorgefunden.

_WARN_BAD_JOIN_1                = Knotenpunkttypen sind nicht kompatibel.
_WARN_INVALID_JOIN              = Ungültiger Knotenpunkt
_WARN_COLUMN_USED               = Spalte wurde bereits in einem Knotenpunkt zwischen Tabellen verwendet.

! Usage:
!   {0} replaced with the column name and {1} replaced with the column datatype
!
_WARN_BAD_JOIN_TYPES               = Der Typ der Spalte {0} ist {1}


!======================================================================================
!
! Here is the list of Error string that have message IDs - make sure they are unique
!
!======================================================================================

_ERROR_DIALOG_TITLE_EXPR_EDIT_FAILED = Bearbeiten des Ausdrucks fehlgeschlagen
_ERROR_DIALOG_MSG_REBUILD_EXPR       = Der Ausdruck muss neu erstellt werden.

_ERROR_TABLE_USED                    = Wählen Sie eine eindeutige Tabelle aus, oder geben Sie einen Alias ein.
_ERROR_ALIAS_USED                    = Geben Sie einen eindeutigen Alias ein.

_ERROR_ALIAS_NOT_UNIQUE_TEXT         = Alias ist nicht eindeutig.


_EXC_OPEN_SQL_FILE_RESOURCE          = Fehler beim Öffnen der Eingabe-SQL-Dateiressource
_EXC_OPEN_SQL_FILE_NOT_CONNECTED     = Sie müssen mit der Datenbank "{0}" verbunden sein, bevor Sie die SQL-Datei in der SQL-Abfrageerstellung öffnen.

!! NOTE TO TRANSLATOR: Do not translate "ISQLBuilderEditorInput" in the following line
_EXC_INPUT_NOT_ISQLBUILDEREDITORINPUT = Eingabe ist kein ISQLBuilderEditorInput.

_ERROR_ALIAS_NOT_ALPHANUMERIC        = Alias muss ausschließlich alphanumerische Zeichen enthalten.
_ERROR_ALIAS_TABLE_USED              = Alias darf kein Datenbanktabellenname sein.
_ERROR_ENTER_ALIAS                   = Tabellenname wird verwendet. Geben Sie einen Alias ein.

_ERROR_DATABASE_NOT_AVAILABLE        = Es ist keine Datenbankverbindung verfügbar.
_ERROR_INPUT_NOT_RECOGNIZED          = Der Editor-Eingabetyp wird nicht unterstützt.
_ERROR_OPEN_SQL_STORAGE_RESOURCE     = Beim Öffnen der Eingabe-SQL-Speicherressource ist ein Fehler aufgetreten.
_ERROR_OPEN_SQL_STRING_RESOURCE      = Beim Öffnen der Eingabe ist ein Fehler aufgetreten.
_ERROR_OPEN_INPUT_PARSE_FAILED       = Der SQL-Code kann nicht analysiert werden, weil er entweder ungültig ist oder derzeit nicht unterstützt wird.
_QUESTION_TITLE_OPEN_INPUT_PARSE_FAILED    = Analysefehler bei der SQL-Abfrageerstellung
_QUESTION_MESSAGE_OPEN_INPUT_PARSE_FAILED    = In der SQL-Abfrageerstellung wird eine leere SQL-Anweisung erstellt.

!
!model/SQLDomainModel.java
!
!note we reuse messages from ErrorMessages.java in org.eclipse.ui.texteditor.ErrorMessages

Editor_error_save_title=Probleme beim Speichern
Editor_error_save_message=Speichervorgang konnte nicht abgeschlossen werden.
Editor_error_save_readonly=\n\nGrund:\nEs konnte nicht in eine schreibgeschützte Datei geschrieben werden:
Editor_error_save_failed=\n\nGrund:\nEs konnte nicht in die Datei geschrieben werden:

!Strings from B2BGUI properties file
_UI_ERROR_CREATING_FILE_TITLE = Fehler beim Erstellen von Datei
_UI_ERROR_CREATING_FILE_SHORT_DESC = Fehler beim Erstellen von Datei "{0}"
_UI_ERROR_CREATING_FILE_LONG_DESC = Beim Versuch, die Datei "{0}" zu erstellen, ist ein Fehler aufgetreten.
_UI_PARENT_FOLDER_IS_READ_ONLY = Das übergeordnete Verzeichnis "{0}" ist schreibgeschützt.
_UI_UNKNOWN_ERROR_WITH_HINT = Unbekannter Fehler. Stellen Sie sicher, dass in das übergeordnete Verzeichnis "{0}" geschrieben werden kann.
_UI_UNKNOWN_ERROR = Unbekannter Fehler. Stellen Sie sicher, dass in das übergeordnete Verzeichnis "{0}" geschrieben werden kann.
! TextViewerOperationAction
_UI_MENU_COPY         = &Kopieren
_UI_MENU_CUT          = Auss&chneiden
_UI_MENU_DELETE       = Löschen
_UI_MENU_PASTE        = &Einfügen
_UI_MENU_PREFIX       = Präfix
_UI_MENU_REDO         = Wiederholen
_UI_MENU_SELECT_ALL   = Alles markieren
_UI_MENU_SHIFT_LEFT   = Nach links
_UI_MENU_SHIFT_RIGHT  = Nach rechts
_UI_MENU_STRIP_PREFIX = Präfix weglassen
_UI_MENU_UNDO         = Rückgängig

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = SQL-Editor öffnen
datatools_sqlbuilder_sqleditor_title = &SQL-Editor

! SQL Query Builder
datatools_sqlbuilder_sqlbuilder_DML_error = Fehler
datatools_sqlbuilder_sqlbuilder_multipleDML = Die SQL-Erstellung kann nur verwendet werden zum Erstellen einer einzelnen \
SQL DML-Anweisung. Datei {0} enthält keine einzelne DML-Anweisung. Datei mit dem SQL-Editor öffnen?
datatools_sqlbuilder_sqlbuilder_multipleDML_VE = Visual Explain kann nur verwendet werden für eine einzelne \
SQL DML-Anweisung. Datei {0} enthält keine einzelne DML-Anweisung.
datatools_sqlbuilder_sqlbuilder_unsupport_VE = Visual Explain wird bei dieser Datenbankverbindung nicht unterstützt.
!Clear to Skeleton and Revert to Last Correct
_UI_CLEAR_TO_TEMPLATE 			     = In Vorlage löschen
_UI_REVERT_TO_LAST_CORRECT_SOURCE    = Zur letzten korrekten Quelle zurückkehren
_UI_LAST_CORRECT_SOURCE 			 = Letzte korrekte Quelle?
!Change Statement Type
_UI_CHANGE_STATEMENT_TYPE			= Anweisungstyp ändern...
!Omit Current Schema
_UI_OMIT_CURRENT_SCHEMA              = Aktuelles Schema auslassen... 

!
! views/execute/ExecuteViewer.java & views/execute/QueryOutputHelper.java
!
_UI_DIALOG_EXECUTE_SQL_TITLE = SQL-Anweisung ausführen
_UI_BUTTON_EXECUTE_CLOSE     = S&chließen
_UI_LABEL_SQL_STATEMENT      = &SQL-Anweisung:
_UI_BUTTON_EXECUTE           = &Ausführen
_UI_LABEL_QUERY_RESULTS      = Abfrageergebnisse:
_UI_MONITOR_EXECUTING_QUERY  = SQL-Anweisung wird ausgeführt...
_UI_LABEL_NO_CONNECTION      = Die Datenbankverbindung fehlte, oder das Schemamodell der relationalen Datenbank ist korrumpiert.
_UI_LABEL_NO_CONNECTION_FILE = Die Datenbankverbindung ist nicht verfügbar, weil die für die Verbindung notwendige xmi-Datei fehlt.

_UI_DIALOG_WARNING_TITLE       = Warnung
_UI_DIALOG_OP_FAILED_TITLE     = Vorgang fehlgeschlagen
_UI_LABEL_EXECUTION_SUCCESSFUL = Anweisung wurde erfolgreich ausgeführt, ergab jedoch keine anzuzeigenden Ergebnisse.
!! NOTE TO TRANSLATOR: the MAX_RECORD_EXCEEDED string should match
!! the strings for RECORD_RETURNED and RECORD_DISPLAYED.
_UI_MSG_MAX_RECORD_EXCEEDED    = Mehr als 1000 wurden zurückgegeben. 1000 Datensätze werden angezeigt.
_UI_MSG_RECORD_RETURNED        = Datensätze zurückgegeben.


! SQL Statement validation errors
! usage note: %1 will be replaced with a SQL statement name
_ERROR_STATEMENT_NAME_EXISTS         = Eine Anweisung mit dem Namen %1 ist bereits vorhanden.
_ERROR_INVALID_STATEMENT_NAME = Geben Sie einen gültigen Anweisungsnamen ein.
! usage note: %1 is replaced with the invalid character entered by the user
_ERROR_INVALID_CHAR_IN_STATEMENT_NAME = Der Anweisungsname darf das Zeichen %1 nicht enthalten.
_ERROR_STATEMENT_NAME_TOO_LONG = Der Anweisungsname darf 160 Zeichen nicht überschreiten.


! SelectDBTablePage resources
datatools_selectDBTablePage_statements = Anweisungen

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Neu....
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Neue SQL-Anweisung...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Neue Abfrageanweisung erstellen
datatools_sqlbuilder_sqlstatement_actions_openwith = Öffnen mit
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL-Abfrageerstellung
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL-Editor

!
! New SQL statement wizard, dialog, and page
!
datatools_sqlbuilder_newStatementWizard_title = Neue SQL-Anweisung
datatools_sqlbuilder_newStatementWizard_description = Erstellt eine SQL-Anweisung.
datatools_sqlbuilder_newStatementDialog_title = Neue SQL-Anweisung
datatools_sqlbuilder_newStatementPage_title = Anweisungstyp
datatools_sqlbuilder_newStatementPage_description = Wählen Sie den Vorlagentyp für diese Anweisung aus, und geben Sie ihm einen Namen.
datatools_sqlbuilder_newStatementPage_statementID = Anweisungskennung
datatools_sqlbuilder_newStatementPage_statementName = &Anweisungsname:
datatools_sqlbuilder_newStatementPage_statementType = Anweisungs&vorlage:
datatools_sqlbuilder_newStatementPage_editUsing = Bearbeiten mit
datatools_sqlbuilder_newStatementPage_sqlQueryBuilder = S&QL-Erstellung
datatools_sqlbuilder_newStatementPage_sqlEditor = SQL-&Editor
datatools_sqlbuilder_newStatementPage_sampleStatements = Beispielanweisungen
datatools_sqlbuilder_newStatementPage_none = Ohne
!
! Project selection page, for new SQL statement wizard
!
datatools_sqlbuilder_projectPage_title = Projekt auswählen
datatools_sqlbuilder_projectPage_description = Wählen Sie ein bestehendes Projekts aus, oder fügen Sie ein neues für diese Anweisung hinzu.

!
! Generated comment text for template SQL for New SQL Statement action
!
_UI_SAMPLE_DML_TEMPLATE_STATEMENTS = DML-Beispiel-Vorlagenanweisungen
_UI_SAMPLE_DDL_TEMPLATE_STATEMENTS = DDL-Beispiel-Vorlagenanweisungen

!
! String for the AddTable With Table
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_AVAILABLE_TABLES_TREE_PROVIDER = WITH-Tabellen

!actions/ConvertToFullSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" and "UNION" in the following line
_UI_ACTION_CONVERT_TO_FULL_SELECT=In FULLSELECT (UNION) &konvertieren


! org.eclipse.datatools.sqltools.sqlbuilder.views.fullselect/fullselectElement.java
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_VIEWS_FULLSELECTELEMENT_FULLSELECT = FULLSELECT-Anweisung
_UI_VIEWS_FULLSELECTELEMENT_SELECT = SELECT-Anweisung
_UI_VIEWS_FULLSELECTELEMENT_VALUES = VALUES

! org.eclipse.datatools.sqltools.sqlbuilder.views.graph/GraphContextMenuProvider.java
_UI_VIEWS_GRAPH_SELECT_ALL_COLUMN = Alle Spalten auswählen
_UI_VIEWS_GRAPH_DESELECT_ALL_COLUMN = Alle Spalten abwählen

!SQLQueryBuilder Dialog
_UI_SQLQUERYBUILDERDIALOG_NAME = SQL-Abfrageerstellung
SQLQueryBuilderDialogEditTabName=Bearbeiten
SQLQueryBuilderDialogNoInput=Es wurde keine zu öffnende Eingabe an den SQLBuilder-Dialog weitergeleitet.
SQLQueryBuilderDialogParseFailOnOpenAskUserTitle=SQL-Abfrageerstellung
SQLQueryBuilderDialogParseFailOnOpenAskUserMessage=Wenn Sie fortfahren, wird in der SQL-Abfrageerstellung eine leere SQL-Anweisung erstellt. Möchten Sie fortfahren?
SQLQueryBuilderDialogResultsTabName=SQL-Ergebnisse


# plugin.xml.  preference page extension point
_UI_SQLQUERY_NAME = SQL-Abfrage

## Resources for the standard editor actions

ContentAssistProposal_label       =Hilfe zum &Inhalt@Strg+Leerzeichen
ContentAssistProposal_tooltip     =Hilfe zum Inhalt
ContentAssistProposal_image       =
ContentAssistProposal_description =Hilfe zum Inhalt

ContentTip_label       =Tipp zum Inhalt@Strg+Umschalt+Leerzeichen
ContentTip_tooltip     =Tipp zum Inhalt
ContentTip_image       =
ContentTip_description =Tipp zum Inhalt

## Resources for other SQL Query Builder actions

datatools_sqlbuilder_RunSQLAction_label       = SQL &ausführen
datatools_sqlbuilder_RunSQLAction_tooltip     = SQL-Anweisung ausführen
datatools_sqlbuilder_RunSQLAction_image       =
datatools_sqlbuilder_RunSQLAction_description =

datatools_sqlbuilder_RevertToPreviousAction_label       = Zur letzten korrekten Quelle zurückkehren
datatools_sqlbuilder_RevertToPreviousAction_tooltip     =
datatools_sqlbuilder_RevertToPreviousAction_image       =
datatools_sqlbuilder_RevertToPreviousAction_description =

datatools_sqlbuilder_RevertToDefaultAction_label       = In Vorlage löschen
datatools_sqlbuilder_RevertToDefaultAction_tooltip     =
datatools_sqlbuilder_RevertToDefaultAction_image       =
datatools_sqlbuilder_RevertToDefaultAction_description =

datatools_sqlbuilder_ChangeStatementTypeAction_label   = Anweisungstyp ändern...
datatools_sqlbuilder_ChangeStatementTypeAction_tooltip     =
datatools_sqlbuilder_ChangeStatementTypeAction_image       =
datatools_sqlbuilder_ChangeStatementTypeAction_description =

datatools_sqlbuilder_OmitCurrentSchemaAction_label       = Aktuelles Schema auslassen...
datatools_sqlbuilder_OmitCurrentSchemaAction_tooltip     =
datatools_sqlbuilder_OmitCurrentSchemaAction_image       =
datatools_sqlbuilder_OmitCurrentSchemaAction_description =

!RDBTableDropListener
_UI_INVALID_TABLE_ADDED = Sie können nur dann Tabellen aus einer Datenbank zu einer Anweisung hinzufügen, wenn die Datenbank mit dem Projekt verknüpft ist.

## Resources for utilities

VIEW_UTILITY_DEFAULT_FONT_UI_ = MS Sans Serif
STRING_MATCH_EXPECTED_EXCEPTION_MESSAGE = Erwartet: 
STRING_MATCH_RETURNED_EXCEPTION_MESSAGE =  Zurückgegeben:
