# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Copyright (c) 2002, 2007. All Rights Reserved IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which is available at
# http://www.eclipse.org/legal/epl-v10.html
#  
# Contributors:
#     IBM Corporation - initial API and implementation
#
# Properties file for component:  SQLQ - SQL builder

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

!
! views/update/RemoveUpdateColumnAction.java
!
_UI_ACTION_REMOVE_UPDATE_COLUMN = 删除列(&C)

!
! views/update/UpdateTreeElement.java
!
_UI_COLUMN_UPDATE_GROUP = 更新组

!
! views/update/UpdateTreeViewer.java
!
_UI_COLUMN_UPDATE_COLUMN     = 更新列
_UI_COLUMN_UPDATE_EXPRESSION = 表达式

!
!views/update/UpdateViewer.java
!
_UI_WORKBOOK_SET    = 设置
_UI_WORKBOOK_WHERE  = 位置


!
! Actions
!
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_ACTION_ADD_TABLE          = 添加表(&A)...
_UI_ACTION_ADD_TABLE_REPLACE  = 替换表(&E)...
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" in the following line
_UI_ACTION_ADD_FULLSELECT     = 添加 FULLSELECT 语句(&F)
_UI_ACTION_REMOVE_TABLE       = 删除表(&M)...

!actions/ChangeStatementTypeAction
_UI_ACTION_CHANGE_STATEMENT_TYPE		= 更改语句类型(&C)...

!actions/OmitCurrentSchemaAction
_UI_ACTION_OMIT_CURRENT_SCHEMA		= 省略当前架构(&O)...

!actions/AddValueRowAction
_UI_ACTION_ADD_VALUE_ROW=添加值行(&R)

!actions/AddValuesAction.java
_UI_ACTION_ADD_VALUES=添加值(&V)

!actions/AddSubSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following line
_UI_ACTION_ADD_SELECT=添加 SELECT 语句(&S)

!actions/CreateWithTableAction.java
_UI_ACTION_ADD_COMMON_TABLE=添加常规表表达式(WITH)(&A)

!actions/DeleteStatementAction.java
_UI_ACTION_DELETE_STATEMENT=删除(&D)

!expressionbuilder/actions/DeleteExpressionAction.java
_UI_ACTION_DELETE_EXPRESSION=删除表达式(&R)

!expressionbuilder/actions/DeleteCaseClauseAction.java
_UI_ACTION_DELETE_CLAUSE=删除子句(&R)

!expressionbuilder/actions/DeleteFunctionParameterAction.java
_UI_ACTION_DELETE_PARAMETER=删除参数(&R)

!expressionbuilder/case/CastExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_WIZARD_CAST_EXPRESSION_TITLE=CAST 表达式生成器

!expressionbuilder/caseexpr/CaseSimplePage.java
_UI_COMBO_ADDFUNCTION=生成函数表达式...

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_COMBO_ADDCASE=生成 CASE 表达式...
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_COMBO_ADDCAST=生成 CAST 表达式...
_UI_COMBO_ADDCONSTANT=生成常量表达式...
_UI_COMBO_SELECTSUBQUERY=选择子查询...
_UI_COMBO_ADDEXPRBYOPERATOR=通过运算符生成表达式...
_UI_WIZARD_CASE_SIMPLE_TITLE=简单 CASE 表达式
_UI_WIZARD_CASE_SIMPLE_HEADING=生成简单 CASE 表达式。
!! NOTE TO TRANSLATOR: Do not translate "WHEN-THEN" and "ELSE" in the following line
_UI_LABEL_BUILD_WHEN_CLAUSE=生成 WHEN-THEN 子句和/或添加 ELSE 子句(&U)
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_CHECKBOX_ADD_ELSE=添加 ELSE 子句(&E)
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_BUTTON_ADD_WHEN=添加 WHEN 子句(&W)
_UI_LABEL_EXPRESSION_PREVIEW=CASE 表达式预览:

!expressionbuilder/function/FunctionBuilderPage.java:

!expressionbuilder/caseexpr/CaseSearchTable.java
_UI_COLUMN_CASE_SEARCH_EXPRESSION=表达式
_UI_COLUMN_CASE_SEARCH_OPERATOR=运算符
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE_SEARCH=删除 WHEN 子句(&R)
_UI_ACTION_DELETE_SEARCH_CONDITION=删除搜索条件(&R)
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION_SEARCH=删除 ELSE 表达式(&R)

!expressionbuilder/caseexpr/CaseSearchPage.java
_UI_WIZARD_CASE_SEARCH_HEADING=搜索到的 CASE 表达式
_UI_WIZARD_CASE_SEARCH_EXPR=生成搜索到的 CASE 表达式。

!expressionbuilder/caseexpr/CaseSimpleTable.java
_UI_COLUMN_CASE_EXPRESSION=表达式
_UI_COLUMN_RESULT_EXPRESSION=结果表达式
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE=删除 WHEN 子句(&R)
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION=删除 ELSE 表达式(&R)

!expressionbuilder/...Signatures...
_UI_FCN_ALL=全部
_UI_FCN_COLUMN=列
_UI_FCN_SPECIAL_REG=专用寄存器
_UI_FCN_SCALAR=标量
_UI_FCN_CONVERSION=转换
_UI_FCN_SECURITY=安全性
_UI_FCN_DATE_TIME=日期和时间
_UI_FCN_DATE=日期
_UI_FCN_DB2=DB2
_UI_FCN_LOGICAL=逻辑
_UI_FCN_MATH=数学
_UI_FCN_BIT=位
_UI_FCN_NUMBER=数值
_UI_FCN_CHARACTER=字符
_UI_FCN_SUMMARY=摘要
_UI_FCN_TEXT=文本
_UI_FCN_SYSTEM=系统
_UI_FCN_STRING=字符串
_UI_FCN_AGGREGATE=聚合
_UI_FCN_MISCELLANEOUS_SINGLE_ROW=杂项单行
_UI_FCN_MISCELLANEOUS=杂项
_UI_FCN_OBJECT_REFERENCE=对象引用
_UI_FCN_CONTROL_FLOW=控制流
_UI_FCN_TEXT_EXTENDERS=文本扩展器
_UI_FCN_AIV_EXTENDERS=音频/图像/视频扩展器
_UI_FCN_XMLFUNCTIONS=XML
_UI_FCN_NOT_SUPPORTED=不支持
_UI_FCN_UDF=用户定义函数(UDF)
_UI_FCN_DATALINK=数据链路
_UI_FCN_MQ_EXTENDER=消息队列(MQ)

!expressionbuilder/subquery/SubQueryWizard.java
_UI_WINDOW_TITLE_CHOICES=子查询选择

!expressionbuilder/function/FunctionBuilderPage.java
_UI_WIZARD_FUNCTION_BUILDER_HEADING=函数生成器
_UI_WIZARD_FUNCTION_BUILDER_EXPL=使用此页面生成函数表达式。
_UI_WIZARD_FUNCTION_BUILDER_INSTR_CAT=1. 选择函数类别(&C):
_UI_WIZARD_FUNCTION_BUILDER_INSTR_FCN=2. 选择函数(&U):
_UI_WIZARD_FUNCTION_BUILDER_INSTR_SIG=3. 选择函数特征符(&S):
_UI_WIZARD_FUNCTION_BUILDER_INSTR_EXPR=4. 选择自变量的表达式(&E):
_UI_WIZARD_FUNCTION_BUILDER_INSTR_PRE=5. 函数表达式预览:

!expressionbuilder/caseexpr/CaseExpressionDialog.java

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following 2 lines
_UI_WIZARD_CASE_OPTION_HEADING=CASE 选项
_UI_WIZARD_CASE_OPTION_EXPL=选择要生成的 CASE 表达式的类型。

_UI_GROUP_CASE_TYPE=CASE 类型
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SEARCHED_WHEN=搜索到的 WHEN 子句(&S)

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SEARCHED_WHEN = 例如，CASE WHEN i>j THEN k END

!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SIMPLE_WHEN=简单 WHEN 子句(&I)

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SIMPLE_WHEN = 例如，CASE i WHEN 8 THEN j END

!expressionbuilder/caseexpr/CaseExpressionDialog.java
!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_WIZARD_CASE_EXPRESSION_TITLE=CASE 表达式生成器

!expressionbuilder/constant/ConstantExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_NUMERIC_CONSTANT=0123456789-+E.

!expressionbuilder/case/CaseBuilderPage.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" where it occurs in the following 6 lines
_UI_WIZARD_CAST_BUILDER_TITLE=CAST 生成器
_UI_WIZARD_CAST_BUILDER_HEADING=使用此页面生成 CAST 表达式。
!! NOTE TO TRANSLATOR: Do not translate "SCOPE" in the following line
_UI_LABEL_PREVIEW_CAST_EXPRESSION=CAST 表达式预览:
_UI_LABEL_DATATYPE_LENGTH=数据类型长度:

!expressionbuilder/constant/ConstantExpressionDialog.java
_UI_WIZARD_CONSTANT_TITLE=常量表达式生成器

!expressionbuilder/constant/NumericConstantBuilderPage.java
_UI_WIZARD_NUMERIC_CONSTANT_TITLE=数字常量生成器
_UI_WIZARD_NUMERIC_CONSTANT_HEADER=数字常量生成器
_UI_WIZARD_NUMERIC_CONSTANT_EXPL=此页面帮助您生成数字常量表达式。
_UI_BUTTON_CLEAR=清除(&C)

!! NOTE TO TRANSLATOR: Do not translate the following 2 lines
_UI_BUTTON_FLOAT_TO_EXP=&F <-> E
_UI_BUTTON_PLUS_MINUS=+&/-

!expressionbuilder/constant/ConstantOptions.java
_UI_WIZARD_CONSTANT_OPTIONS_TITLE=常量选项
_UI_WIZARD_CONSTANT_OPTIONS_HEADING=常量选项
_UI_WIZARD_CONSTANT_OPTIONS_EXPL=选择要生成的常量表达式的类型。
_UI_GROUP_CONSTANT_TYPE=常量类型
_UI_RADIO_NUMERIC=数字常量(&U):整数、浮点或十进制数
_UI_RADIO_STRING=字符串常量(&S):字符或图形字符串、十六进制数或主变量名称

!expressionbuilder/constant/StringConstantBuilderPage.java
_UI_WIZARD_STRING_CONSTANT_TITLE=字符串常量生成器
_UI_WIZARD_STRING_CONSTANT_HEADING=字符串常量生成器
_UI_WIZARD_STRING_CONSTANT_EXPL=此页帮助您生成字符串常量表达式。在文本字段中键入表达式。
_UI_GROUP_STRING_TYPE=字符串常量类型
_UI_RADIO_CHARACTER=字符串常量(&A)
_UI_RADIO_HEX=十六进制常量(&H)
_UI_RADIO_HOST_VARIABLE_NAME=主变量名称(&V)
_UI_RADIO_GRAPHIC=图形字符串常量(&G)
_UI_LABEL_PREVIEW_CONSTANT_EXPRESSION=常量表达式预览:

!expressionbuilder/function/FunctionExpressionDialog.java
_UI_WIZARD_FUNCTION_EXPRESSION_TITLE=函数表达式生成器

!ExpressionBuilder/MainExpressionPage.java
_UI_WIZARD_MAIN_EXPRESSION_TITLE=表达式生成器
_UI_WIZARD_MAIN_EXPRESSION_HEADING=表达式类型
_UI_WIZARD_MAIN_EXPRESSION_EXPL=选择要生成的表达式的类型。
_UI_RADIO_FUNCTION=函数(&F)

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_RADIO_CASE=CASE(&C) - 搜索到的或简单

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_RADIO_CAST=CAST(&A)

_UI_RADIO_CONSTANT=常量(&O) - 数字、字符串或主变量
_UI_RADIO_SUBQUERY=子查询(&S)
_UI_RADIO_OPERATORS=通过运算符生成表达式(&U)
_UI_COLUMN_EXPRESSION=表达式
_UI_COLUMN_OPERATOR=运算符
_UI_COLUMN_PARAMETER=参数
_UI_COLUMN_VALUE=值

!expressionbuilder/multiexpr/ExpressionsByOperatorsWizard.java
_UI_WIZARD_EXPRESSION_BY_OPERATOR_TITLE=通过运算符生成表达式
_UI_WIZARD_EXPRESSION_BY_OPERATOR_HEADING=基于运算符的表达式
_UI_WIZARD_EXPRESSION_BY_OPERATOR_EXPL=通过使用提供的运算符生成较大表达式。
_UI_LABEL_BUILD_LEFT_OP_RIGHT=在左边生成表达式并在右边选择运算符(&U):
_UI_LABEL_PREVIEW_EXPRESSION=表达式预览:

!expressionbuilder/subquery/SubQueryPage.java
_UI_WIZARD_SUBQUERY_HEADING=子查询
_UI_WIZARD_SUBQUERY_EXPL=选择子查询。
_UI_LABEL_CHOICES=可用选择：
_UI_RADIO_EXISTING_STATEMENTS=创建基于现有查询的子查询(&E)
_UI_RADIO_SCRATCH_SELECT=创建原始子查询(&S)
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following 2 lines
_UI_LABEL_EXISTING_SELECT=创建或编辑 SELECT 语句(&R):
_UI_LABEL_NEW_SELECT_INFO=键入 SELECT 语句(&T)。您可以指定虚拟表。

!views/CustomSashForm.java
_UI_TOOLTIP_RESTORE_PANE=复原窗格
_UI_TOOLTIP_HIDE_PANE=隐藏窗格


!preferences/SQLBuilderPreferencePage.java
_UI_PREFERENCES_OMIT_SCHEMA_DESC=与 SQL 语句相关联的“省略当前架构”设置的默认值
_UI_PREFERENCES_OMIT_SCHEMA_IN_SQL=在生成的 SQL 语句中省略当前架构(&O)
_UI_PREFERENCES_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=当前架构
_UI_PREFERENCES_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=授权 ID(&A)
_UI_PREFERENCES_OMIT_SCHEMA_SCHEMA_NAME=架构名称(&S):

!dialogs/ChangeStatementTypeDialog
_UI_DIALOG_CHANGE_STATEMENT_TYPE_TITLE=更改 SQL 语句类型
_UI_DIALOG_CHANGE_STATEMENT_TYPE_NOTE=更改 SQL 语句类型将导致当前语句替换为新的空语句。
_UI_DIALOG_CHANGE_STATEMENT_TYPE_GROUP_TITLE=语句类型

!dialogs/OmitCurrentSchemaDialog
_UI_DIALOG_OMIT_SCHEMA_TITLE=省略当前架构
_UI_DIALOG_OMIT_SCHEMA_IN_SQL=在生成的 SQL 语句中省略当前架构(&O)
_UI_DIALOG_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=当前架构
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_USER_AS_CURRENT_SCHEMA=授权 ID <{0}>(&A)
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=授权 ID(&A)
_UI_DIALOG_OMIT_SCHEMA_SCHEMA_NAME=架构名称(&S):

!views/execute/ParameterWizards.java
_UI_WIZARD_SPECIFY_VARIABLE_VALUES_TITLE=指定变量值

!views/execute/ParameterWizardDialog.java
_UI_WIZARD_PARAMETER_MARKERS_TITLE=参数标记

!views/execute/ParameterMarkerPage.java
_UI_WIZARD_PARAMETER_MARKER_TITLE=替代变量
_UI_WIZARD_PARAMETER_MARKER_HEADING=主变量值
_UI_WIZARD_PARAMETER_MARKER_EXPL=指定要使用的变量值

!views/execute/ParameterTableViewer.java
_UI_COLUMN_MARKER_NAME=名称
_UI_COLUMN_TYPE=类型
_UI_COLUMN_PARAMETER_VALUE=值


!views/AddTableDialog.java
_UI_LABEL_TABLE_NAME            = 表名(&N):
_UI_DIALOG_REPLACE_TABLE_TITLE  = 替换表
_UI_DIALOG_ADD_TABLE_TITLE      = 添加表
_UI_LABEL_TABLE_ALIAS           = 表别名(&A):
_UI_DIALOG_TABLE_ALREADY_ADDED  = 已添加表 - 指定别名
_UI_DIALOG_ADD_VIEW_TO_SELF     = 不能将视图添加至拥有的定义


!views/GridViewer.java
_UI_COLUMN_DEFAULT_COLUMN=列

!views/insert/InsertGridViewer.java
_UI_COLUMN_INSERT_VALUE=值

!views/criteria/CriteriaGridViewer.java
_UI_COLUMN_COLUMN=列
_UI_COLUMN_CRITERIA_OPERATOR=运算符
_UI_COLUMN_CRITERIA_VALUE=值

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_COLUMN_CRTIERIA_AND_OR=AND/OR

!views/criteria/CriteriaValueExpression.java
_UI_ACTION_UPDATE_VALUE_EXPRESSON=更新值表达式(&U)
_UI_ACTION_REMOVE_CONDITION=删除条件(&R)
_UI_MENU_EXECUTE= 运行 SQL(&R)

!views/fullselect/FullSelectViewer.java
!! NOTE TO TRANSLATOR: Do not translate VALUES in the following entry, since it is a SQL keyword
_UI_LABEL_FULL_SELECT_VALUES_HELP=要添加值行，右键单击“轮廓”视图中的 VALUES。

!views/fullselect/ValuesRowViewer.java
_UI_COLUMN_VALUES_ROW_ITEM=值行项
_UI_ACTION_REMOVE_VALUES_ROW=删除项(&R)

!views/fullselect/FullSelectGridViewer.java
_UI_COLUMN_STATEMENT=语句
_UI_COLUMN_FULL_SELECT_OPERATOR=运算符

!views/graph/editparts/TableEditPart.java
_UI_ACTION_UPDATE_ALIAS=更新别名(&U)...
_UI_DIALOG_CHANGE_ALIAS_TITLE=更改表别名
_UI_DIALOG_CHANGE_ALIAS_TEXT=新建别名(&E):
_UI_ACTION_CREATE_JOIN=创建联接(&J)...
_UI_ACTION_REMOVE_TABLE_EDIT=删除表(&M)


!views/graph/GraphContextMenuProvider.java:
_UI_ACTION_REMOVE_JOIN=删除联接(&R)

!views/graph/SourceTargetDialog.java
_UI_DIALOG_SOURCE_AND_TARGET_TITLE=创建联接
_UI_DIALOG_SOURCE_AND_TARGET_TEXT=选择联接的源列和目标列。
_UI_LABEL_JOIN_SRCCOL_TYPE = 源列类型:
_UI_LABEL_JOIN_TGTCOL_TYPE = 目标列类型:

_UI_GROUP_SOURCE=源
_UI_LABEL_TABLE=表(别名)(&T)
_UI_LABEL_COLUMN=列(&C)
_UI_GROUP_TARGET=目标
_UI_LABEL_TARGET_TABLE=表(别名)(&A)
_UI_LABEL_TARGET_COLUMN=列(&O)

_UI_GRAPH_PROMPT = 要添加表，右键单击此窗格并使用弹出菜单。
_UI_GRAPH_PARSE_FAILED = 此 SQL 语法无效或当前不受支持。\
您可以手动输入 SQL。某些 SQL 生成器功能已被禁用。\
要启用这些函数，请更改语法。\n\n要撤消最近的更改，\
请从 SQL 菜单中选择“回复到上次正确的源”。
_UI_GRAPH_NO_TABLE_FOUND = 无法找到表 {0}。它可能不存在或被筛选掉。\
某些 SQL 生成器函数已被禁用。\
要启用这些函数，请更改语法并保存语句。\n\n要撤消最近的更改，\
请从 SQL 菜单中选择“回复到上次正确的源”。
_UI_GRAPH_NO_COLUMN_FOUND = 无法找到列 {0}。某些 SQL 生成器功能已被禁用。\
要启用这些函数，请更改语法并保存语句。\n\n要撤消最近的更改，\
请从 SQL 菜单中选择“回复到上次正确的源”。

!views/inster/InsertTypeViewer.java
_UI_GROUP_INSERT_ROWS=从以下位置插入行:
_UI_RADIO_VALUES=值
_UI_RADIO_INSERT_FROM_SUBQUERY=子查询
_UI_ACTION_REMOVE_COLUMN=删除列(&R)

!views/insert/InsertSelectViewer.java
_UI_LABEL_QUERY_NAME=查询名称:

!views/select/GroupByContentViewer.java
_UI_LABEL_GROUPS_TYPE=类型:
_UI_COMBOBOXITEM_GROUPING_ROOT=分组根
_UI_ACTION_REMOVE=删除(&R)
_UI_NONE=无
_UI_SIMPLE=简单

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_CUBE=CUBE

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_ROLLUP=ROLLUP

_UI_GROUPING=分组
_UI_GROUPINGSETS=分组集合

! views/select/SelectGridViewer.java:
!
_UI_COMBO_SORT_UNSORTED   = 未排序
_UI_COMBO_SORT_ASCENDING  = 升序
_UI_COMBO_SORT_DESCENDING = 降序
_UI_COMBO_SORT_DEFAULT = 默认

!
!views/select/RemoveSelectColumnsAction.java
!
_UI_ACTION_REMOVE_SELECT_COLUMN = 删除列表达式(&C)

!
!views/select/RemoveOrderByExpressionAction.java
!
_UI_ACTION_REMOVE_ORDER_BY_EXPRESSION = 删除排序表达式(&O)

!
! views/select/SelectGridViewer.java
!
_UI_COLUMN_SELECT_ALIAS      = 别名
_UI_COLUMN_SELECT_OUTPUT     = 输出
_UI_COLUMN_SELECT_SORT_TYPE  = 排序类型
_UI_COLUMN_SELECT_SORT_ORDER = 排序顺序

!
! views/select/SelectViewer.java
!
_UI_WORKBOOKPAGE_COLUMNS          = 列
_UI_WORKBOOKPAGE_CONDITIONS       = 条件
_UI_WORKBOOKPAGE_GROUPS           = 组
_UI_WORKBOOKPAGE_GROUP_CONDITIONS = 分组条件

!
! views/SQLBuilderActionBarContributor.java
!
_UI_TOOLTIP_EXECUTE_SQL = 运行 SQL 语句
_UI_MENU_SQLBUILDER     = SQL(&S)

!
! views/source/SQLSourceViewer.java & SQLSourceParser
!
!! NOTE TO TRANSLATOR: Do not translate the following four lines
_UI_INSERT                   = INSERT
_UI_UPDATE                   = UPDATE
_UI_DELETE                   = DELETE
_UI_SELECT                   = SELECT

_UI_PARSE_ERROR_ENCOUNTERED  = 遇到了解析错误。


!
! views/StatementNameViewer.java
!
_UI_LABEL_STATEMENT = 语句:


!
! Join stuff - DefineJoinDialog.java, DefineJoinTypeDialog.java
!
_UI_DEFINE_JOIN_DIALOG_TITLE = 指定联接:
_UI_DEFINE_JOIN_DIALOG_INSTR = 联接类型
_UI_RADIO_INNER_JOIN         = 内联接(&I)
_UI_RADIO_LEFT_OUTER_JOIN    = 左外联接(&L)
_UI_RADIO_RIGHT_OUTER_JOIN   = 右外联接(&R)
_UI_RADIO_FULL_OUTER_JOIN    = 完全外部联接(&F)
_UI_ACTION_SPECIFY_JOIN_TYPE = 指定联接类型(&S)...
_UI_MSG_INVALID_JOIN_TITLE = 不兼容类型

!
!views/update/UpdateDesignViewer.java
!
_UI_TOOLTIP_UPDATE_ADD_COL = 将个别列添加至语句
_UI_TOOLTIP_UPDATE_ADD_GRP = 将多列作为一组添加至语句

!
!views/with/WithTableViewer.java
!
_UI_GROUP_WITH_TABLE     = 表
_UI_GROUP_WITH_COLUMN    = 列
_UI_BUTTON_ADD_RIGHT     = 添加 >>
_UI_BUTTON_REMOVE_LEFT   = << 删除

!
! views/with/WithStatementViewer
!
_UI_LABEL_WITH_STATEMENT  = 语句名称:

! CreateWithTableAction.java

!! NOTE TO TRANSLATOR: Do not translate "WithTable%1" in the following line
_UI_WITH_TABLE_NAME		  = WithTable%1
!
! SQLPreferencePage.java
!
_UI_VALIDATE_PREFERENCE_LABEL = 在保存之前运行查询语句来验证语句(&V)
_UI_ERROR_VALUE_GREATER_THAN_0 = 此值必须是大于零的整数。

!
!views/SQLBuilder.java
!
_UI_VALIDATE_FAILED_TITLE    = 验证失败
_UI_CONTINUE_WITH_SAVE       = 要继续保存吗？
_UI_VALIDATING_STATEMENT     = 正在验证语句...
_UI_OBTAINING_CONNECTION     = 正在获取连接...
_UI_VALIDATE_DONE            = 验证完成...
_UI_SAVING_STATEMENT         = 正在保存语句...

!model/SQLBuilderConstants.java:
_UI_BUILD_EXPRESSION   = 生成表达式...
_UI_EDIT_EXPRESSION    = 编辑表达式...
_UI_REPLACE_EXPRESSION = 替换表达式...
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_ADD_SELECT         = 添加 SELECT 语句...
_UI_ADD_FULLSELECT     = 添加 FULLSELECT 语句...
_UI_ADD_WITH           = 添加 WITH 语句...
_UI_ADD_VALUES         = 添加值
_UI_SPECIFY_VALUE	   = 指定值...
_UI_SPECIFY_VALUE_TITLE	   = 指定值


!========================================================================================
!
! Here is the list of Warning string that have message IDs - make sure they are unique
!
!========================================================================================
_WARN_MESSAGES_ENCOUNTERED      = 遇到了警告消息
_WARN_DATA_WAS_TRUNCATED        = 数据被截断
_WARN_SQL_WARNINGS_FOUND        = 发现了 SQL 警告

_WARN_BAD_JOIN_1                = 联接类型不兼容
_WARN_INVALID_JOIN              = 无效联接
_WARN_COLUMN_USED               = 已在表之间的联接中使用了列

! Usage:
!   {0} replaced with the column name and {1} replaced with the column datatype
!
_WARN_BAD_JOIN_TYPES               = 列 {0} 的类型为 {1}


!======================================================================================
!
! Here is the list of Error string that have message IDs - make sure they are unique
!
!======================================================================================

_ERROR_DIALOG_TITLE_EXPR_EDIT_FAILED = 编辑表达式失败
_ERROR_DIALOG_MSG_REBUILD_EXPR       = 必须重新生成表达式

_ERROR_TABLE_USED                    = 选择唯一表或输入别名。
_ERROR_ALIAS_USED                    = 输入唯一别名。

_ERROR_ALIAS_NOT_UNIQUE_TEXT         = 别名并非唯一。


_EXC_OPEN_SQL_FILE_RESOURCE          = 打开输入 SQL 文件资源时发生了错误
_EXC_OPEN_SQL_FILE_NOT_CONNECTED     = 在 SQL 查询生成器中打开 SQL 文件之前，必须连接至数据库“{0}”。

!! NOTE TO TRANSLATOR: Do not translate "ISQLBuilderEditorInput" in the following line
_EXC_INPUT_NOT_ISQLBUILDEREDITORINPUT = 输入并非 ISQLBuilderEditorInput

_ERROR_ALIAS_NOT_ALPHANUMERIC        = 别名必须全为字母数字字符。
_ERROR_ALIAS_TABLE_USED              = 别名不能是数据库表名。
_ERROR_ENTER_ALIAS                   = 表名已使用。输入别名。

_ERROR_DATABASE_NOT_AVAILABLE        = 数据库连接不可用。
_ERROR_INPUT_NOT_RECOGNIZED          = 该编辑器输入类型不受支持。
_ERROR_OPEN_SQL_STORAGE_RESOURCE     = 打开输入 SQL 存储器资源时发生了错误
_ERROR_OPEN_SQL_STRING_RESOURCE      = 打开输入时发生了错误
_ERROR_OPEN_INPUT_PARSE_FAILED       = 因为此 SQL 无效或当前不受支持，所以不能解析此 SQL。
_QUESTION_TITLE_OPEN_INPUT_PARSE_FAILED    = SQL 查询生成器解析错误
_QUESTION_MESSAGE_OPEN_INPUT_PARSE_FAILED    = 将在 SQL 查询生成器中创建空 SQL 语句。

!
!model/SQLDomainModel.java
!
!note we reuse messages from ErrorMessages.java in org.eclipse.ui.texteditor.ErrorMessages

Editor_error_save_title=保存问题
Editor_error_save_message=无法完成保存操作。
Editor_error_save_readonly=\n\n原因:\n不能写至只读文件:
Editor_error_save_failed=\n\n原因:\n不能写至文件:

!Strings from B2BGUI properties file
_UI_ERROR_CREATING_FILE_TITLE = 创建文件时出错
_UI_ERROR_CREATING_FILE_SHORT_DESC = 创建文件“{0}”时出错
_UI_ERROR_CREATING_FILE_LONG_DESC = 尝试创建文件“{0}”时发生了错误。
_UI_PARENT_FOLDER_IS_READ_ONLY = 父目录“{0}”为只读目录。
_UI_UNKNOWN_ERROR_WITH_HINT = 未知错误。确保父目录“{0}”为可写入目录。
_UI_UNKNOWN_ERROR = 未知错误。确保父目录“{0}”为可写入目录。
! TextViewerOperationAction
_UI_MENU_COPY         = 复制(&C)
_UI_MENU_CUT          = 剪切(&T)
_UI_MENU_DELETE       = 删除
_UI_MENU_PASTE        = 粘贴(&P)
_UI_MENU_PREFIX       = 前缀
_UI_MENU_REDO         = 恢复
_UI_MENU_SELECT_ALL   = 全选
_UI_MENU_SHIFT_LEFT   = 左移
_UI_MENU_SHIFT_RIGHT  = 右移
_UI_MENU_STRIP_PREFIX = 删除前缀
_UI_MENU_UNDO         = 撤消

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = 打开 SQL 编辑器
datatools_sqlbuilder_sqleditor_title = SQL 编辑器(&S)

! SQL Query Builder
datatools_sqlbuilder_sqlbuilder_DML_error = 错误
datatools_sqlbuilder_sqlbuilder_multipleDML = SQL 生成器只能用于创建单个\
SQL DML 语句。文件 {0} 不包含单个 DML 语句。使用 SQL 编辑器打开文件?
datatools_sqlbuilder_sqlbuilder_multipleDML_VE = Visual Explain 只能用于单个\
SQL DML 语句。文件 {0} 不包含单个 DML 语句。
datatools_sqlbuilder_sqlbuilder_unsupport_VE = 此数据库连接不支持 Visual Explain。
!Clear to Skeleton and Revert to Last Correct
_UI_CLEAR_TO_TEMPLATE 			     = 清除至模板
_UI_REVERT_TO_LAST_CORRECT_SOURCE    = 回复至上一次的正确源
_UI_LAST_CORRECT_SOURCE 			 = 要回复至上一次的正确源吗?
!Change Statement Type
_UI_CHANGE_STATEMENT_TYPE			= 更改语句类型...
!Omit Current Schema
_UI_OMIT_CURRENT_SCHEMA              = 省略当前架构... 

!
! views/execute/ExecuteViewer.java & views/execute/QueryOutputHelper.java
!
_UI_DIALOG_EXECUTE_SQL_TITLE = 运行 SQL 语句
_UI_BUTTON_EXECUTE_CLOSE     = 关闭(&C)
_UI_LABEL_SQL_STATEMENT      = SQL 语句(&S):
_UI_BUTTON_EXECUTE           = 运行(&R)
_UI_LABEL_QUERY_RESULTS      = 查询结果:
_UI_MONITOR_EXECUTING_QUERY  = 正在运行 SQL 语句...
_UI_LABEL_NO_CONNECTION      = 数据库连接已丢失或关系数据库架构模型已毁坏。
_UI_LABEL_NO_CONNECTION_FILE = 因为连接 XMI 文件丢失，所以数据库连接不可用。

_UI_DIALOG_WARNING_TITLE       = 警告
_UI_DIALOG_OP_FAILED_TITLE     = 操作失败
_UI_LABEL_EXECUTION_SUCCESSFUL = 语句运行成功，但未生成要显示的结果。
!! NOTE TO TRANSLATOR: the MAX_RECORD_EXCEEDED string should match
!! the strings for RECORD_RETURNED and RECORD_DISPLAYED.
_UI_MSG_MAX_RECORD_EXCEEDED    = 返回的记录数超过 1000。显示 1000 个记录。
_UI_MSG_RECORD_RETURNED        = 返回了多个记录。


! SQL Statement validation errors
! usage note: %1 will be replaced with a SQL statement name
_ERROR_STATEMENT_NAME_EXISTS         = 名为 %1 的语句已存在。
_ERROR_INVALID_STATEMENT_NAME = 输入有效语句名。
! usage note: %1 is replaced with the invalid character entered by the user
_ERROR_INVALID_CHAR_IN_STATEMENT_NAME = 语句名不能包含字符 %1。
_ERROR_STATEMENT_NAME_TOO_LONG = 语句名不能超过 160 个字符。


! SelectDBTablePage resources
datatools_selectDBTablePage_statements = 语句

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = 新建...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = 新建 SQL 语句...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = 创建新查询语句
datatools_sqlbuilder_sqlstatement_actions_openwith = 打开方式
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = SQL 查询生成器
datatools_sqlbuilder_sqlstatement_actions_sqleditor = SQL 编辑器

!
! New SQL statement wizard, dialog, and page
!
datatools_sqlbuilder_newStatementWizard_title = 新建 SQL 语句
datatools_sqlbuilder_newStatementWizard_description = 创建 SQL 语句。
datatools_sqlbuilder_newStatementDialog_title = 新建 SQL 语句
datatools_sqlbuilder_newStatementPage_title = 语句类型
datatools_sqlbuilder_newStatementPage_description = 命名此语句，并对此语句选择模板类型。
datatools_sqlbuilder_newStatementPage_statementID = 语句标识
datatools_sqlbuilder_newStatementPage_statementName = 语句名(&S):
datatools_sqlbuilder_newStatementPage_statementType = 语句模板(&T):
datatools_sqlbuilder_newStatementPage_editUsing = 编辑方式
datatools_sqlbuilder_newStatementPage_sqlQueryBuilder = SQL 生成器(&Q)
datatools_sqlbuilder_newStatementPage_sqlEditor = SQL 编辑器(&E)
datatools_sqlbuilder_newStatementPage_sampleStatements = 样本语句
datatools_sqlbuilder_newStatementPage_none = 无
!
! Project selection page, for new SQL statement wizard
!
datatools_sqlbuilder_projectPage_title = 选择项目
datatools_sqlbuilder_projectPage_description = 对此语句选择现有项目或添加新项目。

!
! Generated comment text for template SQL for New SQL Statement action
!
_UI_SAMPLE_DML_TEMPLATE_STATEMENTS = 样本 DML 模板语句
_UI_SAMPLE_DDL_TEMPLATE_STATEMENTS = 样本 DDL 模板语句

!
! String for the AddTable With Table
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_AVAILABLE_TABLES_TREE_PROVIDER = WITH 表

!actions/ConvertToFullSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" and "UNION" in the following line
_UI_ACTION_CONVERT_TO_FULL_SELECT=转换为 FULLSELECT (UNION)(&C)


! org.eclipse.datatools.sqltools.sqlbuilder.views.fullselect/fullselectElement.java
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_VIEWS_FULLSELECTELEMENT_FULLSELECT = FULLSELECT 语句
_UI_VIEWS_FULLSELECTELEMENT_SELECT = SELECT 语句
_UI_VIEWS_FULLSELECTELEMENT_VALUES = VALUES

! org.eclipse.datatools.sqltools.sqlbuilder.views.graph/GraphContextMenuProvider.java
_UI_VIEWS_GRAPH_SELECT_ALL_COLUMN = 选择所有列
_UI_VIEWS_GRAPH_DESELECT_ALL_COLUMN = 取消选择所有列

!SQLQueryBuilder Dialog
_UI_SQLQUERYBUILDERDIALOG_NAME = SQL 查询生成器
SQLQueryBuilderDialogEditTabName=编辑
SQLQueryBuilderDialogNoInput=SQLBuilder 对话未传递输入，无法打开。
SQLQueryBuilderDialogParseFailOnOpenAskUserTitle=SQL 查询生成器
SQLQueryBuilderDialogParseFailOnOpenAskUserMessage=如果继续，将在 SQL 查询生成器中创建空 SQL 语句。要继续吗?
SQLQueryBuilderDialogResultsTabName=SQL 结果


# plugin.xml.  preference page extension point
_UI_SQLQUERY_NAME = SQL 查询

## Resources for the standard editor actions

ContentAssistProposal_label       =内容助手@Ctrl+SPACE(&N)
ContentAssistProposal_tooltip     =内容助手
ContentAssistProposal_image       =
ContentAssistProposal_description =内容助手

ContentTip_label       =内容提示@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =内容提示
ContentTip_image       =
ContentTip_description =内容提示

## Resources for other SQL Query Builder actions

datatools_sqlbuilder_RunSQLAction_label       = 运行 SQL(&R)
datatools_sqlbuilder_RunSQLAction_tooltip     = 运行 SQL 语句
datatools_sqlbuilder_RunSQLAction_image       =
datatools_sqlbuilder_RunSQLAction_description =

datatools_sqlbuilder_RevertToPreviousAction_label       = 回复至上一次的正确源
datatools_sqlbuilder_RevertToPreviousAction_tooltip     =
datatools_sqlbuilder_RevertToPreviousAction_image       =
datatools_sqlbuilder_RevertToPreviousAction_description =

datatools_sqlbuilder_RevertToDefaultAction_label       = 清除至模板
datatools_sqlbuilder_RevertToDefaultAction_tooltip     =
datatools_sqlbuilder_RevertToDefaultAction_image       =
datatools_sqlbuilder_RevertToDefaultAction_description =

datatools_sqlbuilder_ChangeStatementTypeAction_label   = 更改语句类型...
datatools_sqlbuilder_ChangeStatementTypeAction_tooltip     =
datatools_sqlbuilder_ChangeStatementTypeAction_image       =
datatools_sqlbuilder_ChangeStatementTypeAction_description =

datatools_sqlbuilder_OmitCurrentSchemaAction_label       = 省略当前架构...
datatools_sqlbuilder_OmitCurrentSchemaAction_tooltip     =
datatools_sqlbuilder_OmitCurrentSchemaAction_image       =
datatools_sqlbuilder_OmitCurrentSchemaAction_description =

!RDBTableDropListener
_UI_INVALID_TABLE_ADDED = 不能将数据库中的表添加至语句，除非该数据库已与项目相关联。

## Resources for utilities

VIEW_UTILITY_DEFAULT_FONT_UI_ = 宋体
STRING_MATCH_EXPECTED_EXCEPTION_MESSAGE = 期望: 
STRING_MATCH_RETURNED_EXCEPTION_MESSAGE =  返回:
