# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Copyright (c) 2002, 2009. All Rights Reserved IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which is available at
# http://www.eclipse.org/legal/epl-v10.html
#  
# Contributors:
#     IBM Corporation - initial API and implementation
#
# Properties file for component:  SQLQ - SQL builder

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

!
! views/update/RemoveUpdateColumnAction.java
!
_UI_ACTION_REMOVE_UPDATE_COLUMN = Quitar &columna

!
! views/update/UpdateTreeElement.java
!
_UI_COLUMN_UPDATE_GROUP = Actualizar grupo

!
! views/update/UpdateTreeViewer.java
!
_UI_COLUMN_UPDATE_COLUMN     = Actualizar columna
_UI_COLUMN_UPDATE_EXPRESSION = Expresión

!
!views/update/UpdateViewer.java
!
_UI_WORKBOOK_SET    = Conjunto
_UI_WORKBOOK_WHERE  = Dónde


!
! Actions
!
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_ACTION_ADD_TABLE          = &Añadir tabla...
_UI_ACTION_ADD_TABLE_REPLACE  = R&eemplazar tabla...
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" in the following line
_UI_ACTION_ADD_FULLSELECT     = Añadir sentencia &FULLSELECT
_UI_ACTION_REMOVE_TABLE       = Eli&minar tabla...

!actions/ChangeStatementTypeAction
_UI_ACTION_CHANGE_STATEMENT_TYPE		= &Cambiar tipo de sentencia...

!actions/ChangeSetOperatorAction
_UI_ACTION_CHANGE_SET_OPERATOR		= Cambiar operador &Set...

!actions/OmitCurrentSchemaAction
_UI_ACTION_OMIT_CURRENT_SCHEMA		= &Omitir esquema actual...

!actions/AddValueRowAction
_UI_ACTION_ADD_VALUE_ROW=Añadir fila de valo&res

!actions/AddValuesAction.java
_UI_ACTION_ADD_VALUES=Añadir &valores

!actions/AddSubSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following line
_UI_ACTION_ADD_SELECT=Añadir sentencia &SELECT

!actions/CreateWithTableAction.java
_UI_ACTION_ADD_COMMON_TABLE=&Añadir expresión de tabla común (WITH)

!actions/DeleteStatementAction.java
_UI_ACTION_DELETE_STATEMENT=&Eliminar

!expressionbuilder/actions/DeleteExpressionAction.java
_UI_ACTION_DELETE_EXPRESSION=Quita&r expresión

!expressionbuilder/actions/DeleteCaseClauseAction.java
_UI_ACTION_DELETE_CLAUSE=Quita&r cláusula

!expressionbuilder/actions/DeleteFunctionParameterAction.java
_UI_ACTION_DELETE_PARAMETER=Quita&r parámetro

!expressionbuilder/case/CastExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_WIZARD_CAST_EXPRESSION_TITLE=Compilador de expresiones CAST

!expressionbuilder/caseexpr/CaseSimplePage.java
_UI_COMBO_ADDFUNCTION=Compilar expresión de función...

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_COMBO_ADDCASE=Compilar expresión CASE...
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_COMBO_ADDCAST=Compilar expresión CAST...
_UI_COMBO_ADDCONSTANT=Compilar expresión constante...
_UI_COMBO_SELECTSUBQUERY=Seleccionar subconsulta...
_UI_COMBO_ADDEXPRBYOPERATOR=Compilar expresión mediante operadores...
_UI_WIZARD_CASE_SIMPLE_TITLE=Expresión CASE simple
_UI_WIZARD_CASE_SIMPLE_HEADING=Compilar una expresión CASE simple.
!! NOTE TO TRANSLATOR: Do not translate "WHEN-THEN" and "ELSE" in the following line
_UI_LABEL_BUILD_WHEN_CLAUSE=Compilar clá&usulas WHEN-THEN, añadir una cláusula ELSE, o ambas cosas.
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_CHECKBOX_ADD_ELSE=Añadir cláusula &ELSE
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_BUTTON_ADD_WHEN=Añadir cláusula &WHEN
_UI_LABEL_EXPRESSION_PREVIEW=Vista previa de expresión CASE:

!expressionbuilder/function/FunctionBuilderPage.java:

!expressionbuilder/caseexpr/CaseSearchTable.java
_UI_COLUMN_CASE_SEARCH_EXPRESSION=Expresión
_UI_COLUMN_CASE_SEARCH_OPERATOR=Operador
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE_SEARCH=Quita&r cláusula WHEN
_UI_ACTION_DELETE_SEARCH_CONDITION=Quita&r condición de búsqueda
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION_SEARCH=Quita&r expresión ELSE

!expressionbuilder/caseexpr/CaseSearchPage.java
_UI_WIZARD_CASE_SEARCH_HEADING=Expresión CASE buscada
_UI_WIZARD_CASE_SEARCH_EXPR=Compilar una expresión CASE buscada.

!expressionbuilder/caseexpr/CaseSimpleTable.java
_UI_COLUMN_CASE_EXPRESSION=Expresión
_UI_COLUMN_RESULT_EXPRESSION=Expresión resultado
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE=Quita&r cláusula WHEN
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION=Quita&r expresión ELSE

!expressionbuilder/...Signatures...
_UI_FCN_ALL=Todos
_UI_FCN_COLUMN=Columna
_UI_FCN_SPECIAL_REG=Registros especiales
_UI_FCN_SCALAR=Escala
_UI_FCN_CONVERSION=Conversión
_UI_FCN_SECURITY=Valor
_UI_FCN_DATE_TIME=Fecha y hora
_UI_FCN_DATE=Fecha
_UI_FCN_DB2=DB2
_UI_FCN_LOGICAL=Lógica
_UI_FCN_MATH=Matemático
_UI_FCN_BIT=Bit
_UI_FCN_NUMBER=Número
_UI_FCN_CHARACTER=Carácter
_UI_FCN_SUMMARY=Resumen
_UI_FCN_TEXT=Texto
_UI_FCN_SYSTEM=Sistema
_UI_FCN_STRING=String
_UI_FCN_AGGREGATE=Total
_UI_FCN_MISCELLANEOUS_SINGLE_ROW=Fila única de varios
_UI_FCN_MISCELLANEOUS=Varios
_UI_FCN_OBJECT_REFERENCE=Referencia de objeto
_UI_FCN_CONTROL_FLOW=Flujo de control
_UI_FCN_TEXT_EXTENDERS=Ampliador de texto
_UI_FCN_AIV_EXTENDERS=Ampliadores de audio/imagen/vídeo
_UI_FCN_XMLFUNCTIONS=XML
_UI_FCN_NOT_SUPPORTED=NO ADMITIDO
_UI_FCN_UDF=Funciones definidas por el usuario (UDF)
_UI_FCN_DATALINK=Enlace de datos
_UI_FCN_MQ_EXTENDER=Cola de mensajes (MQ)

!expressionbuilder/subquery/SubQueryWizard.java
_UI_WINDOW_TITLE_CHOICES=Selecciones de subconsultas

!expressionbuilder/function/FunctionBuilderPage.java
_UI_WIZARD_FUNCTION_BUILDER_HEADING=Compilador de funciones
_UI_WIZARD_FUNCTION_BUILDER_EXPL=Usar esta página para compilar una expresión de función.
_UI_WIZARD_FUNCTION_BUILDER_INSTR_CAT=1. Seleccionar una &categoría de función:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_FCN=2. Seleccionar una f&unción:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_SIG=3. &Seleccionar una firma de función:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_EXPR=4. Seleccionar una &expresión para los argumentos:
_UI_WIZARD_FUNCTION_BUILDER_INSTR_PRE=5. Vista previa de expresión de función:

!expressionbuilder/caseexpr/CaseExpressionDialog.java

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following 2 lines
_UI_WIZARD_CASE_OPTION_HEADING=Opciones CASE
_UI_WIZARD_CASE_OPTION_EXPL=Seleccionar el tipo de expresión CASE a compilar.

_UI_GROUP_CASE_TYPE=Tipo de CASE
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SEARCHED_WHEN=Cláusula-WHEN-bu&scada

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SEARCHED_WHEN = por ejemplo, CASE WHEN i>j THEN k END

!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SIMPLE_WHEN=Cláusula-WHEN-s&imple

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SIMPLE_WHEN = por ejemplo, CASE i WHEN 8 THEN j END

!expressionbuilder/caseexpr/CaseExpressionDialog.java
!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_WIZARD_CASE_EXPRESSION_TITLE=Compilador de expresiones CASE

!expressionbuilder/constant/ConstantExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_NUMERIC_CONSTANT=0123456789-+E.

!expressionbuilder/case/CaseBuilderPage.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" where it occurs in the following 6 lines
_UI_WIZARD_CAST_BUILDER_TITLE=Compilador de CAST
_UI_WIZARD_CAST_BUILDER_HEADING=Usar esta página para compilar una expresión CAST.
!! NOTE TO TRANSLATOR: Do not translate "SCOPE" in the following line
_UI_LABEL_PREVIEW_CAST_EXPRESSION=Vista previa de expresión CAST:
_UI_LABEL_DATATYPE_LENGTH=Longitud de tipo de datos:

!expressionbuilder/constant/ConstantExpressionDialog.java
_UI_WIZARD_CONSTANT_TITLE=Compilador de expresión constante

!expressionbuilder/constant/NumericConstantBuilderPage.java
_UI_WIZARD_NUMERIC_CONSTANT_TITLE=Compilador de constante numérica
_UI_WIZARD_NUMERIC_CONSTANT_HEADER=Compilador de constante numérica
_UI_WIZARD_NUMERIC_CONSTANT_EXPL=Esta página le ayuda a compilar una expresión de constante numérica.
_UI_BUTTON_CLEAR=&Borrar

!! NOTE TO TRANSLATOR: Do not translate the following 2 lines
_UI_BUTTON_FLOAT_TO_EXP=&F <-> E
_UI_BUTTON_PLUS_MINUS=+&/-

!expressionbuilder/constant/ConstantOptions.java
_UI_WIZARD_CONSTANT_OPTIONS_TITLE=Opciones constantes
_UI_WIZARD_CONSTANT_OPTIONS_HEADING=Opciones constantes
_UI_WIZARD_CONSTANT_OPTIONS_EXPL=Seleccionar el tipo de expresión constante a compilar.
_UI_GROUP_CONSTANT_TYPE=Tipo constante
_UI_RADIO_NUMERIC=Constante n&umérica: entero, punto flotante o decimal
_UI_RADIO_STRING=Constante &string: carácter o string gráfico, hexadecimal, o nombres de variables de host

!expressionbuilder/constant/StringConstantBuilderPage.java
_UI_WIZARD_STRING_CONSTANT_TITLE=Compilador de constante string
_UI_WIZARD_STRING_CONSTANT_HEADING=Compilador de constante string
_UI_WIZARD_STRING_CONSTANT_EXPL=Esta página le ayuda a compilar una expresión de constante string. Introduzca la expresión en el campo de texto.
_UI_GROUP_STRING_TYPE=Tipo de constante string
_UI_RADIO_CHARACTER=Constante string c&arácter
_UI_RADIO_HEX=Constante &hexadecimal
_UI_RADIO_HOST_VARIABLE_NAME=Nombre de &variable de host
_UI_RADIO_GRAPHIC=Constante string &gráfico
_UI_LABEL_PREVIEW_CONSTANT_EXPRESSION=Vista previa de expresión constante:

!expressionbuilder/function/FunctionExpressionDialog.java
_UI_WIZARD_FUNCTION_EXPRESSION_TITLE=Compilador de expresiones de función

!ExpressionBuilder/MainExpressionPage.java
_UI_WIZARD_MAIN_EXPRESSION_TITLE=Compilador de expresiones
_UI_WIZARD_MAIN_EXPRESSION_HEADING=Tipos de expresión
_UI_WIZARD_MAIN_EXPRESSION_EXPL=Seleccionar el tipo de expresión a compilar.
_UI_RADIO_FUNCTION=&Función

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_RADIO_CASE=&CASE: buscada o simple

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_RADIO_CAST=C&AST

_UI_RADIO_CONSTANT=C&onstante: numérica, string o variable de host
_UI_RADIO_SUBQUERY=&Subconsulta
_UI_RADIO_OPERATORS=Com&pilar expresiones mediante operadores
_UI_COLUMN_EXPRESSION=Expresión
_UI_COLUMN_OPERATOR=Operador
_UI_COLUMN_PARAMETER=Parámetro
_UI_COLUMN_VALUE=Valor

!expressionbuilder/multiexpr/ExpressionsByOperatorsWizard.java
_UI_WIZARD_EXPRESSION_BY_OPERATOR_TITLE=Compilar expresiones mediante operadores
_UI_WIZARD_EXPRESSION_BY_OPERATOR_HEADING=Expresiones mediante operadores
_UI_WIZARD_EXPRESSION_BY_OPERATOR_EXPL=Compilar expresiones más grandes mediante los operadores que se proporcionan.
_UI_LABEL_BUILD_LEFT_OP_RIGHT=Com&pilar expresiones a la izquierda y seleccionar operadores a la derecha:
_UI_LABEL_PREVIEW_EXPRESSION=Vista previa de expresión:

!expressionbuilder/subquery/SubQueryPage.java
_UI_WIZARD_SUBQUERY_HEADING=Subconsulta
_UI_WIZARD_SUBQUERY_EXPL=Seleccionar una subconsulta.
_UI_LABEL_CHOICES=Selecciones disponibles:
_UI_RADIO_EXISTING_STATEMENTS=Crear una subconsulta basada en una consulta &existente
_UI_RADIO_SCRATCH_SELECT=Crear una &subconsulta original
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following 2 lines
_UI_LABEL_EXISTING_SELECT=C&rear o editar una sentencia SELECT:
_UI_LABEL_NEW_SELECT_INFO=Escribir una sen&tencia SELECT. Puede especificar una tabla virtual.

!views/CustomSashForm.java
_UI_TOOLTIP_RESTORE_PANE=Restaurar panel
_UI_TOOLTIP_HIDE_PANE=Ocultar panel


!preferences/SQLBuilderPreferencePage.java
_UI_PREFERENCES_OMIT_SCHEMA_DESC=Valores predeterminados de los ajustes Omitir esquema actual asociados con sentencias SQL
_UI_PREFERENCES_OMIT_SCHEMA_IN_SQL=&Omitir esquema actual en sentencias SQL generadas
_UI_PREFERENCES_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Esquema actual
_UI_PREFERENCES_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=ID de a&utorización
_UI_PREFERENCES_OMIT_SCHEMA_SCHEMA_NAME=Nombre de e&squema:

!dialogs/ChangeStatementTypeDialog
_UI_DIALOG_CHANGE_STATEMENT_TYPE_TITLE=Cambiar tipo de sentencia SQL
_UI_DIALOG_CHANGE_STATEMENT_TYPE_NOTE=Cambiar el tipo de sentencia SQL provocará que la sentencia actual sea reemplazada por una nueva sentencia vacía.
_UI_DIALOG_CHANGE_STATEMENT_TYPE_GROUP_TITLE=Tipo de sentencia

!dialogs/ChangeSetOperatorDialog
_UI_DIALOG_CHANGE_SET_OPERATOR_TITLE=Cambiar operador Set 
_UI_DIALOG_CHANGE_SET_OPERATOR_GROUP_TITLE=Operador Set


!dialogs/OmitCurrentSchemaDialog
_UI_DIALOG_OMIT_SCHEMA_TITLE=Omitir esquema actual
_UI_DIALOG_OMIT_SCHEMA_IN_SQL=&Omitir esquema actual en sentencias SQL generadas
_UI_DIALOG_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Esquema actual
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_USER_AS_CURRENT_SCHEMA=ID de &autorización <{0}>
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=ID de &autorización
_UI_DIALOG_OMIT_SCHEMA_SCHEMA_NAME=Nombre de e&squema:

!views/execute/ParameterWizards.java
_UI_WIZARD_SPECIFY_VARIABLE_VALUES_TITLE=Especificar valores de variables

!views/execute/ParameterWizardDialog.java
_UI_WIZARD_PARAMETER_MARKERS_TITLE=Marcadores de parámetros

!views/execute/ParameterMarkerPage.java
_UI_WIZARD_PARAMETER_MARKER_TITLE=Sustituir variables
_UI_WIZARD_PARAMETER_MARKER_HEADING=Valores de variables de host
_UI_WIZARD_PARAMETER_MARKER_EXPL=Especificar los valores de variables a utilizar

!views/execute/ParameterTableViewer.java
_UI_COLUMN_MARKER_NAME=Nombre
_UI_COLUMN_TYPE=Tipo
_UI_COLUMN_PARAMETER_VALUE=Valor


!views/AddTableDialog.java
_UI_LABEL_TABLE_NAME            = &Nombre de tabla:
_UI_DIALOG_REPLACE_TABLE_TITLE  = Reemplazar tabla
_UI_DIALOG_ADD_TABLE_TITLE      = Añadir tabla
_UI_LABEL_TABLE_ALIAS           = &Alias de tabla:
_UI_DIALOG_TABLE_ALREADY_ADDED  = Tabla ya añadida: especificar alias
_UI_DIALOG_ADD_VIEW_TO_SELF     = No se puede añadir vista a definición propia


!views/GridViewer.java
_UI_COLUMN_DEFAULT_COLUMN=Columna

!views/insert/InsertGridViewer.java
_UI_COLUMN_INSERT_VALUE=Valor

!views/criteria/CriteriaGridViewer.java
_UI_COLUMN_COLUMN=Columna
_UI_COLUMN_CRITERIA_OPERATOR=Operador
_UI_COLUMN_CRITERIA_VALUE=Valor

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_COLUMN_CRTIERIA_AND_OR=AND/OR

!views/criteria/CriteriaValueExpression.java
_UI_ACTION_UPDATE_VALUE_EXPRESSON=Act&ualizar expresión de valor
_UI_ACTION_REMOVE_CONDITION=Quita&r condición
_UI_MENU_EXECUTE= Ejecuta&r SQL

!views/fullselect/FullSelectViewer.java
!! NOTE TO TRANSLATOR: Do not translate VALUES in the following entry, since it is a SQL keyword
_UI_LABEL_FULL_SELECT_VALUES_HELP=Para añadir una fila de valores, hacer clic con el botón derecho en VALUES en la vista de contorno.

!views/fullselect/ValuesRowViewer.java
_UI_COLUMN_VALUES_ROW_ITEM=Elemento de fila de valores
_UI_ACTION_REMOVE_VALUES_ROW=Quita&r elemento

!views/fullselect/FullSelectGridViewer.java
_UI_COLUMN_STATEMENT=Sentencia
_UI_COLUMN_FULL_SELECT_OPERATOR=Operador

!views/graph/editparts/TableEditPart.java
_UI_ACTION_UPDATE_ALIAS=Act&ualizar alias...
_UI_DIALOG_CHANGE_ALIAS_TITLE=Cambiar alias de tabla
_UI_DIALOG_CHANGE_ALIAS_TEXT=Nu&evo alias:
_UI_ACTION_CREATE_JOIN=Crear &combinación...
_UI_ACTION_REMOVE_TABLE_EDIT=Eli&minar tabla


!views/graph/GraphContextMenuProvider.java:
_UI_ACTION_REMOVE_JOIN=Elimina&r combinación

!views/graph/SourceTargetDialog.java
_UI_DIALOG_SOURCE_AND_TARGET_TITLE=Crear combinación
_UI_DIALOG_SOURCE_AND_TARGET_TEXT=Seleccionar columnas fuente y destino para la combinación.
_UI_LABEL_JOIN_SRCCOL_TYPE = Tipo de columna fuente:
_UI_LABEL_JOIN_TGTCOL_TYPE = Tipo de columna destino:

_UI_GROUP_SOURCE=Fuente
_UI_LABEL_TABLE=&Tabla (alias)
_UI_LABEL_COLUMN=&Columna
_UI_GROUP_TARGET=Destino
_UI_LABEL_TARGET_TABLE=T&abla (alias)
_UI_LABEL_TARGET_COLUMN=C&olumna

_UI_GRAPH_PROMPT = Para añadir una tabla, hacer clic con el botón derecho en este panel y usar el menú emergente.
_UI_GRAPH_PARSE_FAILED = Esta sintaxis de SQL no es válida o no se admite actualmente. \
Puede entrar en SQL manualmente. Se han desactivado algunas funciones del compilador de SQL. \
Para activar esas funciones, cambie la sintaxis.\n\nPara deshacer los últimos cambios, \
seleccione Volver a la última fuente correcta en el menú de SQL.
_UI_GRAPH_NO_TABLE_FOUND = No es posible encontrar la tabla {0}. Puede que no exista o que esté filtrada. \
Se han desactivado algunas funciones del compilador de SQL. \
Para activar esas funciones, cambie la sintaxis y guarde la sentencia.\n\nPara deshacer los últimos cambios, \
seleccione Volver a la última fuente correcta en el menú de SQL.
_UI_GRAPH_NO_COLUMN_FOUND = No es posible encontrar la columna {0}. Se han desactivado algunas funciones del compilador de SQL. \
Para activar esas funciones, cambie la sintaxis y guarde la sentencia.\n\nPara deshacer los últimos cambios, \
seleccione Volver a la última fuente correcta en el menú de SQL.

!views/inster/InsertTypeViewer.java
_UI_GROUP_INSERT_ROWS=Insertar filas de:
_UI_RADIO_VALUES=Valores
_UI_RADIO_INSERT_FROM_SUBQUERY=Subconsulta
_UI_ACTION_REMOVE_COLUMN=Quita&r columna

!views/insert/InsertSelectViewer.java
_UI_LABEL_QUERY_NAME=Nombre de consulta:

!views/select/GroupByContentViewer.java
_UI_LABEL_GROUPS_TYPE=Tipo:
_UI_COMBOBOXITEM_GROUPING_ROOT=Raíz de agrupación
_UI_ACTION_REMOVE=Quita&r
_UI_NONE=Ninguno
_UI_SIMPLE=Simple

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_CUBE=CUBE

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_ROLLUP=ROLLUP

_UI_GROUPING=Agrupación
_UI_GROUPINGSETS=Conjuntos de agrupación

! views/select/SelectGridViewer.java:
!
_UI_COMBO_SORT_UNSORTED   = Sin orden
_UI_COMBO_SORT_ASCENDING  = Ascendente
_UI_COMBO_SORT_DESCENDING = Descendente
_UI_COMBO_SORT_DEFAULT = Predeterminado

!
!views/select/RemoveSelectColumnsAction.java
!
_UI_ACTION_REMOVE_SELECT_COLUMN = Quitar expresión de &columna

!
!views/select/RemoveOrderByExpressionAction.java
!
_UI_ACTION_REMOVE_ORDER_BY_EXPRESSION = Quitar &orden por expresión

!
! views/select/SelectGridViewer.java
!
_UI_COLUMN_SELECT_ALIAS      = Alias
_UI_COLUMN_SELECT_OUTPUT     = Salida
_UI_COLUMN_SELECT_SORT_TYPE  = Clase de clasificación
_UI_COLUMN_SELECT_SORT_ORDER = Orden

!
! views/select/SelectViewer.java
!
_UI_WORKBOOKPAGE_COLUMNS          = Columnas
_UI_WORKBOOKPAGE_CONDITIONS       = Condiciones
_UI_WORKBOOKPAGE_GROUPS           = Grupos
_UI_WORKBOOKPAGE_GROUP_CONDITIONS = Agrupar condiciones

!
! views/SQLBuilderActionBarContributor.java
!
_UI_TOOLTIP_EXECUTE_SQL = Ejecutar la sentencia SQL
_UI_MENU_SQLBUILDER     = &SQL

!
! views/source/SQLSourceViewer.java & SQLSourceParser
!
!! NOTE TO TRANSLATOR: Do not translate the following four lines
_UI_INSERT                   = INSERT
_UI_UPDATE                   = UPDATE
_UI_DELETE                   = DELETE
_UI_SELECT                   = SELECT

_UI_PARSE_ERROR_ENCOUNTERED  = Se ha encontrado un error de analizador.


!
! views/StatementNameViewer.java
!
_UI_LABEL_STATEMENT = Sentencia:


!
! Join stuff - DefineJoinDialog.java, DefineJoinTypeDialog.java
!
_UI_DEFINE_JOIN_DIALOG_TITLE = Especificar combinación
_UI_DEFINE_JOIN_DIALOG_INSTR = Tipo de combinación
_UI_RADIO_INNER_JOIN         = Combinación &interna
_UI_RADIO_LEFT_OUTER_JOIN    = Combinación externa &izquierda
_UI_RADIO_RIGHT_OUTER_JOIN   = Combinación externa &derecha
_UI_RADIO_FULL_OUTER_JOIN    = Combinación externa &completa
_UI_ACTION_SPECIFY_JOIN_TYPE = E&specificar tipo de combinación...
_UI_MSG_INVALID_JOIN_TITLE = Tipos incompatibles

!
!views/update/UpdateDesignViewer.java
!
_UI_TOOLTIP_UPDATE_ADD_COL = Añadir columna individual a sentencia
_UI_TOOLTIP_UPDATE_ADD_GRP = Añadir columnas a sentencia como grupo

!
!views/with/WithTableViewer.java
!
_UI_GROUP_WITH_TABLE     = Tabla
_UI_GROUP_WITH_COLUMN    = Columna
_UI_BUTTON_ADD_RIGHT     = Añadir >>
_UI_BUTTON_REMOVE_LEFT   = << Quitar

!
! views/with/WithStatementViewer
!
_UI_LABEL_WITH_STATEMENT  = Nombre de sentencia:

! CreateWithTableAction.java

!! NOTE TO TRANSLATOR: Do not translate "WithTable%1" in the following line
_UI_WITH_TABLE_NAME		  = WithTable%1
!
! SQLPreferencePage.java
!
_UI_VALIDATE_PREFERENCE_LABEL = &Validar sentencias de consulta mediante ejecución antes de guardar
_UI_ERROR_VALUE_GREATER_THAN_0 = Este valor debe ser un entero mayor que cero.

!
!views/SQLBuilder.java
!
_UI_VALIDATE_FAILED_TITLE    = Error de validación
_UI_CONTINUE_WITH_SAVE       = ¿Continuar guardando?
_UI_VALIDATING_STATEMENT     = Validando sentencia...
_UI_OBTAINING_CONNECTION     = Obteniendo conexión...
_UI_VALIDATE_DONE            = Validación completada...
_UI_SAVING_STATEMENT         = Guardando sentencia...

!model/SQLBuilderConstants.java:
_UI_BUILD_EXPRESSION   = Compilar expresión...
_UI_EDIT_EXPRESSION    = Editar expresión...
_UI_REPLACE_EXPRESSION = Reemplazar expresión...
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_ADD_SELECT         = Añadir sentencia SELECT...
_UI_ADD_FULLSELECT     = Añadir sentencia FULLSELECT...
_UI_ADD_WITH           = Añadir sentencia WITH...
_UI_ADD_VALUES         = Añadir valores
_UI_SPECIFY_VALUE	   = Especificar valor...
_UI_SPECIFY_VALUE_TITLE	   = Especificar valor


!========================================================================================
!
! Here is the list of Warning string that have message IDs - make sure they are unique
!
!========================================================================================
_WARN_MESSAGES_ENCOUNTERED      = Se han encontrado mensajes de advertencia
_WARN_DATA_WAS_TRUNCATED        = Se han truncado los datos
_WARN_SQL_WARNINGS_FOUND        = Se han encontrado advertencias de SQL

_WARN_BAD_JOIN_1                = Tipos de combinación no compatibles
_WARN_INVALID_JOIN              = Combinación no válida
_WARN_COLUMN_USED               = La columna ya se había utilizado en una combinación entre tablas

! Usage:
!   {0} replaced with the column name and {1} replaced with the column datatype
!
_WARN_BAD_JOIN_TYPES               = El tipo de la columna {0} es {1}


!======================================================================================
!
! Here is the list of Error string that have message IDs - make sure they are unique
!
!======================================================================================

_ERROR_DIALOG_TITLE_EXPR_EDIT_FAILED = Error al editar expresión
_ERROR_DIALOG_MSG_REBUILD_EXPR       = La expresión se debe volver a compilar

_ERROR_TABLE_USED                    = Seleccionar una tabla única o introducir un alias.
_ERROR_ALIAS_USED                    = Introducir un alias único.

_ERROR_ALIAS_NOT_UNIQUE_TEXT         = El alias no es único


_EXC_OPEN_SQL_FILE_RESOURCE          = Se ha producido un error al abrir el recurso del archivo SQL de entrada
_EXC_OPEN_SQL_FILE_NOT_CONNECTED     = Debe conectarse a la base de datos "{0}" antes de abrir el archivo SQL en el compilador de consultas SQL.

!! NOTE TO TRANSLATOR: Do not translate "ISQLBuilderEditorInput" in the following line
_EXC_INPUT_NOT_ISQLBUILDEREDITORINPUT = La entrada no es una ISQLBuilderEditorInput

_ERROR_ALIAS_NOT_ALPHANUMERIC        = Todos los caracteres del alias deben ser alfanuméricos.
_ERROR_ALIAS_TABLE_USED              = El alias no debe ser un nombre de tabla de base de datos.
_ERROR_ENTER_ALIAS                   = El nombre de tabla está en uso. Introduzca un alias.

_ERROR_DATABASE_NOT_AVAILABLE        = No hay disponible una conexión con base de datos
_ERROR_INPUT_NOT_RECOGNIZED          = No se admite el tipo de entrada del editor
_ERROR_OPEN_SQL_STORAGE_RESOURCE     = Se ha producido un error al abrir el recurso de almacenamiento de SQL de entrada
_ERROR_OPEN_SQL_STRING_RESOURCE      = Se ha producido un error al abrir la entrada
_ERROR_OPEN_INPUT_PARSE_FAILED       = No se puede analizar el SQL porque no es válido o no se admite actualmente.
_QUESTION_TITLE_OPEN_INPUT_PARSE_FAILED    = Error al analizar el compilador de consultas SQL
_QUESTION_MESSAGE_OPEN_INPUT_PARSE_FAILED    = Se creará una sentencia SQL vacía en el compilador de consultas SQL.

!
!model/SQLDomainModel.java
!
!note we reuse messages from ErrorMessages.java in org.eclipse.ui.texteditor.ErrorMessages

Editor_error_save_title=Problemas al guardar
Editor_error_save_message=No se ha podido finalizar Guardar.
Editor_error_save_readonly=\n\nCausa:\nNo se ha podido escribir en un archivo de sólo lectura:
Editor_error_save_failed=\n\nCausa:\nNo se ha podido escribir en un archivo:

!Strings from B2BGUI properties file
_UI_ERROR_CREATING_FILE_TITLE = Error al crear el archivo
_UI_ERROR_CREATING_FILE_SHORT_DESC = Error al crear el archivo "{0}"
_UI_ERROR_CREATING_FILE_LONG_DESC = Se ha producido un error al intentar crear el archivo "{0}".
_UI_PARENT_FOLDER_IS_READ_ONLY = El directorio principal "{0}" es de sólo lectura.
_UI_UNKNOWN_ERROR_WITH_HINT = Error desconocido. Asegúrese de que se puede escribir en el directorio principal "{0}".
_UI_UNKNOWN_ERROR = Error desconocido. Asegúrese de que se puede escribir en el directorio principal "{0}".
! TextViewerOperationAction
_UI_MENU_COPY         = &Copiar
_UI_MENU_CUT          = Cor&tar
_UI_MENU_DELETE       = Eliminar
_UI_MENU_PASTE        = &Pegar
_UI_MENU_PREFIX       = Prefijo
_UI_MENU_REDO         = Rehacer
_UI_MENU_SELECT_ALL   = Seleccionar todo
_UI_MENU_SHIFT_LEFT   = Mayús izquierda
_UI_MENU_SHIFT_RIGHT  = Mayús derecha
_UI_MENU_STRIP_PREFIX = Eliminar prefijo
_UI_MENU_UNDO         = Deshacer

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = Abrir Editor SQL
datatools_sqlbuilder_sqleditor_title = Editor &SQL

! SQL Query Builder
datatools_sqlbuilder_sqlbuilder_DML_error = Error
datatools_sqlbuilder_sqlbuilder_multipleDML = El compilador de SQL sólo se puede utilizar para crear una única \
sentencia SQL DML. El archivo {0} no contiene una única sentencia DML. ¿Abrir archivo mediante el editor SQL?
datatools_sqlbuilder_sqlbuilder_multipleDML_VE = Visual Explain sólo se puede utilizar para una única \
sentencia SQL DML. El archivo {0} no contiene una única sentencia DML.
datatools_sqlbuilder_sqlbuilder_unsupport_VE = Esta conexión de base de datos no es compatible con Visual Explain.
!Clear to Skeleton and Revert to Last Correct
_UI_CLEAR_TO_TEMPLATE 			     = Borrar en plantilla
_UI_REVERT_TO_LAST_CORRECT_SOURCE    = Volver a la última fuente correcta
_UI_LAST_CORRECT_SOURCE 			 = ¿Última fuente correcta?
!Change Statement Type
_UI_CHANGE_STATEMENT_TYPE			= Cambiar tipo de sentencia...
!Omit Current Schema
_UI_OMIT_CURRENT_SCHEMA              = Omitir esquema actual... 

!
! views/execute/ExecuteViewer.java & views/execute/QueryOutputHelper.java
!
_UI_DIALOG_EXECUTE_SQL_TITLE = Ejecutar sentencia SQL
_UI_BUTTON_EXECUTE_CLOSE     = &Cerrar
_UI_LABEL_SQL_STATEMENT      = Sentencia &SQL:
_UI_BUTTON_EXECUTE           = Ejecuta&r
_UI_LABEL_QUERY_RESULTS      = Resultados de consulta:
_UI_MONITOR_EXECUTING_QUERY  = Ejecutando sentencia SQL...
_UI_LABEL_NO_CONNECTION      = La conexión con la base de datos no está disponible o el modelo del esquema de la base de datos relacional está dañado.
_UI_LABEL_NO_CONNECTION_FILE = La conexión con la base de datos no está disponible porque falta el archivo xmi de conexión.

_UI_DIALOG_WARNING_TITLE       = Advertencia
_UI_DIALOG_OP_FAILED_TITLE     = Error de la operación
_UI_LABEL_EXECUTION_SUCCESSFUL = La sentencia se ejecutó correctamente, pero no produjo resultados que mostrar.
!! NOTE TO TRANSLATOR: the MAX_RECORD_EXCEEDED string should match
!! the strings for RECORD_RETURNED and RECORD_DISPLAYED.
_UI_MSG_MAX_RECORD_EXCEEDED    = Se han devuelto más de 1000 registros. 1000 registros mostrados.
_UI_MSG_RECORD_RETURNED        = registros devueltos.


! SQL Statement validation errors
! usage note: %1 will be replaced with a SQL statement name
_ERROR_STATEMENT_NAME_EXISTS         = Ya existe una sentencia de nombre %1
_ERROR_INVALID_STATEMENT_NAME = Introduzca un nombre de sentencia válido.
! usage note: %1 is replaced with the invalid character entered by the user
_ERROR_INVALID_CHAR_IN_STATEMENT_NAME = El nombre de sentencia no puede contener el carácter: %1
_ERROR_STATEMENT_NAME_TOO_LONG = El nombre de sentencia no puede superar los 160 caracteres.


! SelectDBTablePage resources
datatools_selectDBTablePage_statements = Sentencias

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Nuevo...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Nueva sentencia SQL...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Crear una nueva sentencia de consulta
datatools_sqlbuilder_sqlstatement_actions_openwith = Abrir con
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = Compilador de consultas SQL
datatools_sqlbuilder_sqlstatement_actions_sqleditor = Editor SQL

!
! New SQL statement wizard, dialog, and page
!
datatools_sqlbuilder_newStatementWizard_title = Nueva sentencia SQL
datatools_sqlbuilder_newStatementWizard_description = Crea una sentencia SQL.
datatools_sqlbuilder_newStatementDialog_title = Nueva sentencia SQL
datatools_sqlbuilder_newStatementPage_title = Tipo de sentencia
datatools_sqlbuilder_newStatementPage_description = Dar nombre y seleccionar el tipo de plantilla para esta sentencia.
datatools_sqlbuilder_newStatementPage_statementID = Identificación de sentencia
datatools_sqlbuilder_newStatementPage_statementName = Nombre de &sentencia:
datatools_sqlbuilder_newStatementPage_statementType = Plan&tilla de sentencia:
datatools_sqlbuilder_newStatementPage_editUsing = Editar utilizando
datatools_sqlbuilder_newStatementPage_sqlQueryBuilder = Compilador de S&QL
datatools_sqlbuilder_newStatementPage_sqlEditor = &Editor SQL
datatools_sqlbuilder_newStatementPage_sampleStatements = Sentencias de muestra
datatools_sqlbuilder_newStatementPage_none = Ninguno
!
! Project selection page, for new SQL statement wizard
!
datatools_sqlbuilder_projectPage_title = Seleccionar proyecto
datatools_sqlbuilder_projectPage_description = Seleccionar un proyecto existente o añadir uno nuevo para esta sentencia.

!
! Generated comment text for template SQL for New SQL Statement action
!
_UI_SAMPLE_DML_TEMPLATE_STATEMENTS = Sentencias de plantilla DML de muestra
_UI_SAMPLE_DDL_TEMPLATE_STATEMENTS = Sentencias de plantilla DDL de muestra

!
! String for the AddTable With Table
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_AVAILABLE_TABLES_TREE_PROVIDER = Tablas WITH

!actions/ConvertToFullSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" and "UNION" in the following line
_UI_ACTION_CONVERT_TO_FULL_SELECT=&Convertir a FULLSELECT (UNION)


! org.eclipse.datatools.sqltools.sqlbuilder.views.fullselect/fullselectElement.java
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_VIEWS_FULLSELECTELEMENT_FULLSELECT = Sentencia FULLSELECT
_UI_VIEWS_FULLSELECTELEMENT_SELECT = Sentencia SELECT
_UI_VIEWS_FULLSELECTELEMENT_VALUES = VALUES

! org.eclipse.datatools.sqltools.sqlbuilder.views.graph/GraphContextMenuProvider.java
_UI_VIEWS_GRAPH_SELECT_ALL_COLUMN = Seleccionar todas las columnas
_UI_VIEWS_GRAPH_DESELECT_ALL_COLUMN = Anular la selección de todas las columnas

!SQLQueryBuilder Dialog
_UI_SQLQUERYBUILDERDIALOG_NAME = Compilador de consultas SQL
SQLQueryBuilderDialogEditTabName=Editar
SQLQueryBuilderDialogNoInput=No se pasó una entrada para abrir a SQLBuilder Dialog.
SQLQueryBuilderDialogParseFailOnOpenAskUserTitle=Compilador de consultas SQL
SQLQueryBuilderDialogParseFailOnOpenAskUserMessage=Si continúa, se creará una sentencia SQL vacía en el compilador de consultas SQL. ¿Desea continuar?
SQLQueryBuilderDialogResultsTabName=Resultados de SQL


# plugin.xml.  preference page extension point
_UI_SQLQUERY_NAME = Consulta SQL

## Resources for the standard editor actions

ContentAssistProposal_label       =Ayuda de co&ntenido@Ctrl+ESPACIO
ContentAssistProposal_tooltip     =Ayuda de contenido
ContentAssistProposal_image       =
ContentAssistProposal_description =Ayuda de contenido

ContentTip_label       =Sugerencia de contenido@Ctrl+MAYÚS+ESPACIO
ContentTip_tooltip     =Sugerencia de contenido
ContentTip_image       =
ContentTip_description =Sugerencia de contenido

## Resources for other SQL Query Builder actions

datatools_sqlbuilder_RunSQLAction_label       = Ejecuta&r SQL
datatools_sqlbuilder_RunSQLAction_tooltip     = Ejecutar la sentencia SQL
datatools_sqlbuilder_RunSQLAction_image       =
datatools_sqlbuilder_RunSQLAction_description =

datatools_sqlbuilder_RevertToPreviousAction_label       = Volver a la última fuente correcta
datatools_sqlbuilder_RevertToPreviousAction_tooltip     =
datatools_sqlbuilder_RevertToPreviousAction_image       =
datatools_sqlbuilder_RevertToPreviousAction_description =

datatools_sqlbuilder_RevertToDefaultAction_label       = Borrar en plantilla
datatools_sqlbuilder_RevertToDefaultAction_tooltip     =
datatools_sqlbuilder_RevertToDefaultAction_image       =
datatools_sqlbuilder_RevertToDefaultAction_description =

datatools_sqlbuilder_ChangeStatementTypeAction_label   = Cambiar tipo de sentencia...
datatools_sqlbuilder_ChangeStatementTypeAction_tooltip     =
datatools_sqlbuilder_ChangeStatementTypeAction_image       =
datatools_sqlbuilder_ChangeStatementTypeAction_description =

datatools_sqlbuilder_OmitCurrentSchemaAction_label       = Omitir esquema actual...
datatools_sqlbuilder_OmitCurrentSchemaAction_tooltip     =
datatools_sqlbuilder_OmitCurrentSchemaAction_image       =
datatools_sqlbuilder_OmitCurrentSchemaAction_description =

!RDBTableDropListener
_UI_INVALID_TABLE_ADDED = Si la base de datos no está asociada con el proyecto, no puede añadir tablas de base de datos a una sentencia.

## Resources for utilities

VIEW_UTILITY_DEFAULT_FONT_UI_ = MS Sans Serif
STRING_MATCH_EXPECTED_EXCEPTION_MESSAGE = Se esperaba: 
STRING_MATCH_RETURNED_EXCEPTION_MESSAGE =  Se ha devuelto:
