# NLS_MESSAGEFORMAT_VAR          needed to handle quotes correctly
#
# Copyright (c) 2002, 2009. All Rights Reserved IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which is available at
# http://www.eclipse.org/legal/epl-v10.html
#  
# Contributors:
#     IBM Corporation - initial API and implementation
#
# Properties file for component:  SQLQ - SQL builder

! Please do not translate following strings  in this file (appears exactly, case sensitive) :
! WITH
! SQL
! SELECT
! FULLSELECT
! UNION
! CASE
! CAST

!
! views/update/RemoveUpdateColumnAction.java
!
_UI_ACTION_REMOVE_UPDATE_COLUMN = Supprimer la &colonne

!
! views/update/UpdateTreeElement.java
!
_UI_COLUMN_UPDATE_GROUP = Mettre à jour le groupe

!
! views/update/UpdateTreeViewer.java
!
_UI_COLUMN_UPDATE_COLUMN     = Mettre à jour la colonne
_UI_COLUMN_UPDATE_EXPRESSION = Expression

!
!views/update/UpdateViewer.java
!
_UI_WORKBOOK_SET    = Définir
_UI_WORKBOOK_WHERE  = Où


!
! Actions
!
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_ACTION_ADD_TABLE          = &Ajouter une table...
_UI_ACTION_ADD_TABLE_REPLACE  = R&emplacer une table...
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" in the following line
_UI_ACTION_ADD_FULLSELECT     = Ajouter une instruction &FULLSELECT
_UI_ACTION_REMOVE_TABLE       = Suppri&mer une table...

!actions/ChangeStatementTypeAction
_UI_ACTION_CHANGE_STATEMENT_TYPE		= &Modifier le type d'instruction...

!actions/ChangeSetOperatorAction
_UI_ACTION_CHANGE_SET_OPERATOR		= Change &Set Operator...

!actions/OmitCurrentSchemaAction
_UI_ACTION_OMIT_CURRENT_SCHEMA		= Ign&orer le schéma actuel...

!actions/AddValueRowAction
_UI_ACTION_ADD_VALUE_ROW=Ajouter une ligne de valeu&rs

!actions/AddValuesAction.java
_UI_ACTION_ADD_VALUES=Ajouter des &valeurs

!actions/AddSubSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following line
_UI_ACTION_ADD_SELECT=Ajouter une instruction &SELECT

!actions/CreateWithTableAction.java
_UI_ACTION_ADD_COMMON_TABLE=&Ajouter une expression de table commune (WITH)

!actions/DeleteStatementAction.java
_UI_ACTION_DELETE_STATEMENT=&Supprimer

!expressionbuilder/actions/DeleteExpressionAction.java
_UI_ACTION_DELETE_EXPRESSION=Supp&rimer l'expression

!expressionbuilder/actions/DeleteCaseClauseAction.java
_UI_ACTION_DELETE_CLAUSE=Supp&rimer la clause

!expressionbuilder/actions/DeleteFunctionParameterAction.java
_UI_ACTION_DELETE_PARAMETER=Supp&rimer le paramètre

!expressionbuilder/case/CastExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_WIZARD_CAST_EXPRESSION_TITLE=Générateur d'expression CAST

!expressionbuilder/caseexpr/CaseSimplePage.java
_UI_COMBO_ADDFUNCTION=Générer une expression de fonction...

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_COMBO_ADDCASE=Générer une expression CASE...
!! NOTE TO TRANSLATOR: Do not translate "CAST" in the following line
_UI_COMBO_ADDCAST=Générer une expression CAST...
_UI_COMBO_ADDCONSTANT=Générer une expression de constante
_UI_COMBO_SELECTSUBQUERY=Sélectionner une sous-requête...
_UI_COMBO_ADDEXPRBYOPERATOR=Générer une expression à l'aide d'opérateurs...
_UI_WIZARD_CASE_SIMPLE_TITLE=Expression CASE simple
_UI_WIZARD_CASE_SIMPLE_HEADING=Générer une expression CASE simple
!! NOTE TO TRANSLATOR: Do not translate "WHEN-THEN" and "ELSE" in the following line
_UI_LABEL_BUILD_WHEN_CLAUSE=Générer des cla&uses WHEN-THEN, ajouter une clause ELSE, ou les deux.
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_CHECKBOX_ADD_ELSE=Ajouter une clause &ELSE
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_BUTTON_ADD_WHEN=Ajouter une clause &WHEN
_UI_LABEL_EXPRESSION_PREVIEW=Aperçu de l'expression CASE :

!expressionbuilder/function/FunctionBuilderPage.java:

!expressionbuilder/caseexpr/CaseSearchTable.java
_UI_COLUMN_CASE_SEARCH_EXPRESSION=Expression
_UI_COLUMN_CASE_SEARCH_OPERATOR=Opérateur
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE_SEARCH=Supp&rimer une clause WHEN
_UI_ACTION_DELETE_SEARCH_CONDITION=Supp&rimer une condition de recherche
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION_SEARCH=Supp&rimer une expression ELSE

!expressionbuilder/caseexpr/CaseSearchPage.java
_UI_WIZARD_CASE_SEARCH_HEADING=Expression CASE recherchée
_UI_WIZARD_CASE_SEARCH_EXPR=Générer une expression CASE recherchée.

!expressionbuilder/caseexpr/CaseSimpleTable.java
_UI_COLUMN_CASE_EXPRESSION=Expression
_UI_COLUMN_RESULT_EXPRESSION=Expression de résultats
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_ACTION_DELETE_WHEN_CLAUSE=Supp&rimer une clause WHEN
!! NOTE TO TRANSLATOR: Do not translate "ELSE" in the following line
_UI_ACTION_DELETE_ELSE_EXPRESSION=Supp&rimer une expression ELSE

!expressionbuilder/...Signatures...
_UI_FCN_ALL=Tous
_UI_FCN_COLUMN=Colonne
_UI_FCN_SPECIAL_REG=Registres spéciaux
_UI_FCN_SCALAR=Scalaire
_UI_FCN_CONVERSION=Conversion
_UI_FCN_SECURITY=Sécurité
_UI_FCN_DATE_TIME=Date et heure
_UI_FCN_DATE=Date
_UI_FCN_DB2=DB2
_UI_FCN_LOGICAL=Logique
_UI_FCN_MATH=Math
_UI_FCN_BIT=Bit
_UI_FCN_NUMBER=Numéro
_UI_FCN_CHARACTER=Caractère
_UI_FCN_SUMMARY=Résumé
_UI_FCN_TEXT=Texte
_UI_FCN_SYSTEM=Système
_UI_FCN_STRING=Chaîne
_UI_FCN_AGGREGATE=Agrégat
_UI_FCN_MISCELLANEOUS_SINGLE_ROW=Ligne unique (divers)
_UI_FCN_MISCELLANEOUS=Divers
_UI_FCN_OBJECT_REFERENCE=Référence d'objet
_UI_FCN_CONTROL_FLOW=Flux de contrôle
_UI_FCN_TEXT_EXTENDERS=Extension Texte
_UI_FCN_AIV_EXTENDERS=Extensions Audio/Image/Vidéo
_UI_FCN_XMLFUNCTIONS=XML
_UI_FCN_NOT_SUPPORTED=NOT SUPPORTED
_UI_FCN_UDF=Fonctions définies par l'utilisateur (FDU)
_UI_FCN_DATALINK=Datalink
_UI_FCN_MQ_EXTENDER=File d'attente de messages (MQ)

!expressionbuilder/subquery/SubQueryWizard.java
_UI_WINDOW_TITLE_CHOICES=Choix des sous-requêtes

!expressionbuilder/function/FunctionBuilderPage.java
_UI_WIZARD_FUNCTION_BUILDER_HEADING=Générateur de fonction
_UI_WIZARD_FUNCTION_BUILDER_EXPL=Utiliser cette page pour générer une expression de fonction.
_UI_WIZARD_FUNCTION_BUILDER_INSTR_CAT=1. Sélectionnez une &catégorie de fonction :
_UI_WIZARD_FUNCTION_BUILDER_INSTR_FCN=2. Sélectionnez une f&onction :
_UI_WIZARD_FUNCTION_BUILDER_INSTR_SIG=3. Sélectionnez une &signature de fonction :
_UI_WIZARD_FUNCTION_BUILDER_INSTR_EXPR=4. Sélectionnez une &expression pour l'/les argument(s) :
_UI_WIZARD_FUNCTION_BUILDER_INSTR_PRE=5. Aperçu de l'expression de fonction :

!expressionbuilder/caseexpr/CaseExpressionDialog.java

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following 2 lines
_UI_WIZARD_CASE_OPTION_HEADING=Options CASE
_UI_WIZARD_CASE_OPTION_EXPL=Sélectionner le type d'expression CASE à générer.

_UI_GROUP_CASE_TYPE=Type CASE
!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SEARCHED_WHEN=Clau&se WHEN recherchée

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SEARCHED_WHEN = par exemple, CASE WHEN i>j THEN k END

!! NOTE TO TRANSLATOR: Do not translate "WHEN" in the following line
_UI_RADIO_SIMPLE_WHEN=Clause WHEN s&imple

!! NOTE TO TRANSLATOR: Translate only "for example," in the following line
_UI_TOOLTIP_SIMPLE_WHEN = par exemple, CASE i WHEN 8 THEN j END

!expressionbuilder/caseexpr/CaseExpressionDialog.java
!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_WIZARD_CASE_EXPRESSION_TITLE=Générateur d'expression CASE

!expressionbuilder/constant/ConstantExpressionWizard.java
!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_NUMERIC_CONSTANT=0123456789-+E.

!expressionbuilder/case/CaseBuilderPage.java
!! NOTE TO TRANSLATOR: Do not translate "CAST" where it occurs in the following 6 lines
_UI_WIZARD_CAST_BUILDER_TITLE=Générateur CAST
_UI_WIZARD_CAST_BUILDER_HEADING=Utiliser cette page pour générer une expression CAST.
!! NOTE TO TRANSLATOR: Do not translate "SCOPE" in the following line
_UI_LABEL_PREVIEW_CAST_EXPRESSION=Aperçu de l'expression CAST :
_UI_LABEL_DATATYPE_LENGTH=Longueur du type de données :

!expressionbuilder/constant/ConstantExpressionDialog.java
_UI_WIZARD_CONSTANT_TITLE=Générateur d'expression de constante

!expressionbuilder/constant/NumericConstantBuilderPage.java
_UI_WIZARD_NUMERIC_CONSTANT_TITLE=Générateur de constante numérique
_UI_WIZARD_NUMERIC_CONSTANT_HEADER=Générateur de constante numérique
_UI_WIZARD_NUMERIC_CONSTANT_EXPL=Cette page vous permet de générer une expression de constante numérique.
_UI_BUTTON_CLEAR=Effa&cer

!! NOTE TO TRANSLATOR: Do not translate the following 2 lines
_UI_BUTTON_FLOAT_TO_EXP=&F <-> E
_UI_BUTTON_PLUS_MINUS=+&/-

!expressionbuilder/constant/ConstantOptions.java
_UI_WIZARD_CONSTANT_OPTIONS_TITLE=Options de constante
_UI_WIZARD_CONSTANT_OPTIONS_HEADING=Options de constante
_UI_WIZARD_CONSTANT_OPTIONS_EXPL=Sélectionner le type d'expression de constante à générer.
_UI_GROUP_CONSTANT_TYPE=Type de constante
_UI_RADIO_NUMERIC=Constante n&umérique : entier, virgule flottante ou décimal
_UI_RADIO_STRING=Con&stante de chaîne : chaîne de caractères ou graphique, hexadécimale ou noms de variables hôtes

!expressionbuilder/constant/StringConstantBuilderPage.java
_UI_WIZARD_STRING_CONSTANT_TITLE=Générateur de constante de chaîne
_UI_WIZARD_STRING_CONSTANT_HEADING=Générateur de constante de chaîne
_UI_WIZARD_STRING_CONSTANT_EXPL=Cette page vous permet de générer une expression de constante de chaîne. Saisissez l'expression dans la zone de texte.
_UI_GROUP_STRING_TYPE=Type de constante de chaîne
_UI_RADIO_CHARACTER=Constante de chaîne de c&aractères
_UI_RADIO_HEX=Constante &hexadécimale
_UI_RADIO_HOST_VARIABLE_NAME=Nom de &variable hôte
_UI_RADIO_GRAPHIC=Constante de chaîne &graphique
_UI_LABEL_PREVIEW_CONSTANT_EXPRESSION=Aperçu de l'expression de constante :

!expressionbuilder/function/FunctionExpressionDialog.java
_UI_WIZARD_FUNCTION_EXPRESSION_TITLE=Générateur d'expression de fonction

!ExpressionBuilder/MainExpressionPage.java
_UI_WIZARD_MAIN_EXPRESSION_TITLE=Générateur d'expression
_UI_WIZARD_MAIN_EXPRESSION_HEADING=Types d'expression
_UI_WIZARD_MAIN_EXPRESSION_EXPL=Sélectionner le type d'expression à générer.
_UI_RADIO_FUNCTION=&Fonction :

!! NOTE TO TRANSLATOR: Do not translate "CASE" in the following line
_UI_RADIO_CASE=&CASE - recherchée ou simple

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_RADIO_CAST=C&AST

_UI_RADIO_CONSTANT=C&onstante - numérique, chaîne ou variable hôte
_UI_RADIO_SUBQUERY=&Sous-requête
_UI_RADIO_OPERATORS=Générer des expressions à l'aide d'opérate&urs
_UI_COLUMN_EXPRESSION=Expression
_UI_COLUMN_OPERATOR=Opérateur
_UI_COLUMN_PARAMETER=Paramètre
_UI_COLUMN_VALUE=Valeur

!expressionbuilder/multiexpr/ExpressionsByOperatorsWizard.java
_UI_WIZARD_EXPRESSION_BY_OPERATOR_TITLE=Générer des expressions à l'aide d'opérateurs
_UI_WIZARD_EXPRESSION_BY_OPERATOR_HEADING=Expressions à l'aide d'opérateurs
_UI_WIZARD_EXPRESSION_BY_OPERATOR_EXPL=Générer des expressions plus larges en utilisant les opérateurs fournis.
_UI_LABEL_BUILD_LEFT_OP_RIGHT=Générer des expressions sur la ga&uche et sélectionner des opérateurs sur la droite :
_UI_LABEL_PREVIEW_EXPRESSION=Aperçu de l'expression :

!expressionbuilder/subquery/SubQueryPage.java
_UI_WIZARD_SUBQUERY_HEADING=Sous-requête
_UI_WIZARD_SUBQUERY_EXPL=Sélectionner une sous-requête :
_UI_LABEL_CHOICES=Choix disponibles :
_UI_RADIO_EXISTING_STATEMENTS=Créer une sous-requête à partir d'une requête &existante
_UI_RADIO_SCRATCH_SELECT=Créer une &sous-requête originale
!! NOTE TO TRANSLATOR: Do not translate "SELECT" in the following 2 lines
_UI_LABEL_EXISTING_SELECT=C&réer ou modifier une instruction SELECT :
_UI_LABEL_NEW_SELECT_INFO=Saisir une ins&truction SELECT. Vous pouvez spécifier une table virtuelle.

!views/CustomSashForm.java
_UI_TOOLTIP_RESTORE_PANE=Restaurer le volet
_UI_TOOLTIP_HIDE_PANE=Masquer le volet


!preferences/SQLBuilderPreferencePage.java
_UI_PREFERENCES_OMIT_SCHEMA_DESC=Valeurs par défaut des paramètres Ignorer le schéma actuel associés aux instructions SQL
_UI_PREFERENCES_OMIT_SCHEMA_IN_SQL=Ign&orer le schéma actuel dans les instructions SQL générées
_UI_PREFERENCES_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Schéma actuel
_UI_PREFERENCES_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=ID &autorisation
_UI_PREFERENCES_OMIT_SCHEMA_SCHEMA_NAME=Nom du &schéma :

!dialogs/ChangeStatementTypeDialog
_UI_DIALOG_CHANGE_STATEMENT_TYPE_TITLE=Modifier le type d'instruction SQL
_UI_DIALOG_CHANGE_STATEMENT_TYPE_NOTE=La modification du type d'instruction SQL entraînera le remplacement de l'instruction actuelle par une nouvelle instruction vide.
_UI_DIALOG_CHANGE_STATEMENT_TYPE_GROUP_TITLE=Type d'instruction

!dialogs/ChangeSetOperatorDialog
_UI_DIALOG_CHANGE_SET_OPERATOR_TITLE=Change Set Operator 
_UI_DIALOG_CHANGE_SET_OPERATOR_GROUP_TITLE=Set Operator


!dialogs/OmitCurrentSchemaDialog
_UI_DIALOG_OMIT_SCHEMA_TITLE=Ignorer le schéma actuel
_UI_DIALOG_OMIT_SCHEMA_IN_SQL=Ign&orer le schéma actuel dans les instructions SQL générées
_UI_DIALOG_OMIT_SCHEMA_SPECIFY_SCHEMA_GROUP_TITLE=Schéma actuel
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_USER_AS_CURRENT_SCHEMA=ID &autorisation <{0}>
_UI_DIALOG_OMIT_SCHEMA_USE_AUID_AS_CURRENT_SCHEMA=ID &autorisation
_UI_DIALOG_OMIT_SCHEMA_SCHEMA_NAME=Nom du &schéma :

!views/execute/ParameterWizards.java
_UI_WIZARD_SPECIFY_VARIABLE_VALUES_TITLE=Spécifier les valeurs des variables

!views/execute/ParameterWizardDialog.java
_UI_WIZARD_PARAMETER_MARKERS_TITLE=Repères des paramètres

!views/execute/ParameterMarkerPage.java
_UI_WIZARD_PARAMETER_MARKER_TITLE=Remplacer des variables
_UI_WIZARD_PARAMETER_MARKER_HEADING=Valeurs des variables hôtes
_UI_WIZARD_PARAMETER_MARKER_EXPL=Spécifier les valeurs des variables à utiliser

!views/execute/ParameterTableViewer.java
_UI_COLUMN_MARKER_NAME=Nom
_UI_COLUMN_TYPE=Type
_UI_COLUMN_PARAMETER_VALUE=Valeur


!views/AddTableDialog.java
_UI_LABEL_TABLE_NAME            = &Nom de la table :
_UI_DIALOG_REPLACE_TABLE_TITLE  = Remplacer la table
_UI_DIALOG_ADD_TABLE_TITLE      = Ajouter une table
_UI_LABEL_TABLE_ALIAS           = Pseudo de la t&able :
_UI_DIALOG_TABLE_ALREADY_ADDED  = Table déjà ajoutée - Spécifier un pseudo
_UI_DIALOG_ADD_VIEW_TO_SELF     = Impossible d'ajouter la vue à sa propre définition


!views/GridViewer.java
_UI_COLUMN_DEFAULT_COLUMN=Colonne

!views/insert/InsertGridViewer.java
_UI_COLUMN_INSERT_VALUE=Valeur

!views/criteria/CriteriaGridViewer.java
_UI_COLUMN_COLUMN=Colonne
_UI_COLUMN_CRITERIA_OPERATOR=Opérateur
_UI_COLUMN_CRITERIA_VALUE=Valeur

!! NOTE TO TRANSLATOR: Do not translate the following line
_UI_COLUMN_CRTIERIA_AND_OR=AND/OR

!views/criteria/CriteriaValueExpression.java
_UI_ACTION_UPDATE_VALUE_EXPRESSON=Mettre à jo&ur l'expression de valeur
_UI_ACTION_REMOVE_CONDITION=Supp&rimer une condition
_UI_MENU_EXECUTE= Exécute&r SQL

!views/fullselect/FullSelectViewer.java
!! NOTE TO TRANSLATOR: Do not translate VALUES in the following entry, since it is a SQL keyword
_UI_LABEL_FULL_SELECT_VALUES_HELP=Pour ajouter une ligne de valeurs, cliquer droit sur VALUES dans la vue de contour.

!views/fullselect/ValuesRowViewer.java
_UI_COLUMN_VALUES_ROW_ITEM=Elément de la ligne de valeurs
_UI_ACTION_REMOVE_VALUES_ROW=Supp&rimer l'élément

!views/fullselect/FullSelectGridViewer.java
_UI_COLUMN_STATEMENT=Instruction
_UI_COLUMN_FULL_SELECT_OPERATOR=Opérateur

!views/graph/editparts/TableEditPart.java
_UI_ACTION_UPDATE_ALIAS=Mettre à jo&ur le pseudo...
_UI_DIALOG_CHANGE_ALIAS_TITLE=Modifier le pseudo de la table
_UI_DIALOG_CHANGE_ALIAS_TEXT=Nouv&eau pseudo :
_UI_ACTION_CREATE_JOIN=Créer une &liaison...
_UI_ACTION_REMOVE_TABLE_EDIT=Suppri&mer une table


!views/graph/GraphContextMenuProvider.java:
_UI_ACTION_REMOVE_JOIN=Supp&rimer une liaison

!views/graph/SourceTargetDialog.java
_UI_DIALOG_SOURCE_AND_TARGET_TITLE=Créer une liaison
_UI_DIALOG_SOURCE_AND_TARGET_TEXT=Sélectionner des colonnes source et cible pour la liaison.
_UI_LABEL_JOIN_SRCCOL_TYPE = Type de colonne source :
_UI_LABEL_JOIN_TGTCOL_TYPE = Type de colonne cible :

_UI_GROUP_SOURCE=Source
_UI_LABEL_TABLE=&Table (pseudo)
_UI_LABEL_COLUMN=&Colonne
_UI_GROUP_TARGET=Cible
_UI_LABEL_TARGET_TABLE=T&able (pseudo)
_UI_LABEL_TARGET_COLUMN=C&olonne

_UI_GRAPH_PROMPT = Pour ajouter une table, cliquer droit sur ce volet et utiliser le menu contextuel.
_UI_GRAPH_PARSE_FAILED = Cette syntaxe SQL est soit invalide soit actuellement non prise en charge. \
Vous pouvez saisir une requête SQL manuellement. Certaines fonctions de générateurs SQL ont été désactivées. \
Pour activer ces fonctions, modifiez la syntaxe.\n\nPour annuler de récentes modifications, \
sélectionnez Restaurer la dernière source correcte dans le menu SQL.
_UI_GRAPH_NO_TABLE_FOUND = Impossible de trouver la table {0}. Il se peut qu'elle n'existe pas ou qu'elle soit filtrée. \
Certaines fonctions de générateurs SQL ont été désactivées.\
Pour activer ces fonctions, modifiez la syntaxe et enregistrez l'instruction.\n\nPour annuler de récentes modifications, \
sélectionnez Restaurer la dernière source correcte dans le menu SQL.
_UI_GRAPH_NO_COLUMN_FOUND = Impossible de trouver la colonne {0}. Certaines fonctions de générateurs SQL ont été désactivées. \
Pour activer ces fonctions, modifiez la syntaxe et enregistrez l'instruction.\n\nPour annuler de récentes modifications, \
sélectionnez Restaurer la dernière source correcte dans le menu SQL.

!views/inster/InsertTypeViewer.java
_UI_GROUP_INSERT_ROWS=Insérer des lignes à partir de :
_UI_RADIO_VALUES=Valeurs
_UI_RADIO_INSERT_FROM_SUBQUERY=Sous-requête
_UI_ACTION_REMOVE_COLUMN=Supp&rimer une colonne

!views/insert/InsertSelectViewer.java
_UI_LABEL_QUERY_NAME=Nom de la requête :

!views/select/GroupByContentViewer.java
_UI_LABEL_GROUPS_TYPE=Type :
_UI_COMBOBOXITEM_GROUPING_ROOT=Racine de regroupement
_UI_ACTION_REMOVE=Supp&rimer
_UI_NONE=Aucun
_UI_SIMPLE=Simple

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_CUBE=CUBE

!! NOTE TO TRANSLATOR: Do not translate following line
_UI_ROLLUP=ROLLUP

_UI_GROUPING=Regroupement
_UI_GROUPINGSETS=Ensembles de regroupements

! views/select/SelectGridViewer.java:
!
_UI_COMBO_SORT_UNSORTED   = Non trié
_UI_COMBO_SORT_ASCENDING  = Croissant
_UI_COMBO_SORT_DESCENDING = Décroissant
_UI_COMBO_SORT_DEFAULT = Par défaut

!
!views/select/RemoveSelectColumnsAction.java
!
_UI_ACTION_REMOVE_SELECT_COLUMN = Supprimer la &colonne Expression

!
!views/select/RemoveOrderByExpressionAction.java
!
_UI_ACTION_REMOVE_ORDER_BY_EXPRESSION = Supprimer le tri par expressi&on

!
! views/select/SelectGridViewer.java
!
_UI_COLUMN_SELECT_ALIAS      = Pseudo
_UI_COLUMN_SELECT_OUTPUT     = Sortie
_UI_COLUMN_SELECT_SORT_TYPE  = Type de tri
_UI_COLUMN_SELECT_SORT_ORDER = Ordre de tri

!
! views/select/SelectViewer.java
!
_UI_WORKBOOKPAGE_COLUMNS          = Colonnes
_UI_WORKBOOKPAGE_CONDITIONS       = Conditions
_UI_WORKBOOKPAGE_GROUPS           = Groupes
_UI_WORKBOOKPAGE_GROUP_CONDITIONS = Conditions de groupe

!
! views/SQLBuilderActionBarContributor.java
!
_UI_TOOLTIP_EXECUTE_SQL = Exécuter l'instruction SQL
_UI_MENU_SQLBUILDER     = &SQL

!
! views/source/SQLSourceViewer.java & SQLSourceParser
!
!! NOTE TO TRANSLATOR: Do not translate the following four lines
_UI_INSERT                   = INSERT
_UI_UPDATE                   = UPDATE
_UI_DELETE                   = DELETE
_UI_SELECT                   = SELECT

_UI_PARSE_ERROR_ENCOUNTERED  = Erreur d'analyse rencontrée.


!
! views/StatementNameViewer.java
!
_UI_LABEL_STATEMENT = Instruction :


!
! Join stuff - DefineJoinDialog.java, DefineJoinTypeDialog.java
!
_UI_DEFINE_JOIN_DIALOG_TITLE = Spécifier une liaison
_UI_DEFINE_JOIN_DIALOG_INSTR = Type de liaison
_UI_RADIO_INNER_JOIN         = Liaison &interne
_UI_RADIO_LEFT_OUTER_JOIN    = &Liaison externe gauche
_UI_RADIO_RIGHT_OUTER_JOIN   = Liaison externe d&roite
_UI_RADIO_FULL_OUTER_JOIN    = Liaison e&xterne complète
_UI_ACTION_SPECIFY_JOIN_TYPE = &Spécifier le type de liaison...
_UI_MSG_INVALID_JOIN_TITLE = Types incompatibles

!
!views/update/UpdateDesignViewer.java
!
_UI_TOOLTIP_UPDATE_ADD_COL = Ajouter une colonne individuelle à l'instruction
_UI_TOOLTIP_UPDATE_ADD_GRP = Ajouter des colonnes à l'instruction comme un groupe

!
!views/with/WithTableViewer.java
!
_UI_GROUP_WITH_TABLE     = Table
_UI_GROUP_WITH_COLUMN    = Colonne
_UI_BUTTON_ADD_RIGHT     = Ajouter>>
_UI_BUTTON_REMOVE_LEFT   = <<Supprimer

!
! views/with/WithStatementViewer
!
_UI_LABEL_WITH_STATEMENT  = Nom de l'instruction :

! CreateWithTableAction.java

!! NOTE TO TRANSLATOR: Do not translate "WithTable%1" in the following line
_UI_WITH_TABLE_NAME		  = WithTable%1
!
! SQLPreferencePage.java
!
_UI_VALIDATE_PREFERENCE_LABEL = &Valider des instructions de requêtes en exécutant avant d'enregistrer
_UI_ERROR_VALUE_GREATER_THAN_0 = Cette valeur doit être un entier supérieur à zéro.

!
!views/SQLBuilder.java
!
_UI_VALIDATE_FAILED_TITLE    = Echec de la validation
_UI_CONTINUE_WITH_SAVE       = Continuer et enregistrer ?
_UI_VALIDATING_STATEMENT     = Validation de l'instruction...
_UI_OBTAINING_CONNECTION     = Obtention de la connexion...
_UI_VALIDATE_DONE            = Validation terminée...
_UI_SAVING_STATEMENT         = Enregistrement de l'instruction...

!model/SQLBuilderConstants.java:
_UI_BUILD_EXPRESSION   = Générer une expression...
_UI_EDIT_EXPRESSION    = Modifier une expression...
_UI_REPLACE_EXPRESSION = Remplacer une expression...
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_ADD_SELECT         = Ajouter une instruction SELECT...
_UI_ADD_FULLSELECT     = Ajouter une instruction FULLSELECT...
_UI_ADD_WITH           = Ajouter une instruction WITH...
_UI_ADD_VALUES         = Ajouter des valeurs
_UI_SPECIFY_VALUE	   = Spécifier une valeur...
_UI_SPECIFY_VALUE_TITLE	   = Spécifier une valeur


!========================================================================================
!
! Here is the list of Warning string that have message IDs - make sure they are unique
!
!========================================================================================
_WARN_MESSAGES_ENCOUNTERED      = Des messages d'avertissement ont été rencontrés
_WARN_DATA_WAS_TRUNCATED        = Les données étaient tronquées
_WARN_SQL_WARNINGS_FOUND        = Des avertissements SQL ont été trouvés

_WARN_BAD_JOIN_1                = Types de liaison incompatibles
_WARN_INVALID_JOIN              = Liaison invalide
_WARN_COLUMN_USED               = La colonne a déjà été utilisée dans une liaison entre des tables

! Usage:
!   {0} replaced with the column name and {1} replaced with the column datatype
!
_WARN_BAD_JOIN_TYPES               = Le type de colonne {0} est {1}


!======================================================================================
!
! Here is the list of Error string that have message IDs - make sure they are unique
!
!======================================================================================

_ERROR_DIALOG_TITLE_EXPR_EDIT_FAILED = Echec de la modification d'une expression
_ERROR_DIALOG_MSG_REBUILD_EXPR       = L'expression doit être de nouveau générée

_ERROR_TABLE_USED                    = Sélectionner une seule table ou saisir un pseudo.
_ERROR_ALIAS_USED                    = Saisir un pseudo unique.

_ERROR_ALIAS_NOT_UNIQUE_TEXT         = Le pseudo n'est pas unique


_EXC_OPEN_SQL_FILE_RESOURCE          = Une erreur s'est produite lors de l'ouverture de la ressource du fichier SQL d'entrée
_EXC_OPEN_SQL_FILE_NOT_CONNECTED     = Vous devez vous connecter à la base de données "{0}" avant d'ouvrir le fichier SQL dans le générateur de requête SQL.

!! NOTE TO TRANSLATOR: Do not translate "ISQLBuilderEditorInput" in the following line
_EXC_INPUT_NOT_ISQLBUILDEREDITORINPUT = L'entrée n'est pas une ISQLBuilderEditorInput

_ERROR_ALIAS_NOT_ALPHANUMERIC        = Le pseudo ne doit contenir que des caractères alphanumériques.
_ERROR_ALIAS_TABLE_USED              = Le pseudo ne doit pas être un nom de table de base de données.
_ERROR_ENTER_ALIAS                   = Le nom de table est déjà utilisé. Saisissez un pseudo.

_ERROR_DATABASE_NOT_AVAILABLE        = Une connexion à une base de données est indisponible
_ERROR_INPUT_NOT_RECOGNIZED          = Le type d'entrée de l'éditeur n'est pas pris en charge
_ERROR_OPEN_SQL_STORAGE_RESOURCE     = Une erreur s'est produite lors de l'ouverture de la ressource de stockage SQL d'entrée
_ERROR_OPEN_SQL_STRING_RESOURCE      = Une erreur s'est produite lors de l'ouverture de l'entrée.
_ERROR_OPEN_INPUT_PARSE_FAILED       = Le SQL ne peut pas être analysé car il est soit invalide soit actuellement non pris en charge.
_QUESTION_TITLE_OPEN_INPUT_PARSE_FAILED    = Erreur d'analyse du générateur de requête SQL
_QUESTION_MESSAGE_OPEN_INPUT_PARSE_FAILED    = Une instruction SQL vide sera créée dans le générateur de requête SQL.

!
!model/SQLDomainModel.java
!
!note we reuse messages from ErrorMessages.java in org.eclipse.ui.texteditor.ErrorMessages

Editor_error_save_title=Problèmes de sauvegarde
Editor_error_save_message=La sauvegarde a échoué.
Editor_error_save_readonly=\n\nMotif :\nImpossible d'écrire dans un fichier en lecture seule :
Editor_error_save_failed=\n\nMotif :\nImpossible d'écrire dans le fichier :

!Strings from B2BGUI properties file
_UI_ERROR_CREATING_FILE_TITLE = Erreur lors de la création d'un fichier
_UI_ERROR_CREATING_FILE_SHORT_DESC = Erreur lors de la création du fichier "{0}"
_UI_ERROR_CREATING_FILE_LONG_DESC = Une erreur s'est produite lors de la création du fichier "{0}".
_UI_PARENT_FOLDER_IS_READ_ONLY = Le répertoire parent "{0}" est en lecture seule.
_UI_UNKNOWN_ERROR_WITH_HINT = Erreur inconnue. Vérifiez que le répertoire parent "{0}" est accessible en écriture.
_UI_UNKNOWN_ERROR = Erreur inconnue. Vérifiez que le répertoire parent "{0}" est accessible en écriture.
! TextViewerOperationAction
_UI_MENU_COPY         = &Copier
_UI_MENU_CUT          = Co&uper
_UI_MENU_DELETE       = Supprimer
_UI_MENU_PASTE        = &Coller
_UI_MENU_PREFIX       = Préfixe
_UI_MENU_REDO         = Rétablir
_UI_MENU_SELECT_ALL   = Sélectionner tout
_UI_MENU_SHIFT_LEFT   = Déplacement à gauche
_UI_MENU_SHIFT_RIGHT  = Déplacement à droite
_UI_MENU_STRIP_PREFIX = Extraire le préfixe
_UI_MENU_UNDO         = Annuler

!SQL Editor
datatools_sqlbuilder_sqleditor_tooltip = Ouvrir l'éditeur SQL
datatools_sqlbuilder_sqleditor_title = Editeur &SQL

! SQL Query Builder
datatools_sqlbuilder_sqlbuilder_DML_error = Erreur
datatools_sqlbuilder_sqlbuilder_multipleDML = Le générateur SQL peut être utilisé uniquement pour créer un(e) unique \
instruction SQL DML. Le fichier {0} ne contient aucune instruction DML. Ouvrir le fichier avec l'éditeur SQL ?
datatools_sqlbuilder_sqlbuilder_multipleDML_VE = Visual Explain peut être utilisé uniquement pour une unique \
instruction SQL DML. Le fichier {0} ne contient aucune instruction DML.
datatools_sqlbuilder_sqlbuilder_unsupport_VE = Visual Explain n'est pas pris en charge par cette connexion de base de données.
!Clear to Skeleton and Revert to Last Correct
_UI_CLEAR_TO_TEMPLATE 			     = Restaurer le modèle
_UI_REVERT_TO_LAST_CORRECT_SOURCE    = Revenir à la dernière source correcte
_UI_LAST_CORRECT_SOURCE 			 = Dernière source correcte ?
!Change Statement Type
_UI_CHANGE_STATEMENT_TYPE			= Modifier le type d'instruction...
!Omit Current Schema
_UI_OMIT_CURRENT_SCHEMA              = Ignorer le schéma actuel... 

!
! views/execute/ExecuteViewer.java & views/execute/QueryOutputHelper.java
!
_UI_DIALOG_EXECUTE_SQL_TITLE = Exécuter l'instruction SQL
_UI_BUTTON_EXECUTE_CLOSE     = &Fermer
_UI_LABEL_SQL_STATEMENT      = Instruction &SQL :
_UI_BUTTON_EXECUTE           = Exécute&r
_UI_LABEL_QUERY_RESULTS      = Résultats de la requête :
_UI_MONITOR_EXECUTING_QUERY  = Exécution de l'instruction SQL...
_UI_LABEL_NO_CONNECTION      = La connexion à la base de données est manquante ou le modèle de schéma de la base de données relationnelle est corrompu.
_UI_LABEL_NO_CONNECTION_FILE = La connexion à la base de données est indisponible car le fichier xmi de connexion est manquant.

_UI_DIALOG_WARNING_TITLE       = Avertissement
_UI_DIALOG_OP_FAILED_TITLE     = Echec de l'opération
_UI_LABEL_EXECUTION_SUCCESSFUL = L'instruction s'est exécutée correctement mais n'a généré aucun résultat.
!! NOTE TO TRANSLATOR: the MAX_RECORD_EXCEEDED string should match
!! the strings for RECORD_RETURNED and RECORD_DISPLAYED.
_UI_MSG_MAX_RECORD_EXCEEDED    = Plus de 1000 enregistrements renvoyés. 1000 enregistrements affichés.
_UI_MSG_RECORD_RETURNED        = enregistrements renvoyés.


! SQL Statement validation errors
! usage note: %1 will be replaced with a SQL statement name
_ERROR_STATEMENT_NAME_EXISTS         = Une instruction appelée %1 existe déjà
_ERROR_INVALID_STATEMENT_NAME = Saisir un nom d'instruction valide.
! usage note: %1 is replaced with the invalid character entered by the user
_ERROR_INVALID_CHAR_IN_STATEMENT_NAME = Le nom de l'instruction ne peut pas contenir le caractère %1
_ERROR_STATEMENT_NAME_TOO_LONG = Le nom de l'instruction ne peut pas dépasser 160 caractères.


! SelectDBTablePage resources
datatools_selectDBTablePage_statements = Instructions

!
! SQL Statement actions
!
datatools_sqlbuilder_sqlstatement_actions_new = Nouveau...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement = Nouvelle instruction SQL...
datatools_sqlbuilder_sqlstatement_actions_newSQLStatement_tooltip = Créer une nouvelle instruction de requête
datatools_sqlbuilder_sqlstatement_actions_openwith = Ouvrir avec
datatools_sqlbuilder_sqlstatement_actions_sqlbuilder = Générateur de requête SQL
datatools_sqlbuilder_sqlstatement_actions_sqleditor = Editeur SQL

!
! New SQL statement wizard, dialog, and page
!
datatools_sqlbuilder_newStatementWizard_title = Nouvelle instruction SQL
datatools_sqlbuilder_newStatementWizard_description = Crée une instruction SQL.
datatools_sqlbuilder_newStatementDialog_title = Nouvelle instruction SQL
datatools_sqlbuilder_newStatementPage_title = Type d'instruction
datatools_sqlbuilder_newStatementPage_description = Nommer et sélectionner le type de modèle pour cette instruction.
datatools_sqlbuilder_newStatementPage_statementID = Identification de l'instruction
datatools_sqlbuilder_newStatementPage_statementName = Nom de l'in&struction :
datatools_sqlbuilder_newStatementPage_statementType = Modèle d'ins&truction :
datatools_sqlbuilder_newStatementPage_editUsing = Modifier par
datatools_sqlbuilder_newStatementPage_sqlQueryBuilder = Générateur S&QL
datatools_sqlbuilder_newStatementPage_sqlEditor = &Editeur SQL
datatools_sqlbuilder_newStatementPage_sampleStatements = Exemples d'instructions
datatools_sqlbuilder_newStatementPage_none = Aucun
!
! Project selection page, for new SQL statement wizard
!
datatools_sqlbuilder_projectPage_title = Sélectionner un projet
datatools_sqlbuilder_projectPage_description = Sélectionner un projet existant ou en ajouter un nouveau pour cette instruction.

!
! Generated comment text for template SQL for New SQL Statement action
!
_UI_SAMPLE_DML_TEMPLATE_STATEMENTS = Exemple d'instructions de modèles DML
_UI_SAMPLE_DDL_TEMPLATE_STATEMENTS = Exemple d'instructions de modèles DDL

!
! String for the AddTable With Table
!! NOTE TO TRANSLATOR: Do not translate "WITH" in the following line
_UI_AVAILABLE_TABLES_TREE_PROVIDER = Tables WITH

!actions/ConvertToFullSelectAction.java
!! NOTE TO TRANSLATOR: Do not translate "FULLSELECT" and "UNION" in the following line
_UI_ACTION_CONVERT_TO_FULL_SELECT=&Convertir en FULLSELECT (UNION)


! org.eclipse.datatools.sqltools.sqlbuilder.views.fullselect/fullselectElement.java
!! NOTE TO TRANSLATOR: Do not translate the words that are fully capitalized in the following 3 lines
_UI_VIEWS_FULLSELECTELEMENT_FULLSELECT = Instruction FULLSELECT
_UI_VIEWS_FULLSELECTELEMENT_SELECT = Instruction SELECT
_UI_VIEWS_FULLSELECTELEMENT_VALUES = VALUES

! org.eclipse.datatools.sqltools.sqlbuilder.views.graph/GraphContextMenuProvider.java
_UI_VIEWS_GRAPH_SELECT_ALL_COLUMN = Sélectionner Toutes les colonnes
_UI_VIEWS_GRAPH_DESELECT_ALL_COLUMN = Désélectionner Toutes les colonnes

!SQLQueryBuilder Dialog
_UI_SQLQUERYBUILDERDIALOG_NAME = Générateur de requête SQL
SQLQueryBuilderDialogEditTabName=Modifier
SQLQueryBuilderDialogNoInput=Echec d'ouverture d'une entrée par SQLBuilder Dialog.
SQLQueryBuilderDialogParseFailOnOpenAskUserTitle=Générateur de requête SQL
SQLQueryBuilderDialogParseFailOnOpenAskUserMessage=Si vous continuez, une instruction SQL vide sera créée dans le générateur de requête SQL. Voulez-vous continuer ?
SQLQueryBuilderDialogResultsTabName=Résultats SQL


# plugin.xml.  preference page extension point
_UI_SQLQUERY_NAME = Requête SQL

## Resources for the standard editor actions

ContentAssistProposal_label       =Co&ntent Assist@Ctrl+SPACE
ContentAssistProposal_tooltip     =Content Assist
ContentAssistProposal_image       =
ContentAssistProposal_description =Content Assist

ContentTip_label       =Content Tip@Ctrl+SHIFT+SPACE
ContentTip_tooltip     =Content Tip
ContentTip_image       =
ContentTip_description =Content Tip

## Resources for other SQL Query Builder actions

datatools_sqlbuilder_RunSQLAction_label       = Exécute&r SQL
datatools_sqlbuilder_RunSQLAction_tooltip     = Exécuter l'instruction SQL
datatools_sqlbuilder_RunSQLAction_image       =
datatools_sqlbuilder_RunSQLAction_description =

datatools_sqlbuilder_RevertToPreviousAction_label       = Revenir à la dernière source correcte
datatools_sqlbuilder_RevertToPreviousAction_tooltip     =
datatools_sqlbuilder_RevertToPreviousAction_image       =
datatools_sqlbuilder_RevertToPreviousAction_description =

datatools_sqlbuilder_RevertToDefaultAction_label       = Restaurer le modèle
datatools_sqlbuilder_RevertToDefaultAction_tooltip     =
datatools_sqlbuilder_RevertToDefaultAction_image       =
datatools_sqlbuilder_RevertToDefaultAction_description =

datatools_sqlbuilder_ChangeStatementTypeAction_label   = Modifier le type d'instruction...
datatools_sqlbuilder_ChangeStatementTypeAction_tooltip     =
datatools_sqlbuilder_ChangeStatementTypeAction_image       =
datatools_sqlbuilder_ChangeStatementTypeAction_description =

datatools_sqlbuilder_OmitCurrentSchemaAction_label       = Ignorer le schéma actuel...
datatools_sqlbuilder_OmitCurrentSchemaAction_tooltip     =
datatools_sqlbuilder_OmitCurrentSchemaAction_image       =
datatools_sqlbuilder_OmitCurrentSchemaAction_description =

!RDBTableDropListener
_UI_INVALID_TABLE_ADDED = Vous ne pouvez pas ajouter de tables d'une base de données vers une instruction sauf si la base de données est associée au projet.

## Resources for utilities

VIEW_UTILITY_DEFAULT_FONT_UI_ = MS Sans Serif
STRING_MATCH_EXPECTED_EXCEPTION_MESSAGE = Attendu : 
STRING_MATCH_RETURNED_EXCEPTION_MESSAGE =  Renvoyé :
