NoSuchProfileException_cant_find_profile=Impossible de trouver le profil : {0}
ProfileUtil_unkown_connection_type=Type de connexion non pris en charge : {0} créé par profil de connexion : {1}
ProfileUtil_error_create_connection=Impossible de créer une connexion à l'aide du profil de connexion : {0}
ProfileUtil_error_getReusableConnection=Impossible d'obtenir une connexion réutilisable par : {0}
ProfileUtil_error_not_connected=Le profil de connexion : {0} n'est pas encore connecté.

ProfileUtil_error_getdriver=Définition de pilote non spécifiée pour {0}.
ProfileUtil_error_wrong_database_name=Base de données incorrecte renvoyée {0} à partir du profil de connexion {1}. Le nom attendu est {2}
ProfileUtil_error_no_managed_connection=Failed to get managed connection for connection profile {0}

