NoSuchProfileException_cant_find_profile=No se puede encontrar el perfil: {0}
ProfileUtil_unkown_connection_type=No se admite el tipo de conexión: {0} creado por el perfil de conexión: {1}
ProfileUtil_error_create_connection=Error al crear conexión usando el perfil de conexión: {0}
ProfileUtil_error_getReusableConnection=Error al obtener una conexión reutilizable por: {0}
ProfileUtil_error_not_connected=El perfil de conexión: {0} no está conectado todavía.

ProfileUtil_error_getdriver=Definición de controlador no especificada para {0}.
ProfileUtil_error_wrong_database_name=La base de datos incorrecta ha devuelto {0} desde el perfil de conexión {1}. El nombre esperado es {2}
