NoSuchProfileException_cant_find_profile=Profil nicht gefunden: {0}
ProfileUtil_unkown_connection_type=Nicht unterstützter Verbindungstyp: {0} erstellt durch Verbindungsprofil: {1}
ProfileUtil_error_create_connection=Verbindung konnte nicht unter Verwendung des Verbindungsprofils erstellt werden: {0}
ProfileUtil_error_getReusableConnection=Es konnte keine wiederverwendbare Verbindung von : {0} abgerufen werden.
ProfileUtil_error_not_connected=Das Verbindungsprofil: {0} ist noch nicht verbunden.

ProfileUtil_error_getdriver=Keine Treiberspezifikation angegeben für {0}.
ProfileUtil_error_wrong_database_name=Falsche Datenbank gab {0} von Verbindungsprofil zurück {1}. Erwarteter Name ist {2}
ProfileUtil_error_no_managed_connection=Fehler beim Abrufen der verwalteten Verbindung für Verbindungsprofil {0}

