NoSuchProfileException_cant_find_profile=找不到配置文件 {0}。
ProfileUtil_unkown_connection_type=连接配置文件 {1} 创建了不受支持的连接类型 {0}。
ProfileUtil_error_create_connection=未能使用连接配置文件 {0} 创建连接。
ProfileUtil_error_getReusableConnection=未能通过 {0} 获取可重复使用的连接。
ProfileUtil_error_not_connected=尚未连接以下连接配置文件: {0}。

ProfileUtil_error_getdriver=未对 {0} 指定驱动程序定义。
ProfileUtil_error_wrong_database_name=从连接配置文件 {1} 返回了错误的数据库 {0}。期望的名称是 {2}
ProfileUtil_error_no_managed_connection=无法为连接配置文件 {0} 获取托管连接

