NoSuchProfileException_cant_find_profile=プロファイル {0} がありません。
ProfileUtil_unkown_connection_type=サポートされていない接続タイプ {0} が、接続プロファイル {1} で作成されました。
ProfileUtil_error_create_connection=接続プロファイル {0} を使って接続を作成できません。
ProfileUtil_error_getReusableConnection=再利用可能な接続を {0} で取得できません。
ProfileUtil_error_not_connected=接続プロファイル {0} はまだ接続されていません。

ProfileUtil_error_getdriver={0} のドライバ定義が指定されていません。
ProfileUtil_error_wrong_database_name=接続プロファイル {1} から間違ったデータベース {0} が返されました。予想される名前は {2} です。

