NoSuchProfileException_cant_find_profile=프로필을 찾을 수 없습니다: {0}
ProfileUtil_unkown_connection_type=지원되지 않는 연결 형식: {0} 다음 연결 프로필에서 생성됨: {1}
ProfileUtil_error_create_connection=연결 프로필을 사용하여 연결을 생성하지 못했습니다: {0}
ProfileUtil_error_getReusableConnection=재사용 가능한 연결을 가져오지 못했습니다: {0}
ProfileUtil_error_not_connected=연결 프로필: {0}이(가) 아직 연결되지 않았습니다.

ProfileUtil_error_getdriver={0}에 드라이버 정의가 지정되지 않았습니다.
ProfileUtil_error_wrong_database_name=잘못된 데이터베이스가 연결 프로필 {1}에서 {0}을(를) 반환했습니다. 예상된 이름은 {2}입니다.
ProfileUtil_error_no_managed_connection=연결 프로필 {0}에 대한 관리 연결 실패

