# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse-Datentools-Plattform – generisches Plug-In für Datenbankschnittstelle
driverClass = Treiberklasse
driverVendor = Anbieter
driverVersion = Version
driverDBName = Datenbankname
driverConnectionURL = Verbindungs-URL
driverUID = Benutzer-ID
driverPWD = Kennwort
org.eclipse.datatools.connectivity.db.driverCategory = Datenbank
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = Generische JDBC
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = Generischer JDBC-Treiber
databases.category = Datenbankverbindungen
generic.profile.name = SQL Modell – JDBC-Verbindung
jdbc.connection.name = JDBC Connection
