# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse.org
Bundle-Name = Eclipse Data Tools Platform Generic DB Connectivity Plug-in
driverClass = 驱动程序类
driverVendor = 供应商
driverVersion = 版本
driverDBName = 数据库名称
driverConnectionURL = 连接 URL
driverUID = 用户 ID
driverPWD = 密码
org.eclipse.datatools.connectivity.db.driverCategory = 数据库
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = 通用 JDBC
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = 通用 JDBC 驱动程序
databases.category = 数据库连接
generic.profile.name = SQL 模型 JDBC 连接
