# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse.org
Bundle-Name = Eclipse Data Tools Platform Generic DB Connectivity Plug-in
driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
driverUID = ユーザ ID
driverPWD = パスワード
org.eclipse.datatools.connectivity.db.driverCategory = データベース
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = 一般的な JDBC
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = 一般的な JDBC ドライバ
databases.category = データベース接続
generic.profile.name = SQL モデル - JDBC 接続
