# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform Generic DB Connectivity Plug-in
driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
driverUID = Identificador de usuario
driverPWD = Contraseña
org.eclipse.datatools.connectivity.db.driverCategory = Base de datos
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = JDBC genérico
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = Controlador de JDBC genérico
databases.category = Conexiones de la base de datos
generic.profile.name = Modelo SQL-Conexión JDBC
