# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse.org
Bundle-Name = Eclipse Data Tools Platform Generic DB Connectivity Plug-in
driverClass = Classe de pilote
driverVendor = Vendeur
driverVersion = Version
driverDBName = Nom de la base de données
driverConnectionURL = URL de connexion
driverUID = ID utilisateur
driverPWD = Mot de passe
org.eclipse.datatools.connectivity.db.driverCategory = Base de données
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = JDBC générique
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = Pilote JDBC générique
databases.category = Connexions à une base de données
generic.profile.name = Connexion JDBC-Modèle SQL
