# properties file for org.eclipse.datatools.connectivity.db.generic
Bundle-Vendor = Eclipse.org
Bundle-Name = Eclipse Data Tools Platform Generic DB Connectivity Plug-in
driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호
org.eclipse.datatools.connectivity.db.driverCategory = 데이터베이스
org.eclipse.datatools.connectivity.db.generic.genericDriverCategory = 범용 JDBC
org.eclipse.datatools.connectivity.db.generic.genericDriverTemplate = 범용 JDBC 드라이버
databases.category = 데이터베이스
generic.profile.name = SQL 모델-JDBC 연결
