###############################################################################
# Copyright (c) 2009 Sybase, Inc. and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Sybase, Inc. - initial API and implementation
###############################################################################
Plugin.Name = Eclipse Data Tools Platform SQL Tools Generic Database Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

generic.db=JDBC générique
generic.db.desc=Support de base de données générique d'outils de données
