###############################################################################
# Copyright (c) 2005, 2011 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=DTP ODA Connection Profile Framework Plug-in
extension-point.name.profileStore = ODA-Verbindungsprofilspeicher

