################################################################################
## Copyright (c) 2006-2007, 2010 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License 2.0
## which accompanies this distribution, and is available at
## https://www.eclipse.org/legal/epl-2.0/
##
## Contributors: 
##  Ingres - Implementation
##  Ingres - update for bugzilla 317378
################################################################################

PLUGIN_NAME = Plug-in d'interface utilisateur DTP Ingres
PROVIDER_NAME=Plate-forme d'outils de données Eclipse

# new connection profile wizard
WIZARD_NAME        = Ingres
WIZARD_DESCRIPTION =

# Property page
PROPERTY_PAGE_NAME = Propriétés de connexion Ingres

SynonymDecorationServiceLabel = Outils de données - Synonyme Ingres
datatools.core.ui.modelexplorer.modelExplorerColumnDecoration = Outils de données - Type de données de colonne Ingres 
