################################################################################
## Copyright (c) 2006-2007, 2010 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License 2.0
## which accompanies this distribution, and is available at
## https://www.eclipse.org/legal/epl-2.0/
##
## Contributors: 
##  Ingres - Implementation
##  Ingres - update for bugzilla 317378
################################################################################

PLUGIN_NAME = Ingres-DTP UI Plug-in
PROVIDER_NAME=Eclipse-Datentools-Plattform

# new connection profile wizard
WIZARD_NAME        = Ingres
WIZARD_DESCRIPTION =

# Property page
PROPERTY_PAGE_NAME = Ingres Verbindungseigenschaften

SynonymDecorationServiceLabel = Datentools – Ingres-Synonym
datatools.core.ui.modelexplorer.modelExplorerColumnDecoration = Datentools – Ingres-Spaltendatentyp 
