################################################################################
## Copyright (c) 2006-2007, 2010 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors: 
##  Ingres - Implementation
##  Ingres - update for bugzilla 317378
################################################################################

PLUGIN_NAME = Complemento de IU de Ingres DTP
PROVIDER_NAME=Eclipse Data Tools Platform

# new connection profile wizard
WIZARD_NAME        = Ingres
WIZARD_DESCRIPTION =

# Property page
PROPERTY_PAGE_NAME = Propiedades de conexión de Ingres

SynonymDecorationServiceLabel = Herramientas de datos: sinónimo de Ingres
datatools.core.ui.modelexplorer.modelExplorerColumnDecoration = Herramientas de datos: tipo de datos de columna de Ingres 
