###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB LUW UI Plug-in
providerName=Eclipse Data Tools Platform

profile.db2.luw.wizard.title = DB2 para Linux, UNIX y Windows
profile.db2.luw.wizard.description = Crear un perfil de conexión DB2 para Linux, UNIX y Windows.
profile.db2.luw.properties = Propiedades de controlador
