###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB LUW UI Plug-in
providerName=Eclipse Data Tools Platform

profile.db2.luw.wizard.title = Linux, UNIX 및 Windows용 DB2
profile.db2.luw.wizard.description = Linux, UNIX 및 Windows 연결 프로필용 DB2를 생성합니다.
profile.db2.luw.properties = 드라이버 속성
