###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB LUW UI Plug-in
providerName=Eclipse.org

profile.db2.luw.wizard.title = DB2 für Linux, UNIX und Windows
profile.db2.luw.wizard.description = Erstellung eines Verbindungsprofils DB2 für Linux, UNIX und Windows.
profile.db2.luw.properties = Treibereigenschaften
