###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse.org
serverExplorerLayout=サーバエクスプローラのレイアウトの拡張
serverExplorerInitialization=サーバの初期化のプロバイダ
SQL_MODEL_CONTENT_EXTENSION_NAME=SQL モデルコンテンツの拡張

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = データベースエクスプローラ - "既存の接続" コア
rdb.server.ui.views.serverExplorer = データベースエクスプローラ
rdb.server.ui.category = データ

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=接続の新規作成(&N)...
rdb.server.ui.actions.disconnect=切断(&C)
rdb.server.ui.actions.edit.table = テーブル
rdb.server.ui.actions.edit = データベースの追加
rdb.server.ui.actions.delete = 削除(&D)
rdb.server.ui.actions.reconnect = 再接続
rdb.server.ui.actions.navigate = ターゲットへの移動

#
## Menus for the Data
#
rdb.server.ui.actions.fe = DDL の生成(&G)
rdb.server.ui.actions.refresh = 再表示(&R)

#
## Actions
#
rdb.server.ui.explorer.connect_server = 接続の新規作成...
rdb.server.ui.explorer.reconnect_server = 再接続(&R)
rdb.server.ui.explorer.disconnect_server = 切断(&D)
rdb.server.ui.explorer.collapse_all = すべて折りたたむ
rdb.server.ui.actions.editfilter = フィルタ(&F)...

#
## Decorations
#
rdb.server.ui.serverDecoration = データツール - サーバエクスプローラの接続型の装飾
rdb.server.ui.filterDecoration = データツール - サーバエクスプローラのフィルタノードインジケータ
