###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse.org
serverExplorerLayout=Extension de mise en page d'explorateur de serveur
serverExplorerInitialization=Fournisseur d'initialisation de serveur
SQL_MODEL_CONTENT_EXTENSION_NAME=Extension de contenu de modèle SQL

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = Explorateur de base de données - "Connexions Existantes" principal
rdb.server.ui.views.serverExplorer = Explorateur de base de données
rdb.server.ui.category = Données

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=&Nouvelle connexion...
rdb.server.ui.actions.disconnect=Dé&connecter
rdb.server.ui.actions.edit.table = Table
rdb.server.ui.actions.edit = Ajouter une base de données
rdb.server.ui.actions.delete = &Supprimer
rdb.server.ui.actions.reconnect = Reconnecter
rdb.server.ui.actions.navigate = Naviguer vers la cible

#
## Menus for the Data
#
rdb.server.ui.actions.fe = &Générer un DDL
rdb.server.ui.actions.refresh = Actualise&r

#
## Actions
#
rdb.server.ui.explorer.connect_server = Nouvelle connexion...
rdb.server.ui.explorer.reconnect_server = &Reconnecter
rdb.server.ui.explorer.disconnect_server = &Déconnecter
rdb.server.ui.explorer.collapse_all = Tout réduire
rdb.server.ui.actions.editfilter = &Filtre...

#
## Decorations
#
rdb.server.ui.serverDecoration = Outils de données - Décoration de type de connexion d'explorateur de serveur
rdb.server.ui.filterDecoration = Outils de données - Indicateur de nœud de filtre d'explorateur de serveur
