###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse Data Tools Platform
serverExplorerLayout=服务器资源浏览器布局扩展
serverExplorerInitialization=服务器初始化提供程序
SQL_MODEL_CONTENT_EXTENSION_NAME=SQL 模型内容扩展

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = 数据库资源浏览器 -“现有连接”核心
rdb.server.ui.views.serverExplorer = 数据库资源浏览器
rdb.server.ui.category = 数据

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=新建连接(&N)...
rdb.server.ui.actions.disconnect=断开连接(&C)
rdb.server.ui.actions.edit.table = 表
rdb.server.ui.actions.edit = 添加数据库
rdb.server.ui.actions.delete = 删除(&D)
rdb.server.ui.actions.reconnect = 重新连接
rdb.server.ui.actions.navigate = 导航至目标

#
## Menus for the Data
#
rdb.server.ui.actions.fe = 生成 DDL(&G)
rdb.server.ui.actions.refresh = 刷新(&R)

#
## Actions
#
rdb.server.ui.explorer.connect_server = 新建连接...
rdb.server.ui.explorer.reconnect_server = 重新连接(&R)
rdb.server.ui.explorer.disconnect_server = 断开连接(&D)
rdb.server.ui.explorer.collapse_all = 全部折叠
rdb.server.ui.actions.editfilter = 筛选器(&F)...

#
## Decorations
#
rdb.server.ui.serverDecoration = 数据工具 - 服务器资源浏览器连接类型修饰
rdb.server.ui.filterDecoration = 数据工具 - 服务器资源浏览器筛选器节点指示器
