###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse Data Tools Platform
serverExplorerLayout=서버 탐색기 레이아웃 확장명
serverExplorerInitialization=서버 초기화 공급자
SQL_MODEL_CONTENT_EXTENSION_NAME=SQL 모델 콘텐츠 확장명

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = 데이터베이스 탐색기 - "기존 연결" 코어
rdb.server.ui.views.serverExplorer = 데이터베이스 탐색기
rdb.server.ui.category = 데이터

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=새 연결(&N)...
rdb.server.ui.actions.disconnect=연결 해제(&C)
rdb.server.ui.actions.edit.table = 테이블
rdb.server.ui.actions.edit = 데이터베이스 추가
rdb.server.ui.actions.delete = 삭제(&D)
rdb.server.ui.actions.reconnect = 다시 연결
rdb.server.ui.actions.navigate = 대상으로 이동

#
## Menus for the Data
#
rdb.server.ui.actions.fe = DDL 생성(&G)
rdb.server.ui.actions.refresh = 새로 고침(&R)

#
## Actions
#
rdb.server.ui.explorer.connect_server = 새 연결...
rdb.server.ui.explorer.reconnect_server = 다시 연결(&R)
rdb.server.ui.explorer.disconnect_server = 연결 해제(&D)
rdb.server.ui.explorer.collapse_all = 모두 축소
rdb.server.ui.actions.editfilter = 필터(&F)...

#
## Decorations
#
rdb.server.ui.serverDecoration = 데이터 도구 - 서버 탐색기 연결 형식 장식
rdb.server.ui.filterDecoration = 데이터 도구 - 서버 탐색기 필터 노드 표시기
