###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse Data Tools Platform
serverExplorerLayout=Server-Explorer Layout-Extension
serverExplorerInitialization=Server – Initialization Provider
SQL_MODEL_CONTENT_EXTENSION_NAME=SQL-Modell – Content-Extension

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = Datenbank-Explorer - "Existing Connections" Core
rdb.server.ui.views.serverExplorer = Datenbank-Explorer
rdb.server.ui.category = Daten

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=&Neue Verbindung...
rdb.server.ui.actions.disconnect=V&erbindung trennen
rdb.server.ui.actions.edit.table = Tabelle
rdb.server.ui.actions.edit = Datenbank hinzufügen
rdb.server.ui.actions.delete = &Löschen...
rdb.server.ui.actions.reconnect = Verbindung wiederherstellen
rdb.server.ui.actions.navigate = Zum Ziel navigieren

#
## Menus for the Data
#
rdb.server.ui.actions.fe = DDL &erstellen
rdb.server.ui.actions.refresh = &Aktualisieren

#
## Actions
#
rdb.server.ui.explorer.connect_server = Neue Verbindung...
rdb.server.ui.explorer.reconnect_server = &Neuverbinden
rdb.server.ui.explorer.disconnect_server = V&erbindung trennen
rdb.server.ui.explorer.collapse_all = Alle ausblenden
rdb.server.ui.actions.editfilter = &Filter...

#
## Decorations
#
rdb.server.ui.serverDecoration = Datentools – Server-Explorer-Verbindungstyp – Decoration
rdb.server.ui.filterDecoration = Datentools – Server-Explorer-Filterknoten – Indicator
