###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Server UI Plug-in
providerName=Eclipse.org
serverExplorerLayout=Extensión de diseño de explorador de servidor
serverExplorerInitialization=Proveedor de inicialización de servidor
SQL_MODEL_CONTENT_EXTENSION_NAME=Extensión de contenido del modelo SQL

#
## Providers for the Server Explorer
#
org.eclipse.datatools.connectivity.server.ui.serverExplorer = Explorador de base de datos: Núcleo de "conexiones existentes"
rdb.server.ui.views.serverExplorer = Explorador de base de datos
rdb.server.ui.category = Datos

#
## Menus for the Server Explorer
#
rdb.server.ui.actions.connect=&Nueva conexión...
rdb.server.ui.actions.disconnect=Des&conectar
rdb.server.ui.actions.edit.table = Tabla
rdb.server.ui.actions.edit = Añadir base de datos
rdb.server.ui.actions.delete = &Eliminar
rdb.server.ui.actions.reconnect = Volver a conectarse
rdb.server.ui.actions.navigate = Navegar al objetivo

#
## Menus for the Data
#
rdb.server.ui.actions.fe = &Generar DDL
rdb.server.ui.actions.refresh = &Actualizar

#
## Actions
#
rdb.server.ui.explorer.connect_server = Nueva conexión...
rdb.server.ui.explorer.reconnect_server = &Volver a conectar
rdb.server.ui.explorer.disconnect_server = &Desconectar
rdb.server.ui.explorer.collapse_all = Contraer todo
rdb.server.ui.actions.editfilter = &Filtro...

#
## Decorations
#
rdb.server.ui.serverDecoration = Herramientas de datos: decoración de tipo de conexión de explorador de servidor
rdb.server.ui.filterDecoration = Herramientas de datos: indicador de nodo de filtro de explorador de servidor
