###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## iSeries Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = Ba&se de datos:
CUI_NEWCW_HOST_LBL_UI_ = &Anfitrión:
CUI_NEWCW_PORT_LBL_UI_ = Nú&mero de puerto:
CUI_NEWCW_CONNECTIONURL_LBL_UI_= UR&L de conexión:
CUI_NEWCW_DEFDBNAME_VAL_UI_ = MUESTRA
CUI_NEWCW_USERNAME_LBL_UI_ = N&ombre de usuario:
CUI_NEWCW_PASSWORD_LBL_UI_ = Cont&raseña:
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = Guar&dar contraseña
CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = Base de datos
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = Anfitrión
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = Número de puerto
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = Nombre de usuario
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = Guardar contraseña
CUI_NEWCW_DEFAULT_SCHEMA_LBL_UI_ = Esquema predeterminado:
CUI_NEWCW_DEFAULT_SCHEMA_SUMMARY_DATA_TEXT_ = Esquema predeterminado
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = true
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = false
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = Introduzca un nombre de base de datos, por ejemplo, {0}.
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= Introduzca el nombre del anfitrión para el servidor de base de datos.
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = Introduzca el número del puerto de conexión para el servidor de base de datos.
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = Introduzca un nombre de usuario.
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = Introduzca una contraseña.



