################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Eclipse Data Tools Platform Data Source Explorer Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

DSE.Connect.label=Ver&binden
DSE.Disconnect.label=&Verbindung trennen
DSE.Duplicate.label=Du&plikat
DSE.Delete.label=L&öschen
DSE.Rename.label=&Umbenennen
DSE.Refresh.label=A&ktualisieren
DSE.Ping.label=&Pingsignal...
DSE.ADDCP_m.label = N
DSE.AddCP_nm.label = Neues Verbindungsprofil
DSE.AddCP.label=&Neues Verbindungsprofil
DSE.AddCP.tooltip=Neues Verbindungsprofil
DSE.AddRepo.label = Neues Verbindungsprofil-&Repository
DSE.AddRepo.tooltip = Neues Verbindungsprofil-Repository erstellen
DSE.Import_nm.label = Importieren
DSE.Import_m.label = I
DSE.Import.label=&Importieren
DSE.Import.tooltip=Importieren
DSE.Export_nm.label = Exportieren
DSE.Export_m.label = E
DSE.Export.label=E&xportieren
DSE.Export.tooltip=Exportieren
DSE.CollapseAll.label=Alles a&usblenden
DSE.ExpandAll.label=Alles &einblenden
DSE.ExpandAll.tooltip=Alles einblenden
DSE.ShowCategory.command.label = Kategorie anzeigen
DSE.ShowCategory.command.description = Kategorie anzeigen
DSE.ShowCategory_nm.label = Kategorie anzeigen
DSE.ShowCategory_m.label = S
DSE.ShowCategory.label=Kate&gorie anzeigen
DSE.ShowCategory.tooltip=Kategorie anzeigen
DSE.Name=Datenquellen-Explorer
DSE.ContentExtension.Decorator=Dekorator für Verbindungsprofil
DSE.ContentExtension.Decorator.Description=Versieht den Inhaltserweiterungsknoten mit Dekoratoren, wenn die Verbindung zum Server fehlschlägt.
DSE.content.extended = Erweiterung für Datenquellen-Explorer w/Ablage-Support
category.name.dataTools=SQL-Entwicklung
category.name.connectivity=Konnektivität

General = Allgemein
