################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Eclipse Data Tools Platform Data Source Explorer Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

DSE.Connect.label=连接(&C)
DSE.Disconnect.label=断开连接(&D)
DSE.Duplicate.label=复制(&P)
DSE.Delete.label=删除(&E)
DSE.Rename.label=重命名(&N)
DSE.Refresh.label=刷新(&R)
DSE.Ping.label=&Ping...
DSE.ADDCP_m.label = N
DSE.AddCP_nm.label = 新建连接配置文件
DSE.AddCP.label=新建连接概要文件(&N)
DSE.AddCP.tooltip=新建连接概要文件
DSE.AddRepo.label = 新建连接配置文件和存储库
DSE.AddRepo.tooltip = 创建新连接配置文件存储库
DSE.Import_nm.label = 导入
DSE.Import_m.label = I
DSE.Import.label=导入(&I)
DSE.Import.tooltip=导入
DSE.Export_nm.label = 导出
DSE.Export_m.label = E
DSE.Export.label=导出(&E)
DSE.Export.tooltip=导出
DSE.CollapseAll.label=全部折叠(&C)
DSE.ExpandAll.label=全部展开(&E)
DSE.ExpandAll.tooltip=全部展开
DSE.ShowCategory.command.label = 显示类别
DSE.ShowCategory.command.description = 显示类别
DSE.ShowCategory_nm.label = 显示类别
DSE.ShowCategory_m.label = S
DSE.ShowCategory.label=显示类别(&S)
DSE.ShowCategory.tooltip=显示类别
DSE.Name=数据源资源管理器
DSE.ContentExtension.Decorator=连接概要文件修饰符
DSE.ContentExtension.Decorator.Description=连接至服务器失败时修饰内容扩展节点。
DSE.content.extended = 带删除支持的数据源资源管理器扩展
category.name.dataTools=SQL 开发
category.name.connectivity=连接

General = 常规
