################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Eclipse Data Tools Platform Data Source Explorer Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

DSE.Connect.label=&Conectar
DSE.Disconnect.label=&Desconectar
DSE.Duplicate.label=Du&plicar
DSE.Delete.label=&Suprimir
DSE.Rename.label=Rede&nominar
DSE.Refresh.label=Reno&var
DSE.Ping.label=&Ping...
DSE.ADDCP_m.label = N
DSE.AddCP_nm.label = Nuevo perfil de conexión
DSE.AddCP.label=Perfil de c&onexión nuevo
DSE.AddCP.tooltip=Perfil de conexión nuevo
DSE.AddRepo.label = Nuevo &repositorio de perfiles de conexión
DSE.AddRepo.tooltip = Crear un nuevo repositorio de perfiles de conexión
DSE.Import_nm.label = Importar
DSE.Import_m.label = I
DSE.Import.label=&Importar
DSE.Import.tooltip=Importar
DSE.Export_nm.label = Exportar
DSE.Export_m.label = J
DSE.Export.label=E&xportar
DSE.Export.tooltip=Exportar
DSE.CollapseAll.label=&Contraer todo
DSE.ExpandAll.label=&Expandir todo
DSE.ExpandAll.tooltip=Expandir todo
DSE.ShowCategory.command.label = Mostrar categoría
DSE.ShowCategory.command.description = Mostrar categoría
DSE.ShowCategory_nm.label = Mostrar categoría
DSE.ShowCategory_m.label = S
DSE.ShowCategory.label=&Mostrar categoría
DSE.ShowCategory.tooltip=Mostrar categoría
DSE.Name=Explorador de orígenes de datos
DSE.ContentExtension.Decorator=Decorador de perfil de conexión
DSE.ContentExtension.Decorator.Description=La decoración del nodo de extensión de contenido falla al conectar con el servidor.
DSE.content.extended = Extensión de explorador de fuentes de datos con soporte para supresión
category.name.dataTools=Desarrollo SQL
category.name.connectivity=Conectividad

General = General
