################################################################################
## Copyright (c) 2005 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Eclipse Data Tools Platform Data Source Explorer Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

DSE.Connect.label=&Connecter
DSE.Disconnect.label=&Déconnecter
DSE.Duplicate.label=Co&pier
DSE.Delete.label=&Supprimer
DSE.Rename.label=Re&nommer
DSE.Refresh.label=Rég&énérer
DSE.Ping.label=&Ping...
DSE.ADDCP_m.label = N
DSE.AddCP_nm.label = Nouveau profil de connexion
DSE.AddCP.label=&Nouveau profil de connexion
DSE.AddCP.tooltip=Nouveau profil de connexion
DSE.AddRepo.label = Nouveau &référentiel de profils de connexion
DSE.AddRepo.tooltip = Créer un nouveau référentiel de profils de connexion
DSE.Import_nm.label = Importer
DSE.Import_m.label = I
DSE.Import.label=&Importer
DSE.Import.tooltip=Importer
DSE.Export_nm.label = Exporter
DSE.Export_m.label = E
DSE.Export.label=&Exporter
DSE.Export.tooltip=Exporter
DSE.CollapseAll.label=&Réduire tout
DSE.ExpandAll.label=&Développer tout
DSE.ExpandAll.tooltip=Développer tout
DSE.ShowCategory.command.label = Afficher la catégorie
DSE.ShowCategory.command.description = Afficher la catégorie
DSE.ShowCategory_nm.label = Afficher la catégorie
DSE.ShowCategory_m.label = A
DSE.ShowCategory.label=&Afficher la catégorie
DSE.ShowCategory.tooltip=Afficher la catégorie
DSE.Name=Explorateur de source de données
DSE.ContentExtension.Decorator=Décorateur de profils de connexion
DSE.ContentExtension.Decorator.Description=Décorer le noeud d'extension de contenu en cas d'échec de la connexion au serveur.
DSE.content.extended = Extension de l'explorateur de source de données avec Assistance suppression
category.name.dataTools=Développement SQL
category.name.connectivity=Connectivité

General = Général
