DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=Die Eigenschaft {0} wird nicht unterstützt.

plugin_internal_error=Interner Fehler bei Plug-In für Editor-Core

ProcIdentifierImpl_map_cant_be_null=Zuordnung darf nicht gleich Null sein.
ProcIdentifierImpl_invalid_identifier_string=Ungültige Kennungszeichenfolge
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=Nicht definiert

DefaultSQLSyntax_exception_splitSQL=Ausnahme beim Teilen von SQL: {0}

ControlConnectionManager_unknownServerType=Der korrekte Servertyp kann nicht aus dem Verbindungsprofil abgeleitet werden: {0}

AbstractControlConnection_connection_already_being_debugged=Verbindung {0} wird bereits auf Fehler geprüft.
AbstractControlConnection_invalid_store_procedure_description=Ungültige Beschreibung der gespeicherten Prozedur
