DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=속성 {0}이(가) 지원되지 않습니다.

plugin_internal_error=편집기 코어 플러그인 내부 오류

ProcIdentifierImpl_map_cant_be_null=맵은 널(null)일 수 없습니다.
ProcIdentifierImpl_invalid_identifier_string=잘못된 식별자 문자열
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=정의되지 않음

DefaultSQLSyntax_exception_splitSQL=SQL을 분할하는 동안 예외가 발생했습니다: {0}

ControlConnectionManager_unknownServerType=연결 프로필에 의해 올바른 서버 유형을 확인할 수 없습니다: {0}

AbstractControlConnection_connection_already_being_debugged=연결 {0}이(가) 이미 디버깅 중입니다.
AbstractControlConnection_invalid_store_procedure_description=잘못된 저장 프로시저 설명
