DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=不支持属性 {0}

plugin_internal_error=编辑器核心插件内部错误

ProcIdentifierImpl_map_cant_be_null=映射不能为空
ProcIdentifierImpl_invalid_identifier_string=无效标识符字符串
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=未定义

DefaultSQLSyntax_exception_splitSQL=分割 SQL 时发生了异常: {0}

ControlConnectionManager_unknownServerType=不能按连接配置文件确定正确的服务器类型: {0}

AbstractControlConnection_connection_already_being_debugged=已在调试连接 {0}
AbstractControlConnection_invalid_store_procedure_description=无效存储过程说明
