DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=No se admite la propiedad {0}

plugin_internal_error=Error interno del complemento principal del editor

ProcIdentifierImpl_map_cant_be_null=La asignación no puede ser nula
ProcIdentifierImpl_invalid_identifier_string=Cadena de identificador no válida
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=Sin definir

DefaultSQLSyntax_exception_splitSQL=Se ha producido una excepción al dividir SQL: {0}

ControlConnectionManager_unknownServerType=No se puede determinar el tipo de servidor correcto mediante el perfil de conexión: {0}

AbstractControlConnection_connection_already_being_debugged=La conexión {0} ya se está depurando
AbstractControlConnection_invalid_store_procedure_description=Descripción de procedimiento almacenado no válida
