DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=La propriété {0} n'est pas prise en charge

plugin_internal_error=Erreur interne du plug-in principal de l'éditeur

ProcIdentifierImpl_map_cant_be_null=Le mappage ne peut pas être nul
ProcIdentifierImpl_invalid_identifier_string=Chaîne d'identificateur invalide
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=Non défini

DefaultSQLSyntax_exception_splitSQL=Une exception s'est produite lors du fractionnement SQL : {0}

ControlConnectionManager_unknownServerType=Impossible de déterminer le type de serveur correct par le profil de connexion : {0}

AbstractControlConnection_connection_already_being_debugged=La connexion {0} est déjà en cours de débogage
AbstractControlConnection_invalid_store_procedure_description=Description de procédure stockée invalide
