DefaultDBFactory_version=1.0
NotSupportedSettingException_cause=プロパティ "{0}" はサポートされていません。

plugin_internal_error=Editor Core Plugin の内部エラー

ProcIdentifierImpl_map_cant_be_null=マップは Null にできません。
ProcIdentifierImpl_invalid_identifier_string=識別子の文字列が無効です。
#\u200E invisible LEFT-TO-RIGHT MARK (LRM).
ProcIdentifierImpl_trigger_long_display_string=\u200E({0}).{1}.{2}.{3}.{4}\u200E
ProcIdentifierImpl_long_display_string=\u200E({0}).{1}.{2}.{3}\u200E

DefaultDBFactory_vendor=未定義

DefaultSQLSyntax_exception_splitSQL=SQL {0} を分割中に例外が発生しました。

ControlConnectionManager_unknownServerType=接続プロファイル {0} では正しいサーバの種類を認識できません。

AbstractControlConnection_connection_already_being_debugged=接続 {0} はすでにデバッグ中です。
AbstractControlConnection_invalid_store_procedure_description=ストアドプロシージャの記述が無効です。
