#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Externalized messages of the Web Services Data Source Designer

webservice.soap.fault=A SOAP error occurred.

webservice.soap.fault.faultcode=エラーコード
webservice.soap.fault.faultstring=エラーの文字列
webservice.soap.fault.reason=原因
service.notexist=サービスを取得できません
port.notexist=ポートを取得できません
