#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Externalized messages of the Web Services Data Source Designer

webservice.soap.fault=A SOAP error occurred.

webservice.soap.fault.faultcode=Fehlercode
webservice.soap.fault.faultstring=Fehlerzeichenfolge
webservice.soap.fault.reason=Grund
service.notexist=Dienst kann nicht abgerufen werden
port.notexist=Anschluss kann nicht ermittelt werden
