#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Externalized messages of the Web Services Data Source Designer

webservice.soap.fault=A SOAP error occurred.

webservice.soap.fault.faultcode=错误代码
webservice.soap.fault.faultstring=错误字符串
webservice.soap.fault.reason=原因
service.notexist=无法获得服务
port.notexist=无法获得端口
