#
#************************************************************************
# Copyright (c) 2008 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
# Externalized messages of the Web Services Data Source Designer

webservice.soap.fault=A SOAP error occurred.

webservice.soap.fault.faultcode=장애 코드
webservice.soap.fault.faultstring=장애 문자열
webservice.soap.fault.reason=원인
service.notexist=서비스 가져올 수 없음
port.notexist=포트 가져올 수 없음
