###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=Web Services 数据源
connection.profile.name=Web Services 数据源连接配置文件
newwizard.name=Web Services 数据源
newwizard.description=创建 Web Services 数据源连接配置文件
wizard.window.title=新建 Web Services 数据源配置文件
wizard.data.source.page.title=Web Services 数据源
profile.propertypage.name=Web Services 数据源连接属性
wizard.data.set.window.title=新建 Web Services 数据集
wizard.data.set.page.title=查询

oda.ws.operation=WSDL 操作
oda.ws.soapparameters=SOAP 参数
oda.ws.soaprequest=SOAP 请求
oda.ws.soapresponse=SOAP 响应
oda.ws.tablemapping=行映射
oda.ws.columnmapping=列映射
