###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=Fuente de datos de servicios web
connection.profile.name=Perfil de conexión de fuente de datos de servicios web
newwizard.name=Fuente de datos de servicios web
newwizard.description=Crear un perfil de conexión de fuente de datos de servicios web
wizard.window.title=Nuevo perfil de fuente de datos de servicios web
wizard.data.source.page.title=Fuente de datos de servicios web
profile.propertypage.name=Propiedades de conexión de fuente de datos de servicios web
wizard.data.set.window.title=Nuevo conjunto de datos de servicios web
wizard.data.set.page.title=Consulta

oda.ws.operation=Operación
oda.ws.soaprequest=Solicitud de SOAP
oda.ws.soapresponse=Respuesta de SOAP
oda.ws.tablemapping=Asignación de tablas
oda.ws.columnmapping=Asignación de columnas
