###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=Datenquelle für Web-Dienste
connection.profile.name=Datenquellen-Verbindungsprofil für Web-Dienste
newwizard.name=Datenquelle für Web-Dienste
newwizard.description=Datenquellen-Verbindungsprofil für Web-Dienste erstellen
wizard.window.title=Neues Datenquellenprofil für Web-Dienste
wizard.data.source.page.title=Datenquelle für Web-Dienste
profile.propertypage.name=Datenquellen-Verbindungseigenschaften für Web-Dienste
wizard.data.set.window.title=Neuer Datensatz für Web-Dienste
wizard.data.set.page.title=Abfrage

oda.ws.operation=Betrieb
oda.ws.soaprequest=SOAP-Anforderung
oda.ws.soapresponse=SOAP-Antwort
oda.ws.tablemapping=Tabellenzuordnung
oda.ws.columnmapping=Spaltenzuordnung
