###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=Web サービスのデータソース
connection.profile.name=Web サービスのデータソースの接続プロファイル
newwizard.name=Web サービスのデータソース
newwizard.description=Web サービスのデータソースの接続プロファイルを作成します。
wizard.window.title=Web サービスデータソースプロファイルの新規作成
wizard.data.source.page.title=Web サービスのデータソース
profile.propertypage.name=Web サービスのデータソースの接続プロパティ
wizard.data.set.window.title=Web サービスのデータセットの新規作成
wizard.data.set.page.title=クエリ

oda.ws.operation=操作
oda.ws.soaprequest=SOAP リクエスト
oda.ws.soapresponse=SOAP 応答
oda.ws.tablemapping=テーブルのマッピング
oda.ws.columnmapping=列のマッピング
