###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=웹 서비스 데이터 원본
connection.profile.name=웹 서비스 데이터 원본 연결 프로필
newwizard.name=웹 서비스 데이터 원본
newwizard.description=웹 서비스 데이터 원본 연결 프로필 생성
wizard.window.title=새 웹 서비스 데이터 원본 연결 프로필
wizard.data.source.page.title=웹 서비스 데이터 원본
profile.propertypage.name=웹 서비스 데이터 원본 연결 속성
wizard.data.set.window.title=새 웹 서비스 데이터 집합
wizard.data.set.page.title=쿼리

oda.ws.operation=WSDL 작업
oda.ws.soapparameters=SOAP 매개 변수
oda.ws.soaprequest=SOAP 요청
oda.ws.soapresponse=SOAP 응답
oda.ws.tablemapping=테이블 매핑
oda.ws.columnmapping=열 매핑
