###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS strings
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Designer
data.source.name=Source de données Services Web
connection.profile.name=Profil de connexion à la source de données Services Web
newwizard.name=Source de données Services Web
newwizard.description=Créer un profil de connexion à la source de données Services Web
wizard.window.title=Nouveau profil de connexion à la source de données Services Web
wizard.data.source.page.title=Source de données Services Web
profile.propertypage.name=Propriétés de la connexion à la source de données Services Web
wizard.data.set.window.title=Nouveau jeu de données Services Web
wizard.data.set.page.title=Requête

oda.ws.operation=Opération WSDL
oda.ws.soapparameters=Paramètres SOAP
oda.ws.soaprequest=Requête SOAP
oda.ws.soapresponse=Réponse SOAP
oda.ws.tablemapping=Mise en correspondance de ligne
oda.ws.columnmapping=Mise en correspondance de colonne
