###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse.org
databaseDefinitionExtensionPointName=데이터베이스 정의
logicalContainmentExtensionPointName=논리적 제약
DataModelElementFactoryExtensionPointName=데이터 모델 요소 팩토리
DatabaseReverseEngineeringExtensionPointName=데이터베이스 리버스 엔지니어링
DDLReverseEngineeringExtensionPointName=DDL 리버스 엔지니어링
ForwardEngineeringExtensionPointName=포워드 엔지니어링
CatalogExtensionPointName=데이터베이스 카탈로그
DatabaseRecognition=데이터베이스 인식
FilterProfileExtensionName=SQL 모델 필터 설정
SQLModelConnectionName=SQL 모델 연결
