###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse Data Tools Platform
databaseDefinitionExtensionPointName=データベース定義
logicalContainmentExtensionPointName=論理の格納
DataModelElementFactoryExtensionPointName=データモデル要素ファクトリ
DDLReverseEngineeringExtensionPointName=DDL のリバースエンジニアリング
ForwardEngineeringExtensionPointName=フォワードエンジニアリング
CatalogExtensionPointName=データベースカタログ
DatabaseRecognition=データベースの識別
FilterProfileExtensionName=SQL モデルのフィルタ設定
SQLModelConnectionName=SQL モデル接続
