###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse Data Tools Platform
databaseDefinitionExtensionPointName=Définition de base de données
logicalContainmentExtensionPointName=Confinement logique
DataModelElementFactoryExtensionPointName=Génération d'éléments du modèle de données
DDLReverseEngineeringExtensionPointName=Ingénierie inverse DDL
ForwardEngineeringExtensionPointName=Ingénierie directe
CatalogExtensionPointName=Catalogue de base de données
DatabaseRecognition=Reconnaissance de base de données
FilterProfileExtensionName=Paramètres des filtres du modèle SQL
SQLModelConnectionName=Connexion du modèle SQL
