###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse Data Tools Platform
databaseDefinitionExtensionPointName=Datenbank-Definition
logicalContainmentExtensionPointName=Logische Containment-Hierarchie
DataModelElementFactoryExtensionPointName=Datenmodell Element-Factory
DDLReverseEngineeringExtensionPointName=DDL Reverse-Engineering
ForwardEngineeringExtensionPointName=Forward-Engineering
CatalogExtensionPointName=Datenbankkatalog
DatabaseRecognition=Datenbankerkennung
FilterProfileExtensionName=SQL-Modell Filtereinstellungen
SQLModelConnectionName=SQL- Modell Verbindung
