###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse.org
databaseDefinitionExtensionPointName=Definición de base de datos
logicalContainmentExtensionPointName=Contención lógica
DataModelElementFactoryExtensionPointName=Fábrica de elementos del modelo de datos
DDLReverseEngineeringExtensionPointName=Inversión del código de DDL
ForwardEngineeringExtensionPointName=Ingeniería directa
CatalogExtensionPointName=Catálogo de base de datos
DatabaseRecognition=Reconocimiento de base de datos
FilterProfileExtensionName=Ajustes de filtro del modelo SQL
SQLModelConnectionName=Conexión de modelo SQL
