###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform SQM Core Plug-in
providerName=Eclipse.org
databaseDefinitionExtensionPointName=数据库定义
logicalContainmentExtensionPointName=逻辑包含关系
DataModelElementFactoryExtensionPointName=数据模型元素工厂
DDLReverseEngineeringExtensionPointName=DDL 反向工程
ForwardEngineeringExtensionPointName=正向工程
CatalogExtensionPointName=数据库目录
DatabaseRecognition=数据库识别
FilterProfileExtensionName=SQL 模型筛选器设置
SQLModelConnectionName=SQL 模型连接
