# preference page
TemplatePreferencePage_error_import=Vorlagen wurden nicht importiert.
TemplatePreferencePage_error_export=Vorlagen wurden nicht exportiert.
TemplatePreferencePage_error_read_title=Vorlagen werden gelesen
TemplatePreferencePage_error_write_title=Vorlagen werden geschrieben
TemplatePreferencePage_message=Vorlagen &erstellen, bearbeiten oder entfernen:
TemplatePreferencePage_title=Vorlagen

TemplatePreferencePage_new=&Neu...
TemplatePreferencePage_edit=&Bearbeiten...
TemplatePreferencePage_import=&Importieren...
TemplatePreferencePage_export=E&xportieren...
TemplatePreferencePage_remove=&Entfernen
TemplatePreferencePage_editor=Vorlage
TemplatePreferencePage_revert=Auf &Standardwert zurücksetzen
TemplatePreferencePage_restore=Entfernte &wiederherstellen

TemplatePreferencePage_column_name=Name
TemplatePreferencePage_column_context=Kontext
TemplatePreferencePage_column_description=Beschreibung
TemplatePreferencePage_column_autoinsert=Autom einfügen

# on (as the opposite of off)
TemplatePreferencePage_on=am

TemplatePreferencePage_use_code_formatter=Code&formatierung verwenden

TemplatePreferencePage_import_title=Vorlagen werden importiert
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title={0} Vorlagen werden exportiert
TemplatePreferencePage_export_filename=templates.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= Vorlagen werden exportiert
TemplatePreferencePage_export_exists_message= {0} ist bereits vorhanden.\nErsetzen?

TemplatePreferencePage_export_error_title= Vorlagen werden exportiert
TemplatePreferencePage_export_error_hidden= Export fehlgeschlagen.\n{0} ist eine verborgene Datei.
TemplatePreferencePage_export_error_canNotWrite= Export fehlgeschlagen.\n{0} kann nicht geändert werden.
TemplatePreferencePage_export_error_fileNotFound= Export fehlgeschlagen:\n{0}

TemplatePreferencePage_error_parse_message= Vorlagen wurden nicht analysiert:\n{0}
TemplatePreferencePage_error_read_message= Vorlagen wurden nicht gelesen.
TemplatePreferencePage_error_write_message= Vorlagen wurden nicht geschrieben.

TemplatePreferencePage_question_create_new_title= Vorlage bearbeiten
TemplatePreferencePage_question_create_new_message= Der Name der Vorlage wurde geändert. Klicken Sie auf 'Ja', um eine weitere Vorlage mit dem neuen Namen zu erstellen, oder auf 'Nein', um die bestehende umzubenennen.

TemplatePreferencePage_preview=Vor&schau:

# edit template dialog
EditTemplateDialog_error_noname=Vorlagenname darf nicht leer sein.
EditTemplateDialog_error_adjacent_variables=Vorlagenmuster hat benachbarte Variablen.
EditTemplateDialog_title_new=Neue Vorlage
EditTemplateDialog_title_edit=Vorlage bearbeiten

EditTemplateDialog_name=&Name:
EditTemplateDialog_description=&Beschreibung:
EditTemplateDialog_context=&Kontext:
EditTemplateDialog_pattern=&Muster:
EditTemplateDialog_insert_variable=&Variable einfügen...

EditTemplateDialog_undo=&Rückgängig
EditTemplateDialog_cut=Auss&chneiden
EditTemplateDialog_copy=&Kopieren
EditTemplateDialog_paste=&Einfügen
EditTemplateDialog_select_all=Alles m&arkieren
EditTemplateDialog_autoinsert=Auto&matisch einfügen
EditTemplateDialog_content_assist=&Variable einfügen...

TemplateVariableProposal_error_title=Fehler beim Anwenden des Vorlagenvariablenvorschlags
TemplateVariableProcessor_error_title=Fehler beim Erstellen von Vorlagenvariablenvorschlägen

GlobalVariables_variable_description_cursor=Die Cursorposition nach der Bearbeitung der Vorlagenvariablen
GlobalVariables_variable_description_dollar=Das Dollarsymbol
GlobalVariables_variable_description_date=Aktuelles Datum
GlobalVariables_variable_description_year=Aktuelles Jahr
GlobalVariables_variable_description_time=Aktuelle Uhrzeit
GlobalVariables_variable_description_user=Benutzername
GlobalVariables_variable_description_selectedWord= Das ausgewählte Wort
GlobalVariables_variable_description_selectedLines= Die ausgewählten Zeilen

