# preference page
TemplatePreferencePage_error_import=템플릿을 가져오지 못했습니다.
TemplatePreferencePage_error_export=템플릿을 내보내지 못했습니다.
TemplatePreferencePage_error_read_title=템플릿을 읽는 중
TemplatePreferencePage_error_write_title=템플릿을 쓰는 중
TemplatePreferencePage_message=템플릿 생성, 편집 또는 제거(&C):
TemplatePreferencePage_title=템플릿

TemplatePreferencePage_new=새로 만들기(&N)...
TemplatePreferencePage_edit=편집(&E)...
TemplatePreferencePage_import=가져오기(&I)...
TemplatePreferencePage_export=내보내기(&X)...
TemplatePreferencePage_remove=제거(&R)
TemplatePreferencePage_editor=템플릿
TemplatePreferencePage_revert=기본값으로 되돌리기(&V)
TemplatePreferencePage_restore=제거한 내용 복구(&M)

TemplatePreferencePage_column_name=이름
TemplatePreferencePage_column_context=컨텍스트
TemplatePreferencePage_column_description=설명
TemplatePreferencePage_column_autoinsert=자동 삽입

# on (as the opposite of off)
TemplatePreferencePage_on=on

TemplatePreferencePage_use_code_formatter=코드 포맷터 사용(&F)

TemplatePreferencePage_import_title=템플릿 가져오는 중
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title={0} 템플릿 내보내는 중
TemplatePreferencePage_export_filename=templates.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= 템플릿 내보내기
TemplatePreferencePage_export_exists_message= {0}이(가) 이미 있습니다.\n바꾸시겠습니까?

TemplatePreferencePage_export_error_title= 템플릿 내보내기
TemplatePreferencePage_export_error_hidden= 내보내지 못했습니다.\n{0}은(는) 숨겨진 파일입니다.
TemplatePreferencePage_export_error_canNotWrite= 내보내지 못했습니다.\n{0}을(를) 수정할 수 없습니다.
TemplatePreferencePage_export_error_fileNotFound= 내보내기 실패:\n{0}

TemplatePreferencePage_error_parse_message= 템플릿을 구문 분석 할 수 없습니다:\n{0}
TemplatePreferencePage_error_read_message= 템플릿을 읽지 못했습니다.
TemplatePreferencePage_error_write_message= 템플릿을 쓰지 못했습니다.

TemplatePreferencePage_question_create_new_title= 템플릿 편집
TemplatePreferencePage_question_create_new_message= 템플릿 이름이 변경되었습니다. 새로운 이름으로 추가 템플릿을 생성하려면 '예'를, 기존 템플릿의 이름을 바꾸려면 '아니요'를 클릭하십시오.

TemplatePreferencePage_preview=미리 보기(&W):

# edit template dialog
EditTemplateDialog_error_noname=템플릿 이름은 비워 둘 수 없습니다.
EditTemplateDialog_error_adjacent_variables=템플릿 패턴에 인접한 변수가 있습니다.
EditTemplateDialog_title_new=새 템플릿
EditTemplateDialog_title_edit=템플릿 편집

EditTemplateDialog_name=이름(&N):
EditTemplateDialog_description=설명(&D):
EditTemplateDialog_context=컨텍스트(&C):
EditTemplateDialog_pattern=패턴(&P):
EditTemplateDialog_insert_variable=변수 삽입(&V)...

EditTemplateDialog_undo=실행 취소(&U)
EditTemplateDialog_cut=잘라내기(&T)
EditTemplateDialog_copy=복사(&C)
EditTemplateDialog_paste=붙여넣기(&P)
EditTemplateDialog_select_all=모두 선택(&A)
EditTemplateDialog_autoinsert=자동 삽입(&M)
EditTemplateDialog_content_assist=변수 삽입(&V)...

TemplateVariableProposal_error_title=템플릿 변수 제안을 적용하는 중 오류 발생
TemplateVariableProcessor_error_title=템플릿 변수 제안을 생성하는 중 오류 발생

GlobalVariables_variable_description_cursor=템플릿 변수를 편집한 후 커서 위치
GlobalVariables_variable_description_dollar=달러 기호
GlobalVariables_variable_description_date=현재 날짜
GlobalVariables_variable_description_year=현재 연도
GlobalVariables_variable_description_time=현재ㅐ 시간
GlobalVariables_variable_description_user=사용자 이름:
GlobalVariables_variable_description_selectedWord= 선택한 단어
GlobalVariables_variable_description_selectedLines= 선택한 줄
