# preference page
TemplatePreferencePage_error_import=Echec d'importation des modèles.
TemplatePreferencePage_error_export=Echec d'exportation des modèles.
TemplatePreferencePage_error_read_title=Lecture des modèles
TemplatePreferencePage_error_write_title=Ecriture des modèles
TemplatePreferencePage_message=&Créer, modifier ou supprimer des modèles :
TemplatePreferencePage_title=Modèles

TemplatePreferencePage_new=&Nouveau...
TemplatePreferencePage_edit=Modifi&er...
TemplatePreferencePage_import=&Importer...
TemplatePreferencePage_export=E&xporter...
TemplatePreferencePage_remove=Supp&rimer
TemplatePreferencePage_editor=Modèle
TemplatePreferencePage_revert=&Restaurer les paramètres par défaut
TemplatePreferencePage_restore=Restaurer les éléments suppri&més

TemplatePreferencePage_column_name=Nom
TemplatePreferencePage_column_context=Contexte
TemplatePreferencePage_column_description=Description
TemplatePreferencePage_column_autoinsert=Insertion automatique

# on (as the opposite of off)
TemplatePreferencePage_on=le

TemplatePreferencePage_use_code_formatter=Utiliser le &formateur de code

TemplatePreferencePage_import_title=Importation de modèles
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title=Exportation de {0} modèles
TemplatePreferencePage_export_filename=templates.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= Exportation de modèles
TemplatePreferencePage_export_exists_message= {0} existe déjà.\nVoulez-vous le remplacer ?

TemplatePreferencePage_export_error_title= Exportation de modèles
TemplatePreferencePage_export_error_hidden= Echec d'exportation.\n{0} est un fichier caché.
TemplatePreferencePage_export_error_canNotWrite= Echec d'exportation.\n{0} ne peut pas être modifié.
TemplatePreferencePage_export_error_fileNotFound= Echec d'exportation:\n{0}

TemplatePreferencePage_error_parse_message= Impossible d'analyser les modèles :\n{0}
TemplatePreferencePage_error_read_message= Echec de lecture des modèles.
TemplatePreferencePage_error_write_message= Echec d'écriture des modèles.

TemplatePreferencePage_question_create_new_title= Modifier un modèle
TemplatePreferencePage_question_create_new_message= Le nom du modèle a été modifié. Cliquer sur 'Oui' pour créer un modèle supplémentaire sous le nouveau nom ou 'Non' pour renommer le modèle existant.

TemplatePreferencePage_preview=&Aperçu :

# edit template dialog
EditTemplateDialog_error_noname=Le nom du modèle ne peut pas être vide.
EditTemplateDialog_error_adjacent_variables=La correspondance du modèle a des variables adjacentes.
EditTemplateDialog_title_new=Nouveau modèle
EditTemplateDialog_title_edit=Modifier un modèle

EditTemplateDialog_name=&Nom :
EditTemplateDialog_description=&Description :
EditTemplateDialog_context=&Contexte :
EditTemplateDialog_pattern=Corres&pondance :
EditTemplateDialog_insert_variable=Insérer une &variable...

EditTemplateDialog_undo=&Annuler
EditTemplateDialog_cut=Co&uper
EditTemplateDialog_copy=&Copier
EditTemplateDialog_paste=&Coller
EditTemplateDialog_select_all=Sélecti&onner tout
EditTemplateDialog_autoinsert=Insérer auto&matiquement
EditTemplateDialog_content_assist=Insérer une &variable...

TemplateVariableProposal_error_title=Erreur lors de l'application de suggestion de variable de modèle
TemplateVariableProcessor_error_title=Erreur lors de la création de suggestions de variables de modèle

GlobalVariables_variable_description_cursor=Position du curseur après modification de variables de modèle
GlobalVariables_variable_description_dollar=Symbole du dollar
GlobalVariables_variable_description_date=Date du jour
GlobalVariables_variable_description_year=Année en cours
GlobalVariables_variable_description_time=Heure actuelle
GlobalVariables_variable_description_user=Nom d'utilisateur
GlobalVariables_variable_description_selectedWord= Le mot sélectionné
GlobalVariables_variable_description_selectedLines= Les lignes sélectionnées

