# preference page
TemplatePreferencePage_error_import=Error al importar plantillas.
TemplatePreferencePage_error_export=Error al exportar plantillas.
TemplatePreferencePage_error_read_title=Leyendo plantillas
TemplatePreferencePage_error_write_title=Escribiendo plantillas
TemplatePreferencePage_message=&Crear, editar o quitar plantillas:
TemplatePreferencePage_title=Plantillas

TemplatePreferencePage_new=&Nuevo...
TemplatePreferencePage_edit=&Editar...
TemplatePreferencePage_import=&Importar...
TemplatePreferencePage_export=E&xportar...
TemplatePreferencePage_remove=Quita&r
TemplatePreferencePage_editor=Plantilla
TemplatePreferencePage_revert=&Volver a valor predeterminado
TemplatePreferencePage_restore=Restaurar valor eli&minado

TemplatePreferencePage_column_name=Nombre
TemplatePreferencePage_column_context=Contexto
TemplatePreferencePage_column_description=Descripción
TemplatePreferencePage_column_autoinsert=Inserción automática

# on (as the opposite of off)
TemplatePreferencePage_on=el

TemplatePreferencePage_use_code_formatter=Usar &formateador de código

TemplatePreferencePage_import_title=Importación de plantillas
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title=Exportación de {0} plantillas
TemplatePreferencePage_export_filename=plantillas.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= Exportación de plantillas
TemplatePreferencePage_export_exists_message= {0} ya existe.\n¿Desea sustituirlo?

TemplatePreferencePage_export_error_title= Exportación de plantillas
TemplatePreferencePage_export_error_hidden= Error al exportar.\n{0} es un archivo oculto.
TemplatePreferencePage_export_error_canNotWrite= Error al exportar.\n{0} no se puede modificar.
TemplatePreferencePage_export_error_fileNotFound= Error al exportar:\n{0}

TemplatePreferencePage_error_parse_message= Error al analizar plantillas:\n{0}
TemplatePreferencePage_error_read_message= Error al leer plantillas.
TemplatePreferencePage_error_write_message= Error al escribir plantillas.

TemplatePreferencePage_question_create_new_title= Editar plantilla
TemplatePreferencePage_question_create_new_message= El nombre de la plantilla se ha modificado. Haga clic en 'Sí' para crear una plantilla adicional con el nombre nuevo o en 'No' para cambiar el nombre de la existente.

TemplatePreferencePage_preview=&Vista previa:

# edit template dialog
EditTemplateDialog_error_noname=El nombre de la plantilla no puede estar vacío.
EditTemplateDialog_error_adjacent_variables=El patrón de la plantilla tiene variables adyacentes.
EditTemplateDialog_title_new=Nueva plantilla
EditTemplateDialog_title_edit=Editar plantilla

EditTemplateDialog_name=&Nombre:
EditTemplateDialog_description=&Descripción:
EditTemplateDialog_context=&Contexto:
EditTemplateDialog_pattern=&Patrón:
EditTemplateDialog_insert_variable=Insertar &variable...

EditTemplateDialog_undo=&Deshacer
EditTemplateDialog_cut=Cor&tar
EditTemplateDialog_copy=&Copiar
EditTemplateDialog_paste=&Pegar
EditTemplateDialog_select_all=Selecci&onar todo
EditTemplateDialog_autoinsert=Insertar auto&máticamente
EditTemplateDialog_content_assist=Insertar &variable...

TemplateVariableProposal_error_title=Error al aplicar la propuesta de variable de la plantilla
TemplateVariableProcessor_error_title=Error al crear propuestas de variables de plantilla

GlobalVariables_variable_description_cursor=La posición del cursor después de editar las variables de la plantilla
GlobalVariables_variable_description_dollar=El símbolo del dólar
GlobalVariables_variable_description_date=Fecha actual
GlobalVariables_variable_description_year=Año actual
GlobalVariables_variable_description_time=Hora actual
GlobalVariables_variable_description_user=Nombre de usuario
GlobalVariables_variable_description_selectedWord= La palabra seleccionada
GlobalVariables_variable_description_selectedLines= Las líneas seleccionadas

