# preference page
TemplatePreferencePage_error_import=未能导入模板。
TemplatePreferencePage_error_export=未能导出模板。
TemplatePreferencePage_error_read_title=正在读取模板
TemplatePreferencePage_error_write_title=正在写入模板
TemplatePreferencePage_message=创建、编辑或删除模板(&C):
TemplatePreferencePage_title=模板

TemplatePreferencePage_new=新建(&N)...
TemplatePreferencePage_edit=编辑(&E)...
TemplatePreferencePage_import=导入(&I)...
TemplatePreferencePage_export=导出(&X)...
TemplatePreferencePage_remove=删除(&R)
TemplatePreferencePage_editor=模板
TemplatePreferencePage_revert=回复至默认值(&V)
TemplatePreferencePage_restore=复原删除项(&M)

TemplatePreferencePage_column_name=名称
TemplatePreferencePage_column_context=上下文
TemplatePreferencePage_column_description=说明
TemplatePreferencePage_column_autoinsert=自动插入

# on (as the opposite of off)
TemplatePreferencePage_on=位置

TemplatePreferencePage_use_code_formatter=使用代码格式化程序(&F)

TemplatePreferencePage_import_title=正在导入模板
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title=正在导出 {0} 个模板
TemplatePreferencePage_export_filename=templates.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= 正在导出模板
TemplatePreferencePage_export_exists_message= {0} 已存在。\n是否要替换？

TemplatePreferencePage_export_error_title= 正在导出模板
TemplatePreferencePage_export_error_hidden= 导出失败。\n{0} 是隐藏文件。
TemplatePreferencePage_export_error_canNotWrite= 导出失败。\n不能修改 {0}。
TemplatePreferencePage_export_error_fileNotFound= 导出失败:\n{0}

TemplatePreferencePage_error_parse_message= 未能解析模板:\n{0}
TemplatePreferencePage_error_read_message= 未能读取模板。
TemplatePreferencePage_error_write_message= 未能写入模板。

TemplatePreferencePage_question_create_new_title= 编辑模板
TemplatePreferencePage_question_create_new_message= 模板的名称已更改。单击“是”以使用新名称创建另一模板，或单击“否”以重命名现有模板。

TemplatePreferencePage_preview=预览(&W):

# edit template dialog
EditTemplateDialog_error_noname=模板名不能为空。
EditTemplateDialog_error_adjacent_variables=模板模式具有相近变量。
EditTemplateDialog_title_new=新建模板
EditTemplateDialog_title_edit=编辑模板

EditTemplateDialog_name=名称(&N):
EditTemplateDialog_description=说明(&D):
EditTemplateDialog_context=上下文(&C):
EditTemplateDialog_pattern=模式(&P):
EditTemplateDialog_insert_variable=插入变量(&V)...

EditTemplateDialog_undo=撤消(&U)
EditTemplateDialog_cut=剪切(&T)
EditTemplateDialog_copy=复制(&C)
EditTemplateDialog_paste=粘贴(&P)
EditTemplateDialog_select_all=全选(&A)
EditTemplateDialog_autoinsert=自动插入(&M)
EditTemplateDialog_content_assist=插入变量(&V)...

TemplateVariableProposal_error_title=应用模板变量建议时出错
TemplateVariableProcessor_error_title=创建模板变量建议时出错

GlobalVariables_variable_description_cursor=编辑模板变量之后的游标位置
GlobalVariables_variable_description_dollar=美元符号
GlobalVariables_variable_description_date=当前日期
GlobalVariables_variable_description_year=当前年份
GlobalVariables_variable_description_time=当前时间
GlobalVariables_variable_description_user=用户名
GlobalVariables_variable_description_selectedWord= 所选单词
GlobalVariables_variable_description_selectedLines= 所选行
