# preference page
TemplatePreferencePage_error_import=テンプレートをインポートできません。
TemplatePreferencePage_error_export=テンプレートをエクスポートできません。
TemplatePreferencePage_error_read_title=テンプレートの読み取り
TemplatePreferencePage_error_write_title=テンプレートの書き込み
TemplatePreferencePage_message=テンプレートの作成・編集・削除(&C) :
TemplatePreferencePage_title=テンプレート

TemplatePreferencePage_new=新規(&N)...
TemplatePreferencePage_edit=編集(&E)...
TemplatePreferencePage_import=インポート(&I)...
TemplatePreferencePage_export=エクスポート(&X)...
TemplatePreferencePage_remove=削除(&R)
TemplatePreferencePage_editor=テンプレート
TemplatePreferencePage_revert=デフォルトに戻す(&V)
TemplatePreferencePage_restore=削除した内容を元に戻す(&M)

TemplatePreferencePage_column_name=名前
TemplatePreferencePage_column_context=コンテキスト
TemplatePreferencePage_column_description=説明
TemplatePreferencePage_column_autoinsert=自動挿入

# on (as the opposite of off)
TemplatePreferencePage_on=オン

TemplatePreferencePage_use_code_formatter=コードフォーマッタを使用する(&F)

TemplatePreferencePage_import_title=テンプレートをインポート中
TemplatePreferencePage_import_extension=*.xml

TemplatePreferencePage_export_title={0} 個のテンプレートをエクスポート中
TemplatePreferencePage_export_filename=templates.xml
TemplatePreferencePage_export_extension=*.xml

TemplatePreferencePage_export_exists_title= テンプレートをエクスポート中
TemplatePreferencePage_export_exists_message= {0} はすでに存在します。\n置き換えますか ?

TemplatePreferencePage_export_error_title= テンプレートをエクスポート中
TemplatePreferencePage_export_error_hidden= エクスポートできません。\n{0} は隠しファイルです。
TemplatePreferencePage_export_error_canNotWrite= エクスポートできません。\n{0} は変更できません。
TemplatePreferencePage_export_error_fileNotFound= エクスポートできません :\n{0}

TemplatePreferencePage_error_parse_message= テンプレートを解析できません :\n{0}
TemplatePreferencePage_error_read_message= テンプレートを読み取れません。
TemplatePreferencePage_error_write_message= テンプレートを書き込めません。

TemplatePreferencePage_question_create_new_title= テンプレートの編集
TemplatePreferencePage_question_create_new_message= テンプレートの名前が変更されました。テンプレートを別の名前で新規に作成する場合は [はい] を、既存の名前を変更する場合は [いいえ] をクリックしてください。

TemplatePreferencePage_preview=プレビュー(&W) :

# edit template dialog
EditTemplateDialog_error_noname=テンプレート名を空白にすることはできません。
EditTemplateDialog_error_adjacent_variables=テンプレートのパターンに隣接する変数があります。
EditTemplateDialog_title_new=新規テンプレート
EditTemplateDialog_title_edit=テンプレートの編集

EditTemplateDialog_name=名前(&N) :
EditTemplateDialog_description=説明(&D) :
EditTemplateDialog_context=コンテキスト(&C) :
EditTemplateDialog_pattern=パターン(&P) :
EditTemplateDialog_insert_variable=変数の挿入(&V)...

EditTemplateDialog_undo=元に戻す(&U)
EditTemplateDialog_cut=切り取り(&T)
EditTemplateDialog_copy=コピー(&C)
EditTemplateDialog_paste=貼り付け(&P)
EditTemplateDialog_select_all=すべて選択(&A)
EditTemplateDialog_autoinsert=自動挿入(&M)
EditTemplateDialog_content_assist=変数の挿入(&V)...

TemplateVariableProposal_error_title=テンプレート変数の提案の適用エラー
TemplateVariableProcessor_error_title=テンプレート変数の提案の作成エラー

GlobalVariables_variable_description_cursor=テンプレート変数を編集した後のカーソル位置
GlobalVariables_variable_description_dollar=ドル記号
GlobalVariables_variable_description_date=現在の日付
GlobalVariables_variable_description_year=当年
GlobalVariables_variable_description_time=現在の時刻
GlobalVariables_variable_description_user=ユーザ名
GlobalVariables_variable_description_selectedWord= 選択した語
GlobalVariables_variable_description_selectedLines= 選択した行
