#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=DTP ODA 设计者 UI 框架插件
oda.parent.category.name=ODA 数据源
oda.preference.page.name=开放数据访问
providerName=Eclipse Data Tools Platform
