#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=Plug-in Infraestructura de UI de diseñador ODA de DTP
oda.parent.category.name=Orígenes de datos de ODA
oda.preference.page.name=Acceso a datos abiertos
providerName=Eclipse Data Tools Platform
