###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=Plug-in mit Benutzerschnittstellenframework für DTP-ODA-Entwurfsfunktion
oda.parent.category.name=ODA-Datenquellen
oda.preference.page.name=Open Data Access
