#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=DTP ODA Designer UI Framework Plug-in
oda.parent.category.name=ODA データ・ソース
oda.preference.page.name=オープンデータアクセス
providerName=Eclipse Data Tools Platform
