###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=Plug-in de la structure d'interface utilisateur du concepteur ODA DTP
oda.parent.category.name=Sources de données ODA
oda.preference.page.name=Accès aux données ouvertes
