#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Profile Configuration for all ODA profile extensions
#
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS Strings
###############################################################################
#
plugin.name=DTP ODA 디자이너 UI 프레임워크 플러그인
oda.parent.category.name=ODA 데이터 소스
oda.preference.page.name=개방형 데이터 액세스
providerName=Eclipse Data Tools Platform
