###############################################################################
# Copyright (c) 2001, 2004, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Plug-in Derby pour plate-forme d'outils de données Eclipse
providerName = Eclipse Data Tools Platform

DERBY_CONNECTION_PROFILE_NAME=Base de données intégrée Derby
DERBY_JDBC_CONNECTION_FACTORY_NAME=Connexion JDBC
DERBY_PING_CONNECTION_FACTORY_NAME=Génération de connexion Ping
DERBY_SQL_MODEL_CONNECTION_FACTORY_NAME=Connexion du modèle SQL
DRIVER_CLASS_PROPERTY_NAME=Classe de pilote
VENDOR_PROPERTY_NAME=Vendeur
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Nom de la base de données
CONNECTION_URL_PROPERTY_NAME=URL de connexion
USER_ID_PROPERTY_NAME=ID utilisateur
PASSWORD_PROPERTY_NAME=Mot de passe

DERBY_CATEGORY_NAME=Derby
10_0_VERSION_CATEGORY_NAME = 10.0
10_1_VERSION_CATEGORY_NAME = 10.1
10_2_VERSION_CATEGORY_NAME = 10.2

DERBY_EMBEDDED_DRIVER_TEMPLATE_NAME=Pilote JDBC intégré Derby
DERBY_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Pilote 10.0 JDBC intégré Derby
DERBY_OTHER_DRIVER_TEMPLATE_NAME = Autre pilote
DERBY101_EMBEDDED_DRIVER_TEMPLATE_NAME=Pilote JDBC intégré Derby
DERBY101_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Pilote 10.1 JDBC intégré Derby
DERBY_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=Pilote de serveur de données IBM pour JDBC et SQLJ
DERBY101_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=Pilote de serveur de données IBM pour JDBC et SQLJ
DERBY101_CLIENT_DRIVER_TEMPLATE_NAME = Pilote JDBC Client Derby
DERBY101_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Pilote 10.1 JDBC Client Derby
DERBY101_OTHER_DRIVER_TEMPLATE_NAME = Autre pilote
DERBY102_EMBEDDED_DRIVER_TEMPLATE_NAME=Pilote JDBC intégré Derby
DERBY102_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Pilote 10.2 JDBC intégré Derby
DERBY102_CLIENT_DRIVER_TEMPLATE_NAME = Pilote JDBC Client Derby
DERBY102_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Pilote 10.2 JDBC Client Derby
DERBY102_OTHER_DRIVER_TEMPLATE_NAME = Autre pilote
