###############################################################################
# Copyright (c) 2001, 2004, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Eclipse-Datentools-Plattform Derby Plug-In
providerName = Eclipse Data Tools Platform

DERBY_CONNECTION_PROFILE_NAME=Derby eingebettete Datenbank
DERBY_JDBC_CONNECTION_FACTORY_NAME=JDBC-Verbindung
DERBY_PING_CONNECTION_FACTORY_NAME=Ping-Verbindungs-Factory
DERBY_SQL_MODEL_CONNECTION_FACTORY_NAME=SQL- Modell Verbindung
DRIVER_CLASS_PROPERTY_NAME=Treiberklasse
VENDOR_PROPERTY_NAME=Anbieter
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Datenbankname
CONNECTION_URL_PROPERTY_NAME=Verbindungs-URL
USER_ID_PROPERTY_NAME=Benutzer-ID
PASSWORD_PROPERTY_NAME=Kennwort

DERBY_CATEGORY_NAME=Derby
10_0_VERSION_CATEGORY_NAME = 10.0
10_1_VERSION_CATEGORY_NAME = 10.1
10_2_VERSION_CATEGORY_NAME = 10.2

DERBY_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby eingebetteter JDBC-Treiber
DERBY_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby eingebetteter JDBC-Treiber 10.0
DERBY_OTHER_DRIVER_TEMPLATE_NAME = Anderer Treiber
DERBY101_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby eingebetteter JDBC-Treiber
DERBY101_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby eingebetteter JDBC-Treiber 10.1
DERBY_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=IBM Data Server Treiber für JDBC und SQLJ
DERBY101_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=IBM Data Server Treiber für JDBC und SQLJ
DERBY101_CLIENT_DRIVER_TEMPLATE_NAME = Derby Client JDBC-Treiber
DERBY101_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby Client JDBC-Treiber 10.1
DERBY101_OTHER_DRIVER_TEMPLATE_NAME = Anderer Treiber
DERBY102_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby eingebetteter JDBC-Treiber
DERBY102_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby eingebetteter JDBC-Treiber 10.2
DERBY102_CLIENT_DRIVER_TEMPLATE_NAME = Derby Client JDBC-Treiber
DERBY102_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby Client JDBC-Treiber 10.2
DERBY102_OTHER_DRIVER_TEMPLATE_NAME = Anderer Treiber
