###############################################################################
# Copyright (c) 2001, 2004, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Complemento Derby para Eclipse Data Tools Platform
providerName = Eclipse Data Tools Platform

DERBY_CONNECTION_PROFILE_NAME=Base de datos incrustada de Derby
DERBY_JDBC_CONNECTION_FACTORY_NAME=Conexión JDBC
DERBY_PING_CONNECTION_FACTORY_NAME=Fábrica de conexión de ping
DERBY_SQL_MODEL_CONNECTION_FACTORY_NAME=Conexión de modelo SQL
DRIVER_CLASS_PROPERTY_NAME=Clase de controlador
VENDOR_PROPERTY_NAME=Proveedor
VERSION_PROPERTY_NAME=Versión
DATABASE_NAME_PROPERTY_NAME=Nombre de base de datos
CONNECTION_URL_PROPERTY_NAME=URL de conexión
USER_ID_PROPERTY_NAME=Identificador de usuario
PASSWORD_PROPERTY_NAME=Contraseña

DERBY_CATEGORY_NAME=Derby
10_0_VERSION_CATEGORY_NAME = 10.0
10_1_VERSION_CATEGORY_NAME = 10.1
10_2_VERSION_CATEGORY_NAME = 10.2

DERBY_EMBEDDED_DRIVER_TEMPLATE_NAME=Controlador JDBC incrustado de Derby
DERBY_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Controlador JDBC incrustado de Derby 10.0
DERBY_OTHER_DRIVER_TEMPLATE_NAME = Otro controlador
DERBY101_EMBEDDED_DRIVER_TEMPLATE_NAME=Controlador JDBC incrustado de Derby
DERBY101_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Controlador JDBC incrustado de Derby 10.1
DERBY_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=Controlador de servidor de datos de IBM para JDBC y SQLJ
DERBY101_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=Controlador de servidor de datos de IBM para JDBC y SQLJ
DERBY101_CLIENT_DRIVER_TEMPLATE_NAME = Controlador JDBC de cliente de Derby
DERBY101_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Controlador JDBC de cliente de Derby 10.1
DERBY101_OTHER_DRIVER_TEMPLATE_NAME = Otro controlador
DERBY102_EMBEDDED_DRIVER_TEMPLATE_NAME=Controlador JDBC incrustado de Derby
DERBY102_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Controlador JDBC incrustado de Derby 10.2
DERBY102_CLIENT_DRIVER_TEMPLATE_NAME = Controlador JDBC de cliente de Derby
DERBY102_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Controlador JDBC de cliente de Derby 10.2
DERBY102_OTHER_DRIVER_TEMPLATE_NAME = Otro controlador
