###############################################################################
# Copyright (c) 2001, 2004, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Eclipse 数据工具平台 Derby 插件
providerName = Eclipse.org

DERBY_CONNECTION_PROFILE_NAME=Derby 嵌入式数据库
DERBY_JDBC_CONNECTION_FACTORY_NAME=JDBC 连接
DERBY_PING_CONNECTION_FACTORY_NAME=Ping 连接 Factory
DERBY_SQL_MODEL_CONNECTION_FACTORY_NAME=SQL 模型连接
DRIVER_CLASS_PROPERTY_NAME=驱动程序类
VENDOR_PROPERTY_NAME=供应商
VERSION_PROPERTY_NAME=版本
DATABASE_NAME_PROPERTY_NAME=数据库名称
CONNECTION_URL_PROPERTY_NAME=连接 URL
USER_ID_PROPERTY_NAME=用户 ID
PASSWORD_PROPERTY_NAME=密码

DERBY_CATEGORY_NAME=Derby
10_0_VERSION_CATEGORY_NAME = 10.0
10_1_VERSION_CATEGORY_NAME = 10.1
10_2_VERSION_CATEGORY_NAME = 10.2

DERBY_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 嵌入式 JDBC 驱动程序
DERBY_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 嵌入式 JDBC 驱动程序 10.0
DERBY_OTHER_DRIVER_TEMPLATE_NAME = 其他驱动程序
DERBY101_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 嵌入式 JDBC 驱动程序
DERBY101_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 嵌入式 JDBC 驱动程序 10.1
DERBY_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=IBM Data Server Driver for JDBC and SQLJ
DERBY101_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=IBM Data Server Driver for JDBC and SQLJ
DERBY101_CLIENT_DRIVER_TEMPLATE_NAME = Derby 客户机 JDBC 驱动程序
DERBY101_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby 客户机 JDBC 驱动程序 10.1
DERBY101_OTHER_DRIVER_TEMPLATE_NAME = 其他驱动程序
DERBY102_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 嵌入式 JDBC 驱动程序
DERBY102_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 嵌入式 JDBC 驱动程序 10.2
DERBY102_CLIENT_DRIVER_TEMPLATE_NAME = Derby 客户机 JDBC 驱动程序
DERBY102_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby 客户机 JDBC 驱动程序 10.2
DERBY102_OTHER_DRIVER_TEMPLATE_NAME = 其他驱动程序
