###############################################################################
# Copyright (c) 2001, 2004, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Eclipse Data Tools Platform Derby 플러그인
providerName = Eclipse.org

DERBY_CONNECTION_PROFILE_NAME=Derby 임베디드 데이터베이스
DERBY_JDBC_CONNECTION_FACTORY_NAME=JDBC 연결
DERBY_PING_CONNECTION_FACTORY_NAME=핑 연결 팩토리
DERBY_SQL_MODEL_CONNECTION_FACTORY_NAME=SQL 모델 연결
DRIVER_CLASS_PROPERTY_NAME=드라이버 클래스
VENDOR_PROPERTY_NAME=공급업체
VERSION_PROPERTY_NAME=버전
DATABASE_NAME_PROPERTY_NAME=데이터베이스 이름
CONNECTION_URL_PROPERTY_NAME=연결 URL
USER_ID_PROPERTY_NAME=사용자 ID
PASSWORD_PROPERTY_NAME=암호

DERBY_CATEGORY_NAME=Derby
10_0_VERSION_CATEGORY_NAME = 10.0
10_1_VERSION_CATEGORY_NAME = 10.1
10_2_VERSION_CATEGORY_NAME = 10.2

DERBY_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 임베디드 JDBC 드라이버
DERBY_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 임베디드 JDBC 드라이버 10.0
DERBY_OTHER_DRIVER_TEMPLATE_NAME = 기타 드라이버
DERBY101_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 임베디드 JDBC 드라이버
DERBY101_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 임베디드 JDBC 드라이버 10.1
DERBY_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=JDBC 및 SQLJ용 IBM 데이터 서버 드라이버
DERBY101_NETWORK_EMBEDDED_DRIVER_TEMPLATE_NAME=JDBC 및 SQLJ용 IBM 데이터 서버 드라이버
DERBY101_CLIENT_DRIVER_TEMPLATE_NAME = Derby 클라이언트 JDBC 드라이버
DERBY101_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby 클라이언트 JDBC 드라이버 10.1
DERBY101_OTHER_DRIVER_TEMPLATE_NAME = 기타 드라이버
DERBY102_EMBEDDED_DRIVER_TEMPLATE_NAME=Derby 임베디드 JDBC 드라이버
DERBY102_EMBEDDED_DRIVER_DEFAULT_INSTANCE_NAME=Derby 임베디드 JDBC 드라이버 10.2
DERBY102_CLIENT_DRIVER_TEMPLATE_NAME = Derby 클라이언트 JDBC 드라이버
DERBY102_CLIENT_DRIVER_DEFAULT_INSTANCE_NAME = Derby 클라이언트 JDBC 드라이버 10.2
DERBY102_OTHER_DRIVER_TEMPLATE_NAME = 기타 드라이버
