###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = DB2 para z/OS
V7VersionString = V7

V8CompatibilityProductString = DB2 para z/OS
V8CompatibilityVersionString = V8 (modo de compatibilidad)

V8NewFunctionProductString = DB2 para z/OS
V8NewFunctionVersionString = V8 (modo de nueva función)

V7Description = IBM DB2 UDB para z/OS y OS 390 versión 7
V8CompatibilityDescription = IBM DB2 UDB para z/OS versión 8 en modo de compatibilidad
V8NewFunctionDescription = IBM DB2 UDB para z/OS versión 8 en modo de nueva función

V9CompatibilityDescription = IBM DB2 para z/OS versión 9.1 en modo de conversión
V9CompatibilityProductString = DB2 para z/OS
V9CompatibilityVersionString = V9.1 (modo de conversión)

V9NewFunctionDescription = IBM DB2 para z/OS versión 9.1 en modo de nueva función
V9NewFunctionProductString = DB2 para z/OS
V9NewFunctionVersionString = V9.1 (modo de nueva función)
