###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = DB2 for z/OS
V7VersionString = V7

V8CompatibilityProductString = DB2 for z/OS
V8CompatibilityVersionString = V8（兼容性方式）

V8NewFunctionProductString = DB2 for z/OS
V8NewFunctionVersionString = V8（新功能方式）

V7Description = IBM DB2 UDB for z/OS and OS 390 版本 7
V8CompatibilityDescription = IBM DB2 UDB for z/OS 版本 8（兼容模式）
V8NewFunctionDescription = IBM DB2 UDB for z/OS 版本 8（新功能模式）

V9CompatibilityDescription = IBM DB2 for z/OS 9.1 版(转换模式)
V9CompatibilityProductString = DB2 for z/OS
V9CompatibilityVersionString = V9.1(转换模式)

V9NewFunctionDescription = IBM DB2 for z/OS 9.1 版(新功能模式)
V9NewFunctionProductString = DB2 for z/OS
V9NewFunctionVersionString = V9.1 (新功能模式)
