###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = DB2 für z/OS
V7VersionString = V7

V8CompatibilityProductString = DB2 für z/OS
V8CompatibilityVersionString = V8 (Kompatibilitätsmodus)

V8NewFunctionProductString = DB2 für z/OS
V8NewFunctionVersionString = V8 (New-Function-Modus)

V7Description = IBM DB2 UDB für z/OS und OS 390 Version 7
V8CompatibilityDescription = IBM DB2 UDB für z/OS Version 8 im Kompatibilitätsmodus
V8NewFunctionDescription = IBM DB2 UDB für z/OS Version 8 im New-Function-Modus

V9CompatibilityDescription = IBM DB2 für z/OS Version 9.1 im Konversionsmodus
V9CompatibilityProductString = DB2 für z/OS
V9CompatibilityVersionString = V9.1 (Konversionsmodus)

V9NewFunctionDescription = IBM DB2 UDB für z/OS Version 9.1 im New-Function-Modus
V9NewFunctionProductString = DB2 für z/OS
V9NewFunctionVersionString = V9.1 (New-Function-Modus)
