###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = z/OS용 DB2
V7VersionString = V7

V8CompatibilityProductString = z/OS용 DB2
V8CompatibilityVersionString = V8(호환 모드)

V8NewFunctionProductString = z/OS용 DB2
V8NewFunctionVersionString = V8(새 기능 모드)

V7Description = z/OS 및 OS 390 버전 7용 IBM DB2 UDB
V8CompatibilityDescription = z/OS 버전 8 호환 모드용 IBM DB2 UDB
V8NewFunctionDescription = z/OS 버전 8 새 기능 모드용 IBM DB2 UDB

V9CompatibilityDescription = z/OS 버전 9.1 변환 모드용 IBM DB2
V9CompatibilityProductString = z/OS용 DB2
V9CompatibilityVersionString = V9.1(변환 모드)

V9NewFunctionDescription = z/OS 버전 9.1 새 기능 모드용 IBM DB2
V9NewFunctionProductString = z/OS용 DB2
V9NewFunctionVersionString = V9.1(새 기능 모드)
