###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = DB2 pour z/OS
V7VersionString = V7

V8CompatibilityProductString = DB2 pour z/OS
V8CompatibilityVersionString = V8 (mode Compatibilité)

V8NewFunctionProductString = DB2 pour z/OS
V8NewFunctionVersionString = V8 (mode Nouvelle fonction)

V7Description = DB2 UDB IBM pour z/OS et OS 390 Version 7
V8CompatibilityDescription = DB2 UDB IBM pour z/OS Version 8 en mode Compatibilité
V8NewFunctionDescription = DB2 UDB IBM pour z/OS Version 8 en mode Nouvelle fonction

V9CompatibilityDescription = IBM DB2 pour z/OS, version 9.1, en mode Conversion
V9CompatibilityProductString = DB2 pour z/OS
V9CompatibilityVersionString = V9.1 (mode Conversion)

V9NewFunctionDescription = IBM DB2 pour z/OS, version 9.1, en mode New-function
V9NewFunctionProductString = DB2 pour z/OS
V9NewFunctionVersionString = V9.1 (mode New-function)
