###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V7ProductString = DB2 pour z/OS
V7VersionString = V7

V8CompatibilityProductString = DB2 pour z/OS
V8CompatibilityVersionString = V8 (mode Compatibilité)

V8NewFunctionProductString = DB2 pour z/OS
V8NewFunctionVersionString = V8 (mode Nouvelle fonction)

V7Description = DB2 UDB IBM pour z/OS et OS 390 Version 7
V8CompatibilityDescription = DB2 UDB IBM pour z/OS Version 8 en mode Compatibilité
V8NewFunctionDescription = DB2 UDB IBM pour z/OS Version 8 en mode Nouvelle fonction

V9CompatibilityDescription = IBM DB2 for z/OS Version 9.1 in conversion mode
V9CompatibilityProductString = DB2 pour z/OS
V9CompatibilityVersionString = V9.1 (Conversion Mode)

V9NewFunctionDescription = IBM DB2 for z/OS Version 9.1 in new-function mode
V9NewFunctionProductString = DB2 pour z/OS
V9NewFunctionVersionString = V9.1 (New-Function Mode)
