###############################################################################
# Copyright (c) 2001, 2004, 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
##
###
##  !!! This property file should only contain resources that are "translatable" !!!
###
##

#
## Loading support
#
DATATOOLS.SERVER.UI.EXPLORER.LOADING = Cargando proveedor {0}
DATATOOLS.SERVER.UI.EXPLORER.REMOVING_PLACE_HOLDER=Eliminando marcador de posición...
DATATOOLS.SERVER.UI.EXPLORER.DESCRIPTION = Principal

#
## Actions
#
DATATOOLS.SERVER.UI.EXPLORER.CONNECT_SERVER = Añadir conexión al servidor
DATATOOLS.SERVER.UI.EXPLORER.DISCONNECT_SERVER = Desconectar servidor
DATATOOLS.SERVER.UI.EXPLORER.LAYOUT_OPTIONS = diseño
DATATOOLS.SERVER.UI.EXPLORER.VIRTUAL_FOLDER = Carpeta virtual
DATATOOLS.SERVER.UI.EXPLORER.HIERARCHICAL = Jerárquico
DATATOOLS.SERVER.UI.EXPLORER.COLLAPSE_ALL = Contraer todo
DATATOOLS.SERVER.UI.EXPLORER.REFRESH = Actua&lizar

#
## Filtering Decoration
#
DATATOOLS.SERVER.UI.EXPLORER.FILTER_DECORATION = [Filtrado]
DATATOOLS.SERVER.UI.EXPLORER.FILTER = Filtrar
#
## Developer Actions
#
DATATOOLS.SERVER.UI.DEVELOPER.ADD_TABLE = Añadir tabla

#
## Delete Connection Warning
#
DATATOOLS.SERVER.UI.DELETE_CONNECTION_TITLE = Eliminar conexión
DATATOOLS.SERVER.UI.DELETE_CONNECTION_MANY = Los proyectos de Eclipse siguientes: {0} dependen de esta conexión.\n\n¿Está seguro de que desea eliminar la conexión "{1}"?
DATATOOLS.SERVER.UI.DELETE_CONNECTION_ONE = El proyecto de Eclipse siguiente: {0} depende de esta conexión.\n\n¿Está seguro de que desea eliminar la conexión "{1}"?

#
## Add New Server Dialog
#
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_TITLE = Añadir conexión al servidor
DATATOOLS.SERVER.UI.DATABASE_TYPE = Tipo de base de datos:
DATATOOLS.SERVER.UI.DATABASE_VERSION = Versión de base de datos:
DATATOOLS.SERVER.UI.SELECT_DATABASE = Seleccione o introduzca el nombre de la base de datos:
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_ENTER_INFO=Introduzca la información de la conexión
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_CONNECTING=Conectándose al servidor...
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_FAILURE=Error al conectarse al servidor
DATATOOLS.SERVER.UI.IDENTIFICATION_LABEL = Identificación de la conexión del servidor
DATATOOLS.SERVER.UI.PROVIDER_NOT_FOUND = Aún no se ha implementado ningún proveedor
DATATOOLS.SERVER.UI.EXPLORER.NULL_CONNECTION = Conexión no establecida
DATATOOLS.SERVER.UI.EXPLORER.CONNECTION_EXCEPTION = Excepción de conexión SQL con {0}
DATATOOLS.SERVER.UI.USER_NAME_LABEL = Identificador de usuario:
DATATOOLS.SERVER.UI.PASSWORD_LABEL = Contraseña:
_UI_DIALOG_CONNECTION_TITLE  = Nueva conexión

#
## Error Connection Dialog
#
DATATOOLS.SERVER.UI.CONNECTION.ERROR.TITLE = Excepción de conexión no válida
#Removed for bug 285485
#DATATOOLS.SERVER.UI.CONNECTION.ERROR.MESSAGE = Error en la conexión
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.TITLE = Notificación de excepción SQL
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.RECONNECT = Volver a conectarse
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.DISCONNECT = Desconectarse
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.IGNORE = Omitir
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.MESSAGE = Efectúe una de las acciones propuestas:
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.SQLMESSAGE = Se ha detectado una excepción SQL durante esta operación.
 
#
## Server Disconnect
#
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_TITLE = Selección de conexión
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_SELECTION = Seleccione una conexión:
DATATOOLS.SERVER.UI.DISCONNECT_CONNECTED_SERVERS = Conexiones disponibles

#
## Server Explorer Nodes
#
DATATOOLS.SERVER.UI.EXPLORER.KNOWN_SERVERS=Conexiones
DATATOOLS.SERVER.UI.EXPLORER.DISC_SERVERS=Alias descubiertos
DATATOOLS.SERVER.UI.EXPLORER.SCHEMA=Esquemas
DATATOOLS.SERVER.UI.EXPLORER.DATABASE=Bases de datos
DATATOOLS.SERVER.UI.EXPLORER.TABLE=Tablas
DATATOOLS.SERVER.UI.EXPLORER.ROUTINE=Rutinas
DATATOOLS.SERVER.UI.EXPLORER.SEQUENCE=Secuencias
DATATOOLS.SERVER.UI.EXPLORER.UDT=Tipos definidos por el usuario
DATATOOLS.SERVER.UI.EXPLORER.VIEW= Vistas
DATATOOLS.SERVER.UI.EXPLORER.TRIGGER= Activadores
DATATOOLS.SERVER.UI.EXPLORER.INDEX=Índices
DATATOOLS.SERVER.UI.EXPLORER.CONSTRAINT=Restricciones
DATATOOLS.SERVER.UI.EXPLORER.COLUMN=Columnas
DATATOOLS.SERVER.UI.EXPLORER.PROXY=Proxy
DATATOOLS.SERVER.UI.EXPLORER.DEPENDENCY= Dependencias
DATATOOLS.SERVER.UI.EXPLORER.EXTERNAL_DEPENDENCY = Dependencia externa
DATATOOLS.SERVER.UI.EXPLORER.DB2_CLOUDSCAPE = localhost [DB2 Cloudscape]
DATATOOLS.SERVER.UI.EXPLORER.STORED_PROCEDURE=Stored Procedures
DATATOOLS.SERVER.UI.EXPLORER.UDF=Funciones definidas por el usuario
DATATOOLS.SERVER.UI.EXPLORER.CATALOG=Catálogos
DATATOOLS.SERVER.UI.EXPLORER.AUTH_ID = ID de autorización
DATATOOLS.SERVER.UI.EXPLORER.USER = Usuarios
DATATOOLS.SERVER.UI.EXPLORER.GROUP = Grupos
DATATOOLS.SERVER.UI.EXPLORER.ROLE = Funciones

#
## Update Offline Items
#
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE = &Guardar sin conexión
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE = &Trabajar sin conexión
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE_JOB = Guardar sin conexión
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE_JOB = Trabajar sin conexión
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.MESSAGE = El contenido sin conexión no se ha encontrado en su espacio de trabajo.\nEjecute "Guardar sin conexión" cuando esté conectado.
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.TITLE = Error en la conexión
#Removed for bug 285485
#DATATOOLS.SERVER.UI.CONNECTION.ERROR.MESSAGE = Error en la conexión

#
## Bookmark
#
DATATOOLS.SERVER.UI.BOOKMARK.TITLE=Añadir marcador
DATATOOLS.SERVER.UI.BOOKMARK.MESSAGE=Introducir nombre de marcador:


SQL_MODEL_CONTENT_EXTENSION_LABEL=Contenido del modelo SQL








