###############################################################################
# Copyright (c) 2001, 2004, 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
##
###
##  !!! This property file should only contain resources that are "translatable" !!!
###
##

#
## Loading support
#
DATATOOLS.SERVER.UI.EXPLORER.LOADING = Provider {0} laden
DATATOOLS.SERVER.UI.EXPLORER.REMOVING_PLACE_HOLDER=Platzhalter entfernen ...
DATATOOLS.SERVER.UI.EXPLORER.DESCRIPTION = Core

#
## Actions
#
DATATOOLS.SERVER.UI.EXPLORER.CONNECT_SERVER = Serververbindung hinzufügen
DATATOOLS.SERVER.UI.EXPLORER.DISCONNECT_SERVER = Server trennen
DATATOOLS.SERVER.UI.EXPLORER.LAYOUT_OPTIONS = Layout
DATATOOLS.SERVER.UI.EXPLORER.VIRTUAL_FOLDER = Virtueller Ordner
DATATOOLS.SERVER.UI.EXPLORER.HIERARCHICAL = Hierarchisch
DATATOOLS.SERVER.UI.EXPLORER.COLLAPSE_ALL = Alle ausblenden
DATATOOLS.SERVER.UI.EXPLORER.REFRESH = &Aktualisieren
DATATOOLS.SERVER.UI.EXPLORER.PROPERTIES = &Eigenschaften
DATATOOLS.SERVER.UI.EXPLORER.PROPERTIES_DIALOG_TITLE = Filtereigenschaften

#
## Filtering Decoration
#
DATATOOLS.SERVER.UI.EXPLORER.FILTER_DECORATION = [Gefiltert]
DATATOOLS.SERVER.UI.EXPLORER.FILTER = Filter
#
## Developer Actions
#
DATATOOLS.SERVER.UI.DEVELOPER.ADD_TABLE = Tabelle hinzufügen

#
## Delete Connection Warning
#
DATATOOLS.SERVER.UI.DELETE_CONNECTION_TITLE = Verbindung löschen
DATATOOLS.SERVER.UI.DELETE_CONNECTION_MANY = Die folgenden Eclipse-Projekte: {0} sind von dieser Verbindung abhängig.\n\nSind Sie sicher, dass Sie die Verbindung löschen möchten "{1}"?
DATATOOLS.SERVER.UI.DELETE_CONNECTION_ONE = Das folgende Eclipse-Projekt: {0} ist von dieser Verbindung abhängig.\n\nSind Sie sicher, dass Sie die Verbindung löschen möchten "{1}"?

#
## Add New Server Dialog
#
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_TITLE = Serververbindung hinzufügen
DATATOOLS.SERVER.UI.DATABASE_TYPE = Datenbanktyp:
DATATOOLS.SERVER.UI.DATABASE_VERSION = Datenbankversion:
DATATOOLS.SERVER.UI.SELECT_DATABASE = Wählen Sie den Datenbanknamen aus oder geben Sie diesen ein:
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_ENTER_INFO=Geben Sie die Verbindungsinformationen ein.
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_CONNECTING=Verbindung zum Server wird hergestellt...
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_FAILURE=Verbindungsaufnahme zum Server fehlgeschlagen
DATATOOLS.SERVER.UI.IDENTIFICATION_LABEL = Server-Verbindungsidentifikation
DATATOOLS.SERVER.UI.PROVIDER_NOT_FOUND = Es wurde noch kein Provider eingesetzt
DATATOOLS.SERVER.UI.EXPLORER.NULL_CONNECTION = Die Verbindung ist nicht eingerichtet
DATATOOLS.SERVER.UI.EXPLORER.CONNECTION_EXCEPTION = SQL-Verbindung – Ausnahmefehler mit {0}
DATATOOLS.SERVER.UI.USER_NAME_LABEL = Benutzer-ID:
DATATOOLS.SERVER.UI.PASSWORD_LABEL = Kennwort:
_UI_DIALOG_CONNECTION_TITLE  = Neue Verbindung

#
## Error Connection Dialog
#
DATATOOLS.SERVER.UI.CONNECTION.ERROR.TITLE = Ungültige Verbindung – Ausnahmefehler
#Removed for bug 285485
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.TITLE = SQL-Ausnahmefehler – Benachrichtigung
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.RECONNECT = Verbindung wiederherstellen
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.DISCONNECT = Verbindung trennen
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.IGNORE = Ignorieren
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.MESSAGE = Führen Sie eine der vorgeschlagenen Aktionen durch:
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.SQLMESSAGE = Ein SQL-Ausnahmefehler wurde während dieses Vorgangs berichtet.
 
#
## Server Disconnect
#
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_TITLE = Verbindungsauswahl
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_SELECTION = Wählen Sie eine Verbindung aus:
DATATOOLS.SERVER.UI.DISCONNECT_CONNECTED_SERVERS = Verfügbare Verbindungen

#
## Server Explorer Nodes
#
DATATOOLS.SERVER.UI.EXPLORER.KNOWN_SERVERS=Verbindungen
DATATOOLS.SERVER.UI.EXPLORER.DISC_SERVERS=Entdeckte Aliase
DATATOOLS.SERVER.UI.EXPLORER.SCHEMA=Schemata
DATATOOLS.SERVER.UI.EXPLORER.DATABASE=Datenbanken
DATATOOLS.SERVER.UI.EXPLORER.TABLE=Tabellen
DATATOOLS.SERVER.UI.EXPLORER.ROUTINE=Routinen
DATATOOLS.SERVER.UI.EXPLORER.SEQUENCE=Sequenzen
DATATOOLS.SERVER.UI.EXPLORER.UDT=Benutzerdefinierte Typen
DATATOOLS.SERVER.UI.EXPLORER.VIEW= Ansichten
DATATOOLS.SERVER.UI.EXPLORER.TRIGGER= Auslöser
DATATOOLS.SERVER.UI.EXPLORER.INDEX=Indizes
DATATOOLS.SERVER.UI.EXPLORER.CONSTRAINT=Einschränkungen
DATATOOLS.SERVER.UI.EXPLORER.COLUMN=Spalten
DATATOOLS.SERVER.UI.EXPLORER.PROXY=Proxy
DATATOOLS.SERVER.UI.EXPLORER.DEPENDENCY= Abhängigkeiten
DATATOOLS.SERVER.UI.EXPLORER.EXTERNAL_DEPENDENCY = Externe Abhängigkeit
DATATOOLS.SERVER.UI.EXPLORER.DB2_CLOUDSCAPE = localhost [DB2 Cloudscape]
DATATOOLS.SERVER.UI.EXPLORER.STORED_PROCEDURE=Gespeicherte Prozeduren
DATATOOLS.SERVER.UI.EXPLORER.UDF=Benutzerdefinierte Funktionen
DATATOOLS.SERVER.UI.EXPLORER.CATALOG=Kataloge
DATATOOLS.SERVER.UI.EXPLORER.AUTH_ID = Autorisierungs-IDs
DATATOOLS.SERVER.UI.EXPLORER.USER = Benutzer
DATATOOLS.SERVER.UI.EXPLORER.GROUP = Gruppen
DATATOOLS.SERVER.UI.EXPLORER.ROLE = Rollen

#
## Update Offline Items
#
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE = Offline &speichern
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE = Offline &arbeiten
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE_JOB = Offline speichern
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE_JOB = Offline arbeiten
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.MESSAGE = Offline-Content wurde in Ihrem Workspace nicht gefunden.\nFühren Sie "Offline speichern" aus, wenn Sie verbunden sind.
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.TITLE = Verbindung fehlgeschlagen
#Removed for bug 285485

#
## Bookmark
#
DATATOOLS.SERVER.UI.BOOKMARK.TITLE=Lesezeichen hinzufügen
DATATOOLS.SERVER.UI.BOOKMARK.MESSAGE=Geben Sie den Lesezeichen-Namen ein:


SQL_MODEL_CONTENT_EXTENSION_LABEL=SQL-Modell?– Content








