###############################################################################
# Copyright (c) 2001, 2004, 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
##
###
##  !!! This property file should only contain resources that are "translatable" !!!
###
##

#
## Loading support
#
DATATOOLS.SERVER.UI.EXPLORER.LOADING = Chargement du fournisseur {0}
DATATOOLS.SERVER.UI.EXPLORER.REMOVING_PLACE_HOLDER=Suppression d'une marque de réservation ...
DATATOOLS.SERVER.UI.EXPLORER.DESCRIPTION = Principal

#
## Actions
#
DATATOOLS.SERVER.UI.EXPLORER.CONNECT_SERVER = Ajouter une connexion au serveur
DATATOOLS.SERVER.UI.EXPLORER.DISCONNECT_SERVER = Déconnecter le serveur
DATATOOLS.SERVER.UI.EXPLORER.LAYOUT_OPTIONS = mise en page
DATATOOLS.SERVER.UI.EXPLORER.VIRTUAL_FOLDER = Dossier virtuel
DATATOOLS.SERVER.UI.EXPLORER.HIERARCHICAL = Hiérarchique
DATATOOLS.SERVER.UI.EXPLORER.COLLAPSE_ALL = Tout réduire
DATATOOLS.SERVER.UI.EXPLORER.REFRESH = Actualise&r

#
## Filtering Decoration
#
DATATOOLS.SERVER.UI.EXPLORER.FILTER_DECORATION = [Filtré]
DATATOOLS.SERVER.UI.EXPLORER.FILTER = Filtre
#
## Developer Actions
#
DATATOOLS.SERVER.UI.DEVELOPER.ADD_TABLE = Ajouter une table

#
## Delete Connection Warning
#
DATATOOLS.SERVER.UI.DELETE_CONNECTION_TITLE = Supprimer une connexion
DATATOOLS.SERVER.UI.DELETE_CONNECTION_MANY = Les projets Eclipse suivants : {0} dépendent de cette connexion.\n\nVoulez-vous vraiment supprimer la connexion "{1}" ?
DATATOOLS.SERVER.UI.DELETE_CONNECTION_ONE = Le projet Eclipse suivant : {0} dépend de cette connexion.\n\nVoulez-vous vraiment supprimer la connexion "{1}" ?

#
## Add New Server Dialog
#
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_TITLE = Ajouter une connexion au serveur
DATATOOLS.SERVER.UI.DATABASE_TYPE = Type de base de données :
DATATOOLS.SERVER.UI.DATABASE_VERSION = Version de base de données :
DATATOOLS.SERVER.UI.SELECT_DATABASE = Sélectionner ou entrer un nom de base de données :
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_ENTER_INFO=Entrer les informations de connexion
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_CONNECTING=Connexion au serveur...
DATATOOLS.SERVER.UI.ADD_NEW_SERVER_FAILURE=Echec de la connexion au serveur
DATATOOLS.SERVER.UI.IDENTIFICATION_LABEL = Identification de la connexion au serveur
DATATOOLS.SERVER.UI.PROVIDER_NOT_FOUND = Aucun fournisseur n'a encore été installé
DATATOOLS.SERVER.UI.EXPLORER.NULL_CONNECTION = Connexion non établie
DATATOOLS.SERVER.UI.EXPLORER.CONNECTION_EXCEPTION = Exception de connexion SQL avec {0}
DATATOOLS.SERVER.UI.USER_NAME_LABEL = ID utilisateur :
DATATOOLS.SERVER.UI.PASSWORD_LABEL = Mot de passe :
_UI_DIALOG_CONNECTION_TITLE  = Nouvelle connexion

#
## Error Connection Dialog
#
DATATOOLS.SERVER.UI.CONNECTION.ERROR.TITLE = Exception de connexion invalide
DATATOOLS.SERVER.UI.CONNECTION.ERROR.MESSAGE = Echec de connexion
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.TITLE = Notification d'exception SQL
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.RECONNECT = Reconnecter
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.DISCONNECT = Déconnecter
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.IGNORE = Ignorer
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.MESSAGE = Veuillez effectuer l'une des actions proposées :
DATATOOLS.SERVER.UI.CONNECTION.SQLEXCEPTION.SQLMESSAGE = Une exception SQL a été détectée lors de cette opération.
 
#
## Server Disconnect
#
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_TITLE = Sélection de connexion
DATATOOLS.SERVER.UI.DISCONNECT_SERVER_SELECTION = Sélectionner une connexion :
DATATOOLS.SERVER.UI.DISCONNECT_CONNECTED_SERVERS = Connexions disponibles

#
## Server Explorer Nodes
#
DATATOOLS.SERVER.UI.EXPLORER.KNOWN_SERVERS=Connexions
DATATOOLS.SERVER.UI.EXPLORER.DISC_SERVERS=Pseudos trouvés
DATATOOLS.SERVER.UI.EXPLORER.SCHEMA=Schémas
DATATOOLS.SERVER.UI.EXPLORER.DATABASE=Bases de données
DATATOOLS.SERVER.UI.EXPLORER.TABLE=Tables
DATATOOLS.SERVER.UI.EXPLORER.ROUTINE=Routines
DATATOOLS.SERVER.UI.EXPLORER.SEQUENCE=Séquences
DATATOOLS.SERVER.UI.EXPLORER.UDT=Types définis par l'utilisateur
DATATOOLS.SERVER.UI.EXPLORER.VIEW= Vues
DATATOOLS.SERVER.UI.EXPLORER.TRIGGER= Déclencheurs
DATATOOLS.SERVER.UI.EXPLORER.INDEX=Index
DATATOOLS.SERVER.UI.EXPLORER.CONSTRAINT=Contraintes
DATATOOLS.SERVER.UI.EXPLORER.COLUMN=Colonnes
DATATOOLS.SERVER.UI.EXPLORER.PROXY=Proxy
DATATOOLS.SERVER.UI.EXPLORER.DEPENDENCY= Dépendances
DATATOOLS.SERVER.UI.EXPLORER.EXTERNAL_DEPENDENCY = Dépendance externe
DATATOOLS.SERVER.UI.EXPLORER.DB2_CLOUDSCAPE = localhost [DB2 Cloudscape]
DATATOOLS.SERVER.UI.EXPLORER.STORED_PROCEDURE=Procédures stockées
DATATOOLS.SERVER.UI.EXPLORER.UDF=Fonctions définies par l'utilisateur
DATATOOLS.SERVER.UI.EXPLORER.CATALOG=Catalogues
DATATOOLS.SERVER.UI.EXPLORER.AUTH_ID = ID d'autorisation
DATATOOLS.SERVER.UI.EXPLORER.USER = Utilisateurs
DATATOOLS.SERVER.UI.EXPLORER.GROUP = Groupes
DATATOOLS.SERVER.UI.EXPLORER.ROLE = Rôles

#
## Update Offline Items
#
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE = Enregi&strer hors ligne
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE = &Travailler hors ligne
DATATOOLS.SERVER.UI.EXPLORER.UPDATE_OFFLINE_JOB = Enregistrer hors ligne
DATATOOLS.SERVER.UI.EXPLORER.WORKOFFLINE_JOB = Travailler hors ligne
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.MESSAGE = Le contenu hors ligne n'a pas été trouvé dans votre espace de travail.\nExécuter "Save Offline" une fois que vous êtes connecté.
DATATOOLS.SERVER.UI.CONNECTION.OFFLINE.TITLE = Echec de connexion
DATATOOLS.SERVER.UI.CONNECTION.ERROR.MESSAGE = Echec de connexion

#
## Bookmark
#
DATATOOLS.SERVER.UI.BOOKMARK.TITLE=Ajouter un signet
DATATOOLS.SERVER.UI.BOOKMARK.MESSAGE=Entrer un nom de signet :


SQL_MODEL_CONTENT_EXTENSION_LABEL=Contenu de modèle SQL








