################################################################################
## Copyright (c) 2006-2007 Ingres Corporation and others.
## All rights reserved.   This program and the accompanying materials
## are made available under the terms of the Eclipse Public License 2.0
## which accompanies this distribution, and is available at
## https://www.eclipse.org/legal/epl-2.0/
##
## Contributors: 
##  Ingres - Implementation
################################################################################

PLUGIN_NAME = Plug-in DTP Ingres
PROVIDER_NAME = Plate-forme d'outils de données Eclipse

# Parent category for Ingres in the driver definition
CATEGORY_PRODUCT_FAMILY_NAME        = Ingres
CATEGORY_PRODUCT_FAMILY_DESCRIPTION =

# Category for Ingres 2006 in the driver definition
CATEGORY_PRODUCT_NAME        = 2006
CATEGORY_PRODUCT_DESCRIPTION =

# Ingres 2006 Driver Template
DRIVER_NAME = Pilote JDBC Ingres
DRIVER_DESCRIPTION =

# Various properties for the driver template

DRIVER_DRIVER_CLASS_NAME = Classe de pilote
DRIVER_DRIVER_CLASS_DESCRIPTION =

DRIVER_DB_VENDOR_NAME = Vendeur
DRIVER_DB_VENDOR_DESCRIPTION =

DRIVER_DB_VERSION_NAME = 2006
DRIVER_DB_VERSION_DESCRIPTION =

DRIVER_DATABASE_NAME_NAME = Nom de la base de données
DRIVER_DATABASE_NAME_DESCRIPTION =

DRIVER_DB_URL_NAME = URL de connexion
DRIVER_DB_URL_DESCRIPTION =

DRIVER_DB_USERNAME_NAME = Nom d'utilisateur
DRIVER_DB_USERNAME_DESCRIPTION =

DRIVER_DB_PASSWORD_NAME = Mot de passe
DRIVER_DB_PASSWORD_DESCRIPTION =

# Connection Profile
CONNECTION_PROFILE_NAME = Base de données Ingres

# Connection factory
CONNECTION_FACTORY_NAME = Génération de connexion JDBC Ingres
# ====================================================================

