################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Data Tools Platform 연결 JDT 확장 플러그인
Plugin.ProviderName = Eclipse Data Tools Platform

driver.classpath.container.name = 연결 드라이버 정의
