################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Data Tools Platform Connectivity JDT Extension Plug-in
Plugin.ProviderName = Eclipse Data Tools Platform

driver.classpath.container.name = 接続ドライバの定義
