################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = 数据工具平台连接 JDT 扩展插件
Plugin.ProviderName = Eclipse 数据工具平台

driver.classpath.container.name = 连接驱动程序定义
