################################################################################
## Copyright (c) 2006 Sybase, Inc.
## All rights reserved. This program and the accompanying materials
## are made available under the terms of the Eclipse Public License v1.0
## which accompanies this distribution, and is available at
## http://www.eclipse.org/legal/epl-v10.html
##
## Contributors:
##    Sybase, Inc. - initial API and implementation
################################################################################ 
Plugin.Name = Plug-in d'extension JDT de connectivité pour la plate-forme d'outils de données
Plugin.ProviderName = Plate-forme d'outils de données Eclipse

driver.classpath.container.name = Définition de pilote de connectivité
