###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
#
oda.xml.datasource=DTP XMLデータソース
oda.xml.dataset=DTP XML データセット
oda.xml.tablemapping=テーブルのマッピング
oda.xml.columnmapping=列のマッピング
#
plugin.name=DTP XML File Designer
newwizard.name=DTP XML ファイルデータソース
newwizard.description=DTP XML ファイルの接続プロファイルを作成します。
wizard.window.title=DTP XML ファイルデータソースのプロファイル
wizard.data.source.page.title=XMLデータソースの定義
wizard.data.set.window.title=新規 XML データセット
profile.propertypage.name=DTP XML ファイルデータソースの接続プロパティ
preference.datasetpreview=XML データセット
providerName=Eclipse Data Tools Platform
