###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=Source de données XML DTP
oda.xml.dataset=Jeu de données XML DTP
oda.xml.tablemapping=Mise en correspondance de table
oda.xml.columnmapping=Mise en correspondance de colonne
#
###############################################################################
# NLS messages
#
plugin.name=DTP XML File Designer
newwizard.name=Source de données sous forme de fichier XML DTP
newwizard.description=Créer un profil de connexion de fichier XML DTP
wizard.window.title=Nouveau profil de source de données sous forme de fichier XML
wizard.data.source.page.title=Définir les URL du fichier XML et les informations du schéma
profile.propertypage.name=Propriétés de connexion de source de données sous forme de fichier XML DTP
preference.datasetpreview=Jeu de données XML
