###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=DTP XML 数据源
oda.xml.dataset=DTP XML 数据集
oda.xml.tablemapping=表映射
oda.xml.columnmapping=列映射

oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=DTP XML File Designer
oda.data.source.name=DTP XML 文件
connection.profile.name=DTP XML 文件数据源连接配置文件
newwizard.name=DTP XML 文件数据源
newwizard.description=创建 DTP XML 文件连接配置文件
wizard.window.title=新建 XML 文件数据源配置文件
wizard.data.source.page.title=定义 XML 文件和架构信息的 URL
profile.propertypage.name=DTP XML 文件数据源连接属性
preference.datasetpreview=XML 数据集
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
