###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
#
oda.xml.datasource=Fuente de datos XML DTP
oda.xml.dataset=Conjunto de datos XML DTP
oda.xml.tablemapping=Asignación de tablas
oda.xml.columnmapping=Asignación de columnas
#
plugin.name=DTP XML File Designernewwizard.name=Fuente de datos de archivo XML DTP
newwizard.description=Crear un perfil de conexión del archivo XML DTP
wizard.window.title=Nuevo perfil de fuente de datos del archivo XML
wizard.data.source.page.title=Definir fuente de datos XML
wizard.data.set.window.title=Nuevo conjunto de datos XML
profile.propertypage.name=Propiedades de conexión de fuente de datos de archivo XML DTP
preference.datasetpreview=Conjunto de datos XML
providerName=Eclipse Data Tools Platform
