###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
#
oda.xml.datasource=DTP XML 데이터 원본
oda.xml.dataset=DTP XML 데이터 집합
oda.xml.tablemapping=테이블 매핑
oda.xml.columnmapping=열 매핑
#
plugin.name=DTP XML File Designer
newwizard.name=DTP XML 파일 데이터 원본
newwizard.description=DTP XML 파일 연결 프로필 생성
wizard.window.title=새 XML 파일 데이터 원본 프로필
wizard.data.source.page.title=XML 데이터 원본 정의
wizard.data.set.window.title=새 XML 데이터 집합
profile.propertypage.name=DTP XML 파일 데이터 원본 연결 속성
preference.datasetpreview=XML 데이터 집합
providerName=Eclipse Data Tools Platform
