###############################################################################
# Copyright (c) 2004 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=DTP XML データソース
oda.xml.dataset=DTP XML データセット
oda.xml.tablemapping=テーブルのマッピング
oda.xml.columnmapping=列のマッピング

oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=DTP XML File Designer
oda.data.source.name=DTP XML ファイル
connection.profile.name=DTP XML ファイルのデータソースの接続プロファイル
newwizard.name=DTP XML ファイルのデータソース
newwizard.description=DTP XML ファイルの接続プロファイルを作成します。
wizard.window.title=DTP XML ファイルのデータソースのプロファイル
wizard.data.source.page.title=XML ファイルとスキーマ情報への ULR を定義してください。
profile.propertypage.name=DTP XML ファイルのデータソースの接続プロパティ
preference.datasetpreview=XML データセット
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリ
