###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
###############################################################################

###############################################################################
# NLS String
###############################################################################
oda.xml.datasource=DTP-XML-Datenquelle
oda.xml.dataset=DTP-XML-Datensatz
oda.xml.tablemapping=Tabellenzuordnung
oda.xml.columnmapping=Spaltenzuordnung

oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS messages
#
plugin.name=DTP XML File Designer
oda.data.source.name=DTP-XML-Dateien
connection.profile.name=Verbindungsprofil für Datenquelle der DTP-XML-Datei
newwizard.name=Datenquelle der DTP-XML-Datei
newwizard.description=Verbindungsprofil für DTP-XML-Datei erstellen
wizard.window.title=Profil für Datenquelle der neuen XML-Datei
wizard.data.source.page.title=Geben Sie die URLs und die Schemainformation für die XML-Datei an.
profile.propertypage.name=Verbindungseigenschaften für Datenquelle der DTP-XML-Datei
preference.datasetpreview=XML-Datensatz
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
