###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
#
oda.xml.datasource=DTP XML 数据源
oda.xml.dataset=DTP XML 数据集
oda.xml.tablemapping=表映射
oda.xml.columnmapping=列映射
#
plugin.name=DTP XML File Designer
newwizard.name=DTP XML 文件数据源
newwizard.description=创建 DTP XML 文件连接配置文件
wizard.window.title=新建 XML 文件数据源配置文件
wizard.data.source.page.title=定义 XML 数据源
wizard.data.set.window.title=New XML Data Set
profile.propertypage.name=DTP XML 文件数据源连接属性
preference.datasetpreview=XML 数据集
providerName=Eclipse Data Tools Platform
