###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation  - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
#
###############################################################################
#
oda.xml.datasource=DTP-XML-Datenquelle
oda.xml.dataset=DTP-XML-Datensatz
oda.xml.tablemapping=Tabellenzuordnung
oda.xml.columnmapping=Spaltenzuordnung
#
plugin.name=DTP XML File Designer
newwizard.name=Datenquelle der DTP-XML-Datei
newwizard.description=Verbindungsprofil für DTP-XML-Datei erstellen
wizard.window.title=Profil für Datenquelle der neuen XML-Datei
wizard.data.source.page.title=XML-Datenquelle definieren
wizard.data.set.window.title=Neuer XML-Datensatz
profile.propertypage.name=Verbindungseigenschaften für Datenquelle der DTP-XML-Datei
preference.datasetpreview=XML-Datensatz
providerName=Eclipse-Datentools-Plattform
