GENERATE_FULL_SYNTAX = &Vollständige Syntax 
GENERATE_FULL_SYNTAX_DES = Erstellen Sie eine vollständige Syntax
GENERATE_SETUSER= Set user 
GENERATE_SETUSER_DES = Generate setuser statement to impersonate another user
GENERATE_USEDATABASE= Use Database 
GENERATE_USEDATABASE_DES = Generate use database statement to switch to another database

GENERATE_EXTRA_CODE	=	E&xtra Code
GENERATE_EXTRA_CODE_DES	=	Erstellen Sie Extra?Code
GENERATE_PRIVILEGE	=	&Privileg
GENERATE_PRIVILEGE_DES	=	Erstellen Sie Privilegien
GENERATE_COMMENTS = Kommentare
GENERATE_COMMENTS_DES = Erstellen Sie &Kommentare

GENERATE_ROUTINE=Stored &Procedures and User Defined Functions
GENERATE_ROUTINE_DES=Generate stored procedures and user defined functions

GENERATE_FUNCTION=User Defined &Functions
GENERATE_FUNCTION_DES=Generate user defined functions
GENERATE_USER_DEFINED_TYPES 	= Benutzerdefinierte &Typen
GENERATE_USER_DEFINED_TYPES_DES 	= Erstellen Sie benutzerdefinierte Typen
GENERATE_DEFAULTS_DES 	= Erstellen Sie Standardwerte
GENERATE_DEFAULTS 		= &Standardwerte
GENERATE_DEFAULTS_DES 	= Erstellen Sie Standardwerte
GENERATE_RULES 		= &Regeln
GENERATE_RULES_DES 	= Erstellen Sie Regeln
GENERATE_USERS_GROUPS = &Benutzer & Gruppen
GENERATE_USERS_GROUPS_DES = Erstellen Sie Benutzer und Gruppen
GENERATE_PROXY_TABLES = &Proxy-Tabellen
GENERATE_PROXY_TABLES_DES = Erstellen Sie Proxy-Tabellen
GENERATE_SEGMENTS = Se&gmente
GENERATE_SEGMENTS_DES = Erstellen Sie Segmente
GENERATE_DBSPACES = Dbs&pace
GENERATE_DBSPACES_DES = Erstellen Sie Dbspaces
GENERATE_EVENTS = E&reignisse
GENERATE_EVENTS_DES = Erstellen Sie Ereignisse

GENERATE_CHECK_CONSTRAINTS = &Prüf-Einschränkung
GENERATE_CHECK_CONSTRAINTS_DES = Erstellen Sie Prüf-Einschränkungen
GENERATE_UNIQUE_CONSTRAINTS = &Eindeutige Einschränkungen
GENERATE_UNIQUE_CONSTRAINTS_DES = Erstellen Sie eindeutige Einschränkungen
GENERATE_PRIMARY_KEYS = &Primärschlüssel
GENERATE_PRIMARY_KEYS_DES = Erstellen Sie Primärschlüssel
GENERATE_FOREIGN_KEYS = &Fremdschlüssel
GENERATE_FOREIGN_KEYS_DES = Erstellen Sie Fremdschlüssel

GENERATE_CATALOGS = Katalo&g
GENERATE_CATALOGS_DES = Erstellen Sie Kataloge
GENERATE_DATABASE = &Datenbanken
GENERATE_DATABASE_DES = Erstellen Sie Datenbanken

GENERATE_JOIN_INDICES=&Join Index
GENERATE_JOIN_INDICES_DES=Generate Join Index

#GENERATE_DOMAINS = Do&mänen
#GENERATE_DOMAINS_DES = Erstellen Sie Domänen

DATABASE_LABEL = Datenbank
TABLE_LABEL = Tabelle
PROCEDURE_LABEL = Prozedur
USER_DEFINED_FUNCTION_LABEL = Benutzerdefinierte Funktion
VIEW_LABEL = Ansicht
USER_DEFINED_DATATYPE_LABEL = Benutzerdefinierter Datentyp
EVENT_LABEL = Ereignis
CHECK_CONSTRAINT_LABEL = Prüf-Einschränkung
UNIQUE_CONSTRAINT_LABEL = Eindeutige Einschränkung
PRIMARY_KEY_LABEL = Primärschlüssel
FOREIGN_KEY_LABEL = Fremdschlüssel
INDEX_LABEL = Index
TRIGGER_LABEL = Auslösen
DEFAULT_LABEL = Standard
RULE_LABEL = Regel
