GENERATE_FULL_SYNTAX = Sintaxis comp&leta 
GENERATE_FULL_SYNTAX_DES = Generar sintaxis completa
GENERATE_SETUSER= Set user 
GENERATE_SETUSER_DES = Generar sentencia setuser para hacerse pasar por otro usuario
GENERATE_USEDATABASE= Use Database 
GENERATE_USEDATABASE_DES = Generar sentencia use database para cambiar a otra base de datos

GENERATE_EXTRA_CODE	=	Código e&xtra
GENERATE_EXTRA_CODE_DES	=	Generar código extra
GENERATE_PRIVILEGE	=	Conceder sentencias de &privilegios
GENERATE_PRIVILEGE_DES	=	Generar concesión de privilegios
GENERATE_COMMENTS = Co&mentarios
GENERATE_COMMENTS_DES = Generar comen&tarios

GENERATE_ROUTINE=Stored &Procedures y funciones definidas por el usuario
GENERATE_ROUTINE_DES=Generar stored procedures y funciones definidas por el usuario

GENERATE_FUNCTION=&Funciones definidas por el usuario
GENERATE_FUNCTION_DES=Generar funciones definidas por el usuario
GENERATE_USER_DEFINED_TYPES 	= &Tipos definidos por el usuario
GENERATE_USER_DEFINED_TYPES_DES 	= Generar tipos definidos por el usuario
GENERATE_DEFAULTS_DES 	= Generar predeterminados
GENERATE_DEFAULTS 		= &Predeterminados
GENERATE_DEFAULTS_DES 	= Generar predeterminados
GENERATE_RULES 		= &Reglas
GENERATE_RULES_DES 	= Generar reglas
GENERATE_USERS_GROUPS = &Usuarios y grupos
GENERATE_USERS_GROUPS_DES = Generar usuarios y grupos
GENERATE_PROXY_TABLES = Tablas de &proxy
GENERATE_PROXY_TABLES_DES = Generar tablas de proxy
GENERATE_SEGMENTS = Se&gmentos
GENERATE_SEGMENTS_DES = Generar segmentos
GENERATE_DBSPACES = Es&pacio DB
GENERATE_DBSPACES_DES = Generar espacios de base de datos
GENERATE_EVENTS = E&ventos
GENERATE_EVENTS_DES = Generar eventos

GENERATE_CHECK_CONSTRAINTS = &Comprobar restricciones
GENERATE_CHECK_CONSTRAINTS_DES = Generar comprobación de restricciones
GENERATE_UNIQUE_CONSTRAINTS = Restricciones excl&usivas
GENERATE_UNIQUE_CONSTRAINTS_DES = Generar restricciones exclusivas
GENERATE_PRIMARY_KEYS = Claves &primarias
GENERATE_PRIMARY_KEYS_DES = Generar claves primarias
GENERATE_FOREIGN_KEYS = Claves e&xternas
GENERATE_FOREIGN_KEYS_DES = Generar claves externas

GENERATE_CATALOGS = Catálo&go
GENERATE_CATALOGS_DES = Generar catálogo
GENERATE_DATABASE = &Base de datos
GENERATE_DATABASE_DES = Generar base de datos

GENERATE_JOIN_INDICES=Índice co&mbinado
GENERATE_JOIN_INDICES_DES=Generar índice combinado

#GENERATE_DOMAINS = Do&minios
#GENERATE_DOMAINS_DES = Generar dominios

DATABASE_LABEL = Base de datos
TABLE_LABEL = Tabla
PROCEDURE_LABEL = Procedimiento
USER_DEFINED_FUNCTION_LABEL = Función definida por el usuario
VIEW_LABEL = Ver
USER_DEFINED_DATATYPE_LABEL = Tipo de datos definido por el usuario
EVENT_LABEL = Evento
CHECK_CONSTRAINT_LABEL = Comprobar restricción
UNIQUE_CONSTRAINT_LABEL = Restricción exclusiva
PRIMARY_KEY_LABEL = Clave primaria
FOREIGN_KEY_LABEL = Clave externa
INDEX_LABEL = Índice
TRIGGER_LABEL = Activador
DEFAULT_LABEL = Predeterminado
RULE_LABEL = Regla
