GENERATE_FULL_SYNTAX = Syntaxe comp&lète 
GENERATE_FULL_SYNTAX_DES = Générer syntaxe complète
GENERATE_SETUSER= Set user 
GENERATE_SETUSER_DES = Générer une instruction setuser pour emprunter l'identité d'un autre utilisateur
GENERATE_USEDATABASE= Use Database 
GENERATE_USEDATABASE_DES = Générer une instruction use database pour utiliser une autre base de données

GENERATE_EXTRA_CODE	=	&Code supplémentaire
GENERATE_EXTRA_CODE_DES	=	Générer un code supplémentaire
GENERATE_PRIVILEGE	=	Instructions des droits et &privilèges
GENERATE_PRIVILEGE_DES	=	Générer une attribution de privilège
GENERATE_COMMENTS = Co&mmentaires
GENERATE_COMMENTS_DES = Générer des commen&taires

GENERATE_ROUTINE=&Procédures stockées et fonctions définies par l'utilisateur
GENERATE_ROUTINE_DES=Générer des procédures stockées et des fonctions définies par l'utilisateur

GENERATE_FUNCTION=&Fonctions définies par l'utilisateur
GENERATE_FUNCTION_DES=Générer des fonctions définies par l'utilisateur
GENERATE_USER_DEFINED_TYPES 	= &Types définis par l'utilisateur
GENERATE_USER_DEFINED_TYPES_DES 	= Générer des types définis par l'utilisateur
GENERATE_DEFAULTS_DES 	= Générer des valeurs par défaut
GENERATE_DEFAULTS 		= Valeurs par &défaut
GENERATE_DEFAULTS_DES 	= Générer des valeurs par défaut
GENERATE_RULES 		= &Règles
GENERATE_RULES_DES 	= Générer des règles
GENERATE_USERS_GROUPS = &Utilisateurs et groupes
GENERATE_USERS_GROUPS_DES = Générer des utilisateurs et des groupes
GENERATE_PROXY_TABLES = Tables &Proxy
GENERATE_PROXY_TABLES_DES = Générer des tables proxy
GENERATE_SEGMENTS = Se&gments
GENERATE_SEGMENTS_DES = Générer des segments
GENERATE_DBSPACES = Dbs&pace
GENERATE_DBSPACES_DES = Générer des dbspaces
GENERATE_EVENTS = E&vénements
GENERATE_EVENTS_DES = Générer des événements

GENERATE_CHECK_CONSTRAINTS = &Contraintes de vérification
GENERATE_CHECK_CONSTRAINTS_DES = Générer des contraintes de vérification
GENERATE_UNIQUE_CONSTRAINTS = Contraintes &uniques
GENERATE_UNIQUE_CONSTRAINTS_DES = Générer des contraintes uniques
GENERATE_PRIMARY_KEYS = Clés &principales
GENERATE_PRIMARY_KEYS_DES = Générer des clés principales
GENERATE_FOREIGN_KEYS = Clés é&trangères
GENERATE_FOREIGN_KEYS_DES = Générer des clés étrangères

GENERATE_CATALOGS = Catalo&gue
GENERATE_CATALOGS_DES = Générer un catalogue
GENERATE_DATABASE = Base de &données
GENERATE_DATABASE_DES = Générer une base de données

GENERATE_JOIN_INDICES=Index de &jointure
GENERATE_JOIN_INDICES_DES=Générer Index de jointure

#GENERATE_DOMAINS = Do&maines
#GENERATE_DOMAINS_DES = Générer des domaines

DATABASE_LABEL = Base de données
TABLE_LABEL = Table
PROCEDURE_LABEL = Procédure
USER_DEFINED_FUNCTION_LABEL = Fonction définie par l'utilisateur
VIEW_LABEL = Vue
USER_DEFINED_DATATYPE_LABEL = Type de données défini par l'utilisateur
EVENT_LABEL = Evénement
CHECK_CONSTRAINT_LABEL = Contrainte de vérification
UNIQUE_CONSTRAINT_LABEL = Contrainte unique
PRIMARY_KEY_LABEL = Clé principale
FOREIGN_KEY_LABEL = Clé étrangère
INDEX_LABEL = Index
TRIGGER_LABEL = Déclencheur
DEFAULT_LABEL = Par défaut
RULE_LABEL = Règle


