# ====================================================================
# * Copyright (c) 2005, 2006 Actuate Corporation.
# * All rights reserved. This program and the accompanying materials
# * are made available under the terms of the Eclipse Public License v1.0
# * which accompanies this distribution, and is available at
# * http://www.eclipse.org/legal/epl-v10.html
# *
# * Contributors:
# *  Actuate Corporation - initial API and implementation
# *  
# *************************************************************************
# *
# * $Id: plugin.properties,v 1.3 2006/03/07 02:00:04 lchan Exp $
# ====================================================================
#
# ====================================================================
# To code developer:
#   Do NOT change the properties between this line and the
#   "%%% END OF TRANSLATED PROPERTIES %%%" line.
#   Make a new property name, append to the end of the file and change
#   the code to use the new property.
# ====================================================================
#
# ====================================================================
# %%% END OF TRANSLATED PROPERTIES %%%
# ====================================================================
#
pluginName=DTP ODA Design Session Model
