/* Generated By:JJTree: Do not edit this line. ..\src\org\eclipse\datatools\enablement\ingres\internal\parser\IngresSQLParserVisitor.java */

package org.eclipse.datatools.enablement.ingres.internal.ui.parser;

public interface IngresSQLParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTStart node, Object data);
  public Object visit(ASTSQLDelimiter node, Object data);
  public Object visit(ASTSQLStatement node, Object data);
  public Object visit(ASTSQLDataType node, Object data);
  public Object visit(ASTDeclareKeyword node, Object data);
  public Object visit(ASTDeclareComma node, Object data);
  public Object visit(ASTSQLParam node, Object data);
  public Object visit(ASTExpression node, Object data);
}
