###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB zSeries Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Treiberklasse
driverVendor = Anbieter
driverVersion = Version
driverDBName = Datenbankname
driverConnectionURL = Verbindungs-URL
filterOnTBCreator = Aufrufen von Objekten, die ausschließlich von diesem Nutzer erstellt wurden
driverUID = Benutzer-ID
driverPWD = Kennwort

DB2_UDB_ZSERIES_CATEGORY_NAME = DB2 für z/OS

org.eclipse.datatools.enablement.ibm.db2.zseries.driverTemplate = IBM Data Server Treiber für JDBC und SQLJ
org.eclipse.datatools.enablement.ibm.db2.zseries.other.driverTemplate = Anderer Treiber

jdbc.connection.name = JDBC-Verbindung
profile.db2.zseries.title = DB2 für z/OS
