###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB zSeries Plug-in
providerName=Eclipse Data Tools Platform

driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
filterOnTBCreator = このユーザが作成したオブジェクトだけを取得する
driverUID = ユーザ ID
driverPWD = パスワード

DB2_UDB_ZSERIES_CATEGORY_NAME = DB2 for z/OS

org.eclipse.datatools.enablement.ibm.db2.zseries.driverTemplate = IBM Data Server Driver for JDBC and SQLJ
org.eclipse.datatools.enablement.ibm.db2.zseries.other.driverTemplate = その他のドライバ

jdbc.connection.name = JDBC 接続
profile.db2.zseries.title = DB2 for z/OS
