###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB zSeries Plug-in
providerName=Eclipse Data Tools Platform

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
filterOnTBCreator = 이 사용자가 생성한 개체만 검색
driverUID = 사용자 ID
driverPWD = 암호

DB2_UDB_ZSERIES_CATEGORY_NAME = z/OS용 DB2

org.eclipse.datatools.enablement.ibm.db2.zseries.driverTemplate = JDBC 및 SQLJ용 IBM 데이터 서버 드라이버
org.eclipse.datatools.enablement.ibm.db2.zseries.other.driverTemplate = 기타 드라이버

jdbc.connection.name = JDBC 연결
profile.db2.zseries.title = z/OS용 DB2
