###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Classe de pilote
driverVendor = Vendeur
driverVersion = Version
driverDBName = Nom de la base de données
driverConnectionURL = URL de connexion
driverUID = ID utilisateur
driverPWD = Mot de passe

SQLSERVER_CATEGORY_NAME = Serveur SQL
2008_VERSION_CATEGORY_NAME = 2008
2005_VERSION_CATEGORY_NAME = 2005
2000_VERSION_CATEGORY_NAME = 2000

org.eclipse.datatools.enablement.msft.sqlserver.2008.driverTemplate = Microsoft SQL Server 2008 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2005.driverTemplate = Pilote JDBC du serveur SQL Microsoft 2005
org.eclipse.datatools.enablement.msft.sqlserver.2000.driverTemplate = Pilote du serveur SQL Microsoft 2000 pour JDBC
org.eclipse.datatools.enablement.msft.sqlserver.2008.other.driverTemplate = Autre pilote
org.eclipse.datatools.enablement.msft.sqlserver.2005.other.driverTemplate = Autre pilote
org.eclipse.datatools.enablement.msft.sqlserver.2000.other.driverTemplate = Autre pilote

jdbc.connection.name = Connexion JDBC
profile.sqlserver.title = Serveur SQL
