###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server Plug-in
providerName=Eclipse.org

driverClass = Driver Class
driverVendor = Vendor
driverVersion = Version
driverDBName = Database Name
driverConnectionURL = Connection URL
driverUID = User ID
driverPWD = Password

SQLSERVER_CATEGORY_NAME = SQL Server
2005_VERSION_CATEGORY_NAME = 2005
2000_VERSION_CATEGORY_NAME = 2000

org.eclipse.datatools.enablement.msft.sqlserver.2005.driverTemplate = Microsoft SQL Server 2005 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2000.driverTemplate = Microsoft SQL Server 2000 Driver for JDBC
org.eclipse.datatools.enablement.msft.sqlserver.2005.other.driverTemplate = Other Driver
org.eclipse.datatools.enablement.msft.sqlserver.2000.other.driverTemplate = Other Driver

jdbc.connection.name = JDBC Connection
profile.sqlserver.title = SQL Server
