###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server Plug-in
providerName=Eclipse Data Tools Platform

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호

SQLSERVER_CATEGORY_NAME = SQL 서버
2008_VERSION_CATEGORY_NAME = 2008
2005_VERSION_CATEGORY_NAME = 2005
2000_VERSION_CATEGORY_NAME = 2000

org.eclipse.datatools.enablement.msft.sqlserver.2008.driverTemplate = Microsoft SQL Server 2008 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2005.driverTemplate = Microsoft SQL 서버 2005 JDBC 드라이버
org.eclipse.datatools.enablement.msft.sqlserver.2000.driverTemplate = JDBC용 Microsoft SQL 서버 2000 드라이버
org.eclipse.datatools.enablement.msft.sqlserver.2008.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.msft.sqlserver.2005.other.driverTemplate = 기타 드라이버
org.eclipse.datatools.enablement.msft.sqlserver.2000.other.driverTemplate = 기타 드라이버

jdbc.connection.name = JDBC 연결
profile.sqlserver.title = SQL 서버
