###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
driverUID = Identificador de usuario
driverPWD = Contraseña

SQLSERVER_CATEGORY_NAME = SQL Server
2008_VERSION_CATEGORY_NAME = 2008
2005_VERSION_CATEGORY_NAME = 2005
2000_VERSION_CATEGORY_NAME = 2000

org.eclipse.datatools.enablement.msft.sqlserver.2008.driverTemplate = Microsoft SQL Server 2008 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2005.driverTemplate = Controlador JDBC de Microsoft SQL Server 2005
org.eclipse.datatools.enablement.msft.sqlserver.2000.driverTemplate = Controlador de Microsoft SQL Server 2000 para JDBC
org.eclipse.datatools.enablement.msft.sqlserver.2008.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.msft.sqlserver.2005.other.driverTemplate = Otro controlador
org.eclipse.datatools.enablement.msft.sqlserver.2000.other.driverTemplate = Otro controlador

jdbc.connection.name = Conexión JDBC
profile.sqlserver.title = SQL Server
