###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Microsoft SQL Server Plug-in
providerName=Eclipse Data Tools Platform

driverClass = ドライバクラス
driverVendor = ベンダ
driverVersion = バージョン
driverDBName = データベース名
driverConnectionURL = 接続 URL
driverUID = ユーザ ID
driverPWD = パスワード

SQLSERVER_CATEGORY_NAME = SQL サーバ
2008_VERSION_CATEGORY_NAME = 2008
2005_VERSION_CATEGORY_NAME = 2005
2000_VERSION_CATEGORY_NAME = 2000

org.eclipse.datatools.enablement.msft.sqlserver.2008.driverTemplate = Microsoft SQL Server 2008 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2005.driverTemplate = Microsoft SQL Server 2005 JDBC Driver
org.eclipse.datatools.enablement.msft.sqlserver.2000.driverTemplate = Microsoft SQL Server 2000 Driver for JDBC
org.eclipse.datatools.enablement.msft.sqlserver.2008.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.msft.sqlserver.2005.other.driverTemplate = その他のドライバ
org.eclipse.datatools.enablement.msft.sqlserver.2000.other.driverTemplate = その他のドライバ

jdbc.connection.name = JDBC 接続
profile.sqlserver.title = SQL サーバ
