Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform SQLite Enablement Plug-in

driver.category.name = SQLite
driver.category.description = SQLite JDBC ドライバ
driver.version.category.name = 3.5.9
driver.version.category.description = SQLite JDBC Drivers for Version 3.5.9
driver.name = SQLite JDBC ドライバ
driver.description = SQLite 用の JDBC ドライバ

DRIVER_CLASS_PROPERTY_NAME=ドライバクラス
VENDOR_PROPERTY_NAME=ベンダ
VERSION_PROPERTY_NAME=バージョン
DATABASE_NAME_PROPERTY_NAME=データベース名
CONNECTION_URL_PROPERTY_NAME=接続 URL
USER_ID_PROPERTY_NAME=ユーザ ID

connection.factory = SQLite 接続ファクトリ
connection.profile = SQLite 接続プロファイル
