Bundle-Vendor = Plate-forme d'outils de données Eclipse
Bundle-Name = Plug-in d'activation SQLite pour la plate-forme d'outils de données Eclipse

driver.category.name = SQLite
driver.category.description = Pilotes JDBC SQLite
driver.version.category.name = 3.5.9
driver.version.category.description = Pilotes JDBC SQLite pour la version 3.5.9
driver.name = Pilote JDBC SQLite
driver.description = Pilote JDBC pour SQLite

DRIVER_CLASS_PROPERTY_NAME=Classe de pilote
VENDOR_PROPERTY_NAME=Vendeur
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Nom de la base de données
CONNECTION_URL_PROPERTY_NAME=URL de connexion
USER_ID_PROPERTY_NAME=ID utilisateur

connection.factory = Génération de connexion SQLite
connection.profile = Profil de connexion SQLite
