Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform SQLite 사용 플러그인

driver.category.name = SQLite
driver.category.description = SQLite JDBC 드라이버
driver.version.category.name = 3.5.9
driver.version.category.description = 버전 3.5.9용 SQLite JDBC 드라이버
driver.name = SQLite JDBC 드라이버
driver.description = SQLite용 JDBC 드라이버

DRIVER_CLASS_PROPERTY_NAME=드라이버 클래스
VENDOR_PROPERTY_NAME=공급업체
VERSION_PROPERTY_NAME=버전
DATABASE_NAME_PROPERTY_NAME=데이터베이스 이름
CONNECTION_URL_PROPERTY_NAME=연결 URL
USER_ID_PROPERTY_NAME=사용자 ID

connection.factory = SQLite 연결 팩토리
connection.profile = SQLite 연결 프로필
