Bundle-Vendor = Eclipse-Datentools-Plattform
Bundle-Name = Eclipse-Datentools-Plattform SQLite Enablement Plug-In

driver.category.name = SQLite
driver.category.description = SQLite JDBC-Treiber
driver.version.category.name = 3.5.9
driver.version.category.description = SQLite JDBC-Treiber für Version 3.5.9
driver.name = SQLite JDBC-Treiber
driver.description = JDBC-Treiber für SQLite

DRIVER_CLASS_PROPERTY_NAME=Treiberklasse
VENDOR_PROPERTY_NAME=Anbieter
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Datenbankname
CONNECTION_URL_PROPERTY_NAME=Verbindungs-URL
USER_ID_PROPERTY_NAME=Benutzer-ID

connection.factory = SQLite-Verbindungs-Factory
connection.profile = SQLite-Verbindungsprofil
