Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Complemento de activación de SQLite para Eclipse Data Tools Platform

driver.category.name = SQLite
driver.category.description = Controladores JDBC de SQLite
driver.version.category.name = 3.5.9
driver.version.category.description = Controladores JDBC de SQLite para versión 3.5.9
driver.name = Controlador JDBC de SQLite
driver.description = Controlador JDBC para SQLite

DRIVER_CLASS_PROPERTY_NAME=Clase de controlador
VENDOR_PROPERTY_NAME=Proveedor
VERSION_PROPERTY_NAME=Versión
DATABASE_NAME_PROPERTY_NAME=Nombre de base de datos
CONNECTION_URL_PROPERTY_NAME=URL de conexión
USER_ID_PROPERTY_NAME=Identificador de usuario

connection.factory = Fábrica de conexión SQLite
connection.profile = Perfil de conexión SQLite
