Bundle-Vendor = Eclipse 数据工具平台
Bundle-Name = Eclipse 数据工具平台 SQLite 启用插件

driver.category.name = SQLite
driver.category.description = SQLite JDBC 驱动程序
driver.version.category.name = 3.5.9
driver.version.category.description = 针对版本 3.5.9 的 SQLite JDBC 驱动程序
driver.name = SQLite JDBC 驱动程序
driver.description = SQLite 的 JDBC 驱动程序

DRIVER_CLASS_PROPERTY_NAME=驱动程序类
VENDOR_PROPERTY_NAME=供应商
VERSION_PROPERTY_NAME=版本
DATABASE_NAME_PROPERTY_NAME=数据库名称
CONNECTION_URL_PROPERTY_NAME=连接 URL
USER_ID_PROPERTY_NAME=用户 ID

connection.factory = SQLite 连接工厂
connection.profile = SQLite 连接配置文件
