/* Generated By:JJTree: Do not edit this line. C:/work/dtp16/org.eclipse.datatools.sqltools.db.generic/src/org/eclipse/datatools/sqltools/db/generic/parser\GenericSQLParserTreeConstants.java */

package org.eclipse.datatools.sqltools.db.generic.parser;

public interface GenericSQLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTSQLDELIMITER = 2;
  public int JJTSQLSTATEMENT = 3;
  public int JJTSQLDATATYPE = 4;
  public int JJTDECLAREKEYWORD = 5;
  public int JJTDECLARECOMMA = 6;
  public int JJTSQLPARAM = 7;
  public int JJTEXPRESSION = 8;


  public String[] jjtNodeName = {
    "void",
    "Start",
    "SQLDelimiter",
    "SQLStatement",
    "SQLDataType",
    "DeclareKeyword",
    "DeclareComma",
    "SQLParam",
    "Expression",
  };
}
