###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform XML ODA Runtime Driver
oda.data.source.category.name=Source de données XML

datasource.name=Source de données XML
dataset.name=Jeu de données XML

datasource.property.xmlFile=Fichier de source de données XML
datasource.property.xmlEncoding=Codage de la source de données XML
datasource.property.schemaFile=Fichier de schéma XML
oda.data.source.name=Source de données XML
connection.profile.name=Profil de connexion à la source de données XML
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Génération de connexion ODA
