###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform XML ODA Runtime Driver
oda.data.source.category.name=XML 데이터 원본

datasource.name=XML 데이터 원본
dataset.name=XML 데이터 집합

datasource.property.xmlFile=XML 데이터 원본 파일(&X)
datasource.property.xmlEncoding=XML 데이터 원본 인코딩(&E)
datasource.property.schemaFile=XML 스키마 파일(&S)
oda.data.source.name=XML 데이터 원본
connection.profile.name=XML 데이터 원본 연결 프로필
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 연결 팩토리
