###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform XML ODA Runtime Driver
oda.data.source.category.name=XMLデータソース

datasource.name=XMLデータソース
dataset.name=XML データセット

datasource.property.xmlFile=XMLデータソースファイル(&X)
datasource.property.xmlEncoding=XMLデータソースエンコード(&E)
datasource.property.schemaFile=XML スキーマファイル(&S)
oda.data.source.name=XMLデータソース
connection.profile.name=XMLデータソース接続プロファイル
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 接続ファクトリ
