###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
plugin.name=Eclipse Data Tools Platform XML ODA Runtime Driver
oda.data.source.category.name=XML 数据源

datasource.name=XML 数据源
dataset.name=XML 数据集

datasource.property.xmlFile=XML 数据源文件(&X)
datasource.property.xmlEncoding=XML 日期源编码(&E)
datasource.property.schemaFile=XML 架构文件(&S)
oda.data.source.name=XML 数据源
connection.profile.name=XML 数据源连接配置文件
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA 连接工厂
