###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
oda.data.source.category.name=DTP-XML-Datenquelle

datasource.name=DTP-XML-Datenquelle
dataset.name=DTP XML-Datensatz

datasource.property.xmlFile=XML-Datenquellendatei
datasource.property.xmlEncoding=XML-Datenquellen-Codierung
datasource.property.schemaFile=XML-Schema-Datei
oda.data.source.name=DTP-XML-Dateien
connection.profile.name=Verbindungsprofil für Datenquelle der DTPT-XML-Datei
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=ODA-Verbindungs-Factory
