###############################################################################
# Copyright (c) 2004, 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.xml
oda.parent.category.id=org.eclipse.datatools.connectivity.oda.profileCategory
#
###############################################################################
# NLS String
###############################################################################
oda.data.source.category.name=Fuente de datos XML DTP

datasource.name=Fuente de datos XML DTP
dataset.name=Conjunto de datos XML DTP

datasource.property.xmlFile=Archivo de fuente de datos XML
datasource.property.xmlEncoding=Codificación de la fuente de datos XML
datasource.property.schemaFile=Archivo del esquema XML
oda.data.source.name=Archivos XML DTP
connection.profile.name=Perfil de conexión de fuente de datos de archivo XML DTP
#
#  Below NLS messages apply to all ODA data sources; should be re-factored
#
oda.connection.factory.name=Fábrica de conexión ODA
