# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase ASE
profile.ase.wizard.title = Sybase ASE
jdbc.connection.name = JDBC 连接
profile.ase.properties = Sybase ASE 连接属性

database.name=数据库
profile.ase.content = Sybase ASE SQL 模型内容扩展

driversExtension.name = Sybase JDBC 驱动程序
drivers.ase.name = Sybase ASE
drivers.ase.xa.name = Sybase ASE XA
drivers.ase.description = Sybase Adaptive Server Enterprise (ASE) 数据库的 JDBC 驱动程序
drivers.ase.xa.description = 启用 XA 的 Sybase Adaptive Server Enterprise (ASE) 数据库的 JDBC 驱动程序
proxytable.name = 代理表
default.name = 默认
rule.name = 规则
trigger.name = 触发器
webservice.name = Web 服务
datatype.name = 数据类型
datatype.node.name = 数据类型文件夹
default.node.name = 默认文件夹
rule.node.name = 规则文件夹
proxytable.node.name = 代理表文件夹
webservicetable.node.name = 作为表的 Web 服务文件夹

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = 数据库连接配置文件

decorator.label = Sybase 系统表装饰器

