# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase ASE
profile.ase.wizard.title = Sybase ASE
jdbc.connection.name = JDBC 接続
profile.ase.properties = Sybase ASE 接続プロパティ

database.name=データベース
profile.ase.content = Sybase ASE SQL Model Content Extension

driversExtension.name = Sybase JDBC ドライバ
drivers.ase.name = Sybase ASE
drivers.ase.xa.name = Sybase ASE XA
drivers.ase.description = Sybase Adaptive Server Enterprise (ASE) データベース用 JDBC ドライバ
drivers.ase.xa.description = XA が有効な Sybase Adaptive Server Enterprise (ASE) データベース用 JDBC ドライバ
proxytable.name = プロキシテーブル
default.name = デフォルト
rule.name = 規則
trigger.name = トリガ
webservice.name = Web サービス
datatype.name = データ型
datatype.node.name = データ型フォルダ
default.node.name = デフォルトフォルダ
rule.node.name = 規則フォルダ
proxytable.node.name = プロキシテーブルフォルダ
webservicetable.node.name = テーブルフォルダとしての Web サービス

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = データベース接続プロファイル

decorator.label = Sybase System Table Decorator

