# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase ASE
profile.ase.wizard.title = Sybase ASE
jdbc.connection.name = JDBC 연결
profile.ase.properties = Sybase ASE 연결 속성

database.name=데이터베이스
profile.ase.content = Sybase ASE SQL 모델 콘텐츠 확장명

driversExtension.name = Sybase JDBC 드라이버
drivers.ase.name = Sybase ASE
drivers.ase.xa.name = Sybase ASE XA
drivers.ase.description = Sybase ASE(Adaptive Server Enterprise) 데이터베이스용 JDBC 드라이버
drivers.ase.xa.description = XA 지원 Sybase ASE( Adaptive Server Enterprise) 데이터베이스용 JDBC 드라이버
proxytable.name = 프록시 테이블
default.name = 기본값
rule.name = 규칙
trigger.name = 트리거
webservice.name = 웹 서비스
datatype.name = 데이터 형식
datatype.node.name = 데이터 형식 폴더
default.node.name = 기본값 폴더
rule.node.name = 규칙 폴더
proxytable.node.name = 프록시 테이블 폴더
webservicetable.node.name = 웹 서비스 테이블 폴더

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = 데이터베이스 연결 프로필

decorator.label = Sybase 시스템 테이블 데코레이터

