# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase ASE
profile.ase.wizard.title = Sybase ASE
jdbc.connection.name = Conexión JDBC
profile.ase.properties = Propiedades de conexión Sybase ASE

database.name=Base de datos
profile.ase.content = Extensión de contenido del modelo SQL de Sybase ASE

driversExtension.name = Controladores JDBC de Sybase
drivers.ase.name = Sybase ASE
drivers.ase.xa.name = Sybase ASE XA
drivers.ase.description = Controlador JDBC para una base de datos Sybase Adaptive Server Enterprise (ASE)
drivers.ase.xa.description = Controlador JDBC para una base de datos Sybase Adaptive Server Enterprise (ASE) activada para XA
proxytable.name = Tabla de proxy
default.name = Predeterminado
rule.name = Regla
trigger.name = Activador
webservice.name = Servicio Web
datatype.name = Tipo de datos
datatype.node.name = Carpeta de tipo de datos
default.node.name = Carpeta predeterminada
rule.node.name = Carpeta regla
proxytable.node.name = Carpeta tabla de proxy
webservicetable.node.name = Servicios Web como Carpeta tablas

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = Perfil de conexión de la base de datos

decorator.label = Decorador de tablas del sistema Sybase

