# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase ASE
profile.ase.wizard.title = Sybase ASE
jdbc.connection.name = Connexion JDBC
profile.ase.properties = Propriétés de la connexion Sybase ASE

database.name=Base de données
profile.ase.content = Extension de contenu du modèle Sybase ASE SQL

driversExtension.name = Pilotes JDBC Sybase
drivers.ase.name = Sybase ASE
drivers.ase.xa.name = Sybase ASE XA
drivers.ase.description = Pilote JDBC pour une base de données Sybase Adaptive Server Enterprise (ASE)
drivers.ase.xa.description = Pilote JDBC pour une base de données Sybase Adaptive Server Enterprise (ASE) compatible XA
proxytable.name = Table Proxy
default.name = Par défaut
rule.name = Règle
trigger.name = Déclencheur
webservice.name = Service Web
datatype.name = Type de données
datatype.node.name = Dossier Type de données
default.node.name = Dossier Par défaut
rule.node.name = Dossier Règles
proxytable.node.name = Dossier Table Proxy
webservicetable.node.name = Services Web comme dossier Tables

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = Profil de connexion de base de données

decorator.label = Décorateur de table système Sybase

