# *******************************************************************************
# * Copyright (c) 2008 Sybase, Inc.
# * 
# * All rights reserved. This program and the accompanying materials are made
# * available under the terms of the Eclipse Public License 2.0 which
# * accompanies this distribution, and is available at
# * https://www.eclipse.org/legal/epl-2.0/
# * 
# * Contributors: Sybase - initial API and implementation
# ******************************************************************************
profile.ase.title = Sybase-ASE
profile.ase.wizard.title = Sybase-ASE
jdbc.connection.name = JDBC-Verbindung
profile.ase.properties = Sybase-ASE-Verbindungseigenschaften

database.name=Datenbank
profile.ase.content = Sybase-ASE-SQL-Modell - Inhaltserweiterung

driversExtension.name = Sybase-JDBC-Treiber
drivers.ase.name = Sybase-ASE
drivers.ase.xa.name = Sybase-ASE-XA
drivers.ase.description = JDBC-Treiber für eine Sybase Adaptive Server Enterprise (ASE)-Datenbank
drivers.ase.xa.description = JDBC-Treiber für eine XA-fähige Sybase Adaptive Server Enterprise (ASE)-Datenbank
proxytable.name = Proxy-Tabelle
default.name = Standard
rule.name = Regel
trigger.name = Auslösen
webservice.name = Webdienst
datatype.name = Datentyp
datatype.node.name = Datentypordner
default.node.name = Standardordner
rule.node.name = Regelordner
proxytable.node.name = Proxy-Tabellenordner
webservicetable.node.name = Webdienste als Tabellenordner

pluginName = Sybase UI Plug-in
providerName = Eclipse.org

database.connection.profile.title = Datenbankverbindungsprofil

decorator.label = Sybase-Systemtabellendekorator

