###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform IBM DB2 UDB UI iSeries Plug-in
providerName=Eclipse Data Tools Platform

profile.db2.iseries.wizard.title = DB2 para i5/OS
profile.db2.iseries.wizard.description = Crear una DB2 para perfil de conexión i5/OS.
profile.db2.iseries.properties = Propiedades de controlador
