###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## SQL Server Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = 데이터베이스(&D):
CUI_NEWCW_HOST_LBL_UI_ = 호스트(&H):
CUI_NEWCW_PORT_LBL_UI_ = 포트 번호(&M):
CUI_NEWCW_CONNECTIONURL_LBL_UI_= 연결 URL(&L):
CUI_NEWCW_DEFDBNAME_VAL_UI_ = pubs
CUI_NEWCW_INTEGRATED_AUTHENTICATION_BTN_UI_ = 통합 인증 사용
CUI_NEWCW_USERNAME_LBL_UI_ = 사용자 이름(&A):
CUI_NEWCW_PASSWORD_LBL_UI_ = 암호(&W):
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = 암호 저장(&V)
CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = 데이터베이스
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = 호스트
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = 포트 번호
CUI_NEWCW_USE_INTEGRATED_AUTHENICATION_SUMMARY_DATA_TEXT_ = 통합 인증 사용
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = 사용자 이름:
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = 암호 저장
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = 참
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = 거짓
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = 데이터베이스 이름을 입력하십시오(예: {0}).
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= 데이터베이스 서버의 호스트 이름을 입력하십시오.
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = 데이터베이스 서버의 연결 포트 번호를 입력하십시오.
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = 사용자 이름을 입력하십시오.
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = 암호를 입력하십시오.



