#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=新建 ODA 运行时驱动程序插件
designWizard_windowTitle=新建 ODA 设计器插件
#
baseSection_optLabel_packageName=Java 包名称(&J)
baseSection_optLabel_dataSetName=数据集显示名称(&E)
baseSection_optLabel_dataSourceName=数据源显示名称(&S)
baseSection_dataSetNameSuffix=数据集
baseSection_dataSourceNameSuffix=数据源
baseSection_illegaCharsForIdentifier=输入值包含非法字符 
baseSection_pageDesc=指定将用于生成开放数据访问 (ODA) 插件的选项。
#
designSection_optLabel_driverClass=ODA 运行时驱动程序类(&D)
designSection_optLabel_driverPluginId=ODA 运行时驱动程序插件 ID(&P)
designSection_optLabel_odaDataSetId=ODA 运行时数据集元素 ID(&D)
designSection_optLabel_odaDataSourceId=ODA 运行时数据源元素 ID(&I)
designSection_wizardPageTitle=ODA 数据源设计器
#
runtimeSection_optLabel_numSetProps=数据集属性数(&R)
runtimeSection_optLabel_numSourceProps=数据源属性数(&P)
runtimeSection_optLabel_odaDataSourceId=ODA 数据源元素 ID(&I)
runtimeSection_wizardPageTitle=ODA 数据源运行时驱动程序
#
modeler_odaConnectionFactory=ODA 连接工厂
modeler_propertyDisplayNamePrefix=属性
