#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=ODA 実行時ドライバのプラグインの新規作成
designWizard_windowTitle=ODA デザイナのプラグインの新規作成
#
baseSection_optLabel_packageName=Java のパッケージ名(&J)
baseSection_optLabel_dataSetName=データセットの表示名(&E)
baseSection_optLabel_dataSourceName=データソースの表示名(&S)
baseSection_dataSetNameSuffix=データセット
baseSection_dataSourceNameSuffix=データソース
baseSection_illegaCharsForIdentifier=入力したいくつかの文字は、次の項目には使えません : 
baseSection_pageDesc=オープンデータアクセス (ODA) のプラグインを生成するときに使用するオプションを指定してください。
#
designSection_optLabel_driverClass=ODA 実行時ドライバのクラス(&D)
designSection_optLabel_driverPluginId=ODA 実行時ドライバのプラグイン ID(&P)
designSection_optLabel_odaDataSetId=ODA 実行時データセットの要素 ID(&D)
designSection_optLabel_odaDataSourceId=ODA 実行時データソースの要素 ID(&I)
designSection_wizardPageTitle=ODA データソースデザイナ
#
runtimeSection_optLabel_numSetProps=データセットのプロパティ数(&R)
runtimeSection_optLabel_numSourceProps=データソースのプロパティ数(&P)
runtimeSection_optLabel_odaDataSourceId=ODA データソースの要素 ID(&I)
runtimeSection_wizardPageTitle=ODA データソースの実行時ドライバ
#
modeler_odaConnectionFactory=ODA 接続ファクトリ
modeler_propertyDisplayNamePrefix=プロパティ
