#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=Nuevo complemento de controlador de tiempo de ejecución ODA
designWizard_windowTitle=Nuevo complemento de diseñador ODA
#
baseSection_optLabel_packageName=Nombre de paquete &Java
baseSection_optLabel_dataSetName=Nombr&e en pantalla de conjunto de datos
baseSection_optLabel_dataSourceName=Nombre en pantalla de fuente de dato&s:
baseSection_dataSetNameSuffix=Conjunto de datos
baseSection_dataSourceNameSuffix=Fuente de datos
baseSection_illegaCharsForIdentifier=El valor de entrada contiene caracteres no válidos para 
baseSection_pageDesc=Especifique las opciones que se usarán para generar el complemento de acceso a datos abiertos (ODA, Open Data Access).
#
designSection_optLabel_driverClass=Clase de controla&dor de tiempo de ejecución ODA
designSection_optLabel_driverPluginId=ID de com&plemento de controlador de tiempo de ejecución ODA
designSection_optLabel_odaDataSetId=I&D de elemento de conjunto de datos de tiempo de ejecución ODA.
designSection_optLabel_odaDataSourceId=&ID de elemento de fuente de datos de tiempo de ejecución ODA.
designSection_wizardPageTitle=Diseñador de fuente de datos ODA
#
runtimeSection_optLabel_numSetProps=Número de p&ropiedades de conjunto de datos
runtimeSection_optLabel_numSourceProps=Número de &propiedades de fuentes de datos
runtimeSection_optLabel_odaDataSourceId=&ID de elemento de fuente de datos ODA
runtimeSection_wizardPageTitle=Controlador de tiempo de ejecución de fuente de datos ODA
#
modeler_odaConnectionFactory=Fábrica de conexión ODA
modeler_propertyDisplayNamePrefix=Propiedad
