#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=Nouveau plug-in de pilote d'exécution ODA
designWizard_windowTitle=Nouveau plug-in de conception ODA
#
baseSection_optLabel_packageName=&Nom du package Java
baseSection_optLabel_dataSetName=Nom d'affichage du j&eu de données
baseSection_optLabel_dataSourceName=Nom d'affichage de la &source de données
baseSection_dataSetNameSuffix=Jeu de données
baseSection_dataSourceNameSuffix=Source de données
baseSection_illegaCharsForIdentifier=La valeur d'entrée contient des caractères illégaux pour 
baseSection_pageDesc=Spécifiez les options qui seront utilisées pour générer le plug-in d'accès aux données ouvertes (ODA).
#
designSection_optLabel_driverClass=Classe de pilote &d'exécution ODA
designSection_optLabel_driverPluginId=ID de &plug-in de pilote d'exécution ODA
designSection_optLabel_odaDataSetId=I&D d'élément de jeu de données d'exécution ODA
designSection_optLabel_odaDataSourceId=&ID d'élément de source de données d'exécution ODA
designSection_wizardPageTitle=Conception de source de données ODA
#
runtimeSection_optLabel_numSetProps=Nombre de p&ropriétés de jeu de données
runtimeSection_optLabel_numSourceProps=Nombre de &propriétés de source de données
runtimeSection_optLabel_odaDataSourceId=&ID d'élément de source de données ODA
runtimeSection_wizardPageTitle=Pilote d'exécution de source de données ODA
#
modeler_odaConnectionFactory=Génération de connexion ODA
modeler_propertyDisplayNamePrefix=Propriété
