#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=새 ODA 런타임 드라이버 플러그인
designWizard_windowTitle=새 ODA 디자이너 플러그인
#
baseSection_optLabel_packageName=Java 패키지 이름(&J)
baseSection_optLabel_dataSetName=데이터 집합 표시 이름(&E)
baseSection_optLabel_dataSourceName=데이터 원본 표시 이름(&S)
baseSection_dataSetNameSuffix=데이터 집합
baseSection_dataSourceNameSuffix=데이터 원본
baseSection_illegaCharsForIdentifier=해당 입력 값에 적합하지 않은 문자가 있습니다. 
baseSection_pageDesc=개방형 데이터 액세스(ODA) 플러그인 생성에 사용되는 해당 옵션을 지정합니다.
#
designSection_optLabel_driverClass=ODA 런타임 드라이버 클래스(&D)
designSection_optLabel_driverPluginId=ODA 런타임 드라이버 플러그인 ID(&P)
designSection_optLabel_odaDataSetId=ODA 런타임 데이터 집합 요소 ID(&D)
designSection_optLabel_odaDataSourceId=ODA 런타임 데이터 원본 요소 ID(&I)
designSection_wizardPageTitle=ODA 데이터 원본 디자이너
#
runtimeSection_optLabel_numSetProps=데이터 집합 속성의 수(&R)
runtimeSection_optLabel_numSourceProps=데이터 원본 속성의 수(&P)
runtimeSection_optLabel_odaDataSourceId=ODA 데이터 원본 요소 ID(&I)
runtimeSection_wizardPageTitle=ODA 데이터 원본 런타임 드라이버
#
modeler_odaConnectionFactory=ODA 연결 팩토리
modeler_propertyDisplayNamePrefix=속성
