#
#************************************************************************
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
driverWizard_windowTitle=Neues ODA-Laufzeittreiber-Plug-In
designWizard_windowTitle=Neues Plug-In für ODA-Designer
#
baseSection_optLabel_packageName=&Java-Paketname
baseSection_optLabel_dataSetName=Anzeigename des Daten&satzes
baseSection_optLabel_dataSourceName=Anzeigename der Daten&quelle
baseSection_dataSetNameSuffix=Datensatz
baseSection_dataSourceNameSuffix=Datenquelle
baseSection_illegaCharsForIdentifier=Der Eingabewert enthält unzulässige(s) Zeichen für 
baseSection_pageDesc=Geben Sie die Optionen an, die zum Generieren des Open Data Access (ODA)-Plug-In verwendet werden.
#
designSection_optLabel_driverClass=ODA-Laufzeit&treiberklasse
designSection_optLabel_driverPluginId=ODA-Laufzeittreiber-&Plug-In-ID
designSection_optLabel_odaDataSetId=ODA-Laufzeit-Datensatzelement-I&D
designSection_optLabel_odaDataSourceId=ODA-Laufzeit-Datenquellenelement-&ID
designSection_wizardPageTitle=ODA-Datenquellen-Designer
#
runtimeSection_optLabel_numSetProps=Anzahl der Datensatzei&genschaften
runtimeSection_optLabel_numSourceProps=Anzahl der Datenquellen&eigenschaften
runtimeSection_optLabel_odaDataSourceId=ODA-Datenquellenele&ment-ID
runtimeSection_wizardPageTitle=ODA-Datenquellen-Laufzeittreiber
#
modeler_odaConnectionFactory=ODA-Verbindungs-Factory
modeler_propertyDisplayNamePrefix=Eigenschaft
