/* Generated By:JJTree&JavaCC: Do not edit this line. QuickSQLParserConstants.java */
package org.eclipse.datatools.enablement.sybase.parser;

public interface QuickSQLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 6;
  int COMMENT_CONTENT = 11;
  int INVALID_TOKEN = 13;
  int ADD = 14;
  int ALTER = 15;
  int AND = 16;
  int ANY = 17;
  int AS = 18;
  int ASC = 19;
  int AT = 20;
  int AUTHORIZATION = 21;
  int AVG = 22;
  int BEGIN = 23;
  int BETWEEN = 24;
  int BREAK = 25;
  int BROWSE = 26;
  int BULK = 27;
  int BY = 28;
  int CASCADE = 29;
  int CASE = 30;
  int CHECK = 31;
  int CHECKPOINT = 32;
  int CLOSE = 33;
  int CLUSTERED = 34;
  int COALESCE = 35;
  int COMMIT = 36;
  int COMPUTE = 37;
  int CONFIRM = 38;
  int CONNECT = 39;
  int CONSTRAINT = 40;
  int CONTINUE = 41;
  int CONTROLROW = 42;
  int CONVERT = 43;
  int COUNT = 44;
  int CREATE = 45;
  int CURRENT = 46;
  int CURSOR = 47;
  int DATABASE = 48;
  int DBCC = 49;
  int DEALLOCATE = 50;
  int DECLARE = 51;
  int DEFAULT_VAL = 52;
  int DELETE = 53;
  int DESC = 54;
  int DETERMINISTIC = 55;
  int DISK = 56;
  int DISTINCT = 57;
  int DROP = 58;
  int DUMMY = 59;
  int DUMP = 60;
  int ELSE = 61;
  int END = 62;
  int ENDTRAN = 63;
  int ESCAPE = 64;
  int EXCEPT = 65;
  int EXCLUSIVE = 66;
  int EXEC = 67;
  int EXECUTE = 68;
  int EXISTS = 69;
  int EXIT = 70;
  int EXTERNAL = 71;
  int EVENT = 72;
  int FETCH = 73;
  int FILLFACTOR = 74;
  int FOR = 75;
  int FOREIGN = 76;
  int FROM = 77;
  int FUNC = 78;
  int FUNCTION = 79;
  int GO = 80;
  int GOTO = 81;
  int GRANT = 82;
  int GROUP = 83;
  int HAVING = 84;
  int HOLDLOCK = 85;
  int IDENTITY = 86;
  int IF = 87;
  int IN = 88;
  int INDEX = 89;
  int INOUT = 90;
  int INSERT = 91;
  int INSTALL = 92;
  int INTERSECT = 93;
  int INTO = 94;
  int IS = 95;
  int ISOLATION = 96;
  int JAR = 97;
  int JOIN = 98;
  int KEY = 99;
  int KILL = 100;
  int LEVEL = 101;
  int LIKE = 102;
  int LOAD = 103;
  int LOCK = 104;
  int MAX = 105;
  int MIN = 106;
  int MODIFY = 107;
  int NATIONAL = 108;
  int NOHOLDLOCK = 109;
  int NONCLUSTERED = 110;
  int NOT = 111;
  int NULL = 112;
  int NULLIF = 113;
  int OF = 114;
  int OFF = 115;
  int OFFSETS = 116;
  int ON = 117;
  int ONCE = 118;
  int ONLINE = 119;
  int ONLY = 120;
  int OPEN = 121;
  int OPTION = 122;
  int OR = 123;
  int ORDER = 124;
  int OUT = 125;
  int OUTPUT = 126;
  int OVER = 127;
  int PARTITION = 128;
  int PERM = 129;
  int PERMANENT = 130;
  int PLAN = 131;
  int PREPARE = 132;
  int PRIMARY = 133;
  int PRINT = 134;
  int PRIVILEGES = 135;
  int PROC = 136;
  int PROCEDURE = 137;
  int PROCESSEXIT = 138;
  int PROXY_TABLE = 139;
  int PUBLIC = 140;
  int QUIESCE = 141;
  int RAISERROR = 142;
  int READ = 143;
  int READPAST = 144;
  int READTEXT = 145;
  int RECONFIGURE = 146;
  int REFERENCES = 147;
  int REMOVE = 148;
  int REORG = 149;
  int REPLACE = 150;
  int REPLICATION = 151;
  int RETURN = 152;
  int RETURNS = 153;
  int REVOKE = 154;
  int ROLE = 155;
  int ROLLBACK = 156;
  int ROWCOUNT = 157;
  int ROWS = 158;
  int RULE = 159;
  int SAVE = 160;
  int SCHEMA = 161;
  int SELECT = 162;
  int SET = 163;
  int SETUSER = 164;
  int SHARED = 165;
  int SHUTDOWN = 166;
  int SOME = 167;
  int STATISTICS = 168;
  int STRINGSIZE = 169;
  int STRIPE = 170;
  int SUM = 171;
  int TABLE = 172;
  int TEMP = 173;
  int TEMPORARY = 174;
  int TEXTSIZE = 175;
  int TO = 176;
  int TRAN = 177;
  int TRANSACTION = 178;
  int TRIGGER = 179;
  int TRUNCATE = 180;
  int UNION = 181;
  int UNIQUE = 182;
  int UNPARTITION = 183;
  int UPDATE = 184;
  int USE = 185;
  int USER = 186;
  int USING = 187;
  int VALUES = 188;
  int VARYING = 189;
  int VIEW = 190;
  int WAITFOR = 191;
  int WHEN = 192;
  int WHERE = 193;
  int WHILE = 194;
  int WITH = 195;
  int WORK = 196;
  int WRITETEXT = 197;
  int SQLCODE = 198;
  int SQLSTATE = 199;
  int OPENDESCRIPTION = 200;
  int CLOSEDESCRIPTION = 201;
  int DESCRIPTION = 202;
  int INTEGER_LITERAL = 203;
  int FLOATING_POINT_LITERAL = 204;
  int EXPONENT = 205;
  int SINGLE_STRING_LITERAL = 206;
  int DOUBLE_STRING_LITERAL = 207;
  int BINARY_LITERAL = 208;
  int HEXDIGIT = 209;
  int MONEY_LITERAL = 210;
  int ID = 211;
  int SQUARE_BRACKET_ID = 212;
  int VAR_NAME_BODY = 213;
  int VAR_NAME = 214;
  int LABEL = 215;
  int GLOBAL_VAR_NAME = 216;
  int TEMP_TABLE_NAME = 217;
  int LETTER = 218;
  int DIGIT = 219;
  int SYMBOL = 220;
  int CONCAT = 221;
  int COMMA = 222;
  int SEMICOLON = 223;
  int DOT = 224;
  int ROWTYPE = 225;
  int TILDE = 226;
  int LESS = 227;
  int LESSEQUAL = 228;
  int GREATER = 229;
  int GREATEREQUAL = 230;
  int EQUAL = 231;
  int NOTEQUAL = 232;
  int JOINPLUS = 233;
  int OPENPAREN = 234;
  int CLOSEPAREN = 235;
  int ASTERISK = 236;
  int SLASH = 237;
  int PLUS = 238;
  int MINUS = 239;
  int QUESTIONMARK = 240;
  int LEQJOIN = 241;
  int REQJOIN = 242;
  int JAVA_REF = 243;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;
  int IGNORE_STATE = 3;
  int DESCRIPTION_START_STATE = 4;
  int DESCRIPTION_STATE = 5;

  String[] tokenImage = {
    "<EOF>", //$NON-NLS-1$
    "\" \"", //$NON-NLS-1$
    "\"\\n\"", //$NON-NLS-1$
    "\"\\r\"", //$NON-NLS-1$
    "\"\\t\"", //$NON-NLS-1$
    "\"--\"", //$NON-NLS-1$
    "<SINGLE_LINE_COMMENT>", //$NON-NLS-1$
    "<token of kind 7>", //$NON-NLS-1$
    "\"/*\"", //$NON-NLS-1$
    "\"/*\"", //$NON-NLS-1$
    "\"*/\"", //$NON-NLS-1$
    "<COMMENT_CONTENT>", //$NON-NLS-1$
    "<token of kind 12>", //$NON-NLS-1$
    "\"!%^&\"", //$NON-NLS-1$
    "\"add\"", //$NON-NLS-1$
    "\"alter\"", //$NON-NLS-1$
    "\"and\"", //$NON-NLS-1$
    "\"any\"", //$NON-NLS-1$
    "\"as\"", //$NON-NLS-1$
    "\"asc\"", //$NON-NLS-1$
    "\"at\"", //$NON-NLS-1$
    "\"authorization\"", //$NON-NLS-1$
    "\"avg\"", //$NON-NLS-1$
    "\"begin\"", //$NON-NLS-1$
    "\"between\"", //$NON-NLS-1$
    "\"break\"", //$NON-NLS-1$
    "\"browse\"", //$NON-NLS-1$
    "\"bulk\"", //$NON-NLS-1$
    "\"by\"", //$NON-NLS-1$
    "\"cascade\"", //$NON-NLS-1$
    "\"case\"", //$NON-NLS-1$
    "\"check\"", //$NON-NLS-1$
    "\"checkpoint\"", //$NON-NLS-1$
    "\"close\"", //$NON-NLS-1$
    "\"clustered\"", //$NON-NLS-1$
    "\"coalesce\"", //$NON-NLS-1$
    "\"commit\"", //$NON-NLS-1$
    "\"compute\"", //$NON-NLS-1$
    "\"confirm\"", //$NON-NLS-1$
    "\"connect\"", //$NON-NLS-1$
    "\"constraint\"", //$NON-NLS-1$
    "\"continue\"", //$NON-NLS-1$
    "\"controlrow\"", //$NON-NLS-1$
    "\"convert\"", //$NON-NLS-1$
    "\"count\"", //$NON-NLS-1$
    "\"create\"", //$NON-NLS-1$
    "\"current\"", //$NON-NLS-1$
    "\"cursor\"", //$NON-NLS-1$
    "\"database\"", //$NON-NLS-1$
    "\"dbcc\"", //$NON-NLS-1$
    "\"deallocate\"", //$NON-NLS-1$
    "\"declare\"", //$NON-NLS-1$
    "\"default\"", //$NON-NLS-1$
    "\"delete\"", //$NON-NLS-1$
    "\"desc\"", //$NON-NLS-1$
    "\"deterministic\"", //$NON-NLS-1$
    "\"disk\"", //$NON-NLS-1$
    "\"distinct\"", //$NON-NLS-1$
    "\"drop\"", //$NON-NLS-1$
    "\"dummy\"", //$NON-NLS-1$
    "\"dump\"", //$NON-NLS-1$
    "\"else\"", //$NON-NLS-1$
    "\"end\"", //$NON-NLS-1$
    "\"endtran\"", //$NON-NLS-1$
    "\"escape\"", //$NON-NLS-1$
    "\"except\"", //$NON-NLS-1$
    "\"exclusive\"", //$NON-NLS-1$
    "\"exec\"", //$NON-NLS-1$
    "\"execute\"", //$NON-NLS-1$
    "\"exists\"", //$NON-NLS-1$
    "\"exit\"", //$NON-NLS-1$
    "\"external\"", //$NON-NLS-1$
    "\"event\"", //$NON-NLS-1$
    "\"fetch\"", //$NON-NLS-1$
    "\"fillfactor\"", //$NON-NLS-1$
    "\"for\"", //$NON-NLS-1$
    "\"foreign\"", //$NON-NLS-1$
    "\"from\"", //$NON-NLS-1$
    "\"func\"", //$NON-NLS-1$
    "\"function\"", //$NON-NLS-1$
    "\"go\"", //$NON-NLS-1$
    "\"goto\"", //$NON-NLS-1$
    "\"grant\"", //$NON-NLS-1$
    "\"group\"", //$NON-NLS-1$
    "\"having\"", //$NON-NLS-1$
    "\"holdlock\"", //$NON-NLS-1$
    "\"identity\"", //$NON-NLS-1$
    "\"if\"", //$NON-NLS-1$
    "\"in\"", //$NON-NLS-1$
    "\"index\"", //$NON-NLS-1$
    "\"inout\"", //$NON-NLS-1$
    "\"insert\"", //$NON-NLS-1$
    "\"install\"", //$NON-NLS-1$
    "\"intersect\"", //$NON-NLS-1$
    "\"into\"", //$NON-NLS-1$
    "\"is\"", //$NON-NLS-1$
    "\"isolation\"", //$NON-NLS-1$
    "\"jar\"", //$NON-NLS-1$
    "\"join\"", //$NON-NLS-1$
    "\"key\"", //$NON-NLS-1$
    "\"kill\"", //$NON-NLS-1$
    "\"level\"", //$NON-NLS-1$
    "\"like\"", //$NON-NLS-1$
    "\"load\"", //$NON-NLS-1$ 
    "\"lock\"", //$NON-NLS-1$
    "\"max\"", //$NON-NLS-1$
    "\"min\"", //$NON-NLS-1$
    "\"modify\"", //$NON-NLS-1$
    "\"national\"", //$NON-NLS-1$
    "\"noholdlock\"", //$NON-NLS-1$
    "\"nonclustered\"", //$NON-NLS-1$
    "\"not\"", //$NON-NLS-1$
    "\"null\"", //$NON-NLS-1$
    "\"nullif\"", //$NON-NLS-1$
    "\"of\"", //$NON-NLS-1$
    "\"off\"", //$NON-NLS-1$
    "\"offsets\"", //$NON-NLS-1$
    "\"on\"", //$NON-NLS-1$
    "\"once\"", //$NON-NLS-1$
    "\"online\"", //$NON-NLS-1$
    "\"only\"", //$NON-NLS-1$
    "\"open\"", //$NON-NLS-1$
    "\"option\"", //$NON-NLS-1$
    "\"or\"", //$NON-NLS-1$
    "\"order\"", //$NON-NLS-1$
    "\"out\"", //$NON-NLS-1$
    "\"output\"", //$NON-NLS-1$
    "\"over\"", //$NON-NLS-1$
    "\"partition\"", //$NON-NLS-1$
    "\"perm\"", //$NON-NLS-1$
    "\"permanent\"", //$NON-NLS-1$
    "\"plan\"", //$NON-NLS-1$
    "\"prepare\"", //$NON-NLS-1$
    "\"primary\"", //$NON-NLS-1$
    "\"print\"", //$NON-NLS-1$
    "\"privileges\"", //$NON-NLS-1$
    "\"proc\"", //$NON-NLS-1$
    "\"procedure\"", //$NON-NLS-1$
    "\"processexit\"", //$NON-NLS-1$
    "\"proxy_table\"", //$NON-NLS-1$
    "\"public\"", //$NON-NLS-1$
    "\"quiesce\"", //$NON-NLS-1$
    "\"raiserror\"", //$NON-NLS-1$
    "\"read\"", //$NON-NLS-1$
    "\"readpast\"", //$NON-NLS-1$
    "\"readtext\"", //$NON-NLS-1$
    "\"reconfigure\"", //$NON-NLS-1$
    "\"references\"", //$NON-NLS-1$
    "\"remove\"", //$NON-NLS-1$
    "\"reorg\"", //$NON-NLS-1$
    "\"replace\"", //$NON-NLS-1$
    "\"replication\"", //$NON-NLS-1$
    "\"return\"", //$NON-NLS-1$
    "\"returns\"", //$NON-NLS-1$
    "\"revoke\"", //$NON-NLS-1$
    "\"role\"", //$NON-NLS-1$
    "\"rollback\"", //$NON-NLS-1$
    "\"rowcount\"", //$NON-NLS-1$
    "\"rows\"", //$NON-NLS-1$
    "\"rule\"", //$NON-NLS-1$
    "\"save\"", //$NON-NLS-1$
    "\"schema\"", //$NON-NLS-1$
    "\"select\"", //$NON-NLS-1$
    "\"set\"", //$NON-NLS-1$
    "\"setuser\"", //$NON-NLS-1$
    "\"shared\"", //$NON-NLS-1$
    "\"shutdown\"", //$NON-NLS-1$
    "\"some\"", //$NON-NLS-1$
    "\"statistics\"", //$NON-NLS-1$
    "\"stringsize\"", //$NON-NLS-1$
    "\"stripe\"", //$NON-NLS-1$
    "\"sum\"", //$NON-NLS-1$
    "\"table\"", //$NON-NLS-1$
    "\"temp\"", //$NON-NLS-1$
    "\"temporary\"", //$NON-NLS-1$
    "\"textsize\"", //$NON-NLS-1$
    "\"to\"", //$NON-NLS-1$
    "\"tran\"", //$NON-NLS-1$
    "\"transaction\"", //$NON-NLS-1$
    "\"trigger\"", //$NON-NLS-1$
    "\"truncate\"", //$NON-NLS-1$
    "\"union\"", //$NON-NLS-1$
    "\"unique\"", //$NON-NLS-1$
    "\"unpartition\"",//$NON-NLS-1$
    "\"update\"", //$NON-NLS-1$
    "\"use\"", //$NON-NLS-1$
    "\"user\"", //$NON-NLS-1$
    "\"using\"", //$NON-NLS-1$ 
    "\"values\"", //$NON-NLS-1$
    "\"varying\"", //$NON-NLS-1$
    "\"view\"", //$NON-NLS-1$
    "\"waitfor\"", //$NON-NLS-1$
    "\"when\"", //$NON-NLS-1$
    "\"where\"", //$NON-NLS-1$
    "\"while\"", //$NON-NLS-1$ 
    "\"with\"", //$NON-NLS-1$
    "\"work\"", //$NON-NLS-1$
    "\"writetext\"", //$NON-NLS-1$
    "\"SQLCODE\"", //$NON-NLS-1$
    "\"SQLSTATE\"", //$NON-NLS-1$
    "\"\\r\\n\"", //$NON-NLS-1$
    "\"~\"", //$NON-NLS-1$
    "<DESCRIPTION>", //$NON-NLS-1$
    "<INTEGER_LITERAL>", //$NON-NLS-1$
    "<FLOATING_POINT_LITERAL>", //$NON-NLS-1$
    "<EXPONENT>", //$NON-NLS-1$
    "<SINGLE_STRING_LITERAL>", //$NON-NLS-1$
    "<DOUBLE_STRING_LITERAL>", //$NON-NLS-1$
    "<BINARY_LITERAL>", //$NON-NLS-1$
    "<HEXDIGIT>", //$NON-NLS-1$
    "<MONEY_LITERAL>", //$NON-NLS-1$
    "<ID>", //$NON-NLS-1$
    "<SQUARE_BRACKET_ID>", //$NON-NLS-1$
    "<VAR_NAME_BODY>", //$NON-NLS-1$
    "<VAR_NAME>", //$NON-NLS-1$
    "<LABEL>", //$NON-NLS-1$
    "<GLOBAL_VAR_NAME>", //$NON-NLS-1$
    "<TEMP_TABLE_NAME>", //$NON-NLS-1$
    "<LETTER>", //$NON-NLS-1$
    "<DIGIT>", //$NON-NLS-1$
    "<SYMBOL>", //$NON-NLS-1$
    "\"||\"", //$NON-NLS-1$
    "\",\"", //$NON-NLS-1$
    "\";\"", //$NON-NLS-1$
    "\".\"", //$NON-NLS-1$
    "\"%rowtype\"", //$NON-NLS-1$
    "\"~\"", //$NON-NLS-1$
    "\"<\"", //$NON-NLS-1$
    "\"<=\"", //$NON-NLS-1$
    "\">\"", //$NON-NLS-1$
    "\">=\"", //$NON-NLS-1$
    "\"=\"", //$NON-NLS-1$
    "\"!=\"", //$NON-NLS-1$
    "\"(+)\"", //$NON-NLS-1$
    "\"(\"", //$NON-NLS-1$
    "\")\"", //$NON-NLS-1$
    "\"*\"", //$NON-NLS-1$
    "\"/\"", //$NON-NLS-1$
    "\"+\"", //$NON-NLS-1$
    "\"-\"", //$NON-NLS-1$
    "\"?\"", //$NON-NLS-1$
    "\"*=\"", //$NON-NLS-1$
    "\"=*\"", //$NON-NLS-1$
    "\">>\"", //$NON-NLS-1$
  };

}
