/* Generated By:JJTree: Do not edit this line. C:/work/workspace/org.eclipse.datatools.enablement.sybase/src/org/eclipse/datatools/enablement/sybase/parser\QuickSQLParserTreeConstants.java */

package org.eclipse.datatools.enablement.sybase.parser;

public interface QuickSQLParserTreeConstants
{
  public int JJTSTRING_LITERAL = 0;
  public int JJTANY_STMT_TOKEN = 1;
  public int JJTID = 2;
  public int JJTSTRING = 3;
  public int JJTID_STRING = 4;
  public int JJTID_OR_STRING = 5;
  public int JJTPREFIX = 6;
  public int JJTPREFIX_LIST = 7;
  public int JJTOBJECT = 8;
  public int JJTIDPLUS = 9;
  public int JJTVARIABLE = 10;
  public int JJTDYN_QUESTION_MARK = 11;
  public int JJTNUMBER = 12;
  public int JJTCONSTANT = 13;
  public int JJTSIGNED_CONST = 14;
  public int JJTUNSIGNED_CONST = 15;
  public int JJTLITERAL = 16;
  public int JJTNULL_STMT = 17;
  public int JJTLENGTH_SPEC = 18;
  public int JJTDATATYPE = 19;
  public int JJTDATATYPE_INFO = 20;
  public int JJTPARAMETER = 21;
  public int JJTOPTIONAL_PARAM_DEFAULT = 22;
  public int JJTPARAM_OPTIONS = 23;
  public int JJTOUT_OPTION = 24;
  public int JJTANY_CHARS = 25;
  public int JJTCREATE_PROC_HEADER = 26;
  public int JJTCREATE_FUNC_HEADER = 27;
  public int JJTCREATE_TRIGGER_HEADER = 28;
  public int JJTCREATE_EVENT_HEADER = 29;
  public int JJTPARAMETERS = 30;
  public int JJTROUTINE_PARAMETERS = 31;
  public int JJTPROCPARMDEFAULT = 32;
  public int JJTERROR_SKIPTOBEFORE = 33;
  public int JJTERROR_SKIPTOBEFORE1 = 34;


  public String[] jjtNodeName = {
    "string_literal",
    "any_stmt_token",
    "id",
    "string",
    "id_string",
    "id_or_string",
    "prefix",
    "prefix_list",
    "object",
    "idplus",
    "variable",
    "dyn_question_mark",
    "number",
    "constant",
    "signed_const",
    "unsigned_const",
    "literal",
    "null_stmt",
    "length_spec",
    "datatype",
    "datatype_info",
    "parameter",
    "optional_param_default",
    "param_options",
    "out_option",
    "any_chars",
    "create_proc_header",
    "create_func_header",
    "create_trigger_header",
    "create_event_header",
    "parameters",
    "routine_parameters",
    "procparmdefault",
    "error_skiptobefore",
    "error_skiptobefore1",
  };
}
