/* Generated By:JJTree: Do not edit this line. C:/work/workspace/org.eclipse.datatools.enablement.sybase/src/org/eclipse/datatools/enablement/sybase/parser\QuickSQLParserTreeConstants.java */

package org.eclipse.datatools.enablement.sybase.parser;

public interface QuickSQLParserTreeConstants
{
  public int JJTSTRING_LITERAL = 0;
  public int JJTANY_STMT_TOKEN = 1;
  public int JJTID = 2;
  public int JJTSTRING = 3;
  public int JJTID_STRING = 4;
  public int JJTID_OR_STRING = 5;
  public int JJTPREFIX = 6;
  public int JJTPREFIX_LIST = 7;
  public int JJTOBJECT = 8;
  public int JJTIDPLUS = 9;
  public int JJTVARIABLE = 10;
  public int JJTDYN_QUESTION_MARK = 11;
  public int JJTNUMBER = 12;
  public int JJTCONSTANT = 13;
  public int JJTSIGNED_CONST = 14;
  public int JJTUNSIGNED_CONST = 15;
  public int JJTLITERAL = 16;
  public int JJTNULL_STMT = 17;
  public int JJTLENGTH_SPEC = 18;
  public int JJTDATATYPE = 19;
  public int JJTDATATYPE_INFO = 20;
  public int JJTPARAMETER = 21;
  public int JJTOPTIONAL_PARAM_DEFAULT = 22;
  public int JJTPARAM_OPTIONS = 23;
  public int JJTOUT_OPTION = 24;
  public int JJTANY_CHARS = 25;
  public int JJTCREATE_PROC_HEADER = 26;
  public int JJTCREATE_FUNC_HEADER = 27;
  public int JJTCREATE_TRIGGER_HEADER = 28;
  public int JJTCREATE_EVENT_HEADER = 29;
  public int JJTPARAMETERS = 30;
  public int JJTROUTINE_PARAMETERS = 31;
  public int JJTPROCPARMDEFAULT = 32;
  public int JJTERROR_SKIPTOBEFORE = 33;
  public int JJTERROR_SKIPTOBEFORE1 = 34;


  public String[] jjtNodeName = {
    "string_literal", //$NON-NLS-1$
    "any_stmt_token", //$NON-NLS-1$
    "id", //$NON-NLS-1$
    "string", //$NON-NLS-1$
    "id_string", //$NON-NLS-1$
    "id_or_string", //$NON-NLS-1$
    "prefix", //$NON-NLS-1$
    "prefix_list", //$NON-NLS-1$
    "object", //$NON-NLS-1$
    "idplus", //$NON-NLS-1$
    "variable", //$NON-NLS-1$
    "dyn_question_mark", //$NON-NLS-1$
    "number", //$NON-NLS-1$
    "constant", //$NON-NLS-1$
    "signed_const", //$NON-NLS-1$
    "unsigned_const", //$NON-NLS-1$
    "literal", //$NON-NLS-1$
    "null_stmt", //$NON-NLS-1$
    "length_spec", //$NON-NLS-1$
    "datatype", //$NON-NLS-1$
    "datatype_info", //$NON-NLS-1$
    "parameter", //$NON-NLS-1$
    "optional_param_default", //$NON-NLS-1$
    "param_options", //$NON-NLS-1$
    "out_option", //$NON-NLS-1$
    "any_chars", //$NON-NLS-1$
    "create_proc_header", //$NON-NLS-1$
    "create_func_header", //$NON-NLS-1$
    "create_trigger_header", //$NON-NLS-1$
    "create_event_header", //$NON-NLS-1$
    "parameters", //$NON-NLS-1$
    "routine_parameters", //$NON-NLS-1$
    "procparmdefault", //$NON-NLS-1$
    "error_skiptobefore", //$NON-NLS-1$
    "error_skiptobefore1", //$NON-NLS-1$
  }; 
}
