# template proposal
TemplateProposal.displayString= {0} - {1}
TemplateProposal.errorDialog.title=テンプレートの評価エラー

SQLTemplateProposal_proposalInfo=テーブル/プロシージャ名の変数を入力すると、このインテリジェントテンプレートが次の場所に展開されます :<br>

ContributionTemplateStore_ignore_no_id= テンプレート {0} は ID がないので無視されます。
ContributionTemplateStore_ignore_deleted= テンプレート {0} は削除されているので無視されます。
ContributionTemplateStore_ignore_validation_failed= テンプレート {0} は検証でエラーになったので無視されます。

SQLTemplateReaderWriter_duplicate_id= 重複するテンプレート ID
SQLTemplateReaderWriter_error_missing_attribute= 必要な属性が見つかりません。
SQLTemplateReaderWriter_error_illegal_boolean_attribute= 論理値の属性が無効です。属性は "true" と "false" のいずれかでなければなりません。
