# template proposal
TemplateProposal.displayString= {0} - {1}
TemplateProposal.errorDialog.title=Error de evaluación de plantilla

SQLTemplateProposal_proposalInfo=Después de que rellene la variable del nombre del procedimiento/tabla, esta plantilla inteligente se ampliará a:<br>

ContributionTemplateStore_ignore_no_id= La plantilla {0} se ignora porque no tiene ID.
ContributionTemplateStore_ignore_deleted= La plantilla {0} se ignora porque se ha borrado.
ContributionTemplateStore_ignore_validation_failed= La plantilla {0} se ignora porque ha fallado la validación.

SQLTemplateReaderWriter_duplicate_id= ID de plantilla duplicado
SQLTemplateReaderWriter_error_missing_attribute= Falta un atributo necesario
SQLTemplateReaderWriter_error_illegal_boolean_attribute= Atributo booleano ilegal, debe ser "verdadero" o "falso".
