# template proposal
TemplateProposal.displayString= {0} - {1}
TemplateProposal.errorDialog.title=模板求值错误

SQLTemplateProposal_proposalInfo=填写表/过程名称变量后,此智能模板将扩展为:<br>

ContributionTemplateStore_ignore_no_id= 忽略模板 {0}，因为它没有 ID。
ContributionTemplateStore_ignore_deleted= 忽略模板 {0}，因为它已被删除。
ContributionTemplateStore_ignore_validation_failed= 忽略模板 {0}，因为验证失败。

SQLTemplateReaderWriter_duplicate_id= 模板 ID 重复
SQLTemplateReaderWriter_error_missing_attribute= 缺少必需的属性
SQLTemplateReaderWriter_error_illegal_boolean_attribute= 布尔属性非法，必须为“true”或“false”。
