# template proposal
TemplateProposal_displayString= {0} - {1}
TemplateProposal_errorDialog_title=Fehler beim Auswerten der Vorlage

SQLTemplateProposal_proposalInfo=Nachdem Sie die Tabellen-/Prozedurnamenvariable eingegeben haben, wird diese intelligente Vorlage erweitert in:<br>

ContributionTemplateStore_ignore_no_id= Vorlage {0} wird ignoriert, da sie keine ID besitzt.
ContributionTemplateStore_ignore_deleted= Vorlage {0} wird ignoriert, da sie gelöscht wurde.
ContributionTemplateStore_ignore_validation_failed= Vorlage {0} wird ignoriert, da die Validierung fehlschlug.

SQLTemplateReaderWriter_duplicate_id= Doppelte Vorlagen-ID
SQLTemplateReaderWriter_error_missing_attribute= Erforderliches Attribut fehlt
SQLTemplateReaderWriter_error_illegal_boolean_attribute= Ungültiges Boolesches Attribut; muss "wahr" oder "falsch" sein.

