# template proposal
TemplateProposal_displayString= {0} - {1}
TemplateProposal_errorDialog_title=템플릿 평가 오류

SQLTemplateProposal_proposalInfo=테이블/프로시저 이름 변수를 채우면, 이 지능형 템플릿은 다음으로 확장됩니다:<br>

ContributionTemplateStore_ignore_no_id= ID가 없으므로 템플릿 {0}을(를) 무시합니다.
ContributionTemplateStore_ignore_deleted= 삭제된 것이므로 템플릿 {0}을(를) 무시합니다.
ContributionTemplateStore_ignore_validation_failed= 유효성 검사에 실패했으므로 템플릿 {0}을(를) 무시합니다.

SQLTemplateReaderWriter_duplicate_id= 중복된 템플릿 ID
SQLTemplateReaderWriter_error_missing_attribute= 필수 특성 누락
SQLTemplateReaderWriter_error_illegal_boolean_attribute= 잘못된 부울 특성, "참" 또는 "거짓"이어야 합니다.

