# template proposal
TemplateProposal_displayString= {0} - {1}
TemplateProposal_errorDialog_title=Erreur d'évaluation du modèle

SQLTemplateProposal_proposalInfo=Après avoir rempli la variable du nom de la table/procédure, ce modèle intelligent sera développé dans :<br>

ContributionTemplateStore_ignore_no_id= Ignorer le modèle {0} car il n'a pas d'id.
ContributionTemplateStore_ignore_deleted= Ignorer le modèle {0} car il est supprimé.
ContributionTemplateStore_ignore_validation_failed= Ignorer le modèle {0} car la validation a échoué.

SQLTemplateReaderWriter_duplicate_id= Dupliquer l'id du modèle
SQLTemplateReaderWriter_error_missing_attribute= Attribut requis manquant
SQLTemplateReaderWriter_error_illegal_boolean_attribute= Attribut booléen illégal, doit être "vrai" ou "faux".

