###############################################################################
# Copyright (c) 2005 Versant Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     Versant Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform MySQL Enablement Plug-in
providerName=Eclipse Data Tools Platform

driverClass = 드라이버 클래스
driverVendor = 공급업체
driverVersion = 버전
driverDBName = 데이터베이스 이름
driverConnectionURL = 연결 URL
driverUID = 사용자 ID
driverPWD = 암호

MYSQL_CATEGORY_NAME = MySQL
4_0_VERSION_CATEGORY_NAME = 4.0
4_1_VERSION_CATEGORY_NAME = 4.1
5_0_VERSION_CATEGORY_NAME = 5.0
5_1_VERSION_CATEGORY_NAME = 5.1

org.eclipse.datatools.enablement.mysql.4_0.driverTemplate = MySQL JDBC 드라이버
org.eclipse.datatools.enablement.mysql.4_1.driverTemplate = MySQL JDBC 드라이버
org.eclipse.datatools.enablement.mysql.5_0.driverTemplate = MySQL JDBC 드라이버
org.eclipse.datatools.enablement.mysql.5_1.driverTemplate = MySQL JDBC 드라이버

jdbc.connection.name = JDBC 연결
profile.mysql.title = MySQL
