###############################################################################
# Copyright (c) 2005 Versant Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Versant Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform MySQL Enablement Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Clase de controlador
driverVendor = Proveedor
driverVersion = Versión
driverDBName = Nombre de base de datos
driverConnectionURL = URL de conexión
driverUID = Identificador de usuario
driverPWD = Contraseña
driverCP = Propiedades

MYSQL_CATEGORY_NAME = MySQL
4_0_VERSION_CATEGORY_NAME = 4.0
4_1_VERSION_CATEGORY_NAME = 4.1
5_0_VERSION_CATEGORY_NAME = 5.0
5_1_VERSION_CATEGORY_NAME = 5.1

org.eclipse.datatools.enablement.mysql.4_0.driverTemplate = Controlador JDBC de MySQL
org.eclipse.datatools.enablement.mysql.4_1.driverTemplate = Controlador JDBC de MySQL
org.eclipse.datatools.enablement.mysql.5_0.driverTemplate = Controlador JDBC de MySQL
org.eclipse.datatools.enablement.mysql.5_1.driverTemplate = Controlador JDBC de MySQL

jdbc.connection.name = Conexión JDBC
profile.mysql.title = MySQL
