###############################################################################
# Copyright (c) 2005 Versant Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     Versant Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform MySQL Enablement Plug-in
providerName=Eclipse Data Tools Platform

driverClass = Treiberklasse
driverVendor = Anbieter
driverVersion = Version
driverDBName = Datenbankname
driverConnectionURL = Verbindungs-URL
driverUID = Benutzer-ID
driverPWD = Kennwort
driverCP = Eigenschaften

MYSQL_CATEGORY_NAME = MySQL
4_0_VERSION_CATEGORY_NAME = 4.0
4_1_VERSION_CATEGORY_NAME = 4.1
5_0_VERSION_CATEGORY_NAME = 5.0
5_1_VERSION_CATEGORY_NAME = 5.1

org.eclipse.datatools.enablement.mysql.4_0.driverTemplate = MySQL JDBC-Treiber
org.eclipse.datatools.enablement.mysql.4_1.driverTemplate = MySQL JDBC-Treiber
org.eclipse.datatools.enablement.mysql.5_0.driverTemplate = MySQL JDBC-Treiber
org.eclipse.datatools.enablement.mysql.5_1.driverTemplate = MySQL JDBC-Treiber

jdbc.connection.name = JDBC-Verbindung
profile.mysql.title = MySQL
