###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Eclipse Data Tools Platform DB2 UDB Database Definition Plug-in
providerName = Eclipse Data Tools Platform

V81ProductString = DB2 for Linux, UNIX, and Windows
V81VersionString = V8.1

V82ProductString = DB2 for Linux, UNIX, and Windows
V82VersionString = V8.2

V91ProductString = DB2 for Linux, UNIX, and Windows
V91VersionString = V9.1

V81Description = IBM DB2 UDB for Linux, UNIX, and Windows °æ±¾ 8.1
V82Description = IBM DB2 UDB for Linux, UNIX, and Windows °æ±¾ 8.2
V91Description = IBM DB2 UDB for Linux, UNIX, and Windows °æ±¾ 9.1
