Plugin.name = High-level Sybase Enablement Plug-in
Plugin.providerName = Eclipse Data Tools Platform

sybase.drivers.category = Sybase
sybase.drivers.category.description = Sybase 製品のドライバ
# ====================================================================
pluginName = Sybasesqlmodel Model
providerName = Eclipse Data Tools Platform
temptable.name = 一時テーブル
trigger.name = トリガ
parameter.name = パラメタ
parameters.node.name = パラメタフォルダ
storedprocedure.node.name = ストアドプロシージャフォルダ
table.node.name = テーブルフォルダ
view.node.name = ビューフォルダ
udt.node.name = ユーザ定義のデータ型フォルダ
udf.node.name = ユーザ定義の関数フォルダ
trigger.node.name = トリガフォルダ
column.node.name = 列フォルダ
index.node.name = インデックスフォルダ
checkconstraint.node.name = チェックの制約フォルダ
primarykey.node.name = プライマリキーフォルダ
uniqueconstraint.node.name = 固有の制約フォルダ
foreignkey.node.name = 外部キーフォルダ
event.node.name = イベントフォルダ
schema.node.name = スキーマフォルダ
catalog.node.name = データベースフォルダ
