Plugin.name = High-level Sybase Enablement Plug-in
Plugin.providerName = Sybase, Inc.

sybase.drivers.category = Sybase
sybase.drivers.category.description = Controladores asociados a productos Sybase
# ===================================================================

pluginName = Modelo Sybasesqlmodel
providerName = Eclipse.org
temptable.name = Tabla temporal
trigger.name = Activador
parameter.name = Parámetro
parameters.node.name = Carpeta Parámetro
storedprocedure.node.name = Carpeta Stored Procedure
table.node.name = Carpeta Tabla
view.node.name = Carpeta Ver
udt.node.name = Carpeta Tipo definido por el usuario
udf.node.name = Carpeta Función definida por el usuario
trigger.node.name = Carpeta Activador
column.node.name = Carpeta Columna
index.node.name = Carpeta Índice
checkconstraint.node.name = Carpeta Comprobar restricción
primarykey.node.name = Carpeta Clave primaria
uniqueconstraint.node.name = Carpeta Restricción exclusiva
foreignkey.node.name = Carpeta Clave externa
event.node.name = Carpeta Evento
schema.node.name = Carpeta Esquema
catalog.node.name = Carpeta Base de datos
