Plugin.name = High-level Sybase Enablement Plug-in
Plugin.providerName = Eclipse.org

sybase.drivers.category = Sybase
sybase.drivers.category.description = Sybase 제품과 연관된 드라이버입니다.
# ====================================================================
pluginName = Sybasesqlmodel Model
providerName = Eclipse.org
temptable.name = 임시 테이블
trigger.name = 트리거
parameter.name = 매개 변수
parameters.node.name = 매개 변수 폴더
storedprocedure.node.name = 저장된 프로시저 폴더
table.node.name = 테이블 폴더
view.node.name = 뷰 폴더
udt.node.name = 사용자 정의 형식 폴더
udf.node.name = 사용자 정의 함수 폴더
trigger.node.name = 트리거 폴더
column.node.name = 열 폴더
index.node.name = 인덱스 폴더
checkconstraint.node.name = CHECK 제약 조건 폴더
primarykey.node.name = 기본 키 폴더
uniqueconstraint.node.name = UNIQUE 제약 조건 폴더
foreignkey.node.name = 외래 키 폴더
event.node.name = 이벤트 폴더
schema.node.name = 스키마 폴더
catalog.node.name = 데이터베이스 폴더
