Plugin.name = High-level Sybase Enablement Plug-in
Plugin.providerName = Sybase, Inc.

sybase.drivers.category = Sybase
sybase.drivers.category.description = Treiber für Sybase-Produkte
# ===================================================================

pluginName = Sybasesqlmodel-Modell
providerName = Eclipse.org
temptable.name = Temporäre Tabelle
trigger.name = Auslöser
parameter.name = Parameter
parameters.node.name = Ordner 'Parameter'
storedprocedure.node.name = Ordner 'Gespeicherte Prozedur'
table.node.name = Ordner 'Tabelle'
view.node.name = Ordner 'Ansicht'
udt.node.name = Ordner 'Benutzerdefinierter Typ'
udf.node.name = Ordner 'Benutzerdefinierte Funktion'
trigger.node.name = Ordner 'Auslöser'
column.node.name = Ordner 'Spalte'
index.node.name = Ordner 'Index'
checkconstraint.node.name = Ordner 'Prüf-Einschränkung'
primarykey.node.name = Ordner 'Primärschlüssel'
uniqueconstraint.node.name = Ordner 'Eindeutige Einschränkung'
foreignkey.node.name = Ordner 'Fremdschlüssel'
event.node.name = Ordner 'Ereignis'
schema.node.name = Ordner 'Schema'
catalog.node.name = Ordner 'Datenbank'

