# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.title = Error al crear un nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.msg = Se ha producido una excepción al crear un nuevo perfil de conexión JDBC.

GenericDBProfileDetailsWizardPage.title = Especifique un controlador y los detalles de conexión
GenericDBProfileDetailsWizardPage.msg = Seleccione un controlador del menú desplegable y proporcione los detalles de conexión.
GenericDBProfileDetailsWizardPage.driverCombo.label = Controladores:
GenericDBProfileDetailsWizardPage.databaseName.label = Base de datos:
GenericDBProfileDetailsWizardPage.url.label = URL:
GenericDBProfileDetailsWizardPage.PingButton=Probar conexión
GenericDBProfileDetailsWizardPage.userName.label = Nombre de usuario:
GenericDBProfileDetailsWizardPage.password.label = Contraseña:
GenericDBProfileDetailsWizardPage.persistpassword.label = Guardar contraseña
GenericDBProfileDetailsWizardPage.optionalProps.label = Propiedades opcionales:
GenericDBProfileDetailsWizardPage.summary.driverName.label = Nombre de controlador
GenericDBProfileDetailsWizardPage.summary.connProps.label = Propiedades de conexión
GenericDBProfileDetailsWizardPage.summary.userName.label = Nombre de usuario
GenericDBProfileDetailsWizardPage.summary.password.label = Contraseña
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milésimas (s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Límite de tiempo de conexión en 
JDBCConnectionUtils.AttemptToConnectMessage=Intentando conectarse...
JDBCConnectionUtils.DBConnectAttemptJob=Intento de conexión a la base de datos
JDBCConnectionUtils.ClassNotFoundStatus=No se ha podido cargar la clase: 
JDBCConnectionUtils.ConnectionTimeoutMessage=Se ha alcanzado el límite de tiempo de la conexión.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = El controlador no existe.
JDBCConnection.error.EmptyJarList = Lista jar vacía en la definición de controlador.
