# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Neues JDBC-Verbindungsprofil
NewConnectionProfileWizard.error.title = Fehler bei der Erstellung eines neuen JDBC-Verbindungsprofils
NewConnectionProfileWizard.error.msg = Ein Ausnahmefehler ist bei der Erstellung eines neuen JDBC-Profils aufgetreten.

GenericDBProfileDetailsWizardPage.title = Treiber- und Verbindungsdetails angeben
GenericDBProfileDetailsWizardPage.msg = Wählen Sie einen Treiber aus der Dropdown-Liste, und geben Sie Anmeldedetails für die Verbindung an.
GenericDBProfileDetailsWizardPage.driverCombo.label = Treiber:
GenericDBProfileDetailsWizardPage.databaseName.label = Datenbank:
GenericDBProfileDetailsWizardPage.url.label = URL:
GenericDBProfileDetailsWizardPage.PingButton=Testverbindung
GenericDBProfileDetailsWizardPage.userName.label = Benutzername:
GenericDBProfileDetailsWizardPage.password.label = Kennwort:
GenericDBProfileDetailsWizardPage.persistpassword.label = Kennwort speichern
GenericDBProfileDetailsWizardPage.optionalProps.label = Optionale Eigenschaften:
GenericDBProfileDetailsWizardPage.summary.driverName.label = Treibername
GenericDBProfileDetailsWizardPage.summary.connProps.label = Verbindungseigenschaften
GenericDBProfileDetailsWizardPage.summary.userName.label = Benutzername
GenericDBProfileDetailsWizardPage.summary.password.label = Kennwort
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Login Zeitüberschreitung in 
JDBCConnectionUtils.AttemptToConnectMessage=Verbindungsversuch...
JDBCConnectionUtils.DBConnectAttemptJob=Datenbank Verbindungsversuch
JDBCConnectionUtils.ClassNotFoundStatus=Klasse konnte nicht geladen werden: 
JDBCConnectionUtils.ConnectionTimeoutMessage=Zeitüberschreitung der Verbindung.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = Der Treiber existiert nicht.
JDBCConnection.error.EmptyJarList = Die JAR-Liste in der Treiberdefinition ist leer.
