# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 새 JDBC 연결 프로필
NewConnectionProfileWizard.error.title = 새 JDBC 연결 프로필 생성 중 오류 발생
NewConnectionProfileWizard.error.msg = 새 JDBC 연결 프로필을 생성하는 중 예외가 발생했습니다.

GenericDBProfileDetailsWizardPage.title = 드라이버 및 연결 상세 정보 지정
GenericDBProfileDetailsWizardPage.msg = 드롭다운에서 드라이버를 선택하고 연결 로그인 정보를 제공합니다.
GenericDBProfileDetailsWizardPage.driverCombo.label = 드라이버:
GenericDBProfileDetailsWizardPage.databaseName.label = 데이터베이스:
GenericDBProfileDetailsWizardPage.url.label = URL:
GenericDBProfileDetailsWizardPage.PingButton=연결 테스트
GenericDBProfileDetailsWizardPage.userName.label = 사용자 이름:
GenericDBProfileDetailsWizardPage.password.label = 암호:
GenericDBProfileDetailsWizardPage.persistpassword.label = 암호 저장
GenericDBProfileDetailsWizardPage.optionalProps.label = 옵션 속성:
GenericDBProfileDetailsWizardPage.summary.driverName.label = 드라이버 이름
GenericDBProfileDetailsWizardPage.summary.connProps.label = 연결 속성
GenericDBProfileDetailsWizardPage.summary.userName.label = 사용자 이름:
GenericDBProfileDetailsWizardPage.summary.password.label = 암호
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=로그인 제한 시간 
JDBCConnectionUtils.AttemptToConnectMessage=연결을 시도하는 중...
JDBCConnectionUtils.DBConnectAttemptJob=데이터베이스 연결 시도
JDBCConnectionUtils.ClassNotFoundStatus=클래스를 로드할 수 없습니다. 
JDBCConnectionUtils.ConnectionTimeoutMessage=연결 제한 시간을 초과했습니다.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = 드라이버가 없습니다.
JDBCConnection.error.EmptyJarList = 드라이버 정의에서 jar 목록이 비어 있습니다.
