# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 新建 JDBC 连接配置文件
NewConnectionProfileWizard.error.title = 创建新的 JDBC 连接配置文件时出错
NewConnectionProfileWizard.error.msg = 创建新的 JDBC 连接配置文件时发生了异常。

GenericDBProfileDetailsWizardPage.title = 指定驱动程序和连接详细信息
GenericDBProfileDetailsWizardPage.msg = 从下拉列表中选择驱动程序并提供连接的登录详细信息。
GenericDBProfileDetailsWizardPage.driverCombo.label = 驱动程序:
GenericDBProfileDetailsWizardPage.databaseName.label = 数据库:
GenericDBProfileDetailsWizardPage.url.label = URL:
GenericDBProfileDetailsWizardPage.PingButton=测试连接
GenericDBProfileDetailsWizardPage.userName.label = 用户名:
GenericDBProfileDetailsWizardPage.password.label = 密码:
GenericDBProfileDetailsWizardPage.persistpassword.label = 保存密码
GenericDBProfileDetailsWizardPage.optionalProps.label = 可选属性:
GenericDBProfileDetailsWizardPage.summary.driverName.label = 驱动程序名称
GenericDBProfileDetailsWizardPage.summary.connProps.label = 连接属性
GenericDBProfileDetailsWizardPage.summary.userName.label = 用户名
GenericDBProfileDetailsWizardPage.summary.password.label = 密码
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ ms
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=登录超时 
JDBCConnectionUtils.AttemptToConnectMessage=正在尝试连接...
JDBCConnectionUtils.DBConnectAttemptJob=数据库连接尝试
JDBCConnectionUtils.ClassNotFoundStatus=无法加载类: 
JDBCConnectionUtils.ConnectionTimeoutMessage=连接已超时。

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = 驱动程序不存在。
JDBCConnection.error.EmptyJarList = 驱动程序定义中的空 jar 列表。
