# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 新しい JDBC 接続プロファイル
NewConnectionProfileWizard.error.title = JDBC 接続プロファイルの新規作成エラー
NewConnectionProfileWizard.error.msg = JDBC 接続プロファイルの新規作成中に例外が発生しました。

GenericDBProfileDetailsWizardPage.title = ドライバと接続の詳細を指定
GenericDBProfileDetailsWizardPage.msg = ドロップダウンリストからドライバを選択し、接続用のログイン情報を指定してください。
GenericDBProfileDetailsWizardPage.driverCombo.label = ドライバ :
GenericDBProfileDetailsWizardPage.databaseName.label = データベース :
GenericDBProfileDetailsWizardPage.url.label = URL :
GenericDBProfileDetailsWizardPage.PingButton=接続テスト
GenericDBProfileDetailsWizardPage.userName.label = ユーザ名 :
GenericDBProfileDetailsWizardPage.password.label = パスワード :
GenericDBProfileDetailsWizardPage.persistpassword.label = パスワードの保存
GenericDBProfileDetailsWizardPage.optionalProps.label = オプションプロパティ :
GenericDBProfileDetailsWizardPage.summary.driverName.label = ドライバ名
GenericDBProfileDetailsWizardPage.summary.connProps.label = 接続プロパティ
GenericDBProfileDetailsWizardPage.summary.userName.label = ユーザ名
GenericDBProfileDetailsWizardPage.summary.password.label = パスワード
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ ミリ秒
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=ログインのタイムアウトまであと 
JDBCConnectionUtils.AttemptToConnectMessage=接続中...
JDBCConnectionUtils.DBConnectAttemptJob=データベースへの接続を試行
JDBCConnectionUtils.ClassNotFoundStatus=クラスを読み込めません : 
JDBCConnectionUtils.ConnectionTimeoutMessage=接続がタイムアウトしました。

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = ドライバがありません。
JDBCConnection.error.EmptyJarList = ドライバ定義の jar リストが空です。
