# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.title = Erreur lors de la création d'un nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.msg = Une exception s'est produite lors de la création d'un nouveau profil de connexion JDBC.

GenericDBProfileDetailsWizardPage.title = Spécifier un pilote et les informations de connexion
GenericDBProfileDetailsWizardPage.msg = Dans le menu déroulant, sélectionner un pilote et lui fournir les informations de connexion.
GenericDBProfileDetailsWizardPage.driverCombo.label = Pilotes :
GenericDBProfileDetailsWizardPage.databaseName.label = Base de données :
GenericDBProfileDetailsWizardPage.url.label = URL :
GenericDBProfileDetailsWizardPage.PingButton=Connexion test
GenericDBProfileDetailsWizardPage.userName.label = Nom d'utilisateur :
GenericDBProfileDetailsWizardPage.password.label = Mot de passe :
GenericDBProfileDetailsWizardPage.persistpassword.label = Enregistrer le mot de passe
GenericDBProfileDetailsWizardPage.optionalProps.label = Propriétés facultatives :
GenericDBProfileDetailsWizardPage.summary.driverName.label = Nom du pilote
GenericDBProfileDetailsWizardPage.summary.connProps.label = Propriétés de connexion
GenericDBProfileDetailsWizardPage.summary.userName.label = Nom d'utilisateur
GenericDBProfileDetailsWizardPage.summary.password.label = Mot de passe
GenericDBProfileDetailsWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Délai de connexion 
JDBCConnectionUtils.AttemptToConnectMessage=Tentative de connexion...
JDBCConnectionUtils.DBConnectAttemptJob=Tentative de connexion à la base de données
JDBCConnectionUtils.ClassNotFoundStatus=Impossible de charger la classe : 
JDBCConnectionUtils.ConnectionTimeoutMessage=Délai de connexion dépassé.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = Le pilote n'existe pas.
JDBCConnection.error.EmptyJarList = Liste jar vide dans la définition de pilote.
