###############################################################################
# Copyright (c) 2001, 2004 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Sybase ASE Database Definition
providerName=Eclipse.org

12.xProductString = Sybase ASE(Adaptive Server Enterprise)
12.xVersionString = 12.x
15.xProductString = Sybase ASE(Adaptive Server Enterprise)
15.xVersionString = 15.x
