###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Assistant Nouveau modèle de plug-in ODA DTP
template.runtimeDriver.name=Pilote d'exécution de source de données ODA
template.runtimeDriver.desc=\
Cet assistant crée un plug-in pour un pilote d'exécution de source de données ODA.\
<p>Un plug-in de pilote d'exécution ODA n'apporte <b>aucune</b> contribution à l'interface utilisateur. \
Ne sélectionnez pas la case à cocher relative à la contribution de l'interface dans les options Plug-in de la page précédente.</p>\
<p><b>Extension utilisée</b></p>\
<li>org.eclipse.datatools.connectivity.oda.dataSource</li>
template.designer.name=Concepteur de source de données ODA
template.designer.desc=\
Cet assistant crée un plug-in pour le concepteur de source de données ODA. \
<p>Avant d'utiliser cet assistant pour créer le plug-in de conception ODA, utilisez d'abord \
le modèle de <b>pilote d'exécution de source de données ODA</b> pour créer le plug-in d'exécution \
correspondant.</p>\
<p><b>Extensions utilisées</b></p>\
<li>org.eclipse.datatools.connectivity.oda.design.ui.dataSource</li>\
<li>org.eclipse.datatools.connectivity.connectionProfile</li>\
<li>org.eclipse.ui.propertyPages</li>

