###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=DTP ODA 新建插件模板向导
template.runtimeDriver.name=ODA 数据源运行时驱动程序
template.runtimeDriver.desc=\
此向导为开放数据访问 (ODA) 数据源运行时驱动程序创建一个插件。\
<p>ODA 运行时驱动程序插件<b>不</b>影响 UI。\
不要选择上一页的插件选项下的 UI 影响复选框。</p>\
<p><b>使用扩展</b></p>\
<li>org.eclipse.datatools.connectivity.oda.dataSource</li>
template.designer.name=ODA 数据源设计器
template.designer.desc=\
此向导为开放数据访问 (ODA) 数据源设计器创建一个插件。\
<p>在使用此向导创建 ODA 设计器插件，首先使用\
 <b>ODA 数据源运行时驱动程序</b>模板来创建其相应的\
运行时插件。</p>\
<p><b>使用扩展</b></p>\
<li>org.eclipse.datatools.connectivity.oda.design.ui.dataSource</li>\
<li>org.eclipse.datatools.connectivity.connectionProfile</li>\
<li>org.eclipse.ui.propertyPages</li>

