###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=DTP-ODA-Assistent für neue Plug-In-Vorlage
template.runtimeDriver.name=ODA-Datenquellen-Laufzeittreiber
template.runtimeDriver.desc=\
Mit diesem Assistenten wird ein Plug-In für einen Open Data Acces (ODA)-Datenquellen-Laufzeittreiber erstellt.\
<p>Ein ODA-Laufzeittreiber-Plug-In leistet <b>keinen</b> Beitrag zur UI. \
Aktivieren Sie auf der vorherigen Seite unter den Plug-In-Optionen nicht das Kontrollkästchen für UI-Beitrag.</p>\
<p><b>Verwendete Erweiterung</b></p>\
<li>org.eclipse.datatools.connectivity.oda.dataSource</li>
template.designer.name=ODA-Datenquellen-Designer
template.designer.desc=\
Mit diesem Assistenten wird ein Plug-In für einen Open Data Access (ODA)-Datenquellen-Designer erstellt. \
<p>Bevor Sie ihn für die Erstellung des ODA-Designer-Plug-In verwenden, sollten Sie zuerst \
die Vorlage für den <b>ODA-Datenquellen-Laufzeittreiber</b>verwenden, um das entsprechende \
Laufzeit-Plug-In zu erstellen.</p>\
<p><b>Verwendete Erweiterungen</b></p>\
<li>org.eclipse.datatools.connectivity.oda.design.ui.dataSource</li>\
<li>org.eclipse.datatools.connectivity.connectionProfile</li>\
<li>org.eclipse.ui.propertyPages</li>

