###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=DTP ODA 새 플러그인 템플릿 마법사
template.runtimeDriver.name=ODA 데이터 원본 런타임 드라이버
template.runtimeDriver.desc=\
이 마법사는 개방형 데이터 액세스(ODA) 데이터 원본 런타임 드라이버용 플러그인을 생성합니다.\
<p>ODA 런타임 드라이버 플러그인은 UI에 기여하지 <b>않습니다.</b> \
이전 페이지의 플러그인 옵션 내 UI 기여 확인란을 선택하지 않습니다.</p>\
<p><b>사용된 확장명</b></p>\
<li>org.eclipse.datatools.connectivity.oda.dataSource</li>
template.designer.name=ODA 데이터 원본 디자이너
template.designer.desc=\
이 마법사는 개방형 데이터 액세스(ODA) 데이터 원본 드라이버용 플러그인을 생성합니다. \
<p>ODA 디자이너 플러그인을 생성하기 전에 \
해당 런타임 플러그인을 생성하는 <b>ODA 데이터 원본 런타임 드라이버</b>템플릿을\
 먼저 사용합니다.</p>\
<p><b>사용된 확장명</b></p>\
<li>org.eclipse.datatools.connectivity.oda.design.ui.dataSource</li>\
<li>org.eclipse.datatools.connectivity.connectionProfile</li>\
<li>org.eclipse.ui.propertyPages</li>

