###############################################################################
# Copyright (c) 2006 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# NLS String
###############################################################################
#
plugin.name=Asistente de nuevas plantillas de complemento DTP ODA
template.runtimeDriver.name=Controlador de tiempo de ejecución de fuente de datos ODA
template.runtimeDriver.desc=\
Este asistente crea un complemento para un controlador de tiempo de ejecución de fuente de datos de acceso a datos abiertos (ODA).\
<p>Un complemento de controlador de tiempo de ejecución ODA <b>no</b> contribuye a la IU. \
No seleccione la casilla de verificación de contribución a IU situada debajo de Opciones de complemento en la página anterior.</p>\
<p><b>Extensión utilizada</b></p>\
<li>org.eclipse.datatools.connectivity.oda.dataSource</li>
template.designer.name=Diseñador de fuente de datos ODA
template.designer.desc=\
Este asistente crea un complemento para un diseñador de fuente de datos de acceso a datos abiertos (ODA). \
<p>Antes de usarlo para crear el complemento de diseñador ODA, utilice \
la plantilla de <b>Controlador de tiempo de ejecución de fuente de datos ODA</b> para crear el complemento de 
tiempo de ejecución correspondiente.</p>\
<p><b>Extensiones utilizadas</b></p>\
<li>org.eclipse.datatools.connectivity.oda.design.ui.dataSource</li>\
<li>org.eclipse.datatools.connectivity.connectionProfile</li>\
<li>org.eclipse.ui.propertyPages</li>

