###############################################################################
# Copyright (c) 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

#
## Informix Driver UI Contributor
#
CUI_NEWCW_DATABASE_LBL_UI_ = Base de &données :
CUI_NEWCW_HOST_LBL_UI_ = &Hôte :
CUI_NEWCW_PORT_LBL_UI_ = Nu&méro de port :
CUI_NEWCW_CONNECTIONURL_LBL_UI_= UR&L de connexion :
CUI_NEWCW_SERVER_LBL_UI_ = &Serveur :
CUI_NEWCW_USERNAME_LBL_UI_ = Nom d'utilis&ateur :
CUI_NEWCW_PASSWORD_LBL_UI_ = &Mot de passe :
CUI_NEWCW_SAVE_PASSWORD_LBL_UI_ = Enregistre&r le mot de passe
CUI_NEWCW_DATABASE_SUMMARY_DATA_TEXT_ = Base de données
CUI_NEWCW_HOST_SUMMARY_DATA_TEXT_ = Hôte
CUI_NEWCW_PORT_SUMMARY_DATA_TEXT_ = Numéro de port
CUI_NEWCW_USE_SERVER_SUMMARY_DATA_TEXT_ = Serveur
CUI_NEWCW_USERNAME_SUMMARY_DATA_TEXT_ = Nom d'utilisateur
CUI_NEWCW_SAVE_PASSWORD_SUMMARY_DATA_TEXT_ = Enregistrer le mot de passe
CUI_NEWCW_DEFAULT_SCHEMA_LBL_UI_ = Schéma par défaut :
CUI_NEWCW_DEFAULT_SCHEMA_SUMMARY_DATA_TEXT_ = Schéma par défaut
CUI_NEWCW_TRUE_SUMMARY_DATA_TEXT_ = vrai
CUI_NEWCW_FALSE_SUMMARY_DATA_TEXT_ = faux
CUI_NEWCW_URL_SUMMARY_DATA_TEXT_ = URL

CUI_NEWCW_VALIDATE_DATABASE_REQ_UI_ = Entrer un nom pour la base de données.
CUI_NEWCW_VALIDATE_HOST_REQ_UI_= Entrer le nom d'hôte pour le serveur de la base de données.
CUI_NEWCW_VALIDATE_PORT_REQ_UI_ = Entrer le numéro de port de connexion pour le serveur de la base de données.
CUI_NEWCW_VALIDATE_SERVER_REQ_UI_= Entrer un nom de serveur.
CUI_NEWCW_VALIDATE_USERID_REQ_UI_ = Entrer un nom d'utilisateur.
CUI_NEWCW_VALIDATE_PASSWORD_REQ_UI_ = Entrer un mot de passe.






CUI_NEWCW_SERVER_SUMMARY_DATA_TEXT_=
