####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = Präzision muss größer als Null sein.
SQLParser_datatype_judgeLengthAndScale = Sie müssen eine Skalierung angeben, die gleich der Größe oder kleiner als diese ist
SQLParser_datatype_exceed_maxlength = Die maximal zulässige Länge der Zeichenfolge in Byte ist 32767.

plugin_internal_error=Interner Fehler.
