####################################################
#  SQL ParserExpection Message
####################################################
SQLParser_datatype_judgeLength = Precisión debe ser mayor que cero
SQLParser_datatype_judgeLengthAndScale = Debe especificar una escala que sea menor o igual que el tamaño
SQLParser_datatype_exceed_maxlength = La longitud máxima en bytes del string permitida es de 32767.

plugin_internal_error=Error interno
