NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=HSQLDB Datenbank

HSQLDBProfileDetailsWizardPage.title = Treiber- und Verbindungsdetails angeben
HSQLDBProfileDetailsWizardPage.msg = Wählen Sie einen Treiber aus der Dropdown-Liste, und geben Sie Anmeldedetails für die Verbindung an.
HSQLDBProfileDetailsWizardPage.0=Speicherort:
HSQLDBProfileDetailsWizardPage.1=Durchsuchen...
HSQLDBProfileDetailsWizardPage.2=Datenbank erstellen (falls erforderlich)
HSQLDBProfileDetailsWizardPage.3=Upgrade der Datenbank auf die aktuelle Version
HSQLDBProfileDetailsWizardPage.driverCombo.label = Wählen Sie einen Treiber aus der Dropdown-Liste aus:
HSQLDBProfileDetailsWizardPage.databaseName.label = Datenbank:
HSQLDBProfileDetailsWizardPage.url.label = URL:
HSQLDBProfileDetailsWizardPage.PingButton=Testverbindung
HSQLDBProfileDetailsWizardPage.userName.label = Benutzername:
HSQLDBProfileDetailsWizardPage.password.label = Kennwort:
HSQLDBProfileDetailsWizardPage.persistpassword.label = Kennwort speichern
HSQLDBProfileDetailsWizardPage.optionalProps.label = Optionale Eigenschaften:
HSQLDBProfileDetailsWizardPage.summary.driverName.label = Treibername
HSQLDBProfileDetailsWizardPage.summary.connProps.label = Verbindungseigenschaften
HSQLDBProfileDetailsWizardPage.summary.userName.label = Benutzername
HSQLDBProfileDetailsWizardPage.summary.password.label = Kennwort
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = Datenbank
HSQLDBProfileDetailsWizardPage.summary.true = Wahr
HSQLDBProfileDetailsWizardPage.summary.false = Falsch
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = Datenbankpfad:
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = Kennwort speichern
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = Suchen des Datenbankordners
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = Wählen Sie den Ordner, der Ihrer HSQLDB-Datenbank entspricht.
HSQLDBProfileDetailsWizardPage.general.tab = Allgemein
HSQLDBProfileDetailsWizardPage.optional.tab = Optional
HSQLDBProfileDetailsWizardPage.database.validation.message = Geben Sie einen Datenbanknamen ein.
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = Geben Sie den Pfad der Datenbank ein.



