NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=Base de datos HSQLDB

HSQLDBProfileDetailsWizardPage.title = Especifique un controlador y los detalles de conexión
HSQLDBProfileDetailsWizardPage.msg = Seleccione un controlador del menú desplegable y proporcione los detalles de conexión.
HSQLDBProfileDetailsWizardPage.0=Ubicación de la base de datos:
HSQLDBProfileDetailsWizardPage.1=Examinar...
HSQLDBProfileDetailsWizardPage.2=Crear base de datos (en caso necesario)
HSQLDBProfileDetailsWizardPage.3=Actualizar base de datos a la versión actual
HSQLDBProfileDetailsWizardPage.driverCombo.label = Seleccione un controlador del menú desplegable:
HSQLDBProfileDetailsWizardPage.databaseName.label = Base de datos:
HSQLDBProfileDetailsWizardPage.url.label = URL:
HSQLDBProfileDetailsWizardPage.PingButton=Probar conexión
HSQLDBProfileDetailsWizardPage.userName.label = Nombre de usuario:
HSQLDBProfileDetailsWizardPage.password.label = Contraseña:
HSQLDBProfileDetailsWizardPage.persistpassword.label = Guardar contraseña
HSQLDBProfileDetailsWizardPage.optionalProps.label = Propiedades opcionales:
HSQLDBProfileDetailsWizardPage.summary.driverName.label = Nombre de controlador
HSQLDBProfileDetailsWizardPage.summary.connProps.label = Propiedades de conexión
HSQLDBProfileDetailsWizardPage.summary.userName.label = Nombre de usuario
HSQLDBProfileDetailsWizardPage.summary.password.label = Contraseña
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = Base de datos
HSQLDBProfileDetailsWizardPage.summary.true = true
HSQLDBProfileDetailsWizardPage.summary.false = false
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = Ubicación de la base de datos
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = Guardar contraseña
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = Buscar carpeta de base de datos
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = Seleccionar la carpeta que corresponde a su base de datos HSQLDB.
HSQLDBProfileDetailsWizardPage.general.tab = General
HSQLDBProfileDetailsWizardPage.optional.tab = Opcional
HSQLDBProfileDetailsWizardPage.database.validation.message = Introduzca un nombre de base de datos.
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = Introduzca una ubicación de base de datos.


