NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=HSQLDB 데이터베이스

HSQLDBProfileDetailsWizardPage.title = 드라이버 및 연결 상세 정보 지정
HSQLDBProfileDetailsWizardPage.msg = 드롭다운에서 드라이버를 선택하고 연결 로그인 정보를 제공합니다.
HSQLDBProfileDetailsWizardPage.0=데이터베이스 위치:
HSQLDBProfileDetailsWizardPage.1=찾아보기...
HSQLDBProfileDetailsWizardPage.2=데이터베이스 생성(필요 시)
HSQLDBProfileDetailsWizardPage.3=현재 버전으로 데이터베이스 업그레이드
HSQLDBProfileDetailsWizardPage.driverCombo.label = 드롭다운에서 드라이버를 선택하십시오.
HSQLDBProfileDetailsWizardPage.databaseName.label = 데이터베이스:
HSQLDBProfileDetailsWizardPage.url.label = URL:
HSQLDBProfileDetailsWizardPage.PingButton=연결 테스트
HSQLDBProfileDetailsWizardPage.userName.label = 사용자 이름:
HSQLDBProfileDetailsWizardPage.password.label = 암호:
HSQLDBProfileDetailsWizardPage.persistpassword.label = 암호 저장
HSQLDBProfileDetailsWizardPage.optionalProps.label = 옵션 속성:
HSQLDBProfileDetailsWizardPage.summary.driverName.label = 드라이버 이름
HSQLDBProfileDetailsWizardPage.summary.connProps.label = 연결 속성
HSQLDBProfileDetailsWizardPage.summary.userName.label = 사용자 이름:
HSQLDBProfileDetailsWizardPage.summary.password.label = 암호
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = 데이터베이스
HSQLDBProfileDetailsWizardPage.summary.true = 참
HSQLDBProfileDetailsWizardPage.summary.false = 거짓
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = 데이터베이스 위치
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = 암호 저장
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = 데이터베이스 폴더 찾아보기
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = HSQLDB 데이터베이스와 일치하는 폴더를 선택하십시오.
HSQLDBProfileDetailsWizardPage.general.tab = 일반
HSQLDBProfileDetailsWizardPage.optional.tab = 옵션
HSQLDBProfileDetailsWizardPage.database.validation.message = 데이터베이스 이름을 입력하십시오.
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = 데이터베이스 위치를 입력하십시오.



