NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=Base de données HSQLDB

HSQLDBProfileDetailsWizardPage.title = Spécifier un pilote et les informations de connexion
HSQLDBProfileDetailsWizardPage.msg = Dans le menu déroulant, sélectionner un pilote et lui fournir les informations de connexion.
HSQLDBProfileDetailsWizardPage.0=Emplacement de la base de données :
HSQLDBProfileDetailsWizardPage.1=Parcourir...
HSQLDBProfileDetailsWizardPage.2=Créer une base de données (si besoin)
HSQLDBProfileDetailsWizardPage.3=Mettre à niveau la base de données à la version actuelle
HSQLDBProfileDetailsWizardPage.driverCombo.label = Sélectionner un pilote dans le menu déroulant :
HSQLDBProfileDetailsWizardPage.databaseName.label = Base de données :
HSQLDBProfileDetailsWizardPage.url.label = URL :
HSQLDBProfileDetailsWizardPage.PingButton=Connexion test
HSQLDBProfileDetailsWizardPage.userName.label = Nom d'utilisateur :
HSQLDBProfileDetailsWizardPage.password.label = Mot de passe :
HSQLDBProfileDetailsWizardPage.persistpassword.label = Enregistrer mot de passe
HSQLDBProfileDetailsWizardPage.optionalProps.label = Propriétés facultatives :
HSQLDBProfileDetailsWizardPage.summary.driverName.label = Nom du pilote
HSQLDBProfileDetailsWizardPage.summary.connProps.label = Propriétés de connexion
HSQLDBProfileDetailsWizardPage.summary.userName.label = Nom d'utilisateur
HSQLDBProfileDetailsWizardPage.summary.password.label = Mot de passe
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = Base de données
HSQLDBProfileDetailsWizardPage.summary.true = vrai
HSQLDBProfileDetailsWizardPage.summary.false = faux
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = Emplacement de la base de données
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = Enregistrer le mot de passe
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = Rechercher le dossier de la base de données
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = Sélectionner le dossier correspondant à votre base de données HSQLDB.
HSQLDBProfileDetailsWizardPage.general.tab = Général
HSQLDBProfileDetailsWizardPage.optional.tab = Facultatif
HSQLDBProfileDetailsWizardPage.database.validation.message = Entrer un nom pour la base de données.
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = Entrer un emplacement pour la base de données.



