NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=HSQLDB データベース

HSQLDBProfileDetailsWizardPage.title = ドライバと接続の詳細を指定
HSQLDBProfileDetailsWizardPage.msg = ドロップダウンリストからドライバを選択し、接続用のログイン情報を指定してください。
HSQLDBProfileDetailsWizardPage.0=データベースの場所 :
HSQLDBProfileDetailsWizardPage.1=参照...
HSQLDBProfileDetailsWizardPage.2=データベースを作成する (必要な場合)
HSQLDBProfileDetailsWizardPage.3=データベースを現在のバージョンに更新する
HSQLDBProfileDetailsWizardPage.driverCombo.label = ドロップダウンからドライバを選択 :
HSQLDBProfileDetailsWizardPage.databaseName.label = データベース :
HSQLDBProfileDetailsWizardPage.url.label = URL :
HSQLDBProfileDetailsWizardPage.PingButton=接続テスト
HSQLDBProfileDetailsWizardPage.userName.label = ユーザ名 :
HSQLDBProfileDetailsWizardPage.password.label = パスワード :
HSQLDBProfileDetailsWizardPage.persistpassword.label = パスワードの保存
HSQLDBProfileDetailsWizardPage.optionalProps.label = オプションプロパティ :
HSQLDBProfileDetailsWizardPage.summary.driverName.label = ドライバ名
HSQLDBProfileDetailsWizardPage.summary.connProps.label = 接続プロパティ
HSQLDBProfileDetailsWizardPage.summary.userName.label = ユーザ名
HSQLDBProfileDetailsWizardPage.summary.password.label = パスワード
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = データベース
HSQLDBProfileDetailsWizardPage.summary.true = true
HSQLDBProfileDetailsWizardPage.summary.false = false
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = データベースの場所
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = パスワードの保存
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = データベースフォルダを参照
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = HSQLDB データベースに対応するフォルダを選択してください。
HSQLDBProfileDetailsWizardPage.general.tab = 全般
HSQLDBProfileDetailsWizardPage.optional.tab = オプション
HSQLDBProfileDetailsWizardPage.database.validation.message = データベース名を入力してください。
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = データベースの場所を入力してください。



