NewHSQLDBConnectionProfileWizard.HSQLDBWizardTitle=HSQLDB 数据库

HSQLDBProfileDetailsWizardPage.title = 指定驱动程序和连接详细信息
HSQLDBProfileDetailsWizardPage.msg = 从下拉列表中选择驱动程序并提供连接的登录详细信息。
HSQLDBProfileDetailsWizardPage.0=数据库位置:
HSQLDBProfileDetailsWizardPage.1=浏览...
HSQLDBProfileDetailsWizardPage.2=创建数据库（如果必要）
HSQLDBProfileDetailsWizardPage.3=将数据库升级至当前版本
HSQLDBProfileDetailsWizardPage.driverCombo.label = 从下拉列表中选择驱动程序:
HSQLDBProfileDetailsWizardPage.databaseName.label = 数据库:
HSQLDBProfileDetailsWizardPage.url.label = URL:
HSQLDBProfileDetailsWizardPage.PingButton=测试连接
HSQLDBProfileDetailsWizardPage.userName.label = 用户名:
HSQLDBProfileDetailsWizardPage.password.label = 密码:
HSQLDBProfileDetailsWizardPage.persistpassword.label = 保存密码
HSQLDBProfileDetailsWizardPage.optionalProps.label = 可选属性:
HSQLDBProfileDetailsWizardPage.summary.driverName.label = 驱动程序名称
HSQLDBProfileDetailsWizardPage.summary.connProps.label = 连接属性
HSQLDBProfileDetailsWizardPage.summary.userName.label = 用户名
HSQLDBProfileDetailsWizardPage.summary.password.label = 密码
HSQLDBProfileDetailsWizardPage.summary.url.label = URL
HSQLDBProfileDetailsWizardPage.summary.database.label = 数据库
HSQLDBProfileDetailsWizardPage.summary.true = true
HSQLDBProfileDetailsWizardPage.summary.false = false
HSQLDBProfileDetailsWizardPage.summary.databaselocation.label = 数据库位置:
HSQLDBProfileDetailsWizardPage.summary.persistpassword.label = 保存密码
HSQLDBProfileDetailsWizardPage.FileDialog.title.filebrowse = 浏览数据库文件夹
HSQLDBProfileDetailsWizardPage.FileDialog.msg.filebrowse = 选择对应于 HSQLDB 数据库的文件夹。
HSQLDBProfileDetailsWizardPage.general.tab = 常规
HSQLDBProfileDetailsWizardPage.optional.tab = 可选
HSQLDBProfileDetailsWizardPage.database.validation.message = 输入数据库名称。
HSQLDBProfileDetailsWizardPage.databaselocation.validation.message = 输入数据库位置。


