common_error=エラー

CutAction_label= 切り取り(&T)
CutAction_tooltip= 選択した内容を切り取ってクリップボードに入れる

CopyAction_label= コピー(&C)
CopyAction_tooltip= 選択した内容をクリップボードにコピーする

CopyToClipboard_error_title= クリップボードへのコピーエラー
CollectionUtil_invalid_size=サイズが無効です。
CopyToClipboard_error_message= システムのクリップボードへのアクセスエラーが発生しました。やり直しますか ?

DeleteAction_label=削除(&D)
DeleteAction_0=ノードの削除中にエラーが発生しました :
DeleteAction_tooltip=選択した要素を削除する
DeleteAction_confirm_title=削除の確認
DeleteAction_confirm_message=削除しますか ?

DeployAction_label=サーバに保存(&S)
DeployAction_error_title=保存エラー
DeployAction_error_message=サーバに保存できません。
DeployAction_save_information=情報
DeployAction_save_message=オブジェクト "{0}" は正しくサーバに保存されました。

PasteAction_label=貼り付け(&P)
PasteAction_1=貼り付け中にエラーが発生しました :
PasteAction_tooltip=クリップボードの内容を貼り付ける

ExecuteSQLAction_label=すべて実行(&E)
ExecuteSQLAction_tooltip=すべての SQL 文を実行する

ExecuteSelectionSQLAction_label=選択した文の実行(&X)
ExecuteSelectionSQLAction_tooltip=選択した SQL 文を実行する

DMLDialogSelectionSQLAction_label=SQL クエリビルダで編集(&Q)...
DMLDialogSelectionSQLAction_tooltip=選択した SQL 文を SQL クエリビルダで編集する

GotoMatchingTokenAction_label=Goto &Matching Token
GotoMatchingTokenAction_tooltip=Matching Current Token

RunAction_label=実行(&R)...
RunAction_tooltip=実行

RunAction_runError=RunAction の実行時にエラーが発生しました。

DebugAction_label=デバッグ(&D)...
DebugAction_tooltip=デバッグ
DebugAction_runError=DebugAction の実行時にエラーが発生しました。

ExplainSQLAction_label=実行プランを取得(&G)
ExplainSQLAction_tooltip=SQL 実行プランを説明する
ExplainSQLActionDelegate_error_initview=SQL 実行プランのビューを初期化できません ：
ExplainSQLActionDelegate_error_proc_qp=処理対象オブジェクトのクエリプランを取得中にエラーが発生しました。

ExecuteSQLActionDelegate_error_execute=SQL を実行できません :
ExecuteSQLActionDelegate_error_profile=接続プロファイルを取得できません ：
ExecuteSQLActionDelegate_error_initview=結果ビューを初期化できません :
ExecuteSQLActionDelegate_error_interrupted=実行が中断されました。

ToggleComment_error_title=コメントの切り替え
ToggleComment_error_message=コメントの切り替え中にエラーが発生しました。

AddTemplateAction_error_write_title=テンプレートの保存
AddTemplateAction_error_write_message=テンプレートを保存できません。
AddTemplateAction_label=テンプレートとして保存(&T)...
AddTemplateAction_tooltip=選択したテキストをテンプレートとして保存する...

BaseExecuteAction_job_title=SQL 文の実行
BaseExecuteAction_group_exec_title=グループの実行
