common_error=Fehler

CutAction_label= Auss&chneiden
CutAction_tooltip= Ausgewählten Text in die Zwischenablage ausschneiden

CopyAction_label= &Kopieren
CopyAction_tooltip= Ausgewählten Text in die Zwischenablage kopieren

CopyToClipboard_error_title= Problem beim Kopieren in Zwischenablage
CollectionUtil_invalid_size=ungültige Größe
CopyToClipboard_error_message= Beim Zugriff auf die Zwischenablage des Systems trat ein Problem auf. Neuversuch?

DeleteAction_label=&Löschen...
DeleteAction_0=Fehler beim Versuch, den Knoten zu löschen:
DeleteAction_tooltip=Löscht die ausgewählten Elemente.
DeleteAction_confirm_title=Löschen bestätigen
DeleteAction_confirm_message=Möchten Sie wirklich löschen?

DeployAction_label=Auf Server &speichern
DeployAction_error_title=Fehler beim Speichern
DeployAction_error_message=Speichern auf Server nicht möglich.
DeployAction_save_information=Informationen
DeployAction_save_message=Das Objekt "{0}" wurde erfolgreich auf dem Server gespeichert!

PasteAction_label=&Einfügen
PasteAction_1=Fehler beim Versuch einzufügen:
PasteAction_tooltip=Fügt Elemente aus der Zwischenablage ein.

ExecuteSQLAction_label=All&e ausführen
ExecuteSQLAction_tooltip=Alle SQL-Anweisungen ausführen

ExecuteSelectionSQLAction_label=Aus&gewählten Text ausführen
ExecuteSelectionSQLAction_tooltip=Ausgewählte SQL-Anweisungen ausführen

ExecuteSQLAsOneStatement_label=Ausgewählten Text als eine Anweisung aus&führen
ExecuteSQLAsOneStatement_tooltip=Ausgewählten Text als eine Anweisung ausführen

ExecuteCurrentSQLAction_label=Aktuellen Text ausfü&hren
ExecuteCurrentSQLAction_tooltip=Aktuelle SQL-Anweisungen ausführen

DMLDialogSelectionSQLAction_label=In S&QL-Abfrageerstellung bearbeiten...
DMLDialogSelectionSQLAction_tooltip=Ausgewählte SQL-Anweisungen in SQL-Abfrageerstellung bearbeiten

GotoMatchingTokenAction_label=Zu übereinsti&mmendem Token
GotoMatchingTokenAction_tooltip=Übereinstimmendes aktuelles Token

RunAction_label=A&usführen..
RunAction_tooltip=Ausf

RunAction_runError=Fehler beim Ausführen von RunAction

DebugAction_label=&Debug...
DebugAction_tooltip=Debug
DebugAction_runError=Fehler beim Ausführen von DebugAction

ExplainSQLAction_label=Ausführungs&plan abrufen
ExplainSQLAction_tooltip=SQL-Ausführungsplan erläutern
ExplainSQLActionDelegate_error_initview=Ansicht des SQL-Ausführungsplans konnte nicht initialisiert werden:
ExplainSQLActionDelegate_error_proc_qp=Fehler beim Abrufen des Abfrageplans für das Prozedurobjekt

ExecuteSQLActionDelegate_error_execute=SQL wurde nicht ausgeführt:
ExecuteSQLActionDelegate_error_profile=Das Verbindungsprofil wurde nicht abgerufen.
ExecuteSQLActionDelegate_error_initview=Ergebnisansicht wurde nicht initialisiert:
ExecuteSQLActionDelegate_error_interrupted=Die Ausführung wurde unterbrochen.

ToggleComment_error_title=Kommentar ein/aus
ToggleComment_error_message=Beim Ein-/Ausschalten von Kommentaren ist ein Fehler aufgetreten.

AddTemplateAction_error_write_title=Vorlage wird gespeichert...
AddTemplateAction_error_write_message=Vorlage konnte nicht gespeichert werden.
AddTemplateAction_label=Als &Vorlage speichern...
AddTemplateAction_tooltip=Ausgewählten Text als Vorlage speichern...

BaseExecuteAction_job_title=Ausführung der SQL-Anweisung
BaseExecuteAction_group_exec_title=Ausführung der Gruppe
