common_error=错误

CutAction_label= 剪切(&T)
CutAction_tooltip= 将选定的文本剪切到剪贴板

CopyAction_label= 复制(&C)
CopyAction_tooltip= 将选定的文本复制到剪贴板

CopyToClipboard_error_title= 复制到剪贴板时发生问题
CollectionUtil_invalid_size=无效的尺寸
CopyToClipboard_error_message= 访问系统剪贴板时出现问题。重试?

DeleteAction_label=删除(&D)
DeleteAction_0=尝试删除节点时出错:
DeleteAction_tooltip=删除选定元素
DeleteAction_confirm_title=确认删除
DeleteAction_confirm_message=是否确实要删除?

DeployAction_label=保存至服务器(&S)
DeployAction_error_title=保存错误
DeployAction_error_message=未能保存至服务器
DeployAction_save_information=信息
DeployAction_save_message=对象“{0}”已成功保存至服务器!

PasteAction_label=粘贴(&P)
PasteAction_1=尝试粘贴时出错:
PasteAction_tooltip=从剪贴板粘贴元素

ExecuteSQLAction_label=全部执行(&E)
ExecuteSQLAction_tooltip=执行所有 SQL 语句

ExecuteSelectionSQLAction_label=执行选定的文本(&X)
ExecuteSelectionSQLAction_tooltip=执行选定的 SQL 语句

ExecuteSQLAsOneStatement_label=Exe&cute Selected Text As One Statement
ExecuteSQLAsOneStatement_tooltip=Execute Selected Text As One Statement

ExecuteCurrentSQLAction_label=Exec&ute Current Text
ExecuteCurrentSQLAction_tooltip=Execute Current SQL Statements

DMLDialogSelectionSQLAction_label=在 SQL 查询生成器中编辑(&Q)...
DMLDialogSelectionSQLAction_tooltip=在 SQL 查询生成器中编辑选定的 SQL 语句

GotoMatchingTokenAction_label=转到匹配标记(&M)
GotoMatchingTokenAction_tooltip=匹配当前标记

RunAction_label=运行(&R)...
RunAction_tooltip=运行

RunAction_runError=执行 RunAction 时发生了错误。

DebugAction_label=调试(&D)...
DebugAction_tooltip=调试
DebugAction_runError=执行 DebugAction 时发生了错误。

ExplainSQLAction_label=获取执行计划(&G)
ExplainSQLAction_tooltip=说明 SQL 执行计划
ExplainSQLActionDelegate_error_initview=未能初始化 SQL 执行方案视图:
ExplainSQLActionDelegate_error_proc_qp=获取过程对象的查询方案时发生了错误

ExecuteSQLActionDelegate_error_execute=未能执行 SQL:
ExecuteSQLActionDelegate_error_profile=未能获取连接配置文件:
ExecuteSQLActionDelegate_error_initview=未能初始化结果视图:
ExecuteSQLActionDelegate_error_interrupted=执行已中断。

ToggleComment_error_title=切换注释
ToggleComment_error_message=切换注释时发生了错误。

AddTemplateAction_error_write_title=正在保存模板
AddTemplateAction_error_write_message=未能保存模板。
AddTemplateAction_label=另存为模板(&T)...
AddTemplateAction_tooltip=将所选文本另存为模板...

BaseExecuteAction_job_title=SQL 语句执行
BaseExecuteAction_group_exec_title=组执行
