common_error=Error

CutAction_label= Cor&tar
CutAction_tooltip= Cortar el texto seleccionado al Portapapeles

CopyAction_label= &Copiar
CopyAction_tooltip= Copiar el texto seleccionado al Portapapeles

CopyToClipboard_error_title= Problema al copiar al Portapapeles
CollectionUtil_invalid_size=tamaño no válido
CopyToClipboard_error_message= Se ha producido un problema al acceder al Portapapeles del sistema. ¿Reintentar?

DeleteAction_label=&Eliminar
DeleteAction_0=Error al intentar eliminar nodo:
DeleteAction_tooltip=Borra los elementos seleccionados
DeleteAction_confirm_title=Confirmar eliminación
DeleteAction_confirm_message=¿Seguro que desea eliminar?

DeployAction_label=Guardar en el &servidor
DeployAction_error_title=Error al guardar
DeployAction_error_message=Error al guardar en el servidor
DeployAction_save_information=Información
DeployAction_save_message=¡El objeto "{0}" se ha guardado en el servidor!

PasteAction_label=&Pegar
PasteAction_1=Error al intentar pegar:
PasteAction_tooltip=Pega elementos del Portapapeles

ExecuteSQLAction_label=&Ejecutar todo
ExecuteSQLAction_tooltip=Ejecutar todas las sentencias SQL

ExecuteSelectionSQLAction_label=E&jecutar texto seleccionado
ExecuteSelectionSQLAction_tooltip=Ejecutar sentencias SQL seleccionadas

DMLDialogSelectionSQLAction_label=Editar en el compilador de consultas S&QL...
DMLDialogSelectionSQLAction_tooltip=Editar sentencias SQL seleccionadas en el compilador de consultas SQL

RunAction_label=&Ejecutar...
RunAction_tooltip=Ejecutar

RunAction_runError=Se ha producido un error al ejecutar RunAction

DebugAction_label=&Depurar...
DebugAction_tooltip=Depurar
DebugAction_runError=Se ha producido un error al ejecutar DebugAction

ExplainSQLAction_label=&Obtener plan de ejecución
ExplainSQLAction_tooltip=Explicar plan de ejecución SQL
ExplainSQLActionDelegate_error_initview=Error al inicializar vista del plan de ejecución SQL:
ExplainSQLActionDelegate_error_proc_qp=Se ha producido un error al obtener el plan de consulta para objeto de procedimiento

ExecuteSQLActionDelegate_error_execute=Error al ejecutar SQL:
ExecuteSQLActionDelegate_error_profile=Error al obtener el perfil de conexión:
ExecuteSQLActionDelegate_error_initview=Error al inicializar vista de resultado:
ExecuteSQLActionDelegate_error_interrupted=Se ha interrumpido la ejecución.

ToggleComment_error_title=Alternar comentario
ToggleComment_error_message=Se ha producido un error al alternar comentarios.

AddTemplateAction_error_write_title=Guardando plantilla
AddTemplateAction_error_write_message=Error al guardar plantilla.
AddTemplateAction_label=Grabar como &plantilla...
AddTemplateAction_tooltip=Grabar texto seleccionado como plantilla...

BaseExecuteAction_job_title=Ejecución de sentencia SQL
BaseExecuteAction_group_exec_title=Ejecución de grupo
