common_error=Erreur

CutAction_label= Co&uper
CutAction_tooltip= Couper le texte sélectionné dans le Presse-papiers

CopyAction_label= &Copier
CopyAction_tooltip= Copier le texte sélectionné dans le Presse-papiers

CopyToClipboard_error_title= Problème de copie dans le Presse-papiers
CollectionUtil_invalid_size=taille invalide
CopyToClipboard_error_message= Un problème est survenu lors de l'accès au Presse-papiers du système.

DeleteAction_label=&Supprimer
DeleteAction_0=Erreur lors de la tentative de suppression du nœud :
DeleteAction_tooltip=Supprime les éléments sélectionnés
DeleteAction_confirm_title=Confirmer la suppression
DeleteAction_confirm_message=Voulez-vous vraiment procéder à la suppression ?

DeployAction_label=Enregi&strer sur le serveur
DeployAction_error_title=Erreur d'enregistrement
DeployAction_error_message=Impossible d'enregistrer sur le serveur
DeployAction_save_information=Informations
DeployAction_save_message=L'objet "{0}" a été enregistré avec succès sur le serveur !

PasteAction_label=&Coller
PasteAction_1=Erreur lors de la tentative de collage :
PasteAction_tooltip=Colle les éléments du Presse-papiers

ExecuteSQLAction_label=&Exécuter Tout
ExecuteSQLAction_tooltip=Exécuter toutes les instructions SQL

ExecuteSelectionSQLAction_label=E&xécuter le texte sélectionné
ExecuteSelectionSQLAction_tooltip=Exécuter les instructions SQL sélectionnées

DMLDialogSelectionSQLAction_label=Modifier dans le générateur de requête S&QL...
DMLDialogSelectionSQLAction_tooltip=Modifier les instructions SQL sélectionnées dans le générateur de requête SQL

GotoMatchingTokenAction_label=Goto &Matching Token
GotoMatchingTokenAction_tooltip=Matching Current Token

RunAction_label=&Exécuter...
RunAction_tooltip=Exécuter

RunAction_runError=Une erreur s'est produite lors de l'exécution de RunAction

DebugAction_label=&Déboguer...
DebugAction_tooltip=Déboguer
DebugAction_runError=Une erreur s'est produite lors de l'exécution de DebugAction

ExplainSQLAction_label=&Obtenir le plan d'exécution
ExplainSQLAction_tooltip=Expliquer le plan d'exécution SQL
ExplainSQLActionDelegate_error_initview=Impossible d'initialiser la vue du plan d'exécution SQL :
ExplainSQLActionDelegate_error_proc_qp=Une erreur se produit lors de l'obtention du plan de requête pour l'objet procédural

ExecuteSQLActionDelegate_error_execute=Impossible d'exécuter SQL :
ExecuteSQLActionDelegate_error_profile=Impossible d'obtenir un profil de connexion :
ExecuteSQLActionDelegate_error_initview=Impossible d'initialiser la vue des résultats :
ExecuteSQLActionDelegate_error_interrupted=L'exécution a été interrompue.

ToggleComment_error_title=Basculer le commentaire
ToggleComment_error_message=Une erreur s'est produite lors du basculement des commentaires.

AddTemplateAction_error_write_title=Enregistrement du modèle
AddTemplateAction_error_write_message=Echec d'enregistrement du modèle.
AddTemplateAction_label=Enregistrer comme &modèle...
AddTemplateAction_tooltip=Enregistrer le texte sélectionné comme modèle...

BaseExecuteAction_job_title=Exécution de l'instruction SQL
BaseExecuteAction_group_exec_title=Exécution du groupe
