common_error=오류

CutAction_label= 잘라내기(&T)
CutAction_tooltip= 클립보드에 선택한 텍스트 잘라내기

CopyAction_label= 복사(&C)
CopyAction_tooltip= 클립보드에 선택한 텍스트 복사

CopyToClipboard_error_title= 클립보드로 복사하는 중 문제 발생
CollectionUtil_invalid_size=잘못된 크기
CopyToClipboard_error_message= 시스템 클립보드에 액세스하는 중 문제가 발생했습니다. 다시 시도하시겠습니까?

DeleteAction_label=삭제(&D)
DeleteAction_0=노드 삭제 중 오류 발생:
DeleteAction_tooltip=선택한 요소 삭제
DeleteAction_confirm_title=삭제 확인
DeleteAction_confirm_message=삭제하시겠습니까?

DeployAction_label=서버에 저장(&S)
DeployAction_error_title=저장 오류
DeployAction_error_message=서버에 저장 실패
DeployAction_save_information=정보
DeployAction_save_message=개체 "{0}"을 서버에 저장하였습니다!

PasteAction_label=붙여넣기(&P)
PasteAction_1=붙여넣기 중 오류 발생:
PasteAction_tooltip=클립보드에 있는 요소 붙여넣기

ExecuteSQLAction_label=모두 실행(&E)l
ExecuteSQLAction_tooltip=모든 SQL 문 실행

ExecuteSelectionSQLAction_label=선택한 텍스트 실행(&X)
ExecuteSelectionSQLAction_tooltip=선택한 SQL 문 실행

DMLDialogSelectionSQLAction_label=SQL 쿼리 빌더에서 편집(&Q)...
DMLDialogSelectionSQLAction_tooltip=SQL 쿼리 빌더에서 선택한 SQL 문 편집

RunAction_label=실행(&R)...
RunAction_tooltip=실행

RunAction_runError=작업을 실행하는 중 오류가 발생했습니다.

DebugAction_label=디버그(&D)...
DebugAction_tooltip=디버그
DebugAction_runError=Debug 작업을 실행하는 중 오류가 발생했습니다.

ExplainSQLAction_label=실행 계획 가져오기(&G)
ExplainSQLAction_tooltip=SQL 실행 계획 설명
ExplainSQLActionDelegate_error_initview=SQL 실행 계획 보기를 초기화하지 못했습니다.
ExplainSQLActionDelegate_error_proc_qp=프로시저 개체의 쿼리 계획을 가져오는 중 오류가 발생했습니다.

ExecuteSQLActionDelegate_error_execute=SQL 실행 실패:
ExecuteSQLActionDelegate_error_profile=연결 프로필을 가져오지 못했습니다.
ExecuteSQLActionDelegate_error_initview=결과 보기를 초기화하지 못했습니다.
ExecuteSQLActionDelegate_error_interrupted=실행이 중단되었습니다.

ToggleComment_error_title=설명 전환
ToggleComment_error_message=설명을 전환하는 중 오류가 발생했습니다.

AddTemplateAction_error_write_title=템플릿을 저장하는 중
AddTemplateAction_error_write_message=템플릿을 저장하지 못했습니다.
AddTemplateAction_label=템플릿으로 저장(&T)...
AddTemplateAction_tooltip=선택한 텍스트를 템플릿으로 저장...

BaseExecuteAction_job_title=SQL 문 실행
BaseExecuteAction_group_exec_title=그룹 실행
