#Thu Jun 22 00:30:48 EDT 2006
plugin.internal_error=Interner Fehler - org.eclipse.datatools.connectivity
ConnectionProfileConstants.unknownVersion=Unbekannt
dialog.title.error.loadconnectionfactory=Beim Laden der Verbindungsfactory in "{0}" ist ein Fehler aufgetreten\!
ConnectJob.name=Verbindungen zu {0} werden erstellt.
ConnectJob.status.info=Für eine oder mehrere Erweiterungen konnten keine Verbindungen zu {0} erstellt werden.
ConnectJob.status.error=Die Verbindung zu {0} konnte nicht hergestellt werden.
DisconnectJob.name=Verbindungen zu {0} werden geschlossen.
DisconnectJob.status.info=Für eine oder mehrere Erweiterungen konnten die Verbindungen zu {0} nicht geschlossen werden.
DisconnectJob.status.error=Die Verbindung zu {0} konnte nicht getrennt werden.
CreateConnectionJob.name={0} mit {1} wird erstellt.
CreateConnectionJob.error=Beim Herstellen der Verbindung {0} zu {1} trat ein Fehler auf. (Fehler\: {2})
OpenConnectionEventJob.name=Das Ereignis zum Öffnen der Verbindung für {0} wird verarbeitet.
CloseManagedConnectionJob.name=Verbindung {0} zu {1} wird geschlossen.
CloseManagedConnectionJob.error=Fehler beim Schließen der Verbindung {0} zu {1}. (Fehler\: {2})
CloseConnectionEventJob.name=Das Ereignis zum Schließen der Verbindung für {0} wird verarbeitet.
assert.invalid.profile=Parsing-Fehler\: Ungültiges Attribut ({0})
assert.invalid.profile.duplicateFactory = Analysefehler\: Doppelte Factory-ID mit doppelter Priorität ({0})
assert.invalid.profile.nullFactory = Analysefehler\: Factory oder Factory-ID ({0}/{1}) ist gleich null.
dialog.title.error.loadwizard=Beim Laden des Assistenten für neue Objekte in "{0}" ist ein Fehler aufgetreten\!
operation.new.connectionprofile=Profil wird erstellt\: "{0}"
error.connect=Beim Herstellen der Verbindung zum Profil "{0}" ist ein Fehler aufgetreten. Weitere Details enthält die Protokolldatei.
marker.error=Beim Herstellen der Verbindung zum Profil {0} ist ein Fehler aufgetreten.  (Fehler\: {1})
drivermarker.error = Problem mit Treiber "{0}". (Fehler\: {1})
drivermarker.import.error = Fehlende JAR-Liste für Treiberdefinition bei Import von Profil "{0}" erstellt.
profile.duplicate =Der Verbindungsprofilname "{0}" ist doppelt vorhanden\!
profile.notexist=Das Verbindungsprofil "{0}" ist nicht vorhanden\!
duplicate.profile.name=Kopie von {0}({1})
DriverConnectionBase.error.unknown=Die Verbindung ist mit einem nicht angegebenen Fehler fehlgeschlagen.
DriverConnectionBase.error.driverDefinitionNotSpecified=Die Treiberdefinition war nicht angegeben.
DriverConnectionBase.error.driverDefinitionNotFound=Die Treiberdefinition wurde nicht gefunden.
error.loadprofilesxml=Beim Laden der Verbindungsprofildaten trat ein Fehler auf.
error.saveprofilesxml=Beim Speichern der Verbindungsprofildaten trat ein Fehler auf.
error.loaddriversxml = Fehler beim Laden der Treiberdefinitionsdaten.
error.savedriversxml = Fehler beim Speichern der Treiberdefinitionsdaten.
trace.error.propertiesPersistenceHook=''propertiesPersistenceHook'' konnte nicht geladen werden; Standardwert wird verwendet (Profiltyp\={0}, Erweiterung\={1})
trace.error.propertiesPersistenceHookSaveError=Beim Aufrufen des permanenten Hooks für die Eigenschaften trat ein Fehler auf. Alle Eigenschaften bleiben permanent bestehen (Profil\={0}, Erweiterung\={1})
trace.error.propertiesPersistenceHookLoadError=Beim Aufrufen des permanenten Hooks für die Eigenschaften trat ein Fehler auf. Temporäre Eigenschaften werden nicht festgelegt (Profil\={0}, Erweiterung\={1})
trace.error.migration = Fehler beim Laden des Migrationselements für Verbindungsprofil-Anbieter (id={0}, migration class={1})
trace.error.drivermigration = Fehler beim Erstellen der Treiberinstanz des Profils (ID={0}, Treiber-ID={1})

migration.error.providerDoesNotExist = Fehler beim Laden des Migrationselements: Angegebene neue Anbieter-ID ist ungültig (newProviderID={0})
migration.error.invalidPropertyMigrationElement = Fehler beim Laden des Migrationselements: Eigenschaftsmigration muss neuen oder alten Eigenschaftsschlüssel oder beides enthalten
migration.error.unknownParentElement = Fehler beim Laden des Migrationselements: Unbekanntes übergeordnetes Element (parent element name={0})

DriverUtil.taskName = Klassen werden in {0} verarbeitet
Category.Name.Unknown=Nicht unterstützt

WorkOfflineJob.name = {0} wird in Offline-Modus geändert.
WorkOfflineJob.status.error = Offline-Verbindungen zu {1} konnten für eine oder mehrere Erweiterungen nicht erstellt werden.

SaveWorkOfflineDataJob.name = Speichern Sie die Offline-Daten für {0}.
SaveWorkOfflineDataJob.status = Speichern Sie den Status der Offline-Daten.

CreateOfflineConnectionJob.name = Offline-Verbindung {0} zu {1} wird erstellt.
CreateOfflineConnectionJob.error = Fehler beim Erstellen der Offline-Verbindung {0} zu {1}. (Fehler\: {2})

ManagedConnection_save_not_connected_error = Verbindung zum Server erforderlich, um Offline-Daten zu speichern.
ManagedConnection_offline_not_supported_error = {0} unterstützt Offline-Arbeiten nicht.

drivers.error.finding.property.no.template = Beim Versuch, {0} aus der Treibervorlage abzurufen, ist ein Problem aufgetreten.

JDBCConnection.technologyName = JDBC


