#Thu Jun 22 00:30:48 EDT 2006
plugin.internal_error=내부 오류 - org.eclipse.datatools.connectivity
ConnectionProfileConstants.unknownVersion=알 수 없음
dialog.title.error.loadconnectionfactory="{0}"에서 연결 팩토리 로드 중 오류 발생.
ConnectJob.name={0}에 대한 연결 작성 중.
ConnectJob.status.info=하나 이상의 확장자에 대해 {0}에 대한 연결을 작성할 수 없습니다.
ConnectJob.status.error={0}에 연결할 수 없습니다.
DisconnectJob.name={0}에 대한 연결을 닫는 중.
DisconnectJob.status.info=하나 이상의 확장에 대해 {0}에 대한 연결을 닫을 수 없습니다.
DisconnectJob.status.error={0}에서 연결을 끊을 수 없습니다.
CreateConnectionJob.name={1}에 대한 {0} 연결 작성 중.
CreateConnectionJob.error={1}에 대한 {0} 연결 작성 중 오류 발생(오류\: {2}).
OpenConnectionEventJob.name={0}에 대한 연결 열기 이벤트 처리 중.
CloseManagedConnectionJob.name={1}에 대한 {0} 연결을 닫는 중(오류\: {2}).
CloseManagedConnectionJob.error={1}에 대한 {0} 연결을 닫는 중 오류 발생.
CloseConnectionEventJob.name={0}에 대한 연결 닫기 이벤트 처리 중.
assert.invalid.profile=구문 분석 오류\: 올바르지 않은 속성({0})
assert.invalid.profile.duplicateFactory=구문 분석 오류\: 팩토리 ID 중복({0})
dialog.title.error.loadwizard="{0}"에서 새로 작성 마법사 로드 중 오류 발생.
operation.new.connectionprofile=프로파일 작성 중\: "{0}"
error.connect="{0}" 프로파일에 연결하는 중에 문제가 발생했습니다. 세부사항은 로그 파일을 참조하십시오.
marker.error={0} 프로파일에 연결 중 문제 발생  (오류\: {1}).
profile.duplicate=연결 프로파일 이름 "{0}" 중복.
profile.notexist="{0}" 연결 프로파일이 없습니다\!
duplicate.profile.name={0}의 사본({1})
DriverConnectionBase.error.unknown=지정되지 않은 오류로 연결에 실패했습니다.
DriverConnectionBase.error.driverDefinitionNotSpecified=드라이버 정의가 지정되지 않았습니다.
DriverConnectionBase.error.driverDefinitionNotFound=드라이버 정의를 찾을 수 없습니다.
error.loadprofilesxml=연결 프로파일 데이터 로드 중에 오류가 발생했습니다.
error.saveprofilesxml=연결 프로파일 데이터 저장 중에 오류가 발생했습니다.
error.loaddriversxml = 드라이버 정의 데이터 로드 중 오류 발생
error.savedriversxml = 드라이버 정의 데이터 저장 중 오류 발생
trace.error.propertiesPersistenceHook=기본값(프로파일 유형\={0}, 확장\={1})을 사용하는 propertiesPersistenceHook를 로드할 수 없습니다.
trace.error.propertiesPersistenceHookSaveError=특성 지속 후크 호출 중에 오류 발생; 모든 특성 지속(프로파일\={0}, 확장\={1})
trace.error.propertiesPersistenceHookLoadError=특성 지속 후크 호출 중에 오류 발생; 임시 특성이 설정되지 않음(프로파일\={0}, 확장\={1})

DriverUtil.taskName = {0}의 클래스 처리 중
Category.Name.Unknown=지원 안 함
