#Thu Jun 22 00:30:48 EDT 2006
plugin.internal_error=内部错误 － org.eclipse.datatools.connectivity
ConnectionProfileConstants.unknownVersion=未知
dialog.title.error.loadconnectionfactory=在“{0}”中装入连接工厂时出错！
ConnectJob.name=正在创建与 {0} 的连接。
ConnectJob.status.info=未能为一个或多个扩展创建与 {0} 的连接。
ConnectJob.status.error=未能连接到 {0}。
DisconnectJob.name=正在关闭与 {0} 的连接。
DisconnectJob.status.info=未能为一个或多个扩展关闭与 {0} 的连接。
DisconnectJob.status.error=未能与 {0} 断开连接。
CreateConnectionJob.name=正在创建与 {1} 的 {0} 连接。
CreateConnectionJob.error=创建与 {1} 的 {0} 连接时出错。（错误：{2}）
OpenConnectionEventJob.name=正在处理 {0} 的打开连接事件。
CloseManagedConnectionJob.name=正在关闭与 {1} 的 {0} 连接。（错误：{2}）
CloseManagedConnectionJob.error=关闭与 {1} 的 {0} 连接时出错。
CloseConnectionEventJob.name=正在处理 {0} 的关闭连接事件。
assert.invalid.profile=解析错误：属性（{0}）无效。
assert.invalid.profile.duplicateFactory = 分析错误\: 具有重复优先级({0})的重复工厂 ID
assert.invalid.profile.nullFactory = 分析错误\: 工厂或工厂 id 为空 ({0}/{1})
dialog.title.error.loadwizard=在“{0}”中装入新向导时出错！
operation.new.connectionprofile=正在创建概要文件“{0}”。
error.connect=连接到概要文件“{0}”时发生了问题。请参阅日志文件以了解更多详细信息。
marker.error=连接到概要文件 {0} 时发生了问题。（错误：{1}）
profile.duplicate=连接概要文件名“{0}”重复！
profile.notexist=连接概要文件“{0}”不存在！
duplicate.profile.name={0} 的副本（{1}）
DriverConnectionBase.error.unknown=发生了未指定的错误，连接失败。
DriverConnectionBase.error.driverDefinitionNotSpecified=未指定驱动程序定义。
DriverConnectionBase.error.driverDefinitionNotFound=找不到驱动程序定义。
error.loadprofilesxml=装入连接概要文件数据时出错。
error.saveprofilesxml=保存连接概要文件数据时出错。
error.loaddriversxml = 加载驱动程序定义数据时出错。
error.savedriversxml = 保存驱动程序定义数据时出错。
trace.error.propertiesPersistenceHook=无法装入 propertiesPersistenceHook，使用缺省值（概要文件类型为 {0}，扩展名为 {1}）
trace.error.propertiesPersistenceHookSaveError=调用属性持久挂钩时出错；保存所有属性（概要文件为 {0}，扩展名为 {1}）
trace.error.propertiesPersistenceHookLoadError=调用属性持久挂钩时出错；未设置瞬态属性（概要文件为 {0}，扩展名为 {1}）
trace.error.migration = 为连接配置文件提供程序加载迁移元素时出错(id={0}，迁移类={1})
trace.error.drivermigration = 创建配置文件(id={0}，驱动程序 id={1})的驱动程序实例时出错

migration.error.providerDoesNotExist = 加载迁移元素时出错: 指定的 newProviderID 无效(newProviderID={0})
migration.error.invalidPropertyMigrationElement = 加载迁移元素时出错: propertyMigration 必须指定 newPropertyKey、oldPropertyKey 或二者
migration.error.unknownParentElement = 加载迁移元素时出错: 未知父元素(父元素名称={0})

DriverUtil.taskName = 正在处理 {0} 中的类
Category.Name.Unknown=不支持

WorkOfflineJob.name = 将 {0} 更改为脱机工作模式。
WorkOfflineJob.status.error = 无法为一个或多个扩展创建到 {1} 的脱机连接。

SaveWorkOfflineDataJob.name = 保存 {0} 的脱机数据。
SaveWorkOfflineDataJob.status = 保存脱机数据状态。

CreateOfflineConnectionJob.name = 创建到 {1} 的脱机 {0} 连接。
CreateOfflineConnectionJob.error = 创建到 {1} 的脱机 {0} 连接时出错。(错误: {2})

ManagedConnection_save_not_connected_error = 必须连接到服务器才能保存脱机数据。
ManagedConnection_offline_not_supported_error = {0} 不支持脱机工作。

drivers.error.finding.property.no.template = 尝试从驱动程序模板中检索 {0} 时出现问题。

JDBCConnection.technologyName = JDBC

