#Thu Jun 22 00:30:48 EDT 2006
plugin.internal_error=内部エラー - org.eclipse.datatools.connectivity
ConnectionProfileConstants.unknownVersion=不明
dialog.title.error.loadconnectionfactory="{0}" での接続ファクトリーのロード中エラーが発生しました。
ConnectJob.name={0} への接続を作成中です。
ConnectJob.status.info=1 つ以上の拡張に対して {0} への接続を作成できませんでした。
ConnectJob.status.error={0} へ接続できませんでした。
DisconnectJob.name={0} への接続を終了中です。
DisconnectJob.status.info=1 つ以上の拡張に対して {0} への接続を終了できませんでした。
DisconnectJob.status.error={0} を切断できませんでした。
CreateConnectionJob.name={1} への {0} 接続を作成中です。
CreateConnectionJob.error={1} への {0} 接続の作成中にエラーが発生しました。 (エラー\: {2})
OpenConnectionEventJob.name={0} の接続オープン・イベントを処理中です。
CloseManagedConnectionJob.name={1} への {0} 接続を終了中です。 (エラー\: {2})
CloseManagedConnectionJob.error={1} への {0} 接続の終了中にエラーが発生しました。
CloseConnectionEventJob.name={0} の接続終了イベントを処理中です。
assert.invalid.profile=構文解析エラー\: 無効な属性です ({0})
assert.invalid.profile.duplicateFactory=構文解析エラー\: ファクトリー ID ({0}) が重複しています
dialog.title.error.loadwizard="{0}" での新規ウィザードのロード中にエラーが発生しました。
operation.new.connectionprofile=プロファイルの作成中です\: "{0}"
error.connect=プロファイル "{0}" の接続中に問題が発生しました。詳細についてはログ・ファイルを参照してください。
marker.error=プロファイル {0} の接続中に問題が発生しました。  (エラー\: {1})
profile.duplicate=プロファイル名 "{0}" の接続が重複しています\!
profile.notexist=接続プロファイル "{0}" が存在しません\!
duplicate.profile.name={0} のコピー ({1})
DriverConnectionBase.error.unknown=接続が、未指定のエラーで失敗しました。
DriverConnectionBase.error.driverDefinitionNotSpecified=ドライバー定義が指定されていません。
DriverConnectionBase.error.driverDefinitionNotFound=ドライバー定義が見つかりません。
error.loadprofilesxml=接続プロファイル・データのロード中にエラーが発生しました。
error.saveprofilesxml=接続プロファイル・データの保管中にエラーが発生しました。
error.loaddriversxml = ドライバ定義のデータを読み込み中にエラーが発生しました。
error.savedriversxml = ドライバ定義のデータを保存中にエラーが発生しました。
trace.error.propertiesPersistenceHook=propertiesPersistenceHook をロードできませんでした。デフォルトを使用します (プロファイル・タイプ\={0}, 拡張子\={1})
trace.error.propertiesPersistenceHookSaveError=プロパティー永続フックの起動中にエラーが発生しました; すべてのプロパティーを保持します (プロファイル\={0}、拡張子\={1})
trace.error.propertiesPersistenceHookLoadError=プロパティー永続フックの起動中にエラーが発生しました; 一時プロパティーが設定されていません (プロファイル\={0}、拡張子\={1})

DriverUtil.taskName = {0} でクラスを処理中です。
