###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=웹 서비스 데이터 원본
data.set.name=웹 서비스 데이터 집합

connection.profile.name=웹 서비스 데이터 원본 연결 프로필

datasource.property.soapEndPoint=SOAP 끝점(&S)
datasource.property.connectionClass=연결 클래스(&C)
datasource.property.connectionTimeOut=연결 시간 초과(&T)
dataset.property.xmlFileURI=XML 파일(&X)
dataset.property.xsdFileURI=스키마 파일(&S)
datasource.property.wsdlUrl=&WSDL URL
