###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=Web Services 数据源
data.set.name=Web Services 数据集

connection.profile.name=Web Services 数据源连接配置文件

datasource.property.soapEndPoint=SOAP 终结点
datasource.property.connectionClass=连接类
datasource.property.connectionTimeOut=连接超时
dataset.property.xmlFileURI=XML 文件
dataset.property.xsdFileURI=架构文件
