###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=Web サービスのデータソース
data.set.name=Web サービスのデータセット

connection.profile.name=Web サービスのデータソースの接続プロファイル

datasource.property.soapEndPoint=SOAP エンドポイント(&S)
datasource.property.connectionClass=接続クラス(&C)
datasource.property.connectionTimeOut=接続のタイムアウト(&T)
dataset.property.xmlFileURI=XML ファイル(&X)
dataset.property.xsdFileURI=スキーマファイル(&S)
datasource.property.wsdlUrl=&WSDL URL
