###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=Web サービスデータソース
data.set.name=Web サービスのデータセット

connection.profile.name=Web サービスデータソースの接続プロファイル

datasource.property.soapEndPoint=SOAP エンドポイント(&S)
datasource.property.connectionClass=接続クラス(&C)
datasource.property.connectionTimeOut=接続のタイムアウト(&T)
dataset.property.xmlFileURI=XML ファイル(&X)
dataset.property.xsdFileURI=スキーマファイル(&S)
datasource.property.wsdlUrl=WSDL の URL(&W)
datasource.property.driverClassPath=Driver Class&Path
