###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=Source de données Services Web
data.set.name=Jeu de données Services Web

connection.profile.name=Profil de connexion à la source de données Services Web

datasource.property.soapEndPoint=Point de fin &SOAP
datasource.property.connectionClass=&Classe de connexion
datasource.property.connectionTimeOut=Délai de connexion &dépassé
dataset.property.xmlFileURI=Fichier &XML
dataset.property.xsdFileURI=Fichier de &schéma
datasource.property.wsdlUrl=&WSDL URL
