###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=ODA-Laufzeittreiber für Web-Dienste von Eclipse-Datentools-Plattform
data.source.name=Datenquelle für Web-Dienste
data.set.name=Datensatz für Web-Dienste

connection.profile.name=Datenquellen-Verbindungsprofil für Web-Dienste

datasource.property.soapEndPoint=&SOAP-Endpunkt
datasource.property.connectionClass=Verbindungs&klasse
datasource.property.connectionTimeOut=&Zeitüberschreitung für Verbindung
dataset.property.xmlFileURI=&XML-Datei
dataset.property.xsdFileURI=&Schema-Datei
datasource.property.wsdlUrl=URL für &WSDL
