###############################################################################
# Copyright (c) 2007 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#
###############################################################################
# Plug-in Configuration
#
oda.data.source.id=org.eclipse.datatools.enablement.oda.ws
#
###############################################################################
# NLS String
#
plugin.name=Eclipse Data Tools Platform Web Services ODA Runtime Driver
data.source.name=Fuente de datos de servicios web
data.set.name=Conjunto de datos de servicios web

connection.profile.name=Perfil de conexión de fuente de datos de servicios web

datasource.property.soapEndPoint=Punto final de &SOAP
datasource.property.connectionClass=&Clase de conexión
datasource.property.connectionTimeOut=&Tiempo límite de conexión
dataset.property.xmlFileURI=Archivo &XML
dataset.property.xsdFileURI=Archivo del e&squema
datasource.property.wsdlUrl=&WSDL URL
