#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=Nombre de archivo de recurso ({0}) no válido; debe terminar en .properties.
design_invalidResourceKey=Clave de recursos ({0}) no válida; no debe contener ningún espacio en blanco incrustado.
design_nullArgument=El argumento no debe ser nulo.
design_missingDataSourceDesign=Falta el diseño de origen de datos en la instancia de OdaDesignSession.
design_missingId=Falta el ID de origen de datos en el diseño del origen de datos.
