#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=Invalid resource file name ({0}); it must end with .properties.
design_invalidResourceKey=Invalid resource key ({0}); it must not contain any embedded white space.
design_nullArgument=引数は null にできません。
design_missingDataSourceDesign=OdaDesignSession インスタンスのデータ・ソース・デザインがありません。
design_missingId=データ・ソース・デザインのデータ・ソース ID がありません。
