#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=Ungültiger Ressourcendateiname ({0}); muss auf .properties enden.
design_invalidResourceKey=Ungültiger Ressourcenschlüssel ({0}); darf keine eingebetteten Leerzeichen enthalten.
design_nullArgument=Das Argument darf nicht Null sein.
design_missingDataSourceDesign=Im Exemplar 'OdaDesignSession' fehlt der Datenquellenentwurf.
design_missingId=Im Datenquellenentwurf fehlt die Datenquellen-ID.
