#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=无效的资源文件名 ({0})；它必须以 .properties 结尾。
design_invalidResourceKey=无效的资源关键字 ({0})；它不能包含任何嵌入空格。
design_nullArgument=参数不能为空。
design_missingDataSourceDesign=在 OdaDesignSession 实例中缺少数据源设计。
design_missingId=在数据源设计中缺少数据源标识。
