#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=Le nom du fichier de ressources ({0}) est incorrect, car il doit se terminer par .properties.
design_invalidResourceKey=La clé de ressources ({0}) est incorrecte, car elle ne doit contenir aucun espace intercalé.
design_nullArgument=L'argument ne doit pas être null.
design_missingDataSourceDesign=Conception de source de données manquante dans l'instance OdaDesignSession.
design_missingId=ID de source de données manquante dans la conception de source de données.
