#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=잘못된 리소스 파일 이름({0})입니다. 파일 이름은 .properties로 끝나야 합니다.
design_invalidResourceKey=잘못된 리소스 키({0})입니다. 리소스 키에 포함된 공백이 있으면 안 됩니다.
design_nullArgument=인수는 널(null)일 수 없습니다.
design_missingDataSourceDesign=OdaDesignSession 인스턴스에서 데이터 소스 디자인이 누락되었습니다.
design_missingId=데이터 소스 디자인에서 데이터 소스 ID가 누락되었습니다.
