#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=Invalid resource file name ({0}); it must end with .properties.
design_invalidResourceKey=Invalid resource key ({0}); it must not contain any embedded white space.
design_nullArgument=인수는 널(null)일 수 없습니다.
design_missingDataSourceDesign=OdaDesignSession 인스턴스에서 데이터 소스 디자인이 누락되었습니다.
design_missingId=데이터 소스 디자인에서 데이터 소스 ID가 누락되었습니다.
