#
#************************************************************************
# Copyright (c) 2005, 2010 Actuate Corporation.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
#
# Contributors:
#  Actuate Corporation - initial API and implementation
#  
#************************************************************************
#
design_invalidResourceFileName=リソースファイル名 ({0}) が無効です。拡張子は .properties にしてください。
design_invalidResourceKey=リソースキー ({0}) が無効です。埋め込みスペースは使用できません。
design_nullArgument=引数は null にできません。
design_missingDataSourceDesign=OdaDesignSession インスタンスのデータ・ソース・デザインがありません。
design_missingId=データ・ソース・デザインのデータ・ソース ID がありません。
