/* Generated By:JJTree: Do not edit this line. ..\src\org\eclipse\datatools\enablement\ingres\internal\parser\IngresSQLParserTreeConstants.java */

package org.eclipse.datatools.enablement.ingres.internal.ui.parser;

public interface IngresSQLParserTreeConstants
{
  public int JJTVOID = 0;
  public int JJTSTART = 1;
  public int JJTSQLDELIMITER = 2;
  public int JJTSQLSTATEMENT = 3;
  public int JJTSQLDATATYPE = 4;
  public int JJTDECLAREKEYWORD = 5;
  public int JJTDECLARECOMMA = 6;
  public int JJTSQLPARAM = 7;
  public int JJTEXPRESSION = 8;


  public String[] jjtNodeName = {
    "void",
    "Start",
    "SQLDelimiter",
    "SQLStatement",
    "SQLDataType",
    "DeclareKeyword",
    "DeclareComma",
    "SQLParam",
    "Expression",
  };
}
