/* Generated By:JJTree&JavaCC: Do not edit this line. IngresSQLParserConstants.java */
package org.eclipse.datatools.enablement.ingres.internal.ui.parser;

public interface IngresSQLParserConstants {

  int EOF = 0;
  int SINGLE_LINE_COMMENT = 7;
  int COMMENT_CONTENT = 12;
  int INVALID_TOKEN = 13;
  int ADD = 14;
  int ALTER = 15;
  int AND = 16;
  int ANY = 17;
  int AS = 18;
  int ASC = 19;
  int AT = 20;
  int AUTHORIZATION = 21;
  int AVG = 22;
  int BEGIN = 23;
  int BETWEEN = 24;
  int BY = 25;
  int CASCADE = 26;
  int CASE = 27;
  int CHECK = 28;
  int CHECKPOINT = 29;
  int CLOSE = 30;
  int COALESCE = 31;
  int COMMIT = 32;
  int CONSTRAINT = 33;
  int CONTINUE = 34;
  int COUNT = 35;
  int CREATE = 36;
  int CURRENT = 37;
  int CURSOR = 38;
  int DATABASE = 39;
  int DBEVENT = 40;
  int DECLARE = 41;
  int DEFAULT_VAL = 42;
  int DELETE = 43;
  int DESC = 44;
  int DISTINCT = 45;
  int DOMAIN = 46;
  int DROP = 47;
  int DUMP = 48;
  int ELSE = 49;
  int END = 50;
  int ESCAPE = 51;
  int EXCEPT = 52;
  int EXCLUSIVE = 53;
  int EXEC = 54;
  int EXECUTE = 55;
  int EXISTS = 56;
  int FETCH = 57;
  int FILLFACTOR = 58;
  int FOR = 59;
  int FOREIGN = 60;
  int FROM = 61;
  int FUNC = 62;
  int FUNCTION = 63;
  int GO = 64;
  int GOTO = 65;
  int GRANT = 66;
  int GROUP = 67;
  int HAVING = 68;
  int IF = 69;
  int IN = 70;
  int INDEX = 71;
  int INSERT = 72;
  int INTERSECT = 73;
  int INTEGRITY = 74;
  int INTO = 75;
  int IS = 76;
  int ISOLATION = 77;
  int JOIN = 78;
  int KEY = 79;
  int KILL = 80;
  int LEVEL = 81;
  int LIKE = 82;
  int LOAD = 83;
  int LOCATION = 84;
  int MAX = 85;
  int MIN = 86;
  int MODIFY = 87;
  int NO = 88;
  int NOT = 89;
  int NULL = 90;
  int NULLIF = 91;
  int OF = 92;
  int OFF = 93;
  int ON = 94;
  int ONLY = 95;
  int OPEN = 96;
  int OPTION = 97;
  int OR = 98;
  int ORDER = 99;
  int OUT = 100;
  int OUTPUT = 101;
  int PARTITION = 102;
  int PERM = 103;
  int PERMANENT = 104;
  int PREPARE = 105;
  int PRIMARY = 106;
  int PRIVILEGES = 107;
  int PRINT = 108;
  int PROCEDURE = 109;
  int PROFILE = 110;
  int PUBLIC = 111;
  int READ = 112;
  int REFERENCES = 113;
  int REMOVE = 114;
  int REORGANIZE = 115;
  int RETURN = 116;
  int REVOKE = 117;
  int ROLE = 118;
  int ROLLBACK = 119;
  int ROWCOUNT = 120;
  int ROWS = 121;
  int RULE = 122;
  int SAVE = 123;
  int SCHEMA = 124;
  int SECURITY_AUDIT = 125;
  int SECURITY_ALARM = 126;
  int SELECT = 127;
  int SEQUENCE = 128;
  int SESSION = 129;
  int SET = 130;
  int SHARED = 131;
  int SOME = 132;
  int STATISTICS = 133;
  int SUM = 134;
  int SYNONYM = 135;
  int TABLE = 136;
  int TEMPORARY = 137;
  int TO = 138;
  int TRANSACTION = 139;
  int UNION = 140;
  int UNIQUE = 141;
  int UNPARTITION = 142;
  int UPDATE = 143;
  int USER = 144;
  int USING = 145;
  int VALUES = 146;
  int VARYING = 147;
  int VIEW = 148;
  int WHEN = 149;
  int WHERE = 150;
  int WHILE = 151;
  int WITH = 152;
  int WORK = 153;
  int II_DBA = 154;
  int II_INGRES = 155;
  int INTEGER_LITERAL = 156;
  int FLOATING_POINT_LITERAL = 157;
  int EXPONENT = 158;
  int SINGLE_STRING_LITERAL = 159;
  int DOUBLE_STRING_LITERAL = 160;
  int BINARY_LITERAL = 161;
  int HEXDIGIT = 162;
  int MONEY_LITERAL = 163;
  int ID = 164;
  int SQUARE_BRACKET_ID = 165;
  int VAR_NAME_BODY = 166;
  int VAR_NAME = 167;
  int LABEL = 168;
  int GLOBAL_VAR_NAME = 169;
  int TEMP_TABLE_NAME = 170;
  int LETTER = 171;
  int DIGIT = 172;
  int SYMBOL = 173;
  int SPECSYMB = 174;
  int DELIM_START = 175;
  int DELIM_PART = 176;
  int DELIM_IDENT = 177;
  int CONCAT = 178;
  int COMMA = 179;
  int SEMICOLON = 180;
  int DOT = 181;
  int ROWTYPE = 182;
  int TILDE = 183;
  int LESS = 184;
  int LESSEQUAL = 185;
  int GREATER = 186;
  int GREATEREQUAL = 187;
  int EQUAL = 188;
  int NOTEQUAL = 189;
  int JOINPLUS = 190;
  int OPENPAREN = 191;
  int CLOSEPAREN = 192;
  int ASTERISK = 193;
  int SLASH = 194;
  int PLUS = 195;
  int MINUS = 196;
  int QUESTIONMARK = 197;
  int LEQJOIN = 198;
  int REQJOIN = 199;
  int JAVA_REF = 200;
  int UK_DOUBLE_PRECISION = 201;
  int UK_NO_SCROLL = 202;
  int UK_SEMI_SENSITIVE = 203;
  int UK_VARCHAR_S = 204;
  int UK_VARCHAR_S1 = 205;

  int DEFAULT = 0;
  int IN_SINGLE_LINE_COMMENT = 1;
  int IN_MULTI_LINE_COMMENT = 2;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\f\"",
    "\"--\"",
    "<SINGLE_LINE_COMMENT>",
    "<token of kind 8>",
    "\"/*\"",
    "\"/*\"",
    "\"*/\"",
    "<COMMENT_CONTENT>",
    "\"!%^&\"",
    "\"add\"",
    "\"alter\"",
    "\"and\"",
    "\"any\"",
    "\"as\"",
    "\"asc\"",
    "\"at\"",
    "\"authorization\"",
    "\"avg\"",
    "\"begin\"",
    "\"between\"",
    "\"by\"",
    "\"cascade\"",
    "\"case\"",
    "\"check\"",
    "\"checkpoint\"",
    "\"close\"",
    "\"coalesce\"",
    "\"commit\"",
    "\"constraint\"",
    "\"continue\"",
    "\"count\"",
    "\"create\"",
    "\"current\"",
    "\"cursor\"",
    "\"database\"",
    "\"dbevent\"",
    "\"declare\"",
    "\"default\"",
    "\"delete\"",
    "\"desc\"",
    "\"distinct\"",
    "\"domain\"",
    "\"drop\"",
    "\"dump\"",
    "\"else\"",
    "\"end\"",
    "\"escape\"",
    "\"except\"",
    "\"exclusive\"",
    "\"exec\"",
    "\"execute\"",
    "\"exists\"",
    "\"fetch\"",
    "\"fillfactor\"",
    "\"for\"",
    "\"foreign\"",
    "\"from\"",
    "\"func\"",
    "\"function\"",
    "\"\\\\g\"",
    "\"goto\"",
    "\"grant\"",
    "\"group\"",
    "\"having\"",
    "\"if\"",
    "\"in\"",
    "\"index\"",
    "\"insert\"",
    "\"intersect\"",
    "\"integrity\"",
    "\"into\"",
    "\"is\"",
    "\"isolation\"",
    "\"join\"",
    "\"key\"",
    "\"kill\"",
    "\"level\"",
    "\"like\"",
    "\"load\"",
    "\"location\"",
    "\"max\"",
    "\"min\"",
    "\"modify\"",
    "\"no\"",
    "\"not\"",
    "\"null\"",
    "\"nullif\"",
    "\"of\"",
    "\"off\"",
    "\"on\"",
    "\"only\"",
    "\"open\"",
    "\"option\"",
    "\"or\"",
    "\"order\"",
    "\"out\"",
    "\"output\"",
    "\"partition\"",
    "\"perm\"",
    "\"permanent\"",
    "\"prepare\"",
    "\"primary\"",
    "\"privileges\"",
    "\"print\"",
    "\"procedure\"",
    "\"profile\"",
    "\"public\"",
    "\"read\"",
    "\"references\"",
    "\"remove\"",
    "\"reorganize\"",
    "\"return\"",
    "\"revoke\"",
    "\"role\"",
    "\"rollback\"",
    "\"rowcount\"",
    "\"rows\"",
    "\"rule\"",
    "\"save\"",
    "\"schema\"",
    "\"security_audit\"",
    "\"security_alarm\"",
    "\"select\"",
    "\"sequence\"",
    "\"session\"",
    "\"set\"",
    "\"shared\"",
    "\"some\"",
    "\"statistics\"",
    "\"sum\"",
    "\"synonym\"",
    "\"table\"",
    "\"temporary\"",
    "\"to\"",
    "\"transaction\"",
    "\"union\"",
    "\"unique\"",
    "\"unpartition\"",
    "\"update\"",
    "\"user\"",
    "\"using\"",
    "\"values\"",
    "\"varying\"",
    "\"view\"",
    "\"when\"",
    "\"where\"",
    "\"while\"",
    "\"with\"",
    "\"work\"",
    "\"$dba\"",
    "\"$ingres\"",
    "<INTEGER_LITERAL>",
    "<FLOATING_POINT_LITERAL>",
    "<EXPONENT>",
    "<SINGLE_STRING_LITERAL>",
    "<DOUBLE_STRING_LITERAL>",
    "<BINARY_LITERAL>",
    "<HEXDIGIT>",
    "<MONEY_LITERAL>",
    "<ID>",
    "<SQUARE_BRACKET_ID>",
    "<VAR_NAME_BODY>",
    "<VAR_NAME>",
    "<LABEL>",
    "<GLOBAL_VAR_NAME>",
    "<TEMP_TABLE_NAME>",
    "<LETTER>",
    "<DIGIT>",
    "<SYMBOL>",
    "<SPECSYMB>",
    "<DELIM_START>",
    "<DELIM_PART>",
    "<DELIM_IDENT>",
    "\"||\"",
    "\",\"",
    "\";\"",
    "\".\"",
    "\"%rowtype\"",
    "\"~\"",
    "\"<\"",
    "\"<=\"",
    "\">\"",
    "\">=\"",
    "\"=\"",
    "\"!=\"",
    "\"(+)\"",
    "\"(\"",
    "\")\"",
    "\"*\"",
    "\"/\"",
    "\"+\"",
    "\"-\"",
    "\"?\"",
    "\"*=\"",
    "\"=*\"",
    "\">>\"",
    "<UK_DOUBLE_PRECISION>",
    "<UK_NO_SCROLL>",
    "<UK_SEMI_SENSITIVE>",
    "<UK_VARCHAR_S>",
    "<UK_VARCHAR_S1>",
    "\":\"",
    "\"!\"",
    "\"!>\"",
    "\"!<\"",
    "\"<>\"",
    "\"|\"",
    "\"&\"",
    "\"^\"",
    "\"%\"",
  };

}
