###############################################################################
# Copyright (c) 2001, 2004, 2008 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License 2.0
# which accompanies this distribution, and is available at
# https://www.eclipse.org/legal/epl-2.0/
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################

pluginName = Eclipse Data Tools Platform Oracle Database Definition Plug-in
providerName = Eclipse Data Tools Platform

11ProductString = Oracle
11VersionString = 11

10ProductString = Oracle
10VersionString = 10

9ProductString = Oracle
9VersionString = 9

8ProductString = Oracle
8VersionString = 8

