###############################################################################
# Copyright (c) 2006, 2007 IBM Corporation and others.
# All rights reserved. This program and the accompanying materials
# are made available under the terms of the Eclipse Public License v1.0
# which accompanies this distribution, and is available at
# http://www.eclipse.org/legal/epl-v10.html
# 
# Contributors:
#     IBM Corporation - initial API and implementation
###############################################################################
pluginName=Eclipse Data Tools Platform Apache Derby UI Plug-in
providerName=Eclipse Data Tools Platform

DERBY_EMBEDDED_CONNECTION_PROFILE_WIZARD_NAME=Derby
DERBY_EMBEDDED_CONNECTION_PROFILE_WIZARD_DESCRIPTION = 创建 Derby 连接配置文件。
DERBY_EMBEDDED_DB_PROPERTY_PAGE_NAME=JDBC 连接属性

