# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.ASA.title = 新しい ASA 接続プロファイル
NewConnectionProfileWizard.ASIQ.title = 新しい ASIQ 接続プロファイル
NewConnectionProfileWizard.error.title = JDBC 接続プロファイルの新規作成エラー
NewConnectionProfileWizard.error.msg = JDBC 接続プロファイルの新規作成中に例外が発生しました。
NewConnectionProfileWizard.confirmation.title=確認
NewConnectionProfileWizard.confirmation.msg=データベース \"{1}\" の接続プロファイル \"{0}\" はすでに存在します。\n上書きしますか ?
								
								
JDBCASAPropertyWizardPage.title = ドライバと接続の詳細を指定
JDBCPropertyWizardPage.PingButton=
JDBCASAPropertyWizardPage.msg = ドロップダウンリストからドライバを選択し、接続用のログイン情報を指定してください。
JDBCASAPropertyWizardPage.driverCombo.label = ドロップダウンからドライバを選択 :
JDBCASAPropertyWizardPage.hostName.label = ホスト :
JDBCASAPropertyWizardPage.databaseName.label = データベース名 :
JDBCASAPropertyWizardPage.portNumber.label = ポート :
JDBCASAPropertyWizardPage.userName.label = ユーザ名 :
JDBCASAPropertyWizardPage.password.label = パスワード :
JDBCASAPropertyWizardPage.filterGroup.label = フィルタのプロパティ
JDBCASAPropertyWizardPage.catalog.label = カタログ :
JDBCASAPropertyWizardPage.schema.label = スキーマ :
JDBCASAPropertyWizardPage.PingButton=接続テスト
JDBCASAProfilePropertyPage.PingButton=接続テスト
JDBCASAPropertyWizardPage.procedureName.label = プロシージャ名 :
JDBCASAPropertyWizardPage.optionalProps.label = 接続プロパティ
JDBCASAPropertyWizardPage.summary.driverName.label = ドライバ名
JDBCASAPropertyWizardPage.summary.connProps.label = 接続プロパティ
JDBCASAPropertyWizardPage.summary.host.label = ホスト
JDBCASAPropertyWizardPage.summary.databaseName.label = データベース名
JDBCASAPropertyWizardPage.summary.port.label = ポート
JDBCASAPropertyWizardPage.summary.userName.label = ユーザ名
JDBCASAPropertyWizardPage.summary.password.label = パスワード
JDBCASAPropertyWizardPage.summary.driverClass.label = ドライバクラス
JDBCASAPropertyWizardPage.summary.catalog.label = カタログ
JDBCASAPropertyWizardPage.summary.schema.label = スキーマ
JDBCASAPropertyWizardPage.summary.procedureName.label = プロシージャ名
JDBCASAPropertyWizardPage.summary.url.label = URL

ASAWSMFConnection.error.DriverNotExist = ドライバがありません。
ASAWSMFConnection.error.EmptyJarList = ドライバ定義の jar リストが空です。

JDBCASAProfileTabs.errors.requiredHost = ホストを指定してください。
JDBCASAProfileTabs.errors.requiredPort = ポートを指定してください。
JDBCASAProfileTabs.errors.requiredPortValidNumber = ポートを有効な数値にしてください。
JDBCASAProfileTabs.otherPropertiesTab.commonOptions=APPLICATIONNAME=SYBASE WORKSPACE,CHARSET=UTF8,CONNECTION_FAILOVER=TRUE,SQLINITSTRING=SET QUOTED_IDENTIFIER ON,JCONNECT_VERSION=6,JCONNECT_VERSION=0

MultiASAWizardPage.title=複数のデータベースを公開している ASA サーバの確認 (オプション)
MultiASAWizardPage.description=ASA サーバで複数のデータベースを公開しているかどうかを確認します。複数を公開している場合は、プロファイルとして公開するデータベースを選択し、[複数のデータベースを確認する] をオンにします。
MultiASADialog.dialog.title=複数の ASA プロファイルの作成
MultiASADialog.dialog.message=ASA サーバで複数のデータベースを公開しているかどうかを確認します。複数を公開している場合は、プロファイルとして公開するデータベースを選択し、[複数のデータベースを確認する] をオンにします。
MultiASAWizardPage.OnlyOneDBMessage=公開されているデータベースは 1 つだけなので、追加の作業は不要です。
MultiASADialog.dialog.message.title=複数のデータベースを公開している ASA サーバの確認
MultiASAWizardPage.checkButton.label=複数のデータベースを確認する
MultiASAWizardPage.Label.ChooseDbs=プロファイルとして公開するデータベースの選択 :
MultiASAWizardPage.Error.title.CannotConnect=接続不可
MultiASAWizardPage.Error.msg.CannotConnect=プロファイルへの接続中にエラーが発生しました。プロパティのページに戻り、プロファイル情報を確認してください。
MultiASAWizardPage.selectAllButton.label=すべて選択
MultiASAWizardPage.deselectAllButton.label=すべて選択解除
MultiASAWizardPage.Summary.Label=選択済みのデータベース

ProfileASAMultiDBAction.error.failedprofileupdate = プロファイル ''{0}'' を更新できません。
ProfileASAMultiDBAction.error.title.profilealreadyexists=プロファイルはすでに存在します
ProfileASAMultiDBAction.msg.profilealreadyexists = ''{0}'' という名前のプロファイルはすでに存在しています。置き換えますか ? 


# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 新しい JDBC 接続プロファイル
NewConnectionProfileWizard.error.title = JDBC 接続プロファイルの新規作成エラー
NewConnectionProfileWizard.error.msg = JDBC 接続プロファイルの新規作成中に例外が発生しました。

JDBCPropertyWizardPage.title = ドライバと接続の詳細を指定
JDBCPropertyWizardPage.msg = ドロップダウンリストからドライバを選択し、接続用のログイン情報を指定してください。
JDBCPropertyWizardPage.driverCombo.label = ドロップダウンからドライバを選択 :
JDBCPropertyWizardPage.url.label = URL :
JDBCPropertyWizardPage.PingButton=接続テスト
JDBCPropertyWizardPage.userName.label = ユーザ名 :
JDBCPropertyWizardPage.password.label = パスワード :
JDBCPropertyWizardPage.persistpassword.label = パスワードの保存
JDBCPropertyWizardPage.filterGroup.label = オプションのフィルタのプロパティ
JDBCPropertyWizardPage.catalog.label = カタログ :
JDBCPropertyWizardPage.schema.label = スキーマ :
JDBCProfilePropertyPage.PingButton=接続テスト
JDBCPropertyWizardPage.procedureName.label = プロシージャ名 :
JDBCPropertyWizardPage.optionalProps.label = オプションプロパティ :
JDBCPropertyWizardPage.summary.driverName.label = ドライバ名
JDBCPropertyWizardPage.summary.connProps.label = 接続プロパティ
JDBCPropertyWizardPage.summary.userName.label = ユーザ名
JDBCPropertyWizardPage.summary.password.label = パスワード
JDBCPropertyWizardPage.summary.driverClass.label = ドライバクラス
JDBCPropertyWizardPage.summary.catalog.label = カタログ
JDBCPropertyWizardPage.summary.schema.label = スキーマ
JDBCPropertyWizardPage.summary.procedureName.label = プロシージャ名
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ ミリ秒
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=ログインのタイムアウトまであと 
JDBCConnectionUtils.AttemptToConnectMessage=接続中...
JDBCConnectionUtils.DBConnectAttemptJob=データベースへの接続を試行
JDBCConnectionUtils.ClassNotFoundStatus=クラスを読み込めません : 
JDBCConnectionUtils.ConnectionTimeoutMessage=接続がタイムアウトしました。

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = ドライバがありません。
JDBCConnection.error.EmptyJarList = ドライバ定義の jar リストが空です。

JDBCProfileTabs.tabs.label.connection = 接続(&C)
JDBCProfileTabs.tabs.label.filters = フィルタ(&F)
JDBCProfileTabs.tabs.label.other = その他のプロパティ(&P)
JDBCProfileTabs.errors.requiredURL = JDBC の URL を指定してください。
JDBCProfileTabs.errors.requiredUID = ユーザ名を指定してください。

# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 新しい JDBC 接続プロファイル
NewConnectionProfileWizard.error.title = JDBC 接続プロファイルの新規作成エラー
NewConnectionProfileWizard.error.msg = JDBC 接続プロファイルの新規作成中に例外が発生しました。

JDBCPropertyWizardPage.title = ドライバと接続の詳細を指定
JDBCPropertyWizardPage.msg = ドロップダウンリストからドライバを選択し、接続用のログイン情報を指定してください。
JDBCPropertyWizardPage.driverCombo.label = ドロップダウンからドライバを選択 :
JDBCPropertyWizardPage.url.label = URL :
JDBCPropertyWizardPage.PingButton=接続テスト
JDBCPropertyWizardPage.userName.label = ユーザ名 :
JDBCPropertyWizardPage.password.label = パスワード :
JDBCPropertyWizardPage.filterGroup.label = オプションのフィルタのプロパティ
JDBCPropertyWizardPage.catalog.label = カタログ :
JDBCPropertyWizardPage.schema.label = スキーマ :
JDBCProfilePropertyPage.PingButton=接続テスト
JDBCPropertyWizardPage.procedureName.label = プロシージャ名 :
JDBCPropertyWizardPage.optionalProps.label = オプションプロパティ :
JDBCPropertyWizardPage.summary.driverName.label = ドライバ名
JDBCPropertyWizardPage.summary.connProps.label = 接続プロパティ
JDBCPropertyWizardPage.summary.userName.label = ユーザ名
JDBCPropertyWizardPage.summary.password.label = パスワード
JDBCPropertyWizardPage.summary.driverClass.label = ドライバクラス
JDBCPropertyWizardPage.summary.catalog.label = カタログ
JDBCPropertyWizardPage.summary.schema.label = スキーマ
JDBCPropertyWizardPage.summary.procedureName.label = プロシージャ名
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ ミリ秒
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=ログインのタイムアウトまであと 
JDBCConnectionUtils.AttemptToConnectMessage=接続中...
JDBCConnectionUtils.DBConnectAttemptJob=データベースへの接続を試行
JDBCConnectionUtils.ClassNotFoundStatus=クラスを読み込めません : 
JDBCConnectionUtils.ConnectionTimeoutMessage=接続がタイムアウトしました。

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = ドライバがありません。
JDBCConnection.error.EmptyJarList = ドライバ定義の jar リストが空です。

JDBCProfileTabs.tabs.label.connection = 接続(&C)
JDBCProfileTabs.tabs.label.filters = フィルタ(&F)
JDBCProfileTabs.tabs.label.other = その他のプロパティ(&P)
JDBCProfileTabs.errors.requiredURL = JDBC の URL を指定してください。
JDBCProfileTabs.errors.requiredUID = ユーザ名を指定してください。
events.folder.name=イベント
webservices.folder.name=Web サービス
datatypes.folder.name=データ型
udt.folder.name=ユーザ定義のデータ型
udf.folder.name=ユーザ定義の関数

plugin_internal_error=内部エラーが発生しました。

ProxyTable.folder.name = プロキシテーブル
