# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.ASA.title = Nouveau profil de connexion ASA
NewConnectionProfileWizard.ASIQ.title = Nouveau profil de connexion ASIQ
NewConnectionProfileWizard.error.title = Erreur lors de la création d'un nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.msg = Une exception s'est produite lors de la création d'un nouveau profil de connexion JDBC.
NewConnectionProfileWizard.confirmation.title=Confirmation
NewConnectionProfileWizard.confirmation.msg=Le profil de connexion \"{0}\" pour la base de données \"{1}\" existe déjà. \nVoulez-vous l'écraser ?
								
								
JDBCASAPropertyWizardPage.title = Spécifier un pilote et les informations de connexion
JDBCPropertyWizardPage.PingButton=
JDBCASAPropertyWizardPage.msg = Dans le menu déroulant, sélectionner un pilote et lui fournir les informations de connexion.
JDBCASAPropertyWizardPage.driverCombo.label = Sélectionner un pilote dans le menu déroulant :
JDBCASAPropertyWizardPage.hostName.label = Hôte :
JDBCASAPropertyWizardPage.databaseName.label = Nom de la base de données :
JDBCASAPropertyWizardPage.portNumber.label = Port :
JDBCASAPropertyWizardPage.userName.label = Nom d'utilisateur :
JDBCASAPropertyWizardPage.password.label = Mot de passe :
JDBCASAPropertyWizardPage.filterGroup.label = Propriétés de filtre
JDBCASAPropertyWizardPage.catalog.label = Catalogue :
JDBCASAPropertyWizardPage.schema.label = Schéma :
JDBCASAPropertyWizardPage.PingButton=Connexion test
JDBCASAProfilePropertyPage.PingButton=Connexion test
JDBCASAPropertyWizardPage.procedureName.label = Nom de procédure :
JDBCASAPropertyWizardPage.optionalProps.label = Propriétés de connexion
JDBCASAPropertyWizardPage.summary.driverName.label = Nom du pilote
JDBCASAPropertyWizardPage.summary.connProps.label = Propriétés de connexion
JDBCASAPropertyWizardPage.summary.host.label = Hôte
JDBCASAPropertyWizardPage.summary.databaseName.label = Nom de la base de données
JDBCASAPropertyWizardPage.summary.port.label = Port
JDBCASAPropertyWizardPage.summary.userName.label = Nom d'utilisateur
JDBCASAPropertyWizardPage.summary.password.label = Mot de passe
JDBCASAPropertyWizardPage.summary.driverClass.label = Classe de pilote
JDBCASAPropertyWizardPage.summary.catalog.label = Catalogue
JDBCASAPropertyWizardPage.summary.schema.label = Schéma
JDBCASAPropertyWizardPage.summary.procedureName.label = Nom de procédure
JDBCASAPropertyWizardPage.summary.url.label = URL

ASAWSMFConnection.error.DriverNotExist = Le pilote n'existe pas.
ASAWSMFConnection.error.EmptyJarList = Liste jar vide dans la définition de pilote.

JDBCASAProfileTabs.errors.requiredHost = Hôte requis
JDBCASAProfileTabs.errors.requiredPort = Port requis
JDBCASAProfileTabs.errors.requiredPortValidNumber = Le port doit être un nombre valide
JDBCASAProfileTabs.otherPropertiesTab.commonOptions=APPLICATIONNAME=SYBASE WORKSPACE,CHARSET=UTF8,CONNECTION_FAILOVER=TRUE,SQLINITSTRING=SET QUOTED_IDENTIFIER ON,JCONNECT_VERSION=6,JCONNECT_VERSION=0

MultiASAWizardPage.title=Rechercher un serveur ASA présentant plusieurs bases de données (facultatif)
MultiASAWizardPage.description=Vérifiez si le serveur ASA présente plus d'une base de données.Le cas échéant, sélectionnez les bases de données à présenter comme des profils. Cliquez sur 'Rechercher des bases de données multiples' pour commencer.
MultiASADialog.dialog.title=Créer des profils ASA multiples
MultiASADialog.dialog.message=Vérifiez si le serveur ASA présente plus d'une base de données.Le cas échéant, sélectionnez les bases de données à présenter comme des profils. Cliquez sur 'Rechercher des bases de données multiples' pour commencer.
MultiASAWizardPage.OnlyOneDBMessage=Dans la mesure où une seule base de données est présentée, aucune autre opération n'est requise.
MultiASADialog.dialog.message.title=Rechercher un serveur ASA présentant plusieurs bases de données
MultiASAWizardPage.checkButton.label=Rechercher des bases de données multiples
MultiASAWizardPage.Label.ChooseDbs=Sélectionner les bases de données à présenter comme des profils :
MultiASAWizardPage.Error.title.CannotConnect=Impossible de se connecter
MultiASAWizardPage.Error.msg.CannotConnect=Une erreur s'est produite lors de la connexion au profil. Veuillez revenir à la page des propriétés et vérifier les informations du profil.
MultiASAWizardPage.selectAllButton.label=Sélectionner tout
MultiASAWizardPage.deselectAllButton.label=Désélectionner tout
MultiASAWizardPage.Summary.Label=Base(s) de données sélectionnée(s)

ProfileASAMultiDBAction.error.failedprofileupdate = Echec de mise à jour du profil ''{0}''.
ProfileASAMultiDBAction.error.title.profilealreadyexists=Le profil existe déjà
ProfileASAMultiDBAction.msg.profilealreadyexists = Un profil existe déjà sous le nom ''{0}''. Voulez-vous le remplacer ? 


# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.title = Erreur lors de la création d'un nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.msg = Une exception s'est produite lors de la création d'un nouveau profil de connexion JDBC.

JDBCPropertyWizardPage.title = Spécifier un pilote et les informations de connexion
JDBCPropertyWizardPage.msg = Dans le menu déroulant, sélectionner un pilote et lui fournir les informations de connexion.
JDBCPropertyWizardPage.driverCombo.label = Sélectionner un pilote dans le menu déroulant :
JDBCPropertyWizardPage.url.label = URL :
JDBCPropertyWizardPage.PingButton=Connexion test
JDBCPropertyWizardPage.userName.label = Nom d'utilisateur :
JDBCPropertyWizardPage.password.label = Mot de passe :
JDBCPropertyWizardPage.persistpassword.label = Enregistrer mot de passe
JDBCPropertyWizardPage.filterGroup.label = Propriétés de filtre facultatives
JDBCPropertyWizardPage.catalog.label = Catalogue :
JDBCPropertyWizardPage.schema.label = Schéma :
JDBCProfilePropertyPage.PingButton=Connexion test
JDBCPropertyWizardPage.procedureName.label = Nom de procédure :
JDBCPropertyWizardPage.optionalProps.label = Propriétés facultatives :
JDBCPropertyWizardPage.summary.driverName.label = Nom du pilote
JDBCPropertyWizardPage.summary.connProps.label = Propriétés de connexion
JDBCPropertyWizardPage.summary.userName.label = Nom d'utilisateur
JDBCPropertyWizardPage.summary.password.label = Mot de passe
JDBCPropertyWizardPage.summary.driverClass.label = Classe de pilote
JDBCPropertyWizardPage.summary.catalog.label = Catalogue
JDBCPropertyWizardPage.summary.schema.label = Schéma
JDBCPropertyWizardPage.summary.procedureName.label = Nom de procédure
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Délai de connexion 
JDBCConnectionUtils.AttemptToConnectMessage=Tentative de connexion...
JDBCConnectionUtils.DBConnectAttemptJob=Tentative de connexion à la base de données
JDBCConnectionUtils.ClassNotFoundStatus=Impossible de charger la classe : 
JDBCConnectionUtils.ConnectionTimeoutMessage=Délai de connexion dépassé.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = Le pilote n'existe pas.
JDBCConnection.error.EmptyJarList = Liste jar vide dans la définition de pilote.

JDBCProfileTabs.tabs.label.connection = &Connexion
JDBCProfileTabs.tabs.label.filters = &Filtres
JDBCProfileTabs.tabs.label.other = Autres &propriétés
JDBCProfileTabs.errors.requiredURL = URL JDBC requise
JDBCProfileTabs.errors.requiredUID = Nom d'utilisateur requis

# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.title = Erreur lors de la création d'un nouveau profil de connexion JDBC
NewConnectionProfileWizard.error.msg = Une exception s'est produite lors de la création d'un nouveau profil de connexion JDBC.

JDBCPropertyWizardPage.title = Spécifier un pilote et les informations de connexion
JDBCPropertyWizardPage.msg = Dans le menu déroulant, sélectionner un pilote et lui fournir les informations de connexion.
JDBCPropertyWizardPage.driverCombo.label = Sélectionner un pilote dans le menu déroulant :
JDBCPropertyWizardPage.url.label = URL :
JDBCPropertyWizardPage.PingButton=Connexion test
JDBCPropertyWizardPage.userName.label = Nom d'utilisateur :
JDBCPropertyWizardPage.password.label = Mot de passe :
JDBCPropertyWizardPage.filterGroup.label = Propriétés de filtre facultatives
JDBCPropertyWizardPage.catalog.label = Catalogue :
JDBCPropertyWizardPage.schema.label = Schéma :
JDBCProfilePropertyPage.PingButton=Connexion test
JDBCPropertyWizardPage.procedureName.label = Nom de procédure :
JDBCPropertyWizardPage.optionalProps.label = Propriétés facultatives :
JDBCPropertyWizardPage.summary.driverName.label = Nom du pilote
JDBCPropertyWizardPage.summary.connProps.label = Propriétés de connexion
JDBCPropertyWizardPage.summary.userName.label = Nom d'utilisateur
JDBCPropertyWizardPage.summary.password.label = Mot de passe
JDBCPropertyWizardPage.summary.driverClass.label = Classe de pilote
JDBCPropertyWizardPage.summary.catalog.label = Catalogue
JDBCPropertyWizardPage.summary.schema.label = Schéma
JDBCPropertyWizardPage.summary.procedureName.label = Nom de procédure
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Délai de connexion 
JDBCConnectionUtils.AttemptToConnectMessage=Tentative de connexion...
JDBCConnectionUtils.DBConnectAttemptJob=Tentative de connexion à la base de données
JDBCConnectionUtils.ClassNotFoundStatus=Impossible de charger la classe : 
JDBCConnectionUtils.ConnectionTimeoutMessage=Délai de connexion dépassé.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = Le pilote n'existe pas.
JDBCConnection.error.EmptyJarList = Liste jar vide dans la définition de pilote.

JDBCProfileTabs.tabs.label.connection = &Connexion
JDBCProfileTabs.tabs.label.filters = &Filtres
JDBCProfileTabs.tabs.label.other = Autres &propriétés
JDBCProfileTabs.errors.requiredURL = URL JDBC requise
JDBCProfileTabs.errors.requiredUID = Nom d'utilisateur requis
events.folder.name=Evénements
webservices.folder.name=Services Web
datatypes.folder.name=Types de données
udt.folder.name=Types définis par l'utilisateur
udf.folder.name=Fonctions définies par l'utilisateur

plugin_internal_error=Une erreur interne s'est produite

ProxyTable.folder.name = Tables proxy
