# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.ASA.title = Nuevo perfil de conexión ASA
NewConnectionProfileWizard.ASIQ.title = Nuevo perfil de conexión ASIQ
NewConnectionProfileWizard.error.title = Error al crear un nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.msg = Se ha producido una excepción al crear un nuevo perfil de conexión JDBC.
NewConnectionProfileWizard.confirmation.title=Confirmación
NewConnectionProfileWizard.confirmation.msg=El perfil de conexión \"{0}\" para la base de datos \"{1}\" ya existe. \n¿Desea sobrescribirlo?
								
								
JDBCASAPropertyWizardPage.title = Especifique un controlador y los detalles de conexión
JDBCPropertyWizardPage.PingButton=
JDBCASAPropertyWizardPage.msg = Seleccione un controlador del menú desplegable y proporcione los detalles de conexión.
JDBCASAPropertyWizardPage.driverCombo.label = Seleccione un controlador del menú desplegable:
JDBCASAPropertyWizardPage.hostName.label = Anfitrión:
JDBCASAPropertyWizardPage.databaseName.label = Nombre de la base de datos:
JDBCASAPropertyWizardPage.portNumber.label = Puerto:
JDBCASAPropertyWizardPage.userName.label = Nombre de usuario:
JDBCASAPropertyWizardPage.password.label = Contraseña:
JDBCASAPropertyWizardPage.filterGroup.label = Propiedades del filtro
JDBCASAPropertyWizardPage.catalog.label = Catálogo:
JDBCASAPropertyWizardPage.schema.label = Esquema:
JDBCASAPropertyWizardPage.PingButton=Probar conexión
JDBCASAProfilePropertyPage.PingButton=Probar conexión
JDBCASAPropertyWizardPage.procedureName.label = Nombre del procedimiento:
JDBCASAPropertyWizardPage.optionalProps.label = Propiedades de conexión
JDBCASAPropertyWizardPage.summary.driverName.label = Nombre de controlador
JDBCASAPropertyWizardPage.summary.connProps.label = Propiedades de conexión
JDBCASAPropertyWizardPage.summary.host.label = Anfitrión
JDBCASAPropertyWizardPage.summary.databaseName.label = Nombre de la base de datos
JDBCASAPropertyWizardPage.summary.port.label = Puerto
JDBCASAPropertyWizardPage.summary.userName.label = Nombre de usuario
JDBCASAPropertyWizardPage.summary.password.label = Contraseña
JDBCASAPropertyWizardPage.summary.driverClass.label = Clase de controlador
JDBCASAPropertyWizardPage.summary.catalog.label = Catálogo
JDBCASAPropertyWizardPage.summary.schema.label = Esquema
JDBCASAPropertyWizardPage.summary.procedureName.label = Nombre del procedimiento
JDBCASAPropertyWizardPage.summary.url.label = URL

ASAWSMFConnection.error.DriverNotExist = El controlador no existe.
ASAWSMFConnection.error.EmptyJarList = Lista jar vacía en la definición de controlador.

JDBCASAProfileTabs.errors.requiredHost = Anfitrión requerido
JDBCASAProfileTabs.errors.requiredPort = Puerto requerido
JDBCASAProfileTabs.errors.requiredPortValidNumber = El puerto debe ser un número válido
JDBCASAProfileTabs.otherPropertiesTab.commonOptions=APPLICATIONNAME=SYBASE WORKSPACE,CHARSET=UTF8,CONNECTION_FAILOVER=TRUE,SQLINITSTRING=SET QUOTED_IDENTIFIER ON,JCONNECT_VERSION=6,JCONNECT_VERSION=0

MultiASAWizardPage.title=Comprobación de servidor ASA de varias bases de datos (opcional)
MultiASAWizardPage.description=Compruebe si el servidor ASA expone más de una base de datos. Si es así, seleccione las bases de datos que desee que se expongan como perfiles. Haga clic en 'Comprobar varias bases de datos' para comenzar.
MultiASADialog.dialog.title=Crear varios perfiles ASA
MultiASADialog.dialog.message=Compruebe si el servidor ASA expone más de una base de datos. Si es así, seleccione las bases de datos que desee que se expongan como perfiles. Haga clic en 'Comprobar varias bases de datos' para comenzar.
MultiASAWizardPage.OnlyOneDBMessage=Dado que sólo se expone una base de datos, no es necesario realizar más trabajo.
MultiASADialog.dialog.message.title=Comprobación de servidor ASA de varias bases de datos
MultiASAWizardPage.checkButton.label=Comprobar varias bases de datos
MultiASAWizardPage.Label.ChooseDbs=Seleccione las bases de datos que desee exponer como perfiles:
MultiASAWizardPage.Error.title.CannotConnect=No se puede conectar
MultiASAWizardPage.Error.msg.CannotConnect=Se ha producido un error al conectarse al perfil. Vuelva a la página de propiedades y compruebe la información del perfil.
MultiASAWizardPage.selectAllButton.label=Seleccionar todo
MultiASAWizardPage.deselectAllButton.label=Anular la selección de todo
MultiASAWizardPage.Summary.Label=Base(s) de datos seleccionada(s)

ProfileASAMultiDBAction.error.failedprofileupdate = Error al actualizar el perfil ''{0}''.
ProfileASAMultiDBAction.error.title.profilealreadyexists=El perfil ya existe
ProfileASAMultiDBAction.msg.profilealreadyexists = Ya existe un perfil con el nombre ''{0}''. ¿Desea reemplazarlo? 


# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.title = Error al crear un nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.msg = Se ha producido una excepción al crear un nuevo perfil de conexión JDBC.

JDBCPropertyWizardPage.title = Especifique un controlador y los detalles de conexión
JDBCPropertyWizardPage.msg = Seleccione un controlador del menú desplegable y proporcione los detalles de conexión.
JDBCPropertyWizardPage.driverCombo.label = Seleccione un controlador del menú desplegable:
JDBCPropertyWizardPage.url.label = URL:
JDBCPropertyWizardPage.PingButton=Probar conexión
JDBCPropertyWizardPage.userName.label = Nombre de usuario:
JDBCPropertyWizardPage.password.label = Contraseña:
JDBCPropertyWizardPage.persistpassword.label = Guardar contraseña
JDBCPropertyWizardPage.filterGroup.label = Propiedades opcionales de filtro
JDBCPropertyWizardPage.catalog.label = Catálogo:
JDBCPropertyWizardPage.schema.label = Esquema:
JDBCProfilePropertyPage.PingButton=Probar conexión
JDBCPropertyWizardPage.procedureName.label = Nombre del procedimiento:
JDBCPropertyWizardPage.optionalProps.label = Propiedades opcionales:
JDBCPropertyWizardPage.summary.driverName.label = Nombre de controlador
JDBCPropertyWizardPage.summary.connProps.label = Propiedades de conexión
JDBCPropertyWizardPage.summary.userName.label = Nombre de usuario
JDBCPropertyWizardPage.summary.password.label = Contraseña
JDBCPropertyWizardPage.summary.driverClass.label = Clase de controlador
JDBCPropertyWizardPage.summary.catalog.label = Catálogo
JDBCPropertyWizardPage.summary.schema.label = Esquema
JDBCPropertyWizardPage.summary.procedureName.label = Nombre del procedimiento
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milésimas (s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Límite de tiempo de conexión en 
JDBCConnectionUtils.AttemptToConnectMessage=Intentando conectarse...
JDBCConnectionUtils.DBConnectAttemptJob=Intento de conexión a la base de datos
JDBCConnectionUtils.ClassNotFoundStatus=No se ha podido cargar la clase: 
JDBCConnectionUtils.ConnectionTimeoutMessage=Se ha alcanzado el límite de tiempo de la conexión.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = El controlador no existe.
JDBCConnection.error.EmptyJarList = Lista jar vacía en la definición de controlador.

JDBCProfileTabs.tabs.label.connection = &Conexión
JDBCProfileTabs.tabs.label.filters = &Filtros
JDBCProfileTabs.tabs.label.other = Otras &propiedades
JDBCProfileTabs.errors.requiredURL = URL de JDBC requerido
JDBCProfileTabs.errors.requiredUID = Nombre de usuario requerido

# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = Nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.title = Error al crear un nuevo perfil de conexión JDBC
NewConnectionProfileWizard.error.msg = Se ha producido una excepción al crear un nuevo perfil de conexión JDBC.

JDBCPropertyWizardPage.title = Especifique un controlador y los detalles de conexión
JDBCPropertyWizardPage.msg = Seleccione un controlador del menú desplegable y proporcione los detalles de conexión.
JDBCPropertyWizardPage.driverCombo.label = Seleccione un controlador del menú desplegable:
JDBCPropertyWizardPage.url.label = URL:
JDBCPropertyWizardPage.PingButton=Probar conexión
JDBCPropertyWizardPage.userName.label = Nombre de usuario:
JDBCPropertyWizardPage.password.label = Contraseña:
JDBCPropertyWizardPage.filterGroup.label = Propiedades opcionales de filtro
JDBCPropertyWizardPage.catalog.label = Catálogo:
JDBCPropertyWizardPage.schema.label = Esquema:
JDBCProfilePropertyPage.PingButton=Probar conexión
JDBCPropertyWizardPage.procedureName.label = Nombre del procedimiento:
JDBCPropertyWizardPage.optionalProps.label = Propiedades opcionales:
JDBCPropertyWizardPage.summary.driverName.label = Nombre de controlador
JDBCPropertyWizardPage.summary.connProps.label = Propiedades de conexión
JDBCPropertyWizardPage.summary.userName.label = Nombre de usuario
JDBCPropertyWizardPage.summary.password.label = Contraseña
JDBCPropertyWizardPage.summary.driverClass.label = Clase de controlador
JDBCPropertyWizardPage.summary.catalog.label = Catálogo
JDBCPropertyWizardPage.summary.schema.label = Esquema
JDBCPropertyWizardPage.summary.procedureName.label = Nombre del procedimiento
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milésimas (s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=Límite de tiempo de conexión en 
JDBCConnectionUtils.AttemptToConnectMessage=Intentando conectarse...
JDBCConnectionUtils.DBConnectAttemptJob=Intento de conexión a la base de datos
JDBCConnectionUtils.ClassNotFoundStatus=No se ha podido cargar la clase: 
JDBCConnectionUtils.ConnectionTimeoutMessage=Se ha alcanzado el límite de tiempo de la conexión.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = El controlador no existe.
JDBCConnection.error.EmptyJarList = Lista jar vacía en la definición de controlador.

JDBCProfileTabs.tabs.label.connection = &Conexión
JDBCProfileTabs.tabs.label.filters = &Filtros
JDBCProfileTabs.tabs.label.other = Otras &propiedades
JDBCProfileTabs.errors.requiredURL = URL de JDBC requerido
JDBCProfileTabs.errors.requiredUID = Nombre de usuario requerido
events.folder.name=Eventos
webservices.folder.name=Servicios web
datatypes.folder.name=Tipos de datos
udt.folder.name=Tipos definidos por el usuario
udf.folder.name=Funciones definidas por el usuario

plugin_internal_error=Se ha producido un error interno

ProxyTable.folder.name = Tablas de proxy
