# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.ASA.title = 새 ASA 연결 프로필
NewConnectionProfileWizard.ASIQ.title = 새 ASIQ 연결 프로필
NewConnectionProfileWizard.error.title = 새 JDBC 연결 프로필 생성 중 오류 발생
NewConnectionProfileWizard.error.msg = 새 JDBC 연결 프로필을 생성하는 중 예외가 발생했습니다.
NewConnectionProfileWizard.confirmation.title=확인
NewConnectionProfileWizard.confirmation.msg=데이터베이스 \"{1}\"의 연결 프로필 \"{0}\"이(가) 이미 있습니다. \n덮어쓰시겠습니까?
								
								
JDBCASAPropertyWizardPage.title = 드라이버 및 연결 상세 정보 지정
JDBCPropertyWizardPage.PingButton=
JDBCASAPropertyWizardPage.msg = 드롭다운에서 드라이버를 선택하고 연결 로그인 정보를 제공합니다.
JDBCASAPropertyWizardPage.driverCombo.label = 드롭다운에서 드라이버를 선택하십시오.
JDBCASAPropertyWizardPage.hostName.label = 호스트:
JDBCASAPropertyWizardPage.databaseName.label = 데이터베이스 이름:
JDBCASAPropertyWizardPage.portNumber.label = 포트:
JDBCASAPropertyWizardPage.userName.label = 사용자 이름:
JDBCASAPropertyWizardPage.password.label = 암호:
JDBCASAPropertyWizardPage.filterGroup.label = 필터 속성
JDBCASAPropertyWizardPage.catalog.label = 카탈로그:
JDBCASAPropertyWizardPage.schema.label = 스키마:
JDBCASAPropertyWizardPage.PingButton=연결 테스트
JDBCASAProfilePropertyPage.PingButton=연결 테스트
JDBCASAPropertyWizardPage.procedureName.label = 프로시저 이름:
JDBCASAPropertyWizardPage.optionalProps.label = 연결 속성
JDBCASAPropertyWizardPage.summary.driverName.label = 드라이버 이름
JDBCASAPropertyWizardPage.summary.connProps.label = 연결 속성
JDBCASAPropertyWizardPage.summary.host.label = 호스트
JDBCASAPropertyWizardPage.summary.databaseName.label = 데이터베이스 이름
JDBCASAPropertyWizardPage.summary.port.label = 포트 
JDBCASAPropertyWizardPage.summary.userName.label = 사용자 이름:
JDBCASAPropertyWizardPage.summary.password.label = 암호
JDBCASAPropertyWizardPage.summary.driverClass.label = 드라이버 클래스
JDBCASAPropertyWizardPage.summary.catalog.label = 카탈로그
JDBCASAPropertyWizardPage.summary.schema.label = 스키마
JDBCASAPropertyWizardPage.summary.procedureName.label = 프로시저 이름
JDBCASAPropertyWizardPage.summary.url.label = URL

ASAWSMFConnection.error.DriverNotExist = 드라이버가 없습니다.
ASAWSMFConnection.error.EmptyJarList = 드라이버 정의에서 jar 목록이 비어 있습니다.

JDBCASAProfileTabs.errors.requiredHost = 호스트 필요
JDBCASAProfileTabs.errors.requiredPort = 포트 필요
JDBCASAProfileTabs.errors.requiredPortValidNumber = 포트는 유효한 숫자여야 합니다.
JDBCASAProfileTabs.otherPropertiesTab.commonOptions=APPLICATIONNAME=SYBASE WORKSPACE,CHARSET=UTF8,CONNECTION_FAILOVER=TRUE,SQLINITSTRING=SET QUOTED_IDENTIFIER ON,JCONNECT_VERSION=6,JCONNECT_VERSION=0

MultiASAWizardPage.title=여러 데이터베이스 ASA 서버 검사(옵션)
MultiASAWizardPage.description=ASA 서버가 하나 이상의 데이터베이스를 노출하는지 검사합니다. 노출되는 경우 프로필로 노출할 데이터베이스를 선택하십시오. 시작하려면 '여러 데이터베이스 검사'를 클릭하십시오.
MultiASADialog.dialog.title=여러 ASA 프로필 생성
MultiASADialog.dialog.message=ASA 서버가 하나 이상의 데이터베이스를 노출하는지 검사합니다. 노출되는 경우 프로필로 노출할 데이터베이스를 선택하십시오. 시작하려면 '여러 데이터베이스 검사'를 클릭하십시오.
MultiASAWizardPage.OnlyOneDBMessage=데이터베이스가 하나만 노출되었으므로 필요한 추가 작업은 없습니다.
MultiASADialog.dialog.message.title=여러 데이터베이스 ASA 서버 검사
MultiASAWizardPage.checkButton.label=여러 데이터베이스 검사
MultiASAWizardPage.Label.ChooseDbs=프로필로 노출할 데이터베이스를 선택하십시오.
MultiASAWizardPage.Error.title.CannotConnect=연결할 수 없습니다.
MultiASAWizardPage.Error.msg.CannotConnect=해당 프로필로 연결하는 중 문제가 발생했습니다. 속성 페이지로 돌아가서 프로필 정보를 확인하십시오.
MultiASAWizardPage.selectAllButton.label=모두 선택
MultiASAWizardPage.deselectAllButton.label=모두 선택 취소
MultiASAWizardPage.Summary.Label=선택된 데이터베이스

ProfileASAMultiDBAction.error.failedprofileupdate = 프로필 ''{0}''을(를) 업데이트하지 못했습니다.
ProfileASAMultiDBAction.error.title.profilealreadyexists=프로필이 이미 있습니다.
ProfileASAMultiDBAction.msg.profilealreadyexists = 이름이 ''{0}''인 프로필이 이미 있습니다. 바꾸시겠습니까? 


# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 새 JDBC 연결 프로필
NewConnectionProfileWizard.error.title = 새 JDBC 연결 프로필 생성 중 오류 발생
NewConnectionProfileWizard.error.msg = 새 JDBC 연결 프로필을 생성하는 중 예외가 발생했습니다.

JDBCPropertyWizardPage.title = 드라이버 및 연결 상세 정보 지정
JDBCPropertyWizardPage.msg = 드롭다운에서 드라이버를 선택하고 연결 로그인 정보를 제공합니다.
JDBCPropertyWizardPage.driverCombo.label = 드롭다운에서 드라이버를 선택하십시오.
JDBCPropertyWizardPage.url.label = URL:
JDBCPropertyWizardPage.PingButton=연결 테스트
JDBCPropertyWizardPage.userName.label = 사용자 이름:
JDBCPropertyWizardPage.password.label = 암호:
JDBCPropertyWizardPage.persistpassword.label = 암호 저장
JDBCPropertyWizardPage.filterGroup.label = 옵션 필터 속성
JDBCPropertyWizardPage.catalog.label = 카탈로그:
JDBCPropertyWizardPage.schema.label = 스키마:
JDBCProfilePropertyPage.PingButton=연결 테스트
JDBCPropertyWizardPage.procedureName.label = 프로시저 이름:
JDBCPropertyWizardPage.optionalProps.label = 옵션 속성:
JDBCPropertyWizardPage.summary.driverName.label = 드라이버 이름
JDBCPropertyWizardPage.summary.connProps.label = 연결 속성
JDBCPropertyWizardPage.summary.userName.label = 사용자 이름:
JDBCPropertyWizardPage.summary.password.label = 암호
JDBCPropertyWizardPage.summary.driverClass.label = 드라이버 클래스
JDBCPropertyWizardPage.summary.catalog.label = 카탈로그
JDBCPropertyWizardPage.summary.schema.label = 스키마
JDBCPropertyWizardPage.summary.procedureName.label = 프로시저 이름
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=로그인 제한 시간 
JDBCConnectionUtils.AttemptToConnectMessage=연결을 시도하는 중...
JDBCConnectionUtils.DBConnectAttemptJob=데이터베이스 연결 시도
JDBCConnectionUtils.ClassNotFoundStatus=클래스를 로드할 수 없습니다. 
JDBCConnectionUtils.ConnectionTimeoutMessage=연결 제한 시간을 초과했습니다.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = 드라이버가 없습니다.
JDBCConnection.error.EmptyJarList = 드라이버 정의에서 jar 목록이 비어 있습니다.

JDBCProfileTabs.tabs.label.connection = 연결(&C)
JDBCProfileTabs.tabs.label.filters = 필터(&F)
JDBCProfileTabs.tabs.label.other = 기타 속성(&P)
JDBCProfileTabs.errors.requiredURL = JDBC URL 필요
JDBCProfileTabs.errors.requiredUID = 사용자 이름 필요

# package: com.sybase.suade.servers.sample.jdbc
NewConnectionProfileWizard.title = 새 JDBC 연결 프로필
NewConnectionProfileWizard.error.title = 새 JDBC 연결 프로필 생성 중 오류 발생
NewConnectionProfileWizard.error.msg = 새 JDBC 연결 프로필을 생성하는 중 예외가 발생했습니다.

JDBCPropertyWizardPage.title = 드라이버 및 연결 상세 정보 지정
JDBCPropertyWizardPage.msg = 드롭다운에서 드라이버를 선택하고 연결 로그인 정보를 제공합니다.
JDBCPropertyWizardPage.driverCombo.label = 드롭다운에서 드라이버를 선택하십시오.
JDBCPropertyWizardPage.url.label = URL:
JDBCPropertyWizardPage.PingButton=연결 테스트
JDBCPropertyWizardPage.userName.label = 사용자 이름:
JDBCPropertyWizardPage.password.label = 암호:
JDBCPropertyWizardPage.filterGroup.label = 옵션 필터 속성
JDBCPropertyWizardPage.catalog.label = 카탈로그:
JDBCPropertyWizardPage.schema.label = 스키마:
JDBCProfilePropertyPage.PingButton=연결 테스트
JDBCPropertyWizardPage.procedureName.label = 프로시저 이름:
JDBCPropertyWizardPage.optionalProps.label = 옵션 속성:
JDBCPropertyWizardPage.summary.driverName.label = 드라이버 이름
JDBCPropertyWizardPage.summary.connProps.label = 연결 속성
JDBCPropertyWizardPage.summary.userName.label = 사용자 이름:
JDBCPropertyWizardPage.summary.password.label = 암호
JDBCPropertyWizardPage.summary.driverClass.label = 드라이버 클래스
JDBCPropertyWizardPage.summary.catalog.label = 카탈로그
JDBCPropertyWizardPage.summary.schema.label = 스키마
JDBCPropertyWizardPage.summary.procedureName.label = 프로시저 이름
JDBCPropertyWizardPage.summary.url.label = URL

JDBCConnectionUtils.Milliseconds=\ milli(s)
JDBCConnectionUtils.StatusTitle=JDBCConnectionUtils
JDBCConnectionUtils.TimeoutInXMilliSecondsMsg=로그인 제한 시간 
JDBCConnectionUtils.AttemptToConnectMessage=연결을 시도하는 중...
JDBCConnectionUtils.DBConnectAttemptJob=데이터베이스 연결 시도
JDBCConnectionUtils.ClassNotFoundStatus=클래스를 로드할 수 없습니다. 
JDBCConnectionUtils.ConnectionTimeoutMessage=연결 제한 시간을 초과했습니다.

JDBCConnection.technologyName = JDBC
JDBCConnection.error.DriverNotExist = 드라이버가 없습니다.
JDBCConnection.error.EmptyJarList = 드라이버 정의에서 jar 목록이 비어 있습니다.

JDBCProfileTabs.tabs.label.connection = 연결(&C)
JDBCProfileTabs.tabs.label.filters = 필터(&F)
JDBCProfileTabs.tabs.label.other = 기타 속성(&P)
JDBCProfileTabs.errors.requiredURL = JDBC URL 필요
JDBCProfileTabs.errors.requiredUID = 사용자 이름 필요
events.folder.name=이벤트
webservices.folder.name=웹 서비스
datatypes.folder.name=데이터 형식
udt.folder.name=사용자 정의 형식
udf.folder.name=사용자 정의 기능

plugin_internal_error=내부 오류 발생

ProxyTable.folder.name = 프록시 테이블
