DRIVER_CLASS_PROPERTY_NAME=Classe de pilote
VENDOR_PROPERTY_NAME=Vendeur
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Nom de la base de données
CONNECTION_URL_PROPERTY_NAME=URL de connexion
USER_ID_PROPERTY_NAME=ID utilisateur
PASSWORD_PROPERTY_NAME=Mot de passe

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB UI Enablement Plug-in
profile.page.name = Propriétés de profil HSQLDB

connection.profile.newwizard = HSQLDB
connection.profile.newwizard.description = Créer un profil de connexion HSQLDB.
