DRIVER_CLASS_PROPERTY_NAME=Clase de controlador
VENDOR_PROPERTY_NAME=Proveedor
VERSION_PROPERTY_NAME=Versión
DATABASE_NAME_PROPERTY_NAME=Nombre de base de datos
CONNECTION_URL_PROPERTY_NAME=URL de conexión
USER_ID_PROPERTY_NAME=Identificador de usuario
PASSWORD_PROPERTY_NAME=Contraseña

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB UI Enablement Plug-in
profile.page.name = Propiedades de perfil de HSQLDB

connection.profile.newwizard = HSQLDB
connection.profile.newwizard.description = Crear un perfil de conexión HSQLDB 
