DRIVER_CLASS_PROPERTY_NAME=드라이버 클래스
VENDOR_PROPERTY_NAME=공급업체
VERSION_PROPERTY_NAME=버전
DATABASE_NAME_PROPERTY_NAME=데이터베이스 이름
CONNECTION_URL_PROPERTY_NAME=연결 URL
USER_ID_PROPERTY_NAME=사용자 ID
PASSWORD_PROPERTY_NAME=암호

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB UI Enablement Plug-in
profile.page.name = HSQLDB 프로필 속성

connection.profile.newwizard = HSQLDB
connection.profile.newwizard.description = HSQLDB 연결 프로필을 생성합니다.
