DRIVER_CLASS_PROPERTY_NAME=Treiberklasse
VENDOR_PROPERTY_NAME=Anbieter
VERSION_PROPERTY_NAME=Version
DATABASE_NAME_PROPERTY_NAME=Datenbankname
CONNECTION_URL_PROPERTY_NAME=Verbindungs-URL
USER_ID_PROPERTY_NAME=Benutzer-ID
PASSWORD_PROPERTY_NAME=Kennwort

Bundle-Vendor = Eclipse Data Tools Platform
Bundle-Name = Eclipse Data Tools Platform HSQLDB UI Enablement Plug-in
profile.page.name = HSQLDB Profileigenschaften

connection.profile.newwizard = HSQLDB
connection.profile.newwizard.description = Erstellen Sie ein HSQLDB-Verbindungsprofil.
